### ISSUE TITLE
Cypress run fails with status code 9 - Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by candril** [cypress-io/cypress#1166]
- Operating System:
Windows 10 Enterprise, Version 1703
- Cypress Version:
1.4.1
- Browser Version:
Chrome 63

### Is this a Feature or Bug?
BUG

### Current behavior:
It logs in the console when executing `cypress run`
> (node:15630) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

And then fails with status code 9. See full log below.

This happens when it's run as a build step in VSTS on a local Windows build agent.

On my dev machine (macOS High Sierra, 10.13.1) I get the same warning about the EventEmitter memory leak, but the tests run successfully.

### Additional Info (images, stack traces, etc)
Full log:
```
2018-01-08T10:53:48.8992035Z > <project>@0.1.0 cypress:run C:\agents\alpha\_work\r1\a\<repo>#develop
2018-01-08T10:53:48.8992035Z > cypress run "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"
2018-01-08T10:53:48.8992035Z 
2018-01-08T10:53:49.6598077Z It looks like this is your first time using Cypress: 1.4.1
2018-01-08T10:53:49.6608066Z 
2018-01-08T10:53:49.6728167Z [?25l[11:53:49]  Verifying Cypress can run C:\agents\alpha\_work\r1\a\<repo>#develop\node_modules\cypress\dist\Cypress [started]
2018-01-08T10:53:51.6613928Z [11:53:51]  Verifying Cypress can run C:\agents\alpha\_work\r1\a\<repo>#develop\node_modules\cypress\dist\Cypress [completed]
2018-01-08T10:53:51.6613928Z [?25h
2018-01-08T10:53:51.6613928Z Opening Cypress...
2018-01-08T10:53:51.7164366Z 
2018-01-08T10:54:03.4659214Z   (Tests Starting)
2018-01-08T10:54:08.1276388Z (node:19340) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
2018-01-08T10:54:18.3747570Z 
2018-01-08T10:54:18.3747570Z   (Tests Finished)
2018-01-08T10:54:18.3747570Z 
2018-01-08T10:54:18.3757580Z   - Tests:           0
2018-01-08T10:54:18.3757580Z   - Passes:          0
2018-01-08T10:54:18.3757580Z   - Failures:        9
2018-01-08T10:54:18.3757580Z   - Pending:         0
2018-01-08T10:54:18.3757580Z   - Duration:        9 seconds
2018-01-08T10:54:18.3757580Z   - Screenshots:     0
2018-01-08T10:54:18.3757580Z   - Video Recorded:  false
2018-01-08T10:54:18.3757580Z   - Cypress Version: 1.4.1
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4307994Z   (All Done)
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4788395Z [?25hnpm ERR! code ELIFECYCLE
2018-01-08T10:54:18.4788395Z npm ERR! errno 9
2018-01-08T10:54:18.4788395Z npm ERR! <project>@0.1.0 cypress:run: `cypress run "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"`
2018-01-08T10:54:18.4788395Z npm ERR! Exit status 9
2018-01-08T10:54:18.4788395Z npm ERR! 
2018-01-08T10:54:18.4788395Z npm ERR! Failed at the <project>@0.1.0 cypress:run script.
2018-01-08T10:54:18.4788395Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-01-08T10:54:18.4788395Z 
2018-01-08T10:54:18.4788395Z npm ERR! A complete log of this run can be found in:
2018-01-08T10:54:18.4788395Z npm ERR!     C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\npm-cache\_logs\2018-01-08T10_54_18_472Z-debug.log
2018-01-08T10:54:18.4998568Z Found npm debug log, make sure the path matches with the one in npm's output: C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\npm-cache\_logs\2018-01-08T10_54_18_472Z-debug.log
2018-01-08T10:54:18.5068608Z 0 info it worked if it ends with ok
2018-01-08T10:54:18.5068608Z 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
2018-01-08T10:54:18.5068608Z 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
2018-01-08T10:54:18.5068608Z 1 verbose cli   'run',
2018-01-08T10:54:18.5068608Z 1 verbose cli   'cypress:run',
2018-01-08T10:54:18.5068608Z 1 verbose cli   '--',
2018-01-08T10:54:18.5068608Z 1 verbose cli   '--reporter',
2018-01-08T10:54:18.5068608Z 1 verbose cli   'junit',
2018-01-08T10:54:18.5068608Z 1 verbose cli   '--reporter-options',
2018-01-08T10:54:18.5068608Z 1 verbose cli   'mochaFile=test-results.xml' ]
2018-01-08T10:54:18.5068608Z 2 info using npm@5.0.3
2018-01-08T10:54:18.5068608Z 3 info using node@v8.1.1
2018-01-08T10:54:18.5068608Z 4 verbose run-script [ 'precypress:run', 'cypress:run', 'postcypress:run' ]
2018-01-08T10:54:18.5068608Z 5 info lifecycle <project>@0.1.0~precypress:run: <project>@0.1.0
2018-01-08T10:54:18.5068608Z 6 verbose lifecycle <project>@0.1.0~precypress:run: unsafe-perm in lifecycle true
2018-01-08T10:54:18.5068608Z 7 verbose lifecycle <project>@0.1.0~precypress:run: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\agents\alpha\_work\r1\a\<repo>#develop\node_modules\.bin;C:\agents\alpha\externals\git\cmd;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Sublime Text 3;C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps;C:\agents\alpha\bin;C:\agents\alpha\bin
2018-01-08T10:54:18.5068608Z 8 verbose lifecycle <project>@0.1.0~precypress:run: CWD: C:\agents\alpha\_work\r1\a\<repo>#develop
2018-01-08T10:54:18.5068608Z 9 silly lifecycle <project>@0.1.0~precypress:run: Args: [ '/d /s /c', 'npm run cypress:prepare' ]
2018-01-08T10:54:18.5068608Z 10 silly lifecycle <project>@0.1.0~precypress:run: Returned: code: 0  signal: null
2018-01-08T10:54:18.5068608Z 11 info lifecycle <project>@0.1.0~cypress:run: <project>@0.1.0
2018-01-08T10:54:18.5068608Z 12 verbose lifecycle <project>@0.1.0~cypress:run: unsafe-perm in lifecycle true
2018-01-08T10:54:18.5068608Z 13 verbose lifecycle <project>@0.1.0~cypress:run: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\agents\alpha\_work\r1\a\<repo>#develop\node_modules\.bin;C:\agents\alpha\externals\git\cmd;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Sublime Text 3;C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\WindowsApps;C:\agents\alpha\bin;C:\agents\alpha\bin
2018-01-08T10:54:18.5078623Z 14 verbose lifecycle <project>@0.1.0~cypress:run: CWD: C:\agents\alpha\_work\r1\a\<repo>#develop
2018-01-08T10:54:18.5078623Z 15 silly lifecycle <project>@0.1.0~cypress:run: Args: [ '/d /s /c',
2018-01-08T10:54:18.5078623Z 15 silly lifecycle   'cypress run "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"' ]
2018-01-08T10:54:18.5078623Z 16 silly lifecycle <project>@0.1.0~cypress:run: Returned: code: 9  signal: null
2018-01-08T10:54:18.5078623Z 17 info lifecycle <project>@0.1.0~cypress:run: Failed to exec cypress:run script
2018-01-08T10:54:18.5078623Z 18 verbose stack Error: <project>@0.1.0 cypress:run: `cypress run "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"`
2018-01-08T10:54:18.5078623Z 18 verbose stack Exit status 9
2018-01-08T10:54:18.5078623Z 18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at emitTwo (events.js:125:13)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at EventEmitter.emit (events.js:213:7)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at emitTwo (events.js:125:13)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at ChildProcess.emit (events.js:213:7)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at maybeClose (internal/child_process.js:897:16)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
2018-01-08T10:54:18.5078623Z 19 verbose pkgid <project>@0.1.0
2018-01-08T10:54:18.5078623Z 20 verbose cwd C:\agents\alpha\_work\r1\a\<repo>#develop
2018-01-08T10:54:18.5078623Z 21 verbose Windows_NT 10.0.15063
2018-01-08T10:54:18.5078623Z 22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cypress:run" "--" "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"
2018-01-08T10:54:18.5078623Z 23 verbose node v8.1.1
2018-01-08T10:54:18.5078623Z 24 verbose npm  v5.0.3
2018-01-08T10:54:18.5078623Z 25 error code ELIFECYCLE
2018-01-08T10:54:18.5078623Z 26 error errno 9
2018-01-08T10:54:18.5078623Z 27 error <project>@0.1.0 cypress:run: `cypress run "--reporter" "junit" "--reporter-options" "mochaFile=test-results.xml"`
2018-01-08T10:54:18.5078623Z 27 error Exit status 9
2018-01-08T10:54:18.5078623Z 28 error Failed at the <project>@0.1.0 cypress:run script.
2018-01-08T10:54:18.5078623Z 28 error This is probably not a problem with npm. There is likely additional logging output above.
2018-01-08T10:54:18.5078623Z 29 verbose exit [ 9, true ]
```

**Comment by brian-mann** [comment]
Not seeing what the bug is here. The events emitter warning is a pretty standard thing in node - and my guess is that it's likely coming from the `junit` reporter. Swap that reporter out with something else  (or just use the default reporter) and see if you still get that warning. 

Regardless - it's just a warning, it's not going to have any effect on the way Cypress works.

As for your tests failing I have no idea - it looks like you've removed the failing tests from the output - but I would just look at the recorded video + screenshots for figuring out why it's failing on Windows and not on OSX. Probably related to a build process.

**Comment by candril** [comment]
Okay, thanks for your reply. I was assuming it has nothing to do with the tests itself, since in the stack trace it look like it's failing when spawning a new process:

```
2018-01-08T10:54:18.5078623Z 18 verbose stack Exit status 9
2018-01-08T10:54:18.5078623Z 18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at emitTwo (events.js:125:13)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at EventEmitter.emit (events.js:213:7)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at emitTwo (events.js:125:13)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at ChildProcess.emit (events.js:213:7)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at maybeClose (internal/child_process.js:897:16)
2018-01-08T10:54:18.5078623Z 18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```
Plus, it's not running any tests:

```
2018-01-08T10:53:51.6613928Z Opening Cypress...
2018-01-08T10:53:51.7164366Z 
2018-01-08T10:54:03.4659214Z   (Tests Starting)
2018-01-08T10:54:08.1276388Z (node:19340) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
2018-01-08T10:54:18.3747570Z 
2018-01-08T10:54:18.3747570Z   (Tests Finished)
2018-01-08T10:54:18.3747570Z 
2018-01-08T10:54:18.3757580Z   - Tests:           0
2018-01-08T10:54:18.3757580Z   - Passes:          0
2018-01-08T10:54:18.3757580Z   - Failures:        9
2018-01-08T10:54:18.3757580Z   - Pending:         0
2018-01-08T10:54:18.3757580Z   - Duration:        9 seconds
2018-01-08T10:54:18.3757580Z   - Screenshots:     0
2018-01-08T10:54:18.3757580Z   - Video Recorded:  false
2018-01-08T10:54:18.3757580Z   - Cypress Version: 1.4.1
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4307994Z   (All Done)
2018-01-08T10:54:18.4307994Z 
2018-01-08T10:54:18.4788395Z �[?25hnpm ERR! code ELIFECYCLE
....
```

That's why I was assuming cypress failed to run any tests.

I will try with a different reporter and post the result here.

**Comment by brian-mann** [comment]
The stack trace is coming from `npm` because Cypress exited with a non zero status code. You always get this whenever `npm` exits any command with non zero status code. It actually has nothing to do with Cypress.

**Comment by candril** [comment]
After removing the jUnit reporter, I've seen the actual errors in the log, which were indeed comming from a before each hook.
So this can be closes, since it's not related to cypress. 
Thanks for your help!

**Comment by JakubKubista** [comment]
@jennifer-shehane 
Is this related to issue https://github.com/cypress-io/cypress/issues/1305?

If yes - I couldn't solve it via: https://github.com/Bkucera/cypress-plugin-retries

Is possible to solve this issue via following approach, please?
https://www.stefanjudis.com/today-i-learned/nodejs-sends-warnings-when-you-add-too-many-listeners-to-an-event-emitter/

I tried to solve it like that in my project, but I'm afraid that it is in Cypress itself.

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

If you have a question, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
