### ISSUE TITLE
cy.request failures are not obvious

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#134]
When `cy.request` fails we get a stack trace that looks like this:

```bash
2) Todo MVC "before each" hook:
     CypressError: Error: connect ECONNREFUSED 127.0.0.1:9002
      at Object.$Cypress.Utils._.cypressError (http://localhost:2020/__cypress/static/js/cypress.js:4377:15)
      at $Cypress.Cy.extend.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:5027:31)
      at $Cypress.Cy.extend.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:5032:22)
      at http://localhost:2020/__cypress/static/js/cypress.js:9092:21
      at i (http://localhost:2020/__cypress/static/js/vendor.js:588:27)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:587:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:587:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:587:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:586:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:586:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:586:1186)
```

We should at explain that it was caused by the `cy.request` and additionally print out request data and/or response data as a nicely formatted (truncated) object.

This will help users debug `cy.request` failures.

**Comment by chrisbreiding** [comment]
Fixed in upcoming `0.16.0`.

**Comment by chrisbreiding** [comment]
In the browser:
![Browser Error](https://cloud.githubusercontent.com/assets/1157043/15151921/51e41344-16a1-11e6-91d2-75917091b37d.png)

In the terminal:
![Terminal Error](https://cloud.githubusercontent.com/assets/1157043/15151922/51e7b47c-16a1-11e6-9896-b3bfad0c7bfc.png)
