### ISSUE TITLE
Unexpected `URIError` for proxied request

### ISSUE THREAD

**Issue by OliverJAsh** [cypress-io/cypress#14228]
### Current behavior

If I run `fetch('/%')` in my tests, the proxy returns an error.

```
URIError: Failed to decode param '/%'
    at decodeURIComponent (<anonymous>:null:null)
    at decode_param (/Users/oliverash/Library/Caches/Cypress/6.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/oliverash/Library/Caches/Cypress/6.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/oliverash/Library/Caches/Cypress/6.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/oliverash/Library/Caches/Cypress/6.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/router/index.js:220:15)
```

(stack trace truncated)

### Desired behavior

If I run `fetch('/%')` in my tests, the proxy should forward the request to my server so it can handle the request itself.

For context, I am trying to write a test that ensures my server's error handler works correctly. However, I can't test this if the proxy does not allow the request to go through to my server.

### Test code to reproduce

https://github.com/OliverJAsh/cypress-uri-error-test

`index.js`:
```js
const express = require("express");

const app = express();

app.get("*", (req, res) => {
  res.send("foo");
});

// error handling middleware
app.use((error, req, res, next) => {
  res.send("my custom error page");
});

app.listen(3000);
```

`cypress/integration/server.test.js`:
```js
describe("server", () => {
  it("handles errors", async () => {
    const responseTextPromise = fetch("/%").then((res) => res.text());

    expect(await responseTextPromise).to.equal("my custom error page");
  });
});
```

This test assertion fails because the request does not go through to my server. The proxy responds with an error.

### Versions

Cypress v6.1.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

Confirmed that the given example shows the failure. 

When index.js is run indenpendently and visit `localhost:3000/%`, it shows `my custom error page` correctly. But with Cypress, there's an error.

**Comment by intellix** [comment]
I'm also getting this error spam my tests.. I think due to an intercept and an image with percentages in the URL?

```
URIError: Failed to decode param '/dev/1x1%20-%20Icon%20-%20Bonus%20-%20100%%20-%20ALL.svg'
    at decodeURIComponent (<anonymous>:null:null)
    at decode_param (/Users/Dom/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/router/layer.js:172:12)
    ...
```
