### ISSUE TITLE
Unable to add cypress on an existing project in Windows 10

### ISSUE THREAD

**Issue by shreyaj-5** [cypress-io/cypress#14280]
Unable to install cypress on an existing react project on Windows 10 machine. Here is the error:

```
> cypress@6.2.0 postinstall C:\Users\ShreyaJ\Desktop\generic-user-portal\node_modules\cypress
> node index.js --exec install

C:\Users\ShreyaJ\Desktop\generic-user-portal\node_modules\cypress\node_modules\fs-extra\lib\mkdirs\make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ShreyaJ\Desktop\generic-user-portal\node_modules\cypress\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:49


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@6.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ShreyaJ\AppData\Roaming\npm-cache\_logs\2020-12-22T20_41_20_421Z-debug.log
```
Any help would be appreciated. Able to install cypress in a fresh new project on the same machine.

**Comment by bahmutov** [comment]
What’s the Node version on your machine? Check the minimum Node version required

**Comment by shreyaj-5** [comment]
Node v12.18.3 
NPM v6.14.6

**Comment by jennifer-shehane** [comment]
Yah, this does look like the error you would generally see if you have a version of Node that's not supported by us. But our min version is v10 still, so 12.18.3 should be fine. 

Seems identical to this issue, which says to upgrade above Node.js 10. https://github.com/google/docsy/issues/265

**Comment by lcaparros** [comment]
I had the same problem and have just fixed it just checking not only Node version, but also the modules use fs-extra. For example, in my case, I am using Node 14.16.1 and some modules were getting fs-extra 9.1.0. However, I was using Cypress 3.4.1 and latest version is 7.1.0. After upgrade it works like a charm.

Hope to help you!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by Vetnametz** [comment]
`> cypress@7.7.0 postinstall /.../node_modules/cypress
> node index.js --exec install

/.../node_modules/is-installed-globally/index.js:12
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../node_modules/cypress/lib/util.js:43:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@7.7.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@7.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by shuklanitesh1** [comment]
Hi,

I am also receiving the same error while installing the Cypress
node --version
v14.17.6
npm --version
6.14.15
`PS C:\Users\User\Desktop\Cypress_POM_Project> npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> cypress@9.1.0 postinstall C:\Users\User\Desktop\Cypress_POM_Project\node_modules\cypress
> node index.js --exec install

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\@cypress\request\lib\har.js
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\@cypress\request\request.js
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\@cypress\request\index.js
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\cypress\lib\tasks\download.js
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\cypress\lib\tasks\install.js
- C:\Users\User\Desktop\Cypress_POM_Project\node_modules\cypress\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\User\Desktop\Cypress_POM_Project\node_modules\@cypress\request\lib\har.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\User\Desktop\Cypress_POM_Project\node_modules\@cypress\request\request.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\@cypress\\request\\lib\\har.js',
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\@cypress\\request\\request.js',
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\@cypress\\request\\index.js',
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\cypress\\lib\\tasks\\download.js',
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\cypress\\lib\\tasks\\install.js',
    'C:\\Users\\User\\Desktop\\Cypress_POM_Project\\node_modules\\cypress\\index.js'
  ]
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN cypresslearning@1.0.0 No description
npm WARN cypresslearning@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@9.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@9.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-11-25T02_33_56_077Z-debug.log`

**Comment by karthikakn123** [comment]
i am getting similar error while running cypress
node
v14.18.1
npm 
6.14.15

**Comment by rajendran-k** [comment]
Same error with npm: '6.14.13',  node: '14.17.0',
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> cypress@9.1.0 postinstall C:\stash\UI-Integration-Tests\node_modules\cypress
> node index.js --exec install

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- C:\stash\UI-Integration-Tests\node_modules\@cypress\request\lib\har.js
- C:\stash\UI-Integration-Tests\node_modules\@cypress\request\request.js
- C:\stash\UI-Integration-Tests\node_modules\@cypress\request\index.js
- C:\stash\UI-Integration-Tests\node_modules\cypress\lib\tasks\download.js
- C:\stash\UI-Integration-Tests\node_modules\cypress\lib\tasks\install.js
- C:\stash\UI-Integration-Tests\node_modules\cypress\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\stash\UI-Integration-Tests\node_modules\@cypress\request\lib\har.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\stash\UI-Integration-Tests\node_modules\@cypress\request\request.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\stash\\UI-Integration-Tests\\node_modules\\@cypress\\request\\lib\\har.js',
    'C:\\stash\\UI-Integration-Tests\\node_modules\\@cypress\\request\\request.js',
    'C:\\stash\\UI-Integration-Tests\\node_modules\\@cypress\\request\\index.js',
    'C:\\stash\\UI-Integration-Tests\\node_modules\\cypress\\lib\\tasks\\download.js',
    'C:\\stash\\UI-Integration-Tests\\node_modules\\cypress\\lib\\tasks\\install.js',
    'C:\\stash\\UI-Integration-Tests\\node_modules\\cypress\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@9.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@9.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by hamzaable** [comment]
Same error

**Comment by adi0709** [comment]
Facing the same issue.

**Comment by lebraz1998** [comment]
i have same error 
i have been upgrade node to 16.x.x but still get error :
cypress@9.1.0 postinstall: `node index.js --exec install

**Comment by IlCallo** [comment]
Same
- Windows 10
- Node 12.22.7
- Yarn 1.22.15
- Cypress 8.7

**Comment by barbzrona** [comment]
same error

**Comment by Medmj** [comment]
Hello, same error here with node v14.19.3 and npm v6.14.17.

**Comment by azelaya6** [comment]
why was this closed, is there an fix?
