### ISSUE TITLE
Trying to install and run cypress on AWS lambda

### ISSUE THREAD

**Issue by sridhar562345** [cypress-io/cypress#14286]
I am trying to run cypress on AWS lambda but getting the following issue for the past two days. I am using new feature of Lambda where we can deploy container images on AWS lambda. If anyone had success trying this thing, please guide me. Thank you in advance
```
START RequestId: c5aaf6e1-7e3a-4c5a-86ef-6356e732d372 Version: $LATEST

> cypress-testing@1.0.0 test /tmp
> cypress run

It looks like this is your first time using Cypress: 6.2.0

[04:23:23]  Verifying Cypress can run /home/sbx_user1051/.cache/Cypress/6.2.0/Cypress [started]
[04:23:49]  Verifying Cypress can run /home/sbx_user1051/.cache/Cypress/6.2.0/Cypress [failed]
[04:23:49] → Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

prctl(PR_SET_NO_NEW_PRIVS) failed
prctl(PR_SET_NO_NEW_PRIVS) failed
[44:1223/042334.667345:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space in temporary directory for shared memory files: 0
prctl(PR_SET_NO_NEW_PRIVS) failed
prctl(PR_SET_NO_NEW_PRIVS) failed
[59:1223/042346.161282:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
[44:1223/042347.754979:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[44:1223/042348.988289:ERROR:platform_shared_memory_region_posix.cc(250)] Creating shared memory in /dev/shm/.org.chromium.Chromium.UOLE7c failed: No such file or directory (2)
[44:1223/042348.988340:ERROR:platform_shared_memory_region_posix.cc(253)] Unable to access(W_OK|X_OK) /dev/shm: No such file or directory (2)
[44:1223/042348.988346:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.

----------

Platform: linux (Amazon Linux - 2 (Karoo))
Cypress Version: 6.2.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

prctl(PR_SET_NO_NEW_PRIVS) failed
prctl(PR_SET_NO_NEW_PRIVS) failed
[44:1223/042334.667345:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space in temporary directory for shared memory files: 0
prctl(PR_SET_NO_NEW_PRIVS) failed
prctl(PR_SET_NO_NEW_PRIVS) failed
[59:1223/042346.161282:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
[44:1223/042347.754979:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[44:1223/042348.988289:ERROR:platform_shared_memory_region_posix.cc(250)] Creating shared memory in /dev/shm/.org.chromium.Chromium.UOLE7c failed: No such file or directory (2)
[44:1223/042348.988340:ERROR:platform_shared_memory_region_posix.cc(253)] Unable to access(W_OK|X_OK) /dev/shm: No such file or directory (2)
[44:1223/042348.988346:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.

----------

Platform: linux (Amazon Linux - 2 (Karoo))
Cypress Version: 6.2.0
npm ERR! Test failed.  See above for more details.
2020-12-23T04:23:49.120Z	c5aaf6e1-7e3a-4c5a-86ef-6356e732d372	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Command failed: cd /tmp && npm test","status":1,"signal":null,"output":[null,null,null],"pid":20,"stdout":null,"stderr":null,"stack":["Error: Command failed: cd /tmp && npm test","    at checkExecSyncError (child_process.js:635:11)","    at Object.execSync (child_process.js:671:15)","    at Runtime.exports.handler (/home/workspace/index.js:13:19)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: c5aaf6e1-7e3a-4c5a-86ef-6356e732d372
REPORT RequestId: c5aaf6e1-7e3a-4c5a-86ef-6356e732d372	Duration: 30081.88 ms	Billed Duration: 34616 ms	Memory Size: 3008 MB	Max Memory Used: 581 MB	Init Duration: 4534.03 ms	
```

**Comment by jennifer-shehane** [comment]
Please see this thread https://github.com/cypress-io/cypress/issues/1232

You may also want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

**Comment by manv6** [comment]
@sridhar562345 did you make it work ?

**Comment by sridhar562345** [comment]
@manv6 no, I couldn't make it work.
