### ISSUE TITLE
Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by KrzysztofMadejski** [cypress-io/cypress#14359]
### Current behavior

Test:
```js
cy.wrap(undefined).should('have.value', 'somevalue')
```

Response:
```
Cannot read property 'tagName' of undefined
    at getTagName (http://localhost:3000/__cypress/runner/cypress_runner.js:179108:23)
    at Module.isValueNumberTypeElement (http://localhost:3000/__cypress/runner/cypress_runner.js:179091:36)
    at Proxy.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:168429:21)
    at Proxy.methodWrapper (http://localhost:3000/__cypress/runner/cypress_runner.js:80820:26)
    at applyChainer (http://localhost:3000/__cypress/runner/cypress_runner.js:154697:33)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:154751:17)
    at arrayReduce (http://localhost:3000/__cypress/runner/cypress_runner.js:25424:22)
    at Function.reduce (http://localhost:3000/__cypress/runner/cypress_runner.js:34448:15)
    at applyChainers (http://localhost:3000/__cypress/runner/cypress_runner.js:154728:25)
From previous event:
    at Context.shouldFn (http://localhost:3000/__cypress/runner/cypress_runner.js:154757:24)
    at Context.should (http://localhost:3000/__cypress/runner/cypress_runner.js:154775:24)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:150480:40)
    at assertions (http://localhost:3000/__cypress/runner/cypress_runner.js:150732:15)
From previous event:
    at $Cy.verifyUpcomingAssertions (http://localhost:3000/__cypress/runner/cypress_runner.js:150747:21)
    at resolveWrap (http://localhost:3000/__cypress/runner/cypress_runner.js:156832:22)
    at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:165754:22)
    at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:165792:13)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:165287:17)
```

### Desired behavior
Should print sth around "expected undefined to be somevalue"

### Test code to reproduce
```
cy.wrap(undefined).should('have.value', 'somevalue')
```

### Versions

6.2.0

**Comment by jennifer-shehane** [comment]
The `value` chainer comes from Chai JQuery and expects a DOM object to assert on. 

This began showing the incorrect error in 4.9.0, likely with this PR https://github.com/cypress-io/cypress/pull/7621, which added additional checks around `value` assertions. cc @sainthkh 

### Reproducible

```js
it('assertion', () => {
  cy.wrap(undefined).should('have.value', 'somevalue')
})
```

### 4.8.0

<img width="655" alt="Screen Shot 2021-01-04 at 4 43 46 PM" src="https://user-images.githubusercontent.com/1271364/103524519-18106080-4eac-11eb-9ab8-4d98b1ccb49a.png">

### 4.9.0 


<img width="530" alt="Screen Shot 2021-01-04 at 4 46 33 PM" src="https://user-images.githubusercontent.com/1271364/103524717-6cb3db80-4eac-11eb-88fe-6a09025228fd.png">


### Workaround

Don't use Chai JQuery assertions on non DOM objects

```js
cy.wrap(undefined).should('eq', 'somevalue')
```
