### ISSUE TITLE
"Error: incorrect header check" Cypress 6.2.1

### ISSUE THREAD

**Issue by marcmyers** [cypress-io/cypress#14540]
I made a request using Cypress 6.3.0 and received an error.

I can make this same request using Postman or curl with no issues.

### Current behavior
I make a request and receive the following error:
Error: incorrect header check

![image](https://user-images.githubusercontent.com/5490442/104497139-e718e580-55a7-11eb-954d-cb4401765cdc.png)

### Desired behavior
200 OK should be returned as a response

### Test code to reproduce
`cy.request('https://www.cmmiinstitute.com/');
`
### Versions
Cypress 6.3.0
Windows 10 Enterprise

**Comment by marcmyers** [comment]
Here's the stack trace in case that's helpful. This causes to be blocked using cypress for any api testing as we need to scrape the viewstate and token off of the page to make any other requests.
```
From Node.js Internals:
    RequestError: Error: incorrect header check
      at new RequestError (C:\Users\mmyers\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:16)
      at Request.plumbing.callback (C:\Users\mmyers\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:30)
      at Request.RP$callback [as _callback] (C:\Users\mmyers\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:32)
      at self.callback (C:\Users\mmyers\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:185:23)
      at Request.emit (events.js:223:6)
      at Inflate.<anonymous> (C:\Users\mmyers\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1081:13)
      at Inflate.emit (events.js:228:8)
      at Zlib.zlibOnError [as onerror] (zlib.js:173:9)
```

**Comment by marcmyers** [comment]
Upgraded to 6.3.0, same issue but slightly different stack trace:
```
From Node.js Internals:
    RequestError: Error: incorrect header check
      at new RequestError (C:\Users\mmyers\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:16)
      at Request.plumbing.callback (C:\Users\mmyers\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:30)
      at Request.RP$callback [as _callback] (C:\Users\mmyers\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:32)
      at self.callback (C:\Users\mmyers\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:185:23)
      at Request.emit (events.js:315:21)
      at Inflate.<anonymous> (C:\Users\mmyers\AppData\Local\Cypress\Cache\6.3.0\Cypress\resources\app\packages\server\node_modules\@cypress\request\request.js:1081:13)
      at Inflate.emit (events.js:327:23)
      at Zlib.zlibOnError [as onerror] (zlib.js:183:9)
```

**Comment by bahmutov** [comment]
Can we have a reproducible example to debug this?

**Comment by marcmyers** [comment]
> Can we have a reproducible example to debug this?

Thanks for the comment. I created a repo here. After installing dependencies, npx cypress run and you'll see the exception: https://github.com/marcmyers/incorrect-header-example

**Comment by bahmutov** [comment]
Running with `NODE_DEBUG=request npx cypress open`

does not show anything suspicious
```
REQUEST {
  agent: CombinedAgent {
    familyCache: { 'download.cypress.io': 4 },
    httpAgent: HttpAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      httpsAgent: [Agent],
      [Symbol(kCapture)]: false
    },
    httpsAgent: HttpsAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    }
  },
  headers: {
    Connection: 'keep-alive',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.3.0 Chrome/87.0.4280.141 Electron/11.2.0 Safari/537.36',
    accept: '*/*'
  },
  proxy: null,
  url: 'https://cmmiinstitute.com/',
  method: 'GET',
  encoding: 'utf8',
  gzip: true,
  timeout: 30000,
  followRedirect: [Function],
  failOnStatusCode: true,
  retryOnNetworkFailure: true,
  retryOnStatusCodeFailure: false,
  cookies: true,
  strictSSL: false,
  simple: false,
  resolveWithFullResponse: true,
  followAllRedirects: true,
  requestId: 'request4',
  retryIntervals: [ 0, 1000, 2000, 2000 ],
  delaysRemaining: [ 0, 1000, 2000, 2000 ],
  callback: [Function: RP$callback],
  transform: undefined,
  transform2xxOnly: false
}
REQUEST make request https://cmmiinstitute.com/
REQUEST onRequestResponse https://cmmiinstitute.com/ 200 {
  'cache-control': 'no-cache, no-store, must-revalidate',
  pragma: 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'text/html; charset=utf-8',
  'content-encoding': 'deflate',
  expires: '-1',
  vary: 'Accept-Encoding',
  server: 'Microsoft-IIS/10.0',
  'set-cookie': [
    'CMSPreferredCulture=en-US; expires=Sat, 22-Jan-2022 02:57:13 GMT; path=/; secure; HttpOnly',
    'CMSCsrfCookie=ioKc84koqBZivsHnGNAV82rGU4Hjg6midC12HObA; path=/; secure; HttpOnly',
    'ASP.NET_SessionId=azqterzn1hd0man0xvgqcoev; path=/; secure; HttpOnly; SameSite=Lax',
    'CMSCurrentTheme=CMMI-Styles; expires=Sat, 23-Jan-2021 02:57:13 GMT; path=/; secure; HttpOnly',
    'ARRAffinity=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;Secure;Domain=cmmiinstitute.com',
    'ARRAffinitySameSite=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;SameSite=None;Secure;Domain=cmmiinstitute.com'
  ],
  'x-frame-options': 'SAMEORIGIN, SAMEORIGIN',
  'x-ua-compatible': 'IE=Edge',
  'x-aspnet-version': '4.0.30319',
  'request-context': 'appId=cid-v1:72d07bf2-269a-42b9-b9ab-edc94538858e',
  'access-control-expose-headers': 'Request-Context',
  'x-powered-by': 'ASP.NET',
  date: 'Fri, 22 Jan 2021 02:57:13 GMT'
}
REQUEST reading response's body
REQUEST finish init function https://cmmiinstitute.com/
```

**Comment by bahmutov** [comment]
Just using https://github.com/cypress-io/request
shows now errors
```js
// get.js
const request = require('@cypress/request');
request('https://cmmiinstitute.com/', function (error, response, body) {
  console.error('error:', error); // Print the error if one occurred
  console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
  // console.log('body:', body); // Print the HTML for the Google homepage.
});
```

```
$ node ./get
error: null
statusCode: 200
```

**Comment by bahmutov** [comment]
Interesting - the server returns different headers (deflate vs none) depending on the client

Using httpie
```
$ http https://cmmiinstitute.com/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Request-Context
Cache-Control: no-cache, no-store, must-revalidate
Content-Encoding: deflate
Content-Length: 7868
Content-Type: text/html; charset=utf-8
Date: Fri, 22 Jan 2021 03:16:32 GMT
Expires: -1
Pragma: no-cache
Request-Context: appId=cid-v1:72d07bf2-269a-42b9-b9ab-edc94538858e
Server: Microsoft-IIS/10.0
Set-Cookie: CMSPreferredCulture=en-US; expires=Sat, 22-Jan-2022 03:16:32 GMT; path=/; secure; HttpOnly
Set-Cookie: CMSCsrfCookie=pEwGkEO4oPFSksgtJEE8498TzmKJ0NuLaM7ZrM0r; path=/; secure; HttpOnly
Set-Cookie: ASP.NET_SessionId=5mpuvnt1h0qcwzxdj2nkdcjh; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: CMSCurrentTheme=CMMI-Styles; expires=Sat, 23-Jan-2021 03:16:32 GMT; path=/; secure; HttpOnly
Set-Cookie: ARRAffinity=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;Secure;Domain=cmmiinstitute.com
Set-Cookie: ARRAffinitySameSite=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;SameSite=None;Secure;Domain=cmmiinstitute.com
Vary: Accept-Encoding
X-AspNet-Version: 4.0.30319
X-FRAME-OPTIONS: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
X-Powered-By: ASP.NET
X-UA-Compatible: IE=Edge
```

Notice

```
Content-Encoding: deflate
Content-Length: 7868
```

Using curl

```
$ curl -I https://cmmiinstitute.com/
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Length: 21812
Content-Type: text/html; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
Set-Cookie: CMSPreferredCulture=en-US; expires=Sat, 22-Jan-2022 03:16:00 GMT; path=/; secure; HttpOnly
Set-Cookie: CMSCsrfCookie=BMCeL20tBZgEC7+04vjcFN49rvOvhY+txO/Vkd5O; path=/; secure; HttpOnly
Set-Cookie: ASP.NET_SessionId=53rpbuxwyqp0roravfix23qo; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: CMSCurrentTheme=CMMI-Styles; expires=Sat, 23-Jan-2021 03:16:00 GMT; path=/; secure; HttpOnly
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=Edge
X-AspNet-Version: 4.0.30319
Request-Context: appId=cid-v1:72d07bf2-269a-42b9-b9ab-edc94538858e
Access-Control-Expose-Headers: Request-Context
X-Powered-By: ASP.NET
X-FRAME-OPTIONS: SAMEORIGIN
Set-Cookie: ARRAffinity=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;Secure;Domain=cmmiinstitute.com
Set-Cookie: ARRAffinitySameSite=4fe8d51f56fadd33f6feed576117e27caa04e6c6da553f8349f3cbceb8f687fd;Path=/;HttpOnly;SameSite=None;Secure;Domain=cmmiinstitute.com
Date: Fri, 22 Jan 2021 03:15:59 GMT
```

Notice 

```
Content-Length: 21812
```
and no deflate. 

When using `cy.request` we are getting

```
REQUEST response end https://cmmiinstitute.com/ 200 {
  'cache-control': 'no-cache, no-store, must-revalidate',
  pragma: 'no-cache',
  'content-length': '8578',
  'content-type': 'text/html; charset=utf-8',
  'content-encoding': 'deflate'
```

If the content-length is incorrect the zlib decompression fails, as others have noted in https://github.com/axios/axios/issues/2406 for the error "incorrect header check". This error in our stack does come from zlib deflate

```
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

**Comment by bahmutov** [comment]
Since the problem seems to be in gzipped response, let's disable gzip using https://on.cypress.io/request options

```js
/// <reference types="cypress" />
describe('Cypress Request to our page', () => {
  it('causes an incorrect header check exception to be thrown', () => {
    // https://on.cypress.io/request
    cy.request({
      url: 'https://cmmiinstitute.com/',
      gzip: false
    });
  });
});
```

Working!

## Final solution

If `cy.request` is getting error "incorrect header check" use `gzip: true` option

**Comment by marcmyers** [comment]
@bahmutov Thank you so much for looking into this.

**Comment by nateroling** [comment]
We keep running into this issue as we write new tests and commands. Is there a way to set `gzip: false` globally by default?
