### ISSUE TITLE
process.binding is not supported error

### ISSUE THREAD

**Issue by senthiltr** [cypress-io/cypress#14569]
Getting "process.binding is not supported" error in cypress when I use call the modules which is created using node modules(third party).
cypress_runner.js:200035 Error: The following error originated from your test code, not from Cypress.

  > process.binding is not supported

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at Object.C:\Users\skrajan\AppData\Local\Cypress\Cache\6.2.0\Cypress\resources\app\packages\server\node_modules\process\browser.js.process.binding (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:70179:11)
    at Object.eval (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:5759:247)
    at Object../node_modules/node-netconf/node_modules/ssh2-streams/lib/sftp.js (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:8882:30)
    at __webpack_require__ (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:20:30)
    at Object../node_modules/node-netconf/node_modules/ssh2-streams/index.js (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:2347:15)
    at __webpack_require__ (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:20:30)
    at Object.eval (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:15638:20)
    at Object../node_modules/node-netconf/node_modules/ssh2/lib/client.js (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:17203:30)
    at __webpack_require__ (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:20:30)
    at Object../node_modules/node-netconf/lib/netconf.js (http://localhost:50170/__cypress/tests?p=cypress\user_test_suites\newtest.js:2017:13)
From previous event:
    at Object.runScripts (http://localhost:50170/__cypress/runner/cypress_runner.js:176504:96)
    at $Cypress.onSpecWindow (http://localhost:50170/__cypress/runner/cypress_runner.js:166461:18)
### Desired behavior

Should be able to call and get the result what the module is returning.
### Test code to reproduce

Test Code:
const get_netconf_data = require("../support/util/get_netconf_data")
//import get_netconf_data from './test-proto'
describe("New-Test", function(){

    it.only("Test1", ()=>{
        cy.log(get_netconf_data("inventory"))
    })
})

module code:- (inside support/util/)
var netconf = require("node-netconf");
var result;
var ne_creds = {
    host: '1.1.1.1',
    port: '1000',
    username: 'username',
    password: 'password'
}

module.exports = function(dataof="statistics"){
    
    const conn_obj = new netconf.Client(ne_creds)
    var connected;
    conn_obj.open((err)=>{
        if(err){
            throw err
        }
        connected = conn_obj.connected
        //console.log(typeof(connected))
        if(connected==true){
            console.log("true-1")
            conn_obj.rpc("get", function(err, reply){
                console.log("rpc:1")
                conn_obj.close()
                if(!err){
                    //console.log(reply)
                    result = reply.rpc_reply.data[dataof]
                    //console.log("result")
                    console.log(result)
                    //return result
                }
                else{
                    console.log("rpc:error")
                    throw err
                }
            })
        }
    })
    return result
}

### Versions
version:6.2.0

![error](https://user-images.githubusercontent.com/36333193/104629537-a2806d80-56bf-11eb-8679-acee5d890551.JPG)

**Comment by senthiltr** [comment]
HI Team,
I have created a new module and imported their the above exported module and executed using "node filepath". I am getting the expected result. But when i try to call that module from cypress testcase getting the above error. Kindly provide your comments.

**Comment by bahmutov** [comment]
Cypress spec files execute in the browser. Thus any modules with native Node bindings will not be bundled by the Webpack bundler. I suggest you place the code with native bindings into the plugin file and execute it by calling [cy.task](https://on.cypress.io/task) from your spec file.
