### ISSUE TITLE
Cypress crashes on trying to record with an empty key

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#14571]
Cypress v6.2.1

Cypress crashes if you pass an empty `--key` CLI parameter.

Reproduction steps:
- clone https://github.com/cypress-io/cypress-test-tiny/tree/key-example
- install dependencies `npm i`
- run Cypress in record mode with an empty key parameter, for example
```
DEBUG=cypress:* npx cypress run --record --key --parallel --ci-build-id bar
```

Crash
```
token.slice is not a function
TypeError: token.slice is not a function
    at Object.hide (/Users/gleb/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/util/keys.js:7:11)
    at /Users/gleb/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/record.js:406:26
```

Note: if you simply try

```
cypress run --record --key
```

The our CLI catches the empty parameter and shows a good message. You must follow `--key` by something else. Then it somehow evades our CLI argument checks. I can see in the crashing case

```
  cypress:cli spawning Cypress with executable: /Users/gleb/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/MacOS/Cypress +3ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '/Users/gleb/git/cypress-test-tiny', '--ci-build-id', 'bar', '--key', '--parallel', '--record', true, '--cwd', '/Users/gleb/git/cypress-test-tiny' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
```

## Why this matters

As we found with @estrada9166 if you pass an environment variable on CI that is undefined, it happily crashes

```
npx cypress run --record --key $KEY_DOES_NOT_EXIST --parallel
```

**Comment by bahmutov** [comment]
Funny that this crash happens when trying to print an error message when cannot record :)

**Comment by bahmutov** [comment]
Seems the `--key` by its presence gets cast as a boolean

```
  cypress:electron spawning /Users/gleb/git/cypress/packages/electron/dist/Cypress/Cypress.app/Contents/MacOS/Cypress with args [
  '--max-http-header-size=1048576',
  '--ciBuildId=bar',
  '--config={}',
  '--cwd=/Users/gleb/git/cypress/packages/server',
  '--key=true',
  '--parallel=true',
  '--record=true'
]
```
