### ISSUE TITLE
TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by rslemos** [cypress-io/cypress#14591]
When taking a snapshot, cypress fails with:
```
  1) Visual regression tests
       Should match previous screenshot
     TypeError: Cannot read property 'top' of undefined
      at scrollTo (<anonymous>:12:43)
```

I tried to ignore the error `TypeError: Cannot read property 'top' of undefined` using `cy.on('uncaught:exception', (e) => {...`, but I think this error is not thrown by the client application.

My spec only takes a snapshot of entire page and expect it to be equal to some previously saved snapshot.

I'm using [cypress-image-snapshot](https://github.com/jaredpalmer/cypress-image-snapshot), which adds the `matchImageSnapshot` command.

```
const ignore = [
  ...
  'TypeError: Cannot read property \'top\' of undefined',
];

describe('Visual regression tests', () => {
        it(`Should match previous screenshot`, () => {
          cy.on('uncaught:exception', (e) => {
            if (ignore.find(m => e.message.includes(m))) {
              return false;
            }
          });

          cy.setResolution([1200, 800]);
          cy.visit('project-url', { onBeforeLoad: window => {
            var style = window.document.createElement('style');
            style.append('.lgpdfooter, [vw-access-button] { display: none !important; }');
            window.document.head.append(style);
          }});
          cy.matchImageSnapshot();
        });
      });
    });
});
```

Though the exception spills from cypress code (or so I think), I'm pretty sure that there is something related to that particular application (I have 29 other pages which pass with exact the same spec)

Since this is a hard to reproduce bug, I'd like to ask how can I further debug this issue.

I could steadily reproduce this bug for this specific page in:
- Electron 87 (headless)
```
     TypeError: Cannot read property 'top' of undefined
      at scrollTo (<anonymous>:12:43)
```
- Electron 87 (headed)
```
TypeError
Cannot read property 'top' of undefined
View stack trace
    at scrollTo (undefined:12:44)
From previous event:
    at takeFullPageScreenshot (http://localhost:8082/__cypress/runner/cypress_runner.js:159283:83)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:159474:15)
From previous event:
    at takeScreenshot (http://localhost:8082/__cypress/runner/cypress_runner.js:159462:20)
    at Context.screenshot (http://localhost:8082/__cypress/runner/cypress_runner.js:159582:15)
    at Context.<anonymous> (http://localhost:8082/__cypress/runner/cypress_runner.js:170226:22)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:169650:16)
From previous event:
    at runCommand (http://localhost:8082/__cypress/runner/cypress_runner.js:169629:9)
    at next (http://localhost:8082/__cypress/runner/cypress_runner.js:169775:15)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:169803:17)
From previous event:
    at next (http://localhost:8082/__cypress/runner/cypress_runner.js:169775:35)
From previous event:
    at Promise.catch.err.name (http://localhost:8082/__cypress/runner/cypress_runner.js:169816:38)
From previous event:
    at run (http://localhost:8082/__cypress/runner/cypress_runner.js:169809:22)
    at $Cy.cy.<computed> [as setResolution] (http://localhost:8082/__cypress/runner/cypress_runner.js:170266:12)
    at Context.runnable.fn (http://localhost:8082/__cypress/runner/cypress_runner.js:170493:22)
    at callFn (http://localhost:8082/__cypress/runner/cypress_runner.js:104252:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8082/__cypress/runner/cypress_runner.js:104239:8)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:176051:29)
From previous event:
    at Object.onRunnableRun (http://localhost:8082/__cypress/runner/cypress_runner.js:176039:18)
    at $Cypress.action (http://localhost:8082/__cypress/runner/cypress_runner.js:166634:29)
    at Test.Runnable.run (http://localhost:8082/__cypress/runner/cypress_runner.js:174418:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:8082/__cypress/runner/cypress_runner.js:104911:11)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:105037:13)
    at next (http://localhost:8082/__cypress/runner/cypress_runner.js:104820:15)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:104830:8)
    at next (http://localhost:8082/__cypress/runner/cypress_runner.js:104732:15)
    at <unknown> (http://localhost:8082/__cypress/runner/cypress_runner.js:104798:6)
    at timeslice (http://localhost:8082/__cypress/runner/cypress_runner.js:98724:28)
```

I cannot test anything besides Electron because my coporation policy locks Chrome and Firefox settings for proxy.

----
Cypress: 6.2.1
OS: Windows 2010 Pro

**Comment by rslemos** [comment]
Nevermind. I just found this page actually defines a top level funcion `scrollTo`.
