### ISSUE TITLE
Strange behaviour with html class ui-button ui-corner-all ui-widget element, parent is hidden error

### ISSUE THREAD

**Issue by Nmb23** [cypress-io/cypress#14735]
Finds the button 
![image](https://user-images.githubusercontent.com/26368013/105734743-e169bb00-5f2a-11eb-9ed5-0bec454573bc.png)

Can't use click on that element
![image](https://user-images.githubusercontent.com/26368013/105734679-cac36400-5f2a-11eb-93cd-ca96b1a495c9.png)
``` 
at $Cy.ensureVisibility (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:161294:25)
    at runAllChecks (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:150169:15)
    at retryActionability (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:150223:17)
From previous event:
    at tryFn (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:165787:22)
    at whenStable (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:165825:13)
    at <unknown> (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:165320:17)
From previous event:
    at $Cy.retry (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:165300:39)
    at retryActionability (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:150226:20)
    at <unknown> (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:150228:8)
From previous event:
    at Object.verify (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:150139:22)
    at perform (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:152192:30)
From previous event:
    at mouseAction (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:152230:21)
    at Context.click (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:152249:15)
    at Context.<anonymous> (https://XYZ.co.uk/__cypress/runner/cypress_runner.js:170229:22)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/test_login.js:118:27)
```

Have tried forcing true on hidden - this doesn't work either 
![image](https://user-images.githubusercontent.com/26368013/105734991-1d9d1b80-5f2b-11eb-9b6c-a100275fe2ef.png)
& No Stack Trace

HTML element is child of flexboxlegacy item.

`js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths`

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example including some HTML + CSS with a failing Cypress test against it? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
