### ISSUE TITLE
@cypress/vue Errors thrown during mount are not handled by cy.on('oncaught:exception')

### ISSUE THREAD

**Issue by LolliDepp** [cypress-io/cypress#14782]
### Current behavior
Using `mount` from `@cypress/vue`, errors thrown during the execution of `mounted` on the component are not handled by cy.on('oncaught:exception') and cannot be caught.

The exception I get:
```
cypress_runner.js:200852 Error: ATabsPanel configuration error: tabsConfig array must contain at least one item
    at VueComponent.ATabsPanel.verifyTabsConfig (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:34678:13)
    at VueComponent.ATabsPanel.mounted (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:34673:10)
    at invokeWithErrorHandling (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:24310:57)
    at callHook (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:26670:7)
    at Object.insert (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:25593:7)
    at invokeInsertHook (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:28795:28)
    at VueComponent.patch [as __patch__] (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:29014:5)
    at VueComponent.Vue._update (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:26396:19)
    at VueComponent.updateComponent (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:26517:10)
    at Watcher.get (http://localhost:13716/__cypress/tests?p=cypress\unit\components\patterns\ATabsPanel.spec.tsx:26930:25)
From previous event:
    at Context.thenFn (http://localhost:13716/__cypress/runner/cypress_runner.js:155190:23)
    at Context.then (http://localhost:13716/__cypress/runner/cypress_runner.js:155629:21)
    at Context.<anonymous> (http://localhost:13716/__cypress/runner/cypress_runner.js:170229:21)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:169653:15
From previous event:
    at runCommand (http://localhost:13716/__cypress/runner/cypress_runner.js:169632:8)
    at next (http://localhost:13716/__cypress/runner/cypress_runner.js:169778:14)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:169806:16
From previous event:
    at next (http://localhost:13716/__cypress/runner/cypress_runner.js:169778:34)
From previous event:
    at Promise.catch.err.name (http://localhost:13716/__cypress/runner/cypress_runner.js:169819:37)
From previous event:
    at run (http://localhost:13716/__cypress/runner/cypress_runner.js:169812:21)
    at $Cy.cy.<computed> [as window] (http://localhost:13716/__cypress/runner/cypress_runner.js:170269:11)
    at Context.runnable.fn (http://localhost:13716/__cypress/runner/cypress_runner.js:170496:21)
    at callFn (http://localhost:13716/__cypress/runner/cypress_runner.js:104252:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:13716/__cypress/runner/cypress_runner.js:104239:7)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:176219:28
From previous event:
    at Object.onRunnableRun (http://localhost:13716/__cypress/runner/cypress_runner.js:176207:17)
    at $Cypress.action (http://localhost:13716/__cypress/runner/cypress_runner.js:166637:28)
    at Test.Runnable.run (http://localhost:13716/__cypress/runner/cypress_runner.js:174384:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:13716/__cypress/runner/cypress_runner.js:104911:10)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:105037:12
    at next (http://localhost:13716/__cypress/runner/cypress_runner.js:104820:14)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:104830:7
    at next (http://localhost:13716/__cypress/runner/cypress_runner.js:104732:14)
    at http://localhost:13716/__cypress/runner/cypress_runner.js:104798:5
    at timeslice (http://localhost:13716/__cypress/runner/cypress_runner.js:98724:27)
```

### Desired behavior

Uncaught exception event handlers should be triggered when the `mounted` function throws

### Test code to reproduce

This code was working in an older version, the idea was that I would catch an exception before the cypress timeout makes the last statement fail.

```ts
// my.spec.ts

it('throws', () => {
  const errorPromise = new Cypress.Promise(res => {
    cy.on('uncaught:exception', () => {
      res();
      return false;
    });
  });
  mount(AComponent, { propsData });
  cy.wrap(null).then(() => errorPromise);
})
```

```html
// AComponent.vue
<template>
  <p>{{ greeting }} World!</p>
</template>

<script>
export default {
  data() {
    return {
      greeting: 'Hello',
    }
  },
  mounted() {
    throw new Error('error while mounting');
  }
}
</script>
```

If you run this now, you'll get an error, the test will fail, and the error handler will not be triggered.

I managed to make my test work, but it looks like an hack since I need to handle the `fail` event instead:
```js
const noErrorMessage = 'No error was thrown';
cy.on('fail', error => {
  if (error.message === noErrorMessage) {
    throw error;
  }
});

mount(ATabsPanel, { propsData }).then(() => {
  assert.fail(noErrorMessage);
});
```

### Versions

With `cypress-vue-unit-tests` version 1.4.0 mount would trigger the "uncaught:exception" event - I'm now trying with `@cypress/vue` version 1.1.0-alpha.2 and it no longer works

**Comment by LolliDepp** [comment]
I wanted to add: with the previous version I was running this piece of code during initialisation:
```
Vue.config.errorHandler = err =>
  setTimeout(() => {
    throw err;
  });
```
It could be the error was getting handled as a cypress error due to this...

**Comment by LolliDepp** [comment]
Last update - it turns out I can just
```
expect(() => mount(AComponent)).to.throw;
```

still, it could be a bug that the error isn't triggering the `oncaught:exception` event...

But if you want to close this issue that would be fine
