### ISSUE TITLE
When running headlessly or in CI there is a TypeError

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#148]
When running Cypress headlessly or in CI there is a TypeError. This only happens in newly released version `0.16.0`.

**Error**
```
[TypeError: The header content contains invalid characters]
TypeError: The header content contains invalid characters
  at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
  at new ClientRequest (_http_client.js:85:14)
  at Object.exports.request (http.js:31:10)
  at Object.exports.request (https.js:196:15)
  at Request.start (/home/ubuntu/.cypress/Cypress/resources/app/node_modules/request/request.js:747:30)
  at Request.end (/home/ubuntu/.cypress/Cypress/resources/app/node_modules/request/request.js:1381:10)
  at end (/home/ubuntu/.cypress/Cypress/resources/app/node_modules/request/request.js:575:14)
  at Immediate._onImmediate (/home/ubuntu/.cypress/Cypress/resources/app/node_modules/request/request.js:589:7)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by brian-mann** [comment]
Fixed in [`0.16.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0161-05222016).
