### ISSUE TITLE
6.3.0 Crash on windows 10 

### ISSUE THREAD

**Issue by testtek** [cypress-io/cypress#14844]
I was trying to upgrade cypress locally from 6.2.1 to 6.3.0 but could able to run cypress 

It looks like this is your first time using Cypress: 6.3.0

  ×  Verifying Cypress can run C:\Users\sbantode\AppData\Local\Cypress\Cache\6.3.0\Cypress
    → Cypress Version: 6.3.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000724450F0E0
1: 00007FF628E44FDF node::Buffer::New+130911
2: 00007FF628B5D72A IsSandboxedProcess+752266
3: 00007FF626C3F408 v8::Isolate::Initialize+744
4: 00007FF628B6B410 uv_mutex_unlock+56032
5: 00007FF625F6C503 v8_inspector::V8InspectorClient::resourceNameToUrl+70643
6: 00007FF625F637EB v8_inspector::V8InspectorClient::resourceNameToUrl+34523
7: 00007FF6279AF852 uv_timer_set_repeat+2016162
8: 00007FF6279B3509 uv_timer_set_repeat+2031705
9: 00007FF6279AEEB2 uv_timer_set_repeat+2013698
10: 00007FF6278975B9 uv_timer_set_repeat+868617
11: 00007FF6278971CC uv_timer_set_repeat+867612
12: 00007FF626B33D34 v8::Location::GetColumnNumber+838772
13: 00007FF626B3405D v8::Location::GetColumnNumber+839581
14: 00007FF625E91506 Ordinal0+5382
15: 00007FF62C110002 uv_random+18543858
16: 00007FFC5E3A7BD4 BaseThreadInitThunk+20
17: 00007FFC5E78CED1 RtlUserThreadStart+33

----------

Platform: win32 (10.0.18362)
Cypress Version: 6.3.0
Error: Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000724450F0E0
1: 00007FF628E44FDF node::Buffer::New+130911
2: 00007FF628B5D72A IsSandboxedProcess+752266
3: 00007FF626C3F408 v8::Isolate::Initialize+744
4: 00007FF628B6B410 uv_mutex_unlock+56032
5: 00007FF625F6C503 v8_inspector::V8InspectorClient::resourceNameToUrl+70643
6: 00007FF625F637EB v8_inspector::V8InspectorClient::resourceNameToUrl+34523
7: 00007FF6279AF852 uv_timer_set_repeat+2016162
8: 00007FF6279B3509 uv_timer_set_repeat+2031705
9: 00007FF6279AEEB2 uv_timer_set_repeat+2013698
10: 00007FF6278975B9 uv_timer_set_repeat+868617
11: 00007FF6278971CC uv_timer_set_repeat+867612
12: 00007FF626B33D34 v8::Location::GetColumnNumber+838772
13: 00007FF626B3405D v8::Location::GetColumnNumber+839581
14: 00007FF625E91506 Ordinal0+5382
15: 00007FF62C110002 uv_random+18543858
16: 00007FFC5E3A7BD4 BaseThreadInitThunk+20
17: 00007FFC5E78CED1 RtlUserThreadStart+33

----------

Platform: win32 (10.0.18362)
Cypress Version: 6.3.0
    at C:\Code\Cypress\node_modules\cypress\lib\errors.js:332:17
    at tryCatcher (C:\Code\Cypress\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Code\Cypress\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Code\Cypress\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Code\Cypress\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Code\Cypress\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Code\Cypress\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Code\Cypress\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Code\Cypress\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Code\Cypress\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  known: true,
  context: [Object: null prototype] {}
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1

C:\Code\Cypress>npx cypress version
Cypress package version: 6.3.0
Cypress binary version: 6.3.0
Electron version: 11.2.0
Bundled Node version:
12.18.3

Any help in this regards would be appreciated?

**Comment by testtek** [comment]
restart windows machine after installation helped running cypress
