### ISSUE TITLE
Cannot read property 'show' of undefined when opening links in Command Log in Electron

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#14912]
### Current behavior

Starting in Cypress 6.4.0, Clicking the 'Learn more' link containing a docsUrl from within the Command Log of the Test Runner crashes when running tests in Electron browser.

```
(node:84685) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
TypeError: Cannot read property 'show' of undefined
    at Object._launch (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:193:17)
    at Object._launchChild (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:189:17)
    at BrowserWindow.onNewWindow (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:137:22)
    at Object.<anonymous> (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:192:36)
    at Object.emit (events.js:315:20)
    at Object.internalWindowOpen (electron/js2c/browser_init.js:181:2714)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:11014)
    at Object.emit (events.js:315:20)

TypeError: Cannot read property 'show' of undefined
    at Object._launch (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:193:17)
    at Object._launchChild (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:189:17)
    at BrowserWindow.onNewWindow (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:137:22)
    at Object.<anonymous> (/Users/jennifer/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:192:36)
    at Object.emit (events.js:315:20)
    at Object.internalWindowOpen (electron/js2c/browser_init.js:181:2714)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:11014)
    at Object.emit (events.js:315:20)
```

This is being thrown at this line of code: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/electron.js#L189:L189

### Test code to reproduce

```js
it('test', () => {
  cy.clock('250')
})
```

1. `cypress open` and select 'Electron' browser
2. Run test code above
3. Click 'Learn More' when the test fails

### Versions

Cypress 6.4.0

**Comment by jennifer-shehane** [comment]
This was introduced in this PR: https://github.com/cypress-io/cypress/pull/14749 The signature of the `_launch` function was changed and the call was not updated with the new order of args.
