### ISSUE TITLE
@cypress/vue TypeError: Cannot read property 'rules' of undefined during manual installation

### ISSUE THREAD

**Issue by alvarosabu** [cypress-io/cypress#14973]
### Current behavior

Following the [manual-install guide](https://github.com/cypress-io/cypress/blob/develop/npm/vue/docs/manual-install.md) for `@cypress/vue` package shows the following error when `cypress open` 
<img width="801" alt="Screenshot 2021-02-08 at 17 09 37" src="https://user-images.githubusercontent.com/4699008/107246898-054ff500-6a31-11eb-99ce-57425dd30d0d.png">

**Message:** The function exported by the plugins file threw an error.
We invoked the function exported by `/Users/alvarosaburido/Projects/dav/digital.av.portal/cypress/plugins/index.js`, but it threw an error.
**Details:**
```
TypeError: Cannot read property 'rules' of undefined
    at insertBabelLoader (/Users/alvarosaburido/Projects/dav/digital.av.portal/node_modules/@cypress/vue/dist/preprocessor/webpack.js:111:20)
    at onFileDefaultPreprocessor (/Users/alvarosaburido/Projects/dav/digital.av.portal/node_modules/@cypress/vue/dist/preprocessor/webpack.js:137:5)
    at cypressPluginsFn (/Users/alvarosaburido/Projects/dav/digital.av.portal/node_modules/@cypress/vue/dist/plugins/webpack/index.js:20:29)
    at module.exports (/Users/alvarosaburido/Projects/dav/digital.av.portal/cypress/plugins/index.js:22:3)
    at /Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:89:12
    at tryCatcher (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:86:7)
    at EventEmitter.<anonymous> (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:200:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```
**Stack trace:**
```
Error: The function exported by the plugins file threw an error.
We invoked the function exported by `/Users/alvarosaburido/Projects/dav/digital.av.portal/cypress/plugins/index.js`, but it threw an error.
    at Object.get (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:966:15)
    at EventEmitter.<anonymous> (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:144:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/alvarosaburido/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

### Desired behavior

Cypress works correctly

### Test code to reproduce

1. Follow this guide https://github.com/cypress-io/cypress/blob/develop/npm/vue/docs/manual-install.md in a non-Vue-cli project.
2.  Command `cypress open`
3.  Check line `111` on `node_modules/@cypress/vue/dist/preprocessor/webpack` 

### Versions
```
"cypress": "^6.4.0"
"@cypress/vue": "^1.0.0-alpha.4",
"@cypress/webpack-preprocessor": "^4.1.0",
```

**Comment by alvarosaburido** [comment]
Is weird, because the codebase seems to be correct by adding:

**Comment by jennifer-shehane** [comment]
cc @cypress-io/component-testing

**Comment by JessicaSachs** [comment]
It seems like the webpack configuration being passed in does not contain any rules. If you add the following section to your webpack.config.js and import it in your plugins file (as per the directions in the docs), then I believe it should work.

**Comment by alvarosaburido** [comment]
Hi @JessicaSachs thanks for answer, indeed that would be a work around to avoid the issue mentioned but I think is more valuable for you guys to check why the dist file of the npm package differs from the codebase one, 

The one in the codebase is in fact correct by avoiding checking property's of an undefined module property.

```
options.module = options.module || {}
options.module.rules = options.module.rules || []
```

If that is fixed there is no need for work around.

Maybe cache issue while building last release?

**Comment by JessicaSachs** [comment]
This is a bug with semantic release. We didn't promote the `master` tag to `latest`. Nice catch. For an immediate (very temp) fix you can `npm i @cypress/vue@master` to get around it and when we do our breaking changes and major version bump in a few days, we'll be changing the `latest` tag to be 2.x

**Comment by alvarosaburido** [comment]
Awesome! Yeah, I also have issues sometimes with the semantic release hehe. Cheers!
