### ISSUE TITLE
Syntax Error, Unrecognized Expression: cy.get() on an element with an id that contains '...'

### ISSUE THREAD

**Issue by mannanj** [cypress-io/cypress#15020]
Hello Cypress team! 

### Current behavior
I have an element with an id that contains the characters `...`, and when I make a query for this id with cy.get() i.e. `cy.get('#nickName...1234')` the test fails and Cypress throws the error below. Can you help?
```
     Error: Syntax error, unrecognized expression: #nickName_...1234
      at Function.Sizzle.error (http://localhost:3000/__cypress/runner/cypress_runner.js:86548:8)
      at Sizzle.tokenize (http://localhost:3000/__cypress/runner/cypress_runner.js:87200:11)
      at Sizzle.select (http://localhost:3000/__cypress/runner/cypress_runner.js:87627:20)
      at Function.Sizzle [as find] (http://localhost:3000/__cypress/runner/cypress_runner.js:85852:9)
      at jQuery.fn.init.find (http://localhost:3000/__cypress/runner/cypress_runner.js:87883:11)
      at new jQuery.fn.init (http://localhost:3000/__cypress/runner/cypress_runner.js:87998:40)
      at Object.query (http://localhost:3000/__cypress/runner/cypress_runner.js:177505:10)
      at $Cy.$$ (http://localhost:3000/__cypress/runner/cypress_runner.js:167015:17)
      at getElements (http://localhost:3000/__cypress/runner/cypress_runner.js:156995:20)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9956:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:7230:29)
      at resolveElements (http://localhost:3000/__cypress/runner/cypress_runner.js:157045:30)
      at Context.get (http://localhost:3000/__cypress/runner/cypress_runner.js:157056:14)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:167243:15
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:9956:23)

```

### Desired behavior
Cypress should attempt to find the element by id and return whether it was found or not.

### Test code to reproduce
Attempt a cypress get() on an element that has an id with the characters `...` in it.

### Versions
We are using these combinations of packages (and the above is called in a Cypress-cucumber-preprocessor step)
```
    "cypress": "4.11.0",
    "cypress-cucumber-preprocessor": "^2.3.1",
    "cypress-log-to-output": "^1.1.2",
    "@cypress/webpack-preprocessor": "^5.4.1",
    "@nrwl/cypress": "9.7.1",
    "@types/cypress-cucumber-preprocessor": "^1.14.1",
```

Thank you!

**Comment by sainthkh** [comment]
Internally, `cy.get()` uses jQuery engine. When your selector contains characters that are used in CSS, you need to add `\\` in front of that character. In your case, it should be `cy.get('nickname\\.\\.\\.1234')`

**Comment by anilpujaraofficial** [comment]
![Uploading Capture.PNG…]()

**Comment by rodrigosantosbh** [comment]
> Internamente, `cy.get()`usa o motor jQuery. Quando seu seletor contém caracteres que são usados ​​em CSS, você precisa adicionar `\\`na frente desse caractere. No seu caso, deve ser`cy.get('nickname\\.\\.\\.1234')`

Eu estava com um problema parecido e funcionou a solucao acima.

Meu problema era este: 
cy.get('#loginForm\:username')

Entao inseri 2 barras antes e o erro sumiu.
cy.get('#loginForm\\\:username')
