### ISSUE TITLE
Declare or import any function on spec file throws "TypeError: err.replace is not a function"

### ISSUE THREAD

**Issue by GustavoEklund** [cypress-io/cypress#15121]
### Current behavior
Declare any function or import any function throws "TypeError: err.replace is not a function" on running the test.
Not declare functions or imports, all tests runs perfectly

![image](https://user-images.githubusercontent.com/49698654/108147709-25755900-70ae-11eb-883e-eb4d403a5443.png)

Error output:
```
TypeError: err.replace is not a function
    at cleanseError (/home/gustavoeklund/www/clean-react/node_modules/@cypress/webpack-preprocessor/dist/index.js:272:16)
    at Array.map (<anonymous>)
    at Watching.handle [as handler] (/home/gustavoeklund/www/clean-react/node_modules/@cypress/webpack-preprocessor/dist/index.js:175:22)
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Watching.js:185:9
    at Hook.eval [as callAsync] (eval at create (/home/gustavoeklund/www/clean-react/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/gustavoeklund/www/clean-react/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Watching.js:182:28)
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Watching.js:107:21
    at Compiler.emitRecords (/home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Compiler.js:825:39)
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Watching.js:85:22
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Compiler.js:807:14
    at Hook.eval [as callAsync] (eval at create (/home/gustavoeklund/www/clean-react/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/gustavoeklund/www/clean-react/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Compiler.js:804:27
    at /home/gustavoeklund/www/clean-react/node_modules/neo-async/async.js:2818:7
    at done (/home/gustavoeklund/www/clean-react/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Compiler.js:647:8)
    at /home/gustavoeklund/www/clean-react/node_modules/webpack/lib/Compiler.js:735:19
    at /home/gustavoeklund/www/clean-react/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/gustavoeklund/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```
Stack trace:
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/home/gustavoeklund/www/clean-react/src/main/test/cypress/plugins/index.js`)
    at Object.get (/home/gustavoeklund/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/errors.js:966:15)
    at EventEmitter.handleError (/home/gustavoeklund/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/plugins/index.js:159:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/gustavoeklund/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

### Desired behavior
Not Throw error

### Test code to reproduce
```ts
// cypress/integration/login.spec.ts

// import { helperFunction } from '../utils/form-helper.ts // throws error
const a = (): void => {} // throws error
const b = 'b' // not throws error


describe('Login', () => {
  it('Should be ok', () => {
    // ...
  })
})
```

### Versions
"cypress": "^6.4.0"
"ts-loader": "^8.0.16"
"typescript": "^4.1.3"
"webpack": "^5.21.2"
"@cypress/webpack-preprocessor": "^5.5.0"
"react": "^17.0.1"
"react-dom": "^17.0.1"

**Comment by JohnnyFun** [comment]
What was your resolution for this issue? I'm upgrading to webpack@5.x and seeing this error.

**Comment by JohnnyFun** [comment]
Ah, I think I found what I need: `cypress-webpack-preprocessor-v5`. From this comment: https://github.com/cypress-io/cypress/issues/8948#issuecomment-737156406
