### ISSUE TITLE
Install fails when running as root

### ISSUE THREAD

**Issue by davidsteinsland** [cypress-io/cypress#1512]
- Operating System: Redhat 7
- Cypress Version: 2.1.0
- Browser Version:

### Is this a Feature or Bug?
Bug.

### Current behavior:

When installing globally, running as root, cypress fails with an `EACCESS` error when creating the `dist` dir.
```
$ npm install -g cypress
/opt/node-v8.9.1-linux-x64/bin/cypress -> /opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/bin/cypress

> cypress@2.1.0 postinstall /opt/node-v8.9.1-linux-x64/lib/node_modules/cypress
> node index.js --exec install

EACCES: permission denied, mkdir '/opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@2.1.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

One possible solution is having the `dist` dir created in the npm release so that the postinstall script doesn't have to create it.

### Desired behavior:
Cypress should have no problems creating that directory when running as root.

### Additional Info (images, stack traces, etc)
Cypress does not provide any stacktraces, because callbacks to the underlying filesystem lib isn't provided. But I was able to pin-point that the error occurs when trying to output JSON:
https://github.com/cypress-io/cypress/blob/ae794d1f8c2b68ed63ce2b9fff5fb5160d9ad74b/cli/lib/tasks/info.js#L76-L80

The fourth argument to `fs.outputJsonAsync()` is a callback which receives any errors, and when modifying the code with this, the stack trace then points to the `mkdir.mkdirs()` function:
```
    at /opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/lib/tasks/info.js:94:13
    at mkdir.mkdirs.err (/opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/node_modules/fs-extra/lib/json/output-json.js:21:23)
    at xfs.stat (/opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/mkdirs.js:55:43)
    at /opt/node-v8.9.1-linux-x64/lib/node_modules/cypress/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
```

However, the original error is when the `mkdir.mkdirs()` function calls `graceful-fs.mkdir()` which in turn is `fs.mkdir()`:
https://nodejs.org/api/fs.html#fs_fs_mkdir_path_mode_callback

**Comment by aaronthebaron** [comment]
I have a similar issue although I'm installing locally instead of global. The workaround that I found, is to run it with sudo.

**Comment by brian-mann** [comment]
This is not a Cypress issue. It's an underlying permission issue with the way you've installed `node`. You installed `node` with `sudo` and you're not using `sudo` when running `npm install`.

Solution: don't install node with `sudo`.

**Comment by brian-mann** [comment]
The only actionable thing for us to do would be to handle the situation where we get `EPERM` or `EACCES ` errors and tell the user that they've installed `node` wrong or need to use `sudo`.

We may want to open a new issue with that feature.

**Comment by AndrewStobie** [comment]
I am also having this issue in Mac OS 10.13.6 I had to sudo install node and I've run `sudo npm install` and it still has this issue.

**Comment by kenji0911** [comment]
So do I having this issue in Mac OS 10.13.5

**Comment by ryparker** [comment]
The only way I was able to get cypress to install was with sudo `npm install --unsafe-perm=true --allow-root cypress`.

I have not had this problem with any other package...

**Comment by cesarcruzm** [comment]
> You should be able to install using:
> `sudo npm install --unsafe-perm=true --allow-root cypress`
> 
> However that is not recommended. I installed npm using a nvm and it worked without sudo.
> npm docs:
> https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-node-js-and-npm

It worked for me under Xubuntu 18.04.2 LTS, npm 6.9.0.

The latest version I got of Cypress was 3.3.1

I also had to grant permissions for execution to $home/.cache/Cypress/. 

Then run npx cypress open.

**Comment by Sindr0me** [comment]
Hi! Run the next scripts for fix directories owner. There are should be your login instead 'root'. Check it with ``ls -la``

```bash
 sudo chown -R {login} "/Users/{login}/Library/Application Support/Cypress/cy"
```   
```bash
 sudo chown -R {login} /{project}/cypress/
```

**Comment by valentina98** [comment]
I have the same issue with cypress@6.5.0. I'm running the install as a root user so I have the permissions.
I also tried "npm install --unsafe-perm=true --allow-root cypress" but it did't work for me. 
Does anyone have an idea what might fix it?

**Comment by paulwag** [comment]
Having the same issue with Version 6.5.0. None of the above mentioned solutions solved it for me

**Comment by Herz3h** [comment]
Same issue here on Fedora 37, running as root, logs below:

```
~/backend # ❯❯❯ sudo DEBUG=cypress:\* npx cypress open                                                                                                                                                            issue/250-cypress-tests ✱ ◼
  cypress:cli:cli cli starts with arguments ["/usr/bin/node","/root/backend/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +121ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /root/.cache/Cypress/12.5.1/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  /root/.cache/Cypress/12.5.1/Cypress +0ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/12.5.1/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 12.5.1 installed in: /root/.cache/Cypress/12.5.1/Cypress +3ms
  cypress:cli { verified: true } +4ms
  cypress:cli is Verified ? true +2ms
  cypress:cli opening from options {"project":"/root/backend"} +0ms
  cypress:cli command line arguments ["--project","/root/backend"] +0ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli passing DISPLAY :0 +7ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--project', '/root/backend', '--cwd', '/root/backend', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '18.12.1' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +0ms
  cypress:cli spawning Cypress with executable: /root/.cache/Cypress/12.5.1/Cypress/Cypress +1ms
  cypress:cli piping child STDERR to process STDERR +7ms
  cypress:snapshot:info Caching 3372, defining 4275 modules! Using cache +0ms
  cypress:snapshot:debug initializing packherd require +0ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/browsers +0ms
  cypress:server:cypress starting cypress with argv [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--', '--project', '/root/backend', '--cwd', '/root/backend', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '18.12.1' ] +0ms
  cypress:server:args argv array: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--project', '/root/backend', '--cwd', '/root/backend', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '18.12.1' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1' } } +1ms
  cypress:server:args argv parsed: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1', invokedFromCli: true } +3ms
  cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' } +0ms
  cypress:server:args options { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1', invokedFromCli: true, config: {} } +2ms
  cypress:server:args argv options: { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1', invokedFromCli: true, config: {}, projectRoot: '/root/backend' } +1ms
  cypress:server:cypress from argv [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress', '--no-sandbox', '--project', '/root/backend', '--cwd', '/root/backend', '--userNodePath', '/usr/bin/node', '--userNodeVersion', '18.12.1' ] got options { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1', invokedFromCli: true, config: {}, projectRoot: '/root/backend' } +10ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production +96ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[90968:0206/194346.387139:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[90968:0206/194346.387357:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[90968:0206/194346.387480:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[90968:0206/194346.387562:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[90968:0206/194346.387602:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[90968:0206/194346.394505:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[90811:0206/194346.404949:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
  cypress:server:cypress starting in mode interactive with options { _: [ '/root/.cache/Cypress/12.5.1/Cypress/Cypress' ], sandbox: false, project: '/root/backend', cwd: '/root/backend', userNodePath: '/usr/bin/node', userNodeVersion: '18.12.1', invokedFromCli: true, config: {}, projectRoot: '/root/backend' } +108ms
  cypress:server:cypress running Electron currently +1ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[90988:0206/194346.415499:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[90988:0206/194346.415829:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[90988:0206/194346.416094:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[90988:0206/194346.416232:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[90988:0206/194346.416452:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[90988:0206/194346.418703:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudLatestRunUpdateSpecData +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectBySlug +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectsBySlugs +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudSpecByPath +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudViewer +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.pollingIntervals +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.versions +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for CurrentProject.cloudProject +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectResult.data +3ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectSpecResult.data +1ms
  cypress:server:browsers:utils getBrowsers +0ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86, validator: [Function: validator] }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/im, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge.+?(\S*(?= canary)|(?<=canary )\S*)/im, binary: [ 'edge-canary', 'microsoft-edge-canary' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge.+?(\S*(?= beta)|(?<=beta )\S*)/im, binary: [ 'edge-beta', 'microsoft-edge-beta' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge.+?(\S*(?= dev)|(?<=dev )\S*)/im, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +0ms
  cypress:server:browsers:utils WebKit is enabled, but there was an error constructing the WebKit browser: { err: Error: Cannot find module 'playwright-webkit' Require stack: - /root/.cache/Cypress/12.5.1/Cypress/resources/app/packages/server/lib/browsers/utils.ts     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)     at n._resolveFilename (node:electron/js2c/browser_init:249:1105)     at resolve (node:internal/modules/cjs/helpers:108:19) at Function.resolve (evalmachine.<anonymous>:1:733924) at N (<embedded>:4567:307214) at Object.I [as getBrowsers] (<embedded>:4567:308049) at b.machineBrowsers (<embedded>:4226:46866) at T._setCurrentProject (<embedded>:4337:78225) at new T (<embedded>:4337:71533) at new I (<embedded>:4337:122599) at N (<embedded>:4639:437733) at s.exports (<embedded>:4639:529323) at <embedded>:4646:2607 at tryCatcher (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23) at Function.<anonymous> (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29) at Object.runElectron (<embedded>:4646:2377) at Object.startInMode (<embedded>:4646:5205) at <embedded>:4646:3945 at tryCatcher (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._settlePromise (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:582:21) at Promise._settlePromise0 (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._settlePromise (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:582:21) at Promise._settlePromise0 (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at PromiseArray._resolve (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:126:19) at PromiseArray._promiseFulfilled (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:144:14) at Promise._settlePromise (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:574:26) at Promise._settlePromise0 (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at /root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/bluebird/js/release/nodeback.js:42:21 at <embedded>:1955:88964 { code: 'MODULE_NOT_FOUND', requireStack: [ '/root/.cache/Cypress/12.5.1/Cypress/resources/app/packages/server/lib/browsers/utils.ts' ] } } +3ms
  cypress:data-context:sources:GitDataSource config: { isRunMode: false, projectRoot: '/root/backend', onError: [Function (anonymous)], onBranchChange: [Function: onBranchChange], onGitInfoChange: [Function: onGitInfoChange], onGitLogChange: [AsyncFunction: onGitLogChange] } +0ms
  cypress:data-context:sources:GitDataSource Refreshing git data +8ms
  cypress:scaffold-config:detect Checking for default Cypress config file +0ms
  cypress:scaffold-config:detect Detected cypress.config.js - using JS +0ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/cache +136ms
  cypress:server:util:editors get user editor +0ms
  cypress:server:saved_state making saved state from /root/.cache/Cypress/12.5.1/Cypress/resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/root/.cache/Cypress/12.5.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/root/backend', '--file', '/root/backend/cypress.config.js' ], childOptions: { stdio: 'pipe', cwd: '/root/backend', execPath: '/usr/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc no typescript found, just use regular Node.js +1ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +12ms
  cypress:server:performance-benchmark elapsed time at open mode ready: 492.151ms +0ms
  cypress:server:saved_state making saved state from /root/.cache/Cypress/12.5.1/Cypress/resources/app/packages/server +75ms
  cypress:server:saved_state for project path /root/backend +0ms
  cypress:server:saved_state state path for project /root/backend +0ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/projects/backend-40f46622e53c9cfa9d1aa466f3f623b6/state.json +116ms
  cypress:server:saved_state full state path /root/.config/Cypress/cy/production/projects/backend-40f46622e53c9cfa9d1aa466f3f623b6/state.json +37ms
  cypress:server:saved_state making new state file around /root/.config/Cypress/cy/production/projects/backend-40f46622e53c9cfa9d1aa466f3f623b6/state.json +0ms
  cypress:data-context:sources:GitDataSource Loading git hashes +128ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[91234:0206/194346.648078:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[91234:0206/194346.648401:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[91234:0206/194346.648732:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[91234:0206/194346.648905:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[91234:0206/194346.649079:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[91234:0206/194346.651742:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
  cypress:server:saved_state state path for global mode +39ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/projects/__global__/state.json +39ms
  cypress:server:saved_state full state path /root/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:saved_state making new state file around /root/.config/Cypress/cy/production/projects/__global__/state.json +0ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
  cypress:data-context:sources:GitDataSource On current branch issue/250-cypress-tests +36ms
  cypress:data-context:sources:GitDataSource Creating watcher +1ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[91272:0206/194346.675768:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[91272:0206/194346.675894:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[91272:0206/194346.676077:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[91272:0206/194346.676247:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[91272:0206/194346.676392:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[91272:0206/194346.678321:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
  cypress:data-context:sources:GitDataSource Calling onGitLogChange: callback defined true, git hash count 100 +8ms
  cypress:data-context:sources:RelevantRunsDataSource check relevant runs with 100 shas and clear cache set to true +0ms
  cypress:config:browser validating configuration {} +0ms
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[91300:0206/194346.694549:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[91300:0206/194346.694899:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[91300:0206/194346.695195:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[91300:0206/194346.695364:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[91300:0206/194346.695541:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[91300:0206/194346.698360:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[91360:0206/194346.731820:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[91360:0206/194346.731943:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[91360:0206/194346.732051:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[91360:0206/194346.732087:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[91360:0206/194346.732125:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[91360:0206/194346.733837:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
  cypress:server:windows creating electron window with options { url: 'http://localhost:46267/__launchpad/index.html', backgroundColor: 'white', width: 1200, height: 800, minWidth: 597, minHeight: 400, x: null, y: null, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage { toPNG: [Function: toPNG], toJPEG: [Function: toJPEG], toBitmap: [Function: toBitmap], getBitmap: [Function: getBitmap], getScaleFactors: [Function: getScaleFactors], getNativeHandle: [Function: getNativeHandle], toDataURL: [Function: toDataURL], isEmpty: [Function: isEmpty], getSize: [Function: getSize], setTemplateImage: [Function: setTemplateImage], isTemplateImage: [Function: isTemplateImage], isMacTemplateImage: [Getter/Setter], resize: [Function: resize], crop: [Function: crop], getAspectRatio: [Function: getAspectRatio], addRepresentation: [Function: addRepresentation] }, webPreferences: { contextIsolation: true, partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false }, contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
Authorization required, but no authorization protocol specified
  cypress:lifecycle:child:run_require_async_child:91214 configFile: /root/backend/cypress.config.js +0ms
  cypress:lifecycle:child:run_require_async_child:91214 projectRoot: /root/backend +1ms
Authorization required, but no authorization protocol specified
[91449:0206/194346.792215:WARNING:vaapi_wrapper.cc(794)] VAAPI video acceleration not available for disabled
[91449:0206/194346.799704:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is
[91449:0206/194346.802688:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 48234499
  cypress:lifecycle:child:run_require_async_child:91214 try loading /root/backend/cypress.config.js +23ms
  cypress:lifecycle:child:run_require_async_child:91214 Loading file /root/backend/cypress.config.js +1ms
  cypress:lifecycle:child:run_require_async_child:91214 loaded config file /root/backend/cypress.config.js +1ms
  cypress:lifecycle:child:run_require_async_child:91214 loaded config from /root/backend/cypress.config.js {} +0ms
  cypress:lifecycle:ProjectConfigIpc loadConfig:reply +228ms
  cypress:lifecycle:ProjectConfigManager config is loaded for file /root/backend/cypress.config.js null +0ms
  cypress:config:browser validating configuration {} +134ms
  cypress:data-context:sources:RelevantRunsDataSource No project detected +140ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '90811'     │     0      │       0        │  315.88  │    315.88    │   315.88    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '90814, 90815' │     0      │       0        │  100.39  │    100.39    │   100.39    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '90954, 90955' │     0      │       0        │    7     │      7       │      7      │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │      '-'       │     0      │       0        │  423.28  │    423.28    │   423.28    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
```
