### ISSUE TITLE
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. 

### ISSUE THREAD

**Issue by Saravanakumarm0903** [cypress-io/cypress#15267]
Currently I am executing the query using cypress but i am facing some issue. Could please me ASAP

Cypress.json
```json
    "db": {
            "userName": "",
            "password": "",
            "server": "",
            "options": {
                "database": "",
                "encrypt": true,
                "rowCollectionOnRequestCompletion" : true
            }     
```  

Plugin/Index.js

```js
const sqlServer = require('cypress-sql-server');
const dbConfig = require('../../cypress.json');

module.exports = (on, config) => {
  tasks = sqlServer.loadDBPlugin(dbConfig.db);
  on('task', tasks);
  return tasks;
}
```
Support/index.js
```js
import sqlServer from 'cypress-sql-server';
sqlServer.loadDBCommands();
```
MyTest File : 
```js
cy.sqlServer(`query`).should('eq','test');
```

After Executing this query, I am facing this issue
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`......plugins\index.js`)
    at Object.get (C:\Users\smarudh\AppData\Local\Cypress\Cache\6.5.0\Cypress\resources\app\packages\server\lib\errors.js:966:15)
    at EventEmitter.handleError (C:\Users\smarudh\AppData\Local\Cypress\Cache\6.5.0\Cypress\resources\app\packages\server\lib\plugins\index.js:168:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\smarudh\AppData\Local\Cypress\Cache\6.5.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

Please give me solutions

**Comment by jennifer-shehane** [comment]
@Saravanakumarm0903 Try removing the `return tasks;` from the exports, that is not originally part of the `'cypress-sql-server` plugin instructions. 

You may want to try asking our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.

**Comment by Saravanakumarm0903** [comment]
connect ECONNREFUSED 127.0.0.1:3306 while connecting the mysql database

Please help me
