### ISSUE TITLE
Cannot find any-observable implementation nor global.Observable error whlile updating version cypress from 6.0.1 to 6.5.0

### ISSUE THREAD

**Issue by aalexeyenko** [cypress-io/cypress#15272]
Current version of Cypress is 6.0.1
When I upgrade cypress:
`npm install cypress@6.5.0`

### Current behavior
error is thrown
>Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").`

### Desired behavior
Cypress 6.5.0 successfully installed

debug log:
```
1185 verbose stack Error: command failed
1185 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
1185 verbose stack     at ChildProcess.emit (node:events:378:20)
1185 verbose stack     at maybeClose (node:internal/child_process:1067:16)
1185 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
1186 verbose pkgid cypress@6.5.0
1187 verbose cwd C:\Users\user\Projects\trunk\Cypress
1188 verbose Windows_NT 10.0.15063
1189 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cypress@6.5.0"
1190 verbose node v15.10.0
1191 verbose npm  v7.5.3
1192 error code 1
1193 error path C:\Users\user\Projects\trunk\Cypress\node_modules\cypress
1194 error command failed
1195 error command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
1196 error C:\Users\user\Projects\trunk\Cypress\node_modules\any-observable\register.js:29
1196 error 		throw new Error('Cannot find any-observable implementation nor' +
1196 error 		^
1196 error
1196 error Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
1196 error     at loadImplementation (C:\Users\user\Projects\trunk\Cypress\node_modules\any-observable\register.js:29:9)
1196 error     at C:\Users\user\Projects\trunk\Cypress\node_modules\any-observable\loader.js:30:18
1196 error     at Object.<anonymous> (C:\Users\user\Projects\trunk\Cypress\node_modules\any-observable\index.js:2:39)
1196 error     at Module._compile (node:internal/modules/cjs/loader:1091:14)
1196 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
1196 error     at Module.load (node:internal/modules/cjs/loader:971:32)
1196 error     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
1196 error     at Module.require (node:internal/modules/cjs/loader:995:19)
1196 error     at require (node:internal/modules/cjs/helpers:92:18)
1196 error     at Object.<anonymous> (C:\Users\user\Projects\trunk\Cypress\node_modules\@samverschueren\stream-to-observable\index.js:2:20)
1196 error     at Module._compile (node:internal/modules/cjs/loader:1091:14)
1196 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
1196 error     at Module.load (node:internal/modules/cjs/loader:971:32)
1196 error     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
1196 error     at Module.require (node:internal/modules/cjs/loader:995:19)
1196 error     at require (node:internal/modules/cjs/helpers:92:18)
1197 verbose exit 1
```

**Comment by jennifer-shehane** [comment]
@aalexeyenko Does this error happen when installing on a blank project? Or one of our example projects?

Please provide a base repo we can install Cypress on to reproduce this error. Thanks!

**Comment by aalexeyenko** [comment]
Please find repo here https://github.com/aalexeyenko/cypress-error-on-update-to-6.5.0

**Comment by aalexeyenko** [comment]
I tried to update to latest 6.8.0 using command `npm install cypress@6.8.0 ` and installation failed with same error above.
The workaround that worked for me is run:  `npm install -g cypress`. This updates cypress successfully.

**Comment by Garcia-JuanLuis** [comment]
Hi, I was able to install cypress just this morning; right now I can't and I'm getting this issue/error.

npm install -D cypress

npm ERR! cypress@**7.4.0** postinstall: `node index.js --exec install`
