### ISSUE TITLE
ffmpeg error with Chrome 89

### ISSUE THREAD

**Issue by mdantonio** [cypress-io/cypress#15300]
### Current behavior

After upgrading to google-chrome 89 Cypress fails:

```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/Cypress/6.5.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/Cypress/6.5.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/Cypress/6.5.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: Command failed with exit code 1: cypress run --record --group totp --browser chrome
    at makeError (/app/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/app/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  command: 'cypress run --record --group totp --browser chrome',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
```

### Desired behavior

google-chrome 89 should work

### Test code to reproduce

`cypress run --browser chrome`

having installed chrome 89 (the new stable version since yesterday):

```
$ google-chrome-stable --version
Google Chrome 89.0.4389.72 
```

It works with chrome 88

```
$ google-chrome-stable --version
Google Chrome 88.0.4324.182 
```

### Versions

Cypress 6.6.0
Google Chrome 89.0.4389.72

**Comment by grahamhar** [comment]
I managed to get some additional information by setting the environment variable 

DEBUG=cypress:server:video

The error indicates the source video generated is 1050x839 and the height is not divisible by 2

I can't copy the error due to not having access so attempting via a photo of the screen

![image](https://user-images.githubusercontent.com/904991/109812864-7fd0f680-7c24-11eb-8744-76e75e226060.jpeg)

**Comment by mcmarkj** [comment]
Also spotted here: https://github.com/cypress-io/cypress-docker-images/issues/450

It appears the first spec that it runs works fine, then the second spec has a different resolution

Working spec:
2021-03-03T13:38:00.239Z]   cypress:server:video capture stderr log { message: '    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), **_1050x842_** [SAR 1:1 DAR 525:421], 25 fps, 25 tbr, 25 tbn, 25 tbc' } +0ms



Failing Spec:
[2021-03-03T13:38:33.085Z]   cypress:server:video capture stderr log { message: '[libx264 @ 0x6916800] height not divisible by 2 (**_1050x891_**)' } +4ms

**Comment by jennifer-shehane** [comment]
We also encountered this error when upgrading to the new Electron version because it uses Chrome 89. There is already a PR open to fix this in our next release. https://github.com/cypress-io/cypress/pull/15295

We'll close this issue as it is pending release, but has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

In the meantime, there are a few workarounds you might consider:

- Turn off video recording until the next release.
- Run tests in the Electron browser which uses Chromium 87.
- Use another Chrome browser version in docker containers: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
- Downgrade Chrome to the last stable version of Chrome 88 locally for your operating system: https://chromium.cypress.io/

**Comment by mcmarkj** [comment]
@jennifer-shehane out of curiosity how frequently do you cut releases, or at which point? 
I'm refreshing the changelog page multiple times daily, as this is quite a big thing breaking CI for us so keen to get the fix in asap.

**Comment by bahmutov** [comment]
@mcmarkj https://docs.cypress.io/faq/questions/general-questions-faq.html#How-often-are-Cypress-Test-Runner-versions-released so we should release a new version on Monday

**Comment by jennifer-shehane** [comment]
@mcmarkj We usually release every 2 weeks, but we've been trying to juggle some feature work between 6.7 and breaking 7.0, so there's been some delay.

**Comment by jennifer-shehane** [comment]
6.7.0 should go out today though!
