### ISSUE TITLE
Crash when parsing JSON object passed via --env option

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#15323]
Cypress v6.6.0 trying to use `--env` option to pass an object, related to the discussion https://github.com/cypress-io/cypress/discussions/14292

works

```
$ npx cypress open --env person='{ "name": "hi", "age": 18 }'
plugins file has the config.env { person: { name: 'hi', age: 18 } }
```

crashes

```
$ npx cypress open --env person='{ "name": {}, "age": 18 }'
Cypress encountered an error while parsing the argument env

You passed: person={ "name": {}, "age": 18 }

The error was: Cannot read property 'split' of undefined
```

Running with debug log

```
$ DEBUG=cypress:server:args npx cypress open --env person='{ "name": {}, "age": 18 }'
  cypress:server:args argv array: [ '/Users/gleb/Library/Caches/Cypress/6.6.0/Cypress.app/Contents/MacOS/Cypress', '--no-sandbox', '--env', 'person={ "name": {}, "age": 18 }', '--project', '/Users/gleb/git/cypress-env-from-cli-example', '--cwd', '/Users/gleb/git/cypress-env-from-cli-example' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/Users/gleb/Library/Caches/Cypress/6.6.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, env: 'person={ "name": {}, "age": 18 }', project: '/Users/gleb/git/cypress-env-from-cli-example', cwd: '/Users/gleb/git/cypress-env-from-cli-example' } } +5ms
  cypress:server:args argv parsed: { _: [ '/Users/gleb/Library/Caches/Cypress/6.6.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, env: 'person={ "name": {}, "age": 18 }', project: '/Users/gleb/git/cypress-env-from-cli-example', cwd: '/Users/gleb/git/cypress-env-from-cli-example', invokedFromCli: true } +3ms
  cypress:server:args could not pass config env value person={ "name": {}, "age": 18 } +1ms
  cypress:server:args error TypeError: Cannot read property 'split' of undefined at pipesToCommas (/Users/gleb/Library/Caches/Cypress/6.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:90:14) at JSONOrCoerce (/Users/gleb/Library/Caches/Cypress/6.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:111:9)
```

Feels weird to parse some JSON, but not the nested objects (or at least fallback to try JSON)

## Reproduction

https://github.com/bahmutov/cypress-env-from-cli-example

## Proposed fix

Add a check, and if the argument is of the form `name=JSON object or array` parse the right side of `=` as JSON and not a comma-separated list.

**Comment by bahmutov** [comment]
Related issue: https://github.com/cypress-io/cypress/issues/4543 but that one is slightly different, since there it is trying to parse non-json list

**Comment by bahmutov** [comment]
Workaround: use separate `CYPRESS_` variable instead of `--env` option

```
$ CYPRESS_person='{ "name": { "first": "Joe", "last": "Smith" }, "age": 18 }' npx cypress open
```

**Comment by FrancisBourgault** [comment]
Workaround doesn't seem to work.

I haven't tested with a execution that uses the object variable, but I get a white-screen when I try to check the environment variable in the Settings.

Cypress version: 8.0.0
