### ISSUE TITLE
Error: val is not a non-empty string or a valid number. val=null

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#15359]
### Current behavior
Since upgrading to 6.6.0, we've seen this error and stack trace appear a few times:

```
Error: val is not a non-empty string or a valid number. val=null
    at module.exports (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/node_modules/ms/index.js:34:9)
    at Spec.Base.epilogue (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/lib/reporters/base.js:349:43)
    at Object.onceWrapper (events.js:422:26)
    at Runner.emit (events.js:327:22)
    at Reporter.emit (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/reporter.js:333:46)
    at Object.onMocha (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/project-base.js:274:26)
    at Socket.<anonymous> (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/socket-base.js:217:40)
    at Socket.emit (events.js:315:20)
    at Socket.onevent (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:253:20)
    at Socket._onpacket (/home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:216:22)
    at /home/jenkins/.cache/Cypress/6.6.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:205:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

This is coming from within Cypress/mocha and seems to be unrelated to our tests. I have no idea what's causing this or what it means.

### Desired behavior
For this to not happen.

### Versions

Cypress 6.6.0

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Maybe a repo that recreates the error? We haven't seen this reported by anyone else, so it is likely related to something in your porject. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by kaiyoma** [comment]
Just ran into this again:

```
18:14:10  Error: val is not a non-empty string or a valid number. val=null
18:14:10      at module.exports (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/node_modules/ms/index.js:34:9)
18:14:10      at Spec.Base.epilogue (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/lib/reporters/base.js:349:43)
18:14:10      at Object.onceWrapper (events.js:422:26)
18:14:10      at Runner.emit (events.js:327:22)
18:14:10      at Reporter.emit (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/reporter.js:333:46)
18:14:10      at Object.onMocha (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/project-base.js:293:26)
18:14:10      at Socket.<anonymous> (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/socket-base.js:225:40)
18:14:10      at Socket.emit (events.js:315:20)
18:14:10      at Socket.onevent (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:253:20)
18:14:10      at Socket._onpacket (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:216:22)
18:14:10      at /home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:205:28
18:14:10      at processTicksAndRejections (internal/process/task_queues.js:79:11)
18:14:10  
18:14:10  Error: val is not a non-empty string or a valid number. val=null
18:14:10      at module.exports (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/node_modules/ms/index.js:34:9)
18:14:10      at Spec.Base.epilogue (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/node_modules/mocha-7.0.1/lib/reporters/base.js:349:43)
18:14:10      at Object.onceWrapper (events.js:422:26)
18:14:10      at Runner.emit (events.js:327:22)
18:14:10      at Reporter.emit (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/reporter.js:333:46)
18:14:10      at Object.onMocha (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/project-base.js:293:26)
18:14:10      at Socket.<anonymous> (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/server/lib/socket-base.js:225:40)
18:14:10      at Socket.emit (events.js:315:20)
18:14:10      at Socket.onevent (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:253:20)
18:14:10      at Socket._onpacket (/home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:216:22)
18:14:10      at /home/jenkins/.cache/Cypress/6.9.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:205:28
18:14:10      at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by kaiyoma** [comment]
@jennifer-shehane Like most Cypress issues I run into, there's no reliable repro. The problem happens randomly.

**Comment by jennifer-shehane** [comment]
@kaiyoma I understand, but we need something to go off of in order to investigate even if it's not 100% reproducible. It's likely related to the tests written or the application under test, so seeing those or some reduced version of those would be helpful.
