### ISSUE TITLE
ffmpeg failing on GitHub actions causing whole test run to fail

### ISSUE THREAD

**Issue by andycarrell** [cypress-io/cypress#15498]
### Current behavior
Video is not recorded, then `ffmpeg` fails with exit code 1, failing the whole test run.

### Desired behavior
Tests run and failed test videos are recorded.

### Test code to reproduce
Reproducible on GitHub actions, across any test we run. 

```json
// cypress.json
{
	"video": true,
	"integrationFolder": ".cypress/integration",
	"supportFile": ".cypress/setup.integration.js",
	"pluginsFile": ".cypress/plugins.integration.js",
	"fixturesFolder": ".cypress/fixtures",
	"baseUrl": "http://localhost:3000/",
	"projectId": "---",
	"blockHosts": [
		"*sentry.io",
		"*api.segment.io",
		"*cdn.coview.com",
		"*cdn.segment.com",
		"*google-analytics.com",
		"*hotjar.com",
		"*intercom.io",
		"*intercomcdn.com",
		"*mapbox.com"
	],
	"retries": {
		"runMode": 1,
		"openMode": 0
	}
}
```

### Versions

- GitHub actions on Ubuntu 20.04.2 LTS
- 'cypress-io/github-action@v2.3.6'
- Cypress v6.6

#### Error
```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

Test run failed, code 1
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

**Comment by pmerwin** [comment]
Good news, latest cypress should have this fixed =>
https://github.com/cypress-io/cypress/issues/15300

**Comment by andycarrell** [comment]
Yup looks like it does 🙏
