### ISSUE TITLE
Error when running test suite with empty spec files

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress#15512]
### Current behavior

I upgraded to Cypress 6.7.1 and now [there's an error](https://github.com/tutorbookapp/tutorbook/runs/2118940428?check_suite_focus=true#step:9:42) when using `cypress run` with empty spec files:

```
TypeError: Cannot read property 'tests' of null
    at Object.exports.flattenSuiteIntoRunnables (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/util/tests_utils.js:12:32)
    at ProjectE2E.onTestsReceived [as _recordTests] (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/modes/record.js:727:30)
    at ProjectE2E.<anonymous> (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:280:32)
    at Generator.next (<anonymous>:null:null)
    at /home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:9:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:5:12)
    at Object.onTestsReceivedAndMaybeRecord (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:274:63)
    at SocketE2E.<anonymous> (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:222:32)
    at Generator.next (<anonymous>:null:null)
    at /home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:4:12)
    at Socket.<anonymous> (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:221:82)
    at Socket.emit (events.js:315:20)
    at Socket.onevent (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:253:20)
    at Socket._onpacket (/home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:216:22)
    at /home/runner/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:205:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Desired behavior

There should be no error when running empty spec files. Instead, Cypress should just log a warning that they're empty and move on.

### Test code to reproduce

This should be relatively simple to reproduce.:
1. Just create a new Cypress repo
2. Add an empty test
3. And run Cypress

Here's [the link to the original repository](https://github.com/tutorbookapp/tutorbook) where I'm seeing the error.

### Versions

Cypress: 6.7.1
Browser: N/A

**Comment by jennifer-shehane** [comment]
This is a bug introduced in 6.7.1. When running Cypress tests while recording to the Dashboard with an empty specfile, the run will exit with SIGSEGV. 

<img width="1436" alt="Screen Shot 2021-03-16 at 9 18 42 AM" src="https://user-images.githubusercontent.com/1271364/111315689-ff08f600-8638-11eb-9f06-a0d5f9b108e9.png">

### Workaround

Downgrade to 6.6.0 to record tests with empty spec files.

**Comment by clarkd** [comment]
We are seeing this issue, I think because we use the popular Cypress tags plugin to run different subsets of tests.

**Comment by jennifer-shehane** [comment]
@clarkd Could you provide an example of your setup?

**Comment by clarkd** [comment]
Hi @jennifer-shehane - it's a pretty complex so I can't provide a repo but the basic pieces are:
* Cypress 6.7.1
* cypress-tags plugin - [annaet/cypress-tags](https://github.com/annaet/cypress-tags)
* Running against Cypress Dashboard with parallelisation
* Chrome 88 (due to previous issue with v89)

Is there any other info I can provide?

**Comment by thewillhuang** [comment]
We are running into this issue as well. We have commented out tests and this will result in SIGSEGV with 6.7.1 in headless mode. Runs fine tho if you don't do headless
