### ISSUE TITLE
RangeError: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by dvkruchinin** [cypress-io/cypress#15619]
### Current behavior
```
     RangeError: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received 3686592
  RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received 3686592
      at boundsError (internal/buffer.js:77:9)
      at Buffer.readUInt32BE (internal/buffer.js:300:5)
      at Jimp.<anonymous> (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\@jimp\plugin-crop\dist\index.js:43:37)
      at scan (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\@jimp\utils\dist\index.js:53:9)
      at Jimp.scanQuiet (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\@jimp\core\dist\index.js:1262:32)
      at Jimp.cropQuiet (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\@jimp\plugin-crop\dist\index.js:42:12)
      at Jimp.<computed> [as crop] (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\@jimp\core\dist\index.js:1176:23)
      at crop (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\lib\screenshots.js:171:24)
      at C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\lib\screenshots.js:464:17
      at tryCatcher (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\<username>\AppData\Local\Cypress\Cache\6.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
```
The error occurs when running the test in the Chrome browser in headless mode.

### Desired behavior
There is no error

### Test code to reproduce
```git clone https://github.com/dvkruchinin/cvat.git && cd ./cvat```
```git checkout dkru/cypress-test-canvas-3d-m4-check-resize-views-origin```
```docker-compose -f docker-compose.yml -f docker-compose.dev.yml build```
```docker-compose up -d```
```docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'``` for Linux
or
```winpty docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'``` for Windows
```
name: admin
e-mail: <empty>
password: 12qwaszx
```
```cd ./tests && npm ci```
```npx cypress run --env coverage=false --headless --browser chrome --spec="cypress/integration/canvas3d_functionality/case_56_canvas3d_functionality_basic_actions.js"```

### Versions
Cypress 6.4.0, 6.8.0
Chrome 89

**Comment by dvkruchinin** [comment]
Increasing the viewport() values helped. But still it is not clear why this error occurred.

**Comment by clayhindman01** [comment]
@dvkruchinin did you find a solution to this? I'm having the same issue.
