### ISSUE TITLE
Running in parallel results in TypeError: Cannot read property 'tests' of null

### ISSUE THREAD

**Issue by iainsscratchpad** [cypress-io/cypress#15613]
If there is a empty *.spec.js file (no tests in it) then running in parallel fails on the empty file.

### Current behavior
When I run cypress in parallel using the Cypress Dashboard on Azure Dev Ops it is often failing with the following error:

2021-03-22T14:12:02.0892698Z TypeError: Cannot read property 'tests' of null
2021-03-22T14:12:02.0893308Z     at Object.exports.flattenSuiteIntoRunnables (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/util/tests_utils.js:12:32)
2021-03-22T14:12:02.0894266Z     at ProjectE2E.onTestsReceived [as _recordTests] (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/modes/record.js:727:30)
2021-03-22T14:12:02.0895096Z     at ProjectE2E.<anonymous> (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:280:32)
2021-03-22T14:12:02.0895829Z     at Generator.next (<anonymous>:null:null)
2021-03-22T14:12:02.0896426Z     at /home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:9:71
2021-03-22T14:12:02.0896915Z     at new Promise (<anonymous>:null:null)
2021-03-22T14:12:02.0897534Z     at __awaiter (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:5:12)
2021-03-22T14:12:02.0898260Z     at Object.onTestsReceivedAndMaybeRecord (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/project-base.js:274:63)
2021-03-22T14:12:02.0898985Z     at SocketE2E.<anonymous> (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:222:32)
2021-03-22T14:12:02.0899407Z     at Generator.next (<anonymous>:null:null)
2021-03-22T14:12:02.0899958Z     at /home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:8:71
2021-03-22T14:12:02.0900338Z     at new Promise (<anonymous>:null:null)
2021-03-22T14:12:02.0901035Z     at __awaiter (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:4:12)
2021-03-22T14:12:02.0901736Z     at Socket.<anonymous> (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/server/lib/socket-base.js:221:82)
2021-03-22T14:12:02.0902272Z     at Socket.emit (events.js:315:20)
2021-03-22T14:12:02.0902677Z     at Socket.onevent (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:253:20)
2021-03-22T14:12:02.0903220Z     at Socket._onpacket (/home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:216:22)
2021-03-22T14:12:02.0903726Z     at /home/vsts/.cache/Cypress/6.7.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:205:28
2021-03-22T14:12:02.0904141Z     at processTicksAndRejections (internal/process/task_queues.js:79:11)

I do not see this error when I do not run in parallel.

### Desired behavior
That I can run in parallel without error.

### Test code to reproduce
An empty spec file included in the list of specs picked up.

### Versions
6.7.1

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog) - this was fixed in 6.8.0. Thanks!

**Comment by iainsscratchpad** [comment]
Thanks, I'll try that.
