### ISSUE TITLE
Cannot open testing browser when running a test: failed to connect to CDP

### ISSUE THREAD

**Issue by nsrivastava645** [cypress-io/cypress#15650]
`**Title:** Error launching browser

**Message:** 

```
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">64829</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:64829
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m64829[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:64829
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

    at get (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\lib\errors.js:966:15)
    at Object.throwErr [as throw] (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\lib\errors.js:984:9)
    at C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\lib\browsers\protocol.js:105:21
    at tryCatcher (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Neeraj\AppData\Local\Cypress\Cache\6.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

````

**Comment by yingningcc** [comment]
Having the same issue here!
Cypress version 6.4.0
Mac OS 11.2.3 Big Sur

Error Trace:
`Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m62219[39m.

Error details:

Error: connect ETIMEDOUT 10.0.116.212:62219
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

    at get (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:966:15)
    at Object.throwErr [as throw] (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:984:9)
    at /Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:105:21
    at tryCatcher (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/huimin.chen/Library/Caches/Cypress/6.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)`

**Comment by AdrianHL** [comment]
I'm getting this error now after upgrading to 7.0.1 (with node 12 and 14). Tried with our older version and I'm getting the same error. Using Mac OS 11.2.3 Big Sur.

**Comment by pavel-R5** [comment]
Same here with Cypress 7.7 in CI/CD
Using CircleCI
Chrome 85 (headless)

Failed randomly, after re-running the same tests(without any changes) it ran without failures.
Short logs here:

```
Failed to connect to Chrome, retrying in 1 second (attempt 59/62)
Failed to connect to Chrome, retrying in 1 second (attempt 60/62)
Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 41233.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:41233
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

Hey, @jennifer-shehane !
You've added a "Needs information" label.
Is it something we can provide?

**Comment by nickpm21** [comment]
I'm running on Windows as my OS. This is a recent thing, it will happen randomly

**Comment by onthespotqa** [comment]
I've also hit this  issue since we upgraded to 9.2 and started using chrome. we're using cypress/browsers:node16.14.2-slim-chrome100-ff99-edge as the docker image that runs the tests. It happened with previous versions of the image. But mostly we noticed since we switched to chrome after upgrading to 9.2.
