### ISSUE TITLE
Plugin crash issue in Cypress

### ISSUE THREAD

**Issue by jithinjosejacob** [cypress-io/cypress#15706]
I am running cypress tests inside CI and they are crashing with below error .Locally they seems to be passing fine without any issues

### Current behavior
Tests fail with plugin error
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed

### Desired behavior
Tests should pass successfully
### Test code to reproduce

Plugins file
```js
/// <reference types="cypress" />
const fs = require('fs');
const request = require('request');

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('before:run', (details) => {
    // This will  generate test txt files
    const dateTime = new Date().toLocaleString().replace(',', '');
    for (let fileName of ["createData", "updateData", "TC08_createData"]) {
      const reqFile = require(`../fixtures/AU/${fileName}.json`);
      reqFile.merchantReference = fileName+'-'+'SAU' + '-' + dateTime;
      const jsonString = JSON.stringify(reqFile, null, 2)
      fs.writeFile(`./cypress/fixtures/AU/${fileName}.txt`, jsonString, err => {
        if (err) {
          return reject(err);
        }
      })
    }
  })

  on('task', {
    // This task is to fetch secrets from AWS Secrets Manager
    getSecrets() {
      return new Promise((resolve, reject) => {
        const testType = 'AU';
        var arnMap = {
          AU: 'AXXlPR',
          US: 'BE0aKo'
        };
        // Load the AWS SDK and fetch secrets based on environment variable
        var AWS = require('aws-sdk'),
          region = "ap-southeast-2",
          secretName = `arn:aws:secretsmanager:ap-southeast-2:123456789:secret:${arnMap[testType]}`;

        // Create a Secrets Manager client
        var client = new AWS.SecretsManager({
          region: region
        });

        // Fetch secrets
        client.getSecretValue({ SecretId: secretName }, function (err, data) {
          if (err) {
            return reject(err);
          }
          const secretValues = data.SecretString;
          const secretString = JSON.parse(secretValues);
          resolve(secretString);
        })
      })
    }
  })

  on('task', {
    // This task is to get phone code from stub
    getMobileCode({ mobileStub }) {
      return new Promise((resolve, reject) => {
        request(`${mobileStub}`, { json: true }, (err, res, body) => {
          if (err) { return reject(err); }
          var codes = (body.content.match(/\d{6}/) || [false])[0];
          resolve(codes);
        });
      })
    }
  })
}
```
Logs

```
2021-03-30T08:45:50.516Z cypress:server:plugins plugins process error: Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
--
  | at ChildProcess.target.send (internal/child_process.js:679:16)
  | at Object.send (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/util.js:28:25)
  | at EventEmitter.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:47:16)
  | at EventEmitter.emit (events.js:327:22)
  | at Object.removeFile (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:121:17)
  | at Object.options.onBrowserClose (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/open_project.js:121:28)
  | at EventEmitter.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:213:19)
  | at Object.onceWrapper (events.js:421:28)
  | at EventEmitter.emit (events.js:327:22)
  | at BrowserWindow.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:400:25)
  | at Object.onceWrapper (events.js:422:26)
  | at BrowserWindow.emit (events.js:327:22)
  | at tryToCall (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:28:27)
  | at EventEmitter.kill (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:409:20)
  | at /root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:34:14
  | at Promise.cancellationExecute [as _execute] (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
  | at Promise._resolveFromExecutor (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
  | at new Promise (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
  | at Object.kill [as close] (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:21:10)
  | at Object.closeBrowser (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/open_project.js:273:23)
  | at /root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/modes/run.js:1161:25
  |  
  |  
  | The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/testing/cypress/plugins/index.js`)
  |  
  | Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
  | at ChildProcess.target.send (internal/child_process.js:679:16)
  | at Object.send (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/util.js:28:25)
  | at EventEmitter.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:47:16)
  | at EventEmitter.emit (events.js:327:22)
  | at Object.removeFile (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:121:17)
  | at Object.options.onBrowserClose (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/open_project.js:121:28)
  | at EventEmitter.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:213:19)
  | at Object.onceWrapper (events.js:421:28)
  | at EventEmitter.emit (events.js:327:22)
  | at BrowserWindow.<anonymous> (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:400:25)
  | at Object.onceWrapper (events.js:422:26)
  | at BrowserWindow.emit (events.js:327:22)
  | at tryToCall (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:28:27)
  | at EventEmitter.kill (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:409:20)
  | at /root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:34:14
  | at Promise.cancellationExecute [as _execute] (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
  | at Promise._resolveFromExecutor (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
  | at new Promise (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
  | at Object.kill [as close] (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/browsers/index.js:21:10)
  | at Object.closeBrowser (/root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/open_project.js:273:23)
  | at /root/.cache/Cypress/6.6.0/Cypress/resources/app/packages/server/lib/modes/run.js:1161:25
  |  
```

### Versions
6.6.0

**Comment by jennifer-shehane** [comment]
You should only have one `on` listener per event. The second `on` listener, which has the same name of `task` will overwrite the second on. You need one `on` listener with several tasks within it. 

I'm not sure if that's what's causing the crash because I cannot recreate the issue with the code given. Please provide the test code to run - when the crash happens.

```js
/// <reference types="cypress" />
const fs = require('fs');
const request = require('request');

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('before:run', (details) => {
    // This will  generate test txt files
    const dateTime = new Date().toLocaleString().replace(',', '');
    for (let fileName of ["createData", "updateData", "TC08_createData"]) {
      const reqFile = require(`../fixtures/AU/${fileName}.json`);
      reqFile.merchantReference = fileName + '-' + 'SAU' + '-' + dateTime;
      const jsonString = JSON.stringify(reqFile, null, 2)
      fs.writeFile(`./cypress/fixtures/AU/${fileName}.txt`, jsonString, err => {
        if (err) {
          return reject(err);
        }
      })
    }
  })

  on('task', {
    // This task is to fetch secrets from AWS Secrets Manager
    getSecrets() {
      return new Promise((resolve, reject) => {
        const testType = 'AU';
        var arnMap = {
          AU: 'AXXlPR',
          US: 'BE0aKo'
        };
        // Load the AWS SDK and fetch secrets based on environment variable
        var AWS = require('aws-sdk'),
          region = "ap-southeast-2",
          secretName = `arn:aws:secretsmanager:ap-southeast-2:123456789:secret:${arnMap[testType]}`;

        // Create a Secrets Manager client
        var client = new AWS.SecretsManager({
          region: region
        });

        // Fetch secrets
        client.getSecretValue({ SecretId: secretName }, function (err, data) {
          if (err) {
            return reject(err);
          }
          const secretValues = data.SecretString;
          const secretString = JSON.parse(secretValues);
          resolve(secretString);
        })
      })
    },
    // This task is to get phone code from stub
    getMobileCode({ mobileStub }) {
      return new Promise((resolve, reject) => {
        request(`${mobileStub}`, { json: true }, (err, res, body) => {
          if (err) { return reject(err); }
          var codes = (body.content.match(/\d{6}/) || [false])[0];
          resolve(codes);
        });
      })
    }
  })
}
```

**Comment by jithinjosejacob** [comment]
@jennifer-shehane - Can you please let me know a simple example for one on listener per event. I have used one on listener for before run hook and one on listener for 2 tasks in the above example

**Comment by jithinjosejacob** [comment]
Detailed logging indicates that this issue is related to already logged issue - https://github.com/cypress-io/cypress/issues/15434
