### ISSUE TITLE
Cypress on CI, always report a not visible issue

### ISSUE THREAD

**Issue by WishQi** [cypress-io/cypress#15803]
Run cypress locally, it is all right. But run on CI, the element is always not visible. It is wired.

I started a server locally in CI, and run cypress
```
nohup yarn start >1.log 2>&1 & npx wait-on http-get://localhost:4000/
npx cypress run
```

And then I get the following errors.

> CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is not visible:
`<div class="pages-plus">...</div>`
This element `<div.pages-plus>` is not visible because its parent `<div.page-header>` has CSS property: `visibility: hidden`
Fix this problem, or use `{force: true}` to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureVisibility (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:162564:24)
      at runAllChecks (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:151399:14)
      at retryActionability (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:151453:16)
      at tryCatcher (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:10765:23)
      at Function.Promise.attempt.Promise.try (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8039:29)
      at tryFn (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:167065:21)
      at whenStable (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:167103:12)
      at http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:166598:16
      at tryCatcher (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:10765:23)
      at Promise._settlePromiseFromHandler (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8700:31)
      at Promise._settlePromise (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8757:18)
      at Promise._settlePromise0 (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8802:10)
      at Promise._settlePromises (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8882:18)
      at Promise._fulfill (http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:8826:18)
      at http://ratio.bytedance.local/__cypress/runner/cypress_runner.js:10440:46

On my own computer, there is no this problem.

**Comment by bahmutov** [comment]
We'll have to close this issue until we can reproduce it.

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by bahmutov** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI
