### ISSUE TITLE
Add support for detecting Flatpak-installed browsers

### ISSUE THREAD

**Issue by softshipper** [cypress-io/cypress#15843]
Dear cypress team,

I would like to test my components with cypress but it does not work as expected. When starting the test, I have got the following error:
```
npx cypress open-ct --browser chromium

(node:44501) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error: Can't run because you've entered an invalid browser name.

Browser: 'chromium' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
 {
  isCypressErr: true,
  type: 'BROWSER_NOT_FOUND_BY_NAME',
  details: undefined
}
Error: Can't run because you've entered an invalid browser name.

Browser: 'chromium' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)

Done in 10.55s.
```
I have attached the files and folders.
[components.zip](https://github.com/cypress-io/cypress/files/6270667/components.zip)
I am using RollupJS, maybe that causes the problem.

I am using Visual Studio Code

Thanks

**Comment by agg23** [comment]
Do you have Chromium installed? According to the error message, you only have Firefox and Electron available.

**Comment by softshipper** [comment]
Yes I have chromium installed:
![Screenshot from 2021-04-07 16-50-37](https://user-images.githubusercontent.com/56756949/113887121-84f40900-97c1-11eb-974e-52d6b61315de.png)
I use https://pop.system76.com/ as OS

**Comment by softshipper** [comment]
@agg23 Did you download the attached file? If not, you should do it.

**Comment by agg23** [comment]
Your project config should not affect the browsers detected by Cypress. Could you try running that same command with the `DEBUG=cypress:server:browsers` envvar set and post the terminal output?

**Comment by softshipper** [comment]
When I would start Chromium through the console, I have to enter:
```
flatpak run org.chromium.Chromium 
```
in the terminal. I could not find the path from Chromium browser.

**Comment by softshipper** [comment]
```


> Your project config should not affect the browsers detected by Cypress. Could you try running that same command with the `DEBUG=cypress:server:browsers` envvar set and post the terminal output?

```
 DEBUG=cypress:server:browsers
❯ yarn run cypress
yarn run v1.22.10
$ npx cypress open-ct
(node:14573) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error: Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
 {
  isCypressErr: true,
  type: 'BROWSER_NOT_FOUND_BY_NAME',
  details: undefined
}
Error: Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)

Done in 2.02s.
  ~/projects/openidea/webapp/components ❯                                                                                                                                                                                    17:40:28
```

**Comment by softshipper** [comment]
> @agg23 Did you download the attached file? If not, you should do it.

**Comment by softshipper** [comment]
@agg23  Sorry I have pressed wrong button.

**Comment by agg23** [comment]
What do you expect me to see if I download the attached project?

It appears that we do not currently support `flatpak` browser detection due to flatpaked programs not appearing in path. If you can assign `flatpak run org.chromium.Chromium` to an alias or a standalone executable in `$PATH`, the autodetection may work.

**Comment by softshipper** [comment]
> What do you expect me to see if I download the attached project?
I would like to know if it works on your computer.

> It appears that we do not currently support `flatpak` browser detection due to flatpaked programs not appearing in path. If you can assign `flatpak run org.chromium.Chromium` to an alias or a standalone executable in `$PATH`, the autodetection may work.

The problem is about browser detection? I will try it.

**Comment by agg23** [comment]
> I would like to know if it works on your computer.

This is unrelated to the issue, but you need to choose a dev server and packaging mechanism for Component Testing. We would recommend Webpack, so you will need to `yarn add -D webpack webpack-dev-server html-webpack-plugin@4` and provide a proper config to `plugins/index.js`. See https://docs.cypress.io/guides/component-testing/introduction#Install, which provides the example `plugins/index.js`:

```// cypress/plugins/index.js
const { startDevServer } = require('@cypress/webpack-dev-server')
// your project's webpack configuration
const webpackConfig = require('../../webpack.config.js')

module.exports = (on, config) => {
  if (config.testingType === 'component') {
    on('dev-server:start', (options) => {
      return startDevServer({ options, webpackConfig })
    })
  }

  return config
}
```

**Comment by agg23** [comment]
> When I would assign an alias or a standalone executable in $PATH, then how to run Cypress?

Once you've assigned the alias, continue running Cypress as you were.

**Comment by softshipper** [comment]
How should I name the alias? Chromium?

**Comment by softshipper** [comment]
Do I get our correctly, I have to install `html-webpack-plugin` version 4 right?

**Comment by agg23** [comment]
> How should I name the alias? Chromium?
Yes, it should be named `chromium-browser` or `chromium`

**Comment by softshipper** [comment]
I have set the alias as follows:
```
alias chromium="flatpak run org.chromium.Chromium"
```
and the scripts:
```
"scripts": {
    "build": "rollup --config",
    "cypress": "npx cypress open-ct --browser chromium"
  },
```
still error:
```
$ npx cypress open-ct --browser chromium
(node:41605) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error: Can't run because you've entered an invalid browser name.

Browser: 'chromium' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
 {
  isCypressErr: true,
  type: 'BROWSER_NOT_FOUND_BY_NAME',
  details: undefined
}
Error: Can't run because you've entered an invalid browser name.

Browser: 'chromium' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- firefox
- electron
    at get (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:995:15)
    at Object.throwErr [as throw] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/errors.js:1013:9)
    at throwBrowserNotFound (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:140:22)
    at /home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/server/lib/browsers/index.js:123:12
    at tryCatcher (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/developer/.cache/Cypress/7.0.0/Cypress/resources/app/packages/launcher/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by softshipper** [comment]
@agg23 I have also tried `chromium-browser` and still does not work. It outputs the same error message.
I am using:
`"cypress": "^7.0.0",`

**Comment by agg23** [comment]
#15837 is unrelated. Your alias is most likely not accessible to Cypress. Just make a `bash` script named `chromium` and put it in your path.

**Comment by softshipper** [comment]
I have created and where should I put it exactly?

**Comment by softshipper** [comment]
I found the solution:
```
"cypress": "npx cypress open-ct --browser ~/.local/share/flatpak/app/org.chromium.Chromium/x86_64/stable/active/export/bin/org.chromium.Chromium"
```
Thanks a lot for your help @agg23

**Comment by agg23** [comment]
This is still an issue that we should solve. Reopening

**Comment by skomorokh** [comment]
Pointing cypress at the binary directly probably won't be invoking it through flatpak and thus not within the sandbox the user is expecting the browser to run under on their system.

Seems there's a similar problem with snap and that a shell script is refused and it insists on needing the bin:
https://github.com/cypress-io/cypress/issues/3183#issuecomment-546999050

flatpak (and presumably snap) flow through any options to the underlying browser, but would that suffice for cypress' integration or does it do more than pass options to the command? eg. is all that's needed here a mechanism to detect the the packages and invoke them via the wrapper or are these systems more deeply incompatible?

**Comment by jennifer-shehane** [comment]
Since this has not had a lot of interest over the years, we’ll close this as not planned.

**Comment by marinofra** [comment]
for anyone reading this, a workaround that enabled me to autodiscover every flatpak browser i had installed inside cypress is the following:

1. create shims for the flatpak apps, you can use [this script](https://github.com/ronoaldo/tools/blob/master/bin/flatpak-gen-shims) to autgenerate them
2. add the shim directory to PATH in `.profile` / `.bash_profile`
3. Use a tool like `flatseal` to provide access to the user home directory for the flatpak apps that couldn't start because of missing access to the cypress config directory (Firefox in my case)
