### ISSUE TITLE
[7.0.1]Error: The plugins file is missing or invalid

### ISSUE THREAD

**Issue by softshipper** [cypress-io/cypress#15874]
Hi all  

When I try to run the component test, I have got the following error:
```
$ npx cypress open-ct --browser ~/chromium
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/developer/projects/openidea/webapp/components/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at EventEmitter.<anonymous> (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
 {
  isCypressErr: true,
  type: 'PLUGINS_FILE_ERROR',
  details: "Error: Cannot find module '../../webpack.config.js'\n" +
    'Require stack:\n' +
    '- /home/developer/projects/openidea/webapp/components/cypress/plugins/index.js\n' +
    '- /home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js\n' +
    '- /home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:732:27)\n' +
    '    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:959:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
    '    at Object.<anonymous> (/home/developer/projects/openidea/webapp/components/cypress/plugins/index.js:20:23)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1078:30)\n' +
    '    at Module.m._compile (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)\n' +
    '    at Module._extensions..js (internal/modules/cjs/loader.js:1108:10)\n' +
    '    at Object.require.extensions.<computed> [as .js] (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:935:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:776:14)\n' +
    '    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:959:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
    '    at runPlugins (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:175:15)'
}
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/developer/projects/openidea/webapp/components/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at EventEmitter.<anonymous> (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/index.js:154:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/developer/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Done in 3.08s.
```
The project files:
[components.zip](https://github.com/cypress-io/cypress/files/6278725/components.zip)

Thanks

**Comment by agg23** [comment]
>   details: "Error: Cannot find module '../../webpack.config.js'\n"

Your `plugins/index.js` file is attempting to import a Webpack config that does not exist. You can either provide no config, or make a minimal config by following [Webpack's Getting Started Guide](https://webpack.js.org/guides/getting-started/)

**Comment by softshipper** [comment]
@agg23 I am using RollupJS. How to use RollupJS instead of Webpack?

**Comment by agg23** [comment]
Rollup is a build system for libraries. It doesn't have a concept of a server, and we have not built one specifically for Rollup. Hence, you need to run at least a minimal Webpack config so we can start a server. Like I said, you don't need much (or even anything) in your Webpack config.

**Comment by softshipper** [comment]
It is a little bit difficult to figure out, what exactly do I need. @agg23 For sure you know better than me.

**Comment by agg23** [comment]
Your `plugins/index.js` should look like:

```
module.exports = (on, config) => {
  if (config.testingType === 'component') {
    on('dev-server:start', (options) => {
      return startDevServer({ options, webpackConfig })
    })
  }

  return config
}
```

where `webpackConfig` is your Webpack config. Following https://webpack.js.org/guides/getting-started/ will tell you how to create a Webpack config, but you may not need one, so you can simply try `return startDevServer({ options, webpackConfig })`

**Comment by agg23** [comment]
@softshipper please see my previous comment

**Comment by softshipper** [comment]
@agg23 One more question.
I can see now the test file: 
![Screenshot from 2021-04-08 21-28-40](https://user-images.githubusercontent.com/56756949/114085516-c532b480-98b1-11eb-93c6-26321003fe0d.png)
When I click on the `Foo.spec.tsx` it shows **Your tests are loading**. It does not stop. 
What is missing?  
Here are the files.
[components.zip](https://github.com/cypress-io/cypress/files/6281011/components.zip)

**Comment by lmiller1990** [comment]
I pulled your repo and made one change to `tsconfig.json`. You need to remove `"noEmit": true`. Then it worked!

![image](https://user-images.githubusercontent.com/19196536/114331972-8ab66980-9b88-11eb-8f15-2cd79af687eb.png)

The very first test shows this error in the console for some reason (Cypress internal) but it seems you can safely ignore this.

![image](https://user-images.githubusercontent.com/19196536/114331993-986bef00-9b88-11eb-89e6-ae5954ded221.png)

 I'll look into this console error, but for now the original problem is resolved (we only have support for projects using webpack or soon, vite) so I will close this.

Making a rollup-dev-server plugin is likely not too difficult, but more of a mid term goal - for now the focus is on making the webpack dev server as robust and efficient as possible

If you find any more issues, comment and I'll do my best to help figure them out.
