### ISSUE TITLE
Error: It is required to register dev-server plugin that implements `dev-server:start` event for component testing.

### ISSUE THREAD

**Issue by gbaah** [cypress-io/cypress#15890]
### Current behavior

I have enabled cypress e2e testing it works seamlessly. However, I am running into issues when trying to enable and use the new cypress component testing. I followed the directions in the cypress doc. but to no avail. Below is the error I am getting .

$ npm run cypress:open-ct

> MyApp@3.0.0 cypress:open-ct c:\myapp\client
> cypress open-ct

Error: It is required to register dev-server plugin that implements `dev-server:start` event for component testing.
    at Object.start (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\lib\plugins\dev-server.js:36:13)
    at C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server-ct\src\project-ct.js:108:45
    at tryCatcher (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:127:19)
    at MappingPromiseArray.init (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:75:18)
    at Promise._settlePromise (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

Error: It is required to register dev-server plugin that implements `dev-server:start` event for component testing.
    at Object.start (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\lib\plugins\dev-server.js:36:13)
    at C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server-ct\src\project-ct.js:108:45
    at tryCatcher (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:127:19)
    at MappingPromiseArray.init (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:75:18)
    at Promise._settlePromise (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\tester\AppData\Local\Cypress\Cache\7.0.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
### Test code to reproduce
//This is what is in my cypress/plugins/index.js 
```

const { startDevServer } = require('@cypress/webpack-dev-server')

const webpackConfig = require('../../../../webpack.config.js') 

  module.exports = (on, config) => { 
 ​if (config.testingType === 'component') {
   on('dev-server:start', (options) => {
        return startDevServer({ options, webpackConfig })
   })  
 }
 return config
}
```

### Versions
Cypress ver: ^7.00
OS: Windows 10 server

**Comment by lmiller1990** [comment]
Hi! Thanks for trying out the new component testing runner.

There is a [known issue with windows](https://github.com/cypress-io/cypress/pull/15889) which will be released next week. That said, you should be getting further than you are with your config. Are you able to share your repository? From what I can see, everything looks completely fine.

There is also [a demo repository available](https://github.com/lmiller1990/cypress-react-template), that might give you some further clues.

**Comment by gbaah** [comment]
Hi, Thanks for responding. I will try the demo to see if I get the same error.

**Comment by gbaah** [comment]
I was able to make some progress but I run into this error on both the  cypress react template demo and my own sample test app. The error appears to be a path issue. I wonder whether it's related to [issue 15889](https://github.com/cypress-io/cypress/pull/15889).

```
ERROR in ./node_modules/@cypress/webpack-dev-server/dist/browser.js                                                      
Module not found: Error: Can't resolve 'c:test
demosmy_app                                                                                   
ode_moduleslazy-compile-webpack-pluginlibloadersapi.js' in 'c:\test\demos\my_app\node_modules\@cypress\webpack-dev-server\dist'                                                                                      
@ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:10-133    
```

**Comment by lmiller1990** [comment]
Ahhhh yes it looks likee it might be the same issue - clearly that path is supposed to be `c://test/demos/my_app`. That patch will be released this week, let's see if it fixes it.

**Comment by gbaah** [comment]
Awesome, thanks!

**Comment by blackgrouse** [comment]
> I was able to make some progress but I run into this error on both the cypress react template demo and my own sample test app. The error appears to be a path issue. I wonder whether it's related to [issue 15889](https://github.com/cypress-io/cypress/pull/15889).
> 
> ```
> ERROR in ./node_modules/@cypress/webpack-dev-server/dist/browser.js                                                      
> Module not found: Error: Can't resolve 'c:test
> demosmy_app                                                                                   
> ode_moduleslazy-compile-webpack-pluginlibloadersapi.js' in 'c:\test\demos\my_app\node_modules\@cypress\webpack-dev-server\dist'                                                                                      
> @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js 3:10-133    
> ```

I'm getting this with Cypress 7.1.0

**Comment by lmiller1990** [comment]
What version of `@cypress/webpack-dev-server` are you on? We removed this plugin for various reasons (like, a day or two ago, due to various problems it was causing).

Can you add the latest `@cypress/webpack-dev-server` and try again? You might want to delete your `node_modules` to make sure no cache is hanging around (or run `yarn cache clean`, I think that'll do the same thing).

**Comment by blackgrouse** [comment]
@lmiller1990 Thanks, upgrading to @cypress/webpack-dev-server v1.1.3 fixed it
