### ISSUE TITLE
[7.0.1]Bug: cy.intercept POST terminates cypress process

### ISSUE THREAD

**Issue by njh7799** [cypress-io/cypress#15901]
## Simplified reproduction

https://github.com/bahmutov/cypress-15901-bug

### presettings
- The code includes POST request with Chineese words inside it's body (Chineese words should be long enough)
```html
<script>
    fetch('http://localhost:5000/api/sample', {
    method: 'POST', body: JSON.stringify({first: '東京都新東', second: '東京都新'})})
</script>
```
- use `cy.intercept` in the test with the API above
```
cy.intercept('POST', 'http://localhost:5000/api/sample');
```

### Result
If I run Cypress, it's process is terminated with error messages
![cypress-intercept-bug](https://user-images.githubusercontent.com/40619551/114158693-f1a50a00-995f-11eb-80a9-308332661720.gif)
```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (123)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/Users/user/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /Users/user/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/Users/user/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/Users/user/Library/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
![image](https://user-images.githubusercontent.com/40619551/114159754-1a79cf00-9961-11eb-9728-04eaf1d1d95b.png)

### Desired behavior
Cypress test process must not be terminated.

### Test code to reproduce

https://github.com/njh7799/cypress7.0-intercept-post-bug

### Versions

Cypress version: 7.0.1
OS: MAC Big Sir

**Comment by bahmutov** [comment]
Interesting, confirmed it crashes. Also, it crashes when the page posts
```
JSON.stringify({first: '東京都新東'})
```

but does not crash if we post
```js
JSON.stringify({first: 'hello'})
```

**Comment by bahmutov** [comment]
Works in 6.8.0, crashes in v7

**Comment by edant92** [comment]
Just to confirm, I also have this issue in `7.0.0` and `7.0.1`

**Comment by donalmurtagh** [comment]
I don't think the Chinese characters are relevant. I observed the same problem when making a HTTP POST containing only Latin (English) characters. The problem occurs after upgrading from 6.8.0 to 7.0.1. I've described the problem in a bit more detail on [Stackoverflow](https://stackoverflow.com/questions/67023339/error-making-http-post-with-file-in-request-body)

**Comment by bahmutov** [comment]
Comparing the debug messages during crash vs non-crash

## Crash

```
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "451-["net:event","before:request",{"eventId":"event2","subscription":{"eventName":"before:request","await":false,"routeId":"1618242756221-4"},"requestId":"interceptedRequest1","data":{"headers":{"host":"localhost:5000","proxy-connection":"keep-alive","content-length":"27","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/0.0.0-development Chrome/89.0.4389.90 Electron/12.0.2 Safari/537.36","content-type":"text/plain;charset=UTF-8","accept":"*/*","origin":"http://localhost:64365","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:64365/","accept-encoding":"gzip, deflate, br","accept-language":"en-US"},"url":"http://localhost:5000/api/sample","method":"POST","httpVersion":"1.1","body":{"_placeholder":true,"num":0}}}]" +81ms
  engine:socket sending packet "message" ({"first":"東京都新東"}) +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfUnloaded' } +5ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'EndRequestsToBlockedHosts' } +1ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'StripUnsupportedAcceptEncoding' } +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeSetBasicAuthHeaders' } +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing' } +1ms
  engine:socket flushing buffer to transport +5ms
  engine:ws writing "{"first":"東京都新東"}" +5ms
```

Notice the `"body":{"_placeholder":true,"num":0}}}]` part

## No crash

```
  engine:socket sending packet "message" (2["net:event","before:request",{"eventId":"event2","subscription":{"eventName":"before:request","await":false,"routeId":"1618242780023-4"},"requestId":"interceptedRequest1","data":{"headers":{"host":"localhost:5000","proxy-connection":"keep-alive","content-length":"17","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/0.0.0-development Chrome/89.0.4389.90 Electron/12.0.2 Safari/537.36","content-type":"text/plain;charset=UTF-8","accept":"*/*","origin":"http://localhost:64384","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:64384/","accept-encoding":"gzip, deflate, br","accept-language":"en-US"},"url":"http://localhost:5000/api/sample","method":"POST","httpVersion":"1.1","body":"{\"first\":\"hello\"}"}}]) +82ms
  engine:socket flushing buffer to transport +1ms
  engine:ws writing "42["net:event","before:request",{"eventId":"event2","subscription":{"eventName":"before:request","await":false,"routeId":"1618242780023-4"},"requestId":"interceptedRequest1","data":{"headers":{"host":"localhost:5000","proxy-connection":"keep-alive","content-length":"17","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/0.0.0-development Chrome/89.0.4389.90 Electron/12.0.2 Safari/537.36","content-type":"text/plain;charset=UTF-8","accept":"*/*","origin":"http://localhost:64384","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:64384/","accept-encoding":"gzip, deflate, br","accept-language":"en-US"},"url":"http://localhost:5000/api/sample","method":"POST","httpVersion":"1.1","body":"{\"first\":\"hello\"}"}}]" +83ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfUnloaded' } +5ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'EndRequestsToBlockedHosts' } +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'StripUnsupportedAcceptEncoding' } +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeSetBasicAuthHeaders' } +0ms
  cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing' } +1ms
  cypress:network:agent addRequest called { isHttps: false, href: 'http://localhost:5000/api/sample' } +110ms
  cypress:network:agent got family { family: 4, href: 'http://localhost:5000/api/sample' } +0ms
  engine:ws received "42["mocha","pass",{"id":"r3","order":1,"title":"dd","state":"passed","body":"() => {\n    cy.intercept('POST', 'http://localhost:5000/api/sample'); // cy.visit('http://localhost:5000')\n\n    cy.visit('public/index.html');\n  }","type":"test","duration":202,"wallClockStartedAt":"2021-04-12T15:52:59.992Z","timings":{"lifecycle":26,"test":{"fnDuration":175,"afterFnDuration":1}},"file":null,"invocationDetails":{"function":"Suite.eval","fileUrl":"http://localhost:64384/__cypress/tests?p=cypress/integration/spec.js","originalFile":"webpack:///cypress/integration/spec.js","relativeFile":"cypress/integration/spec.js","absoluteFile":"/Users/gleb/git/cypress7.0-intercept-post-bug/cypress/integration/spec.js","line":2,"column":5,"whitespace":"    "},"final":true,"currentRetry":0,"retries":0}]" +17ms
```

Notice the same message with `"body":"{\"first\":\"hello\"}"}`

Running with debug logs `DEBUG=engine:socket,cypress:proxy*,cypress:network*,engine:ws`

**Comment by bahmutov** [comment]
Digging under the hood, we decide to treat the crashing JSON object as binary, which breaks the request. If we treat the posted `req.body` as utf8 then everything is fine. We determine if the buffer is binary or utf8 by using module [istextorbinary](https://github.com/bevry/istextorbinary)

which has a nice open issue with exactly our scenario https://github.com/bevry/istextorbinary/issues/13

**Comment by smfelsher** [comment]
I was running into this issue in v7.0.1 while `POST`ing `FormData` (testing file uploads). As a temporary workaround, I used `cy.server()` and `cy.route()` to spy on the response. Cypress did not crash using these (**deprecated)** commands.

**Comment by johnnyperkins** [comment]
It's a shame `cy.route()` is being deprecated as it's been nothing but issues since switching to `intercepts`

**Comment by flotwig** [comment]
@johnnyperkins `cy.route` will continue to be available as a plugin even once it's removed from core, don't feel like you must convert everything to `cy.intercept`. `cy.intercept` is a huge new API surface and we appreciate your patience as we continue to fix issues and improve the experience.
