### ISSUE TITLE
Intercept times out on circeCI every single time.

### ISSUE THREAD

**Issue by fila90** [cypress-io/cypress#15957]
Greetings,

I have a bit tricky issue to pinpoint but `cy.intercept` times out on circleCI every single time. 
When ran locally on my machine (with `open` and `run`) everything passes with no issues.

We use `graphql` so we're intercepting queries according to your docs
```js
cy.intercept('POST', '/graphql', (req) => {
  if (req.body.operationName === operationName) {
    req.alias = operationName;
  }
});
```
This was working great until the refactor to `intercept` in version 7. 
### Current behaviour

Every single `cy.intercept` will time out on circleCI with same error (except the `route:` name)
```
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `ProposalUpdate`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3050/__cypress/runner/cypress_runner.js:153363:18)
    at Object.errByPath (http://localhost:3050/__cypress/runner/cypress_runner.js:153432:10)
    at checkForXhr (http://localhost:3050/__cypress/runner/cypress_runner.js:140376:33)
    at http://localhost:3050/__cypress/runner/cypress_runner.js:140399:28
    at tryCatcher (http://localhost:3050/__cypress/runner/cypress_runner.js:10747:23)
    at Function.Promise.attempt.Promise.try (http://localhost:3050/__cypress/runner/cypress_runner.js:8021:29)
    at tryFn (http://localhost:3050/__cypress/runner/cypress_runner.js:146270:21)
    at whenStable (http://localhost:3050/__cypress/runner/cypress_runner.js:146308:12)
    at http://localhost:3050/__cypress/runner/cypress_runner.js:145803:16
    at tryCatcher (http://localhost:3050/__cypress/runner/cypress_runner.js:10747:23)
    at Promise._settlePromiseFromHandler (http://localhost:3050/__cypress/runner/cypress_runner.js:8682:31)
    at Promise._settlePromise (http://localhost:3050/__cypress/runner/cypress_runner.js:8739:18)
    at Promise._settlePromise0 (http://localhost:3050/__cypress/runner/cypress_runner.js:8784:10)
    at Promise._settlePromises (http://localhost:3050/__cypress/runner/cypress_runner.js:8864:18)
    at Promise._fulfill (http://localhost:3050/__cypress/runner/cypress_runner.js:8808:18)
    at http://localhost:3050/__cypress/runner/cypress_runner.js:10422:46

```
### Desired behaviour

I would expect it to work as before, as only solution now is to downgrade to 6.8.0

### Test code to reproduce

I would assume any intercept to `/graphql` ran on circleCI

### Versions
working version: 6.8.0
broken versions: 7.0.1, 7.1.0
CI Provider: circleCI
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64

Any advice how to make it work on circleCI again would be helpful.

Thanks.

**Comment by fila90** [comment]
@jennifer-shehane  still the same, I'll try to prepare a demo for you

**Comment by jennifer-shehane** [comment]
This makes sense. Thanks for the update!
