### ISSUE TITLE
cy.request() throwing connection error on 303 response (or oauth redirect)

### ISSUE THREAD

**Issue by cormack00** [cypress-io/cypress#16063]
Hi. I am running tests where I'm just using cy.request() to hit a bunch of urls and assert that eventually they'll return a 200. 
I'm getting a network error on one of these urls. cURL is working perfectly fine, as is just putting the url in the browser. 
It gets as far as the 303, and then returns a connection error (see logs below).

I unfortunately cannot provide you with the actual url, but the redirects behave as follows (from redirect.org):

```
_Result_
https://www.REDACTED.com/path/app?lang=de
_302 Found_
path/app/Assurance?login&lang=de
_302 Found_
https://login.sso.REDACTED.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2path%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop
_301 Moved Permanently_
https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2path%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop
_303 See Other_
https://login.xyz.redacted.com/login?loginRequest=hashedtoken==
200 OK
```

### Current behavior

Cypress ERROR:
```  
cypress:server:request received an error making http request { 
  url: 'https://www.REDACTED.com/path/app?lang=de', 
  method: 'GET', 
  encoding: 'utf8', 
  gzip: true, 
  timeout: 30000, 
  failOnStatusCode: false, 
  retryOnNetworkFailure: true, 
  retryOnStatusCodeFailure: false, 
  headers: { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.8.0 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36', accept: '*/*' }, 
  cookies: true, 
  simple: false, 
  resolveWithFullResponse: true, 
  followAllRedirects: true, 
  requestId: 'request10', 
  retryIntervals: [ 0, 1000, 2000, 2000 ], 
  delaysRemaining: [ 2000 ], 
  err: Error: read ECONNRESET     
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {  
    errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' 
  } 
} +140ms
```
Cypress LOGS:
```
cypress:network:agent addRequest called { isHttps: true, href: 'https://www.redacted.com/path/app?login&lang=de' } +167ms
cypress:network:agent got family { family: 4, href: 'https://www.redacted.com/path/app?login&lang=de' } +0ms
cypress:server:request setting cookies on browser { url: 'https://bwsso.login.xyz.redacted.com/path/app?login&lang=de', defaultDomain: 'bwsso.login.xyz.redacted.com', cookies: [ 'scssecel=bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-; Path=/; Secure; HttpOnly', 'TS01d1b068=01603584da1b7def03d056dad8599882f26ea23cec34fe64f22b6d6ab7cef185533ba8a511c5eb410c9ab6e0edc45658787065aabd; Path=/; Domain=.www.redacted.com; Secure' ] } +177ms
cypress:server:request parsing cookie { cyCookie: 'scssecel=bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-; Path=/; Secure; HttpOnly', toughCookie: Cookie="scssecel=bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-; Path=/; Secure; HttpOnly; hostOnly=?; aAge=?; cAge=0ms" } +1ms
cypress:server:request parsing cookie { cyCookie: 'TS01d1b068=01603584da1b7def03d056dad8599882f26ea23cec34fe64f22b6d6ab7cef185533ba8a511c5eb410c9ab6e0edc45658787065aabd; Path=/; Domain=.www.redacted.com; Secure', toughCookie: Cookie="TS01d1b068=01603584da1b7def03d056dad8599882f26ea23cec34fe64f22b6d6ab7cef185533ba8a511c5eb410c9ab6e0edc45658787065aabd; Domain=www.redacted.com; Path=/; Secure; hostOnly=?; aAge=?; cAge=0ms" } +0ms
cypress:server:request domain match failed: { defaultDomain: 'bwsso.login.xyz.redacted.com' } +0ms
cypress:server:automation:cookies set:cookie { name: 'scssecel', value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: true, hostOnly: true, sameSite: undefined, url: 'https://bwsso.login.xyz.redacted.com/' } +178ms
cypress:server:browsers:electron debugger: sending Network.setCookie with params { domain: 'bwsso.login.xyz.redacted.com', path: '/', secure: true, httpOnly: true, name: 'scssecel', value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-' } +179ms
cypress:server:browsers:electron debugger: received response to Network.setCookie: { success: true } +0ms
cypress:server:browsers:electron debugger: sending Network.getAllCookies with params undefined +0ms
cypress:server:browsers:electron debugger: received response to Network.getAllCookies: { cookies: [ { domain: '.everesttech.net', expires: 1634117354.339762, httpOnly: false, name: 'everest_g_v2', path: '/', priority: 'Medium', secure: false, session: false, size: 39, value: 'g_surferid~XaQ-5wAAFC5s7zx0' }, { domain: '.twitter.com', expires: 1634117353.594835, httpOnly: false, name: 'personalization_id', path: '/', priority: 'Medium', secure: false, session: false, size: 47, value: '"v1_gsEW3aYWS5NR8CxtF49FwQ=="' }, { domain: '.revjet.com', expires: 1634117353.602198, httpOnly: false, name: 'trx', path: '/', priority: 'Medium', secure: false, session: false, size: 22, value: '4872674919346446464' }, { domain: 'on.cypress.io', expires: 1887895765.644924, httpOnly: false, name: '_on', path: '/', priority: 'Medium', secure: false, session: false, size: 39, value: 'e4ddfb13-9760-4b9d-a50e-319db183fedf' }, { domain: '.cypress.io', expires: 1679844138, httpOnly: false, name: '_ga', path: '/', priority: 'Medium', secure: false, session: false, size: 30, value: 'GA1.2.1643615279.1572535767' }, { domain: '.cypress.io', expires: 1649259776, httpOnly: false, name: 'hubspotutk', path: '/', priority: 'Medium', sameSite: 'Lax', secure: false, session: false, size: 42, value: '82c1dfdb861db71ec3378a5463497078' }, { domain: '.cypress.io', expires: 1636818944, httpOnly: false, name: '_hjid', path: '/', priority: 'Medium', sameSite: 'Lax', secure: false, session: false, size: 41, value: '6c2e8dc8-ec6d-47a9-a9c6-fa71e0063b75' }, { domain: '.cypress.io', expires: 1648308138, httpOnly: false, name: 'cb_user_id', path: '/', priority: 'Medium', secure: false, session: false, size: 14, value: 'null' }, { domain: '.cypress.io', expires: 1648308138, httpOnly: false, name: 'cb_group_id', path: '/', priority: 'Medium', secure: false, session: false, size: 15, value: 'null' }, { domain: '.cypress.io', expires: 1647099776, httpOnly: false, name: 'cb_anonymous_id', path: '/', priority: 'Medium', secure: false, session: false, size: 57, value: '%223445cc02-0b92-4a82-9e76-4653ab440463%22' }, { domain: '.cypress.io', expires: 1649259776, httpOnly: false, name: '__hstc', path: '/', priority: 'Medium', sameSite: 'Lax', secure: false, session: false, size: 92, value: '204449871.82c1dfdb861db71ec3378a5463497078.1572535766907.1605282944186.1615563776506.3' }, { domain: '.sso.redacted.com', expires: 1619365053.1, httpOnly: false, name: 'xyz-CID', path: '/', priority: 'Medium', secure: false, session: false, size: 43, value: 'd275fb8e-dc75-4bac-8674-eb29d2df684f' }, { domain: '.surveymonkey.com', expires: 1625060024, httpOnly: false, name: 'ep202', path: '/', priority: 'Medium', sameSite: 'None', secure: true, session: false, size: 33, value: 'ZAznE2PPgNWua0rJQd0yQaQo6cY=' }, { domain: '.surveymonkey.com', expires: 1625060024, httpOnly: true, name: 'ep203', path: '/', priority: 'Medium', sameSite: 'None', secure: true, session: false, size: 33, value: 'vg1vGKtU89U/n1r+Wn73044bZmo=' }, { domain: 'www.redacted.com', expires: -1, httpOnly: false, name: 'SCS_PR5FSXX2IYIOILN5IHDAQ', path: '/', priority: 'Medium', secure: true, session: true, size: 261, value: 'BFajOiwW%2BPXAD3kl365P3y8Wjx0CsEYEjGcvBZnwY1WstEUftoRblCJlTuc3iIAxpF9i3HhsnsnWEZssbRHn%2FhHzjegujEJvNhoAKINo0up7YXOWFZ96tJ%2BFEywE59T7NvzPe%2F6h3u8G7Ft%2F0BMrynD1dB81hwZfoK6Jdfmu0si4QrpQvJWQOX0bhU%2BoOvF%2BG%2BRQCBWscj5edEmeAAAAAQ%3D%3D' }, { domain: '.www.redacted.com', expires: -1, httpOnly: false, name: 'TS01d1b068', path: '/', priority: 'Medium', secure: true, session: true, size: 116, value: '01603584da7bc235e33479acfa893373ca6af023d3dccd0bf2c0194526402dac4ffe1ab4174812de1069281899c53258e235668c08' }, { domain: 'www.redacted.com', expires: -1, httpOnly: true, name: 'scssecel', path: '/', priority: 'Medium', secure: true, session: true, size: 84, value: '/ZGuFe+PjADxsmntQ75PUvpRYgp4TzXkFvLwJsOuoRsgFl7+4igMI/BzFNU5r6t6w952xoX9HKw-' }, { domain: 'bwsso.login.xyz.redacted.com', expires: -1, httpOnly: false, name: 'SCS_PR5FSXX2IYIOILN5IHDAQ', path: '/', priority: 'Medium', secure: true, session: true, size: 251, value: 'mWdUV3docjjacS4l365P3y8Wjx0CsIsbf17uas0ddRhlE7yOW1OLMHvMnZuedDt7d2dVdhg432mVvZU%2FFPofmLfmtmJj1NL0SyHlBlH8CPxRFv3Dsv3f5hb531yjcQ%2F8vP0pP7GGLnDdisWNJ9Prjqyrbh1O%2ByPwI568krOZ83QNiOkmsIuEiISQ1yRpX4uyKXOj5HONRIUsW8T0AAAAAQ%3D%3D' }, { domain: 'bwsso.login.xyz.redacted.com', expires: -1, httpOnly: true, name: 'scssecel', path: '/', priority: 'Medium', secure: true, session: true, size: 84, value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-' } ] } +1ms
cypress:server:automation:cookies received set:cookie { name: 'scssecel', value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: true, sameSite: undefined } +3ms
cypress:server:automation:cookies getting:cookies { url: 'https://login.sso.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +0ms
cypress:server:browsers:electron debugger: sending Network.getCookies with params { urls: [ 'https://login.sso.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' ] } +1ms
cypress:server:browsers:electron debugger: received response to Network.getCookies: { cookies: [ { domain: '.sso.redacted.com', expires: 1619365053.1, httpOnly: false, name: 'xyz-CID', path: '/', priority: 'Medium', secure: false, session: false, size: 43, value: 'd275fb8e-dc75-4bac-8674-eb29d2df684f' } ] } +1ms
cypress:server:automation:cookies received get:cookies [ { name: 'xyz-CID', value: 'd275fb8e-dc75-4bac-8674-eb29d2df684f', path: '/', domain: '.sso.redacted.com', secure: false, httpOnly: false, sameSite: undefined, expiry: 1619365053.1 } ] +1ms
cypress:server:request got cookies from browser { reqUrl: 'https://login.sso.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop', cookies: [ { name: 'xyz-CID', value: 'd275fb8e-dc75-4bac-8674-eb29d2df684f', path: '/', domain: '.sso.redacted.com', secure: false, httpOnly: false, sameSite: undefined, expiry: 1619365053.1 } ] } +4ms
cypress:network:agent addRequest called { isHttps: true, href: 'https://login.sso.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +182ms
cypress:network:agent got family { family: 4, href: 'https://login.sso.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +0ms
cypress:server:automation:cookies getting:cookies { url: 'https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +126ms
cypress:server:browsers:electron debugger: sending Network.getCookies with params { urls: [ 'https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' ] } +126ms
cypress:server:browsers:electron debugger: received response to Network.getCookies: { cookies: [ { domain: 'bwsso.login.xyz.redacted.com', expires: -1, httpOnly: true, name: 'scssecel', path: '/', priority: 'Medium', secure: true, session: true, size: 84, value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-' }, { domain: 'bwsso.login.xyz.redacted.com', expires: -1, httpOnly: false, name: 'SCS_PR5FSXX2IYIOILN5IHDAQ', path: '/', priority: 'Medium', secure: true, session: true, size: 251, value: 'mWdUV3docjjacS4l365P3y8Wjx0CsIsbf17uas0ddRhlE7yOW1OLMHvMnZuedDt7d2dVdhg432mVvZU%2FFPofmLfmtmJj1NL0SyHlBlH8CPxRFv3Dsv3f5hb531yjcQ%2F8vP0pP7GGLnDdisWNJ9Prjqyrbh1O%2ByPwI568krOZ83QNiOkmsIuEiISQ1yRpX4uyKXOj5HONRIUsW8T0AAAAAQ%3D%3D' } ] } +2ms
cypress:server:automation:cookies received get:cookies [ { name: 'scssecel', value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: true, sameSite: undefined }, { name: 'SCS_PR5FSXX2IYIOILN5IHDAQ', value: 'mWdUV3docjjacS4l365P3y8Wjx0CsIsbf17uas0ddRhlE7yOW1OLMHvMnZuedDt7d2dVdhg432mVvZU%2FFPofmLfmtmJj1NL0SyHlBlH8CPxRFv3Dsv3f5hb531yjcQ%2F8vP0pP7GGLnDdisWNJ9Prjqyrbh1O%2ByPwI568krOZ83QNiOkmsIuEiISQ1yRpX4uyKXOj5HONRIUsW8T0AAAAAQ%3D%3D', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: false, sameSite: undefined } ] +2ms
cypress:server:request got cookies from browser { reqUrl: 'https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%2FAssurance%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop', cookies: [ { name: 'scssecel', value: 'bsgTCaVLLvKoQDzKmk9D8Bwdf57HGkPqlSpx3pqI3kLuCWtk3wDrhdsVnLDcaY7q5BG+V2/8Gss-', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: true, sameSite: undefined }, { name: 'SCS_PR5FSXX2IYIOILN5IHDAQ', value: 'mWdUV3docjjacS4l365P3y8Wjx0CsIsbf17uas0ddRhlE7yOW1OLMHvMnZuedDt7d2dVdhg432mVvZU%2FFPofmLfmtmJj1NL0SyHlBlH8CPxRFv3Dsv3f5hb531yjcQ%2F8vP0pP7GGLnDdisWNJ9Prjqyrbh1O%2ByPwI568krOZ83QNiOkmsIuEiISQ1yRpX4uyKXOj5HONRIUsW8T0AAAAAQ%3D%3D', path: '/', domain: 'bwsso.login.xyz.redacted.com', secure: true, httpOnly: false, sameSite: undefined } ] } +129ms
cypress:network:agent addRequest called { isHttps: true, href: 'https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +129ms
cypress:network:agent got family { family: 4, href: 'https://bwsso.login.xyz.redacted.com/login?SNA=redacted&keepLogin=true&RURL=https%3A%2F%2Fwww.redacted.com%2Fpath%2Fapp%3Flogin%26lang%3Dde%26tokenconsume&L=de&pps=desktop' } +0ms
cypress:server:request received an error making http request { url: 'https://www.redacted.com/path/app?lang=de', method: 'GET', encoding: 'utf8', gzip: true, timeout: 30000, failOnStatusCode: false, retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, headers: { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.8.0 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36', accept: '*/*' }, cookies: true, simple: false, resolveWithFullResponse: true, followAllRedirects: true, requestId: 'request10', retryIntervals: [ 0, 1000, 2000, 2000 ], delaysRemaining: [], err: Error: read ECONNRESET     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } } +140ms
```

### Desired behavior
The cy.request should eventually land on the 200 response, instead of throwing a connection error.

### Test code to reproduce
my code is just: 
```js  
cy.request({
        failOnStatusCode: false,
        followRedirect: true,
        url: <link>,
      })
```

I unfortunately can't provide the exact url. But maybe it is just failing on all 303s?

### Versions

Not working in 6.8.0 or 7.1.0

**Comment by flotwig** [comment]
I think this could be a duplicate of #6921
