### ISSUE TITLE
component-testing: closing the last tab of chrome does not stop the cypress process

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16076]
### Current behavior
Running cypress open-ct then closing all the tabs in the browser does not stop the cypress server from running.

https://user-images.githubusercontent.com/5592465/115295842-d1273d80-a11f-11eb-8c0f-3cbd26b65b0c.mov

If you open a new instance of cypress then, you get the following error

```
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
...
Failed to connect to Chrome, retrying in 1 second (attempt 56/62)
Failed to connect to Chrome, retrying in 1 second (attempt 57/62)
Failed to connect to Chrome, retrying in 1 second (attempt 58/62)
```

### Desired behavior
When the tab is closed using CMD-W/Ctrl-W or using the tab closing cross button, the background process should be killed (the same way as it is when chrome is properly quit)

### Test code to reproduce
Any component testing project

### Versions

```
    "@cypress/react": "^5.3.3",
    "@cypress/vite-dev-server": "^1.2.2",
    "cypress": "^7.1.0",
    "cypress-real-events": "^1.3.0",
```

**Comment by kutenai** [comment]
I have this same issue, on Cypress 7.4.0, and 7.5.0. 
It used to work, but did not use it for a month or so, and when I tried again, it just started doing this.
I do not know what I've changed. New version of Chrome perhaps???

**Comment by elevatebart** [comment]
@kutenai are you a windows, mac or Linux user? just curious.

**Comment by kutenai** [comment]
I am on a mac.
I found it works fine with Firefox.

**Comment by kutenai** [comment]
Not sure if this will help

`**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">50662</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:50662
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)


**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m50662[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:50662
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

    at get (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:988:15)
    at Object.throwErr [as throw] (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1006:9)
    at /Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:106:21
    at tryCatcher (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/sharpertool/Users/ed/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

````

**Comment by elevatebart** [comment]
What I have seen is: it works on Windows, but not on Mac. Go figure. I still need to investigate.
Since we use a driven instance of chrome it should at least possible to fix, if not completely easy.

**Comment by kutenai** [comment]
It has definitely worked before.. but, apparently something changed. Not sure what.

**Comment by elevatebart** [comment]
The solution is probably using the cypress extension we load in Chrome automagically.

This extension can access the list of tabs and react to them.

According to [this reference](https://developer.chrome.com/docs/extensions/reference/tabs/), I could do something like this:

```js
// when we close a tab
chrome.tabs.onRemoved.addListener(async function() {
  // if it is the last one on the current window
  if((await chrome.tabs.query({})).length) {
    // send the message to the server to kill chrome then stop
    ws.send('exit')
  }
})
```

**Comment by rockindahizzy** [comment]
Could not reproduce on latest version of Cypress.
