### ISSUE TITLE
Failed to connect to Chrome, retrying in 1 second on brand-new boilerplate code test

### ISSUE THREAD

**Issue by naknode** [cypress-io/cypress#16080]
### Current behavior

I start a fresh project like so:

```json
{
  "name": "NEW-e2e",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^7.1.0"
  }
}
```

and when I run "npx cypress open", I get those standard included files. I select any of them like "examples/viewport.spec.js" and I get: `Failed to connect to Chrome, retrying in 1 second`.

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">41185</span>.

Error details:

Error: connect ECONNREFUSED ::1:41185
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m41185[39m.

Error details:

Error: connect ECONNREFUSED ::1:41185
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

    at get (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at Object.throwErr [as throw] (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/errors.js:1006:9)
    at /home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:106:21
    at tryCatcher (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dan/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```

### Desired behavior

For the provided  code to work as intended.

### Test code to reproduce

No test code to reproduce as the browser won't connect.

### Versions

Node 14.16.0
NPM 6.4.11
Cypress 7.1.0

**Comment by naknode** [comment]
This issue was fixed after I updated my Chrome. Weird.

**Comment by naknode** [comment]
Issue fixed.

**Comment by paulappl** [comment]
Hi, I have the same issue - how did you resolve it?

**Comment by nelsondude** [comment]
I've also had the same issue as well, and my coworker did also. It seems super flaky / random as to when this error occurs

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
