### ISSUE TITLE
Problem with cypress component testing and sass

### ISSUE THREAD

**Issue by victorah96** [cypress-io/cypress#16112]
Hi,
I'm still getting a issue when I try to run `yarn cypress open-ct` where I would like to test one of my react components. The problem is that the test will not even run since it complains that it can not build ./node_modules/sass-loader/dist/cjs.js. 
These are my versions for node and cypress:
`Cypress package version: 7.1.0
Cypress binary version: 7.1.0
Electron version: 12.0.2
Bundled Node version: 14.16.0`

I have installed the component test plugin by the following command:
`yarn add --save-dev cypress @cypress/react @cypress/webpack-dev-server webpack-dev-server`

By the way, we use react-scripts which includes/uses webpack

what is the problem here?

This only happens when I run cypress, I do not get the issue otherwise when building my project.

Complete errror log: 

`./src/components/Layout.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/components/Layout.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (87)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Object.require.extensions.<computed> [as .js] (/home/vahmadi/.cache/Cypress/7.1.0/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getDefaultSassImplementation (/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/components/Layout.scss 2:14-282 21:1-42:3 22:19-287
 @ ./src/components/Layout.tsx
 @ ./src/component-tests/component_example.spec.tsx
 @ ./node_modules/@cypress/webpack-dev-server/dist/loader.js!./node_modules/@cypress/webpack-dev-server/dist/browser.js
 @ ./node_modules/@cypress/webpack-dev-server/dist/browser.js`

**Comment by bahmutov** [comment]
This is due to the mismatch between the Node version you used to run `npm install` or `yarn install` and the Node version bundled with Cypress used to run tests by default. Because Sass includes a native extension, the installed node version has to match the runtime Node version. Just set the node version to the `system` value in the cypress.json file as described in https://docs.cypress.io/guides/references/configuration#Node-version
