### ISSUE TITLE
cy.log is a side effect

### ISSUE THREAD

**Issue by theKashey** [cypress-io/cypress#16216]
### Current behavior
Running `cy.log` can break test. Look like somehow related to the chaining and storing "reference" to an object.

### Desired behavior
`cy.log` does not have any side effect

### Test code to reproduce
```js
		const x = cy.get("div");
		x.find("div");
		cy.log("123"); // remove it, and test will pass
		x.find("div");
```

⬇️⬇️⬇️⬇️⬇️⬇️

```txt
cy.find() failed because it requires a DOM element.

The subject received was:

  > null

The previous command that ran was:

  > cy.log()

All 2 subject validations failed on this subject.
View stack trace
 Print to console
    at ensureElement (http://localhost:8080/__cypress/runner/cypress_runner.js:142062:25)
    at validateType (http://localhost:8080/__cypress/runner/cypress_runner.js:141899:17)
    at Object.ensureSubjectByType (http://localhost:8080/__cypress/runner/cypress_runner.js:141935:10)
    at pushSubjectAndValidate (http://localhost:8080/__cypress/runner/cypress_runner.js:150706:16)
    at Context.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:151058:19)
```

Removing cy.log resolves the problem.
Adding any other task between `const x= cy.find(x);` and `x.find('y');` also breaks the test

### Versions

7.1.0, 7.2.0

**Comment by jennifer-shehane** [comment]
This is intentional. Some commands are 'parent' commands while others are 'child' commands. `.find()` is a child command and requires being chained off of a Cypress command that yields a DOM element. 

```js
cy.get("div"); // yields DOM el
  .find("div"); // yields DOM el
cy.log("123"); // yields null
  .find("div"); // I have no DOM element to chain off of since previous subject was null
```

See https://on.cypress.io/log#Yields and https://on.cypress.io/find#Requirements
