### ISSUE TITLE
Asynchronous stack traces point to internal Cypress code

### ISSUE THREAD

**Issue by kpittman-securus** [cypress-io/cypress#16276]
### Current behavior
If I have `async` code in a Cypress test and it fails, the stack trace points to internal Cypress code instead of application code.

### Desired behavior
The stack trace should be more similar to a normal Mocha trace, which would point to the line of the error even if it's `async` code.

### Test code to reproduce
```javascript
describe("Cypress has stack traces...", () => {
  it("the synchronous ones are great!", () => {
    throw new Error("Find me!");
  });

  it("the async ones are quite opaque", () => {
    cy.wrap(null).then(async () => {
      // this is just an example...
      await fetch("https://github.com/this/does/not/exist", { method: "GET" });
    });
  });
});
```

![image](https://user-images.githubusercontent.com/62567227/116619499-21638400-a906-11eb-90ef-d47a187a9be3.png)

```
at Context.thenFn (http://localhost:60266/__cypress/runner/cypress_runner.js:135863:24)
    at Context.then (http://localhost:60266/__cypress/runner/cypress_runner.js:136302:22)
    at Context.<anonymous> (http://localhost:60266/__cypress/runner/cypress_runner.js:151059:22)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:150467:16)
From previous event:
    at runCommand (http://localhost:60266/__cypress/runner/cypress_runner.js:150446:9)
    at next (http://localhost:60266/__cypress/runner/cypress_runner.js:150592:15)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:150620:17)
From previous event:
    at next (http://localhost:60266/__cypress/runner/cypress_runner.js:150592:35)
From previous event:
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:150633:38)
From previous event:
    at run (http://localhost:60266/__cypress/runner/cypress_runner.js:150626:22)
    at $Cy.cy.<computed> [as wrap] (http://localhost:60266/__cypress/runner/cypress_runner.js:151099:12)
    at Context.runnable.fn (http://localhost:60266/__cypress/runner/cypress_runner.js:151323:22)
    at callFn (http://localhost:60266/__cypress/runner/cypress_runner.js:107502:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:60266/__cypress/runner/cypress_runner.js:107489:8)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:157280:29)
From previous event:
    at Object.onRunnableRun (http://localhost:60266/__cypress/runner/cypress_runner.js:157268:18)
    at $Cypress.action (http://localhost:60266/__cypress/runner/cypress_runner.js:147407:29)
    at Test.Runnable.run (http://localhost:60266/__cypress/runner/cypress_runner.js:155410:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:60266/__cypress/runner/cypress_runner.js:108161:11)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:108287:13)
    at next (http://localhost:60266/__cypress/runner/cypress_runner.js:108070:15)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:108080:8)
    at next (http://localhost:60266/__cypress/runner/cypress_runner.js:107982:15)
    at <unknown> (http://localhost:60266/__cypress/runner/cypress_runner.js:108048:6)
    at timeslice (http://localhost:60266/__cypress/runner/cypress_runner.js:101974:28)
```
### Versions

Cypress 7.2.0

**Comment by jennifer-shehane** [comment]
Yah, this could be better probably. Related to https://github.com/cypress-io/cypress/issues/7202
