### ISSUE TITLE
Inspecting boolean JSON responses crashes Cypress with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by gluxon** [cypress-io/cypress#16403]
### Current behavior

Attempting to inspect an HTTP response that is a simple `true`/`false` JSON value results in a crash.

```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
    at PassThrough.Writable.write (_stream_writable.js:285:13)
    at sendBody (/Users/bcheng/Library/Caches/Cypress/7.2.0/Cypress.app/Contents/Resources/app/packages/net-stubbing/lib/server/util.js:157:22)
    at Object.getBodyStream (/Users/bcheng/Library/Caches/Cypress/7.2.0/Cypress.app/Contents/Resources/app/packages/net-stubbing/lib/server/util.js:161:43)
    at Object.<anonymous> (/Users/bcheng/Library/Caches/Cypress/7.2.0/Cypress.app/Contents/Resources/app/packages/net-stubbing/lib/server/middleware/response.js:79:35)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/Users/bcheng/Library/Caches/Cypress/7.2.0/Cypress.app/Contents/Resources/app/packages/net-stubbing/lib/server/middleware/response.js:5:58)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The response in question was:
```js
{
  headers: {
    server: 'nginx',
    'content-type': 'application/json',
    'content-length': '4',
    connection: 'keep-alive',
    // Some additional fields redacted
  },
  url: 'REDACTED',
  method: null,
  httpVersion: '1.1',
  statusCode: 200,
  statusMessage: 'OK',
  body: "true"
}
```

### Desired behavior

Cypress 7.2.0 can inspect JSON responses that are plain `true` or `false` values.

### Test code to reproduce

```ts
cy.intercept("GET", "*", (req) => {
  req.on("response", (res) => {})
});
```

### Versions

- 7.2.0

---

I added a few lines right before calling `getBodyStream` and the test works as expected afterward.

https://github.com/cypress-io/cypress/blob/1baa5ff454112cee51a7ed7adfc97dd578c4d5e7/packages/net-stubbing/lib/server/middleware/response.ts#L81

```diff
diff --git a/packages/net-stubbing/lib/server/middleware/response.ts b/packages/net-stubbing/lib/server/middleware/response.ts
index cae4b455fa..902cb2d81b 100644
--- a/packages/net-stubbing/lib/server/middleware/response.ts
+++ b/packages/net-stubbing/lib/server/middleware/response.ts
@@ -78,6 +78,10 @@ export const InterceptResponse: ResponseMiddleware = async function () {
 
   mergeChanges(request.res as any, modifiedRes)
 
+  if (_.isObject(modifiedRes.body)) {
+    modifiedRes.body = JSON.stringify(modifiedRes.body)
+  }
+
   const bodyStream = getBodyStream(modifiedRes.body, _.pick(modifiedRes, ['throttleKbps', 'delay']) as any)
 
   return request.continueResponse!(bodyStream)
```

Although I see the `if (_isObject()) { body = JSON.stringify(body) }` pattern in a few other places in Cypress, I suspect there's a deeper root cause. The diff here is just a hack to help show where the problem might be.

Thanks!

**Comment by gluxon** [comment]
Wonderful. Thanks!
