### ISSUE TITLE
Cypress runner crashes after a cy.request() command times out

### ISSUE THREAD

**Issue by gabi-dobritescu** [cypress-io/cypress#16476]
### Current behaviour
The Cypress test runner crashes with a "RangeError: Maximum call stack size exceeded" error a few seconds after a cy.request() command times out.

This happens with both `cypress open` and `cypress run`.

### Desired behavior
cy.request() commands that time out should not crash the test runner.

### Test code to reproduce
Demo repo and instructions here: [demo repo](https://github.com/gabi-dobritescu/exceed-stack-size/tree/master)

Here's a copy of the relevant files from the project:

package.json
```javascript
{
  "name": "stack-size-exceeded",
  "version": "1.0.0",
  "description": "A demo project to show the stack size exceeded error with Cypress",
  "main": "index.js",
  "author": "Gabi Dobritescu",
  "license": "MIT",
  "private": true,
  "scripts": {
    "start": "node app.js",
    "cypress:open": "node_modules\\.bin\\cypress open"
  },
  "devDependencies": {
    "cypress": "^7.3.0",
    "express": "^4.17.1"
  }
}
```

cypress.json
```javascript
{
  "responseTimeout": 2000
}
```

app.js
```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  setTimeout(() => {
    res.send('Hello World!')
  }, 5000)

})

app.listen(port, () => {
  console.log("Example app listening at http://localhost:${port}")
})
```

quick-test.spec.js
```javascript
describe("Demo test for the exceed stack size error", () => {
  it("should gracefully fail the test when api request times out", () => {
    cy.request("http://localhost:3000/").then(response => {
      expect(response.body).to.equal("Hello World!");
    })
  })
})
```

To reproduce the issue:

`yarn install`

`yarn start`

`yarn cypress:open`

Run the `quick-test.spec` test. After the test completes (failing as expected because the request timed out before the server responded) wait for a few seconds (anywhere between 2 to 5 second usually).
The runner crashes with the following error and stacktrace:

```javascript
RangeError: Maximum call stack size exceeded
    at isBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:23:18)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:46:9)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    ...
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at Object.hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at Encoder.encode (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\index.js:38:29)
    at Client._packet (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\client.js:169:44)
    at Socket.packet (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:160:21)
    at C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:274:18
    at C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\lib\socket-base.js:325:28
    at tryCatcher (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

### Versions
7.3.0

**Comment by gabi-dobritescu** [comment]
This is the same issue as #15629 which was recently closed. Version 7.3.0 is meant to have addressed the issue, but it's still happening for me.

**Comment by jennifer-shehane** [comment]
@gabi-dobritescu This is not the same error as #15629 and is a new error, likely introduced in 7.3.0. Likely related though.

**Comment by jennifer-shehane** [comment]
@gabi-dobritescu I actually can't recreate this from your repo on my Mac. But we have seen the same error in our test suite on our CI:  https://app.circleci.com/pipelines/github/cypress-io/cypress/20432/workflows/f90d1e30-e2fe-4b80-815e-ebf2292df162/jobs/739688

Can you give any details about where you're seeing this? Is it on your CI / docker container / local OS?

**Comment by Nasicus** [comment]
@jennifer-shehane as mentioned on the other issue: This is not a new thing and happens since quite a few cypress versions. So I doubt it has anything to do with recent changes.

**Comment by jennifer-shehane** [comment]
@Nasicus Can you provide a reproducible example of the issue? We're aware of other Max call stack errors in previous versions, but not with this same `isBinary` stack trace.

**Comment by jennifer-shehane** [comment]
Our own test encountered this error in the [`retries.ui.spec.js`](https://github.com/cypress-io/cypress/blob/develop/packages/runner/cypress/integration/retries.ui.spec.js) on Chrome 89:

<img width="840" alt="Screen Shot 2021-05-12 at 10 57 41 AM" src="https://user-images.githubusercontent.com/1271364/118006560-f9feb500-b310-11eb-88b5-630f522cf40d.png">

**Comment by Nasicus** [comment]
@jennifer-shehane hmm I never closely looked at it. Sorry I just assumed it was the same.
The only trace I still have is from `6.8.0` form this morning- and you're right that was indeed a different one.
Since it crashed again I just assumed it's the same error... sorry for that!

```
RangeError: Maximum call stack size exceeded
    at _deconstructPacket (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\binary.js:21:28)
    // ^ occurs ~15k times
    at Object.deconstructPacket (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\binary.js:16:17)
    at Encoder.encodeAsBinary (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\index.js:81:41)
    at Encoder.encode (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\index.js:43:29)
    at Client._packet (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\client.js:167:44)
    at Socket.packet (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:161:21)
    at C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:270:18
    at C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\socket-base.js:312:28
    at tryCatcher (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\cypress.user\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by jennifer-shehane** [comment]
Yeah, I can recreate this in Windows 10, on Chrome 90 with this repo: https://github.com/gabi-dobritescu/exceed-stack-size/tree/master?rgh-link-date=2021-05-12T13%3A19%3A02Z

**Comment by gabi-dobritescu** [comment]
@jennifer-shehane Our environments are all Win 10 and we run our test suites with the latest versions of Chrome: 89 & 90.

**Comment by jennifer-shehane** [comment]
I tested this on Windows in 7.2.0 where I can reproduce it and it throws the `deconstructPacket` error from https://github.com/cypress-io/cypress/issues/15629.

**Comment by gabi-dobritescu** [comment]
@jennifer-shehane Downgrading to 6.4.0 is not an option for us as we've migrated away from `cy.route()` to `cy.intercept()`.

**Comment by pyymenta** [comment]
Same here, I've tried to run [this reproducible sample repo](https://github.com/cypress-io/cypress/issues/15101#issuecomment-824220839) using the `7.3.0` version and I've got the following error:

```
...

    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:40:17)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:40:17)
    at Object.hasBinary (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/is-binary.js:55:63)
    at Encoder.encode (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/index.js:38:29)
    at Client._packet (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/client.js:169:44)
    at Socket.packet (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:160:21)
    at /home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:274:18
    at /home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/lib/socket-base.js:325:28
    at tryCatcher (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/testuser/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

In this case, this problem occurs intermittently.

**Comment by poponuts** [comment]
I had to downgrade to 6.4.0 again as this is happening to me too. It is a permanent issue from my end on particular cy.request and not intermittently.

**Comment by sainthkh** [comment]
It wasn't reproducible with Ubuntu 20.04.
