### ISSUE TITLE
Webpack5 - Error: Webpack CompLooked for and couldn't find the file at the following paths:resolve

### ISSUE THREAD

**Issue by feliupe** [cypress-io/cypress#16546]
Looks like there is some WIP on `@cypress/webpack-preprocessor` to make it compatible with webpack 5, so I would just like to contribute with the bug I found and also know if there is an expected time it will be officially compatible with webpack 5 :)

Thanks for the awesome work 🤩

### Current behavior
Error on what I believe is '@cypress/webpack-preprocessor' when running a cypress test.
```
Error: Webpack CompLooked for and couldn't find the file at the following paths:resolve './myAssertion' in '/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/cypress/support/step_definitions'
    at Watching.handle [as handler] (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/@cypress/webpack-preprocessor/dist/index.js:172:23)
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Watching.js:186:9
    at Hook.eval [as callAsync] (eval at create (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Watching.js:183:28)
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Watching.js:108:21
    at Compiler.emitRecords (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Compiler.js:775:39)
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Watching.js:86:22
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Compiler.js:757:14
    at Hook.eval [as callAsync] (eval at create (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Compiler.js:754:27
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/neo-async/async.js:2818:7
    at done (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Compiler.js:616:8)
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/lib/Compiler.js:687:19
    at /Users/felipebatistacoelho/tdc/cypress-cucumber-webpack-typescript-example/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/felipebatistacoelho/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

### Desired behavior
The test to run and pass.

### Test code to reproduce
I've managed to reproduce the problem in the following repo:
https://github.com/feliupe/cypress-cucumber-webpack-typescript-example

Do:
`npm i && npm run test` and pick `WebPack.feature`. The browser should open and the stacktrace with the error should be displayed.

### Versions
Packages:
  "@cypress/webpack-preprocessor": "5.8.0",
  "cypress": "7.3.0",
  "cypress-cucumber-preprocessor": "2.5.0",
  "path-browserify": "^1.0.1",
  "ts-loader": "9.1.1",
  "typescript": "^3.8.2",
  "webpack": "5.3.0"

Running browser: Chrome 90
OS: macOS Catalina 10.15.7

**Comment by BlueWinds** [comment]
This should be fixed in the 10.0-release branch, which will be coming out as 10.0 in the next few weeks.
