### ISSUE TITLE
Video processing times out on videos that are less than 3 seconds long

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#16653]
### Current behavior

Happens in our kitchensink tests for any video that is less than 3 seconds long: https://app.circleci.com/pipelines/github/cypress-io/cypress-example-kitchensink/1063/workflows/081e2595-85f7-4cc9-a5f7-fa3f23006b8e/jobs/6905

<img width="890" alt="Screen Shot 2021-05-24 at 9 54 42 AM" src="https://user-images.githubusercontent.com/1271364/119366033-28b44e00-bc76-11eb-90c3-c83e4ae73d65.png">

### Versions

7.3.0

**Comment by jennifer-shehane** [comment]
If you look at the videos that were actually recorded during the same run where the video processing fails (on the shorter length videos), you'll see that they are very choppy - missing a lot of frames. https://dashboard.cypress.io/projects/4b7344/runs/20278/test-results/71e593db-e6f4-49fe-8420-b86cb7d6db91/video

This run was on Electron 89 on Mac in GitHub Actions. I can't reproduce this issue locally on my Mac though.

**Comment by jennifer-shehane** [comment]
More detailed logs at time of failure:

```
2021-05-26T16:28:25.9781220Z   cypress:server:reporter got mocha event 'hook end' with args: [ { id: 'r7', title: '"before each" hook', hookName: 'before each', hookId: 'h1', body: "() => {\n    cy.visit('http://localhost:8080/commands/querying');\n  }", type: 'hook', duration: 251, file: null, invocationDetails: { function: 'Suite.eval', fileUrl: 'http://localhost:8080/__cypress/tests?p=cypress/integration/2-advanced-examples/querying.spec.js', originalFile: 'webpack:///cypress/integration/2-advanced-examples/querying.spec.js', relativeFile: 'cypress/integration/2-advanced-examples/querying.spec.js', absoluteFile: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', line: 4, column: 3, whitespace: '    ' }, currentRetry: 0, retries: -1 } ] +255ms
2021-05-26T16:28:25.9786250Z   cypress:server:project onMocha pass +2s
2021-05-26T16:28:25.9796080Z   cypress:server:reporter got mocha event 'pass' with args: [ { id: 'r7', order: 5, title: 'best practices - selecting elements', state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/best-practices#Selecting-Elements\n' + "    cy.get('[data-cy=best-practices-selecting-elements]').within(() => {\n" + '      // Worst - too generic, no context\n' + "      cy.get('button').click(); // Bad. Coupled to styling. Highly subject to change.\n" + '\n' + "      cy.get('.btn.btn-large').click(); // Average. Coupled to the `name` attribute which has HTML semantics.\n" + '\n' + "      cy.get('[name=submission]').click(); // Better. But still coupled to styling or JS event listeners.\n" + '\n' + "      cy.get('#main').click(); // Slightly better. Uses an ID but also ensures the element\n" + '      // has an ARIA role attribute\n' + '\n' + "      cy.get('#main[role=button]').click(); // Much better. But still coupled to text content that may change.\n" + '\n' + "      cy.contains('Submit').click(); // Best. Insulated from all changes.\n" + '\n' + "      cy.get('[data-cy=submit]').click();\n" + '    });\n' + '  }', type: 'test', duration: 1761, wallClockStartedAt: '2021-05-26T16:28:23.664Z', timings: { lifecycle: 8, 'before each': [36m[Array], test: [36m[Object] }, file: null, invocationDetails: { function: 'Suite.eval', fileUrl: 'http://localhost:8080/__cypress/tests?p=cypress/integration/2-advanced-examples/querying.spec.js', originalFile: 'webpack:///cypress/integration/2-advanced-examples/querying.spec.js', relativeFile: 'cypress/integration/2-advanced-examples/querying.spec.js', absoluteFile: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', line: 88, column: 3, whitespace: '    ' }, final: true, currentRetry: 0, retries: 0 } ] +2s
2021-05-26T16:28:25.9803660Z   cypress:server:project onMocha test end +5ms
2021-05-26T16:28:25.9813050Z   cypress:server:reporter got mocha event 'test end' with args: [ { id: 'r7', order: 5, title: 'best practices - selecting elements', state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/best-practices#Selecting-Elements\n' + "    cy.get('[data-cy=best-practices-selecting-elements]').within(() => {\n" + '      // Worst - too generic, no context\n' + "      cy.get('button').click(); // Bad. Coupled to styling. Highly subject to change.\n" + '\n' + "      cy.get('.btn.btn-large').click(); // Average. Coupled to the `name` attribute which has HTML semantics.\n" + '\n' + "      cy.get('[name=submission]').click(); // Better. But still coupled to styling or JS event listeners.\n" + '\n' + "      cy.get('#main').click(); // Slightly better. Uses an ID but also ensures the element\n" + '      // has an ARIA role attribute\n' + '\n' + "      cy.get('#main[role=button]').click(); // Much better. But still coupled to text content that may change.\n" + '\n' + "      cy.contains('Submit').click(); // Best. Insulated from all changes.\n" + '\n' + "      cy.get('[data-cy=submit]').click();\n" + '    });\n' + '  }', type: 'test', duration: 1761, wallClockStartedAt: '2021-05-26T16:28:23.664Z', timings: { lifecycle: 8, 'before each': [36m[Array], test: [36m[Object] }, file: null, invocationDetails: { function: 'Suite.eval', fileUrl: 'http://localhost:8080/__cypress/tests?p=cypress/integration/2-advanced-examples/querying.spec.js', originalFile: 'webpack:///cypress/integration/2-advanced-examples/querying.spec.js', relativeFile: 'cypress/integration/2-advanced-examples/querying.spec.js', absoluteFile: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', line: 88, column: 3, whitespace: '    ' }, final: true, currentRetry: 0, retries: 0 } ] +5ms
2021-05-26T16:28:25.9820840Z   cypress:server:project onMocha suite end +0ms
2021-05-26T16:28:25.9825560Z   cypress:server:reporter got mocha event 'suite end' with args: [ { id: 'r2', title: 'Querying', root: false, type: 'suite', file: null, invocationDetails: { function: 'Object../cypress/integration/2-advanced-examples/querying.spec.js', fileUrl: 'http://localhost:8080/__cypress/tests?p=cypress/integration/2-advanced-examples/querying.spec.js', originalFile: 'webpack:///cypress/integration/2-advanced-examples/querying.spec.js', relativeFile: 'cypress/integration/2-advanced-examples/querying.spec.js', absoluteFile: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', line: 3, column: 1, whitespace: '    ' }, retries: -1 } ] +0ms
2021-05-26T16:28:25.9829710Z   cypress:server:project onMocha test:after:run +0ms
2021-05-26T16:28:25.9839100Z   cypress:server:reporter got mocha event 'test:after:run' with args: [ { id: 'r7', order: 5, title: 'best practices - selecting elements', state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/best-practices#Selecting-Elements\n' + "    cy.get('[data-cy=best-practices-selecting-elements]').within(() => {\n" + '      // Worst - too generic, no context\n' + "      cy.get('button').click(); // Bad. Coupled to styling. Highly subject to change.\n" + '\n' + "      cy.get('.btn.btn-large').click(); // Average. Coupled to the `name` attribute which has HTML semantics.\n" + '\n' + "      cy.get('[name=submission]').click(); // Better. But still coupled to styling or JS event listeners.\n" + '\n' + "      cy.get('#main').click(); // Slightly better. Uses an ID but also ensures the element\n" + '      // has an ARIA role attribute\n' + '\n' + "      cy.get('#main[role=button]').click(); // Much better. But still coupled to text content that may change.\n" + '\n' + "      cy.contains('Submit').click(); // Best. Insulated from all changes.\n" + '\n' + "      cy.get('[data-cy=submit]').click();\n" + '    });\n' + '  }', type: 'test', duration: 1761, wallClockStartedAt: '2021-05-26T16:28:23.664Z', wallClockDuration: 1767, timings: { lifecycle: 8, 'before each': [36m[Array], test: [36m[Object] }, file: null, invocationDetails: { function: 'Suite.eval', fileUrl: 'http://localhost:8080/__cypress/tests?p=cypress/integration/2-advanced-examples/querying.spec.js', originalFile: 'webpack:///cypress/integration/2-advanced-examples/querying.spec.js', relativeFile: 'cypress/integration/2-advanced-examples/querying.spec.js', absoluteFile: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', line: 88, column: 3, whitespace: '    ' }, final: true, currentRetry: 0, retries: 0 } ] +0ms
2021-05-26T16:28:25.9847030Z   cypress:server:project onMocha suite end +0ms
2021-05-26T16:28:25.9848960Z   cypress:server:reporter got mocha event 'suite end' with args: [ { id: 'r1', title: '', root: true, type: 'suite', file: 'cypress/integration/2-advanced-examples/querying.spec.js', retries: -1 } ] +0ms
2021-05-26T16:28:25.9850620Z   cypress:server:project onMocha end +1ms
2021-05-26T16:28:25.9851780Z   cypress:server:reporter got mocha event 'end' with args: [ { end: '2021-05-26T16:28:25.432Z' } ] +1ms
2021-05-26T16:28:28.6474010Z   cypress:server:browsers:electron debugger: sending Page.screencastFrameAck with params { sessionId: 1 } +5s
2021-05-26T16:28:28.6479330Z Warning: We failed processing this video.
2021-05-26T16:28:28.6580760Z   cypress:server:browsers:electron debugger: received response to Page.screencastFrameAck: {} +0ms
2021-05-26T16:28:28.6583980Z 
2021-05-26T16:28:28.6677970Z   cypress:server:plugins plugin event registered? { event: 'after:spec', isRegistered: false } +8s
2021-05-26T16:28:28.6685620Z This error will not alter the exit code.
2021-05-26T16:28:28.6730570Z   cypress:server:run No video found after spec ran - skipping processing. Video path: /Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/videos/2-advanced-examples/querying.spec.js.mp4 +7s
2021-05-26T16:28:28.6732950Z 
2021-05-26T16:28:28.6734220Z   cypress:server:run attempting to close the browser +6ms
2021-05-26T16:28:28.6735580Z TimeoutError: operation timed out
2021-05-26T16:28:28.6753100Z   cypress:server:browsers killing browser process +8s
2021-05-26T16:28:28.6842460Z     at afterTimeout (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
2021-05-26T16:28:28.6859960Z   cypress:server:run all BrowserWindows closed, not exiting +0ms
2021-05-26T16:28:28.6946990Z     at Timeout.timeoutTimeout [as _onTimeout] (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
2021-05-26T16:28:28.6949370Z   cypress:server:browsers:electron closed event fired +17ms
2021-05-26T16:28:28.6969270Z     at listOnTimeout (internal/timers.js:554:17)
2021-05-26T16:28:28.6979100Z   cypress:server:windows error removing all extensions { err: TypeError: Object has been destroyed at Object.removeAllExtensions (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/windows.js:52:26) at BrowserWindow.<anonymous> (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:424:19) [90m    at Object.onceWrapper (events.js:422:26) [90m    at BrowserWindow.emit (events.js:327:22) at tryToCall (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:28:27) at EventEmitter.kill (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/electron.js:440:20) at /Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:41:15 at Promise.cancellationExecute [as _execute] (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9) at Promise._resolveFromExecutor (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18) at new Promise (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10) at Object.kill [as close] (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:30:10) at Object.closeBrowser (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/open_project.js:304:23) at /Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/modes/run.js:1237:27 , extensions: [90mundefined } +11s
2021-05-26T16:28:28.6988570Z   cypress:server:preprocessor removeFile /Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js +6s
2021-05-26T16:28:28.6990530Z   cypress:server:preprocessor base emitter plugin close event +0ms
2021-05-26T16:28:28.6991750Z   cypress:server:preprocessor base emitter native close event +0ms
2021-05-26T16:28:28.6992880Z   cypress:server:browsers browser process killed +1ms
2021-05-26T16:28:28.6994730Z   cypress:webpack close /Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js +8s
2021-05-26T16:28:28.6997030Z   cypress:server:browsers:electron debugger: sending Page.screencastFrameAck with params { sessionId: 1 } +6ms
2021-05-26T16:28:28.6998720Z   cypress:server:browsers:electron debugger: received response to Page.screencastFrameAck: {} +0ms
2021-05-26T16:28:28.7000210Z   cypress:server:browsers:electron debugger detached due to { reason: 'target closed' } +1ms
2021-05-26T16:28:28.7001630Z   cypress:server:video capture stderr log { message: '[mjpeg @ 0x7f913c00cc00] EOI missing, emulating' } +9s
2021-05-26T16:28:28.7022710Z   cypress:server:run spec results { stats: { suites: 1, tests: 5, passes: 5, pending: 0, skipped: 0, failures: 0, wallClockStartedAt: 2021-05-26T16:28:21.473Z, wallClockEndedAt: 2021-05-26T16:28:25.432Z, wallClockDuration: 3959 }, reporter: 'spec', reporterStats: { suites: 1, tests: 5, passes: 5, pending: 0, failures: 0, start: 2021-05-26T16:28:21.477Z, end: 2021-05-26T16:28:25.437Z, duration: 3960 }, hooks: [ { hookId: 'h1', hookName: 'before each', title: [36m[Array], body: "() => {\n    cy.visit('http://localhost:8080/commands/querying');\n  }" } ], tests: [ { testId: 'r3', title: [36m[Array], state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/get\n' + "    cy.get('#query-btn').should('contain', 'Button');\n" + "    cy.get('.query-btn').should('contain', 'Button');\n" + "    cy.get('#querying .well>button:first').should('contain', 'Button'); //              ↲\n" + '    // Use CSS selectors just like jQuery\n' + '\n' + `    cy.get('[data-test-id="test-example"]').should('have.class', 'example'); // 'cy.get()' yields jQuery object, you can get its attribute\n` + '    // by invoking `.attr()` method\n' + '\n' + `    cy.get('[data-test-id="test-example"]').invoke('attr', 'data-test-id').should('equal', 'test-example'); // or you can get element's CSS property\n` + '\n' + `    cy.get('[data-test-id="test-example"]').invoke('css', 'position').should('equal', 'static'); // or use assertions directly during 'cy.get()'\n` + '    // https://on.cypress.io/assertions\n' + '\n' + `    cy.get('[data-test-id="test-example"]').should('have.attr', 'data-test-id', 'test-example').and('have.css', 'position', 'static');\n` + '  }', displayError: null, attempts: [36m[Array] }, { testId: 'r4', title: [36m[Array], state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/contains\n' + "    cy.get('.query-list').contains('bananas').should('have.class', 'third'); // we can pass a regexp to `.contains()`\n" + '\n' + "    cy.get('.query-list').contains(/^b\\w+/).should('have.class', 'third');\n" + "    cy.get('.query-list').contains('apples').should('have.class', 'first'); // passing a selector to contains will\n" + '    // yield the selector containing the text\n' + '\n' + "    cy.get('#querying').contains('ul', 'oranges').should('have.class', 'query-list');\n" + "    cy.get('.query-button').contains('Save Form').should('have.class', 'btn');\n" + '  }', displayError: null, attempts: [36m[Array] }, { testId: 'r5', title: [36m[Array], state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/within\n' + "    cy.get('.query-form').within(() => {\n" + "      cy.get('input:first').should('have.attr', 'placeholder', 'Email');\n" + "      cy.get('input:last').should('have.attr', 'placeholder', 'Password');\n" + '    });\n' + '  }', displayError: null, attempts: [36m[Array] }, { testId: 'r6', title: [36m[Array], state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/root\n' + '    // By default, root is the document\n' + "    cy.root().should('match', 'html');\n" + "    cy.get('.query-ul').within(() => {\n" + '      // In this within, the root is now the ul DOM element\n' + "      cy.root().should('have.class', 'query-ul');\n" + '    });\n' + '  }', displayError: null, attempts: [36m[Array] }, { testId: 'r7', title: [36m[Array], state: 'passed', body: '() => {\n' + '    // https://on.cypress.io/best-practices#Selecting-Elements\n' + "    cy.get('[data-cy=best-practices-selecting-elements]').within(() => {\n" + '      // Worst - too generic, no context\n' + "      cy.get('button').click(); // Bad. Coupled to styling. Highly subject to change.\n" + '\n' + "      cy.get('.btn.btn-large').click(); // Average. Coupled to the `name` attribute which has HTML semantics.\n" + '\n' + "      cy.get('[name=submission]').click(); // Better. But still coupled to styling or JS event listeners.\n" + '\n' + "      cy.get('#main').click(); // Slightly better. Uses an ID but also ensures the element\n" + '      // has an ARIA role attribute\n' + '\n' + "      cy.get('#main[role=button]').click(); // Much better. But still coupled to text content that may change.\n" + '\n' + "      cy.contains('Submit').click(); // Best. Insulated from all changes.\n" + '\n' + "      cy.get('[data-cy=submit]').click();\n" + '    });\n' + '  }', displayError: null, attempts: [36m[Array] } ], error: null, video: null, screenshots: [], spec: { name: '2-advanced-examples/querying.spec.js', relative: 'cypress/integration/2-advanced-examples/querying.spec.js', absolute: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', specType: 'integration' }, shouldUploadVideo: true } +21ms
2021-05-26T16:28:28.7040960Z   cypress:server:record after spec run { spec: { name: '2-advanced-examples/querying.spec.js', relative: 'cypress/integration/2-advanced-examples/querying.spec.js', absolute: '/Users/runner/work/cypress-example-kitchensink/cypress-example-kitchensink/cypress/integration/2-advanced-examples/querying.spec.js', specType: 'integration' } } +9s
2021-05-26T16:28:28.7053940Z   cypress:server:api request to url: POST https://api.cypress.io/instances/fe8566f1-5ff2-4854-8d3b-d4350c40a164/results with params: {"body":{"stats":{"suites":1,"tests":5,"passes":5,"pending":0,"skipped":0,"failures":0,"wallClockStartedAt":"2021-05-26T16:28:21.473Z","wallClockEndedAt":"2021-05-26T16:28:25.432Z","wallClockDuration":3959},"tests":[{"clientId":"r3","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":13,"before each":[{"hookId":"h1","fnDuration":373,"afterFnDuration":0}],"test":{"fnDuration":112,"afterFnDuration":1}},"failedFromHookId":null,"wallClockStartedAt":"2021-05-26T16:28:22.490Z","wallClockDuration":510,"videoTimestamp":2472}]},{"clientId":"r4","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":8,"before each":[{"hookId":"h1","fnDuration":174,"afterFnDuration":0}],"test":{"fnDuration":85,"afterFnDuration":1}},"failedFromHookId":null,"wallClockStartedAt":"2021-05-26T16:28:23.003Z","wallClockDuration":284,"videoTimestamp":2985}]},{"clientId":"r5","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":8,"before each":[{"hookId":"h1","fnDuration":144,"afterFnDuration":0}],"test":{"fnDuration":36,"afterFnDuration":1}},"failedFromHookId":null,"wallClockStartedAt":"2021-05-26T16:28:23.289Z","wallClockDuration":193,"videoTimestamp":3271}]},{"clientId":"r6","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":8,"before each":[{"hookId":"h1","fnDuration":141,"afterFnDuration":0}],"test":{"fnDuration":26,"afterFnDuration":0}},"failedFromHookId":null,"wallClockStartedAt":"2021-05-26T16:28:23.483Z","wallClockDuration":179,"videoTimestamp":3465}]},{"clientId":"r7","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":8,"before each":[{"hookId":"h1","fnDuration":243,"afterFnDuration":0}],"test":{"fnDuration":1509,"afterFnDuration":1}},"failedFromHookId":null,"wallClockStartedAt":"2021-05-26T16:28:23.664Z","wallClockDuration":1767,"videoTimestamp":3646}]}],"exception":null,"video":false,"screenshots":[],"reporterStats":{"suites":1,"tests":5,"passes":5,"pending":0,"failures":0,"start":"2021-05-26T16:28:21.477Z","end":"2021-05-26T16:28:25.437Z","duration":3960},"metadata":{"studioCreated":0,"studioExtended":0}},"headers":{"x-route-version":"1","x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"7.3.0"}} and token: undefined +7s
2021-05-26T16:28:28.7064140Z   cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/instances/fe8566f1-5ff2-4854-8d3b-d4350c40a164/results' } +5s
2021-05-26T16:28:28.7066180Z   cypress:network:agent got family { family: 4, href: 'https://api.cypress.io/instances/fe8566f1-5ff2-4854-8d3b-d4350c40a164/results' } +0ms
2021-05-26T16:28:28.7067830Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 49439 } [36m+6s
2021-05-26T16:28:28.7068980Z     at processTimers (internal/timers.js:497:7)
2021-05-26T16:28:28.7069750Z 
2021-05-26T16:28:28.7069980Z 
2021-05-26T16:28:28.7070760Z   (Results)
2021-05-26T16:28:28.7071240Z 
```

**Comment by jennifer-shehane** [comment]
With verbose video frame logging, you can see before the error throws that there were 0 video frames written. 

Seems to be isolated to running on Mac in our CI, even though the Mac version is 10.15.7, which I can't recreate running locally on the same OSX.

```
  cypress-verbose:server:video:frames frames written: 0 +13s
Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/runner/.cache/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
