### ISSUE TITLE
ERR_INVALID_ARG_TYPE Component testing vue 2 bug 

### ISSUE THREAD

**Issue by Badbreaddead** [cypress-io/cypress#16754]
Thank you for your work and amazing instrument to work with.

Back to business. I was following [vue component testing guide](https://docs.cypress.io/guides/component-testing/framework-configuration#Vue-2-Vue-CLI) and wasn't able to run component testing due to the error after installation and basic setup from the tutorial. 

After some debugging I figured that the originates from `node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js` line 54: `devServerPublicPathRoute` is undefined. devServerPublicPathRoute in taken from `options.config` from line `on('dev-server:start', (options) => {` in plugins, so I guess it could be internal problem

```
TypeError [
[log.log](https://github.com/cypress-io/cypress/files/6571368/log.log)
]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Object.<anonymous> (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:54:20)
    at Generator.next (<anonymous>)
    at /Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:23:12)
    at Object.makeWebpackConfig (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:45:12)
    at Object.<anonymous> (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/startServer.js:41:57)
    at Generator.next (<anonymous>)
    at /Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/startServer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/startServer.js:4:12)
    at Object.start (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/startServer.js:35:12)
    at /Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/index.js:18:54
    at Generator.next (<anonymous>)
    at /Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/index.js:4:12)
    at startDevServer (/Users/apavlov/Documents/repos/reuters2/node_modules/@cypress/webpack-dev-server/dist/index.js:17:12)
    at Object.handler (/Users/apavlov/Documents/repos/reuters2/cypress/plugins/index.js:29:12)
    at invoke (/Users/apavlov/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16) {
  code: ''
}
```
```
"devDependencies": {
        "@cypress/vue": "^2.2.3",
        "@cypress/webpack-dev-server": "^1.3.1",
        "cypress": "^6.8.0",
        "html-webpack-plugin": "^4.5.2",
        "webpack-dev-server": "^3.11.2"
}
```
vue@2.6.12
I am on mac Big Sur 11.4

Log with in DEBUG mode attached

**Comment by JessicaSachs** [comment]
Can you send me your plugins file? It should look something like this

```js
const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('@vue/cli-service/webpack.config')

module.exports = (on, config) => {
    on('dev-server:start', (options) => {
        return startDevServer({ options, webpackConfig })
    })
    return config
}

```

**Comment by lmiller1990** [comment]
Cypress 10 should have vastly improved the onboarding!
