### ISSUE TITLE
Code coverage for component tests

### ISSUE THREAD

**Issue by jhiester** [cypress-io/cypress#16798]
### What would you like?
Code coverage for component testing.

### Why is this needed?
It has been really helpful to me and my organization to be able to use the code coverage reports from e2e/integration/unit tests to guide our testing and development. Having component level coverage tests would help in a similar way.

**Comment by yann-combarnous** [comment]
Example setup for code coverage with Create-React-App, in cypress/plugins/index.js:

```
// Component / storybook testing
import injectDevServer from '@cypress/react/plugins/react-scripts';
import findReactScriptsWebpackConfig from '@cypress/react/plugins/react-scripts/findReactScriptsWebpackConfig';
import { startDevServer } from '@cypress/webpack-dev-server';
// Code coverage
import codeCoverageTask from '@cypress/code-coverage/task';

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // Tell Cypress to report on code coverage
  codeCoverageTask(on, config);

  // Unit/Component testing web dev server setup for instrumenting code coverage
  // For integration testing, this is done in CRA start command
  if (config.testingType === 'component') {
    injectDevServer(on, config);
    const webpackConfig = findReactScriptsWebpackConfig(config, {
      webpackConfigPath: 'react-scripts/config/webpack.config',
    });
    const rules = webpackConfig.module.rules.find((rule) => !!rule.oneOf).oneOf;
    const babelRule = rules.find((rule) => /babel-loader/.test(rule.loader));
    babelRule.options.plugins.push(require.resolve('babel-plugin-istanbul'));

    on('dev-server:start', (options) => {
      return startDevServer({ options, webpackConfig });
    });
  }
  return config;
};
```

**Comment by elevatebart** [comment]
Hello @jhiester

I believe there could be two subjects to cover here:

### How to get component testing code coverage
  - If you are using create react app see in this repo https://github.com/elevatebart/cy-ct-cra
  - If you are using Vue see this example https://github.com/cypress-io/cypress/tree/npm/vue/v2/npm/vue/examples/code-coverage

### How to merge it with e2e testing coverage
On that front there is good news:
If you run the e2e job and the component job successively, their test coverage going in the same folder, istanbul is smart and will merge the two reports automagically.

If this does not answer your question, feel free to respond below. 
If it does, you can close this issue. 

Thank you in advance.

**Comment by Dorious** [comment]
Hey @yann-combarnous, I have similar conf and it doesn't collect coverage for CT, for E2E it does it but after running `cypress run-ct` it doesn't generate anything.

**Comment by elevatebart** [comment]
Hello @Dorious 

What @yann-combarnous is doing above should be extracting the coverage in Component testing.

But this line

```js
injectDevServer(on, config);
```

Will do behind the scenes the same as these lines.

```js
on('dev-server:start', (options) => {
  return startDevServer({ options, webpackConfig });
});
```

They will be redundant. 

The first one will inject the server without setting up any coverage.
The second one will inject and have coverage.

We probably should check that in the processing and send a warning.

Did you see that?

**Comment by Dorious** [comment]
@elevatebart I don't have injectDevServer because I don't use react-scripts. My cypress `plugins/index.ts`

```ts
/// <reference types="cypress" />

import browserify from '@cypress/browserify-preprocessor';
import task from '@cypress/code-coverage/task';
import { initPlugin } from 'cypress-plugin-snapshots/plugin';
import { startDevServer } from '@cypress/webpack-dev-server';

import webpackConfig from '../../webpack.cypress';

/**
 * @type {Cypress.PluginConfig}
 */
const configurePlugins: Cypress.PluginConfig = (on, config) => {
  task(on, config);
  initPlugin(on, config);

  on(
    'file:preprocessor',
    browserify({
      typescript: require.resolve('typescript'),
    })
  );

  if (config.testingType === 'component') {
    // console.log(webpackConfig.module.rules[4].use[0].options);
    on('dev-server:start', (options) => startDevServer({ options, webpackConfig }));
  }

  return config;
};

export default configurePlugins;
```

The console log is there to check is `istanbul` there and it is.

**Comment by Dorious** [comment]
Also I see that the coverage is there each test:
![image](https://user-images.githubusercontent.com/2143349/122022086-8eec4680-cdc6-11eb-8638-878c345c79ff.png)
But it doesn't push it into `coverage` dir. In integration tests (`cypress run`) it works.

**Comment by Dorious** [comment]
> If you run the e2e job and the component job successively, their test coverage going in the same folder, istanbul is smart and will merge the two reports automagically.

@elevatebart Do I get this correctly? I need to run e2e tests to get the coverage? This is odd and imo shouldn't be this way. For example I want only component tests to be ran not the integrational tests which takes time.

**Comment by Dorious** [comment]
@elevatebart ok I figured out what was wrong in my case, in `support/` I have separate `component.ts` and we need to put `import '@cypress/code-coverage'` :) now coverage is collected properly.

**Comment by elevatebart** [comment]
Lovely !!!

Code coverage implementation might be a good "recipe" to add to our docs.

To get coverage, you need: 
- In `plugins/index.js`, instrumentation of your code (using babel or another istanbul plugin) in the config you pass to the dev server.
- In `plugins/index.js` implement the code coverage task with the proper task.
```js
const installCoverageTask = require("@cypress/code-coverage/task");
module.exports = (on, config) => {
  installCoverageTask(on, config)
}
```
- In `support/index.js` import the code-coverage implementation to run this task when needed.
```js
import '@cypress/code-coverage/support'
```

**Comment by vrknetha** [comment]
@elevatebart I have followed all the steps mentioned in the repo. But the instrumentation is not happening at all in my case. we use the same react scripts.

**Comment by elevatebart** [comment]
@vrknetha What is your stack? Webpack? vite? vue? react?

**Comment by elevatebart** [comment]
@vrknetha just re-read your answer... 
Sorry about that, you already said you are indeed using react-scripts.

Can you share your setup?
- package.json
- cypress.json
- cypress/plugins & cypress/support

A repository would be even better, but I understand not everyone can take this time.

**Comment by yeyalab** [comment]
Same thing here, CT code coverage is not working. CRA + Typescript. What finally made it work I added 
`{
        test: /\.(tsx|ts)?$/,
        include: [SRC_PATH],
        use: [{
          loader: 'istanbul-instrumenter-loader',
          options: { esModules: true }
        }]
      }`

just before my typescript loader, in webpack config for 
`on('dev-server:start', options => startDevServer({
    options,
    webpackConfig
  }));`

This is what I have:
`const webpackConfig = {
    module: {
      rules: [{
        test: /\.(tsx|ts)?$/,
        include: [SRC_PATH],
        use: [{
          loader: 'istanbul-instrumenter-loader',
          options: { esModules: true }
        }]
      }, {
        test: /\.(tsx|ts)?$/,
        include: [SRC_PATH, CYPRESS_PATH, CYPRESS_NODE_PATH],
        use: [{
          loader: 'awesome-typescript-loader',
          options: {
            configFileName: CONFIG_PATH
          }
        }]
      }]
    },
    resolve: {
      extensions: ['.tsx', '.ts', '.js', '.json']
    }
  };

  on('dev-server:start', options => startDevServer({
    options,
    webpackConfig
  }));`

And it works for me like this...
Hope it helps someone.

**Comment by cowboy** [comment]
Yeah, adding code coverage is absolutely on my list!

**Comment by yann-combarnous** [comment]
One thing I have not figured out is that I want to have nyc report on all files, which is why I used in package.json:
`
  "nyc": {
    "all": true,
    "report-dir": "coverage",
    "reporter": [
      "text-summary",
      "json",
      "json-summary",
      "lcov"
    ],
    "include": [
      "src/**/*.{js,jsx,mjs,ts,tsx}"
    ],
`

But it seems that for component testing, not all files are included in coverage percentage. Any idea how to have component testing honor the nyc setup for scope?

**Comment by yann-combarnous** [comment]
@elevatebart , now trying with Vite to get code coverage for component testing, but getting some issues.

Using vite-plugin-istanbul (latest), Vite 2.7.0-beta.10, and Cypress 8.7.0. 

vite.config.js:
```
    plugins: [
      react(),
      istanbul({
        include: ['src/**/*.{js,jsx,mjs,ts,tsx}'],
        exclude: [
          'coverage',
          'node_modules',
          'src/**/*.{types,stories,spec,faker,test}.{js,jsx,mjs,ts,tsx}',
        ],
        extension: ['.js', '.ts', '.tsx'],
        requireEnv: true,
     })
```

cypress/plugins/index.js
```
import { startDevServer } from '@cypress/vite-dev-server';
import codeCoverageTask from '@cypress/code-coverage/task';

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // Tell Cypress to report on code coverage
  codeCoverageTask(on, config);

  if (config.testingType === 'component') {
    on('dev-server:start', (options) => {
      return startDevServer({
        options
      });
    });
  }
```

When running tests, tests do not run in UI. Error in Cypress UI is:
```
The following error originated from your test code, not from Cypress.
  > Unexpected identifier
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.

at Object.runScripts (http://localhost:3000/__cypress/runner/cypress_runner.js:194369:63)
at $Cypress.onSpecWindow (http://localhost:3000/__cypress/runner/cypress_runner.js:183210:76)
at <unknown> (http://localhost:3000/__cypress/src/@fs//Users/yanncombarnous/Code/cbre-360-portal/node_modules/@cypress/vite-dev-server/client/initCypressTests.js:22:18)
```

In addition, Vite is watching coverage folder, getting the following line updated for all files there:
```
11:18:14 [vite] page reload coverage/lcov-report/src/constants/icons.ts.html
```

When I just change in vite.config.js and disabled Istanbul plugin, component test just run fine.

Any idea on how to get this to work with Vite + React?

**Comment by cowboy** [comment]
In case it helps, we've been working on getting code coverage happening over here. Hopefully we'll get some of these PRs merged in soon!

https://github.com/cypress-io/cypress-component-testing-examples/pulls?q=is%3Apr+%22code+coverage%22

**Comment by samtsai** [comment]
What is your folder structure? We saw the same behavior and it almost always had to do with how we're including/excluding files.

**Comment by yann-combarnous** [comment]
> In case it helps, we've been working on getting code coverage happening over here. Hopefully we'll get some of these PRs merged in soon!
> 
> https://github.com/cypress-io/cypress-component-testing-examples/pulls?q=is%3Apr+%22code+coverage%22

Very helpful, thank you! Found my issue: one "process.env.NODE_ENV" left in my code. Interestingly, it only crashed with Vite code coverage plugin and Cypress. Vite build and dev server ran fine on their own.

**Comment by joshwooding** [comment]
@yann-combarnous How did you end up solving this? I'm seeing the same error due to process.env.NODE_ENV being replaced in the vite-plugin-istanbul sourcesContent output.

```js
function cov_26q8djqde0() {
    ...
    var coverageData = {
        inputSourceMap: {
            version: 3,
            sourcesContent: ["export const reproduction = (item: any) => {\n  if ("development" !== \"production\") {\n    console.log(\"TEST\");\n  }\n\n  return \"\";\n};\n"],
        },
    };
   
}
```

**Comment by yann-combarnous** [comment]
> @yann-combarnous How did you end up solving this? I'm seeing the same error due to process.env.NODE_ENV being replaced in the vite-plugin-istanbul sourcesContent output.
> 
> ```js
> function cov_26q8djqde0() {
>     ...
>     var coverageData = {
>         inputSourceMap: {
>             version: 3,
>             sourcesContent: ["export const reproduction = (item: any) => {\n  if ("development" !== \"production\") {\n    console.log(\"TEST\");\n  }\n\n  return \"\";\n};\n"],
>         },
>     };
>    
> }
> ```
> 
> I also see [iFaxity/vite-plugin-istanbul#8](https://github.com/iFaxity/vite-plugin-istanbul/issues/8) has been raised.

Replace process.env.NODE_ENV in your code by import.meta.env.MODE. See https://vitejs.dev/guide/env-and-mode.html#env-variables .

**Comment by joshwooding** [comment]
Hmm, sadly I don't think that will work for me since we're building with more than vite.

**Comment by IlCallo** [comment]
If anyone is interested, we just published oob code coverage support for Cypress + TS + Vite + Quasar, check it out: https://github.com/quasarframework/quasar-testing/releases/tag/e2e-cypress-v4.1.0

[This commit](https://github.com/quasarframework/quasar-testing/commit/a43db96fbe5c760a0472b0a832c00499075a4024) can be used to replicate the setup on other frameworks/tools too, as I annotate many details in the readme

**Comment by joshwooding** [comment]
> @yann-combarnous How did you end up solving this? I'm seeing the same error due to process.env.NODE_ENV being replaced in the vite-plugin-istanbul sourcesContent output.
> 
> ```js
> function cov_26q8djqde0() {
>     ...
>     var coverageData = {
>         inputSourceMap: {
>             version: 3,
>             sourcesContent: ["export const reproduction = (item: any) => {\n  if ("development" !== \"production\") {\n    console.log(\"TEST\");\n  }\n\n  return \"\";\n};\n"],
>         },
>     };
>    
> }
> ```
> 
> I also see [iFaxity/vite-plugin-istanbul#8](https://github.com/iFaxity/vite-plugin-istanbul/issues/8) has been raised.

Just to provide an update. I finally got around to investigating this and raised a fix that was released in `vite-plugin-istanbul@2.7.3`

**Comment by Ancient-Dragon** [comment]
Has anyone got a working example of vue 3 + vite working with coverage? 

I have installed the vite plugin with the following config options:

```js
istanbul({
        include: 'src/*',
        exclude: ['node_modules'],
        extension: ['.js', '.ts', '.vue'],
        /**
         * This allows us to omit the INSTRUMENT_BUILD env variable when running the production build via
         * npm run build.
         * More details below.
         */
        requireEnv: false,
        /**
         * If forceBuildInstrument is set to true, this will add coverage instrumentation to the
         * built dist files and allow the reporter to collect coverage from the (built files).
         * However, when forceBuildInstrument is set to true, it will not collect coverage from
         * running against the dev server: e.g. npm run dev.
         *
         * To allow collecting coverage from running cypress against the dev server as well as the
         * preview server (built files), we use an env variable, INSTRUMENT_BUILD, to set
         * forceBuildInstrument to true when running against the preview server via the
         * instrument-build npm script.
         *
         * When you run `npm run build`, the INSTRUMENT_BUILD env variable is omitted from the npm
         * script which will result in forceBuildInstrument being set to false, ensuring your
         * dist/built files for production do not include coverage instrumentation code.
         */
        forceBuildInstrument: Boolean(process.env.INSTRUMENT_BUILD),
      })
```

Cypress config: 
```js
  component: {
    devServer: {
      framework: 'vue',
      bundler: 'vite',
    },
    screenshotOnRunFailure: false,
    video: false,
  },
```

And my package.json commands looks like:
```json
    "instrument-build": "cross-env INSTRUMENT_BUILD=true vite build",
    "test:component": "npm run instrument-build && cypress run --component --reporter spec",
```

I'm using cypress 10.4.0 & cypress coverage 3.10.0. Any help would be greatly appreciated

**Comment by lmiller1990** [comment]
I think we need a definitive guide on coverage. Some resources (other than the ones here):

- CRA + webpack: https://muratkerem.gitbook.io/cctdd/ch30-appendix/combined-code-coverage
- Vite (some info floating around here) https://github.com/iFaxity/vite-plugin-istanbul/issues/22

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/16798?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by muratkeremozcan** [comment]
> In case it helps, we've been working on getting code coverage happening over here. Hopefully we'll get some of these PRs merged in soon!
> 
> https://github.com/cypress-io/cypress-component-testing-examples/pulls?q=is%3Apr+%22code+coverage%22

Get those in now!

**Comment by lmiller1990** [comment]
Yep, we are picking this up in our next block of work, Feb 28->Ma 14, the goal is just to document common combinations and how it works in general, so people with less common combos can configure it, too.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/16798?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @jordanpowell88

**Comment by lmiller1990** [comment]
Relevent https://github.com/cypress-io/cypress-component-testing-apps/issues/16
