### ISSUE TITLE
"cypress run-ct" socket hang up error

### ISSUE THREAD

**Issue by vladyslavkuliani** [cypress-io/cypress#16806]
### Current behavior

In Vue 2 project with custom webpack config (not vue cli project) I've set up two npm scripts in package.json as follows:
```json
"test:open-integration": "DEBUG=cypress:* cypress open-ct",
"test:run-integration": "DEBUG=cypress:* cypress run-ct",
```

✅  When running `test:open-integration` - Cypress opens browser with spec file that it found. Clicking on the file runs test as expected.

❌  When running `test:run-integration` - Cypress hangs after bundling step with error:
```console
cypress:server:routes Proxy request error. This is likely the socket hangup issue, we can basically ignore this because the stream will automatically continue once the asset will be available Error: socket hang up
    at connResetException (internal/errors.js:617:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 {
  code: 'ECONNRESET'
}
```

**Additional info:**
-  Same issue when running e.g. `cypress run-ct --browser chrome`
<details>
  <summary>cypress/plugins/index.js</summary>

  ```js
  module.exports = (on, config) => {
    const makeWebpackConfig = require('../../webpack.config.js');
    const webpackConfig = makeWebpackConfig({ config: 'local' });
    const { startDevServer } = require('@cypress/webpack-dev-server');
    on('dev-server:start', options => startDevServer({ options, webpackConfig: webpackConfig }));
  
    return config;
  };
  ```
</details>

### Desired behavior

Since both scripts use same config and `cypress open-ct` succeeds, outcome of running `cypress run-ct` should be a successful test execution as shown in [docs](https://docs.cypress.io/guides/component-testing/introduction#Set-up-CI):
<img width="300" alt="Screen Shot 2021-06-03 at 6 49 33 PM" src="https://user-images.githubusercontent.com/22001260/120733655-72820d00-c49c-11eb-857b-8d640931504a.png">

In case of an error, ideally would be nice to see an additional, more descriptive message that we can act on, if possible. `Proxy request error. This is likely the socket hangup issue, we can basically ignore this because the stream will automatically continue once the asset will be available Error: socket hang up` makes reader go 🤷‍♂️ (unless you've seen this issue before)

### Versions

Running in local terminal
macOs Big Sur, Version 11.3
Electron 89 OR Chrome 91 
"cypress": "^7.4.0",
"@cypress/webpack-dev-server": "^1.3.0"
"webpack": "^4.46.0"

**Comment by jennifer-shehane** [comment]
There are a couple of places this could have thrown from this file: https://github.com/cypress-io/cypress/blob/develop/packages/server-ct/src/routes-ct.ts#L56:L56

We should probably distinguish these 2 errors from each other for debugging purposes. 

Yes, I agree about the error not being helpful - the way this was written it seems like it was only expected to be thrown as an internal error to the team, not to Cypress users.

**Comment by vladyslavkuliani** [comment]
Found the cause of the issue. Build was failing to compile some `.test.ts` file in the repo which was resulting in `[webpack-dev-middleware] Failed to compile.` error. However app was still served at `http://localhost:8080` and was fully accessible.

Result of starting dev server:
<img width="1274" alt="Screen Shot 2021-06-04 at 10 05 26 PM" src="https://user-images.githubusercontent.com/22001260/120880742-f9101a80-c580-11eb-986d-5a4f41f1f436.png">

Since app was accessible and `cypress open-ct` was running tests successfully, I didn't even pay attention to this failure while debugging this issue. Randomly decided to try fixing compilation failure and luckily it worked.

@jennifer-shehane Wondering if there's a way to change `cypress run-ct` to still be able to run tests in this case, since `cypress open-ct` manages to run them. That would be ideal, I guess.
Alternatively, as we've mentioned above, displaying some detailed error message would be extremely helpful here.

Not closing this issue since looks like there're couple action items here.

**Comment by emilyrohrbough** [comment]
`cypress run-ct` was removed in Cypress 10.0. The current Cypress version is 11.0 where component testing was released as GA. I am closing this issue due to inactivity. Please try the latest Cypress version and open a new issue if a similar problem persists.
