### ISSUE TITLE
EMFILE: too many open files, watch cypress.json

### ISSUE THREAD

**Issue by marmelin** [cypress-io/cypress#16849]
### Description
I know there is an [advise](https://github.com/cypress-io/cypress/blob/46e9b3066089014d25bf1169441db6690a5db136/CONTRIBUTING.md#known-problems) for this the problem, but I cannot fix it. 
The open command should just work and it seems to be a node_module cypress uses. 
Please, have a look. 

### Error
`Error: EMFILE: too many open files, watch`

### Facts
I have set redicolously high values for ulimits 
```
❯ ulimit -n
500000
❯ sudo sysctl -a | grep fs.file-max
fs.file-max = 9223372036854775807
❯ cat /proc/sys/fs/inotify/max_user_watches
524288
```
Looks like this `fs.watch` ist not async:
```js
102 function createFsWatchInstance(path, options, listener, errHandler, emitRaw) {
103   const handleEvent = (rawEvent, evPath) => {
104     listener(path);
105     emitRaw(rawEvent, evPath, {watchedPath: path});
106 
107     // emit based on events occurring for files from a directory's watcher in
108     // case the file's watcher misses it (and rely on throttling to de-dupe)
109     if (evPath && path !== evPath) {
110       fsWatchBroadcast(
111         sysPath.resolve(path, evPath), KEY_LISTENERS, sysPath.join(path, evPath)
112       );
113     }
114   };
115   try {
116     return fs.watch(path, options, handleEvent);
117   } catch (error) {
118     errHandler(error);
119   }
120 }

```

### Current behavior
<details><summary>npx cypress open</summary>

```
❯ npx cypress open
[313284:0608/135242.546859:ERROR:proxy_config_service_linux.cc(607)] inotify_init failed: Zu viele offene Dateien (24)
[313284:0608/135242.547107:ERROR:file_path_watcher_linux.cc(315)] inotify_init() failed: Zu viele offene Dateien (24)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[313284:0608/135243.947389:ERROR:proxy_config_service_linux.cc(607)] inotify_init failed: Zu viele offene Dateien (24)
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/first_test/cypress.json'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/datadisk/projects/cypress/first_test/cypress.json',
  filename: '/datadisk/projects/cypress/first_test/cypress.json'
}
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/first_test/cypress.json'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)

```
</details>

### Desired behavior
Just run cypress as described in docu. 

### Test code to reproduce
Follow docu to install cypress 
* `npm install`
* `npx cypress open`

### Versions
```
❯ node --version
v16.3.0
❯ npm --version
7.15.1
* Cypress/7.5.0
```
##### OS
```
Linux  5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jennifer-shehane** [comment]
@marmelin Can you provide a repo of code  where this is reproducible? Can you reproduce this pulling down and running our cypress-example-kitchensink for example? https://github.com/cypress-io/cypress-example-kitchensink

**Comment by marmelin** [comment]
Hey @jennifer-shehane :) thx for quick reply. 

No repo used here .. I simply followed [instruction for npm-installation](https://docs.cypress.io/guides/getting-started/installing-cypress#npm-install) . Exactly those two commands I described in "Test code to reproduce" section. 

I adding os information.

**Comment by marmelin** [comment]
So the 
* kitchensink example is working :heavy_check_mark: . 
* `npx cypress open` works find :heavy_check_mark: 
   Except a little error: 
   ```
   Opening Cypress...
   libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
   ```
*  This is using 7.3.0 ... I used 7.5.0 :exclamation:

**Comment by marmelin** [comment]
now i am getting the same error with kitchensink as well: 
:red_circle: `EMFILE: too many open files, watch`

<details><summary>too many open files</summary>

``` 
❯ npx cypress open
[165855:0611/081815.825268:ERROR:proxy_config_service_linux.cc(607)] inotify_init failed: Zu viele offene Dateien (24)
[165855:0611/081815.825537:ERROR:file_path_watcher_linux.cc(315)] inotify_init() failed: Zu viele offene Dateien (24)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[165855:0611/081817.175301:ERROR:proxy_config_service_linux.cc(607)] inotify_init failed: Zu viele offene Dateien (24)
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink/cypress.json'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/datadisk/projects/cypress/cypress-example-kitchensink/cypress.json',
  filename: '/datadisk/projects/cypress/cypress-example-kitchensink/cypress.json'
}
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink/cypress.json'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)

Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink/cypress/plugins/index.js'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/datadisk/projects/cypress/cypress-example-kitchensink/cypress/plugins/index.js',
  filename: '/datadisk/projects/cypress/cypress-example-kitchensink/cypress/plugins/index.js'
}
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink/cypress/plugins/index.js'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleFile (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:355:23)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:617:21)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)

Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleDir (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:548:19)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:597:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/datadisk/projects/cypress/cypress-example-kitchensink',
  filename: '/datadisk/projects/cypress/cypress-example-kitchensink'
}
Error: EMFILE: too many open files, watch '/datadisk/projects/cypress/cypress-example-kitchensink'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:116:15)
    at setFsWatchListener (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:325:14)
    at NodeFsHandler._handleDir (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:548:19)
    at NodeFsHandler._addToNodeFs (/home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:597:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/markus/.cache/Cypress/7.3.0/Cypress/resources/app/packages/server/node_modules/chokidar/index.js:435:21
    at Function.all (<anonymous>:null:null)
```
</details>

**Comment by marmelin** [comment]
## [SOLVED] :heavy_check_mark: Fixed with `fs.inotify.max_user_instances = 256`

#### For Linux:
Check current value of max_user_instances:
`$ cat /proc/sys/fs/inotify/max_user_instances`
increase that value:
`$ echo 256 > /proc/sys/fs/inotify/max_user_instances`
> Note: sudo ... does not work, you have to switch to root or use `sudo su -c ... `

In order to make that change permanent add a line to /etc/sysctl.conf:
`fs.inotify.max_user_instances = 256`

**Comment by jennifer-shehane** [comment]
@marmelin Thanks for sharing your solution.
