### ISSUE TITLE
Cannot find module 'webpack-dev-server'

### ISSUE THREAD

**Issue by ga-devfront** [cypress-io/cypress#16845]
### Current behavior
I'm trying to install Cypress on my existing Nuxt (2.15.6) project with this command :
`yarn add --dev cypress @cypress/vue @cypress/webpack-dev-server html-webpack-plugin@4`
After this I change my `cypress/plugins/index.js` file with this code :
```js
const { startDevServer } = require('@cypress/webpack-dev-server')
const { getWebpackConfig } = require('nuxt')

module.exports = (on, config) => {
  on('dev-server:start', async (options) => {
    const webpackConfig = await getWebpackConfig()
    return startDevServer({
      options,
      webpackConfig,
    })
  })

  return config
}
```
And the I try to run `yarn run cypress open` the window give me the error below.

### Debug logs

**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/alexis/Documents/www/myTeam/myProject/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that&#x27;s the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** 
```
Error: Cannot find module 'webpack-dev-server'
Require stack:
- /home/alexis/Documents/www/myTeam/myProject/node_modules/@cypress/webpack-dev-server/dist/startServer.js
- /home/alexis/Documents/www/myTeam/myProject/node_modules/@cypress/webpack-dev-server/dist/index.js
- /home/alexis/Documents/www/myTeam/myProject/cypress/plugins/index.js
- /home/alexis/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /home/alexis/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/alexis/Documents/www/myTeam/myProject/node_modules/@cypress/webpack-dev-server/dist/startServer.js:29:46)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/alexis/Documents/www/myTeam/myProject/node_modules/@cypress/webpack-dev-server/dist/index.js:14:23)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
```
**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/alexis/Documents/www/myTeam/myProject/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/alexis/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/lib/errors.js:988:15)
    at EventEmitter.<anonymous> (/home/alexis/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/lib/plugins/index.js:160:21)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/home/alexis/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

### Download method
 

- [ ] npm
- [X] yarn 1.22.10
- [ ] Direct download
- [ ] other 

### Operating System
 

- [X] Linux x86_64 // Ubuntu 20.04.2 LTS
- [ ] Mac
- [ ] Windows

### Other

- [X] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI 
Same issue in other repo : https://github.com/cypress-io/cypress-component-examples/issues/2

**Comment by lmiller1990** [comment]
Hey,

You will need to install `webpack-dev-server`. Although Next.js uses webpack for development, they bundle their own version inside the `@next` namespace - we cannot access it. For that reason, you need to install it yourself (basically a peer dependency). [Documentation](https://docs.cypress.io/guides/component-testing/framework-configuration#Next-js-Webpack-4).

This should be in the docs - have we missed it somewhere? If so, please share and I'll update it. For now, try adding `webpack-dev-server` and everything should just work.

**Comment by lmiller1990** [comment]
Are you still having this problem? I saw something similar with `vite-dev-server`. Posted a related comment here: https://github.com/cypress-io/cypress-component-examples/issues/2#issuecomment-868991078

I think this is something to do with `yarn`. I installed Yarn 2 recently and a LOT of my projects are having problems now (even ones still using Yarn 1).

**Comment by JessicaSachs** [comment]
I think you had a typo above @lmiller1990. He's talking about Nuxt, not Next 😛. I just validated that Nuxt works, but only after they explicitly install the webpack-dev-server. Going to close this issue.
