### ISSUE TITLE
In K8S, cypress always crashes if enable video recording

### ISSUE THREAD

**Issue by holphi** [cypress-io/cypress#16863]
I use Jenkins and Kubernetes as the CI test solution, I set up 3 CI agents in my test job, perviously, the Jenkins job ran successfully, however, recently, I notice that the cypress always crashes in video recording, pls refer to below error, at first I thought it was resources issue, so I tried assigning more memory(requested memory: 1Gi) and CPU resource(requested CPU: 2000m) for those 3 CI agents, but the error is still there unless I turn off video recording in cypress.json. Does anyone meet this error before in k8s env? How can I resolve this issue? thanks you in advance!

### Error logs:

Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

Error: ffmpeg was killed with signal SIGKILL
    at ChildProcess.<anonymous> (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

### Test code to reproduce
On each CI agent, I use below cypress command to run test:
npx cypress run --parallel --headless --browser=firefox --record --key XXXXXXXXXXXXXXXXXXXXXXXXXX

### Versions:
I tried below docker images, both of them reproduce the issue

cypress/included:7.1.0
cypress/included:7.4.0

**Comment by holphi** [comment]
I finally realized this issue is caused by insufficient resource, I have set the the CPU resource to 2Gi and memory resource to 4000m, now I can those 3 CI agents can run tests and process video successfully and I don't see the issue anymore!

This ticket can be closed!
