### ISSUE TITLE
BaseURL parameter not working in GitHub Actions

### ISSUE THREAD

**Issue by bart-kosmala** [cypress-io/cypress#16878]
### Current behavior

The `baseURL` parameter of `cypress.json` is not working with GitHub Actions CI pipeline. It **skips** the base part when using `cy.visit()`. It works normally when used locally.

Part of error log:
```log
  Running:  login.spec.ts                                                                   (1 of 2)


  Login page
    1) fills inputs and logs in


  0 passing (619ms)
  1 failing

  1) Login page
       fills inputs and logs in:
     CypressError: `cy.visit()` failed trying to load:

/signin

We failed looking for this file at the path:

/home/runner/work/inz/inz/frontend/webapp/signin

The internal Cypress web server responded with:

  > 404: Not Found
      at http://localhost:38291/__cypress/runner/cypress_runner.js:138889:25
      at visitFailedByErr (http://localhost:38291/__cypress/runner/cypress_runner.js:138264:12)
      at http://localhost:38291/__cypress/runner/cypress_runner.js:138869:13
      at tryCatcher (http://localhost:38291/__cypress/runner/cypress_runner.js:10798:23)
      at Promise._settlePromiseFromHandler (http://localhost:38291/__cypress/runner/cypress_runner.js:8733:31)
      at Promise._settlePromise (http://localhost:38291/__cypress/runner/cypress_runner.js:8790:18)
      at Promise._settlePromise0 (http://localhost:38291/__cypress/runner/cypress_runner.js:8835:10)
      at Promise._settlePromises (http://localhost:38291/__cypress/runner/cypress_runner.js:8911:18)
      at _drainQueueStep (http://localhost:38291/__cypress/runner/cypress_runner.js:5505:12)
      at _drainQueue (http://localhost:38291/__cypress/runner/cypress_runner.js:5498:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:38291/__cypress/runner/cypress_runner.js:5514:5)
      at Async.drainQueues (http://localhost:38291/__cypress/runner/cypress_runner.js:5384:14)
  From Your Spec Code:
      at Context.eval (http://localhost:38291/__cypress/tests?p=cypress/integration/login.spec.ts:118:12)
```

### Desired behavior

`cv.visit()` with suffix location and a specified `baseURL` works normally in GitHub Actions.

Or any kind of documentation that says it is not supposed to.

### Test code to reproduce

Used this `react.yml` CI:
```yml
name: React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          working-directory: frontend/webapp
          start: npm start
          wait-on: http://localhost:3000
          config-file: false
```

Project uses `react-app-rewired` for monaco editor webpack.

### Versions

Cypress is `^7.5.0`.

`package.json` snippet:
```json
{
  ...
  "dependencies": {
    "@babel/plugin-transform-modules-commonjs": "^7.13.8",
    "@hookform/resolvers": "^1.3.6",
    "@material-ui/core": "^4.11.3",
    "@material-ui/data-grid": "*",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.58",
    "@types/node": "^14.14.37",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "@types/react-google-recaptcha": "^2.1.0",
    "@types/react-rte": "^0.16.1",
    "@types/react-transition-group": "^4.4.1",
    "axios": "^0.21.1",
    "chokidar": "^2.1.8",
    "monaco-editor-webpack-plugin": "^3.1.0",
    "nanoid": "^3.1.22",
    "normalize.css": "^8.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-google-login": "^5.2.2",
    "react-google-recaptcha": "^2.1.0",
    "react-hook-form": "^6.15.5",
    "react-loading-overlay-ts": "^0.2.0",
    "react-monaco-editor": "^0.43.0",
    "react-router-dom": "^5.2.0",
    "react-rte": "^0.16.3",
    "react-scripts": "^4.0.3",
    "react-transition-group": "^4.4.1",
    "styled-components": "^5.2.3",
    "typescript": "^4.2.3",
    "yup": "^0.32.9"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject",
    "lint": "eslint src/**/*.ts src/**/*.tsx",
    "format": "prettier --write \"**/*.+(ts|tsx|json|css|md)\"",
    "cypress": "cypress open"
  },
  ...
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^13.1.1",
    "@types/jest": "^26.0.23",
    "@types/react-router-dom": "^5.1.7",
    "@types/styled-components": "^5.1.9",
    "babel-eslint": "^10.1.0",
    "cypress": "^7.5.0",
    "eslint": "^7.23.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.23.1",
    "eslint-plugin-react-hooks": "^4.1.0",
    "prettier": "^2.1.1",
    "react-app-rewired": "^2.1.8"
  },
  "proxy": "http://localhost:8000"
}
```

**Comment by bahmutov** [comment]
You used the parameters config-file false, thus your baseUrl is not read from that file

**Comment by bart-kosmala** [comment]
Thanks for lightning fast response, will fix that later on my side.
