### ISSUE TITLE
Error launching browser, Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds, The CDP port requested was 50877.

### ISSUE THREAD

**Issue by DrNio13** [cypress-io/cypress#16908]
### Current behavior
**Title:** Error launching browser

![0](https://user-images.githubusercontent.com/11769448/121708509-eee9a100-cad7-11eb-8111-ba427abb07ff.PNG)

**Message:** 
 
 [Downloading and starting the Electron Starting Guide example from the docs](https://www.electronjs.org/), build the binaries , for example _/out/electron-quick-start-win32-x64/electron-quick-start.exe_ and link that Electron Browser to Cypress Browsers list to execute the tests ( 
 https://docs.cypress.io/guides/guides/launching-browsers#Launching-by-a-path )
 Currently this causes the following error:
 
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">50877</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:50877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m50877[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:50877
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

    at get (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\errors.js:988:15)
    at Object.throwErr [as throw] (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\errors.js:1006:9)
    at C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\browsers\protocol.js:106:21
    at tryCatcher (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\perivolg\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```
### Desired behavior
 [Downloading and starting the Electron Starting Guide example from the docs](https://www.electronjs.org/), build the binaries for example _/out/electron-quick-start-win32-x64/electron-quick-start.exe_ and link that Electron Browser to Cypress Browsers list to execute the tests ( 
 https://docs.cypress.io/guides/guides/launching-browsers#Launching-by-a-path )

### Test code to reproduce
Test taken from Cypress.io 

    const execa = require('execa')
    const findBrowser = () => {
    const browserPath =
        '{path_to}/electron-quick-start/out/electron-quick-start-win32-x64/electron-quick-start.exe'

    return execa(browserPath, ['--version']).then((result) => {

        return {
            name: 'My.Electron.Browser',
            channel: 'stable',
            family: 'chromium',
            displayName: 'My.Electron.Browser',
            version: '1.0.0',
            path: browserPath,
            majorVersion: '1.0.0',
        }
    })
}

    module.exports = (on, config) => {
        return findBrowser().then((browser) => {
            return {
                browsers: config.browsers.concat(browser),
            }
        })
    }

### Versions
Cypress (latest) 7.5.0
Electron (latest) 13.1.2 (starting guide repo https://github.com/electron/electron-quick-start )

**Comment by jennifer-shehane** [comment]
@DrNio13 Our previous guide on testing in Electron is a bit out of date, so there's likely issues launching this way. Which guide from Cypress did you follow for this?

**Comment by DrNio13** [comment]
@jennifer-shehane thanks for the quick reply. I basically followed this guide https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers 

Is there a better guide that I could follow? I just want to have control on which Electron Browser Cypress will run the tests.

**Comment by johngrimsey** [comment]
Am seeing this here too, different port but same error. I've also experienced some Chrome crashes which have caused macOS to send a problem report to Apple. Just trying to run Cypress in watch mode.

<img width="1405" alt="Screenshot 2021-06-18 at 11 29 26" src="https://user-images.githubusercontent.com/898591/122551308-b47a8980-d02c-11eb-94ce-6cce04fc50a7.png">

**Comment by icortex** [comment]
I'm having the same issue running Cypress 8.0.0 on Mac M1. It works for others with Mac running on Intel.

**Comment by tammistov** [comment]
same issue running Cypress 8.2.0 or 8.3.0 on a mac with Chrome 92. With Edge 92 I can run the tests 

![image](https://user-images.githubusercontent.com/77278405/130043728-c0a6548e-97df-41fe-a8ea-bb0b23ccd651.png)

**Comment by huangweilinag** [comment]
macOS 10.15.5 ,  cypress 8.3.0
![image](https://user-images.githubusercontent.com/22027570/130612279-eb6fc550-8a3f-4df2-ba9d-89e816ff39d9.png)

**Comment by shanshanrjz** [comment]
> macOS 10.15.5 , cypress 8.3.0
> ![image](https://user-images.githubusercontent.com/22027570/130612279-eb6fc550-8a3f-4df2-ba9d-89e816ff39d9.png)

i have the same issue

**Comment by truefalse10** [comment]
I am having the same issue macOS 12.2.1 (M1), Cypress 9.4.1
