### ISSUE TITLE
TypeError: Cannot read property 'started' of undefined

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#1693]
### Current behavior: 
Random test failure with the following error message:
```
TypeError: Cannot read property 'started' of undefined
    at Reporter.mergeRunnable (/usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:81:18)
    at Reporter.parseArgs (/usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:200:20)
    at Reporter.emit (/usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/reporter.js:190:23)
    at Object.server.startWebsockets.onMocha (/usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/project.js:288:22)
    at Socket.<anonymous> (/usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /usr/local/lib/node_modules/cypress/dist/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Desired behavior:
Not to fail.

### Steps to reproduce:
Hard, I've tried running on random tests and that's the error I got.
Run cypress run with both electron/ chrome. I haven't tried with cypress open as it would take too long.

```js
  mergeRunnable = function(testProps, runnables) {
    var runnable;
    runnable = runnables[testProps.id];
    if (!runnable.started) { // runnable is undefined and that's how the test if failing to execute
      testProps.started = Date.now();
    }
    return _.extend(runnable, testProps);
  };
```

### Versions  

2.1.0

**Comment by Bkucera** [comment]
@paulpruteanu Thanks! Currently trying to reproduce

**Comment by jennifer-shehane** [comment]
Hey @paulpruteanu, unfortunately we'll have to close this issue since no reproducible example was provided.

**Comment by Bkucera** [comment]
@paulpruteanu feel free to leave a comment here if you've got more information or want this re-opened :+1:
