### ISSUE TITLE
Error running plugin: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed

### ISSUE THREAD

**Issue by dipika654** [cypress-io/cypress#16941]
Getting this issue while working with Cypress- cucumber preprocessor
**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\AJ\CypressAutomation\cypress\plugins\index.js`)

**Details:** 

```
TypeError: Cannot destructure property 'name' of '(intermediate value).parse(...).feature' as it is undefined.
    at module.exports (C:\Users\AJ\CypressAutomation\node_modules\cypress-cucumber-preprocessor\lib\loader.js:29:11)
    at Stream.end (C:\Users\AJ\CypressAutomation\node_modules\cypress-cucumber-preprocessor\lib\index.js:24:18)
    at _end (C:\Users\AJ\CypressAutomation\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\AJ\CypressAutomation\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\AJ\CypressAutomation\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (C:\Users\AJ\CypressAutomation\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\AJ\CypressAutomation\cypress\plugins\index.js`)
    at Object.get (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\errors.js:988:15)
    at EventEmitter.handleError (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\plugins\index.js:175:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\AJ\AppData\Local\Cypress\Cache\7.5.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Package.json:**
```json
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^7.5.0",
    "cypress-cucumber-preprocessor": "^4.1.2",
    "cypress-xpath": "^1.6.2"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
```
 

index.js
```js
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
```

**Comment by jennifer-shehane** [comment]
@dipika654 Just looking at the code above, it looks like you wrote everything correctly. 

This looks like an issue with `cypress-cucumber-preprocessor`, which is not a plugin that Cypress maintains. I would suggest opening an issue in that repo: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor
