### ISSUE TITLE
Cypress fails when a png is imported down the file path

### ISSUE THREAD

**Issue by Vishwaas** [cypress-io/cypress#17023]
In one of the acceptance files, I am trying to import a file which inturn imports a png file(not sure if that is a good practice)

Eg: (note this code is not related to cypress but part of main app.
```
//in  some-cypress-accetpance.test.spec.js
import SomeSrcFile from '../../../../../src/mock-data/controller.js"

//in mock-data/controller.js
import SomePng from './fixtures/mockImage.png"
```

Then cypress fails with 

```
SyntaxError: Unexpected character '�'
    at EventEmitter.handler (C:\Users\.....\AppData\Local\Cypress\Cache\7.4.0\Cypress\resources\app\packages\server\lib\plugins\util.js:69:27)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\....\AppData\Local\Cypress\Cache\7.4.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by Vishwaas** [comment]
Moving from browserify-preprocessor to webpack-preprocessor solved the issue
