### ISSUE TITLE
e.onFail is not a function

### ISSUE THREAD

**Issue by Terbiy** [cypress-io/cypress#17070]
### Current behavior
When Cypress faces a failing page with unlimited HTTP redirects, it ends up with the confusing `e.onFail is not a function` error in the *After All* hook.
![изображение](https://user-images.githubusercontent.com/2117141/123063688-4fe97100-d416-11eb-8d09-28237203df80.png)

Here is the `e` object coming to the `response` object in the `catch` method in `installLogsCollector.js`. I cleaned sensitive data replacing the URL and removing my machine name:
```json
{
    "name": "CypressError",
    "docsUrl": "https://on.cypress.io/request",
    "appendToStack":
    {
        "title": "From Node.js Internals",
        "content": "RequestError: Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://example.com\n    at new RequestError ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at $HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:988:19\n    at processRedirect ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/lib/redirect.js:104:14)\n    at tryCatcher ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] ($HOME/Library/Caches/Cypress/6.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:456:21)\n"
    }
}
```

### Desired behavior
Cypress should print the text of the `content` property from `e.appendToStack`.

### Test code to reproduce
Cypress should encounter a page with a redirect loop. Mine is internal, and I do not know any other.🤔

### Versions

6.2.1

**Comment by sainthkh** [comment]
Sorry for the late reply. You can create a infinitely redirecting pages [like here](https://github.com/cypress-io/cypress/pull/14643/files#diff-5e53bb7db65fc81d310c138c5a898b24e34d6211bf2c29468492712f8d2888d3). 

As we all know, the debugging starts with reproducing the bug on the developer's local machine. Can you provide me a reproducible example?

**Comment by sainthkh** [comment]
Closing because of the inactivity. If the problem continues to happen, please open a new issue with a reproducible example.

**Comment by Terbiy** [comment]
I was on vacation, sorry for the late reply. I cannot reproduce this because the problem occurred when Cypress faced the infinitely looping HTTP redirect, no JS-based one. I tried to find the example somewhere on the web, but didn't succeed.

**Comment by sainthkh** [comment]
I tested it with the code below, but failed to reproduce it.

```js
// server.js

const express = require('express')
const app = express()
const port = 3000

app.get('/a', (req, res) => {
  res.redirect('/b')
})

app.get('/b', (req, res) => {
  res.redirect('/a')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

```js
// test.js

it('server-side infinite redirection', () => {
    cy.visit('http://localhost:3000/a')
});
```

I got the error below:

![image](https://user-images.githubusercontent.com/8130013/126919614-3e335419-0757-4911-bc52-1ae367c17f5d.png)
