### ISSUE TITLE
Cannot install cypress locally to project

### ISSUE THREAD

**Issue by fypnlp** [cypress-io/cypress#17083]
Installation seems to be stuck at `reify:rxjs: timing reifyNode:node_modules/lodash` and will not go any further.

### Debug logs

```
node:3289) ExperimentalWarning: The fs.promises API is experimental
npm WARN EBADENGINE Unsupported engine { package: 'cypress@7.5.0',
npm WARN EBADENGINE   required: { node: '>=12.0.0' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.12.1' } }
npm WARN EBADENGINE Unsupported engine { package: 'extract-zip@2.0.1',
npm WARN EBADENGINE   required: { node: '>= 10.17.0' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.12.1' } }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
⸨                  ⸩ ⠇ reify:rxjs: timing reifyNode:node_modules/lodash Completed in 3579ms
```

Then.  It appeared to be installed  so I did `npx open cypress`   it would not allow me to open cypress and asked me to run `npm fund'.

I typed `npm fund` and the  following was displayed in the debug log (I modified the my name for confidentiality)

```
my_machine e@my-MacBook-Air Cypress API Sample % npm fund
(node:3875) ExperimentalWarning: The fs.promises API is experimental
cypress-api-sample@1.0.0
├── https://github.com/sponsors/feross
│   └── arch@2.2.0, safe-buffer@5.2.1
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.1
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
├─┬ https://github.com/sindresorhus/execa?sponsor=1
│ │ └── execa@4.1.0
│ └── https://github.com/sponsors/sindresorhus
│     └── get-stream@5.2.0, onetime@5.1.2, is-installed-globally@0.4.0, global-dirs@3.0.0, log-symbols@4.1.0, is-unicode-supported@0.1.0, pretty-bytes@5.6.0, cli-truncate@2.1.0, log-update@4.0.0, ansi-escapes@4.3.2, type-fest@0.21.3, p-map@4.0.0
├── https://github.com/chalk/supports-color?sponsor=1
│   └── supports-color@8.1.1
├── https://github.com/sponsors/epoberezkin
│   └── ajv@6.12.6
├── https://github.com/chalk/wrap-ansi?sponsor=1
│   └── wrap-ansi@7.0.0
└── https://github.com/sponsors/isaacs
    └── rimraf@3.0.2, glob@7.1.7
```
I just found this complete debug log.  I'm not sure if it's necessary but I' will add it to the ticket as well (modified my id for confidentiality)

```
I've just found these complete logs. I honestly don't know what you need, but I will add these as well. 
0 verbose cli [ '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'opoen' ]
1 info using npm@7.12.1
2 info using node@v10.13.0
3 timing npm:load:whichnode Completed in 6ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/my_machine/Documents/Cypress API Sample/.npmrc Completed in 3ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/Users/my_machine/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 8ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 29ms
19 timing npm:load:configload Completed in 29ms
20 timing npm:load:setTitle Completed in 13ms
21 timing npm:load:setupLog Completed in 4ms
22 timing npm:load:cleanupLog Completed in 3ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 2ms
25 timing npm:load Completed in 59ms
26 timing config:load:flatten Completed in 3ms
27 http fetch GET 404 https://registry.npmjs.org/opoen 1156ms
28 http fetch GET 404 https://registry.npmjs.org/opoen 702ms
29 timing command:exec Completed in 1889ms
30 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/opoen - Not found
30 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:134:15)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
31 verbose statusCode 404
32 verbose pkgid opoen@latest
33 verbose cwd /Users/jacquelinegeorge/Documents/Cypress API Sample
34 verbose Darwin 20.5.0
35 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "opoen"
36 verbose node v10.13.0
37 verbose npm  v7.12.1
38 error code E404
39 error 404 Not Found - GET https://registry.npmjs.org/opoen - Not found
40 error 404
41 error 404 'opoen@latest' is not in the npm registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit 1
```

My current version of node is `7.12.1 `

Installation command sequence

npm init -y
npm install cypress --save-dev

### Download method
 

- [x ] npm
- [ ] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 
Big Sur version 11.4

- [ ] Linux
- [x ] Mac
- [ ] Windows

### Other

- [ x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by fypnlp** [comment]
here is a [video](https://www.dropbox.com/s/bobihe1h3iv20cv/cypress%20software%20bug.mp4?dl=0) of what I am experiencing

**Comment by jennifer-shehane** [comment]
@fypnlp Thanks for attaching the video that was very helpful. There's some initial logs when you try to install Cypress that show some warnings about the Node version. 

```
Unsupported engine { package: 'cypress.7.5.0',
  required { node: '>=12.0.0' },
  current { node: 'v10.13.0', npm: '7.12.1' } }
```

This displays as just a warning and it will just continue on installing Cypress, then when you try to run Cypress some code within Cypress won't run because it actually does depend on your having Node.js >= 12.0.0.

So, you'll need to update your Node.js version from v10.13.0 to something above 12+, which is a requirement in Cypress versions greater than 7.0. https://on.cypress.io/installing-cypress#Node-js
