### ISSUE TITLE
Test Runner crashes when running test in `develop` branch

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#17131]
### Current behavior

I just happened to run a specific test that I was testing in 7.6.0 in the `develop` branch and the Test Runner crashes when it is run in Electron and hangs in Chrome. 

Maybe it's related to something else, but wanted to do some investigation on whether something was recently merged that's making this crash.

#### Electron error upon crash

```
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.addContext (_tls_wrap.js:1420:32)
    at /Users/jennifer/Dev/cypress/packages/https-proxy/lib/server.js:222:23
    at tryCatcher (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
 {
  library: 'PEM routines',
  function: 'OPENSSL_internal',
  reason: 'NO_START_LINE',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.addContext (_tls_wrap.js:1420:32)
    at /Users/jennifer/Dev/cypress/packages/https-proxy/lib/server.js:222:23
    at tryCatcher (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jennifer/Dev/cypress/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
```

### Desired behavior

Not crash :) 

### Test code to reproduce

```js
it('test', () => {
  cy.visit('https://mocki.io/fake-json-api')
})
```

### Versions

`develop` branch - non-user facing

**Comment by jennifer-shehane** [comment]
This turned out to be a duplicate of https://github.com/cypress-io/cypress/issues/8705 Clearing app data fixed the issue.
