### ISSUE TITLE
Cannot read property 'scrollY' of undefined in a nested iframe. 

### ISSUE THREAD

**Issue by nalmabrcom** [cypress-io/cypress#17175]
### Current behavior
Trying to find an element within a nested iframe brings `Cannot read property 'scrollY' of undefined `. 

![image](https://user-images.githubusercontent.com/65608274/124125879-6036c700-da7a-11eb-8834-fd5d8a13f6ae.png)

```
TypeError: Cannot read property 'scrollY' of undefined
      at Object.getElementPositioning (https://theia/__cypress/runner/cypress_runner.js:159393:49)
      at elAtCenterPoint (https://theia/__cypress/runner/cypress_runner.js:162330:32)
      at elIsNotElementFromPoint (https://theia/__cypress/runner/cypress_runner.js:162364:22)
      at isHidden (https://theia/__cypress/runner/cypress_runner.js:162206:12)
      at Object.isVisible (https://theia/__cypress/runner/cypress_runner.js:162129:11)
      at Array.../driver/src/config/jquery.js.$.expr.filters.visible (https://theia/__cypress/runner/cypress_runner.js:130023:37)
      at https://theia/__cypress/runner/cypress_runner.js:89233:22
      at superMatcher (https://theia/__cypress/runner/cypress_runner.js:89454:12)
      at Sizzle.select (https://theia/__cypress/runner/cypress_runner.js:89633:44)
      at Sizzle (https://theia/__cypress/runner/cypress_runner.js:87801:9)
      at Function.Sizzle.matchesSelector (https://theia/__cypress/runner/cypress_runner.js:88460:9)
      at tryFn (https://theia/__cypress/runner/cypress_runner.js:129999:30)
      at tryCatchFinally (https://theia/__cypress/runner/cypress_runner.js:129970:12)
      at Function.../driver/src/config/jquery.js.$.find.matchesSelector (https://theia/__cypress/runner/cypress_runner.js:129997:10)
      at Function.jQuery.filter (https://theia/__cypress/runner/cypress_runner.js:89805:22)
      at winnow (https://theia/__cypress/runner/cypress_runner.js:89787:17)
```

### Desired behavior
It is possible to find and click on the element. 

### Test code to reproduce
HTML:
```html
<iframe class="webview" sandbox="allow-scripts allow-forms allow-same-origin" src="https://theia/webview/index.html?id=132873a1-ecae-4436-9963-5d315e2b441d" style="border: none; width: 100%; height: 100%;">
    <iframe id="active-frame" frameborder="0" sandbox="allow-scripts allow-forms allow-same-origin" src="./fake.html?id=132873a1-ecae-4436-9963-5d315e2b441d" style="display: block; margin: 0px; overflow: hidden; position: absolute; width: 100%; height: 100%; visibility: visible;">
        <div id="root">
            <div class="holder">
                ...
            </div>
        </div>
    </iframe>
</iframe>

```
```js
cy.frameLoaded('iframe.webview').iframe().within(() => {
     cy.frameLoaded('iframe#active-frame').iframe().within((body) => {
           cy.wrap(body).find('holder')
            });
      });
```     

### Versions
Cypress: 7.1.0
Cypress-iframe: 1.0.1

**Comment by jennifer-shehane** [comment]
You may want to open an issue with cypress-iframe plugin as we don't support this natively at the moment. We're currently working on support for this in https://github.com/cypress-io/cypress/issues/136

**Comment by nalmabrcom** [comment]
@jennifer-shehane So the iframe support will be included in cypress_8.0? 😮 
Can you approximately tell when it will be? :)
