### ISSUE TITLE
Cannot read property 'message' of undefined - makeErrFromObj - cypress_runner.js

### ISSUE THREAD

**Issue by emericspiroux** [cypress-io/cypress#17208]
### Current behavior

Tests fail on `uncaught:exception` but it's not on my code.

The issue happen inside `cypress_runner.js`, `obj` seems to be empty and this param is not verified.
```
const makeErrFromObj = obj => {
  +if (!obj) return new Error("Unknown Error"); <---Fix proposal, work with it 🤷‍♂️
  const err2 = new Error(obj.message); <---- Message doesn't exist
  err2.name = obj.name;
  err2.stack = obj.stack;

  _.each(obj, (val, prop) => {
    if (!err2[prop]) {
      err2[prop] = val;
    }
  });

  return err2;
};
```

![image](https://user-images.githubusercontent.com/8082005/124593965-87690c00-de5f-11eb-86a0-3803da51423b.png)
![image](https://user-images.githubusercontent.com/8082005/124593993-918b0a80-de5f-11eb-93e3-ca6c3bec8768.png)

```
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
    at makeErrFromObj (http://localhost:3001/__cypress/runner/cypress_runner.js:154359:30)
    at errorFromProjectRejectionEvent (http://localhost:3001/__cypress/runner/cypress_runner.js:154711:10)
    at Object.errorFromUncaughtEvent (http://localhost:3001/__cypress/runner/cypress_runner.js:154717:65)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:150977:23
From previous event:
    at run (http://localhost:3001/__cypress/runner/cypress_runner.js:151331:21)
    at $Cy.cy.<computed> [as interceptRecall] (http://localhost:3001/__cypress/runner/cypress_runner.js:151804:11)
    at __stackReplacementMarker (http://localhost:3001/__cypress/runner/cypress_runner.js:150811:13)
    at Context.runnable.fn (http://localhost:3001/__cypress/runner/cypress_runner.js:152028:21)
    at callFn (http://localhost:3001/__cypress/runner/cypress_runner.js:107792:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3001/__cypress/runner/cypress_runner.js:107779:7)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:158033:28
From previous event:
    at Object.onRunnableRun (http://localhost:3001/__cypress/runner/cypress_runner.js:158021:17)
    at $Cypress.action (http://localhost:3001/__cypress/runner/cypress_runner.js:148112:28)
    at Test.Runnable.run (http://localhost:3001/__cypress/runner/cypress_runner.js:156163:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3001/__cypress/runner/cypress_runner.js:108451:10)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:108577:12
    at next (http://localhost:3001/__cypress/runner/cypress_runner.js:108360:14)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:108370:7
    at next (http://localhost:3001/__cypress/runner/cypress_runner.js:108272:14)
    at Hook.<anonymous> (http://localhost:3001/__cypress/runner/cypress_runner.js:108333:7)
    at next (http://localhost:3001/__cypress/runner/cypress_runner.js:157949:22)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:157976:11
From previous event:
    at onNext (http://localhost:3001/__cypress/runner/cypress_runner.js:157973:57)
    at done (http://localhost:3001/__cypress/runner/cypress_runner.js:107732:5)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:107797:11
From previous event:
    at callFn (http://localhost:3001/__cypress/runner/cypress_runner.js:107795:14)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3001/__cypress/runner/cypress_runner.js:107779:7)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:158033:28
From previous event:
    at Object.onRunnableRun (http://localhost:3001/__cypress/runner/cypress_runner.js:158021:17)
    at $Cypress.action (http://localhost:3001/__cypress/runner/cypress_runner.js:148112:28)
    at Hook.Runnable.run (http://localhost:3001/__cypress/runner/cypress_runner.js:156163:13)
    at next (http://localhost:3001/__cypress/runner/cypress_runner.js:108294:10)
    at http://localhost:3001/__cypress/runner/cypress_runner.js:108338:5
    at timeslice (http://localhost:3001/__cypress/runner/cypress_runner.js:102264:27)
```

### Desired behavior
Test doesn't fail.

### Test code to reproduce
N/A

### Versions
Cypress 7.6.0
Chrome Version 91.0.4472.114 (Build officiel) (x86_64)
Mac 11.2.3

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Can you give me the problematic test case? As we all know, we write tests to prevent regression and we need test cases to write tests.

**Comment by sainthkh** [comment]
Closing because of the inactivity. 

If something similar happens, please open a new issue with reproducible examples.
