### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by cardil** [cypress-io/cypress#17288]
### Current behavior

We are experiencing the following error:

```
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
    at ClientRequest.<anonymous> (/home/jenkins/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
 {
  code: 'EPIPE'
}
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
    at ClientRequest.<anonymous> (/home/jenkins/.cache/Cypress/7.5.0/Cypress/resources/app/packages/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

This stack trace is from Cypress 7.5.0, but updating it to latest 7.7.0 doesn't solve the issue.

The following link captures recent CI builds that are affected: [search.ci.openshift.org ws-incoming.js:115:16 in serverless-operator](https://search.ci.openshift.org/?search=ws-incoming.js%3A115%3A16&maxAge=336h&context=1&type=build-log&name=.*serverless-operator.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

This bug report is almost identical #5787 and #6458 which both were _"addressed"_ in #6945 and released in Cypress 4.4.0. 

I think that solution isn't the proper one.

### Desired behavior

I'm convinced that the solution that was applied in https://github.com/cypress-io/node-http-proxy/commit/9322b4b69b34f13a6f3874e660a35df3305179c6 doesn't cover all possible cases.

I did try using the @caosm solution from this comment https://github.com/http-party/node-http-proxy/issues/1342#issuecomment-570105853, and it helped (https://github.com/caosm/node-http-proxy/commit/46d02be9533cc800e32b0df510149ca35e7453cb). After applying this patch, I don't see `EPIPE` errors anymore.

### Test code to reproduce

This problem is flaky. I can't provide other evidence than our CI search engine, here: [search.ci.openshift.org ws-incoming.js:115:16 in serverless-operator](https://search.ci.openshift.org/?search=ws-incoming.js%3A115%3A16&maxAge=336h&context=1&type=build-log&name=.*serverless-operator.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

I could provide instructions to run our test suite - the following error should emerge after a couple of runs (especially on small VMs, maybe not connected?!?)

### Cypress Version

7.7.0

**Comment by pbadenski** [comment]
Does anyone perhaps have any more colour on this?

I'm experiencing similar issue with similar looking stack trace on 8.2.0.

**Comment by cardil** [comment]
As far as I know, this still isn't fixed yet. There's an open PR that should fix it https://github.com/cypress-io/node-http-proxy/pull/1, but that needs some work.

Meanwhile, we are running this work around: https://github.com/openshift-knative/serverless-operator/pull/1101 so you could do similar in your project.

**Comment by KittyGiraudel** [comment]
This workaround no longer works in Cypress v10. It throws with the following error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tasks/state' is not defined by "exports" in /projectname/node_modules/cypress/package.json
```

**Comment by Aishwarya-U-R** [comment]
Any resolution here for the above subpath issue? Still seeing the same on Cy 12 aswell.

**Comment by Aishwarya-U-R** [comment]
Able to solve this by updating below reference in apply-patches.js - from Cy 10 onwards.

`const { getVersionDir } = require("../node_modules/cypress/lib/tasks/state");
`

**Comment by nanek** [comment]
Noting here for visibility, that I was experiencing this issue all the time and after manually applying the patch provided in https://github.com/cypress-io/node-http-proxy/pull/1#issue-943216887 (from July 2021 👀 ) it fixed this issue completely for my team. Cypress now reliably runs every time in CI.

**Comment by LubosD** [comment]
I am still seeing this issue with Cypress 15.2.0.

I think the web app being tested is trying to open a WS connection to the wrong URL, but this shouldn't be a reason for test runner crashing...
