### ISSUE TITLE
Cypress.automation('remote:debugger:protocol') command started failing in Cypress 7.3.0

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#17723]
### Current behavior

Starting in 7.3.0, the test code below (mostly copied from https://www.cypress.io/blog/2020/11/12/testing-application-in-offline-network-mode/) throws this error:

```
CypressError: `cy.then()` timed out after waiting `4000ms`.

Your callback function returned a promise that never resolved.

The callback function was:

() => Cypress.automation('remote:debugger:protocol', {
      command: 'Network.emulateNetworkConditions',
      params: {
        offline: true,
        latency: -1,
        downloadThroughput: -1,
        uploadThroughput: -1
      }
    })
    at https://www.cypress.io/__cypress/runner/cypress_runner.js:136167:24
From previous event:
    at Context.thenFn (https://www.cypress.io/__cypress/runner/cypress_runner.js:136166:13)
    at Context.then (https://www.cypress.io/__cypress/runner/cypress_runner.js:136597:21)
    at Context.<anonymous> (https://www.cypress.io/__cypress/runner/cypress_runner.js:151455:21)
From Your Spec Code:
    at Context.eval (https://www.cypress.io/__cypress/tests?p=cypress/integration/spec.js:133:9)
```

### Desired behavior

The test should run without error.

### Test code to reproduce

Set the `baseUrl` configuration key (e.g. `"https://www.cypress.io"`) and run the following spec. I can reproduce without setting the `baseUrl` but it's a little more complicated and I think this is better as a MWE.

```
describe('page', () => {
  it('tries to go offline', () => {
    cy.log('**go offline**')
    .then(() =>
      Cypress.automation('remote:debugger:protocol', { command: 'Network.enable' })
    )
      .then(() => 
        Cypress.automation('remote:debugger:protocol', {
          command: 'Network.emulateNetworkConditions',
          params: {
            offline: true,
            latency: -1,
            downloadThroughput: -1,
            uploadThroughput: -1
          }
        })
      );
    cy.visit('/');
  });
});
```

### Cypress Version

7.3.0

### Other

I encountered this when attempting to update to the latest version of Cypress, but traced it back to 7.3.0. Version 7.2.0 runs without error.

It looks like at least a couple other people have encountered this based on the comments on that blog post. I found that modifying the callback in the second `then` to not return anything did allow my tests to get further, only to hang indefinitely at random places in my test file so, as I suspected, that isn't a real solution.

**Comment by InfiniteTape** [comment]
+1 to this. I'm seeing the same problem.

**Comment by szhong-becls** [comment]
The same regression issue in `8.0.0`

**Comment by c32hedge** [comment]
@jennifer-shehane did this get lost? It's been two weeks with no response 😦

**Comment by c32hedge** [comment]
@jennifer-shehane Gleb pointed me to this Cypress recipe on the Cypress Gitter: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/server-communication__offline/cypress/integration/offline-spec.js

Which is almost identical to my code except for the use of braces and explicit return statements for the arrow function bodies. Yet, I was able to use the MWE above in a cypress-test-tiny fork and trace the failure back to 7.3.0 as described.

I realize this is a bit of an obscure feature, but you have blogs and recipes that reference it, and multiple people, both here and in the comments on the blog post, are struggling getting code referenced in those blogs/recipes to work in newer versions of Cypress. Could you at least confirm whether you can reproduce the error I'm seeing?

**Comment by raultm** [comment]
any idea or workaround? Can i get an older version of cypress to make it work?

It only fails when is not localhost, in fact i can go offline but i cant recover from this status to the online status

https://github.com/cypress-io/cypress/issues/17723#issuecomment-906152925

**Comment by svenjungnickel** [comment]
A quick workaround would be using a version before cypress 7.0.0. As I stated here https://github.com/cypress-io/cypress-example-recipes/issues/721#issuecomment-920609040 I got it successfully running in version 6.9.1.

**Comment by szhong-becls** [comment]
Another "work around". With the fact that `Network.emulateNetworkConditions` and `offline: true` did set the Chrome network to offline, but Cypress cannot receive the command execution result. So we can tell Cypress to ignore this particular error, and continue to run our test specs.

```ts
cy.on('fail', e => {
  if (
    e.name === 'CypressError'
    && e.message.includes('timed out')
    && e.message.includes('remote:debugger:protocol')
    && e.message.includes('Network.emulateNetworkConditions')
    && e.message.includes('offline: true')
  ) {
    // do not fail the test
    return false;
  }
});

cy.log('**go offline**')
  .then(() =>
    Cypress.automation('remote:debugger:protocol', { command: 'Network.enable' })
  )
  .then(() =>
    Cypress.automation('remote:debugger:protocol', {
      command: 'Network.emulateNetworkConditions',
      params: {
        offline: true,
        latency: -1,
        downloadThroughput: -1,
        uploadThroughput: -1
      }
    })
  );
```

**Comment by svenjungnickel** [comment]
@szhong-becls your workaround did not work for me, unfortunately.

**Comment by matthew-nash-cko** [comment]
Any update on this?  My tests are also failing where this functionality is required

**Comment by lorenzofidalgo** [comment]
I am also suffering with this issue.
I have confirmed Cypress 6.9.1 is still working properly. I have tested Cypress 6.9.1 against Chrome 96 and Electron 87 (working properly in both cases).
Cypress 8.7.0 fails, Cypress 9.0.0 fails. So, or we go back to 6.9.1, or...

**Comment by maayanz1** [comment]
Same for me :( 
Cannot upgrade cypress version because of this issue

**Comment by Gu7z** [comment]
Same! :eyes:

**Comment by ughunoup** [comment]
Same, still not working in 9.1.1

Do anyone know alternative solution to simulate browser offline mode?

**Comment by weilu** [comment]
Same here. Stuck with 6.9.1 because of this issue

**Comment by distante** [comment]
> Another "work around". With the fact that `Network.emulateNetworkConditions` and `offline: true` did set the Chrome network to offline, but Cypress cannot receive the command execution result. So we can tell Cypress to ignore this particular error, and continue to run our test specs.
> 
> ```ts
> cy.on('fail', e => {
>   if (
>     e.name === 'CypressError'
>     && e.message.includes('timed out')
>     && e.message.includes('remote:debugger:protocol')
>     && e.message.includes('Network.emulateNetworkConditions')
>     && e.message.includes('offline: true')
>   ) {
>     // do not fail the test
>     return false;
>   }
> });
> 
> cy.log('**go offline**')
>   .then(() =>
>     Cypress.automation('remote:debugger:protocol', { command: 'Network.enable' })
>   )
>   .then(() =>
>     Cypress.automation('remote:debugger:protocol', {
>       command: 'Network.emulateNetworkConditions',
>       params: {
>         offline: true,
>         latency: -1,
>         downloadThroughput: -1,
>         uploadThroughput: -1
>       }
>     })
>   );
> ```

This workaround worked for my with `cypress open` but hangs for `cypress run`

**Comment by xdubx** [comment]
same problem on "cypress": "^9.6.1"

**Comment by weilu** [comment]
Can we please get this working? None of the workarounds above works anymore. I hate to be stuck with version 6.9 because of this

**Comment by snefa** [comment]
We were also going offline and online in tests and are missing it... +1 here.

**Comment by asmirnov-style** [comment]
Year 2023 
Cypress v10.3.1
Hi there!👋 
Issue with `going back online` still exist.

**Comment by robertbenthompson** [comment]
Hope everyone had a happy holiday season!
As of v12.3.0 looks like the remote:debugger:protocol still fails to go back online.
Can anyone else confirm?

**Comment by Shnrqpdr** [comment]
> Hope everyone had a happy holiday season! As of v12.3.0 looks like the remote:debugger:protocol still fails to go back online. Can anyone else confirm?

Yes, unfortunately this issue stills.
Any workaround that worked for you?

**Comment by AlanCodega** [comment]
Cypress 12.6.0, still has the same issue!
How do you guys test offline/online in Cypress??

**Comment by Shnrqpdr** [comment]
> Cypress 12.6.0, still has the same issue! How do you guys test offline/online in Cypress??

Pls check my answer (the final answer in the issue discussion) at https://github.com/cypress-io/cypress/issues/235 (i couldn't cite the issue), that workaround worked for me.

**Comment by xdubx** [comment]
> Cypress 12.6.0, still has the same issue! How do you guys test offline/online in Cypress??

@AlanCodega  mock all requests

**Comment by asmirnov-style** [comment]
Kind a way for simulate OFFLINE (while Cypress team fixing 4 y.o bug)
```
` goOfflineIntercept() {
        cy.log("**go offline**").then(() => {
            cy.intercept(
                {
                    method: "GET",
                    url: "*",
                },
                {
                    statusCode: 404, // if you like and need it
                }
            );
        });
    }

goOnlineIntercept() {
        cy.log("**go online**").then(() => {
            cy.intercept("GET", "*", (req) => {
                req.continue();
            });
        });
    }`
```

**Comment by KaiVandivier** [comment]
Thanks @asmirnov-style!

I adapted mine a bit too:
```js
const goOffline = () => {
    cy.log('**go offline**')
        // stub every request with a StaticResponse to simulate network error
        .then(() => cy.intercept('*', { forceNetworkError: true }))
        .then(() =>
            cy.window().then((win) => win.dispatchEvent(new Event('offline')))
        )
}
const goOnline = () => {
    cy.log('**go online**')
        // go back to normal network behavior
        .then(() => cy.intercept('*'))
        .then(() =>
            cy.window().then((win) => win.dispatchEvent(new Event('online')))
        )
}
```

**Comment by buffcode** [comment]
Modifying the real `onLine` attribute, tested in Cypress 12.11.0:
```js
// go offline
cy.window().then((win) => {
  cy.stub(win.navigator, 'onLine').value(false);
  cy.wrap(win).trigger('offline');
});

// go online
cy.window().then((win) => {
  cy.stub(win.navigator, 'onLine').value(true);
  cy.wrap(win).trigger('online');
});
```

**Comment by megos** [comment]
Is this issue fixed in v13?

I tried [this test](https://github.com/cypress-io/cypress-example-recipes/tree/2c973d7a53a22629f398c4038a7568897d621de9/examples/server-communication__offline) and the results are as follows:

- v12.17.4: failed
- v13.0.0: passed

**Comment by jennifer-shehane** [comment]
This is resolved as of Cypress v13.0.0. In v13, Chromium-family browsers (Chrome, Edge, Electron) no longer use the <socket.io/engine.io> WebSocket for the driver↔server channel. They communicate over a CDP-based socket instead. Since <engine.io>-client is no longer in that path, the offline listener that closed the transport is gone, and Cypress.automation('remote:debugger:protocol', { command: 'Network.emulateNetworkConditions', params: { offline: true } }) no longer times out.

This matches @megos’s confirmation above (v12.17.4 fails, v13.0.0 passes) using the server-communication__offline recipe.

If you’re on v13+ and still hitting an offline-related issue (e.g., in Firefox/WebKit, which don’t support CDP), please open a new issue with a reproducible example. Closing this one out. Thanks for your patience!
