### ISSUE TITLE
TypeScript aliases not recognized when tsconfig.json file is in Cypress folder

### ISSUE THREAD

**Issue by shawn-e-harris** [cypress-io/cypress#17788]
### Current behavior

When trying to import an `Enum` alias from a Typescript file within the Cypress folder as described in the docs, the webpack cannot resolve the alias, even though it is defined in the `tsconfig.json` file

### Desired behavior

Properly import aliases from `tsconfig.json` files in the Cypress folder without needing to place `tsconfig.json` with at root project directory.

### Test code to reproduce

https://github.com/shawn-e-harris/typeScriptAlias.git

### Cypress Version

8.2.0

### Other

Error: Webpack Compilation Error
./cypress/support/helper/helpers.js
Module not found: Error: Can't resolve '@alias-example/sub-folder/app-code.ts' in '/Users/joel.whalen/Documents/src/reproducers/alias-error-cypress/cypress/support/helper'
resolve '@alias-example/sub-folder/app-code.ts' in '/Users/joel.whalen/Documents/src/reproducers/alias-error-cypress/cypress/support/helper'
  Parsed request is a module
  using description file: /Users/joel.whalen/Documents/src/reproducers/alias-error-cypress/package.json (relative path: ./cypress/support/helper)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:

**Comment by TomaszG** [comment]
@jennifer-shehane I see you've added the `existing workaround` label, could you point to that workaround?

**Comment by masaya-fukazawa** [comment]
I have the same problem, is there a solution?

**Comment by johncrim** [comment]
Try the custom webpack config with ts-loader that I posted here:

https://github.com/cypress-io/cypress/issues/19066#issuecomment-1001308186

**Comment by TomaszG** [comment]
@johncrim, thanks for that, this would work if you don't have any preprocessor files already defined (as Cypress doesn't support multiple file preprocessors). 

The perfect solution for Cypress would be to automatically load the tsconfig.json file (and paths from it) if there's such in its root directory.

**Comment by Vestride** [comment]
I ran into what appears to have been a similar issue after doing a large migration which included TS 3 to 4. My `cypress/tsconfig.json` extended a TS config from my `node_modules`.

That config file at `<project_root>/node_modules/@company/config-typescript/tsconfig.base.json` config file set the `"baseUrl"` to `"../../../src"`.

I fixed my issue by setting the `"baseUrl"` in my `cypress/tsconfig.json` file to `"../src"`

**Comment by wenqi73** [comment]
Adding `"baseUrl": "./",` will resolve this.

**Comment by DevKhaira** [comment]
Is there a solution when there is a tsconfig that exists outside the cypress folder (in root), 
I want to create a few component tests, but blocked by this issue. I have tried to use the ts-loader, but to no avail

the folder stricture is
root
   cypress/
       -all the cypress goodies including a tsconfig file that extends the root tsconfig file
   -tsconfig.json (where the paths exist)

**Comment by RicFer01** [comment]
Does someone know how to use aliases when you use CRA? I tried everything, but I always get error from Cypress gui, something like:
`> Cannot find module '@src/components/menu/Menu'`
even if from linting and ts point of view is working, if I click on the path it leads me to the correct component.

**Comment by kelzvictoria** [comment]
I was able to solve this with:
```js
//cypress.config.ts
import path from 'path';
import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },

  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
      webpackConfig: {
        resolve: {
          alias: {
            '@': path.resolve(__dirname, 'src'),
          },
        },
      },
    },
  },
});
```
source: https://github.com/muratkeremozcan/tour-of-heroes-react-cypress-ts/blob/main/cypress.config.ts

**Comment by eloisetaylor5693** [comment]
> I was able to solve this with:
> 
> ```js
> //cypress.config.ts
> import path from 'path';
> import { defineConfig } from 'cypress';
> 
> export default defineConfig({
>   e2e: {
>     setupNodeEvents(on, config) {
>       // implement node event listeners here
>     },
>   },
> 
>   component: {
>     devServer: {
>       framework: 'create-react-app',
>       bundler: 'webpack',
>       webpackConfig: {
>         resolve: {
>           alias: {
>             '@': path.resolve(__dirname, 'src'),
>           },
>         },
>       },
>     },
>   },
> });
> ```
> 
> source: https://github.com/muratkeremozcan/tour-of-heroes-react-cypress-ts/blob/main/cypress.config.ts

Using `path.resolve(__dirname, 'src'),` resolved it for me

**Comment by kleinfreund** [comment]
This is labeled with [existing workaround](https://github.com/cypress-io/cypress/issues?q=state%3Aopen%20label%3A%22existing%20workaround%22), but I don't see a clear candidate in this thread. What is the workaround?

With the docs at https://docs.cypress.io/app/tooling/typescript-support, I have a `cypress/tsconfig.json` file inside a project that itself has a `tsconfig.json` file with `compilerOptions.paths` that the TS config inside the `cypress` directory is unaware of. I don't know how to set this TS config up in such a way that it's aware of the root TS config's path aliases.

In another attempt, I moved the Cypress TS config into the root as `tsconfig.cypress.json` (trying to emulate common Vite/Vue setups):

```json
{
  "extends": "./tsconfig.app.json",
  "include": ["env.d.ts", "cypress/**/*.ts"],
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.cypress.tsbuildinfo",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "sourceMap": true,
    "types": ["cypress", "node"]
  }
}
```

This now allows the path aliases to be correctly resolved but breaks Cypress with the following error:

```
The error was:

[commonjs--resolver] No known conditions for "./node" specifier in "msw" package
    at e (file:///Users/user/project/node_modules/vite/dist/node/chunks/dep-Bg4HVnP5.js:9074:8)
    ...
    at async file:///Users/user/project/node_modules/rollup/dist/es/shared/node-entry.js:21390:50

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```
