### ISSUE TITLE
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (/Users/Vedika/aol_tests/cypress/plugins/index.js)

### ISSUE THREAD

**Issue by vedaj16** [cypress-io/cypress#17814]
### Current behavior

My tests were running fine until today i got this error "The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (/Users/Vedika/aol_tests/cypress/plugins/index.js)"

CompositeParserException: Parser errors:(33:9): inconsistent cell count within the table
    at Function.Errors.CompositeParserException.create (/Users/Vedika/aol_tests/node_modules/gherkin/lib/gherkin/errors.js:27:13)
    at Parser.parse (/Users/Vedika/aol_tests/node_modules/gherkin/lib/gherkin/parser.js:72:45)
    at module.exports (/Users/Vedika/aol_tests/node_modules/cypress-cucumber-preprocessor/lib/loader.js:29:33)
    at Stream.end (/Users/Vedika/aol_tests/node_modules/cypress-cucumber-preprocessor/lib/index.js:24:18)
    at _end (/Users/Vedika/aol_tests/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/Vedika/aol_tests/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/Vedika/aol_tests/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (/Users/Vedika/aol_tests/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

### Desired behavior

All my tests should have passed. 

### Test code to reproduce

Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/Vedika/aol_tests/cypress/plugins/index.js`)
    at Object.get (/Users/Vedika/Library/Caches/Cypress/8.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1012:15)
    at EventEmitter.handleError (/Users/Vedika/Library/Caches/Cypress/8.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:189:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (/Users/Vedika/Library/Caches/Cypress/8.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

### Cypress Version

Version 8.1.0

**Comment by dhamo-pk** [comment]
Looks like this is specific to `cypress-cucumber-preprocessor` and NOT related to `Cypress`. 
Please double-check your feature file structure and I guess the `Scenario Outline-Example`  table may not be complete.
