### ISSUE TITLE
Cypress is not running test after launch

### ISSUE THREAD

**Issue by PrLu** [cypress-io/cypress#18013]
### Current behavior

I recently installed cypress and new to this platform as well,
I can see that my test runs on browser like edge, but i don't see why it is not running in chrome.

Cypress version i have in my system
Cypress package version: 8.3.1
Cypress binary version: 8.3.1
Electron version: 13.2.0
Bundled Node version:
14.16.0

Chrome version is 92.

The test running in headless and edge browser but not running in chrome.

I don't see CY extension in the plugin area, i cleared the AppData from the documentation but still i am not able to see.
Manually i added the plugin from webstore but still not working.

Below is the log after passing cmd in terminal as "npx cypress open"
PS C:\LearningArea\pCypressLearning> npx cypress open
Debugger attached.
Debugger attached.

Debugger attached.
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 24/62)
Failed to connect to Chrome, retrying in 1 second (attempt 25/62)
Failed to connect to Chrome, retrying in 1 second (attempt 26/62)
Failed to connect to Chrome, retrying in 1 second (attempt 27/62)
Failed to connect to Chrome, retrying in 1 second (attempt 28/62)
Failed to connect to Chrome, retrying in 1 second (attempt 29/62)
Failed to connect to Chrome, retrying in 1 second (attempt 30/62)
Failed to connect to Chrome, retrying in 1 second (attempt 31/62)
Failed to connect to Chrome, retrying in 1 second (attempt 32/62)
Failed to connect to Chrome, retrying in 1 second (attempt 33/62)
Failed to connect to Chrome, retrying in 1 second (attempt 34/62)
Failed to connect to Chrome, retrying in 1 second (attempt 35/62)
Failed to connect to Chrome, retrying in 1 second (attempt 36/62)
Failed to connect to Chrome, retrying in 1 second (attempt 37/62)
Failed to connect to Chrome, retrying in 1 second (attempt 38/62)
Failed to connect to Chrome, retrying in 1 second (attempt 39/62)
Failed to connect to Chrome, retrying in 1 second (attempt 40/62)
Failed to connect to Chrome, retrying in 1 second (attempt 41/62)
Failed to connect to Chrome, retrying in 1 second (attempt 42/62)
Failed to connect to Chrome, retrying in 1 second (attempt 43/62)
Failed to connect to Chrome, retrying in 1 second (attempt 44/62)
Failed to connect to Chrome, retrying in 1 second (attempt 45/62)
Failed to connect to Chrome, retrying in 1 second (attempt 46/62)
Failed to connect to Chrome, retrying in 1 second (attempt 47/62)
Failed to connect to Chrome, retrying in 1 second (attempt 48/62)
Failed to connect to Chrome, retrying in 1 second (attempt 49/62)
Failed to connect to Chrome, retrying in 1 second (attempt 50/62)
Failed to connect to Chrome, retrying in 1 second (attempt 51/62)
Failed to connect to Chrome, retrying in 1 second (attempt 52/62)
Failed to connect to Chrome, retrying in 1 second (attempt 53/62)
Failed to connect to Chrome, retrying in 1 second (attempt 54/62)
Failed to connect to Chrome, retrying in 1 second (attempt 55/62)
Failed to connect to Chrome, retrying in 1 second (attempt 56/62)
Failed to connect to Chrome, retrying in 1 second (attempt 57/62)
Failed to connect to Chrome, retrying in 1 second (attempt 58/62)
Failed to connect to Chrome, retrying in 1 second (attempt 59/62)
Failed to connect to Chrome, retrying in 1 second (attempt 60/62)
Failed to connect to Chrome, retrying in 1 second (attempt 61/62)
Failed to connect to Chrome, retrying in 1 second (attempt 62/62)
PS C:\LearningArea\pCypressLearning> 

Cypress ui error after test failed.
**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">63672</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:63672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m63672[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:63672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

    at get (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\lib\errors.js:1012:15)
    at Object.throwErr [as throw] (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\lib\errors.js:1030:9)
    at C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\lib\browsers\protocol.js:113:21
    at tryCatcher (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Prem.Padayachi\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```
Cypress UI screenshot
![image](https://user-images.githubusercontent.com/27160235/132390344-b8e086f2-1005-4d0f-8c23-9f4ea7385ea8.png)

Chrome browser screenshot
![image](https://user-images.githubusercontent.com/27160235/132390077-9f6d1078-44e4-425d-a1b4-407194e8be5a.png)

Please help me!!

### Desired behavior

I am expecting it to identify the chrome browser and start working

### Test code to reproduce

/// <reference types="cypress" />

it("Launch google",function(){

    cy.visit("https://www.google.com/")
    

})

it("Searching something on google", () =>{

    cy.get('[title=Search]').type("who is prem padayachi")

    cy.get('form').submit()

})

### Cypress Version

8.3.1

### Other

please help

**Comment by ogasawaraShinnosuke** [comment]
@PrLu 
I'm not sure if it's the same problem.
For in my case, the cypress process that started before is still alive and does trouble, so set below script to "package.json".

```json
// package.json
{
  "scripts": {
    "kill:cypress": "pgrep -fi cypress | xargs kill -9"
  }
}
```

To launch terminal, and type to "yarn run kill:cypress", so this problem is fixed in my case.

**Comment by jaisannaidu** [comment]
I am havin exactly the same issue after installing Chrome 93.0.4577.63. I have 8.3.1 cypress installed. As soon as I launch any tests from the test runner it crashes everything. Following error is thrown in console prompt:
OperationalError: true
    at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
    at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:586:8)
 {
  cause: Error: true
      at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
      at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
      at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
      at WebSocket.emit (events.js:315:20)
      at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
      at Receiver.emit (events.js:315:20)
      at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
      at afterWrite (internal/streams/writable.js:466:5)
      at onwrite (internal/streams/writable.js:446:7)
      at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
      at Zlib.processCallback (zlib.js:586:8)
  ,
  isOperational: true
}
Error: true
    at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
    at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.3.1\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:586:8)

**Comment by ogasawaraShinnosuke** [comment]
@jaisannaidu 
I make https://github.com/ogasawaraShinnosuke/nextjs-with-ts-and-cypress with a minimal configuration of nextjs + ts + cypress in.

If you'd like, you can try it below.

```tsx
yarn install
yarn run cypress
```

**Comment by jaisannaidu** [comment]
@ogasawaraShinnosuke 
I tried your approach for this:
{
  "scripts": {
    "killallcypress": "pgrep -fi cypress | xargs kill -9"
  }
}

However windows down't like pgrep command.

**Comment by ogasawaraShinnosuke** [comment]
@jaisannaidu Okay, I haven't used Windows OS for many years, so I don't know much about it, but you can tgry this command: https://stackoverflow.com/a/10153249/7438513

**Comment by jaisannaidu** [comment]
![image](https://user-images.githubusercontent.com/52753342/132757191-ac57516f-293b-4c32-8ae0-2f81b34e35c4.png)

**Comment by ogasawaraShinnosuke** [comment]
CDP errors are often due to process conflicts. In the end, what I wanted to do with yarn scripts was to get the process numbers of all cypress processes and kill them.

**Comment by jaisannaidu** [comment]
@ogasawaraShinnosuke 

I am still having this crashing issue. I have deleted all the cypress files/folders and reinstall everything and still the tests crash when clicking on individual tests from the test runner and even running headless it's crashing.

And as far as the processes go...I see 5 process under Cypress. If I kill them the test runner closes. What else can I do to fix this issue. My chrome version is 93.0.4577.82 | Cypress 8.4.0.

Here is the error from the crash:
POST /ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 990.170 ms - -
GET /chrome-variations/seed?osname=win&channel=stable&milestone=93 304 1001.502 ms - -
GET /service/update2/crx?os=win&arch=x64&os_arch=x86_64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=93.0.4577.63&lang=en-US&acceptformat=crx3&x=id%3Dbfgjjammlemhdcocpejaompfoojnjjfn%26v%3D0.0.0.0%26installedby%3Dpolicy%26uc%26brand%3DGCEU%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dinohlibcpnggdbkmmonaloneikeodinh%26v%3D0.0.0.0%26installedby%3Dpolicy%26uc%26brand%3DGCEU%26ping%3Dr%253D-1%2526e%253D1 200 1100.463 ms - -
Failed to connect to Chrome, retrying in 1 second (attempt 18/62)
Failed to connect to Chrome, retrying in 1 second (attempt 19/62)
Failed to connect to Chrome, retrying in 1 second (attempt 20/62)
Failed to connect to Chrome, retrying in 1 second (attempt 21/62)
Failed to connect to Chrome, retrying in 1 second (attempt 22/62)
HEAD / - - ms - -
HEAD / - - ms - -
HEAD / - - ms - -
Failed to connect to Chrome, retrying in 1 second (attempt 23/62)
Failed to connect to Chrome, retrying in 1 second (attempt 24/62)
Failed to connect to Chrome, retrying in 1 second (attempt 25/62)
Failed to connect to Chrome, retrying in 1 second (attempt 26/62)
Failed to connect to Chrome, retrying in 1 second (attempt 27/62)
Failed to connect to Chrome, retrying in 1 second (attempt 28/62)
OperationalError: true
    at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
    at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:586:8)
 {
  cause: Error: true
      at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
      at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
      at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
      at WebSocket.emit (events.js:315:20)
      at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
      at Receiver.emit (events.js:315:20)
      at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
      at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
      at afterWrite (internal/streams/writable.js:466:5)
      at onwrite (internal/streams/writable.js:446:7)
      at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
      at Zlib.processCallback (zlib.js:586:8)
  ,
  isOperational: true
}
Error: true
    at maybeWrapAsError (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
    at Chrome._handleMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:437:14)
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:394:23
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:308:9
    at C:\Users\jaisan\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:391:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:586:8)

**Comment by jaisannaidu** [comment]
This was a user profile permission issue. Which I was able to resolve by installing cypress in a different folder.
