### ISSUE TITLE
yarn 2 -  @cypress/webpack-dev-server tried to access lodash, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by francisu** [cypress-io/cypress#18070]
### Current behavior

Use cypress component testing with cypress-react-selector with yarn 2 (PnP)

>  yarn cypress open-ct

The function exported by the plugins file threw an error.

We invoked the function exported by `/Users/francis/temp/test-material-ui/cypress/plugins/index.js`, but it threw an error.

 Error: @cypress/webpack-dev-server tried to access lodash, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: lodash
Required by: @cypress/webpack-dev-server@virtual:75543d871e7c13242968c702e15bd65752052208169d6a9c713f2479a33c6be9684ca5208d64d7483a58061fe11b15c623f68d66865cff731493cbf160b2633a#npm:1.6.0 (via /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/)

Require stack:
- /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/plugin.js
- /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js
- /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/startServer.js
- /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/index.js
- /Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-react-virtual-cf8e38ac08/0/cache/@cypress-react-npm-5.10.0-0880f09a0c-eaa959ffaa.zip/node_modules/@cypress/react/plugins/react-scripts/index.js
- /Users/francis/temp/test-material-ui/cypress/plugins/index.js
- /Users/francis/Library/Caches/Cypress/8.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/francis/Library/Caches/Cypress/8.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.external_module_.Module._resolveFilename (/Users/francis/temp/test-material-ui/.pnp.cjs:31396:55)
    at external_module_.Module._load (/Users/francis/temp/test-material-ui/.pnp.cjs:31195:48)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/plugin.js:8:34)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at external_module_.Module._load (/Users/francis/temp/test-material-ui/.pnp.cjs:31245:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/francis/temp/test-material-ui/.yarn/__virtual__/@cypress-webpack-dev-server-virtual-64fa467786/0/cache/@cypress-webpack-dev-server-npm-1.6.0-8a7c245dc5-39df29ddd3.zip/node_modules/@cypress/webpack-dev-server/dist/makeWebpackConfig.js:39:34)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)

### Desired behavior

> yarn cypress open-ct

(it works)

### Test code to reproduce

https://github.com/francisu/test-material-ui

> git clone https://github.com/francisu/test-material-ui
> cd test-material-ui
> git checkout yarn2-lodash
> yarn install
> yarn cypress open-ct

### Cypress Version

8.3.1

### Other

Fix is simple, just add lodash as a dependency in npm/webpack-dev-server

_No response_

**Comment by emilyrohrbough** [comment]
@francisu I can confirm that the `@cypress/webpack-dev-server` module is requiring `lodash` although it's not declared as a dependency. Thank you for reporting this bug. Would you be interested in contributing a fix for this issue?

**Comment by francisu** [comment]
> @francisu I can confirm that the `@cypress/webpack-dev-server` module is requiring `lodash` although it's not declared as a dependency. Thank you for reporting this bug. Would you be interested in contributing a fix for this issue?

Happy to, look for a PR soon.

**Comment by rockhold** [comment]
Closing this issue, as it was addressed in https://github.com/cypress-io/cypress/pull/20815
