### ISSUE TITLE
Edge v93 Update - CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.

### ISSUE THREAD

**Issue by Mas2112** [cypress-io/cypress#18118]
### Current behavior

I have run into a new failure after updating Edge from v92 to v93.

Our CI runs Cypress tests headless on Windows Server 2019 (via Azure Devops), multiple agents per server.

Some tests pass, however some tests randomly fail with the following error, if video is disabled:

```
CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
      at http://localhost/__cypress/runner/cypress_runner.js:157422:81
      at tryCatcher (http://localhost/__cypress/runner/cypress_runner.js:13212:23)
      at http://localhost/__cypress/runner/cypress_runner.js:8334:41
      at tryCatcher (http://localhost/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (http://localhost/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (http://localhost/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (http://localhost/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (http://localhost/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (http://localhost/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (http://localhost/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (http://localhost/__cypress/runner/cypress_runner.js:7798:14)
```

If video is enabled, some tests randomly fail with following error:

```
Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (C:\Users\drsesdev\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (C:\Users\drsesdev\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

This does not occur on Chrome or Electron, and strangely, running the tests manually on the server does not result in this issue.

In the meantime, we are running our tests on Chrome.

Does anyone else have this issue?

### Desired behavior

Tests should not fail due to capturing screenshots or videos.

### Test code to reproduce

Install Edge v93 on Windows Server and run Cypress tests headless.

### Cypress Version

8.4.0

**Comment by jennifer-shehane** [comment]
The tests that pass on Chrome and Electron are also run on Windows server? On the same machine in the same conditions?

**Comment by Mas2112** [comment]
> 
> 
> The tests that pass on Chrome and Electron are also run on Windows server? On the same machine in the same conditions?

Yes, same machine, same conditions. The only difference is the parameter passed into --browser.

**Comment by Mas2112** [comment]
I have updated Edge to Version 97.0.1072.62 (Official build) (64-bit), and it is now working again.
