### ISSUE TITLE
Crash when connecting to Dashboard

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#18129]
### Current behavior

Trying to connect a project to record to Cypress Dashboard

```
$ yarn cypress open
yarn run v1.22.10
$ /Users/glebbahmutov/git/mercari-double-helpcenter/node_modules/.bin/cypress open
TypeError: openProject.getRuns(...).then is not a function
    at IpcMainImpl.handleEvent (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js:367:8)
    at apply (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:492:17)
    at IpcMainImpl.wrapper (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:5379:16)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)

TypeError: openProject.getRuns(...).then is not a function
    at IpcMainImpl.handleEvent (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/lib/gui/events.js:367:8)
    at apply (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:492:17)
    at IpcMainImpl.wrapper (/Users/glebbahmutov/Library/Caches/Cypress/8.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:5379:16)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)

✨  Done in 6.82s.
```

But it did write the project ID into `cypress.json` so at least that worked

### Test code to reproduce

Company org, private project

### Cypress Version

8.4.0

**Comment by bahmutov** [comment]
https://user-images.githubusercontent.com/2212006/133663145-0a03aa90-136d-4093-bb47-dd26c089967d.mp4

**Comment by adoshi-branch** [comment]
I'm also seeing this issue, I am on version 8.3.1.

**Comment by jennifer-shehane** [comment]
@adoshi-branch Are you sure you're seeing this on 8.3.1? I am only seeing this on 8.4.0. Please run `cypress --version` and verify

**Comment by adoshi-branch** [comment]
Sorry you are correct I am on version 8.4.0
