### ISSUE TITLE
Cypress runner closes on clicking Runs tab on Test runner after i setup dashboard with google

### ISSUE THREAD

**Issue by ssohal305** [cypress-io/cypress#18150]
### Current behavior

Hi,
- I was trying to setup Cypress Dashboard using my google account. 
- Setup completed and I could see the dashboard updated
- But when I click Runs tab on the Test Runner, it crashes and the test runner unexpectedly crashes with the following error:
**ERROR:**
TypeError: openProject.getRuns(...).then is not a function
    at IpcMainImpl.handleEvent (C:\Users\<uname>\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\lib\gui\events.js:367:8)
    at apply (C:\Users\<uname>\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\lodash\lodash.js:492:17)
    at IpcMainImpl.wrapper (C:\Users\<uname>\AppData\Local\Cypress\Cache\8.4.0\Cypress\resources\app\packages\server\node_modules\lodash\lodash.js:5379:16)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)

Please advice on how I can fix this issue. Thanks.

### Desired behavior

The Cypress TestRunner should not close unexpectedly and there should not be any such errors

### Test code to reproduce

This is not an issue with test code but apparently Cypress specific problem

### Cypress Version

8.4.0

**Comment by jennifer-shehane** [comment]
This was fixed in 8.4.1. Please update to get the latest fix.

**Comment by ssohal305** [comment]
Thanks a lot, it works now!
