### ISSUE TITLE
Vue Slots Seem to Be Broken on the Most Recent Version of Cypress

### ISSUE THREAD

**Issue by thegouge** [cypress-io/cypress#18219]
### Current behavior

Given a Component that looks like this:
```html
<template>
  <div>
    This is a component with a slot!
    <slot></slot>
  </div>
</template>
```

and a test that looks like this:
```js
/// <reference types="Cypress" />
import { mount } from '@cypress/vue'
import SlotTest from './SlotTest.vue'

it('renders a slot', () => {
  mount(SlotTest, {
    slots: {
      default: 'Hello Cypress!',
    },
  })

  cy.contains('Hello Cypress!')
})
```

the current result of the test is as such:
![image](https://user-images.githubusercontent.com/30990869/134519797-cd8d62bc-6b5e-4cf6-8ed0-976ca654afd7.png)

I've tried this same test in both webpack and vite, and the error is consistent

### Desired behavior

The desired behavior is to have the component be able to mount with some slot content, or provide an alternative syntax with which to do so

what's wonky is if you have react in the project, you can mount the component with JSX syntax
```js
it('renders a slot', () => {
  mount(<SlotTest>Hello Cypress!</SlotTest>)

  cy.contains('Hello Cypress!')
})
```
but I can't get named slots to work this way, which is a problem for the component library I'm trying to test

### Test code to reproduce

https://github.com/thegouge/cypress-test-tiny

### Cypress Version

8.4.1

### Other

here's the stack trace for the error:
```
 at render (http://localhost:3000/__cypress/src/node_modules/.vite/@cypress_vue.js?v=56cb5468:19417:31)
    at <unknown> (http://localhost:3000/__cypress/src/node_modules/.vite/@cypress_vue.js?v=56cb5468:19423:19)
    at <unknown> (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:3656:32)
    at renderFnWithContext (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:1725:18)
    at renderSlot (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:5807:54)
    at Proxy._sfc_render (http://localhost:3000/__cypress/src/src/components/SlotTest.vue:9:6)
    at renderComponentRoot (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:1755:40)
    at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:4681:47)
    at ReactiveEffect.run (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:603:22)
    at setupRenderEffect (http://localhost:3000/__cypress/src/node_modules/.vite/chunk-YSTVXQVC.js?v=56cb5468:4773:6)
From previous event:
    at Context.thenFn (http://localhost:3000/__cypress/runner/cypress_runner.js:170233:64)
    at Context.then (http://localhost:3000/__cypress/runner/cypress_runner.js:170685:22)
    at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:186955:24)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:185649:18)
From previous event:
    at runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:185628:11)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:185771:17)
From previous event:
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:199912:80)
From previous event:
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:199907:24)
    at Object.run (http://localhost:3000/__cypress/runner/cypress_runner.js:185825:18)
    at $Cy.cy.<computed> [as then] (http://localhost:3000/__cypress/runner/cypress_runner.js:186995:20)
    at mount2 (http://localhost:3000/__cypress/src/node_modules/.vite/@cypress_vue.js?v=56cb5468:25512:14)
    at Context.<anonymous> (http://localhost:3000/src/components/SlotTest.spec.js?import:6:4)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:187219:24)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:140081:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:140068:8)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:193749:31)
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:193734:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:183300:29)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:191468:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:140740:11)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:140866:13)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:140649:15)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:140659:8)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:140561:15)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:140627:6)
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:134553:28)
```

**Comment by patrickcate** [comment]
I'm getting the same error with Vue 3 and Cypress 8.7.0.

As @lmiller1990 suggested, passing a function to the slot is a workaround.

**Comment by thegouge** [comment]
I appreciate @lmiller1990's workaround, that should do me for my projects!

however I think I'll keep this issue open until it works how it does with the syntax regular `@vue/test-utils` works with, (assuming that's possible)

**Comment by lavoscore** [comment]
Yes, passing a function works. Also, scoped slots were not working for me so as a total shot in the dark I decided to check if that function might receive the bindings as arguments, and... voila, it does!

```typescript
// MyComponent.vue
<slot :item="myExposedValue" />

// MyComponent.spec.js
mount(MyComponent, {
  slots: {
    default: ({ item }) => `Content received: ${item}`, // <-- works!
  }
});
```

This was the only thing that worked for me after hours of searching around. Is this behavior actually documented somewhere?

**Comment by lmiller1990** [comment]
Components are compiled to functions that receive `props` as the first argument. It is kind of documented, in that if you look up render functions in the Vue docs, it tells you props is the first arg, but I don't think it's actually in the Test Utils docs anywhere.

If you want to add some docs in Test Utils, that'd be great. Our DX team is working on more details docs for Component Testing in general, so those will land soon, too.

**Comment by lmiller1990** [comment]
I'd say just use the function callback style - Vue 3 actually requires this, iirc?
