### ISSUE TITLE
Running cypress with unit tests (Jest) problem

### ISSUE THREAD

**Issue by Algoritm211** [cypress-io/cypress#18289]
### Current behavior

Our team wants to use a cypress dashboard to cover the project with tests. We use both cypress tests and unit tests to test our code (Jest + React Testing Library).

The main problem is that when running unit tests, an error occurs that is related to the construction of the DOM inside jest.

We are getting an error that the webpack is not configured correctly:

```
Error: Webpack Compilation Error
./src/components/Toast/index.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .toast_classes {
|   color: #ffffff;
|   --background: #1d201f;
 @ ./src/components/Toast/toast.ts 1:0-21
 @ ./src/redux/payments/action.ts
 @ ./cypress/integration/payments-action.test.ts
    at Watching.handle [as handler] (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:176:23)
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Watching.js:98:28)
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Watching.js:54:20
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/neo-async/async.js:2818:7
    at done (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/alexey/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/webpack/lib/Compiler.js:464:33
```

### Desired behavior

Cypress should run unit-tests with Jest right

### Test code to reproduce
```typescript
import { getAllConsultationPaymentsByMonths } from "src/api/payments";
import { AllTransactionsType } from "src/pages/types";
import { loadAllPaymentsByMonths } from "../../src/redux/payments/action";

jest.mock("src/api/payments");
const allTransactionInfoResult = {
  groupedByMonthUsers: [
    {
      allConsultationsMonthCount: 12,
      allPaymentsMonth: 123,
      monthYear: "Август 2021г",
      _monthTimestamp: 210981230891823,
      users: [
        {
          avatar: "photo",
          id: "someid",
          name: "Alex",
          paymentAmount: 15.44,
          userConsultations: [
            {
              consultationDate: 21312312321,
              paymentAmount: 14.45,
              paymentDate: 123213123212213,
              id: "someid",
            },
          ],
        },
      ],
    },
  ],
} as AllTransactionsType;

const getAllTransactionsInfo =
  getAllConsultationPaymentsByMonths as jest.Mocked<
    typeof getAllConsultationPaymentsByMonths
  >;

//@ts-ignore
getAllTransactionsInfo.mockReturnValue(
  Promise.resolve(allTransactionInfoResult)
);

test("Load all payments info", async () => {
  const thunk = loadAllPaymentsByMonths("H3Klwd5euOzFVWOD5yjgCAi79jh7");

  const dispatchMock = jest.fn();

  await thunk(dispatchMock);

  expect(dispatchMock).toBeCalledTimes(1);
});
```

### Cypress Version

7.5.0

**Comment by Narretz** [comment]
Have you tried using a custom preprocessor? https://docs.cypress.io/api/plugins/preprocessors-api You should probably use the webpack-preprocessor with (parts of your) app webpack config.

I wouldn't expect this to work out of the box, as Cypress isn't supposed to run unit tests per se.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
