### ISSUE TITLE
Test Hang on Open / Cypress Crash on Run

### ISSUE THREAD

**Issue by davymitchell** [cypress-io/cypress#18373]
### Current behavior

I have a problem spec (sorry no shareable repro as yet):

1. OPEN - Runs all of test. Tests pass. 1 error (not visible anywhere) in LHS column. Last describe (regardless of content) never completes - endless spinner.
2. RUN - Cypress exits with the detail below.
```
  Running:  mytest_spec            (1 of 1)
            .js
TypeError: Cannot read property 'length' of undefined
    at isInvalidSuite (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\mocha-junit-reporter\index.js:151:62)
    at MochaJUnitReporter.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\mocha-junit-reporter\index.js:224:10)
    at Runner.emit (events.js:327:22)
    at Reporter.emit (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\reporter.js:333:46)
    at ProjectBase.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\project-base.js:461:34)
    at Generator.next (<anonymous>:null:null)
    at C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at Object.__awaiter (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\tslib\tslib.js:113:16)
    at Object.onMocha (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\project-base.js:454:51)
    at Socket.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\socket-base.js:213:40)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

TypeError: Cannot read property 'length' of undefined
    at isInvalidSuite (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\mocha-junit-reporter\index.js:151:62)
    at MochaJUnitReporter.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\mocha-junit-reporter\index.js:224:10)
    at Runner.emit (events.js:327:22)
    at Reporter.emit (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\reporter.js:333:46)
    at ProjectBase.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\project-base.js:461:34)
    at Generator.next (<anonymous>:null:null)
    at C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at Object.__awaiter (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\node_modules\tslib\tslib.js:113:16)
    at Object.onMocha (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\project-base.js:454:51)
    at Socket.<anonymous> (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\server\lib\socket-base.js:213:40)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\davyj\AppData\Local\Cypress\Cache\8.5.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
### Desired behavior

1. OPEN - Test runs to completion.
2. RUN - Cypress does not crash.

### Test code to reproduce

Not been able to cut down long test to repro as yet.

### Cypress Version

8.5

### Other

Windows 10.

Appreciate any suggestions to help diagnose.

**Comment by davymitchell** [comment]
Please find repro attached. It was down to a test error with a particular helper mistakenly wrapped in an IT, however I think Cypress could handle this error case a little more elegantly. Thanks for looking at this
[2repro_spec.js.txt](https://github.com/cypress-io/cypress/files/7305180/2repro_spec.js.txt)
.
