### ISSUE TITLE
'ERR_TIMED_OUT (-7) loading' 

### ISSUE THREAD

**Issue by pmweeks98** [cypress-io/cypress#18413]
### Current behavior

Occasionally while using docker to run cypress tests on Jenkins this error occurs
 ```
ERR_TIMED_OUT (-7) loading '<base_url>/__/#/tests/integration/<spec>'[39m
[31mError: ERR_TIMED_OUT (-7) loading '<base_url>/__/#/tests/integration/<spec>'[39m
[31m    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)[39m
[31m    at Object.failListener (electron/js2c/browser_init.js:213:1198)[39m
[31m    at Object.emit (events.js:315:20)[39m
```

This is happening with upgrade to cypress 8.5 and did not occur before upgrade with 6.1

### Desired behavior

Test run normally 

### Test code to reproduce

```
docker build -t cypress-6.1.0 -f cypress/support/cases/utilities/Dockerfile .
docker run --shm-size=2g --name cypress-container1 -w /e2e_tests -e CYPRESS_BASE_URL=$ENV_BASE_URL $CYPRESS_CONFIG cypress-6.1.0 --spec "cypress/integration/*.spec.js" --browser electron --env username=$ADMIN_USERNAME,password=$ADMIN_PASSWORD,allure=true
```

### Cypress Version

8.5.0

**Comment by strout** [comment]
There's an older issue #17627 for this.
