### ISSUE TITLE
Cypress crashed when runing demo case with Chrome94

### ISSUE THREAD

**Issue by feiatnokia** [cypress-io/cypress#18427]
### Current behavior

![image](https://user-images.githubusercontent.com/15189659/136649977-e51be416-7e46-44da-81a0-98f430fc2be9.png)
```  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Network.requestWillBeSent' } +85ms
  cypress:server:browsers:cri-client registering CDP on event { eventName: 'Network.responseReceived' } +2ms
  cypress:server:browsers:chrome options.onScreencastFrame is false +95ms
  cypress:server:browsers:chrome received CRI client +1ms
  cypress:server:browsers:chrome navigating to page http://localhost:50707/__/#/tests/integration/1-getting-started/todo.spec.js +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' } +18s
  cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 } +224ms
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
 {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

  cypress:server:browsers browsers.kill called with no active instance +685ms
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 0, immediatelyMatchedRequests: 0, eventuallyReceivedPreRequest: [], neverReceivedPreRequest: [] } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +24s
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +5ms
```
### Desired behavior

demo case should run pass with chrome

https://user-images.githubusercontent.com/15189659/136650311-111ce622-0f43-4f1c-8806-960c61985d6f.mp4

### Test code to reproduce

1. open the cmd
2. npm run cypress
3. select the chrome explore
4. run the demo case

### Cypress Version

8.5.0

### Other

window10 64bit
D:\repos\Cypress>npm -v
6.14.11
D:\repos\Cypress>node -v
v14.16.0

**Comment by lhx196** [comment]
I also have the same problem. What is the solution @jennifer-shehane
