### ISSUE TITLE
Task error propagation broken

### ISSUE THREAD

**Issue by EtienneBruines** [cypress-io/cypress#18641]
### Current behavior
The error message is not shown:

```
  1) the issue
       something specific
         "before each" hook for "works":
     CypressError: `cy.task('some-bad-task')` failed with the following error:

> Error

https://on.cypress.io/api/task

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `the issue`
      at http://localhost:38953/__cypress/runner/cypress_runner.js:158945:78
      at tryCatcher (http://localhost:38953/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (http://localhost:38953/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (http://localhost:38953/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (http://localhost:38953/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (http://localhost:38953/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (http://localhost:38953/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (http://localhost:38953/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:38953/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (http://localhost:38953/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (http://localhost:38953/__cypress/tests?p=cypress/integration/test_spec.js:101:8)
  
  From Node.js Internals:
    Error
        at EventEmitter.handler (/home/etiennebruines/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:69:27)
        at EventEmitter.emit (events.js:376:20)
        at ChildProcess.<anonymous> (/home/etiennebruines/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
        at ChildProcess.emit (events.js:376:20)
        at emit (internal/child_process.js:910:12)
        at processTicksAndRejections (internal/process/task_queues.js:83:21)
    
```

### Desired behavior
The error message shown, e.g. the string `Hello rejected world` being present.

### Test code to reproduce
```ts
// Register the task in plugins/index.js
on('task', {
    'some-bad-task': () => {
        return new Promise((resolve, reject) => {
            reject("Hello rejected world");
        })
    }
})

// Then later in some tests
describe('the issue', () => {
    beforeEach(() => {
        cy.task('some-bad-task')
    })  

    it('works', () => {
    
    })
})
```

### Cypress Version

8.7.0

**Comment by kris-luminar** [comment]
I'm still seeing this issue in Cypress version 13.12.0
