### ISSUE TITLE
Component Testing Alias is undefined

### ISSUE THREAD

**Issue by chunleng** [cypress-io/cypress#18699]
### Current behavior

Error

```
Cannot read properties of undefined (reading 'foo')

at Context.<anonymous> (http://localhost:50847/__cypress/src/static/js/spec-0.chunk.js:45:25)
at Context.runnable.fn (http://localhost:50847/__cypress/runner/cypress_runner.js:187298:24)
at callFn (http://localhost:50847/__cypress/runner/cypress_runner.js:140085:22)
at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:50847/__cypress/runner/cypress_runner.js:140072:8)
at <unknown> (http://localhost:50847/__cypress/runner/cypress_runner.js:193861:31)
at PassThroughHandlerContext.finallyHandler (http://localhost:50847/__cypress/runner/cypress_runner.js:23046:24)
at PassThroughHandlerContext.tryCatcher (http://localhost:50847/__cypress/runner/cypress_runner.js:26492:24)
at Promise._settlePromiseFromHandler (http://localhost:50847/__cypress/runner/cypress_runner.js:24427:32)
at Promise._settlePromise (http://localhost:50847/__cypress/runner/cypress_runner.js:24484:19)
```

### Desired behavior

- `this` should appear after alias is used
- `expect(this.foo).eq("three");` should pass

### Test code to reproduce

```javascript
  describe("Test", () => {
    beforeEach(() => {
      cy.wrap("three").as("foo");
    });

    it("expect", () => {
      expect(this.foo).eq("three");
    });
  });

```

### Cypress Version

8.7

### Other

Not sure if it's related, the component testing has been installed via this guide (for CRA)

https://docs.cypress.io/guides/component-testing/framework-configuration#React-Create-React-App

**Comment by jennifer-shehane** [comment]
You need to use a `function` defnition instead of an arrow function in order to access `this` properly. 

```js
describe("Test", () => {
  beforeEach(() => {
    cy.wrap("three").as("foo");
  });

  it("expect", function () {
    expect(this.foo).eq("three");
  });
});
```
