### ISSUE TITLE
Confusing error when no `tsconfig.json` exists in a TypeScript project

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#18938]
### Current behavior

If you create a Cypress project with `.ts` specs and do not have a `tsconfig.json`, this error happens:

```
Oops...we found an error preparing this test file:

  cypress/integration/spec.ts

The error was:

Error: Webpack Compilation Error
[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json

```

which is confusing. In fact, creating an empty `tsconfig.json` avoids this error, so the error itself does not point at the solution either.

### Desired behavior

Either provide an empty default `tsconfig.json` or present a better error.

### Test code to reproduce

--

### Cypress Version

9.0.0

**Comment by nemanjam** [comment]
What is default location for `tsconfig.json` file? I moved cypress to `tests-e2e` location and use `--project` option but it can't find `tsconfig.json` in Docker.

```yaml
command: npx wait-on http://npb-app-test:3001 && npx cypress run --project ./tests-e2e
```


![image](https://user-images.githubusercontent.com/9990165/171634497-514b602d-ebf2-4f41-9aad-ff585d3cc513.png)

Error log from Cypress container:

```
                                                                                                    
  Running:  settings.test.ts                                                                (5 of 5)

Oops...we found an error preparing this test file:

  > cypress/support/index.js

The error was:

Error: Webpack Compilation Error
[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.
 @ ./cypress/support/index.js 5:17-48
 
    at handle (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at finalCallback (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
```

**Comment by ShashankAC** [comment]
> I solved it by adding a valid tsconfig.json at the root of the project

Please elaborate, what is the valid content ?

**Comment by guilhermesimoes** [comment]
> I solved it by adding a valid tsconfig.json at the root of the project

Cypress should not be using the tsconfig.json at the root of the project. [Cypress's documentation](https://docs.cypress.io/guides/tooling/typescript-support) states:

> We recommend creating a [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) **inside** your [cypress folder](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-Structure)

**Comment by tim-rohrer** [comment]
> > I solved it by adding a valid tsconfig.json at the root of the project
> 
> Cypress should not be using the tsconfig.json at the root of the project. [Cypress's documentation](https://docs.cypress.io/guides/tooling/typescript-support) states:
> 
> > We recommend creating a [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) **inside** your [cypress folder](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-Structure)

I found a valid `tsconfig.json` was not needed at the project root. 

I started the setup process by running `cypress open`. Once the directory structure was created, I returned to my IDE and created `tsconfig.json` in the cypress directory:

```json
{
  "compilerOptions": {
    "noEmit": true,
    // be explicit about types included
    // to avoid clashing with Jest types
    "types": ["cypress"]
  },
  "include": ["**/*.ts"]
}
```

I then returned to Cypress and continued the set up by creating an initial spec file.  

Everything seems to work without the error.

**Comment by AtofStryker** [comment]
it looks like `ts-loader` needs a `tsconfig.json` to work. Right now, Cypress doesn't have the ability to distinguish whether a project is configured with TypeScript or JavaScript. Cypress just detects whether or not TypeScript is installed in the project and assumes TypeScript configuration moving forward, which is related to #27603. I think we can improve this error by throwing if there is no `tsconfig.json` in the project with something like the below screenshot, but I don't believe it closes the issue 

<img width="1491" alt="Image" src="https://github.com/user-attachments/assets/b7f1800d-94c6-4383-af39-e56fd28c97cd" />

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress/issues/32442
