### ISSUE TITLE
Test runner does not print error to stdout

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1900]
### Current behavior:

The test run https://circleci.com/gh/cypress-io/cypress-example-kitchensink/535 failed 1 test but did not print the error to the standard output

```
Running: examples/navigation.spec.js...                                                (11 of 19) 
(node:695) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added. Use emitter.setMaxListeners() to increase limit


  Navigation
    ✓ cy.go() - go back or forward in the browser's history (1257ms)
    ✓ cy.reload() - reload the page (829ms)


  2 passing (7s)


  (Results)

  ┌───────────────────────────────────────────┐
  │ Tests:        3                           │
  │ Passing:      2                           │
  │ Failing:      1                           │
  │ Pending:      0                           │
  │ Skipped:      0                           │
  │ Screenshots:  1                           │
  │ Video:        true                        │
  │ Duration:     7 seconds                   │
  │ Spec Ran:     examples/navigation.spec.js │
  └───────────────────────────────────────────┘


  (Screenshots)

  - /root/app/cypress/screenshots/Navigation -- cyvisit - visit a remote url.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /root/app/cypress/videos/examples/navigation.spec.js.mp4 (2 seconds)


  (Uploading Results)

  - Done Uploading (1/2) /root/app/cypress/videos/examples/navigation.spec.js.mp4
  - Done Uploading (2/2) /root/app/cypress/screenshots/Navigation -- cyvisit - visit a remote url.png
```

Going to the dashboard https://dashboard.cypress.io/#/projects/4b7344/runs/1606/failures shows the failure https://dashboard.cypress.io/#/projects/4b7344/runs/1606/failures/2cf5d684-15db-43dc-8f36-af7ee7e01a53

```
Navigationcy.visit() - visit a remote url
 Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at jQuery.fn.init.slice (<anonymous>)
at jQuery.fn.init.toArray (http://localhost:8080/__cypress/runner/cypress_runner.js:16683:16)
at Object.unwrap (http://localhost:8080/__cypress/runner/cypress_runner.js:68900:16)
at Object.getElements (http://localhost:8080/__cypress/runner/cypress_runner.js:68709:17)
at obj.consoleProps (http://localhost:8080/__cypress/runner/cypress_runner.js:59017:31)
at attributes.consoleProps (http://localhost:8080/__cypress/runner/cypress_runner.js:65786:43)
at http://localhost:8080/__cypress/runner/cypress_runner.js:65604:20
at Object.invoke (http://localhost:8080/__cypress/runner/cypress_runner.js:65610:21)
at Object.toJSON (http://localhost:8080/__cypress/runner/cypress_runner.js:65628:28)
```

### Desired behavior:

Need to show the error under all circumstances

**Comment by brian-mann** [comment]
This is happening because its dieing while attempting to serialize the error / state so that it *can* print it out. When the communication mechanism fails then it cannot know :P

**Comment by bahmutov** [comment]
The error was from a test that tried to serialize window object

test

```
cy.visit('http://localhost:8080/commands/navigation', {
      timeout: 50000, // increase total time for the visit to resolve
      onBeforeLoad (contentWindow) {
        // contentWindow is the remote page's window object
        expect(contentWindow).to.be.an('object')
      },
      onLoad (contentWindow) {
        // contentWindow is the remote page's window object
        expect(contentWindow).to.be.an('object')
      },
    })
```

relevant code

```
if (!ok) {
      var msg = util.getMessage(this, arguments)
        , actual = util.getActual(this, arguments);
      throw new AssertionError(msg, {
          actual: actual
        , expected: expected
        , showDiff: showDiff
      }, (config.includeStack) ? this.assert : flag(this, 'ssfi'));
    }
```

**Comment by jennifer-shehane** [comment]
This no longer happens in Cypress version 3.4.0. Notably though, the error says it originates from the application code, not from Cypress which is wrong. 

```
   1)  tests:
     expected '<window>' to be an object

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
  AssertionError: expected '<window>' to be an object
      at $Cypress.<anonymous> (https://example.cypress.io/__cypress/runner/cypress_runner.js:74460:73)
      at $Cypress.EventEmitter.emit (https://example.cypress.io/__cypress/runner/cypress_runner.js:15530:22)
      at $Cypress.parent.(anonymous function) [as emit] (https://example.cypress.io/__cypress/runner/cypress_runner.js:81284:27)
      at $Cypress.action (https://example.cypress.io/__cypress/runner/cypress_runner.js:78998:21)
```

Still going to close since the error does now print to stdout.
