### ISSUE TITLE
Error: Cannot find module 'har-validator'

### ISSUE THREAD

**Issue by web-dragon-smsp** [cypress-io/cypress#19104]
### Current behavior

`npm install cypress`

error /Users/user/Projects/project/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /Users/user/Projects/project/node_modules/cypress
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- /Users/user/Projects/project/node_modules/@cypress/request/lib/har.js
- /Users/user/Projects/project/node_modules/@cypress/request/request.js
- /Users/user/Projects/project/node_modules/@cypress/request/index.js
- /Users/user/Projects/project/node_modules/cypress/lib/tasks/download.js
- /Users/user/Projects/project/node_modules/cypress/lib/tasks/install.js
- /Users/user/Projects/project/node_modules/cypress/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/Projects/project/node_modules/@cypress/request/lib/har.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/Projects/project/node_modules/@cypress/request/request.js:23:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Projects/project/node_modules/@cypress/request/lib/har.js',
    '/Users/user/Projects/project/node_modules/@cypress/request/request.js',
    '/Users/user/Projects/project/node_modules/@cypress/request/index.js',
    '/Users/user/Projects/project/node_modules/cypress/lib/tasks/download.js',
    '/Users/user/Projects/project/node_modules/cypress/lib/tasks/install.js',
    '/Users/user/Projects/project/node_modules/cypress/index.js'
  ]

### Cypress Version

8.3.0

### Package Manager

npm

### Operating system

Mac

**Comment by manusanchev** [comment]
#19102 duplicated

**Comment by web-dragon-smsp** [comment]
Is there an unofficial version of har-validator?

**Comment by chrisbreiding** [comment]
The code for this is done in [cypress-io/cypress#19099](https://github.com/cypress-io/cypress/pull/19099), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
