### ISSUE TITLE
cypress lighthouse load test fails on Node 17.0.1

### ISSUE THREAD

**Issue by nagkumar** [cypress-io/cypress#19126]
### Current behavior

When lighthouse run, the load test fails with this stacktrace
```
at <unknown> (> connect ECONNREFUSED ::1:52203)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:161008:79)
From previous event:
    at Context.task (http://localhost:4200/__cypress/runner/cypress_runner.js:160990:16)
From Your Spec Code:
    at Context.eval (webpack:///./node_modules/cypress-audit/src/performances/command-handler.js:35:1)
From Node.js Internals:
      at <unknown> (      Error: connect ECONNREFUSED ::1:52203)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:17)
```
![image](https://user-images.githubusercontent.com/332234/143675789-38df1c1d-b040-4df0-bbad-4d11ccf9b7dc.png)

### Test code to reproduce

Install the current node verstion 17.0.1

### Cypress Version

        "cypress": "^9.1.0",

### Other

the same code works fine on node 14.18.1

**Comment by emilyrohrbough** [comment]
@nagkumar Can you confirm this wasn't an issue with lighthouse and node 17? https://github.com/GoogleChrome/lighthouse/issues/13258
