### ISSUE TITLE
While installing mochawesome report, unable to run cypress and get the error as: Cannot find module 'cypress-mochawesome-reporter/plugin'

### ISSUE THREAD

**Issue by Srinikalai2018** [cypress-io/cypress#19165]
### Current behavior

After installing mochawesome report, added dev dependencies as shown here but getting the below error as shown in the image ::

  "devDependencies": {
    "cypress-mochawesome-reporter": "^2.3.0",
    "mocha": "^9.1.3",
    "mochawesome": "^6.3.1",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^6.0.1"
  }

![image](https://user-images.githubusercontent.com/49427833/144187633-70db34ff-f699-47b2-ab49-d6e25c7805e9.png)

### Cypress Version

8.5.0

### Package Manager

npm

### Operating system

Windows

**Comment by Srinikalai2018** [comment]
Error: Cannot find module 'cypress-mochawesome-reporter/plugin'
Require stack:
- C:\Users\Srinivas.Vijayakumar\CypressAutomation\QASandbox\cypress\plugins\index.js
- C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js
- C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (C:\Users\Srinivas.Vijayakumar\CypressAutomation\QASandbox\cypress\plugins\index.js:20:3)
    at C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:90:12
    at tryCatcher (C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at load (C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:87:7)
    at EventEmitter.<anonymous> (C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:198:5)
    at EventEmitter.emit (events.js:376:20)
    at process.<anonymous> (C:\Users\Srinivas.Vijayakumar\AppData\Local\Cypress\Cache\8.7.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at process.emit (events.js:376:20)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
