### ISSUE TITLE
Cannot read properties of null (reading 'href') when using Cypress v9

### ISSUE THREAD

**Issue by Michael-Xie** [cypress-io/cypress#19265]
### Current behavior

When running a set of Cypress tests, the tests start to fail when `cy.tick` and gives the error:
```
cypress_runner.js:193336 TypeError: Cannot read properties of null (reading 'href')
    at u (http://localhost:5000/static/js/2.da7254e5.chunk.js:2:694570)
    at Object.o [as computeStackTrace] (http://localhost:5000/static/js/2.da7254e5.chunk.js:2:697789)
    at o (http://localhost:5000/static/js/2.da7254e5.chunk.js:2:675766)
From previous event:
    at runCommand (http://localhost:5000/__cypress/runner/cypress_runner.js:170760:10)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:170901:16)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:170879:18)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:170930:18
From previous event:
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:170901:36)
From previous event:
    at http://localhost:5000/__cypress/runner/cypress_runner.js:185174:79
From previous event:
    at Object.run (http://localhost:5000/__cypress/runner/cypress_runner.js:185169:23)
    at Object.run (http://localhost:5000/__cypress/runner/cypress_runner.js:170956:17)
    at $Cy.cy.<computed> [as get] (http://localhost:5000/__cypress/runner/cypress_runner.js:172160:19)
    at Context.runnable.fn (http://localhost:5000/__cypress/runner/cypress_runner.js:172383:23)
    at callFn (http://localhost:5000/__cypress/runner/cypress_runner.js:125018:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:125005:7)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:178975:30
From previous event:
    at Object.onRunnableRun (http://localhost:5000/__cypress/runner/cypress_runner.js:178960:19)
    at $Cypress.action (http://localhost:5000/__cypress/runner/cypress_runner.js:168435:28)
    at Test.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:176656:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:5000/__cypress/runner/cypress_runner.js:125677:10)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:125803:12
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:125586:14)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:125596:7
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:125498:14)
    at Hook.<anonymous> (http://localhost:5000/__cypress/runner/cypress_runner.js:125559:7)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:178873:24)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:178902:13
From previous event:
    at onNext (http://localhost:5000/__cypress/runner/cypress_runner.js:178899:59)
    at done (http://localhost:5000/__cypress/runner/cypress_runner.js:124958:5)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:125023:11
From previous event:
    at callFn (http://localhost:5000/__cypress/runner/cypress_runner.js:125021:14)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:125005:7)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:178975:30
From previous event:
    at Object.onRunnableRun (http://localhost:5000/__cypress/runner/cypress_runner.js:178960:19)
    at $Cypress.action (http://localhost:5000/__cypress/runner/cypress_runner.js:168435:28)
    at Hook.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:176656:13)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:125520:10)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:125564:5
    at timeslice (http://localhost:5000/__cypress/runner/cypress_runner.js:119490:27)
logError @ cypress_runner.js:193336
(anonymous) @ cypress_runner.js:191777
emit @ cypress_runner.js:22575
(anonymous) @ cypress_runner.js:188422
emit @ cypress_runner.js:22575
emit @ cypress_runner.js:188483
onPrint @ cypress_runner.js:187312
_onPrintClick @ cypress_runner.js:187317
(anonymous) @ cypress_runner.js:188654
executeAction @ cypress_runner.js:67511
n @ cypress_runner.js:67511
ca @ cypress_runner.js:77596
ja @ cypress_runner.js:77597
ka @ cypress_runner.js:77597
wa @ cypress_runner.js:77599
Aa @ cypress_runner.js:77600
ya @ cypress_runner.js:77600
Da @ cypress_runner.js:77603
Ad @ cypress_runner.js:77666
Gi @ cypress_runner.js:77832
Kb @ cypress_runner.js:77621
Dd @ cypress_runner.js:77668
(anonymous) @ cypress_runner.js:77833
../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:82421
Ii @ cypress_runner.js:77833
Cd @ cypress_runner.js:77667
```

### Desired behavior

The tests should passed as it should before upgrade to v9.

All tests were passing up until v8.7.0.

### Test code to reproduce

Here is the watered down version of the tests used. The tests mainly checks and see if auto-scroll is behaving as it should for a carousel.
```
	context('Auto-scroll', () => {
		beforeEach(() => {
			cy.clock(new Date().getTime());
			cy.viewport(1920, 1080);
			cy.intercept('GET', '/api/user?*', { fixture: 'userResponse.json' }).as(
				'userRequest',
			);
			cy.intercept('POST', '/api/pride_mobility', (req) => {
				const reply = { fixture: 'response.json' }
				req.reply(reply);
			}).as('dataRequest');
			cy.visit('/');
			cy.get('button[data-cy=login]').click();
			cy.get('input[id=username]').type(email);
			cy.get('input[id=password]').type(password);
			cy.get('button[type=submit]').click();
		});
		afterEach(() => {
			cy.get('span[data-cy=logout-button]').click();
		});

		it('should auto-scroll to next slide when not hovering on carousel', () => {
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('h2')
				.first()
				.should('have.text', 'slide-1-title');
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('.carousel-status')
				.should('have.text', '1 of 4');
			cy.tick(25000);
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('h2')
				.first()
				.should('have.text', 'slide-2-title');
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('.carousel-status')
				.should('have.text', '2 of 4');
		});
		it('should not auto-scroll to next slide when hovering on carousel', () => {
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('h2')
				.first()
				.should('have.text', 'slide-1-title');
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('.carousel-status')
				.should('have.text', '1 of 4');
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('h2')
				.first()
				.type('{selectall}');
			cy.tick(25000);
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('h2')
				.first()
				.should('have.text', 'slide-1-title');
			cy.get('.App')
				.find('.carousel__slide--visible')
				.find('.carousel-status')
				.should('have.text', '1 of 4');
		});
	});
```

### Cypress Version

9.0.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I tried to reproduce the problem with the code below, but failed:

```js
it('t', () => {
  cy.clock(new Date().getTime())
  cy.visit('/fixtures/a.html')
  cy.get('#title').should('have.text', 'Test')
  cy.tick(25000)
  cy.get('#title').should('have.text', 'Test')
})
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Document</title>
</head>
<body>
  <a id="title">Test</a>
</body>
</html>
```

Can you provide a working code example?

**Comment by sainthkh** [comment]
Closing because of the inactivity.
