### ISSUE TITLE
Cypress execution fails during test phase on AWS Amplify CI

### ISSUE THREAD

**Issue by ernestostifano** [cypress-io/cypress#19421]
### Current behavior

Cypress fails to correctly execute.

### Desired behavior

Cypress to correctly execute.

### Test code to reproduce

```yml
version: 1
env:
  variables:
backend:
  phases:
    preBuild:
      commands:
    build:
      commands:
        - amplifyPush --simple
    postBuild:
      commands:
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    discard-paths: yes
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
        - rm -rf node_modules
        - yarn install --frozen-lockfile
        - yarn add pm2@5.1.2 --dev
        - yarn add wait-on@6.0.0 --dev
        - yarn add mocha@9.1.3 mochawesome@7.0.1 mochawesome-merge@4.2.1 mochawesome-report-generator@6.0.1 --dev
        - yarn run cypress:clean
        - yarn run pm2 start 'yarn run start'
        - yarn run wait-on https://localhost:3000
    test:
      commands:
        - yarn run cypress run --reporter mochawesome --reporter-options 'reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss'
    postTest:
      commands:
        - yarn run mochawesome-merge cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
        - yarn run pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

### Cypress Version

9.1.0

### Other

```
                                 # Starting phase: test
                                 # Executing command: yarn run cypress run --reporter mochawesome --reporter-options 'reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss'
2021-12-19T13:46:56.979Z [INFO]: yarn run v1.22.0
2021-12-19T13:46:57.020Z [INFO]: $ /codebuild/output/src671159186/src/codistica-website/node_modules/.bin/cypress run --reporter mochawesome --reporter-options reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss
2021-12-19T13:46:57.327Z [INFO]: It looks like this is your first time using Cypress: 9.1.0
2021-12-19T13:46:57.327Z [INFO]: 
2021-12-19T13:46:57.330Z [INFO]: [STARTED] Task without title.
2021-12-19T13:46:59.928Z [INFO]: [SUCCESS] Task without title.
2021-12-19T13:46:59.929Z [INFO]: Opening Cypress...
2021-12-19T13:47:01.340Z [WARNING]: [3387:1219/134701.340292:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2021-12-19T13:47:01.342Z [WARNING]: [3387:1219/134701.342161:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2021-12-19T13:47:01.342Z [WARNING]: [3387:1219/134701.342301:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2021-12-19T13:47:01.354Z [WARNING]: [3540:1219/134701.354545:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
2021-12-19T13:47:02.268Z [INFO]: The plugins file is missing or invalid.
                                 Your `pluginsFile` is set to `/codebuild/output/src671159186/src/codistica-website/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.
                                 Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.
                                 Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
2021-12-19T13:47:02.269Z [INFO]: /codebuild/output/src671159186/src/codistica-website/node_modules/@cypress/react/plugins/utils/get-transpile-folders.js:5
                                 const rawFolders = config.addTranspiledFolders ?? []
                                 ^
                                 SyntaxError: Unexpected token '?'
                                 at wrapSafe (internal/modules/cjs/loader.js:915:16)
                                 at Module._compile (internal/modules/cjs/loader.js:963:27)
                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
                                 at Module.load (internal/modules/cjs/loader.js:863:32)
                                 at Function.Module._load (internal/modules/cjs/loader.js:708:14)
                                 at Module.require (internal/modules/cjs/loader.js:887:19)
                                 at require (internal/modules/cjs/helpers.js:74:18)
                                 at Object.<anonymous> (/codebuild/output/src671159186/src/codistica-website/node_modules/@cypress/react/plugins/react-scripts/findReactScriptsWebpackConfig.js:6:33)
                                 at Module._compile (internal/modules/cjs/loader.js:999:30)
                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
                                 at Module.load (internal/modules/cjs/loader.js:863:32)
                                 at Function.Module._load (internal/modules/cjs/loader.js:708:14)
                                 at Module.require (internal/modules/cjs/loader.js:887:19)
                                 at require (internal/modules/cjs/helpers.js:74:18)
                                 at Object.<anonymous> (/codebuild/output/src671159186/src/codistica-website/node_modules/@cypress/react/plugins/react-scripts/index.js:2:39)
                                 at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-12-19T13:47:02.339Z [WARNING]: error Command failed with exit code 1.
2021-12-19T13:47:02.340Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-12-19T13:47:02.345Z [INFO]: # Completed phase: test
                                 # Starting phase: postTest
2021-12-19T13:47:02.345Z [INFO]: # Executing command: yarn run mochawesome-merge cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
2021-12-19T13:47:02.346Z [WARNING]: /codebuild/output/src671159186/src/codistica-website/tests.sh: line 40: cypress/report/mochawesome.json: No such file or directory
2021-12-19T13:47:02.347Z [ERROR]: !!! Test execution failed, one or more tests are not passing
2021-12-19T13:47:02.349Z [INFO]: # Starting test artifact upload process...
2021-12-19T13:47:02.358Z [INFO]: # Uploading build artifact 'testConfig.json'...
2021-12-19T13:47:02.362Z [INFO]: # Build artifact is: 0MB
2021-12-19T13:47:02.363Z [INFO]: # Uploading build artifact 'testArtifacts.zip'...
2021-12-19T13:47:02.431Z [INFO]: # Test artifact upload completed
2021-12-19T13:47:02.432Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-19T13:47:02.432Z [INFO]: # Starting environment caching...
2021-12-19T13:47:02.432Z [INFO]: # Uploading environment cache artifact...
2021-12-19T13:47:02.511Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by Narretz** [comment]
This looks like the node version where your job runs doesn't support the nullish coalescing operator `??` Maybe you can set the version in node amplify somewhere? Anyway, doesn't look like a Cypress issue.

**Comment by Narretz** [comment]
Nullish coalescing is pretty new: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

I don't think the warnings are anything to worry about as long as your tests work.

**Comment by ernestostifano** [comment]
@Narretz yes, I immediately searched on MDN. Then everything is working fine, so I will close this issue. Thanks again.
