### ISSUE TITLE
Can't resolve 'chai' 

### ISSUE THREAD

**Issue by eloisetaylor5693** [cypress-io/cypress#19499]
### Current behavior

I started a vanilla cypress project, and found when I tried to use cgai assertions in my new tests, it failed with the following error:

```
Error: Webpack Compilation Error
./cypress/integration/mutations/createSomethingMutation/happy-path.spec.js
Module not found: Error: Can't resolve 'chai' in '/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/integration/mutations/createSomethingMutation'
resolve 'chai' in '/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/integration/mutations/createSomethingMutation'
  Parsed request is a module
  using description file: /Users/Eloise.Taylor/code/zego/e2e-tests/package.json (relative path: ./cypress/integration/mutations/createSomethingMutation)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/integration/mutations/createSomethingMutation/node_modules]
[/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/integration/mutations/node_modules]
[/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/integration/node_modules]
[/Users/Eloise.Taylor/code/zego/e2e-tests/cypress/node_modules]
[/Users/Eloise.Taylor/code/zego/node_modules]
[/Users/Eloise.Taylor/code/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/Eloise.Taylor/node_modules/package.json]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai.js]
[/Users/Eloise.Taylor/node_modules/chai/package.json]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai.json]
[/Users/Eloise.Taylor/node_modules/chai]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai.jsx]
[/Users/Eloise.Taylor/node_modules/chai.js]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai.mjs]
[/Users/Eloise.Taylor/node_modules/chai.json]
[/Users/Eloise.Taylor/code/zego/e2e-tests/node_modules/chai.coffee]
[/Users/Eloise.Taylor/node_modules/chai.jsx]
[/Users/Eloise.Taylor/node_modules/chai.mjs]
[/Users/Eloise.Taylor/node_modules/chai.coffee]
 @ ./cypress/integration/mutations/createSomethingMutation/happy-path.spec.js 7:12-27
 
    at handle (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at finalCallback (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:61:14
    at /Users/Eloise.Taylor/Library/Caches/Cypress/9.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:180:23)
```

1. Intitialise a npm project with this: `npm init`
2. `yarn add cypress`
3. run cypress for first time to generate example tests and boiler-plate code
4.  run cypress tests and all pass
5. added my own tests
6. BOOM

### Desired behavior

I should just be able to write expect statements with chai assertions

### Test code to reproduce

```
expect(response.body.data).to.not.be.null;
expect(response.body.data).not.to.be.null;
expect(response.body.data).to.equal(null);
expect(response.body.data).to.not.equal(null);
```

### Cypress Version

9.2.0

### Other

Running on a mac
Using yarn

**Comment by eloisetaylor5693** [comment]
My IDE (VSCode) had sneakily added `import { expect } from "chai";` as I was writing the tests, hence the errors noted above.

Continued to post in case someone else gets this same issue (hopefully the google gods will present them this closed issue)
