### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by robertovg** [cypress-io/cypress#19569]
### Current behavior

We have some basic integration tests working locally and we just started to add in Github Actions as part of our CI, but we get a `SIGSEGV` error for no reason.

The funny thing is those works fine both locally with `cypress open` (opening the UI) and also with `cypress run --headless` but executing the same ones `headlessly` we get the SIGSEGV error (in Github CI we run the action `runs-on: ubuntu-latest`

<img width="1757" alt="Screen Shot 2022-01-05 at 6 09 24 PM" src="https://user-images.githubusercontent.com/570679/148260666-db6ea5ac-3eb4-4614-b61c-b8b9d8ce6892.png">

Here is the content of the existing e2e tests: The ones giving problems are:

`Monthly premium gets reloaded when ratting changes (to preferred)` && `Monthly premium rates loads on page load (standard ratting)`

```ts
import { formatCurrency } from 'eqai-ui-libs';

describe('Comparison tool tests', () => {
  const initialFormAgeValue = 55;
  const initialFormGenderValue = 'male';
  const initialFormTobaccoValue = 'true';
  const initialFormRatingValue = 'STD';

  const standardTableValues = [
    { faceAmount: '5,000', aig: '30.14', lumico: '53.16' },
    { faceAmount: '10,000', aig: '58.28', lumico: '106.32' },
    { faceAmount: '15,000', aig: '86.42', lumico: '159.48' },
    { faceAmount: '20,000', aig: '128.25', lumico: '212.63' },
    { faceAmount: '25,000', aig: '159.82', lumico: '265.79' },
    { faceAmount: '30,000', aig: '', lumico: '318.95' },
  ];

  const preferredTableValues = [
    { faceAmount: '5,000', aig: '30.14', lumico: '29.04' },
    { faceAmount: '10,000', aig: '58.28', lumico: '58.08' },
    { faceAmount: '15,000', aig: '86.42', lumico: '87.11' },
    { faceAmount: '20,000', aig: '128.25', lumico: '116.15' },
    { faceAmount: '25,000', aig: '159.82', lumico: '145.19' },
    { faceAmount: '30,000', aig: '', lumico: '174.22' },
  ];

  beforeEach(() => {
    const APP_URL = Cypress.env('APP_URL');
    const APP_SERVER_ENDPOINT = Cypress.env('APP_SERVER_ENDPOINT');

    // Prepare params
    const initialParams = `age=${initialFormAgeValue}&gender=${initialFormGenderValue}&tobacco=${initialFormTobaccoValue}&risk_class=${initialFormRatingValue}&eq_lead_uuid=7906b4f1-74ff-5ed8-a004-fbe6a3fff306&advisor_id=me.jan%40example.com`;
    const updatedParams = `age=${initialFormAgeValue}&gender=${initialFormGenderValue}&tobacco=${initialFormTobaccoValue}&risk_class=PFD&eq_lead_uuid=7906b4f1-74ff-5ed8-a004-fbe6a3fff306&advisor_id=me.jan%40example.com`;

    // Prepare URLs to be intercepted/visited
    const initialRateLookupURL = `${APP_SERVER_ENDPOINT}/public/rates/lookup/?${initialParams}`;
    const updatedRateLookupURL = `${APP_SERVER_ENDPOINT}/public/rates/lookup/?${updatedParams}`;

    const comparisonToolUsageURL = `${APP_SERVER_ENDPOINT}public/comparison_tool_usage/`;

    // Set the interceptors
    cy.intercept(initialRateLookupURL, {
      fixture: 'rateLookup_Standard',
    });

    cy.intercept(updatedRateLookupURL, {
      fixture: 'rateLookup_Preferred',
    });

    cy.intercept('POST', comparisonToolUsageURL, { fixture: 'comparisonToolUsage' });

    // Perform the visit with the initial state
    cy.visit(`${APP_URL}public/comparison?${initialParams}&rating=${initialFormRatingValue}`);
  });

  it('Page loads', () => {
    cy.findByText('Client Details').should('exist');
    cy.findByText('Rating').should('exist');
    cy.findByText('Monthly Premium Estimate').should('exist');
  });

  it('Form loads with values from URL params', () => {
    cy.findByTestId('form-input-age').should('have.value', initialFormAgeValue);
    cy.findByTestId('form-input-gender').should('have.value', initialFormGenderValue);
    cy.findByTestId('form-input-tobacco').should('have.value', initialFormTobaccoValue);
    cy.findByTestId('form-input-rating').should('have.value', initialFormRatingValue);
  });

  it('Monthly premium rates loads on page load (standard ratting)', () => {
    cy.findByTestId('form-monthly-premium-selection').find('tbody tr').should('have.length', 6);

    // Check if the calcs in the table are correct for standard rating
    standardTableValues.forEach((e, i) => {
      cy.findByTestId('form-monthly-premium-selection')
        .find('tbody tr')
        // First row
        .eq(i)
        // Face Amount
        .find('td')
        .eq(1)
        .should('contain.text', e.faceAmount)

        // Aig Premium
        .next()
        .should('contain.text', formatCurrency(e.aig))

        // Aig Premium
        .next()
        .should('contain.text', formatCurrency(e.lumico));
    });
  });

  it('Monthly premium gets reloaded when ratting changes (to preferred)', () => {
    // We click in the select input
    cy.get('#rating').click();
    // We select the preferred
    cy.findByRole('listbox').find('[data-value="PFD"]').click();

    // Check if the calcs in the table are correct for preferred rating
    preferredTableValues.forEach((e, i) => {
      cy.findByTestId('form-monthly-premium-selection')
        .find('tbody tr')
        // First row
        .eq(i)
        // Face Amount
        .find('td')
        .eq(1)
        .should('contain.text', e.faceAmount)

        // Aig Premium
        .next()
        .should('contain.text', formatCurrency(e.aig))

        // Aig Premium
        .next()
        .should('contain.text', formatCurrency(e.lumico));
    });
  });

  it('When no monthly rate selected, no recommendation is shown', () => {
    cy.findByTestId('form-monthly-premium-selection')
      .find('input[type="radio"]:checked')
      .should('not.exist');
    cy.findByTestId('recommendation-output')
      .contains('Please select a Face Amount above')
      .should('exist');
  });

  it('When monthly rate selected, we show recommendation', () => {
    // intercept recommendation to return lumico
    const APP_SERVER_ENDPOINT = Cypress.env('APP_SERVER_ENDPOINT');
    const lumicoSifeRecommendationURL = `${APP_SERVER_ENDPOINT}public/recommendations/`;
    cy.intercept('POST', lumicoSifeRecommendationURL, { fixture: 'recommendation_lumicoSife' });

    // Clicking the first row 5000
    cy.findByTestId('form-monthly-premium-selection')
      .find('tbody tr')
      // First row
      .eq(0)
      .find(`input[type="radio"][value="5000"]`)
      .click();

    // Check if the checkbox was clicked
    cy.findByTestId('form-monthly-premium-selection')
      .find('input[type="radio"]:checked')
      .should('exist');

    // The selection text doesn't exist anymore
    cy.findByTestId('recommendation-output')
      .contains('Please select a Face Amount above')
      .should('not.exist');

    // The selection text doesn't exist anymore
    cy.findByTestId('recommendation-output').contains('Lumico').should('exist');
  });
});

```

### Desired behavior

We get the same output for the tests regardless of where they are being executed and we don't have to deal with SIGSEGV errors.

### Test code to reproduce

`yarn cypress run --headless`

The test failing are just checking in the page already rendered, so that's why it is so unexpected. If the first test works all should run successfully in CI.

### Cypress Version

9.2.0

**Comment by dskgry** [comment]
I'm having the same issue locally when using `cypress run`. 

Here is what I found out so far:
- when I'm NOT using cy.screenshot() the tests seem run normally with electron. 
- issue does not happen when running with chrome, e.g. `cypress run --browser chrome`. 
- issue also does not happen with `cypress open`.
- issue mostly happens when running multiple tests, e.g. `cypress run --browser electron --spec 'cypress/integration/**/*'`
- error message is always `Process finished with exit code -1073741819 (0xC0000005)` (on windows)
- rolled back to cypress 8.5.0 and everything works. Issue appears when switching to cypress 8.6.0 or later

Thanks

**Comment by robertovg** [comment]
Just downgraded from v9.2.0 to v8.50 and the SIGSEGV is gone. This is a workaround but I would expect this error not to happen in this way

**Comment by testingJava2** [comment]
Hello team, @sakulstra,

I've also seen this problem with Cypress 8.3.0; not sure then if the workaround (using version 8.5.0) I've seen in other issues related to this problem are going to fix this for me then.

Error logs below:

````
<--- Last few GCs --->
[226:0x318b00000000]  5280146 ms: Mark-sweep 1707.4 (1988.7) -> 1701.4 (1990.2) MB, 344.7 / 0.1 ms  (average mu = 0.843, current mu = 0.807) task scavenge might not succeed
[226:0x318b00000000]  5282173 ms: Mark-sweep 1708.9 (1990.2) -> 1702.9 (1992.0) MB, 390.8 / 0.1 ms  (average mu = 0.825, current mu = 0.807) task scavenge might not succeed
<--- JS stacktrace --->
Error: The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
Please search Cypress documentation for possible solutions:
https://on.cypress.io
Check if there is a GitHub issue describing this crash:
https://github.com/cypress-io/cypress/issues
Consider opening a new issue.
----------
Platform: linux (Debian - 10.9)
Cypress Version: 8.3.0
    at /builds/web/cypressapp/node_modules/cypress/lib/errors.js:257:17
    at tryCatcher (/builds/web/cypressapp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/builds/web/cypressapp/node_modules/bluebird/js/release/promise.js:604:18) {
  known: true
}
````

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi Team, 

Experiencing the same error in below mentioned version of cypress 9.3.0 & 8.3.0. 
Any update on the solution?
