### ISSUE TITLE
Gitlab CI with Cypress not working

### ISSUE THREAD

**Issue by muratdu25** [cypress-io/cypress#19568]
### Current behavior

```
DONE  Compiled successfully in 105675ms2:49:24 PM
<s> [webpack.Progress] 100% 
  App running at:
  - Local:   http://localhost:8080/ 
  It seems you are running Vue CLI inside a container.
  Access the dev server via http://localhost:<your container's external mapped port>/
  Note that the development build is not optimized.
  To create a production build, run npm run build.
> qualiflow@1.0.8 runHeadless /builds/BGDataPLM/octopus/qualiflow
> cypress run --record --key dad69369-a84c-4ba2-9b8d-ebcd92448c5f
[STARTED] Task without title.
[SUCCESS] Task without title.
[547:0105/144949.226053:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[547:0105/144949.226124:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[547:0105/144949.232123:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[704:0105/144949.275768:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.2.0                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v12.14.1 (/usr/local/bin/node)                                                 │
  │ Specs:          4 found (create/quality_action.js, create/quality_item.js, edit/edit_qi.js, ho │
  │                 me/loading_content_page.js)                                                    │
  │ Params:         Tag: false, Group: false, Parallel: false                                      │
  │ Run URL:        https://dashboard.cypress.io/projects/ts9xtv/runs/3                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  create/quality_action.js                                                        (1 of 4)
[547:0105/144957.672777:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
  Création d'une action
    1) "before all" hook for "Recherche QI"
  0 passing (20s)
  1 failing
  1) Création d'une action
       "before all" hook for "Recherche QI":
     Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > Network Error
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Création d'une action`
      at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:99:14)
      at XMLHttpRequest.eval (eval at makeContentWindowListener (http://localhost:8080/__cypress/runner/cypress_runner.js:175603:10), <anonymous>:4:29)
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

### Desired behavior

With the command : start-server-and-test serve http-get://localhost:8080 runHeadless, it will start my server and pass the test

### Test code to reproduce

Run server than start test

### Cypress Version

9.2.0

**Comment by jennifer-shehane** [comment]
There's an error in your application code that is not being handled. Do you have a video recorded so that you can see the error? Or you can ignore the error following the instructions given in Cypress' error message.

>The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > Network Error
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application

**Comment by russoale** [comment]
According to Google Chrome headless needs a temporary `--disable-gpu` (see here).
And it seems this is also required for Linux (see here)
