### ISSUE TITLE
Failed to connect to Chrome, retrying in 1 second <attempts till 62/62> then fails

### ISSUE THREAD

**Issue by Rashi309** [cypress-io/cypress#19669]
### Current behavior

While trying to run the executor, "Still waiting to connect to Chrome, retrying in 1 second (attempt 62/62)" was shown until it finally failed to connect
<img width="764" alt="Screenshot 2022-01-12 at 1 31 12 PM" src="https://user-images.githubusercontent.com/93371780/149087602-8235e556-5bec-4c66-ab75-b73e3d7dc57b.png">
.

### Desired behavior

Cypress should open the chrome window to execute the test

### Test code to reproduce

Not sure if it's because of any code, as earlier it was working fine with the same settings and code.

### Cypress Version

9.2.1

### Other

Cypress package version: 9.2.1
Cypress binary version: 9.2.1
Electron version: 15.2.0
Bundled Node version: 16.5.0

Chrome Version 97.0.4692.71
MacOS Big Sur : v11.6

**Comment by Rashi309** [comment]
**Detailed Report for reference**

**Title:** Error launching browser

**Message:** Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was <span class="ansi-yellow-fg">57212</span>.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:57212
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)


**Stack trace:**
```
Error: Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was [33m57212[39m.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:57212
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)

    at get (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1043:15)
    at Object.throwErr [as throw] (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1061:9)
    at /Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:113:21
    at tryCatcher (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rashigarg/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

```

**Comment by andrescuco** [comment]
I'm also having this issue, tried with both cypress latest release and version `^6.7.1`. I'm on a Macbook Air M1 with MacOS Big Sur Version 11.6
