### ISSUE TITLE
tests with just a name and the test config object but without a callback throws an error

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#19701]
### Current behavior

a test is marked pending if it has just a title and no callback function
```js
// will be pending
it('works')
```

But if you have a test config object there it causes a crash
```js
it('works', {viewportWidth: 100})
```

```
TypeError: fn.apply is not a function
  at Context.runnable.fn (http://localhost:53035/__cypress/runner/cypress_runner.js:172338:19)
  at callFn (http://localhost:53035/__cypress/runner/cypress_runner.js:125099:21)
  at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:53035/__cypress/runner/cypress_runner.js:125086:7)
```

### Desired behavior

No crash, mark the test pending

### Test code to reproduce

https://github.com/cypress-io/cypress-test-tiny/tree/pending-with-config

### Cypress Version

9.2.1

**Comment by mjhenkes** [comment]
@bahmutov, I've been able to reproduce this, Thanks for providing the test repo!
