### ISSUE TITLE
Uncaught TypeError: (P || (intermediate value)(intermediate value)) is not a constructor

### ISSUE THREAD

**Issue by slawiko** [cypress-io/cypress#1979]
I migrated our ng5 application on ng6. After that I started see an issue with e2e tests. I understand that it doesn't look like cypress issue. But I spent a lot of time on it, and I really don't know who is guilty. I do not hope that we'll fix it, but anyway let's just discuss, maybe it can be helpful.

### Current behavior:

Some tests fail with log:

```bash
build	18-Jun-2018 16:00:43	────────────────────────────────────────────────────────────────────────────────
build	18-Jun-2018 16:00:43	                                                                                
build	18-Jun-2018 16:00:43	  Running: decision-tree.spec.js...                                    (7 of 7) 
build	18-Jun-2018 16:00:45	
build	18-Jun-2018 16:00:45	
build	18-Jun-2018 16:00:45	 DecisionTree -> adding node title to summary, adding via context menu 
build	18-Jun-2018 16:00:58	    1) should add last node title to summary
build	18-Jun-2018 16:01:09	    ✓ should create new node by context menu (8214ms)
build	18-Jun-2018 16:01:10	    - should create new option and set focus to input
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  1 passing (25s)
build	18-Jun-2018 16:01:10	  1 pending
build	18-Jun-2018 16:01:10	  1 failing
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  1) DecisionTree -> adding node title to summary, adding via context menu 
build	18-Jun-2018 16:01:10	       should add last node title to summary:
build	18-Jun-2018 16:01:10	     Uncaught TypeError: (n || (intermediate value)(intermediate value)) is not a constructor
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	This error originated from your application code, not from Cypress.
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	https://on.cypress.io/uncaught-exception-from-application
build	18-Jun-2018 16:01:10	      at Object.l (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:1921345)
build	18-Jun-2018 16:01:10	      at e.t.sendLog (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:2066089)
build	18-Jun-2018 16:01:10	      at e.t.error (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:2065525)
build	18-Jun-2018 16:01:10	      at t.handleError (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:3083011)
build	18-Jun-2018 16:01:10	      at Object.next (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:551621)
build	18-Jun-2018 16:01:10	      at e.object.i [as _next] (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:543263)
build	18-Jun-2018 16:01:10	      at e.FFOo.e.__tryOrUnsub (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:723112)
build	18-Jun-2018 16:01:10	      at e.FFOo.e.next (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:722257)
build	18-Jun-2018 16:01:10	      at e.FFOo.e._next (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:721309)
build	18-Jun-2018 16:01:10	      at e.FFOo.e.next (https://.../decision-tree/main.2c9b079741ed5b3b91aa.js:1:720980)
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	[mochawesome] Report JSON saved to /cypress/reports/html/index.json
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	[mochawesome] Report HTML saved to /cypress/reports/html/index.html
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  (Results)
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  ┌─────────────────────────────────────┐
build	18-Jun-2018 16:01:10	  │ Tests:        3                     │
build	18-Jun-2018 16:01:10	  │ Passing:      1                     │
build	18-Jun-2018 16:01:10	  │ Failing:      1                     │
build	18-Jun-2018 16:01:10	  │ Pending:      1                     │
build	18-Jun-2018 16:01:10	  │ Skipped:      0                     │
build	18-Jun-2018 16:01:10	  │ Screenshots:  1                     │
build	18-Jun-2018 16:01:10	  │ Video:        true                  │
build	18-Jun-2018 16:01:10	  │ Duration:     24 seconds            │
build	18-Jun-2018 16:01:10	  │ Spec Ran:     decision-tree.spec.js │
build	18-Jun-2018 16:01:10	  └─────────────────────────────────────┘
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  (Screenshots)
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  - /cypress/screenshots/DecisionTree - adding node title to summary adding via context menu  -- should add last node title to summary.png (1280x720)
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  (Video)
build	18-Jun-2018 16:01:10	
build	18-Jun-2018 16:01:10	  - Started processing:   Compressing to 16 CRF
build	18-Jun-2018 16:01:16	  - Finished processing:  /cypress/videos/decision-tree.spec.js.mp4 (5 seconds)
build	18-Jun-2018 16:01:16	
build	18-Jun-2018 16:01:16	
build	18-Jun-2018 16:01:16	================================================================================
```

The strange thing is that even if I repeated **totally** same actions, I can't reproduce such error. Only in e2e tests running.

Here is `cypress.json`:
```javascript
{
    "projectId": "...",
    "baseUrl": "...",
    "env": {
        "DECISION_TREE_TITLE": "$$DecisionTree Test Title",
        "GET_ALL_DECISION_TREES": "/api/builder-module/getAll",
        "CREATE_DECISION_TREE": "/api/builder-module/create",
        "CLONE_DECISION_TREE": "/api/builder-module/clone",
        "DELETE_DECISION_TREE": "/api/builder-module/remove",
        "USERNAME": "...",
        "PASSWORD": "...",
        "AUTH_KEY": "..."
    },
    "defaultCommandTimeout": 9000,
    "viewportWidth": 1920,
    "viewportHeight": 1080,
    "chromeWebSecurity": false,
    "fixturesFolder": "fixtures",
    "integrationFolder": "integration",
    "pluginsFile": "plugins/index.js",
    "supportFile": "support/index.js",
    "screenshotsFolder": "screenshots",
    "videosFolder": "videos",
    "reporter": "mocha-multi-reporters",
    "videoCompression": 16,
    "reporterOptions": {
        "configFile": "reports.config.json"
    }
}
```

### Desired behavior:

Without any errors, of course :)

### Steps to reproduce:

It's a private project

### Versions

Cypress: 3.0.1
macOS: 10.13.4
Angular(all stuff): 6.0.8

**Comment by slawiko** [comment]
Thank you @brian-mann , I tried but I didn't learn anything new about stacktrace.

Looks like we with my colleague @dosant know a bit about this issue. 
After `cy.visit()` (for example) some requests becomes cancelled - it's understandable. But after page loading, code related to these requests handling, continues to execute. And I assume, that in case of our issue `tslib` is broken somehow in execution context (so `__awaiter` works incorrect).

Actually it looks related to #761

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
