### ISSUE TITLE
9.3.1 - First spec file in integration folder fails due to Maximum call stack size exceeded

### ISSUE THREAD

**Issue by EdwinDurning** [cypress-io/cypress#19856]
### Current behavior

When running cypress in headless mode, the first spec file always fails. If I change the order of the files, the new first file fails. Any spec files following will run as desired.

error message in the terminal:
`RangeError: Maximum call stack size exceeded
    at Object.closeSync (node:fs:526:19)
    at Object.closeSync (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:74:20)
    at tryReadSync (node:fs:436:32)
    at Object.readFileSync (node:fs:471:19)
    at readFileSync (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:71:19)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:76:24)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at loadTsconfig (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:92:20)
    at Object.wrapChildPromise (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:44:23)
    at Object.wrap (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/preprocessor.js:28:8)
    at execute (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:119:27)
    at EventEmitter.<anonymous> (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:209:5)
    at EventEmitter.emit (node:events:390:28)
    at process.<anonymous> (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
From previous event:
    at Object.wrapParentPromise (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:63:12)
    at Object.file:preprocessor (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:167:23)
    at Object.execute (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:252:33)
    at /Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/preprocessor.js:102:22
From previous event:
    at Object.getFile (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/preprocessor.js:101:65)
    at SocketE2E.watchTestFileByPath (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/socket-e2e.js:71:39)
    at Socket.<anonymous> (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/server/lib/socket-e2e.js:83:26)
    at Socket.emit (node:events:394:28)
    at Socket.emitUntyped (/Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/x/Library/Caches/Cypress/9.3.1/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)`

This does not happen when running in open mode.

This is my first Bug Report, please let me know what additional information you need.

### Test code to reproduce

Cypress fails no matter what is contained in the first spec file. It can be empty or have valid test code but it will always fail.

### Cypress Version

9.3.1

**Comment by tbiethman** [comment]
@EdwinDurning thank you for reporting this. The fact that it only happens in run mode is good info. More information regarding your development environment would be helpful. Please provide:

* OS, node, and npm/yarn versions used
* The exact cypress command + options you are executing

**Comment by EdwinDurning** [comment]
@tbiethman Thank you for the quick response


OS: MacOS Monterey 12.1
node: 16.13.0
npm: 8.1.0
yarn: 3.1.1

I execute with `yarn run cypress:run` which uses: `NODE_ENV=development cypress run`
