### ISSUE TITLE
open-ct crash after closing cypress app

### ISSUE THREAD

**Issue by netfly** [cypress-io/cypress#20113]
### Current behavior

I do Vue Component Testing with "cypress open-ct". Everything works fine, but when I close the cypress app, my mac opens an error window and in my console I see the following error:
(And it doesn't matter if I cancel the npm script or close the window. Both ways end up in this error)

```
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (20.6.0)
Cypress Version: 9.3.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! somea@0.1.0 test:component:open: `cypress open-ct`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the somea@0.1.0 test:component:open script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/markus/.npm/_logs/2022-02-09T09_04_22_776Z-debug.log
```

the mentioned log is this:
```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:component:open'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [
4 verbose run-script   'pretest:component:open',
4 verbose run-script   'test:component:open',
4 verbose run-script   'posttest:component:open'
4 verbose run-script ]
5 info lifecycle somea@0.1.0~pretest:component:open: somea@0.1.0
6 info lifecycle somea@0.1.0~test:component:open: somea@0.1.0
7 verbose lifecycle somea@0.1.0~test:component:open: unsafe-perm in lifecycle true
8 verbose lifecycle somea@0.1.0~test:component:open: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/markus/Sites/somea/frontend/node_modules/.bin:/usr/local/sbin:/Users/markus/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Users/markus/.cargo/bin
9 verbose lifecycle somea@0.1.0~test:component:open: CWD: /Users/markus/Sites/somea/frontend
10 silly lifecycle somea@0.1.0~test:component:open: Args: [ '-c', 'cypress open-ct' ]
11 silly lifecycle somea@0.1.0~test:component:open: Returned: code: 1  signal: null
12 info lifecycle somea@0.1.0~test:component:open: Failed to exec test:component:open script
13 verbose stack Error: somea@0.1.0 test:component:open: `cypress open-ct`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid somea@0.1.0
15 verbose cwd /Users/markus/Sites/somea/frontend
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:component:open"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error somea@0.1.0 test:component:open: `cypress open-ct`
22 error Exit status 1
23 error Failed at the somea@0.1.0 test:component:open script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Desired behavior

Just close the app without an error.

### Test code to reproduce

The Tests work fine

### Cypress Version

9.3.1

### Other

When I do Integration test with "cypress open" everything works as expected.

**Comment by netfly** [comment]
Sorry, but I just saw, this topic is already reported in #20101

**Comment by flotwig** [comment]
Closing as duplicate
