### ISSUE TITLE
Tests containing `cy.wait` that pass `open-ct` fail on `run-ct`

### ISSUE THREAD

**Issue by haldunanil** [cypress-io/cypress#20128]
### Current behavior

Currently, I have a test that contains the following code:

```ts
  it("should fail/throw when name given is not valid", () => {
    // intercept API call to the backend
    cy.intercept("/slug*").as("endpoint");

    // make a call to backend
    MyClass.function("some-name");

    // check that the returned status was 404
    cy.wait("@endpoint", { timeout: 30000 }).should(({ response }) => {
      cy.wrap(response).should("have.property", "statusCode", 404);
    });
  });
```

which passes when run using `open-ct` but fails when run using `run-ct` with the following error message:

```
     CypressError: Timed out retrying after 30000ms: `cy.wait()` timed out waiting `30000ms` for the 1st request to the route: `endpoint`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:193346:18)
      at Object.errByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:193415:10)
      at checkForXhr (http://localhost:8080/__cypress/runner/cypress_runner.js:179591:92)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:179614:28
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:26476:23)
      at Function.Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:23750:29)
      at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:185817:63)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:185314:14
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:26476:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:24411:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:24468:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:24513:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:24593:18)
      at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:24537:18)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:26151:46
  From Your Spec Code:
      at $Cy.cy.<computed> [as wait] (http://localhost:8080/__cypress/runner/cypress_runner.js:190243:96)
      at Context.eval (webpack:///../../fpath?:39:8)
      at Context.runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:190495:19)
      at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:142849:21)
      at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:142836:7)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:197372:30
      at PassThroughHandlerContext.finallyHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:23030:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:26476:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:24411:31)
```

### Desired behavior

Test either passes in both `open-ct` and `run-ct` or fails in both and, if the latter, provides better a description of what the problem is.

### Test code to reproduce

The underlying code is:

```ts
MyClass {
  static fromAjaxData = (data) => {
    if (!data) {
      return null;
    }

    return new MyClass(
      data.id,
      data.name,
      data.description,
      ...
    );
  };

  static loadFromId = (id) => {
    const deferred = $.Deferred();

    let segment = null;

    if (!id) {
      deferred.resolve(null);
    } else {
      $.ajax({
        url: "/slug",
        data: {
          app_group_id: viewModel.meta.appGroupId(),
          segment_id: id,
        },
      })
        .done((data) => {
          segment = MyClass.fromAjaxData(data.segment);
          deferred.resolve(segment);
        })
        .fail(() => deferred.reject());
    }

    return deferred;
  };
}
```

### Cypress Version

9.4.1

**Comment by BlueWinds** [comment]
You have a race condition in your code. Remember that cypress commands *add things to a queue*, they don't execute immediately - even things like `cy.intercept`, which seems like it might be synchronous, require talking over a websocket to the cypress server running on your machine.

For me, your original case works sometimes, and changes behavior between browsers (mostly failing on Firefox, mostly passing on Chromium) - definitely a race condition in there, which is why you're getting different behavior between component and e2e testing.

You can fix this by using `cy.then()`, waiting to initialize your component (and make the call) until after your intercept / alias are set up.

```
  it("should fail/throw when name given is not valid", () => {
    cy.intercept("/slug*").as("endpoint");

    cy.then(() => {
        MyClass.loadFromId("some-id");
    })

    cy.wait("@endpoint", { timeout: 30000 }).should(({ response }) => {
      cy.wrap(response).should("have.property", "statusCode", 404);
    });
  });
```
