### ISSUE TITLE
Error: The plugins file is missing or invalid.

### ISSUE THREAD

**Issue by omelnik** [cypress-io/cypress#20227]
### Current behavior

Hi there. I started facing this issue and I need a little help with this. Once I added [DefinePlugin](https://v4.webpack.js.org/plugins/define-plugin/) into my webpack configuration, I started getting this error. Locally everything works perfectly, whenever I run tests on Jenkins I'm getting this error.

```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/var/jenkins/workspace/<name>/app/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/var/jenkins/workspace/<name>/app/cypress/webpack.config.ts:7:24)

````

I run my test in a debug mode on CI and here's what I've got:

```zsh
2022-02-16T18:44:07.676Z cypress:server:project scaffolding with plugins file /opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins/index.ts
2022-02-16T18:44:07.676Z cypress:server:scaffold plugins folder /opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins
2022-02-16T18:44:07.677Z cypress:server:plugins plugins.init /opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins/index.ts
2022-02-16T18:44:07.680Z cypress:server:plugins launching using custom node version { resolvedNodePath: '/tmp/yarn--1645037042619-0.6987812942308429/node', resolvedNodeVersion: '12.22.10' }
2022-02-16T18:44:07.680Z cypress:server:plugins forking to run /root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
2022-02-16T18:44:07.833Z cypress:server:plugins:child pluginsFile: /opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins/index.ts
2022-02-16T18:44:07.834Z cypress:server:plugins:child project root: /opt/jenkins/jobs/<project-name>/workspace/app
2022-02-16T18:44:07.836Z cypress:server:plugins resolving typescript with options { basedir: '/opt/jenkins/jobs/<project-name>/workspace/app' }
2022-02-16T18:44:07.839Z cypress:server:plugins resolved typescript /opt/jenkins/jobs/<project-name>/workspace/app/node_modules/typescript/lib/typescript.js
2022-02-16T18:44:07.840Z cypress:server:ts-node typescript path: /opt/jenkins/jobs/<project-name>/workspace/app/node_modules/typescript/lib/typescript.js
2022-02-16T18:44:07.840Z cypress:server:ts-node registering project TS with options { compiler: '/opt/jenkins/jobs/<project-name>/workspace/app/node_modules/typescript/lib/typescript.js', compilerOptions: { module: 'CommonJS' }, dir: '/opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins', transpileOnly: true }
2022-02-16T18:44:08.101Z cypress:server:plugins:child require pluginsFile
2022-02-16T18:44:08.614Z cypress:server:plugins:child failed to require pluginsFile:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/opt/jenkins/jobs/<project-name>/workspace/app/cypress/webpack.config.ts:7:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at runPlugins (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:177:15)
    at Object.<anonymous> (/root/.cache/Cypress/6.4.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
2022-02-16T18:44:08.616Z cypress:server:plugins load:error PLUGINS_FILE_ERROR, rejecting
2022-02-16T18:44:08.619Z cypress:server:cypress exiting with err Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/opt/jenkins/jobs/<project-name>/workspace/app/cypress/plugins/index.ts`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.
```

### Test code to reproduce

**Dependencies:** 
- "typescript": "4.3.5"
- "webpack": "^4.41.5",
- "tsconfig-paths-webpack-plugin": "^3.3.0",
- "cypress": "^6.3.0",
- "dotenv": "^10.0.0",
- "@cypress/webpack-preprocessor": "^5.5.0",

File: `app/cypress/webpack.config.ts`
```ts
import { Configuration, DefinePlugin } from 'webpack';
import { TsconfigPathsPlugin } from 'tsconfig-paths-webpack-plugin';
import dotenv from 'dotenv';

const env: any = dotenv.config().parsed;

const envKeys = Object.keys(env).reduce((prev: Record<string, string>, next: string) => {
    // eslint-disable-next-line no-param-reassign
    prev[`process.env.${next}`] = JSON.stringify(env[next]);
    return prev;
}, {});

export const cypressWebpackConfig: Configuration = {
    resolve: {
        extensions: ['.ts', '.tsx', '.js'],
        plugins: [new TsconfigPathsPlugin()],
    },
    module: {
        rules: [
            {
                test: /\.[jt]sx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
            },
        ],
    },
    plugins: [new DefinePlugin(envKeys)],
};
```

File: `app/cypress/tsconfig.json`
```ts
{
    "compilerOptions": {
        "baseUrl": ".",
        "esModuleInterop": true,
        "lib": ["dom", "esnext"],
        "noEmit": true,
        "skipLibCheck": true,
        "strict": true
    },
    "include": ["../../node_modules/cypress", "**/*"]
}
```

File: `app/cypress/plugins/index.ts`
```ts
import webpackPreprocessor from '@cypress/webpack-preprocessor';
import { cypressWebpackConfig } from '../webpack.config';
import { loadConfig } from '../common/config';

export default (
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Cypress.PluginConfigOptions => {
    on(
        'file:preprocessor',
        webpackPreprocessor({
            webpackOptions: cypressWebpackConfig,
        })
    );
    // eslint-disable-next-line no-param-reassign
    config = { ...config, ...loadConfig() };
    return config;
};
```

I even tried specifying the direct path to my `/plugins/index.ts`  file, but it didn't help much.
```json
{
    "reporter": "junit",
    "reporterOptions": {
        "mochaFile": "cypress/results/testResults.[hash].xml"
    },
    "nodeVersion": "system",
    "retries": {
        "runMode": 2,
        "openMode": 0
    },
    "pluginsFile": "cypress/plugins/index.ts"
}

```

File: `app/cypress/common/config.ts`
```ts
import fs from 'fs';
import path from 'path';

const getConfigurationByFile = (file: string): any => {
    const filePath = path.resolve('..', 'app/cypress/fileConfig', `${file}.json`);
    const rawdata = fs.readFileSync(filePath).toString();
    return JSON.parse(rawdata);
};

function filterCypressEnv(envVars: NodeJS.ProcessEnv): { [key: string]: string } {
    return Object.entries(envVars).reduce((acc, pair) => {
        const [envVar, value] = pair;
        if (envVar.startsWith('CYPRESS')) {
            Object.assign(acc, { [envVar.substring(8)]: value });
        }
        return acc;
    }, {});
}

export function loadConfig(): { [key: string]: string } {
    const environment = process.env.CYPRESS_TEST_ENV || 'local';
    const config = getConfigurationByFile(environment);
    config.env = { ...config.env, ...filterCypressEnv(process.env) };
    return config;
}

```

### Cypress Version

6.4.0

**Comment by iamskok** [comment]
@omelnik how did you solve it? I'm facing the same error.
