### ISSUE TITLE
Cypress tests not working in docker swarm mode using container service name as baseUrl

### ISSUE THREAD

**Issue by kregheg** [cypress-io/cypress#20239]
### What would you like?

Good day, colleagues!

It seems that cypress cannot work with swarm network in docker-swarm mode.

I am trying to start tests within swarm that consist of multiple services + cypress container + nginx container (let it be "nginx_gateway").

Inside the swarm all services can communicate using service name, for example, any service can get login web-page using "https://nginx_gateway:8443/someURL" url.

But when Cypress tests starts I got fails with output:

    Running:  RBAC/test_RBAC_admin.e2e-spec.ts                                (1 of 9)

    Timed out waiting for the browser to connect. Retrying...

    Timed out waiting for the browser to connect. Retrying again...

    The browser never connected. Something is wrong. The tests cannot run. Aborting...

    The browser never connected. Something is wrong. The tests cannot run. Aborting...
    Warning: We failed processing this video.

    This error will not alter the exit code.

    TimeoutError: operation timed out
        at afterTimeout (/usr/local/bin/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
        at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/bin/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7)

Monitoring tcp-connections inside nginx_gateway container during tests run shows that there were no incoming tcp-connection from chrome.

No one packet send during test except one tcp-session when cypress is verifying remote resource before test starts at the beginning (this session usually starts and closes immediately):
  sh-4.2# tcpdump -ni eth0 port 8443
      14:55:21.786613 IP 10.0.26.6.58734 > 10.0.26.21.pcsync-https: Flags [S], seq 2751108752, win 64860, options [mss 1410,sackOK,TS val 4128685655 ecr 0,nop,wscale 7], length 0
      14:55:21.786649 IP 10.0.26.21.pcsync-https > 10.0.26.6.58734: Flags [S.], seq 2793953799, ack 2751108753, win 64308, options [mss 1410,sackOK,TS val 875692222 ecr      4128685655,nop,wscale 7], length 0
      14:55:21.786702 IP 10.0.26.6.58734 > 10.0.26.21.pcsync-https: Flags [.], ack 1, win 507, options [nop,nop,TS val 4128685655 ecr 875692222], length 0
      14:55:21.787890 IP 10.0.26.6.58734 > 10.0.26.21.pcsync-https: Flags [F.], seq 1, ack 1, win 507, options [nop,nop,TS val 4128685656 ecr 875692222], length 0
      14:55:21.787947 IP 10.0.26.21.pcsync-https > 10.0.26.6.58734: Flags [F.], seq 1, ack 2, win 503, options [nop,nop,TS val 875692223 ecr 4128685656], length 0
      14:55:21.788006 IP 10.0.26.6.58734 > 10.0.26.21.pcsync-https: Flags [.], ack 2, win 507, options [nop,nop,TS val 4128685656 ecr 875692223], length 0

But everything is OK when I use headless google-chrome cli inside cypress container with command:
google-chrome --headless --disable-gpu --print-to-pdf="/tmp/pdf" --window-size=1940,1080 --no-sandbox --ignore-certificate-errors https://nginx_gateway:8443/baseURL/
I receive web page and I can see incoming tcp connections from cypress container inside nginx_gateway container. So, it does not seems like a problem with chrome exactly.

In normal case (not swarm mode and "https://<nginx_ip>:8443/baseURL" as baseUrl.) I see incoming tcp-connections from chrome after 5-6 seconds after cypress checked resource from baseUrl. All tests pass correctly, no problem.

Debug messages are usually like this:
2022-02-16T11:21:20.325Z cypress:launcher chrome stderr: [0216/112120.325397:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
2022-02-16T11:21:20.907Z cypress:server:server-base Got CONNECT request from nginx_gateway:8443
2022-02-16T11:21:20.907Z cypress:https-proxy Writing browserSocket connection headers { url: 'nginx_gateway:8443', headLength: 0, headers: { host: 'nginx_gateway:8443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.212 Safari/537.36' } }
2022-02-16T11:21:20.910Z cypress:https-proxy Got first head bytes { url: 'nginx_gateway:8443', head: "\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03Z'��\x12�Q��D��cw�pSV����mœ#Es��\b ��>�A���#��k\x002�\r�A�\x03�\x17" }
2022-02-16T11:21:21.102Z cypress:https-proxy Making intercepted connection to 36373
2022-02-16T11:21:21.104Z cypress:network:connect successfully connected { opts: { port: 36373, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2022-02-16T11:21:21.105Z cypress:https-proxy received upstreamSocket callback for request { port: 36373, hostname: 'localhost', err: undefined }
2022-02-16T11:21:21.105Z cypress:server:util:socket_allowed allowing socket { localPort: 53464 }
2022-02-16T11:21:21.109Z cypress:launcher chrome stderr: [0216/112121.108872:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -167
2022-02-16T11:21:21.110Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 53464 }
2022-02-16T11:21:21.111Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.loadingFailed', params: { requestId: '7BDA9B9C6F0F149B46D9855825F5A41C', timestamp: 181913.715374, type: 'Document', errorText: 'net::ERR_SSL_SERVER_CERT_BAD_FORMAT', canceled: false } }
2022-02-16T11:21:21.112Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { id: 5, result: { frameId: '22387908373F544E43B771B5D71A9C87', loaderId: '7BDA9B9C6F0F149B46D9855825F5A41C', errorText: 'net::ERR_SSL_SERVER_CERT_BAD_FORMAT' } }
2022-02-16T11:21:21.112Z cypress-verbose:server:browsers:cri-client:send:[-->] sending CDP command { id: 6, method: 'Page.enable', params: {} }
2022-02-16T11:21:21.129Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Page.screencastVisibilityChanged', params: { visible: true } }
2022-02-16T11:21:21.133Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.loadingFinished', params: { requestId: 'FB6102F6CA5C9B946C30BCCFFE6C18B8', timestamp: 181913.734112, encodedDataLength: 0, shouldReportCorbBlocking: false } }
2022-02-16T11:21:21.135Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { id: 6, result: {} }
2022-02-16T11:21:21.135Z cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.downloadWillBegin' }
2022-02-16T11:21:21.135Z cypress:server:browsers:cri-client registering CDP on event { eventName: 'Page.downloadProgress' }
2022-02-16T11:21:21.135Z cypress-verbose:server:browsers:cri-client:send:[-->] sending CDP command { id: 7, method: 'Page.setDownloadBehavior', params: { behavior: 'allow', downloadPath: '/app/tests/cypress/downloads' } }
2022-02-16T11:21:21.136Z cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { id: 7, result: {} }
2022-02-16T11:21:21.136Z cypress:server:browsers browser opened
2022-02-16T11:22:20.020Z cypress:server:browsers killing browser process
2022-02-16T11:22:20.020Z cypress:server:browsers:chrome closing remote interface client
2022-02-16T11:22:20.020Z cypress:server:browsers:chrome closing chrome

I suppose that the problem is somewhere near cypress.https-proxy

### Why is this needed?

Cypress tests could work in docker swarm mode using service names as baseUrl

**Comment by BlueWinds** [comment]
One thing to try is to ensure you have a "." in the baseUrl - [other users](https://github.com/cypress-io/cypress/issues/20015) have had issues when using URLs without them. That issue I linked isn't exactly what you're running into, but trying to add a fake `.foo` on the end of the baseUrl might be a good place to start figuring it out.

**Comment by liam102** [comment]
I got the same 
```
cypress:server:util:socket_allowed allowing socket { localPort: 53464 }
cypress:launcher chrome stderr: [0216/112121.108872:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -167
```
Running in container with image `cypress/base:16`
