### ISSUE TITLE
Cypress require write access of root folder

### ISSUE THREAD

**Issue by xiabai84** [cypress-io/cypress#20366]
### Current behavior

Hi, 
I'm trying to deploy a cypress docker container via a non-root user in Openshift Cluster. 

But Cypress want to create a `.config` subfolder under root folder. Can I change this default settings?

```
[STARTED] Task without title.
[FAILED] Cypress failed to start.
[FAILED]
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED]
[FAILED] Please refer to the error below for more details.
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] [1m[47m[31mA JavaScript error occurred in the main process
[FAILED] [30mUncaught Exception:
[FAILED] Error: EACCES: permission denied, mkdir '/.config'
[FAILED] at Object.mkdirSync (node:fs:1324:3)
[FAILED] at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
[FAILED] at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
[FAILED] at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
[FAILED] at Object.mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
[FAILED] at createFile (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/logger.js:23:6)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/logger.js:42:21)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/server-base.js:20:47)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/server-ct.js:7:23)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/project-base.js:25:21)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/open_project.js:11:24)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/cypress.js:16:25)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/index.js:39:18)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Module.require (node:internal/modules/cjs/loader:1006:19)
[FAILED] at require (node:internal/modules/cjs/helpers:93:18)
[FAILED] at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/index.js:2:1)
[FAILED] at Module._compile (node:internal/modules/cjs/loader:1110:14)
[FAILED] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[FAILED] at Module.load (node:internal/modules/cjs/loader:982:32)
[FAILED] at Module._load (node:internal/modules/cjs/loader:823:12)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Object.<anonymous> (node:electron/js2c/browser_init:197:3197)
[FAILED] at Object../lib/browser/init.ts (node:electron/js2c/browser_init:197:3401)
[FAILED] at __webpack_require__ (node:electron/js2c/browser_init:1:128)
[FAILED] at node:electron/js2c/browser_init:1:1200
[FAILED] at node:electron/js2c/browser_init:1:1267
[FAILED] at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
[FAILED] at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
[FAILED] at loadNativeModule (node:internal/modules/cjs/helpers:40:9)
[FAILED] at Module._load (node:internal/modules/cjs/loader:805:15)
[FAILED] at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
[FAILED] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
[FAILED] at node:internal/main/run_main_module:17:47
[FAILED] [0m
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-x64 (Debian - 10.11)
[FAILED] Cypress Version: 9.5.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

[1m[47m[31mA JavaScript error occurred in the main process
[30mUncaught Exception:
Error: EACCES: permission denied, mkdir '/.config'
at Object.mkdirSync (node:fs:1324:3)
at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
at mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
at Object.mkdirsSync (/app/.cache/Cypress/9.5.0/Cypress/resources/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
at createFile (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/logger.js:23:6)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/logger.js:42:21)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/server-base.js:20:47)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/server-ct.js:7:23)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Function.Module._load (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/override_require.js:15:27)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/project-base.js:25:21)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/open_project.js:11:24)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/lib/cypress.js:16:25)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/packages/server/index.js:39:18)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/app/.cache/Cypress/9.5.0/Cypress/resources/app/index.js:2:1)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Object.<anonymous> (node:electron/js2c/browser_init:197:3197)
at Object../lib/browser/init.ts (node:electron/js2c/browser_init:197:3401)
at __webpack_require__ (node:electron/js2c/browser_init:1:128)
at node:electron/js2c/browser_init:1:1200
at node:electron/js2c/browser_init:1:1267
at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
at loadNativeModule (node:internal/modules/cjs/helpers:40:9)
at Module._load (node:internal/modules/cjs/loader:805:15)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
at node:internal/main/run_main_module:17:47
[0m
```

### Test code to reproduce

Here is my Dockerfile
```
FROM cypress/base:17.3.0

WORKDIR /app

COPY ./startup.sh ./startup.sh
COPY ./cypress ./cypress
COPY ./cypress.json ./cypress.json
COPY ./package.json ./package.json

RUN npm install
RUN mv /root/.cache /app/.cache && chmod a+x -R /app/.cache && chmod a+rwx /app

ENV CYPRESS_CACHE_FOLDER "/app/.cache/Cypress"

CMD ["/app/node_modules/.bin/cypress", "run", "--config-file", "./cypress.json"]
```

cypress.json
```
{
  "pluginsFile": "cypress/plugins/index.js",
  "supportFile": "cypress/support/index.js",
  "video": false,
  "screenshotOnRunFailure": true,
  "experimentalStudio": true,
  "reporter": "junit",
  "reporterOptions": {
    "mochaFile": "/tmp/result.xml",
    "toConsole": false
  }
}
```

### Cypress Version

9.5.0

**Comment by xiabai84** [comment]
solved by setting HOME env and granting permission by using setfacl.
