### ISSUE TITLE
Shodow().find error `Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by rami8k** [cypress-io/cypress#20374]
### Current behavior

Hi,

I'm trying to test a shadow root component. The test case is simple, find the checkbox and verify its checked.
The test script is as follows:
`cy.get('[data-test=newsletter-signup-checkbox-BUNW_NL]').shadow().find('input').should('be.checked')`
it fails on `find`

in the dashboard when I click on the `- shadow` Iog line I get the following printed in the console showing the content of the shadow root, which is expected:
<img width="1385" alt="Screen Shot 2022-02-25 at 8 58 07 PM" src="https://user-images.githubusercontent.com/10948292/155824702-077ea846-865f-47c9-886e-9be4c14fdb9e.png">

however the next line for `- find` is throwing an error:
<img width="474" alt="Screen Shot 2022-02-25 at 9 03 32 PM" src="https://user-images.githubusercontent.com/10948292/155824783-52a4a4a7-f1db-4d5a-ab1e-2e7ad3929acd.png">

Last thing is I forked the test repo, I attached a shadow element with some html and cypress was able to find elements within the shadow root. I don't know whats the problem with my original repo but I thought you might have an idea! maybe the stack trace could help.

Thank you. 

This is the stack trace:
at superMatcher (https://local.my-domain.com/__cypress/runner/cypress_runner.js:110542:18)
at Sizzle.select (https://local.my-domain.com/__cypress/runner/cypress_runner.js:110738:45)
at Function.Sizzle [as find] (https://local.my-domain.com/__cypress/runner/cypress_runner.js:108906:10)
at jQuery.fn.init.find (https://local.my-domain.com/__cypress/runner/cypress_runner.js:110937:12)
at getEl (https://local.my-domain.com/__cypress/runner/cypress_runner.js:162368:36)
at getElements (https://local.my-domain.com/__cypress/runner/cypress_runner.js:162387:18)
at Context. (https://local.my-domain.com/__cypress/runner/cypress_runner.js:162413:15)
at Context. (https://local.my-domain.com/__cypress/runner/cypress_runner.js:173141:20)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:171997:16)
From previous event:
at CommandQueue.runCommand (https://local.my-domain.com/__cypress/runner/cypress_runner.js:171976:9)
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:172119:20)
From previous event:
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:172119:40)
From previous event:
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:186506:78)
From previous event:
at CommandQueue.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:186501:22)
at CommandQueue.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:172182:16)
at $Cy.cy. [as get] (https://local.my-domain.com/__cypress/runner/cypress_runner.js:173180:19)
at Context.runnable.fn (https://local.my-domain.com/__cypress/runner/cypress_runner.js:173398:20)
at callFn (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125619:22)
at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125606:8)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180282:31)
From previous event:
at Object.onRunnableRun (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180267:20)
at $Cypress.action (https://local.my-domain.com/__cypress/runner/cypress_runner.js:169637:29)
at Test.Runnable.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:177963:14)
at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126278:11)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126404:13)
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126187:15)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126197:8)
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126099:15)
at Hook. (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126160:8)
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180180:25)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180209:14)
From previous event:
at onNext (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180206:60)
at done (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125559:6)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125624:12)
From previous event:
at callFn (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125622:15)
at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:125606:8)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180282:31)
From previous event:
at Object.onRunnableRun (https://local.my-domain.com/__cypress/runner/cypress_runner.js:180267:20)
at $Cypress.action (https://local.my-domain.com/__cypress/runner/cypress_runner.js:169637:29)
at Hook.Runnable.run (https://local.my-domain.com/__cypress/runner/cypress_runner.js:177963:14)
at next (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126121:11)
at (https://local.my-domain.com/__cypress/runner/cypress_runner.js:126165:6)
at timeslice (https://local.my-domain.com/__cypress/runner/cypress_runner.js:120091:28)

### Desired behavior

Find on `shadow()` should yield and element.

### Test code to reproduce

https://github.com/rami8k/cypress-test-tiny

I actually tried with a fork and it seem to be working when I attach a shadow element:
https://github.com/rami8k/cypress-test-tiny/blob/master/index.html#L6

### Cypress Version

9.5.0

**Comment by rami8k** [comment]
I was able to re-produce the error, I updated the test repo.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

I ran the repo and it shows that the problematic code is in the website's side.

![image](https://user-images.githubusercontent.com/8130013/156683605-0577fc7b-2c00-4f86-b929-5adb8b64a47b.png)

It's minified, so it's hard to detect the problem with the current repo. 

We need a simpler bug sample. As we all know, the debugging starts with reproducing the problem on the developer's machine.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
