### ISSUE TITLE
Cypress crashes with 'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by LilyNL** [cypress-io/cypress#20605]
### Current behavior

Cypress crashes and stops when I run the following script 

    cy.request({
        method: 'POST',
        url: url + '/OApi/Delete',
        headers: {'Content-Type': 'application/json'},
        body: 7,
    })

In the command prompt where I run Cypress with _npx cypress open_ the following error appears:

> TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type number (7)
    at new NodeError (node:internal/errors:370:5)
    at write_ (node:_http_outgoing:739:11)
    at ClientRequest.write (node:_http_outgoing:704:15)
    at Request.write (C:\Users\XX\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:1489:27)
    at end (C:\Users\XX\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:541:18)
    at Immediate.<anonymous> (C:\Users\..\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:570:7)
    at processImmediate (node:internal/timers:464:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type number (7)
    at new NodeError (node:internal/errors:370:5)
    at write_ (node:_http_outgoing:739:11)
    at ClientRequest.write (node:_http_outgoing:704:15)
    at Request.write (C:\Users\XX\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:1489:27)
    at end (C:\Users\XX\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:541:18)
    at Immediate.<anonymous> (C:\Users\XX\AppData\Local\Cypress\Cache\9.5.1\Cypress\resources\app\node_modules\@cypress\request\request.js:570:7)
    at processImmediate (node:internal/timers:464:21)

### Desired behavior

Cypress should inform the error in web-browser and must not stop

### Test code to reproduce

Test code

    cy.request({
        method: 'POST',
        url: url + '/OrdersApi/Delete',
        headers: {'Content-Type': 'text/json'},
        body: 7,
    })

The function requires parameter in the body of the request as integer. It works well when sending request from Swagger. 

### Cypress Version

9.5.1

**Comment by LilyNL** [comment]
It seems that in Cypress body must always be string ??!!

**Comment by emilyrohrbough** [comment]
@LilyNL The error message describe the expected type:

> TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. R

**Comment by sofinapradhan-tag** [comment]
is there any workaround to this issue?
