### ISSUE TITLE
Cypress Runner Cannot find Chrome (MacOS)

### ISSUE THREAD

**Issue by jimberley** [cypress-io/cypress#20834]
### Current behavior

**Message:** Can't run because you've entered an invalid browser name.

Browser: `chrome` was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
 - electron
 - chrome
 - chromium
 - chrome:canary
 - edge
 - firefox

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
 - firefox
 - electron

**Stack trace:**
```
    at throwBrowserNotFound (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:140:22)
    at /Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:125:12
    at tryCatcher (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jimvannest/Library/Caches/Cypress/9.5.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (node:internal/timers:464:21)

```

### Desired behavior

I would like to use Chrome, please. It's installed on my computer.

### Test code to reproduce

This is an issue on Cypress' side which requires no code on my side to error.

### Cypress Version

9.5.3

**Comment by wojciech-sygier** [comment]
It's running perfectly fine for me on Chrome 100 and Cypress 9.5.3. How did you install Chrome nad what macOS version do you have? Also is this an issue with `cypress open` or `cypress run`?

**Comment by jimberley** [comment]
Thanks for replying.

Chrome was installed via Safari download. It’s now on version
99.0.4844.74(Official Build)(x86_64)

MacOS 11.6.4

The issue happens with “cypress open”. I can’t find Chrome in the drop down
menu, and when I try to force it to run with chrome by passing the —browser
flag in the CLI for cypress open, I get the above error.

**Comment by ozmium** [comment]
You may have a Cypress configuration JSON file somewhere in your `node.js` project, that looks something like this:

(if not, search for the string `"chrome"` in your project (including the speech mark characters)

```json
{
  "targets": {
    "e2e": {
      "executor": "@nrwl/cypress:cypress",
      "outputs": [
        "integration-tests/web-app-ui-e2e",
        "integration-tests/web-app-ui-e2e/videos",
        "integration-tests/web-app-ui-e2e/screenshots"
      ],
      "options": {
        "cypressConfig": "apps/web-app-ui-e2e/cypress.config.ts",
        "tsConfig": "apps/web-app-ui-e2e/tsconfig.json",
        "devServerTarget": "web-app-ui-e2e:serve-all",
        "baseUrl": "http://localhost:8080",
        "browser": "chrome"  //// <--- Remove this line on MacOS (and remove the comma in the previous line)
      },
      "configurations": {
        "production": {
          "devServerTarget": "web-app-ui-e2e:serve-all"
        }
      }
    },
    "nextTarget": {}
  }
}
```

When running the End-to-End (e2e) tests with Cypress on Mac OS, using either...

* MacOS 10.15 Catalina
* Mac OS X 11 Big Sur
* Mac OS 12.5 Monterey
* MacOS 13 Ventura

... **You must remove the line in the Cypress configuration that says `"browser": "chrome"` , and also remove the comma on the line above it, to ensure that it's valid JSON.** That line works fine on Windows and Linux, but not on MacOS.

This is to allow Cypress to launch the default web browser on Mac OS. Note that on Apple Mac computers, there is no command-line option to launch a browser, for example:

```shell
chrome https://en.wikipedia.org
or
firefox https://www.google.com
```

This is why the Cypress test fails, because it's trying to use a command-line option that doesn't exist. The web browsers on Mac OS X do not install command-line tools to launch themselves, like on Windows on Linux. The equivalent on Mac OS is

```shell
open https://www.apple.com
```

which will launch the default browser.

See also:

* https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers
