### ISSUE TITLE
Error spawn UNKNOWN during

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [cypress-io/cypress#20842]
### Current behavior

Not able to run my spec files using the below mentioned command

npx cypress run --spec <spec path>

Hi Team,

I have below mentioned version of cypress and experiencing issue while running the cypress from package.json:

"cy:run": "cypress run --spec 'cypress/integration/1-getting-started/*.js' --browser chrome --headed"

error:

Warning: We failed to trash the existing run results.

This error will not alter the exit code.

Error: spawn UNKNOWN
at ChildProcess.spawn (node:internal/child_process:415:11)
at spawn (node:child_process:707:9)
at execFile (node:child_process:334:17)
at node:child_process:244:21
at node:electron/js2c/asar_bundle:5:3121
at module.exports (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\lib\windows.js:12:8) at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\index.js:53:11
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\p-try\index.js:4:10
at new Promise (:null:null)
at pTry (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\p-try\index.js:3:37)
at trash (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\index.js:11:35)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\util\trash.js:16:16
at tryCatcher (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
at MappingPromiseArray._promiseFulfilled (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\map.js:68:38)
at MappingPromiseArray.PromiseArray._iterate (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:115:31)
at MappingPromiseArray.init (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:79:10)
at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:601:21)
at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\graceful-fs\graceful-fs.js:209:16
at FSReqCallback.oncomplete (node:fs:185:23)

================================================================================

(Run Starting)

┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress: 9.5.2 │
│ Browser: Chrome 99 │
│ Node Version: v14.15.0 (C:\Program Files\nodejs\node.exe) │
│ Specs: 1 found (1-getting-started/todo.spec.js) │
│ Searched: cypress\integration\1-getting-started*.js │
└────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────

Running: 1-getting-started/todo.spec.js (1 of 1)
spawn UNKNOWN
Error: spawn UNKNOWN
at ChildProcess.spawn (node:internal/child_process:415:11)
at spawn (node:child_process:707:9)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:152:24
at FfmpegCommand.proto._getFfmpegPath (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:90:14)
at FfmpegCommand.proto._spawnFfmpeg (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:132:10)
at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:517:10)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:568:14
at nextTask (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4576:13)
at Object.waterfall (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4587:9)
at Object.awaitable (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:208:32)
at FfmpegCommand.proto._checkCapabilities (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:565:11)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:298:14
at nextTask (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4576:13)
at Object.waterfall (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4587:9)
at Object.awaitable (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:208:32)
at FfmpegCommand.proto._prepare (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:295:11)
at FfmpegCommand.proto.exec.proto.execute.proto.run (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:431:10)
at FfmpegCommand.proto.saveToFile.proto.save [as save] (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\recipes.js:28:25)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:215:24
at Promise.cancellationExecute [as _execute] (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\debuggability.js:406:9)
at Promise._resolveFromExecutor (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:518:18)
at new Promise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:103:10)
at startCapturing (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:169:16)
at Object.start (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:218:12)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\modes\run.js:680:6
at tryCatcher (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:617:21)
at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fs-extra\node_modules\universalify\index.js:22:54

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raghav-pal@1.0.0 cy:run: cypress run --spec 'cypress/integration/1-getting-started/*.js' --browser chrome --headed
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raghav-pal@1.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\kemtej01\AppData\Roaming\npm-cache_logs\2022-03-17T10_20_02_430Z-debug.log

### Desired behavior

chrome browser should be launched all the specs should be executed. 

### Test code to reproduce

https://github.com/T-e-j-k-u-m-a-r/cypress-handson

### Cypress Version

8.7.0, Infact tried with latest version as well. But facing the same error. 

### Other

Tried downgrading to older version of cypress, But still facing the same error.

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi Team, 

Any update on the above issue?

**Comment by T-e-j-k-u-m-a-r** [comment]
@davidmunechika : Any update on the above issue?

**Comment by davidmunechika** [comment]
I noticed the repo you linked in the description only contains a README.md file. Is there any test code we can use to reproduce this that you could provide?

**Comment by T-e-j-k-u-m-a-r** [comment]
@davidmunechika  : The issue was related to group policy which had blocked cypress tool for using, Once IT team has whitelisted the cy tool. Its working fine. 

Now, I'm able to perform both tasks. 

1. Launch cypress from command prompt and also from VS code terminal
2. Run cypress using cypress run command from both command prompt and VS code terminal. 

@davidmunechika   and others facing similar issue: The command used to update the group policy is: gpupdate /force

How to execute this command: 

Step1: Open CMD, Type in above command and HIT <Enter>
Step2: Wait for the confirmation to appear which states that the group policy update is successful. 

Restart your system, You are all set to use cypress now 🚀🚀

**Comment by davidmunechika** [comment]
@T-e-j-k-u-m-a-r Thanks for following up with a solution to this issue!
