### ISSUE TITLE
Headless Cypress gets stuck after tests run if screenshot is taken with no video

### ISSUE THREAD

**Issue by lkelley-bec** [cypress-io/cypress#21029]
### Current behavior

Currently if Cypress is run in headless mode with no video being recorded and the test attempts to take a screenshot (either because the test failed or using the `cy.screenshot()` function), Cypress will fail to take the screenshot and when it gets to the end of the run it will get stuck here:

```
================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  test.spec.js                             00:37        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:37        1        -        1        -        -  

```

It stays stuck there for hours - I ran it overnight and it never terminated. This doesn't seem to happen when running with `cypress open`. This issue happens at least going back to Cypress 8.7.0.

What follows is the full output (including the `^C` I used to send a SIGINT) from a run I did of my reproducing repo:
```
[STARTED] Task without title.
[TITLE]  Verified Cypress!       /root/.cache/Cypress/9.5.4/Cypress
[SUCCESS]  Verified Cypress!       /root/.cache/Cypress/9.5.4/Cypress
[399:0411/193342.575235:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 

================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.4                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v16.14.2 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (test.spec.js)                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  test.spec.js                                                                    (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  1) fails and takes a screenshot

  0 passing (38s)
  1 failing

  1) fails and takes a screenshot:
     CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
      at https://www.google.com/__cypress/runner/cypress_runner.js:160811:81
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:13022:23)
      at https://www.google.com/__cypress/runner/cypress_runner.js:8144:41
      at tryCatcher (https://www.google.com/__cypress/runner/cypress_runner.js:13022:23)
      at Promise._settlePromiseFromHandler (https://www.google.com/__cypress/runner/cypress_runner.js:10957:31)
      at Promise._settlePromise (https://www.google.com/__cypress/runner/cypress_runner.js:11014:18)
      at Promise._settlePromise0 (https://www.google.com/__cypress/runner/cypress_runner.js:11059:10)
      at Promise._settlePromises (https://www.google.com/__cypress/runner/cypress_runner.js:11135:18)
      at _drainQueueStep (https://www.google.com/__cypress/runner/cypress_runner.js:7729:12)
      at _drainQueue (https://www.google.com/__cypress/runner/cypress_runner.js:7722:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:7738:5)
      at Async.drainQueues (https://www.google.com/__cypress/runner/cypress_runner.js:7608:14)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     37 seconds                                                                       │
  │ Spec Ran:     test.spec.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  test.spec.js                             00:37        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:37        1        -        1        -        -  

[412:0411/193423.737113:ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -100
^C
```

### Desired behavior

Cypress should not get stuck and should successfully take the screenshot just like when it does record video.

### Test code to reproduce

I made a reproducible example at https://github.com/lkelley-bec/cypress-stuck-screenshot using one of Cypress's provided Docker containers.

### Cypress Version

9.5.4

**Comment by msvinayps** [comment]
I'm also facing the same issue with 9.5.0 and 9.5.4 versions. This is happening in pipeline where even after all tests gets passed the execution step keeps running until it's terminated.

<img width="981" alt="Screenshot 2023-01-17 at 2 25 19 PM" src="https://user-images.githubusercontent.com/96492253/212852958-56b55b19-e036-43ec-91a2-cec6fb046f1c.png">

**Comment by lkelley-bec** [comment]
I can no longer reproduce the issue using my attached repo, even though it's still pinned to Cypress 9.5.4. Things that might have changed:
* I now have Podman rather than Docker installed, so maybe there's some odd discrepancy there that "fixed" the issue
* I foolishly didn't include a `package-lock.json` in my reproduction repo, so `npm` might be pulling in a different version of some dependency that fixes the problem?

Anyways, looks like it's probably fixed?
