### ISSUE TITLE
Cypress (Windows) automatically shuts down when attempting to open a project (WSL).

### ISSUE THREAD

**Issue by david-kirkland** [cypress-io/cypress#21095]
### Current behavior

Cypress is here:  C:\Users\xxxxx\AppData\Roaming\Cypress\Cypress.exe
Project is here:  \\\wsl$\Ubuntu\home\xxxxx\code\automated-tests

When I click "select manually" I am able to navigate to and select the desired directory in WSL.  When Cypress attempts to load this project the app unexpectedly shuts down.  When I reopen the app I can see a project with the correct path in WSL does exist under Recent Projects.  When I click to open/run this project the app shuts down.

### Desired behavior

I want Cypress installed on the Windows side and I want the Cypress project to live in WSL.

### Test code to reproduce

Environment config.  No relevant test code.

### Cypress Version

9.5.4

### Other

I am in an enterprise environment without the ability to install whatever I want.  I cannot install Cypress in WSL because I cannot install X-server.  I need the revision controlled test scripts to live in WSL because I only have Git on the WSL side.

**Comment by ohrlando** [comment]
Same here. I am studying alternatives to run cypress at wsl without x server (I'm not able to install a X Server because i have not Admin priviligies)

chokidar lib cannot handle with wsl directories apparently

```
####@####### MINGW64 //wsl$/Ubuntu/home/####### $ /c/Users/#######/AppData/Roaming/npm/node_modules/cypress/bin/cypress open --config-file=../cypress.json
Found binary version 9.7.0 installed in: C:\Users\#######\AppData\Local\Cypress\Cache\10.11.0\Cypress

‼ Warning: Binary version 9.7.0 does not match the expected package version 10.11.0

  These versions may not work properly together.


'\\wsl$\Ubuntu\######\tests\end-to-end-tests\cypress'
CMD.EXE was started with the above path as the current directory. 
UNC paths are not supported. Defaulting to Windows directory.
Error: EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu/home/########/end-to-end-tests/cypress.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at createFsWatchInstance (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:629:21)
    at C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:445:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -4068,
  syscall: 'watch',
  code: 'EISDIR',
  path: '//wsl$/Ubuntu/home/######/tests/end-to-end-tests/cypress.json',
  filename: '//wsl$/Ubuntu/home/######/tests/end-to-end-tests/cypress.json'
}
Error: EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu/home/######/tests/end-to-end-tests/cypress.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at createFsWatchInstance (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:629:21)
    at C:\Users\######\AppData\Local\Cypress\Cache\10.11.0\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:445:21
    at Function.all (<anonymous>:null:null)

```

I tried to disable watch with `"watchForFileChanges": false` but did not work

I have Windows 10 but Windows 11 apparently can run GUI with WSLg
https://github.com/microsoft/wslg
https://stackoverflow.com/questions/69621197/running-cypress-on-wsl
