### ISSUE TITLE
cy.session() results in Type Error "Cannot read properties of undefined (reading 'id')" for second call

### ISSUE THREAD

**Issue by k9ert** [cypress-io/cypress#21138]
### Current behavior

In order to make this reproducible I've created the simplest test using the session functionality (see below).

So the first Run of this test suceeds but the second does not:
First Run:
![image](https://user-images.githubusercontent.com/117085/164084691-5d21936d-0d81-4382-83fa-d250db954442.png)
Second Run:
![image](https://user-images.githubusercontent.com/117085/164084609-6177b357-379b-4e67-8242-62caf555c685.png)

Stack-trace in textform:
```
    at Context.session (http://localhost:25444/__cypress/runner/cypress_runner.js:161851:38)
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:172123:16)
From previous event:
    at CommandQueue.runCommand (http://localhost:25444/__cypress/runner/cypress_runner.js:172102:9)
    at next (http://localhost:25444/__cypress/runner/cypress_runner.js:172245:20)
From previous event:
    at next (http://localhost:25444/__cypress/runner/cypress_runner.js:172245:40)
From previous event:
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:186675:78)
From previous event:
    at CommandQueue.run (http://localhost:25444/__cypress/runner/cypress_runner.js:186670:22)
    at CommandQueue.run (http://localhost:25444/__cypress/runner/cypress_runner.js:172308:16)
    at $Cy.cy.<computed> [as viewport] (http://localhost:25444/__cypress/runner/cypress_runner.js:173306:19)
    at Context.runnable.fn (http://localhost:25444/__cypress/runner/cypress_runner.js:173524:20)
    at callFn (http://localhost:25444/__cypress/runner/cypress_runner.js:125614:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:25444/__cypress/runner/cypress_runner.js:125601:8)
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:180445:31)
From previous event:
    at Object.onRunnableRun (http://localhost:25444/__cypress/runner/cypress_runner.js:180430:20)
    at $Cypress.action (http://localhost:25444/__cypress/runner/cypress_runner.js:169793:29)
    at Test.Runnable.run (http://localhost:25444/__cypress/runner/cypress_runner.js:178107:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:25444/__cypress/runner/cypress_runner.js:126273:11)
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:126399:13)
    at next (http://localhost:25444/__cypress/runner/cypress_runner.js:126182:15)
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:126192:8)
    at next (http://localhost:25444/__cypress/runner/cypress_runner.js:126094:15)
    at <unknown> (http://localhost:25444/__cypress/runner/cypress_runner.js:126160:6)
    at timeslice (http://localhost:25444/__cypress/runner/cypress_runner.js:120086:28)
```

### Desired behavior

The second run should be successful as well.

### Test code to reproduce

```js
describe('Test the session feature', () => {
    it('Session Login', () => {
        Cypress.config('experimentalSessionSupport',true)
        cy.viewport(1200,660)
        cy.visit('/')
        cy.session(["user1", "password1"], () => {
            cy.visit('/')
            cy.url().should('contain', '/welcome/about')
        },
        {
            validate() {
                cy.visit("/welcome/about")
                cy.url().should('contain', '/welcome/about')
            }
        }
        )        
        
    })
})
```

### Cypress Version

9.5.4

**Comment by emilyrohrbough** [comment]
@k9ert Can you clarify what you mean by the "second run" that you've referenced in the issue?

**Comment by k9ert** [comment]
Second run means, that i'm clicking on the "Run all tests" button on the right.
![image](https://user-images.githubusercontent.com/117085/166644915-5b84c089-4dff-4346-8e5e-226c5d99bd6a.png)

**Comment by emilyrohrbough** [comment]
@k9ert are you still experiencing this issue? I was unable to reproduce.

**Comment by k9ert** [comment]
I'm currently not able to verify this. So let's assume it working now and i'm happy to reopen this issue if it's happening again!
