### ISSUE TITLE
Missing error when trying to make assertion on a non-stub

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2122]
Test that makes a BDD assertion on a non-stub does NOT fail

```js
expect(42).to.have.been.calledOnce
```

But it throws an error that you can see if you have your devtools open

```
Unhandled rejection TypeError: 42 is not a spy or a call to a spy!
    at assertCanWorkWith (http://localhost:52463/__cypress/runner/cypress_runner.js:57:19)
    at Assertion.<anonymous> (http://localhost:52463/__cypress/runner/cypress_runner.js:96:13)
    at Assertion.addProperty (http://localhost:52463/__cypress/runner/cypress_runner.js:11846:29)
```

<img width="1274" alt="screen shot 2018-07-10 at 11 24 46 pm" src="https://user-images.githubusercontent.com/2212006/42538536-7c524ff8-8498-11e8-8d31-201d516ad7b6.png">

**Comment by jennifer-shehane** [comment]
This now errors in the Command Log in Cypress version 3.4.0

<img width="487" alt="Screen Shot 2019-07-12 at 12 18 27 PM" src="https://user-images.githubusercontent.com/1271364/61105214-348e3100-a49f-11e9-943c-2eac69dd1d74.png">
