### ISSUE TITLE
Test runner crashes on url parsing

### ISSUE THREAD

**Issue by bahrb** [cypress-io/cypress#2128]
### Current behavior:

Test runner crashes on url parsing:
>TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:102:11)
    at urlParse (url.js:96:5)
    at Url.resolve (url.js:657:29)
    at Object.urlResolve [as resolve] (url.js:653:40)
    at Request.options.followRedirect (request.js:327:30)
    at Redirect.onResponse (redirect.js:84:42)
    at Request.onRequestResponse (request.js:989:22)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

### Desired behavior:

I don't understand why url is undefinied in my case, maybe somebody can give me a hint. 
However, test runner should log the problem without quitting itself.

### Steps to reproduce:

I'm trying to make a POST request with digest authentication in a before method. The intention is to setup the test state programmatically via our own http-api. I don't call cy.visit before, this is the first request that happens:

> const opts: Partial<Cypress.RequestOptions> = 
{
		url: "http://localhost:8080/myressource",
		auth: {user: "admin", pass: "admin", sendImmediately: false},
		method: "POST",
		body: {},
		followRedirect: true,
		failOnStatusCode: false
};
	cy.request(opts);

cypress.json does not contain base-url:
> {
  "projectId": "pixq6e",
  "defaultCommandTimeout": 60000,
  "viewportWidth": 1024,
  "viewportHeight": 768,
  "requestTimeout": 60000,
  "responseTimeout": 60000,
  "watchForFileChanges": false
}

### Versions
Cypress: 3.0.2
Typescript: 2.9.2
Node: 8.11.2

**Comment by jennifer-shehane** [comment]
The test runner should definitely not crash in this situation. 

However, I ran the code you pasted above with the exact Cypress, TypeScript and Node version - also with exact `cypress.json` and did not run into *any* errors (using another url obviously). 

**my code**
```ts
it('requests without crashing', () => {
  const opts: Partial<Cypress.RequestOptions> =
  {
    url: "https://jsonplaceholder.typicode.com/comments",
    auth: { user: "admin", pass: "admin", sendImmediately: false },
    method: "POST",
    body: {},
    followRedirect: true,
    failOnStatusCode: false
  };
  cy.request(opts);
})
```

**the result**
![screen shot 2018-07-11 at 10 13 16 am](https://user-images.githubusercontent.com/1271364/42577970-8702585c-84f3-11e8-99fa-5f1353417ea6.png)

We'll need a reproducible example in order to begin debugging your issue. Is there any information that was not provided? 
- Other tests running together with this? 
- `before`/`after` hooks? 
- Any setup in your `plugins` file?
- Operating system version & Browser version?

**Comment by bahrb** [comment]
Should be reproduceable with the following request:
> const opts: Partial<Cypress.RequestOptions> = 
{
		url: "http://postman-echo.com/digest-auth",
		auth: {user: "postman", pass: "password", sendImmediately: false},
		method: "GET",
		body: {},
		followRedirect: true,
		failOnStatusCode: false
	};
	return cy.request(opts);

- Other tests running together with this? **NO**
- before/after hooks? **NO**
- Any setup in your plugins file? **NO**
- Operating system version & Browser version? **Kubuntu 18.04 x64 & Chromium 66.0.3359.181**

**Comment by jennifer-shehane** [comment]
Great! I do have it crashing with the example you posted. 

**Simplified case that causes crash**
```js
it('crashes when request is made', () => {
  cy.request({
    url: 'http://postman-echo.com/digest-auth',
    auth: { user: 'postman', pass: 'password', sendImmediately: false },
  })
})
```

**Debug logs during `cypress open`**
```bash
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:102:11)
    at urlParse (url.js:96:5)
    at Url.resolve (url.js:657:29)
    at Object.urlResolve [as resolve] (url.js:653:40)
    at Request.options.followRedirect (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/request.js:327:30)
    at Redirect.onResponse (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/lib/redirect.js:84:42)
    at Request.onRequestResponse (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:989:22)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:102:11)
    at urlParse (url.js:96:5)
    at Url.resolve (url.js:657:29)
    at Object.urlResolve [as resolve] (url.js:653:40)
    at Request.options.followRedirect (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/request.js:327:30)
    at Redirect.onResponse (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/lib/redirect.js:84:42)
    at Request.onRequestResponse (/Users/jennifer/Library/Caches/Cypress/3.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:989:22)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

  cypress:server:browsers killing browser process +2ms
```

**Comment by AnderssonChristian** [comment]
@jennifer-shehane This bug is still present. Is there any fix for this on the horizon?

@bahrb Did you find any workaround, perhaps?

**Comment by bahrb** [comment]
@AnderssonChristian finally we wrote our tests with cy.visit but I came across this issue when we started with cypress and did some research how to use it.

**Comment by rjfranco** [comment]
I can confirm this error is still persisting on Cypress 3.4.0 / node 11

**Comment by gabbersepp** [comment]
is the code in the involved libs (request.js/redirect.js) cypress stuff or from node?

**Comment by bahrb** [comment]
The `TypeError: Parameter "url" must be a string, not undefined` indeed comes from the node module _node-url_ but the problem must originate from within the cypress code because a url was provided in the crashing example.

**Comment by gabbersepp** [comment]
The exception could be solved by adding `followRedirect: false` as option to the request:

![image](https://user-images.githubusercontent.com/3234900/68104596-fb5d4f00-fedb-11e9-817a-afe9dd1cf001.png)

I'm not sure why it tries to follow a redirect here. But this could be fixed I think.
The next question is: Where should the logic for the necesary subsequent request be placed? This question might go to @jennifer-shehane

**Comment by jennifer-shehane** [comment]
This is still an issue in Cypress 8.6.0.
