### ISSUE TITLE
ENOTDIR when trying to install on Ubuntu 22.04 WSL2 

### ISSUE THREAD

**Issue by JoeyMckenzie** [cypress-io/cypress#21508]
### Current behavior

Hi,

I'm trying to install cypress on WSL2 Ubuntu 22.04 and am running into an ENOTDIR error during installation. I'm pretty stumped as to why exactly I'm receiving the ENOTDIR error, and have installed different versions of node wondering if it may be an Ubuntu 22.04/node/cypress incompatibility error, but have been unsuccessful so far. Cypress seems to get halfway through the installation, then fails with a ENOTDIR error from spawn.

Has anyone had a similar issue? I manage my node and npm versions with nvm, not sure if that would affect the installation of cypress. I'm migrating from WSL2 Ubuntu 20.04 and had no issues installing cypress, with only now being an issue on 22.04.

### Debug logs

```
npm ERR! code 1
npm ERR! path /home/joeym/projects/test/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! Installing Cypress (version: 9.6.1)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! [TITLE]  Downloading Cypress      0% 0s
npm ERR! [TITLE]  Downloading Cypress      2% 10s
npm ERR! [TITLE]  Downloading Cypress      3% 10s
npm ERR! [TITLE]  Downloading Cypress      4% 10s
npm ERR! [TITLE]  Downloading Cypress      6% 8s
npm ERR! [TITLE]  Downloading Cypress      7% 8s
npm ERR! [TITLE]  Downloading Cypress      9% 7s
npm ERR! [TITLE]  Downloading Cypress      11% 6s
npm ERR! [TITLE]  Downloading Cypress      13% 6s
npm ERR! [TITLE]  Downloading Cypress      15% 6s
npm ERR! [TITLE]  Downloading Cypress      17% 5s
npm ERR! [TITLE]  Downloading Cypress      18% 5s
npm ERR! [TITLE]  Downloading Cypress      18% 6s
npm ERR! [TITLE]  Downloading Cypress      21% 5s
npm ERR! [TITLE]  Downloading Cypress      23% 5s
npm ERR! [TITLE]  Downloading Cypress      25% 5s
npm ERR! [TITLE]  Downloading Cypress      26% 5s
npm ERR! [TITLE]  Downloading Cypress      28% 5s
npm ERR! [TITLE]  Downloading Cypress      30% 4s
npm ERR! [TITLE]  Downloading Cypress      32% 4s
npm ERR! [TITLE]  Downloading Cypress      33% 4s
npm ERR! [TITLE]  Downloading Cypress      35% 4s
npm ERR! [TITLE]  Downloading Cypress      37% 4s
npm ERR! [TITLE]  Downloading Cypress      39% 4s
npm ERR! [TITLE]  Downloading Cypress      41% 4s
npm ERR! [TITLE]  Downloading Cypress      42% 4s
npm ERR! [TITLE]  Downloading Cypress      44% 3s
npm ERR! [TITLE]  Downloading Cypress      46% 3s
npm ERR! [TITLE]  Downloading Cypress      47% 3s
npm ERR! [TITLE]  Downloading Cypress      49% 3s
npm ERR! [TITLE]  Downloading Cypress      51% 3s
npm ERR! [TITLE]  Downloading Cypress      53% 3s
npm ERR! [TITLE]  Downloading Cypress      56% 3s
npm ERR! [TITLE]  Downloading Cypress      58% 2s
npm ERR! [TITLE]  Downloading Cypress      59% 2s
npm ERR! [TITLE]  Downloading Cypress      61% 2s
npm ERR! [TITLE]  Downloading Cypress      62% 2s
npm ERR! [TITLE]  Downloading Cypress      63% 2s
npm ERR! [TITLE]  Downloading Cypress      65% 2s
npm ERR! [TITLE]  Downloading Cypress      67% 2s
npm ERR! [TITLE]  Downloading Cypress      69% 2s
npm ERR! [TITLE]  Downloading Cypress      71% 2s
npm ERR! [TITLE]  Downloading Cypress      73% 2s
npm ERR! [TITLE]  Downloading Cypress      74% 2s
npm ERR! [TITLE]  Downloading Cypress      76% 1s
npm ERR! [TITLE]  Downloading Cypress      79% 1s
npm ERR! [TITLE]  Downloading Cypress      81% 1s
npm ERR! [TITLE]  Downloading Cypress      83% 1s
npm ERR! [TITLE]  Downloading Cypress      85% 1s
npm ERR! [TITLE]  Downloading Cypress      87% 1s
npm ERR! [TITLE]  Downloading Cypress      89% 1s
npm ERR! [TITLE]  Downloading Cypress      91% 1s
npm ERR! [TITLE]  Downloading Cypress      93% 0s
npm ERR! [TITLE]  Downloading Cypress      95% 0s
npm ERR! [TITLE]  Downloading Cypress      97% 0s
npm ERR! [TITLE]  Downloading Cypress      99% 0s
npm ERR! [TITLE]  Downloading Cypress      100% 0s
npm ERR! [TITLE]  Downloaded Cypress
npm ERR! [SUCCESS]  Downloaded Cypress
npm ERR! [STARTED] Task without title.
npm ERR! 2022-05-16T06:03:21.739Z cypress:cli installing Cypress from NPM
npm ERR! 2022-05-16T06:03:21.933Z cypress:cli installing with options {}
npm ERR! 2022-05-16T06:03:21.933Z cypress:cli version in package.json is 9.6.1, version to install is 9.6.1
npm ERR! 2022-05-16T06:03:21.947Z cypress:cli Reading binary package.json from: /home/joeym/.cache/Cypress/9.6.1/Cypress/resources/app/package.json
npm ERR! 2022-05-16T06:03:21.952Z cypress:cli no binary installed under cli version
npm ERR! 2022-05-16T06:03:21.953Z cypress:cli checking local file /home/joeym/projects/test/9.6.1 cwd /home/joeym/projects/test/node_modules/cypress
npm ERR! 2022-05-16T06:03:21.953Z cypress:cli preparing to download and unzip version  9.6.1 to path /home/joeym/.cache/Cypress/9.6.1
npm ERR! 2022-05-16T06:03:21.960Z cypress:cli needed Cypress version: 9.6.1
npm ERR! 2022-05-16T06:03:21.960Z cypress:cli source url https://download.cypress.io/desktop/9.6.1?platform=linux&arch=x64
npm ERR! 2022-05-16T06:03:21.960Z cypress:cli downloading cypress.zip to "/tmp/cypress-15921.zip"
npm ERR! 2022-05-16T06:03:21.963Z cypress:cli Downloading package {
npm ERR!   url: 'https://download.cypress.io/desktop/9.6.1?platform=linux&arch=x64',
npm ERR!   proxy: null,
npm ERR!   downloadDestination: '/tmp/cypress-15921.zip'
npm ERR! }
npm ERR! 2022-05-16T06:03:22.426Z cypress:cli expected file size 80
npm ERR! 2022-05-16T06:03:22.426Z cypress:cli redirect version: 9.6.1
npm ERR! 2022-05-16T06:03:22.426Z cypress:cli redirect url: https://cdn.cypress.io/desktop/9.6.1/linux-x64/cypress.zip
npm ERR! 2022-05-16T06:03:22.427Z cypress:cli Downloading package {
npm ERR!   url: 'https://cdn.cypress.io/desktop/9.6.1/linux-x64/cypress.zip',
npm ERR!   proxy: null,
npm ERR!   downloadDestination: '/tmp/cypress-15921.zip'
npm ERR! }
npm ERR! 2022-05-16T06:03:22.550Z cypress:cli expected checksum 3d13f73189d8aefbc731677ce33df253587c5f6e1c06b7ae75a309f34e6ae1d5e0c4ef7ccf7581d5d733a1733fc59ef9eaad9f02b38da7836e6b1fc07759e457
npm ERR! 2022-05-16T06:03:22.550Z cypress:cli expected file size 184960256
npm ERR! 2022-05-16T06:03:28.252Z cypress:cli downloading finished
npm ERR! 2022-05-16T06:03:28.253Z cypress:cli verifying checksum and file size
npm ERR! 2022-05-16T06:03:29.285Z cypress:cli downloaded file has the expected checksum and size ✅
npm ERR! 2022-05-16T06:03:29.285Z cypress:cli verified
npm ERR! 2022-05-16T06:03:29.286Z cypress:cli finished downloading file: /tmp/cypress-15921.zip
npm ERR! 2022-05-16T06:03:29.288Z cypress:cli:unzip removing existing unzipped binary /home/joeym/.cache/Cypress/9.6.1
npm ERR! 2022-05-16T06:03:29.290Z cypress:cli:unzip unzipping from /tmp/cypress-15921.zip
npm ERR! 2022-05-16T06:03:29.290Z cypress:cli:unzip into /home/joeym/.cache/Cypress/9.6.1
npm ERR! 2022-05-16T06:03:29.295Z cypress:cli:unzip zipFile entries count 25923
npm ERR! 2022-05-16T06:03:29.295Z cypress:cli:unzip unzipping via `unzip`
npm ERR! node:internal/child_process:413
npm ERR!     throw errnoException(err, 'spawn');
npm ERR!     ^
npm ERR!
npm ERR! Error: spawn ENOTDIR
npm ERR!     at ChildProcess.spawn (node:internal/child_process:413:11)
npm ERR!     at Object.spawn (node:child_process:700:9)
npm ERR!     at unzipWithUnzipTool (/home/joeym/projects/test/node_modules/cypress/lib/tasks/unzip.js:102:25)
npm ERR!     at /home/joeym/projects/test/node_modules/cypress/lib/tasks/unzip.js:173:20
npm ERR!     at /home/joeym/projects/test/node_modules/yauzl/index.js:37:7
npm ERR!     at /home/joeym/projects/test/node_modules/yauzl/index.js:141:16
npm ERR!     at /home/joeym/projects/test/node_modules/yauzl/index.js:631:5
npm ERR!     at /home/joeym/projects/test/node_modules/fd-slicer/index.js:32:7
npm ERR!     at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5) {
npm ERR!   errno: -20,
npm ERR!   code: 'ENOTDIR',
npm ERR!   syscall: 'spawn'
npm ERR! }```

### Cypress Version

9.6.1

### Package Manager

npm

### Operating system

Linux

### Other

_No response_

**Comment by JoeyMckenzie** [comment]
Following up on this, [unzip](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=unzip&searchon=names) wasn't installed on my image, a quick `sudo apt install unzip` solved the issue and I'm now able to install without issue.

It appears the unzip task [assumes an unzip installation](https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/unzip.js#L102), it would be nice to have some sort of warning ahead of time to let an installing user know if they had the tool installed. Not sure if that's doable, but hopefully if someone stumbles across this issue, the aforementioned fix worked for me.
