### ISSUE TITLE
Cypress not running on networked WSL drive

### ISSUE THREAD

**Issue by jarrodpan** [cypress-io/cypress#21530]
### Current behavior

Running Cypress on windows and trying to load a project via a networked WSL drive causes an EISDIR error on `cypress.json` and the directory itself.

```bash
Error: EISDIR: illegal operation on a directory, watch '//wsl.localhost/Ubuntu/home/[user]/[project]/cypress.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2237:34)
    at createFsWatchInstance (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:629:21)
    at D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:445:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -4068,
  syscall: 'watch',
  code: 'EISDIR',
  path: '//wsl.localhost/Ubuntu/home/[user]/[project]/cypress.json',
  filename: '//wsl.localhost/Ubuntu/home/[user]/[project]/cypress.json'
}
```

```bash
Error: EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu/home/[user]/[project]/cypress.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2237:34)
    at createFsWatchInstance (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:629:21)
    at D:\Users\[user]\Cypress\resources\app\packages\server\node_modules\chokidar\index.js:445:21
    at Function.all (<anonymous>:null:null)
 {
  errno: -4068,
  syscall: 'watch',
  code: 'EISDIR',
  path: '//wsl$/Ubuntu/home/[user]/[project]/cypress.json',
  filename: '//wsl$/Ubuntu/home/[user]/[project]/cypress.json'
}
```

Using a mounted letter drive causes the same issue.

I do not have Xvfb as my company has not loaded it on the image so running Cypress in WSL is not an option as of now. Happy to use workarounds.

Windows 10 2H20 with Ubuntu 20.04 on WSL2.

### Desired behavior

Cypress should list the tests and work normally.

### Test code to reproduce

Clone test repo into WSL, download Cypress on host Windows machine, extract, run exe from the command line and select the networked project folder.

### Cypress Version

9.6.0

### Other

Reproduced with Cypress 9.6.1 on Windows 11 Dev, using WSL2 Ubuntu 18.04.2 LTS.

**Comment by jarrodpan** [comment]
This may be unfixable as it's a documented limitation of `fs` which is what `chokidar` uses at [(line 119)](https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L119) to watch the file where the error is thrown.

> If the underlying functionality is not available for some reason, then fs.watch() will not be able to function and may throw an exception. For example, **watching files or directories can be unreliable, and in some cases impossible, on network file systems (NFS, SMB, etc)** or host file systems when using virtualization software such as Vagrant or Docker.

https://nodejs.org/docs/latest/api/fs.html#availability

**Comment by mjhenkes** [comment]
@jarrodpan, thank you for the research. It sounds like this is a limitation with node and unfortunately outside of our control.

**Comment by jarrodpan** [comment]
@mjhenkes Did a bit more digging and found the following:
- Node has a fallback method [`fs.watchFile()`](https://nodejs.org/docs/latest/api/fs.html#fswatchfilefilename-options-listener) which works on network file systems
- Chokidar's `watch()` method [has an option `usePolling: true`](https://github.com/paulmillr/chokidar#performance) which is required for network file systems
- This can be forced with setting an environment variable `CHOKIDAR_USEPOLLING=1`

I've opened #21622 to fix this issue.

**Comment by mjhenkes** [comment]
With 10.0 we will have added more watchers so this issue is related: https://github.com/cypress-io/cypress/issues/22013

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by MichaelPote** [comment]
This is still an issue, @jarrodpan it would be good if you could get that pull request going again?

**Comment by BenHarris** [comment]
This is still an issue with `v12.7.0`. Tried with WSL path and mounted via a drive.

`EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu-20.04/home/ben/test-project/.git/HEAD`

Stack trace
```
Error: EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu-20.04/home/ben/test-project/.git/HEAD'
    at FSWatcher. (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at J (:4692:68918)
    at $ (:4692:69191)
    at s.exports._watchWithNodeFs (:4692:71161)
    at s.exports._handleFile (:4692:71989)
    at s.exports._addToNodeFs (:4692:75918)
    at async :4692:92431
    at async Promise.all (index 0)
```
