### ISSUE TITLE
Cypress returns Parse Error for unknown reason

### ISSUE THREAD

**Issue by timeisenhuth** [cypress-io/cypress#2171]
- Operating System: macOS 10.13.4
- Cypress Version: 3.0.1 and 2.0.1
- Browser Version: Google Chrome 67

Making a `POST` request to an API endpoint intermittently fails with an unknown "Parse" error and it's impossible to determine why. The server does not show any failed request and manually running the same request works fine / as expected. Stack trace is below. This question was posted on Cypress glitter chat but to date had no response.

Just wondering how we can get more info as to why this error is occuring? Its happening on our build environment (CircleCI) and also on my local machine. This seems to have started when switching to a new NGINX server config but again don't have enough information as to why this is now occurring.

Again, this is intermittent, doesn't happen every time. Also most other API requests are fine.

**Stack trace**:

```
CypressError: cy.request() failed trying to load:

http://localhost:3000/api/user/login

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Parse Error

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:3000/api/user/login

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: Parse Error
    at new RequestError (/Users/timeisenhuth/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/timeisenhuth/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/timeisenhuth/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/timeisenhuth/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/Users/timeisenhuth/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:845:8)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketOnData (_http_client.js:459:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
```

**Comment by timeisenhuth** [comment]
So it appears that this was an issue between our new Nginx config and our client proxy - It was passing through the `transfer-encoding:chunked` header but wasn't properly handling response as chunked.
