### ISSUE TITLE
Cypress v10 crashes with EPERM error

### ISSUE THREAD

**Issue by far11ven** [cypress-io/cypress#22002]
### Current behavior

currently on cypress v10 on running tests in hedless or Test Runner, the cypress crashes with following error after an unknown amount of time with following error:

```

────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  Login.feature                                                                 (25 of 75)
  Estimated: 0 seconds
EPERM: operation not permitted, watch 'D:\omnius-qa-automation\.git\index.lock'
Error: EPERM: operation not permitted, watch 'D:\omnius-qa-automation\.git\index.lock'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at createFsWatchInstance (C:\Users\QCuser\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-015e948d\Cypress\resources\app\packages\data-context\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (C:\Users\QCuser\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-015e948d\Cypress\resources\app\packages\data-context\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (C:\Users\QCuser\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-015e948d\Cypress\resources\app\packages\data-context\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (C:\Users\QCuser\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-015e948d\Cypress\resources\app\packages\data-context\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (C:\Users\QCuser\AppData\Local\Cypress\Cache\beta-10.0.0-10.0-release-015e948d\Cypress\resources\app\packages\data-context\node_modules\chokidar\lib\nodefs-handler.js:629:21)

Unhandled rejection Error: ERR_FAILED (-2) loading 'https://doc-ai-qa.internal.omnius.com/__/#/specs/runner?file=cypress\e2e\features\API\Shield\Login.feature'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
```

### Desired behavior

Not crash and work properly

### Test code to reproduce

NA

### Cypress Version

10.0.0

### Other

Environment: Windows

**Comment by jennifer-shehane** [comment]
@far11ven Thanks for reporting this. We're investigating. Sorry for the inconvenience. This should have been fixed previously as part of https://github.com/cypress-io/cypress/pull/21600 and https://github.com/cypress-io/cypress/pull/21659

**Comment by jennifer-shehane** [comment]
@far11ven Had you previously downloaded a pre-release binary of Cypress recently? Could you try clearing your cache if that is the case and retrying? `cypress cache clear`
