### ISSUE TITLE
Version 10: Your configFile is invalid cypress.config.ts

### ISSUE THREAD

**Issue by sitefinitysteve** [cypress-io/cypress#22004]
### Current behavior

I can't get by this screen after the cypress UI pops up, everything seemed fine until the config->.ts step.

![image](https://user-images.githubusercontent.com/1542376/171471142-289b7e66-3f17-40d3-8f5a-20561e20a27f.png)

```
Error
Your configFile is invalid: C:\Github\Project\cypress.config.ts

It threw an error when required, check the stack trace below:

[Stack trace](http://localhost:22331/__launchpad/index.html#)
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1033:11)
    at defaultResolve (node:internal/modules/esm/resolve:1103:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1042:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at loadFile (C:\Users\steve\AppData\Local\Cypress\Cache\10.0.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:126:9)
    at EventEmitter. (C:\Users\steve\AppData\Local\Cypress\Cache\10.0.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:136:38)
    at EventEmitter.emit (node:events:520:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (C:\Users\steve\AppData\Local\Cypress\Cache\10.0.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:520:28)
```

```js
import { defineConfig } from 'cypress'

export default defineConfig({
  projectId: 'nqoyvw',
  viewportWidth: 1480,
  viewportHeight: 1260,
  video: false,
  videosFolder: 'cypress/videos',
  screenshotsFolder: 'cypress/screenshots',
  pageLoadTimeout: 60000,
  requestTimeout: 45000,
  responseTimeout: 45000,
  experimentalStudio: true,
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config)
    },
    baseUrl: 'https://dev.project.ca',
    specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
  },
})
```

### Cypress Version

10

### Package Manager

npm

### Operating system

Windows

### Other

Node: v16.14.0
tsc: Version 4.0.2

**Comment by sitefinitysteve** [comment]
```
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "@types/node": "^10.17.50",
    "cypress": "^10.0.0",
    "cypress-wait-until": "^1.7.1",
    "har-validator": "^5.1.5"
  },
  "dependencies": {
    "@types/angular": "^1.6.51",
    "@types/bootstrap": "^3.4.0",
    "@types/jquery": "^2.0.56",
    "watchify": "^3.11.1"
  },
  "scripts": {
    "cypress": "cypress open",
    "macdot-watchify": "watchify Project\\Mvc\\Views\\MacdotTool\\Resources\\MacdotTool-ng.js -o Project\\Mvc\\Views\\MacdotTool\\Resources\\MacdotTool-ng.min.js",
    "record": "cypress run --record --key 46f05570-9bb9-47d1-9dc1-d6c9d67cb0b4"
  }
}
```

I don't have a tsconfig, don't use typescript in the project, I have a tsconfig.json.ignore from back when I did, but that's clearly nothing

```
{
	"compileOnSave": true,
    "compilerOptions": {
		"lib": ["es2015", "es2015.iterable", "dom"],
		"target": "es6",
		"module": "commonjs",
        "noEmitOnError": true,
		"watch": true,
		"skipLibCheck": true
    },
	"exclude": [
		"./node_modules/@types/*",
		"./node_modules/@types/bluebird/index.d.ts",
		"./node_modules/@types/bluebird/*",
		"./node_modules/@types/jquery/*"
	]
}
```

**Comment by sitefinitysteve** [comment]
If you need typescript added to the project, and you think that'd fix it... I'm cool with that btw, I just don't use it for anything

**Comment by jennifer-shehane** [comment]
@sitefinitysteve It should not error in this case for you. We have some logic to detect a TypeScript project and it may be a bit loose in your case where we're not detecting correctly.

**Comment by rockhold** [comment]
'experimentalStudio' can be safely removed from your config. For more info, check out this discussion: https://github.com/cypress-io/cypress/discussions/21561

**Comment by tgriesser** [comment]
Sorry, should have also said to change `export default` to `module.exports = `

**Comment by qntm** [comment]
I'm having exactly the same issue except I'm not using TypeScript at all.

**Comment by qntm** [comment]
I tried that and it did not fix the problem unfortunately. I think this problem occurs on Windows when the package in question has `"type": "module"`. We can see in the stack trace that it's saying `ERR_UNSUPPORTED_ESM_URL_SCHEME` implying that we're attempting to load an ES module, but the path needs to start with `file://` on Windows, when in fact it is `C:\Github\Project\cypress.config.ts`.

**Comment by lmiller1990** [comment]
You can see the algorithm for detecting TS here: https://github.com/cypress-io/cypress/blob/369a865237df4388c6421d5eae7ed948dd606606/packages/scaffold-config/src/detect.ts#L106

If anyone is having this (or a similar issue) please run with `DEBUG=cypress:scaffold-config:detect yarn cypress open`. This should give additional debugging in the terminal, and tell us exactly **why** TS is getting detected. You could then include this output in your bug report.

**Comment by wakaztahir** [comment]
I am getting this error, I 

When I don't specify `"type" : "module"` in my package.json
```
Your configFile is invalid: D:\Programming\Web\RtEdit\packages\lib\cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for D:\Programming\Web\RtEdit\packages\lib\cypress.config.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async loadFile (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:106:14)    
    at async EventEmitter.<anonymous> (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:32)
```

When I specify `"type":"module"` in my `package.json`
```
C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\util.js:62
    return value.replace(backslashRegExp, directorySeparator);
                 ^

TypeError: value.replace is not a function
    at normalizeSlashes (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\util.js:62:18)
    at Object.getExtendsConfigPath (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\ts-internals.js:24:54)
    at readConfig (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\configuration.js:127:64)
    at findAndReadConfig (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\configuration.js:50:84)
    at create (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\index.js:146:69)
    at register (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\index.js:127:19)
    at Object.registerAndCreateEsmHooks (C:\Users\wakaz\AppData\Local\Cypress\Cache\12.17.2\Cypress\resources\app\node_modules\ts-node\dist\esm.js:25:49)
    at file:///C:/Users/wakaz/AppData/Local/Cypress/Cache/12.17.2/Cypress/resources/app/node_modules/ts-node/esm/transpile-only.mjs:8:7
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

**Comment by corgoss** [comment]
In my case i remove from tsconfig.json "allowImportingTsExtensions": true and cypress is working normally.

**Comment by narendram224** [comment]
I have facing the same issue in **next js 14.**

I have changed the file extension to mjs. and it will solve my problem.

`cypress.config.mjs`

<img width="262" alt="Screenshot 2024-09-16 at 4 55 09 PM" src="https://github.com/user-attachments/assets/b9f49737-aa36-4593-a627-7cc8595a66a0">

<img width="1509" alt="Screenshot 2024-09-16 at 4 56 25 PM" src="https://github.com/user-attachments/assets/e2cf8306-466c-44b2-88d5-e12e9e70eef8">
