### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module during Cypress upgrade to the v10.0.1

### ISSUE THREAD

**Issue by woytekn** [cypress-io/cypress#22038]
### Current behavior

When I try to upgrade Cypress to v10.0.1 I get "SyntaxError: Cannot use import statement outside a module"

```
Your configFile is invalid: /Users/xxx/Documents/Cypress/my_project/cypress.config.js

It threw an error when required, check the stack trace below:`

`/Users/xxx/Documents/Cypress/my_project/cypress.config.js:1
import { defineConfig } from "cypress";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (/Users/xxxi/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:103:14)
    at EventEmitter. (/Users/xxx/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:146:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (/Users/xxx/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
```
    
    
I've read that the solution for this issue is adding `  "type": "module"` in package.json but now I am getting another issue:
```
101 | 
  102 |     try {
> 103 |       return require(file)
      |              ^
  104 |     } catch (err) {
  105 |       originalError = err
  106 |       if (!err.stack.includes('[ERR_REQUIRE_ESM]') && !err.stack.includes('SyntaxError: Cannot use import statement outside a module')) {
  107 |         throw err
```
  
  `[Stack trace](http://localhost:55743/__launchpad/index.html#)
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xxx/Documents/Cypress/my_project/cypress.config.js from /Users/xxx/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js not supported.
Instead change the require of cypress.config.js in /Users/xxx/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js to a dynamic import() which is available in all CommonJS modules.
    at loadFile (/Users/xxx/Library/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:103:14)
    at EventEmitter. (/Users/xxxLibrary/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:146:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (/Users/xxxLibrary/Caches/Cypress/10.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)`
    
Do you have any ideas on how to solve it?

### Cypress Version

10.0.1

### Package Manager

npm

### Operating system

Mac

**Comment by lmiller1990** [comment]
Are you able to share your existing project? Ideally `package.json`, `cypress.json` and `cypress/plugins/index.js`.

If you could re-run the migration with `DEBUG=cypress*` and include the logs from the terminal, that would help, too!

It looks like it's incorrectly generating a ES modules based config; if you just want to make it work, you could change to using CJS:

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // your config content here, as generated by the migration tool
})
```

If you could share a slimmed down version of the repo you want to migrate, that'd be great - we can work through it and find out what's going wrong, so others can have a smooth migration process.

**Comment by lmiller1990** [comment]
For anyone at Cypress looking into this: 

We generate ES module based `cypress.config` if the project is using TypeScript or ES Modules: https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/migration/codegen.ts#L159. In this case, it's generating a `cypress.config.js`, so it's not a TS project, so `isProjectUsingESModules` must be `true`, which only happens if `"type": "module"` is set in `package.json` see here: https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/data/ProjectLifecycleManager.ts#L624-L626

**Comment by qntm** [comment]
I see an identical issue. I am using Node.js 18.2.0 and npm 8.9.0. On Windows, obviously, and using Git Bash for Windows. My minimal reproduction is as follows.

`package.json`:

```json
{
  "name": "what",
  "version": "1.0.0",
  "type": "module",
  "devDependencies": {
    "cypress": "^10.0.1"
  }
}
```

`cypress.config.js`:

```js
import { defineConfig } from 'cypress'

export default defineConfig({})
```

```sh
npm install
npx cypress run
```

```
Your configFile is invalid: C:\Users\qntm\what\cypress.config.js

It threw an error when required, check the stack trace below:

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\qntm\what\cypress.config.js from C:\Users\qntm\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js not supported.
Instead change the require of cypress.config.js in C:\Users\qntm\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js to a dynamic import() which is available in all CommonJS modules.
    at loadFile (C:\Users\qntm\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:103:14)
    at EventEmitter.<anonymous> (C:\Users\qntm\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:146:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (C:\Users\qntm\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
```

Note that here in your code:

https://github.com/cypress-io/cypress/blob/369a865237df4388c6421d5eae7ed948dd606606/packages/server/lib/plugins/child/run_require_async_child.js#L131

there is an error which is being discarded. I've found that the text of that error is:

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

In my case, the filename in question is `C:\Users\qntm\what\cypress.config.js`.

**Comment by maksim-romanov** [comment]
I have same problem too
