### ISSUE TITLE
Cypress10 in jenkins is giving Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.

### ISSUE THREAD

**Issue by MvRiele** [cypress-io/cypress#22040]
### Current behavior

Ran through the migration from 9.7.0 to 10.0.1 with the wizard. Running the tests locally in no problem (via cypress open or cypres run)
When i kick off the repository which has the tests in Jenkins (which uses cypress run), i keep getting the error 'Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.'

The file is there...

When i hardcode the path in cypress.config.ts, i get 'Your supportFile is missing or invalid: cypress\support\e2e.js
 The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).'

The only thing which is in the file, is 'import './commands';'

### Desired behavior

Cypress running in jenkins as 9.7.0 did

### Test code to reproduce

migrate to 10.0.1 and run in jenkins

### Cypress Version

10.0.1

**Comment by jennifer-shehane** [comment]
@MvRiele Can you include the contents of your `cypress.config.js` file? 

Also, I would assume that you checked the new `cypress\support\e2e.js` file into source control so that it's available on Jenkins. It seems there's some difference in the files from your local run and the Jenkins run - I really can't think of how there could be anything else in Cypress causing this. If you pass the same flags during `cypress run` locally it runs fine?

**Comment by MvRiele** [comment]
Yes i can see `e2e.js` in the correct folder on our buildserver.
The command used in jenkins to run the tests: `cypress run --config baseUrl=http://test:4200/ --env userName=xxx,passWord=yyy`
The command to run local (which works correctly): `cypress run --config baseUrl=http://test:4200/`

Also when i try the jenkins command locally it works correctly.

cypress.config.js:

```
import { defineConfig } from 'cypress';

export default defineConfig({
  chromeWebSecurity: false,
  defaultCommandTimeout: 20000,
  pageLoadTimeout: 30000,
  video: false,
  env: {
    domain: 'userDomain',
    userName: 'tst_user',
    passWord: 'test1234',
    layerNames: [
      'test123',
      '123test',
    ],
    newLayerName: 'NewLayerName',
  },
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config);
    },
    baseUrl: 'https://testUrl.com/',
    slowTestThreshold: 1000,
  },
});
```

**Comment by pedroNmelo** [comment]
The same thing happens to me but in my local machine even though people from my team sharing the same code got it running 
Moved from 9.7.0 to 10.0.2 Running on Windows 10
I already tried deleting local repository and reinstalling both NodeJS and Cypress
Tried setting the file's path in the config file and changing the directory altogether.

Here's our `cypress.config.js`:

```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
    defaultCommandTimeout: 60000,
    env: {
        auth_base_url: 'https://build.prod.cloud/auth',
        auth_realm: 'rtpo',
        auth_client_id: 'detection_client',
        auth_scope: 'openid detection_api profile',
    },
    projectId: 'xxxxxx',
    reporter: 'cypress-multi-reporters',
    reporterOptions: {
        configFile: 'reporter-config.json',
    },
    retries: 2,
    video: true,
    videoCompression: false,
    viewportWidth: 1920,
    viewportHeight: 1080,
    pageLoadTimeout: 100000,
    e2e: {
        // We've imported your old cypress plugins here.
        // You may want to clean this up later by importing these.
        setupNodeEvents(on, config) {
            return require('./cypress/plugins/index.js')(on, config)
        },
        baseUrl: 'https://build.prod.cloud',
        specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
    },
})
```

And the `Stack trace`:

```
Error: Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.

If a support file is not necessary for your project, set supportFile to false.

https://on.cypress.io/support-file-missing-or-invalid
    at setSupportFileAndFolder (C:\Users\usr\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\server\lib\config.js:339:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ProjectConfigManager.buildBaseFullConfig (C:\Users\usr\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:279:26)
    at ProjectConfigManager.getFullInitialConfig (C:\Users\usr\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:322:34)
    at ProjectConfigManager.setupNodeEvents (C:\Users\usr\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:119:28)
```

**Comment by mschile** [comment]
Thanks for the contents of the configuration file. I don't see anything abnormal in the config file. Can you provide the Cypress [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) as well.

**Comment by textbook** [comment]
I'm seeing the same error:

```
[e2e] Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.
[e2e] 
[e2e] If a support file is not necessary for your project, set supportFile to false.
[e2e] 
[e2e] https://on.cypress.io/support-file-missing-or-invalid
```

In my case I've _explicitly_ set the support file to a different path (`e2e/support/index.js`, which definitely exists):

```js
// cypress.config.js
const { defineConfig } = require("cypress");

defineConfig({
	e2e: {
		baseUrl: "http://localhost:3000",
		specPattern: "e2e/integration/**/*.test.js",
		supportFile: "e2e/support/index.js",
	},
	fixturesFolder: "e2e/fixtures",
	screenshotsFolder: "e2e/screenshots",
	video: false,
	videosFolder: "e2e/videos",
});
```
This happens on both macOS (my local machine) and Ubuntu 20.04 (GitHub Actions build environment, [example](https://github.com/textbook/starter-kit/runs/6738749433?check_suite_focus=true#step:5:101)) and in Node 14 and 16.

You can see the setup on a branch at: https://github.com/textbook/starter-kit/tree/cypress-10.

**Comment by mschile** [comment]
@textbook, I believe you are receiving the error because you are not exporting the configuration from `cypress.config.js`. Try changing:
```js
defineConfig({
```
to
```js
module.exports = defineConfig({
```

**Comment by madrian13** [comment]
@mschile 
I have same issue, just installed cypress 10.0.2, 1st install on this window 10 machine and it started with same error 

this is my config, created by Cypress

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});

**Comment by textbook** [comment]
@mschile oops yes that was it exactly, thank you!

**Comment by mschile** [comment]
@pedroNmelo, are you to compare your setup to your teams to figure out what is different? Do you have a project I could look at?

@madrian13, do you have a project I could look at? Can you provide the Cypress [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) as well.

**Comment by diogosantana2011** [comment]
Hi Team,

Seems I am encountering same issue with Jenkins failing to recognize the support file, although locally the spec I am running passes without any failures.

My config file is as per below:

cypress.config.js located in cypress/support/e2e.js

```const { defineConfig } = require("cypress")
const { initPlugin } = require('cypress-plugin-snapshots/plugin');
const allureWriter = require('@shelex/cypress-allure-plugin/writer');
const xlsx = require("node-xlsx").default;
const fs = require("fs");
const path = require("path");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message);
          return null;
        }
      });
    
      on('task', {
        parseXlsx({ filePath }) {
          return new Promise((resolve, reject) => {
          try {
            const jsonData = xlsx.parse(fs.readFileSync(filePath));
            resolve(jsonData);
          } catch (e) {
            reject(e);
          }
          });
        }
      });
    
      on('before:browser:launch', (browser = {}, launchOptions) => {
        const downloadDirectory = path.join(__dirname, '..', 'excelDownloads')
        
        if (browser.family === 'chromium') {
          launchOptions.preferences.default['download'] = { default_directory: downloadDirectory }
        }
        return launchOptions;
      });
    
      allureWriter(on, config);
      initPlugin(on, config);
    
      return config;
    },
    env: {
      // Environment variables 
    },
    specPattern: "cypress/e2e/**/*.{js,jsx,ts,tsx}",
    supportFile: "cypress/support/e2e.js",
    baseUrl: "https://api.marketplace.playtech.com",
    retries: 1,
    responseTimeout: 1000000,
    defaultCommandTimeout: 1000000,
    viewportHeight: 960,
    viewportWidth: 1536,
    excludeSpecPattern: ["**/__snapshots__/*", "**/__image_snapshots__/*"],
    reporter: "cypress-multi-reporters",
    reporterOptions: {
      reporterEnabled: "mochawesome,mocha-junit-reporter",
      mochawesomeReporterOptions: {
        reportDir: "cypress/results",
        quite: true,
        overwrite: false,
        html: false,
        json: true,
      },
      mochaJunitReporterReporterOptions: {
        mochaFile: "cypress/results/results-[hash].xml",
      }
    }
  }
});
```


When running my test locally via CLI with correct parameters, it passes however, when doing so on Jenkins VM which is running on Windows, below error is given:

![Screenshot 2022-06-06 at 10 40 15](https://user-images.githubusercontent.com/58599175/172128174-f840e681-0dc6-4f96-b8be-4bbfc7aab242.png)

```
10:24:03 
10:24:13 Your supportFile is missing or invalid: cypress\support\e2e.js
10:24:13 
10:24:13 The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).
10:24:13 
10:24:13 Fix your support file, or set supportFile to false if a support file is not necessary for your project.
10:24:13 
10:24:13 If you have just renamed the extension of your supportFile, restart Cypress.
10:24:13 
10:24:13 https://on.cypress.io/support-file-missing-or-invalid
```
Jenkins CLI:

<img width="960" alt="Screenshot 2022-06-06 at 10 41 41" src="https://user-images.githubusercontent.com/58599175/172128083-433ba616-d8e2-4983-be23-d99a36ed459c.png">

Not sure what else I can try to get it working, have been at it for 2 days and seems its just jenkins.

Any help would be appreciated. 

Let me know if I can provide any more information that can help!

Diogo Santana

**Comment by mschile** [comment]
@diogosantana2011, thanks for the additional report. Since your Jenkins VM is on Windows, I would expect the path separator to be `\` as displayed in the message. I've also been able to successfully load the support file locally on Windows and Mac.

The support file is retrieved [here](https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/packages/server/lib/config.ts#L422). If someone could run Cypress with the [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) logs turned on we can verify the `projectRoot` and `supportFile` properties are correct.

**Comment by diogosantana2011** [comment]
> @diogosantana2011, thanks for the additional report. Since your Jenkins VM is on Windows, I would expect the path separator to be `\` as displayed in the message. I've also been able to successfully load the support file locally on Windows and Mac.
> 
> The support file is retrieved [here](https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/packages/server/lib/config.ts#L422). If someone could run Cypress with the [debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) turned on we can verify the `projectRoot` and `supportFile` properties are correct.

Hi @mschile,

Good morning!

Thanks for the prompt response and suggestion.

I've retried with file name as `cypress\support\e2e.js` and `cypress\\support\\e2e.js` and job continues to fail.

Using `cypress\support\e2e.js` returns above error on support file as:

- `Your supportFile is missing or invalid: cypresssupporte2e.js` <-- not recognizing the `\`.

Using `cypress\\support\\e2e.js` returns file as `cypress\support\e2e.js` but still fails.

I've attached Cypress DEBUG logs here (can forward them on through email if needed): [Cypress_Job_failure.txt](https://github.com/cypress-io/cypress/files/8850859/Cypress_Job_failure.txt)

Although file loads successfully on my Mac locally with `cypress/support/e2e.js`, the issue remains in Jenkins not recognizing it. 

I've included error at end of job for visbility.

```
{
08:55:16   isCypressErr: true,
08:55:16   type: 'SUPPORT_FILE_NOT_FOUND',
08:55:16   details: undefined,
08:55:16   messageMarkdown: 'Your `supportFile` is missing or invalid: `cypress\\support\\e2e.js`\n' +
08:55:16     '\n' +
08:55:16     'The supportFile must be a .js, .ts, .coffee file or be supported by your preprocessor plugin (if configured).\n' +
08:55:16     '\n' +
08:55:16     'Fix your support file, or set supportFile to `false` if a support file is not necessary for your project.\n' +
08:55:16     '\n' +
08:55:16     'If you have just renamed the extension of your supportFile, restart Cypress.\n' +
08:55:16     '\n' +
08:55:16     'https://on.cypress.io/support-file-missing-or-invalid',
08:55:16   originalError: undefined,
08:55:16   stackWithoutMessage: '    at setSupportFileAndFolder (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.0.3\\Cypress\\resources\\app\\packages\\server\\lib\\config.js:341:23)\n' +
08:55:16     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
08:55:16     '    at ProjectConfigManager.buildBaseFullConfig (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.0.3\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:279:26)\n' +
08:55:16     '    at ProjectConfigManager.getFullInitialConfig (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.0.3\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:322:34)\n' +
08:55:16     '    at ProjectConfigManager.setupNodeEvents (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.0.3\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:119:28)\n'
08:55:16 }
```

Independently of all of the above, I will work with it as is for now since the specs are working locally but thought I'd add the information here should it help.

**Comment by MvRiele** [comment]
Same error in log here:

```
[1]   cypress:server:config validate that there is no breaking config options before setupNodeEvents +1ms
[1]   cypress:lifecycle:ProjectConfigManager catch setupNodeEvents Error: Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.  If a support file is not necessary for your project, set supportFile to false.  https://on.cypress.io/support-file-missing-or-invalid at setSupportFileAndFolder (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\server\lib\config.js:339:27)     at processTicksAndRejections (node:internal/process/task_queues:96:5) at ProjectConfigManager.buildBaseFullConfig (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:279:26) at ProjectConfigManager.getFullInitialConfig (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:322:34) at ProjectConfigManager.setupNodeEvents (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:119:28) { isCypressErr: true, type: 'DEFAULT_SUPPORT_FILE_NOT_FOUND', details: undefined, messageMarkdown: 'Your project does not contain a default `supportFile`. We expect a file matching `cypress\\support\\e2e.{js,jsx,ts,tsx}` to exist.\n' + '\n' + 'If a support file is not necessary for your project, set `supportFile` to `false`.\n' + '\n' + 'https://on.cypress.io/support-file-missing-or-invalid', originalError: undefined, stackWithoutMessage: '    at setSupportFileAndFolder (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\server\\lib\\config.js:339:27)\n' + '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' + '    at ProjectConfigManager.buildBaseFullConfig (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:279:26)\n' + '    at ProjectConfigManager.getFullInitialConfig (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:322:34)\n' + '    at ProjectConfigManager.setupNodeEvents (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:119:28)\n' } +29ms
[1] Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.
[1]
[1] If a support file is not necessary for your project, set supportFile to false.
[1]
[1] https://on.cypress.io/support-file-missing-or-invalid
[1]   cypress:server:cypress exiting with err Error: Your project does not contain a default supportFile. We expect a file matching cypress\support\e2e.{js,jsx,ts,tsx} to exist.
[1]
[1] If a support file is not necessary for your project, set supportFile to false.
[1]
[1] https://on.cypress.io/support-file-missing-or-invalid
[1]     at setSupportFileAndFolder (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\server\lib\config.js:339:27)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at ProjectConfigManager.buildBaseFullConfig (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:279:26)
[1]     at ProjectConfigManager.getFullInitialConfig (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:322:34)
[1]     at ProjectConfigManager.setupNodeEvents (C:\Users\svc_jenkins\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\data\ProjectConfigManager.js:119:28)
[1]  {
[1]   isCypressErr: true,
[1]   type: 'DEFAULT_SUPPORT_FILE_NOT_FOUND',
[1]   details: undefined,
[1]   messageMarkdown: 'Your project does not contain a default `supportFile`. We expect a file matching `cypress\\support\\e2e.{js,jsx,ts,tsx}` to exist.\n' +
[1]     '\n' +
[1]     'If a support file is not necessary for your project, set `supportFile` to `false`.\n' +
[1]     '\n' +
[1]     'https://on.cypress.io/support-file-missing-or-invalid',
[1]   originalError: undefined,
[1]   stackWithoutMessage: '    at setSupportFileAndFolder (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\server\\lib\\config.js:339:27)\n' +
[1]     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
[1]     '    at ProjectConfigManager.buildBaseFullConfig (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:279:26)\n' +
[1]     '    at ProjectConfigManager.getFullInitialConfig (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:322:34)\n' +
[1]     '    at ProjectConfigManager.setupNodeEvents (C:\\Users\\svc_jenkins\\AppData\\Local\\Cypress\\Cache\\10.0.2\\Cypress\\resources\\app\\packages\\data-context\\src\\data\\ProjectConfigManager.js:119:28)\n'
[1] } +13s
[1]   cypress:server:cypress calling exit 1 +1ms
[1]   cypress:server:cypress about to exit with code 1 +0ms
[1]   cypress:server:browsers browsers.kill called with no active instance +0ms
```

**Comment by mschile** [comment]
Alright, I was able to reproduce the issue locally by moving my project to the `Program Files (x86)` folder. @diogosantana2011 and @MvRiele, I don't need anything additional right now since I can reproduce locally.
