### ISSUE TITLE
Cypress Migration tool hangs on the loading screen

### ISSUE THREAD

**Issue by Dibbli** [cypress-io/cypress#22075]
### Current behavior

I'm converting a 9.7.0 project over to 10.0.2 and the migration helper tool that comes up just never loads
![migaration_helper](https://user-images.githubusercontent.com/35132242/171797781-5fa58ab8-150a-4130-b078-569113b0493f.png)
. 
It is a rather large project (130ish tests) so i gave it 30 minutes, but even then it just keep hanging. Only one error in dev tools
![combinederror](https://user-images.githubusercontent.com/35132242/171797999-35c57513-f70a-4e94-9a52-67ff12fd8fd3.png)
which might be related, but it might just be some weird error code from the downloadFIles plugin, because upon swapping back to 9.7, all tests run fine.

### Test code to reproduce

I dont know if i can provide anything here, the point is from 9.7.0 --> 10.0.X, tried all of them

### Cypress Version

10.0.2

**Comment by lmiller1990** [comment]
Hi! Migration should run basically instantly - all it does is renames, which is pretty quick, even on huge projects.

As part of migration we **do** execute your `pluginsFile`, so it's possible something is happening there. Can you share your pluginsFile (usually `cypress/plugins/index.js`.

If possible, please include your `package.json` too - ideal would be a minimal repo we can clone and debug, not sure how much trouble that would be.

**Comment by Jcsanga** [comment]
I am running into the same issue. In my terminal it states 

> 
```
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/xxxxxx/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/xxxxx/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js:12:13)
```

**Comment by lmiller1990** [comment]
@Jcsanga what version of Node.js are you running? You'll need at least [v12](https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements).

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
