### ISSUE TITLE
Error when the command npx cypress open is executed

### ISSUE THREAD

**Issue by alanvoigt** [cypress-io/cypress#22088]
### Current behavior

I get this 
```
error:C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:40
  invoke = (eventId, args = []) => {
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)


    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js:12:13)
```
    -------------
    
    I already created 3 projects and the error is always the same.

### Desired behavior

No errors!

### Test code to reproduce

I get this 
```
error:C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:40
  invoke = (eventId, args = []) => {
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)


    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Alan\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js:12:13)
```
    -------------
    
    I already created 3 projects and the error is always the same.

### Cypress Version

10.0.2

**Comment by edvitor13** [comment]
This also happened to me, the way I found to solve it, provisionally, was to move all this "invoke" method into the constructor and add it to the "RunPlugins" object: "this.invoke".
```js
invoke = (eventId, args = []) => {
  const event = this.registeredEventsById[eventId]
  
  return event.handler(...args)
}
```
---->
```js
constructor(...) {
...
  this.invoke = (eventId, args = []) => {
    const event = this.registeredEventsById[eventId]
    
    return event.handler(...args)
  }
...
}
```

**Comment by lmiller1990** [comment]
Can you clarify the Node.js version you are using?

**Comment by jennifer-shehane** [comment]
@lmiller1990 Our documentation states that we support Node 12+. https://on.cypress.io/installing-cypress#System-requirements which is what we should be supporting. 

Providing any of the projects that we could run to recreate this error would also be helpful.

**Comment by edvitor13** [comment]
My node version is: `v10.15.1`

**Comment by lmiller1990** [comment]
@jennifer-shehane my mistake, thanks.
@edvitor13 can you try updating to Node 12? As @jennifer-shehane clarified, that’s the minimum version Cypress requires to run correctly.

**Comment by 33Wil** [comment]
I have the same issue with 10.0.3. In the [run_plugin.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/child/run_plugins.js) file I changed invoke method to match the same function definition  style as the other functions in the class and it started up
```js
invoke = (eventId, args = []) => {
    const event = this.registeredEventsById[eventId]

    return event.handler(...args)
  }
```
To
```js
invoke(eventId, args = []){
    const event = this.registeredEventsById[eventId]

    return event.handler(...args)
  }
```

**Comment by lmiller1990** [comment]
@33Wil same question - what version of Node.js are on? Cypress requires v12. The error described here is the one you get when your version does not support class instance members:

```sh
v10.24.1
$ node -e 'class Foo { bar = () => {} }'                                                     
[eval]:1
class Foo { bar = () => {} }
                ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at createScript (vm.js:277:10)
    at Object.runInThisContext (vm.js:329:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I don't think this is a bug in Cypress, it's the error you get when using a Node.js version outside the ones we support. If anyone is encountering this on Node v12, happy to look into it, but for now I'm going to close this as there's no obvious actionable bug.
