### ISSUE TITLE
cypress >=10.0.0 crashes if behind company proxy when using the first time

### ISSUE THREAD

**Issue by kingofdisasterr** [cypress-io/cypress#22081]
### Current behavior

after installing cypress 10.0.1 or 10.0.2 i run cypress with `npx cpress open` which starts cypress ui. cypress loads correctly but when i click on `E2E Testing` it crashes after a few seconds.
cypress tries to access the url `https://download.cypress.io/desktop.json` but fails with:

`invalid json response body at https://download.cypress.io/desktop.json reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://download.cypress.io/desktop.json reason: Unexpected token < in JSON at position 0
    at C:\Users\<username>\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\node_modules\node-fetch\lib\index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at VersionsDataSource.getLatestVersion (C:\Users\<username>\AppData\Local\Cypress\Cache\10.0.2\Cypress\resources\app\packages\data-context\src\sources\VersionsDataSource.js:125:26)`

i use cypress behind a company firewall which i set as environment variable `HTTP_PROXY=http://my-company-proxy.com:proxy-port`. actually i was able to install cypress itself with this configuration, but using it, fails.

### Desired behavior

cypres should run as previous versions behind a company firewall.

### Test code to reproduce

use a company firewall.

### Cypress Version

10.0.2

**Comment by nitroplonker** [comment]
I am having the exact same issue
