### ISSUE TITLE
Unexpected Error when setting up component testing with nuxt

### ISSUE THREAD

**Issue by Simber1** [cypress-io/cypress#22090]
### Current behavior

Cypress throws an "Unexpected Error" 
![image](https://user-images.githubusercontent.com/16944153/171852818-ee8b4da4-d15e-4953-ae90-73ed0ad5a8ff.png)

Stack trace that is mostly hidden in that screenshot:
```
Error: Error loading nuxt. Looked in /home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/resources/node_modules,/home/peter/.cache/Cypress/10.0.2/Cypress/node_modules,/home/peter/.cache/Cypress/10.0.2/node_modules,/home/peter/.cache/Cypress/node_modules,/home/peter/.cache/node_modules,/home/peter/node_modules,/home/node_modules,/node_modules,/home/peter/.node_modules,/home/peter/.node_libraries,/usr/lib/x86_64-linux-gnu/nodejs,/usr/share/nodejs,/usr/lib/nodejs
    at nuxtHandler (/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nuxtHandler.js:24:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

and error logged in terminal:

```
TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/peter/code/work/mono-repository/clients/website/nuxt.config.js:197:41
    at jiti (/home/peter/code/work/mono-repository/clients/website/node_modules/jiti/dist/jiti.js:1:196506)
    at Object.loadNuxtConfig (/home/peter/code/work/mono-repository/clients/website/node_modules/@nuxt/config/dist/config.js:1082:15)
    at loadNuxt (/home/peter/code/work/mono-repository/clients/website/node_modules/@nuxt/core/dist/core.js:536:33)
    at getWebpackConfig (/home/peter/code/work/mono-repository/clients/website/node_modules/@nuxt/cli/dist/cli-index.js:720:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async nuxtHandler (/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nuxtHandler.js:15:31)
    at async getPreset (/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:70:20)
    at async Function.devServer.create (/home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:90:61)
    at async /home/peter/.cache/Cypress/10.0.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:25:24
```

In our nuxt.config.js inside sentry, config there is `environment: process.env.NODE_ENV.toUpperCase(),`  which would be the cause of the error if I had to guess

### Desired behavior

Cypress should not throw an error and should work as intented

### Test code to reproduce

If you need a copy of our nuxt.config.js I'll have to check if I'm allow to share a version of it with some secrets removed.

### Cypress Version

10.0.2

**Comment by Simber1** [comment]
Just to confirm, removing the `.toUpperCase()` lets me progress, to another error.

**Comment by Simber1** [comment]
> Just to clarify, is this Nuxt 2 or 3? Looks like we are losing `process.env` somewhere along the line.
It's Nuxt v2.15.8 per the nuxt's package.json
