### ISSUE TITLE
Another "Unexpected Error" in Nuxt config import

### ISSUE THREAD

**Issue by Simber1** [cypress-io/cypress#22092]
### Current behavior

Same environment and setup as #22090 but with the `.toUpper()` removed to fix that error.

I now run into another error which seems a lot less self-explanatory.

The Cypress error screen is the same as last time, just an error loading nuxt.

Console logged error:
```

 FATAL  Unexpected token '.'

  at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

### Desired behavior

Load and not run into an error

### Test code to reproduce

Same case as #22090, I would need to ask for permission to post our nuxt.config.js, if it's required to repo I will ask for permission.

### Cypress Version

10.0.2

**Comment by ZachJW34** [comment]
@Simber1 That error is pretty bare (not your fault). If you can ask permission to get a reproduction, or if you could create a minimal reproduction that has this error that would be great. I'm seeing `esm` in the error, do you happen to have `"type": "module" in your `package.json`?

**Comment by Simber1** [comment]
It's not in our main package.json and VS Code search doesn't return anything. I'll ask on Tuesday about what I can and can't post since there are a few secrets in our nuxt.config.js (I know). I'll probably have to redact some of it.

**Comment by marktnoonan** [comment]
Hi @Simber1 did you get any more info you are able to share?

**Comment by Simber1** [comment]
Sorry about the delay, I could have sworn I replied on the 13th but I must have not hit send 🤦
Here's a censored version of our nuxt.js.config and package.json (someone decided to put keys in there). Let me know if you need anything else.
[repo.zip](https://github.com/cypress-io/cypress/files/8957437/repo.zip)
