### ISSUE TITLE
Cypress generates an invalid config file

### ISSUE THREAD

**Issue by noelrappin** [cypress-io/cypress#22107]
### Current behavior

Brand new download of Cypress 10.0.2 using esbuild, converting an existing Cypress configuration. This setup did work under Cypress 9.x

The old config

```
{
  "screenshotsFolder": "tmp/cypress_screenshots",
  "videosFolder": "tmp/cypress_videos",
  "trashAssetsBeforeRuns": false
}
```

Cypress converts this to 

```
import { defineConfig } from 'cypress'

export default defineConfig({
  screenshotsFolder: 'tmp/cypress_screenshots',
  videosFolder: 'tmp/cypress_videos',
  trashAssetsBeforeRuns: false,
})
```

Then cypress immediately gives me a "Your configFile is invalid: <DIRNAME>north_by_seven/cypress.config.ts"

With this stack trace:

```
Error: Dynamic require of "tty" is not supported
    at file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:12:9
    at node_modules/debug/src/node.js (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:783:15)
    at __require2 (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:15:50)
    at node_modules/debug/src/index.js (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:957:25)
    at __require2 (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:15:50)
    at node_modules/cypress/index.js (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:89654:17)
    at __require2 (file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:15:50)
    at file:///Users/noel/projects/pragmatic/north_by_seven/cypress.config.bundled_1654357374176.mjs:89678:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async extractResult (/Users/noel/Library/Caches/Cypress/10.0.2/Cypress.app/Contents/Resources/app/node_modules/bundle-require/dist/index.cjs:185:13)
    at async loadFile (/Users/noel/Library/Caches/Cypress/10.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:120:15)
    at async EventEmitter. (/Users/noel/Library/Caches/Cypress/10.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:139:32)
```

I don't seem to have a `cypress.config.bundled_1654357374176.mjs` even though it is being referenced.

I'm not sure what's going on here, and would appreciate any help.

I've tried deleting the old config file and starting fresh, but I still get the same error. 

What am I doing incorrectly?

### Desired behavior

I'd expect Cypress to start normally.

### Test code to reproduce

```
{
  "screenshotsFolder": "tmp/cypress_screenshots",
  "videosFolder": "tmp/cypress_videos",
  "trashAssetsBeforeRuns": false
}
```

### Cypress Version

10.0.2

**Comment by lmiller1990** [comment]
Hi! I think this is related: https://github.com/cypress-io/cypress/issues/22074

I have no idea why it's complaining about `tty`.

Can you include your `package.json`? Is it using `"type": "module"` (assuming yes?)

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mortik** [comment]
Tried to upgrade to Cypress 10.0.0 from 9.5.3 and after conversion of my cypress.json i'm getting the same error.

my cypress.json:
```
{
  "baseUrl": "http://fleetyards.test",
  "fixturesFolder": "test/javascript/e2e/fixtures",
  "pluginsFolder": "test/javascript/e2e/plugins",
  "integrationFolder": "test/javascript/e2e/specs",
  "screenshotsFolder": "test/javascript/e2e/screenshots",
  "supportFile": "test/javascript/e2e/support",
  "video": false,
  "videosFolder": "test/javascript/e2e/videos",
  "videoUploadOnPasses": false,
  "videoCompression": 0,
  "viewportWidth": 2560,
  "viewportHeight": 1440,
  "defaultCommandTimeout": 10000,
  "reporter": "cypress-mochawesome-reporter",
  "reporterOptions": {
    "reportDir": "test/reports/e2e"
  }
}
```

and the generated cypress.config.ts:

```
import { defineConfig } from 'cypress'

export default defineConfig({
  fixturesFolder: 'test/javascript/e2e/fixtures',
  screenshotsFolder: 'test/javascript/e2e/screenshots',
  pluginsFolder: 'test/javascript/e2e/plugins',
  video: false,
  videosFolder: 'test/javascript/e2e/videos',
  videoUploadOnPasses: false,
  videoCompression: 0,
  viewportWidth: 2560,
  viewportHeight: 1440,
  defaultCommandTimeout: 10000,
  reporter: 'cypress-mochawesome-reporter',
  reporterOptions: {
    reportDir: 'test/reports/e2e',
  },
  e2e: {
    baseUrl: 'http://fleetyards.test',
    specPattern: 'test/javascript/e2e/specs/**/*.{js,jsx,ts,tsx}',
    supportFile: 'test/javascript/e2e/support',
  },
})
```
I also tried the latest 10.x version but than the error message gets even more obscure.
