### ISSUE TITLE
getting random http response code 500

### ISSUE THREAD

**Issue by ainglese** [cypress-io/cypress#2218]
### Current behavior & Steps to reproduce:
This works as expected:
```js
cy.visit('http://localhost:8080/ui/st.bquadro/agent');
cy.get('.login-content input[type=text]')
    .type('admin')
    .should('have.value', 'admin');

cy.get('.login-content input[type=password]')
    .type('xxxx')
    .should('have.value', 'xxxx');

cy.get('.login-content .submit input[name=commit]').click();

cy.visit('http://localhost:8080/ui/st.bquadro/agent#dashboard', {
    auth: { username: 'admin', password: 'xxxx' }
});
```
but this gives some network errors (status code 500):
```js
cy.visit('http://localhost:8080/ui/st.bquadro/agent#dashboard', {
    auth: { username: 'admin', password: 'xxxx' }
});
```
i've run our application with a debugger, and i'm almost sure our web server is not returning an error but a 200 OK.

the requests that fails are not always the same: 
![image](https://user-images.githubusercontent.com/4228935/43275356-d2243282-9101-11e8-8833-fbbeb0fe62b1.png)
but one of four files, just one of them succeeds. i've run cypress in debug mode and 

### Desired behavior:
test should not throw random 500.

### Versions
windows 10 pro + chrome + cypress 3.0.2

**Comment by ainglese** [comment]
addendum, please note that:
- The requests, consistently runs without errors when simulating requests with postman or other tools. so i think it's not becouse of application specific errors.
- Those static files, do non require authentication. so i don't think that exeptions are related to our application using basic instead of a cookie for authentication.
- Since cypress gives no error when using forms authentication, i think i can exclude something in the response content (things like gzip compression, UTF-8 encoding) etc.
- those assets are all UTF-8 encoded with BOM

please note also that i'm almost new to cypress, so there could be something obvious going on here, but i've tryed asking the community on the gitter channel without success.

**Comment by Francis-Moreau-adsk** [comment]
We get the same type of behavior with the app we are trying to auto-test. 
For us,  the error 500 is more consistent but still doesn't make sens. 
Login in and out twice in the same _specs.js will throw some error 500 on the second attempt to log in.

**Comment by mabedan** [comment]
Same issue here. We know for a fact that the requests are not hitting our server, and we've not been able to find any pattern to it. it's really random...

**Comment by jennifer-shehane** [comment]
We'll need a reproducible example in order to begin looking into this issue. Can anyone provide a way to reproduce this?

**Comment by ADavisDon** [comment]
I've encountered this error every time with our own website project. It'll occurs shortly after finishing a test. However, the longer that I use Cypress, the shorter the time length before hitting the 500 code, due to building lag in the Cypress browser. If I close out and relaunch Cypress, it'll go back to normal. It is appears to happen whenever ~60 seconds has passed in the test; The website is still responsive (can navigate to a different page within the same test) and does not display a 500 code when going through normal navigation in the Cypress browser.

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by mabedan** [comment]
I strongly advice against brushing this issue under the rug. This is obviously not an isolated case, as there're many who report the same issue, in this and other threads. I think this is also tied to https://github.com/cypress-io/cypress/issues/1039 , https://github.com/cypress-io/cypress/issues/2938 and https://github.com/cypress-io/cypress/issues/2639 . It has to have something to do with the way cypress channels the requests through.

If not solved, this will occur for future users and Cypress can not become a reliable solution for testing large platforms.

**Comment by jennifer-shehane** [comment]
@mabedan I agree! We definitely want to fix these issues, especially one as strange sounding as this, but we need a reproducible example to begin tracking it down. 

We are also always willing to reopen issues after closing if someone provides an example. We just have to clean up the issues eventually for our sanity. 🙃

**Comment by TheCodeKing** [comment]
Seems to happen fairly consistently for me with a large number of tests across multiple spec files. If I open chrome debugger during the tests there are no network requests being made, but seeing the following error. If I open the same URL in the same browser instance initiated by Cypress the webpage loads without error.

`
CypressError: cy.visit() failed trying to load:

https://www.myoffers.co.uk/product-testing/test--keep-a-kitchenaid-artisan-stand-mixer--12509-0/featured-4

The response we received from your web server was:

  > 500: Server Error

This was considered a failure because the status code was not '2xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'
`

**Comment by TheCodeKing** [comment]
Seems to happen fairly consistently for me with a large number of tests across multiple spec files. If I open chrome debugger during the tests there are no network requests being made, but seeing the following error. If I open the same URL in the same browser instance initiated by Cypress the webpage loads without error.

> CypressError: cy.visit() failed trying to load:
>
> https://...
>
> The response we received from your web server was:
>
> > 500: Server Error
> 
> 
> This was considered a failure because the status code was not '2xx'.
> If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

**Comment by Moejoe90** [comment]
Just an advice if you clone your repo again for some reason everything works 

Deleting the cypress cache didn't work 
Deleting the node_modules didn't work 

Cloning a new project worked

**Comment by charanyarepo** [comment]
Hi team, was there a resolution for this issue, we are facing the same quiet consistently. Especially in the past week.

**Comment by jennifer-shehane** [comment]
If you're experiencing a bug similar to this in Cypress, please comment in the issue with a **fully reproducible example that we can run**.

**Comment by dclowd9901** [comment]
@jennifer-shehane if we were able to fully and reliably replicate the issue, we wouldn't need the Cypress team to fix it.

**Comment by jennifer-shehane** [comment]
>The 500 error message page is a cypress-owned and presented page, not one of ours.

Could you explain what you mean by this? Are you visiting one of Cypress's domains? We don't present any 500 error messages within the application under test itself. 

We do proxy requests and there is logic behind that - so it is definitely possible there is a bug in Cypress. If we can't reproduce it, we have no idea where it could be originating from or how to fix it.

**Comment by dclowd9901** [comment]
> https://github.com/cypress-io/cypress/issues/2218#issuecomment-861520038

It appears to be expressed by the cypress application itself. Here's a screen shot:

![cypress-screenshot](https://user-images.githubusercontent.com/1314066/122084157-6bb99b00-cdb6-11eb-8cbc-db75b024ae75.png)

That isn't one of our 500 pages. Where in the code does the proxy logic live?

**Comment by jennifer-shehane** [comment]
@dclowd9901 Yah the state of this error is a bit unusual. Usually an error would be shown in the `visit` command on the left and the url is not blank within the application under test. It looks like it's still in a loading state. 

Is this a screenshot from a video? It may be cutting off the final moments where it shows the error. If you can recreate this locally, is there anything shown in the DevTools console? Or an error printed to stdout? Or do you have any code overwriting Cypress listeners/commands?

**Comment by TasnimZuhod** [comment]
This happens with me frequently, I usually need to restart Cypress several times in order to proceed with execution

**Comment by albertmir** [comment]
This randomly happens to us as well:
![cypress-random-500-error](https://user-images.githubusercontent.com/61497067/140875572-3db3e5c3-e5ee-44f1-8a69-72dc5b61d33f.png)

We've never experienced those 500 errors while using the site we're testing or running the tests locally. It only happens on the CI server.

**Comment by MaaikeFox** [comment]
We have the same issue
I have a video recording of it
Does this help @jennifer-shehane ?

https://user-images.githubusercontent.com/40559625/158431694-7b6c0e19-0e76-439d-b378-a6cc3f0e351a.mp4

**Comment by burkedavid** [comment]
Exactly the same issue is happening in my tests near every time now.  Is there a workaround  The odd occasion it will pass.

![image](https://user-images.githubusercontent.com/47853410/160142863-1c15b7da-5e00-4083-8471-ffbe6c341d19.png)

**Comment by finnef** [comment]
I have the same problem running my tests. It mostly occurs after a few longer tests have been run (in Gitlab CI). At some point cy.visit() will return a 500 error.

**Comment by alectrocute** [comment]
@jennifer-shehane It's very difficult to provide a sample of this bug since it only occurs on CI. I can attest that this bug is still present and seemingly random.

**Comment by ckifer** [comment]
Can also confirm this still happens and only in CI

Haven't seen anyone else post the stack so:
```
      at <unknown> ({url}/__cypress/runner/cypress_runner.js:138231:84)
      at visitFailedByErr ({url}/__cypress/runner/cypress_runner.js:137639:12)
      at <unknown> ({url}/__cypress/runner/cypress_runner.js:138214:13)
      at tryCatcher ({url}v/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler ({url}/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise ({url}/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 ({url}/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises ({url}/__cypress/runner/cypress_runner.js:7027:18)
      at _drainQueueStep ({url}/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue ({url}/__cypress/runner/cypress_runner.js:3614:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues ({url}/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues ({url}/__cypress/runner/cypress_runner.js:3500:14)
```

**Comment by avirajBoxture** [comment]
How can I verify '500 internal server error' while loading a url to check the access. This is a test case. Negative test.
How to code this situation.

If I use visit, same time getting 500 internal server error. or api ?
@jennifer-shehane

**Comment by gauthierm** [comment]
This is happening in CI for us as well. I see this issue is closed but it does not appear to be fixed.

![Screen Shot 2023-11-29 at 10 53 42](https://github.com/cypress-io/cypress/assets/120511/b542a15d-4be1-4865-a184-b31e3b1c06b9)

**Comment by jennifer-shehane** [comment]
@gauthierm It likely isn't fixed. We need a reproducible example in order to investigate.

**Comment by markhermano** [comment]
I got the same issue and I'm running the command below in Github Actions.
```cmd
docker run -i -v $PWD:/e2e -w /e2e --network=host --ipc=host cypress/included:13.6.2
````

**Comment by agusbrand** [comment]
I started to experience this issue after upgrading Rails from v7.0 to v7.1. It only happens on Github Actions, specs pass locally

**Comment by shwetakanchanv788344** [comment]
Have we got a resolution for this issue yet?
Even I have been experiencing this on my CI platform and it does not occur locally.
I am quite sure this has something to do with proxy.

Also I do see this error in the logs:
Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type
