### ISSUE TITLE
Cypress 10.0.3 cannot find root element to mount when running component test.

### ISSUE THREAD

**Issue by matsch01** [cypress-io/cypress#22185]
### Current behavior

After upgrading to Cypress 10.0.3, Cypress can't find the root element to mount. The app runs fine using same webpack config to run the app if dev mode.

cypress.config.ts

```
import { defineConfig } from 'cypress';
import webpackConfig from './webpack/webpack.cypress';

export default defineConfig({
    video: false,
    reporter: 'junit',
    reporterOptions: {
        mochaFile: 'results/unit/junit-[hash].xml',
    },
    component: {
        setupNodeEvents(on, config) {},
        viewportHeight: 700,
        viewportWidth: 1400,
        specPattern: 'src/**/*.spec.{ts,tsx}',
        devServer: {
            framework: 'react',
            bundler: 'webpack',
            webpackConfig,
        },
    },
});
```

resolved config
```
{
animationDistanceThreshold: 5,
arch: 'x64',
baseUrl: null,
blockHosts: null,
browsers: [
{
name: 'chrome',
family: 'chromium',
channel: 'stable',
displayName: 'Chrome',
version: '102.0.5005.61',
path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
minSupportedVersion: 64,
majorVersion: 102,
},
{
name: 'firefox',
family: 'firefox',
channel: 'stable',
displayName: 'Firefox',
version: '86.0.1',
path: '/Applications/Firefox.app/Contents/MacOS/firefox',
minSupportedVersion: 86,
majorVersion: 86,
},
{
name: 'electron',
channel: 'stable',
family: 'chromium',
displayName: 'Electron',
version: '100.0.4896.75',
path: '',
majorVersion: 100,
info: 'Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.',
},
],
chromeWebSecurity: true,
clientCertificates: [],
defaultCommandTimeout: 4000,
downloadsFolder: 'cypress/downloads',
env: {
},
excludeSpecPattern: [
'**/__snapshots__/*',
'**/__image_snapshots__/*',
],
execTimeout: 60000,
experimentalFetchPolyfill: false,
experimentalInteractiveRunEvents: false,
experimentalSessionAndOrigin: false,
experimentalSourceRewriting: false,
fileServerFolder: '',
fixturesFolder: 'cypress/fixtures',
hosts: null,
includeShadowDom: false,
isInteractive: true,
keystrokeDelay: 0,
modifyObstructiveCode: true,
numTestsKeptInMemory: 50,
pageLoadTimeout: 60000,
platform: 'darwin',
port: null,
projectId: null,
redirectionLimit: 20,
reporter: 'junit',
reporterOptions: {
mochaFile: 'results/unit/junit-[hash].xml',
},
requestTimeout: 5000,
resolvedNodePath: null,
resolvedNodeVersion: null,
responseTimeout: 30000,
retries: {
runMode: 0,
openMode: 0,
},
screenshotOnRunFailure: true,
screenshotsFolder: 'cypress/screenshots',
scrollBehavior: 'top',
slowTestThreshold: 250,
specPattern: 'src/**/*.spec.{ts,tsx}',
supportFile: 'cypress/support/component.{js,jsx,ts,tsx}',
supportFolder: false,
taskTimeout: 60000,
trashAssetsBeforeRuns: true,
userAgent: null,
video: false,
videoCompression: 32,
videosFolder: 'cypress/videos',
videoUploadOnPasses: true,
viewportHeight: 700,
viewportWidth: 1400,
waitForAnimations: true,
watchForFileChanges: true,
}
```

### Debug logs

at Context.<anonymous> (http://localhost:3000/__cypress/src/vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_cypress_react_dist_cypre-c29429.js:331:20)
    at getRet (http://localhost:3000/__cypress/runner/cypress_runner.js:153464:21)
From previous event:
    at Context.thenFn (http://localhost:3000/__cypress/runner/cypress_runner.js:153482:64)
    at Context.then (http://localhost:3000/__cypress/runner/cypress_runner.js:153934:22)
    at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:171664:20)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:170362:16)
From previous event:
    at CommandQueue.runCommand (http://localhost:3000/__cypress/runner/cypress_runner.js:170341:18)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:170495:20)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:170524:17)
From previous event:
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:170495:40)
From previous event:
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:185536:78)
From previous event:
    at CommandQueue.run (http://localhost:3000/__cypress/runner/cypress_runner.js:185531:22)
    at CommandQueue.run (http://localhost:3000/__cypress/runner/cypress_runner.js:170558:16)
    at cy.<computed> [as then] (http://localhost:3000/__cypress/runner/cypress_runner.js:171703:19)
    at _mount (http://localhost:3000/__cypress/src/vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_cypress_react_dist_cypre-c29429.js:324:11)
    at mount (http://localhost:3000/__cypress/src/vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_cypress_react_dist_cypre-c29429.js:305:13)
    at customMount (http://localhost:3000/__cypress/src/src_features_common_hooks_useCheckboxGroup_ts-src_features_common_hooks_useInput_ts-src_featu-ac9296.js:6741:64)
    at Context.<anonymous> (http://localhost:3000/__cypress/src/spec-0.js:22:59)
    at runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:171931:20)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:122314:22)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:122301:8)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:179079:31)
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:179064:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:168003:29)
    at Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:176715:14)
    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:122973:11)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:123099:13)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:122882:15)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:122892:8)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:122794:15)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:122860:6)
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:116786:28)

### Cypress Version

10.0.3

### Package Manager

yarn

### Operating system

Mac

**Comment by ToNewDay** [comment]
same

**Comment by mschaefer-gresham** [comment]
Thank you! That solved the issue.

**Comment by c-1-b** [comment]
@marktnoonan Thanks! This should be included in the migration guide (if not already).
