### ISSUE TITLE
Unexpected Error: Your configFile threw an error from: cypress.config.js

### ISSUE THREAD

**Issue by fityanos** [cypress-io/cypress#22211]
### Current behavior

I was installing the latest cypress in my next.js app, however, and while following up with the setup wizard I saw this error after checking the files that you will generate for me
<img width="1788" alt="Screen Shot 2022-06-09 at 10 56 44 AM" src="https://user-images.githubusercontent.com/16471809/172784402-6243c6a1-066d-4378-8a83-c6739fe908df.png">

### Debug logs

Error: Failed to load "next/dist/server/config" with error: Cannot find module 'next/dist/server/config'
Require stack:
- /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js
- /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js
- /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/index.js
- /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
    at getNextJsPackages (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:39:15)
    at loadWebpackConfig (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:51:56)
    at nextHandler (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:12:33)
    at getPreset (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:74:56)
    at Function.devServer.create (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:90:67)
    at /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:25:40
    at new Promise ()
    at devServer (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:24:12)
    at Object.handler (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:189:24)
    at invoke (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)
    at /Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/dev-server.js:18:8)
    at RunPlugins.execute (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:150:26)
    at EventEmitter. (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/anasfitiani/Library/Caches/Cypress/10.0.3/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

### Cypress Version

10.0.3

### Package Manager

npm

### Operating system

Mac

**Comment by lmiller1990** [comment]
Hi! Can you share your `package.json`? I'm mainly interested in what version of Next.js you are on.

If you could make a minimal reproduction, we can pull it down and take a look - but if you post your `package.json`, that should be enough to get started with debugging.

**Comment by fityanos** [comment]
Hi, hope this helps
```
    "next": "10.0.1",
    "next-pwa": "5.0.2",
```

**Comment by fityanos** [comment]
@marktnoonan upgrading to `"next": "12.0.10",` from ` "next": "10.0.1",` solved the issue - seems it's specific `next` version

**Comment by lmiller1990** [comment]
Great, glad you got it working. I'm sure we have coverage around Next.js 11 and 12 - I'm not sure on the support for older versions, or the difficulty of upgrading Next.js. If 10.x is widespread, we can look into support, but for now, I'd definitely recommend people having issues to update to the latest, if possible.

**Comment by atiurrahaman** [comment]
I've came to same issue in a big project for next js version 10, Is There any way to handle this issue or I'll need to upgrade to version 12. I can't easily upgrade to version 12 as working in a big project.

**Comment by lmiller1990** [comment]
It would be possible to support Next.js without needing to modify Cypress, but in the long run updating to Next 11 is probably going to be ideal.

If you want Next 10 support, you could likely do it with a custom dev server (which is how we do it internally).

## Dev Server

- https://docs.cypress.io/guides/component-testing/component-framework-configuration#Custom-Dev-Server
- https://stackoverflow.com/questions/73239537/how-to-return-a-devserver-for-custom-configuration-while-setting-up-cypress-comp

You also need the correct Webpack config, which seems to be buried in different places depending on the Next version. Here's an example of how we used to do it for older versions of Nexts (like 10):

https://github.com/cypress-io/cypress/blob/v9.7.0/npm/react/plugins/next/index.js#L5-L16. Note how we make a dev server, and do `findNextWebpackConfig` to find the correct config.

If you end up trying this and get stuck, lmk, I might be able to have a look.

**Comment by Alireza-ce** [comment]
I was using next `12.0.1` and after i upgrades my next to `12.0.10` this problem solved.
