### ISSUE TITLE
Cypress GUI stuck with exception on console (run_plugins.js)

### ISSUE THREAD

**Issue by jeenuv** [cypress-io/cypress#22332]
### Current behavior

I get this error on the console after launching Cypress after a fresh install:

```
~/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:40    
  invoke = (eventId, args = []) => {                                                                                                     
         ^                                                          
                                                                                                                                         
SyntaxError: Unexpected token =                                                                                                          
    at new Script (vm.js:79:7)                                      
    at createScript (vm.js:251:10)                                                                                                       
    at Object.runInThisContext (vm.js:303:10)                                                                                            
    at Module._compile (internal/modules/cjs/loader.js:656:28)     
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)                                                                               
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) 
    at Module.require (internal/modules/cjs/loader.js:636:17)       
    at require (internal/modules/cjs/helpers.js:20:18)              
    at Object.<anonymous> (~/.cache/Cypress/10.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)                                                                           
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)                                                                             
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) 
```

The GUI does open, but the spinning logo is displayed. No further progress.

If I change the offending line 40 to:

```
  invoke(eventId, args = []) {
```

Then the GUI appears to be behaving normal.

### Test code to reproduce

Run `$(npm bin)/cypress open` after a fresh install.

### Cypress Version

10.1.0

### Other

I'm running on a Linux x64 host. Node version: v10.13.0.

**Comment by jeenuv** [comment]
I can confirm this error happens with 10.0.0, but not 9.7.0.

**Comment by tracymazelin** [comment]
I see the same issue with Node v10.16.0.  Cypress docs say they support Node 12 or 14 and above.  Upgrading Node resolved the issue for me.

**Comment by miragekamran** [comment]
thank you @tracymazelin and @jeenuv. this error looked like a mystery to me.

**Comment by DylanDelobel** [comment]
I have the same error on a Fresh install

```
/home/admin/.cache/Cypress/11.2.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:40
  invoke = (eventId, args = []) => {
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/admin/.cache/Cypress/11.2.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/admin/.cache/Cypress/11.2.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js:12:13
```

Info from `cypress info`

```
Cypress Version: 11.2.0 (stable)
System Platform: linux (Debian - 10)
System Memory: 8.37 GB free 6.55 GB
```

EDIT: I had to refresh env variable, was still using old npm, v10 => v16 worked

**Comment by EGUS74** [comment]
I double you @jeenuv - faced it on Mac and just changed the function and saved the file so error went away and runner started immediately.
Thanks!
