### ISSUE TITLE
Cypress10.2.0 - Jenkins - Your configFile is invalid ERROR -> Error: Cannot find module 'cypress'

### ISSUE THREAD

**Issue by diogosantana2011** [cypress-io/cypress#22444]
### Current behavior

Hi Cypress Team,

Good morning!

**Background/Description**: 

Upon upgrading to Cypress@10.0.0, and completing migration; the Jenkins VM which I have that is running several jobs, started to fail to recognise supportFile. This was reported on (issue: https://github.com/cypress-io/cypress/issues/22272) which was fixed. 

After upgrading to release 10.1.0, Jenkins jobs which I had setup began to fail as the specPattern threw an error (reported on issue: https://github.com/cypress-io/cypress/issues/22272) as it was not recognising specPatterns.
After upgrading to release 10.2.0 today, I am getting an error on the configFile once again, that it cannot find module 'Cypress':
```
`Your configFile is invalid: C:\Program Files (x86)\Jenkins\workspace\Marketplace Smoke Test\cypress.config.js`

`It threw an error when required, check the stack trace below:`
`Error: Cannot find module 'cypress'`
```
**NOTE:** My configuration file does not have `"type":"module"` nor `"type":"commonjs"`. 

Locally, specs begin to run without the error which occurs on Jenkins:

![image](https://user-images.githubusercontent.com/58599175/175005541-313cefe9-ab71-4c41-b8e8-0602870aa73f.png)

**Additional Information:**

Cypress running local on OSX (Monterey12.4) & iTerm
Cypress running on Windows OS on Jenkins (VM which Jenkins is installed on)

Configuration file:

```js
const { defineConfig } = require('cypress')
/**
* @type {Cypress.PluginConfig}
*/
const { initPlugin } = require('cypress-plugin-snapshots/plugin');
const allureWriter = require('@shelex/cypress-allure-plugin/writer');
const xlsx = require("node-xlsx").default;
const fs = require("fs");
const path = require("path");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('task', {
        log(message) {
          console.log(message);
          return null;
        }
      });
    
      on('task', {
        parseXlsx({ filePath }) {
          return new Promise((resolve, reject) => {
          try {
            const jsonData = xlsx.parse(fs.readFileSync(filePath));
            resolve(jsonData);
          } catch (e) {
            reject(e);
          }
          });
        }
      });
    
      on('before:browser:launch', (browser = {}, launchOptions) => {
        const downloadDirectory = path.join(__dirname, '..', 'excelDownloads')
        
        if (browser.family === 'chromium') {
          launchOptions.preferences.default['download'] = { default_directory: downloadDirectory }
        }
        return launchOptions;
      });
    
      allureWriter(on, config);
      initPlugin(on, config);
    
      return config;
    },
    env: {
      // Env vars
    },
    specPattern: "cypress/e2e/**/*.{js,jsx,ts,tsx}",
    supportFile: "cypress/support/e2e.js",
    // fileServerFolder: "cypress/",
    baseUrl: "https://api.marketplace.playtech.com",
    retries: 1,
    responseTimeout: 1000000,
    defaultCommandTimeout: 1000000,
    viewportHeight: 960,
    viewportWidth: 1536,
    excludeSpecPattern: ["**/__snapshots__/*", "**/__image_snapshots__/*"],
    reporter: "cypress-multi-reporters",
    reporterOptions: {
      reporterEnabled: "mochawesome,mocha-junit-reporter",
      mochawesomeReporterOptions: {
        reportDir: "cypress/results",
        quite: true,
        overwrite: false,
        html: false,
        json: true,
      },
      mochaJunitReporterReporterOptions: {
        mochaFile: "cypress/results/results-[hash].xml",
      }
    }
  }
});
```

On Jenkins, when running Cypress 10.2.0 with command: `npx cypress run -e 'env_vars' -b chrome --headless -s cypress/e2e/smoke-tests/adm/admin-smoke-test.js -c video=false` 

I get below error:

```js
11:52:44   cypress:server:cypress exiting with err {
11:52:44   name: 'Error',
11:52:44   message: 'Your \x1B[33mconfigFile\x1B[39m is invalid: \x1B[94mC:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js\x1B[39m\n' +
11:52:44     '\n' +
11:52:44     'It threw an error when required, check the stack trace below:',
11:52:44   stack: "Error: Cannot find module 'cypress'\n" +
11:52:44     'Require stack:\n' +
11:52:44     '- C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js\n' +
11:52:44     '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js\n' +
11:52:44     '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\require_async_child.js\n' +
11:52:44     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n' +
11:52:44     '    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n' +
11:52:44     '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44     '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44     '    at Object.<anonymous> (C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js:1:26)\n' +
11:52:44     '    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n' +
11:52:44     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
11:52:44     '    at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
11:52:44     '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
11:52:44     '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44     '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44     '    at loadFile (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:89:14)\n' +
11:52:44     '    at EventEmitter.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:116:38)\n' +
11:52:44     '    at EventEmitter.emit (events.js:315:20)\n' +
11:52:44     '    at process.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\util.js:33:22)\n' +
11:52:44     '    at process.emit (events.js:315:20)',
11:52:44   type: 'CONFIG_FILE_REQUIRE_ERROR',
11:52:44   details: "Error: Cannot find module 'cypress'\n" +
11:52:44     'Require stack:\n' +
11:52:44     '- C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js\n' +
11:52:44     '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js\n' +
11:52:44     '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\require_async_child.js\n' +
11:52:44     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n' +
11:52:44     '    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n' +
11:52:44     '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44     '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44     '    at Object.<anonymous> (C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js:1:26)\n' +
11:52:44     '    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n' +
11:52:44     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
11:52:44     '    at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
11:52:44     '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
11:52:44     '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44     '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44     '    at loadFile (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:89:14)\n' +
11:52:44     '    at EventEmitter.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:116:38)\n' +
11:52:44     '    at EventEmitter.emit (events.js:315:20)\n' +
11:52:44     '    at process.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\util.js:33:22)\n' +
11:52:44     '    at process.emit (events.js:315:20)',
11:52:44   isCypressErr: true,
11:52:44   messageMarkdown: 'Your `configFile` is invalid: `C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js`\n' +
11:52:44     '\n' +
11:52:44     'It threw an error when required, check the stack trace below:',
11:52:44   originalError: {
11:52:44     name: 'Error',
11:52:44     message: "Cannot find module 'cypress'\n" +
11:52:44       'Require stack:\n' +
11:52:44       '- C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js\n' +
11:52:44       '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js\n' +
11:52:44       '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\require_async_child.js',
11:52:44     stack: "Error: Cannot find module 'cypress'\n" +
11:52:44       'Require stack:\n' +
11:52:44       '- C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js\n' +
11:52:44       '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js\n' +
11:52:44       '- C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\require_async_child.js\n' +
11:52:44       '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n' +
11:52:44       '    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n' +
11:52:44       '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44       '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44       '    at Object.<anonymous> (C:\\Program Files (x86)\\Jenkins\\workspace\\Marketplace Smoke Test\\cypress.config.js:1:26)\n' +
11:52:44       '    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n' +
11:52:44       '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
11:52:44       '    at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
11:52:44       '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
11:52:44       '    at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
11:52:44       '    at require (internal/modules/cjs/helpers.js:88:18)\n' +
11:52:44       '    at loadFile (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:89:14)\n' +
11:52:44       '    at EventEmitter.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\lib\\plugins\\child\\run_require_async_child.js:116:38)\n' +
11:52:44       '    at EventEmitter.emit (events.js:315:20)\n' +
11:52:44       '    at process.<anonymous> (C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Cypress\\Cache\\10.2.0\\Cypress\\resources\\app\\node
_modules\\@packages\\server\\lib\\plugins\\util.js:33:22)\n' +
11:52:44       '    at process.emit (events.js:315:20)',
11:52:44     code: 'MODULE_NOT_FOUND'
11:52:44   }
11:52:44 }
```

I've attached logs files here: [Cypress-DEBUG-log-10.2.0-Jenkins.txt](https://github.com/cypress-io/cypress/files/8956559/Cypress-DEBUG-log-10.2.0-Jenkins.txt)

Jenkins Workspace has 'cypress.config.js' within the root of the project.

Furthermore, when loading Cypress test builder GUI, specs and configuration file are recognized.

Again, I am able to get specs running locally, but thought of raising this issue.

Let me know if you require any further information which I can provide.

Diogo Santana

### Desired behavior

Should user run Jenkins Jobs on Windows VM -> Then support file to be recognized and cypress to run specs specified in command:
`npx cypress run -e 'env_vars' -b chrome --headless -s cypress/e2e/smoke-tests/adm/admin-smoke-test.js -c video=false` 

**Note:** Above spec path is an example. You can specify any spec existing within your project.

### Test code to reproduce

Using cypress.config.js mentioned above: 
- Please action job run using command and specifying path to spec to be used.
- Observe job result.

**NOTE:** Config file also mentioned in issues (https://github.com/cypress-io/cypress/issues/22272 and https://github.com/cypress-io/cypress/issues/22040) -> No changes made to it.

### Cypress Version

10.2.0

**Comment by diogosantana2011** [comment]
Hi @emilyrohrbough,

Thank you for the reply and suggestion.

Regarding your question:
```
Are you running this directly on your Jenkins node or are you running this within a docker container?
```
I am running on Jenkins node, without docker.

I've added `node_modules` folder within the project on Jenkins:

![image](https://user-images.githubusercontent.com/58599175/176613496-7e2f6b50-8371-46a1-bdd9-e025d87f2d88.png)

Upon running the job; the job ran without the error on Cypress Modules.

![image](https://user-images.githubusercontent.com/58599175/176615090-05eb63bf-7483-4830-91e9-66c2d26c9587.png)

There is however, the spec error which was reported on (issue [#22272](https://github.com/cypress-io/cypress/issues/22272)) where Cypress is unable to pick up on spec patterns.

I guess that is good news, since one less error! =D 

Let me know if you want me to close this, or should I leave it with yourselves.

**Comment by emilyrohrbough** [comment]
@diogosantana2011 Glad you were able to resolve this issue. Sorry you have been struggling through this upgrade! We appreciate your patience! Since this issue is resolved, I'm going to close it.

**Comment by anilpujaraofficial** [comment]
How can solve this issue 

![Screenshot from 2023-10-02 15-30-38](https://github.com/cypress-io/cypress/assets/65593381/c2234a87-40fc-407a-af23-96ef460e8217)

**Comment by MikeMcC399** [comment]
@anilpujaraofficial 

You seem to be reporting an issue with the npm module [cypress-cloud](https://www.npmjs.com/package/cypress-cloud) which is not supported here.
