### ISSUE TITLE
Cannot read properties of undefined (reading 'currentlyAttachedTarget')

### ISSUE THREAD

**Issue by koooge** [cypress-io/cypress#22451]
Hi there,

### Current behavior

```
Timed out waiting for the browser to connect. Retrying...
Cannot read properties of undefined (reading 'currentlyAttachedTarget')
TypeError: Cannot read properties of undefined (reading 'currentlyAttachedTarget')
    at Object.connectToNewSpec (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/browsers/chrome.js:431:48)
    at Object.connectToNewSpec (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/browsers/index.js:139:27)
    at /path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/open_project.js:148:47
    at tryCatcher (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/path/to/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
    111
```

### Desired behavior

no error

### Test code to reproduce

I got this error many times with `cypress run --browser chromium` . The test file includes 10~20 testcases.
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.2.0                                                                         │
  │ Browser:        Chromium 101 (headless)                                                        │
  │ Node Version:   v16.12.0 (/usr/bin/node)                                                       │

  │ Params:         Tag: false, Group: false, Parallel: false    

### Cypress Version

10.2.0

**Comment by emilyrohrbough** [comment]
@koooge Hi there. Thank you for logging an issue. Can you please provide a the the full logs? It would provide more detail on what you did leading up to this error. Was this happening on the first spec ran within your project? Or a 2nd or 3rd spec?  

I've identified where the error has [occurred](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L557) but want to ensure we understand the root of the issue here.

**Comment by emilyrohrbough** [comment]
Actually, I have reached out to someone who is familiar with this logic and it appears this is a mistake on how we are re-launching a browser after the first spec if the browser process is corrupt. This should be a relatively straightforward fix. Thank you for reporting!

**Comment by splincode** [comment]
I have the same issue

**Comment by nsbarsukov** [comment]
Full logs if the same error:

https://github.com/Tinkoff/taiga-ui/runs/7092418750?check_suite_focus=true

**Comment by KiranChil** [comment]
Noticed this issue in 10.0.3, 10.0.2. However 10.0.0 seem to work ok (not noticed this issues)

**Comment by gbooth27** [comment]
any updates on when this will be fixed @emilyrohrbough ?

**Comment by gbooth27** [comment]
@emilyrohrbough looks like the latest release still has this issue, any ETA on when this fix will get out?

**Comment by sandy-farnsworth** [comment]
I also saw this issue in 10.3.1. We use sorry cypress director, and I was running 2 threads for my visual tests, and I would get this error every time when the last test tried to run. When I switched to 1 thread, the tests were fine.

**Comment by alyssa-glean** [comment]
> I also saw this issue in 10.3.1. We use sorry cypress director, and I was running 2 threads for my visual tests, and I would get this error every time when the last test tried to run. When I switched to 1 thread, the tests were fine.

We're also using the sorry cypress director and are seeing this fairly often when the last spec tries to run. It's not every time - I'm not totally clear on what the pattern is between builds that are affected vs ones that aren't, though.

It's just hitting our screenshot tests, so I'm going to try moving those into a dedicated runner and parallelise the rest of the suite (functional tests) like before :crossed_fingers:

**Comment by alyssa-glean** [comment]
Ah, there's a buggy interaction between Cypress 10 and `sorry-cypress` which causes the browser to get closed before the final spec runs (because the penultimate spec is reported as N of N). The root cause is really a sorry-cypress bug, raised with them here: https://github.com/sorry-cypress/sorry-cypress/issues/613.

Just adding this for info in case it helps anyone. The `TypeError` mentioned in this issue is still a separate bug in Cypress that should be fixed :smile:

**Comment by agoldis** [comment]
Sorry-cypress issue was fixed in [v2.3.0](https://github.com/sorry-cypress/sorry-cypress/releases/tag/v2.3.0), thanks @alyssa-glean for issuing a solution. 

The original problem of cypress runner closing the browser (or not populating `currentlyAttachedTarget` on [browser-cri-client](https://github.com/cypress-io/cypress/blob/203758f7088b87d1e23275c39b806d57cf9179b8/packages/server/lib/browsers/browser-cri-client.ts) is still a separate bug, though, not related to dashboard orchestration.

**Comment by anewlens** [comment]
Any update or workaround on this issue? running into this in version 10.0.0, 10.3.0 and 10.9.0. Need to stay 10.0 and above for NextJS compatibility.

**Comment by qa-joerg** [comment]
Having the same issue on 10.0.0 < 10.3.0. This happens randomly during the test run. Please provide a fix for this issue

**Comment by dadagama** [comment]
have similar issue:

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.10.0                                                                        │
  │ Browser:        Chrome 85 (headless)                                                           │
  │ Node Version:   v14.19.0 (/usr/bin/node)                                                       │
  │ Specs:          2 found (*****.cy.ts, ******.cy.ts, ***** )                                    │
  │ Searched:       ./src/integration/**/*.cy.ts                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: analytics-smoke.cy.ts                                                       (1 of 3)
Cannot read properties of undefined (reading 'h7')
TypeError: Cannot read properties of undefined (reading 'h7')
    at Reporter.safelyMergeRunnable (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/server/lib/reporter.js:174:17)
    at Reporter.parseArgs (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/server/lib/reporter.js:377:18)
    at Reporter.emit (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/server/lib/reporter.js:359:17)
    at Object.onMocha (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/server/lib/project-base.js:272:34)
    at Socket.<anonymous> (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/server/lib/socket-base.js:260:40)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at Socket.emitUntyped (/home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/jenkins/.cache/Cypress/10.10.0/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```


Using 
`"cypress": "^10.10.0",`

in case this stack trace helps someone :)

**Comment by jennifer-shehane** [comment]
This was fixed in Cypress 13.13.0 ([#29663](https://github.com/cypress-io/cypress/pull/29663), tracked in [#27657](https://github.com/cypress-io/cypress/issues/27657)). After an unexpected browser exit, the retry now relaunches the browser instead of attempting to attach to a new tab on a torn-down CRI client. Closing the issue. If you still hit this on latest, please open a new issue with logs.
