### ISSUE TITLE
graphql-tag loader for cypress

### ISSUE THREAD

**Issue by websitevirtuoso** [cypress-io/cypress#22519]
### What would you like?

Hello.
I have problem with getting my gql object in cypress.
I have next setup
```
vuejs 3 latest - composition API
vite latest
https://v4.apollo.vuejs.org/guide/ - apollo vue v4
Cypress 10.2.0
graphql plugin to wrap objects into gql object
@rollup/plugin-graphql - latest version
```

I have next test case
https://gist.github.com/websitevirtuoso/c39b6b817a930b99299d353b83a05afe
Command  - gqlRequest looks like
https://gist.github.com/websitevirtuoso/2c2146eaecae3631421c83633afcb7cc

On line 3 I import gql query
My gql file looks like
https://gist.github.com/websitevirtuoso/1a850aa2b911acf431e3bbf8ac5595af
1 file can have multiple queries or mutations.
I import them like this

import { CategoryUpsert } from '../../../graphql/mutations/category.gql'
and this object I use in mutations or queries functions

In cypress I am getting this type of error when trying to get my gql object
```
Error: Webpack Compilation Error
./src/modules/blog/graphql/mutations/category.gql 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #import "../fragments/category.fragment.gql"
| 
| mutation CategoryUpsert ($id: ID, $title: String!) {
 @ ./src/modules/blog/tests/e2e/categories/tc01_categories.spec.ts 3:0-73 19:22-36
    at Watching.handle [as handler] (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:98:28)
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:73:19
    at Compiler.emitRecords (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Watching.js:54:20
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/viktord/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:193:23)
```

How to use gql objects in cypress? 
From this article
https://glebbahmutov.com/blog/request-graphql/
I can define gql query manually in cy.request but it will duplicate my gql objects. I would like to reuse my existing gql objects. Please help me how to do this?

I know that I need to add cypress-preprocessor but I couldn't find any
https://docs.cypress.io/plugins/directory
Something like this
```
webpackConfig.module.rules.push({
    test: /\.feature$/,
    use: [
      {
        loader: 'cypress-cucumber-preprocessor/loader',
      },
    ],
  });
```

### Why is this needed?

avoid duplication very complex gql files, better organization files and functions

**Comment by lmiller1990** [comment]
The error:

```sh
#import "../fragments/category.fragment.gql"
```

Did you accidentally type `#import` with a `#`? 

I think this is a bug in your configuration. Are you able to share a repository reproducing the example?

We are using GraphQL in this repo actually, via the GraphQL codegen library: https://github.com/cypress-io/cypress/blob/develop/graphql-codegen.yml

I created an in-depth tutorial on GraphQL + Vite here: https://github.com/lmiller1990/vue-3-urql-example. It is also available on YouTube: https://www.youtube.com/watch?v=oEOvrd03CIA&list=PLC2LZCNWKL9Z0CgtUGaDejThLdi08BTLe

**Comment by websitevirtuoso** [comment]
By documentation gql appol I can do this
https://www.apollographql.com/docs/react/data/fragments/#importing-fragments-when-using-webpack
This is how we import fragments. because this is not js file.
My configuration is good because app works. But I can't use this type of file in cypress.

I will do reproduction repo

**Comment by lmiller1990** [comment]
Interesting, I've not seen that syntax before. We use the `gql` tag an extract the types automatically with a tool.

If you can make a minimal repro, I can look at it. We grab your webpack config and use it internally, so we should be processing your code exactly the same.

**Comment by websitevirtuoso** [comment]
Sure. But I don't use webpack either. I am using vite

**Comment by websitevirtuoso** [comment]
@lmiller1990 here repo with tests
https://github.com/websitevirtuoso/repo_cypress_gql

**Comment by lmiller1990** [comment]
@websitevirtuoso I cloned your repository but it does not seem to have component testing configured. I configured it, but I don't see any Cypress tests (`cy.ts`). What should I run to reproduce the issue?

**Comment by lmiller1990** [comment]
There's a few things going on here. E2E and Component Testing are configured separately, and have different uses. By default, we include webpack, which will handle TypeScript, babel etc automatically. [Documentation on preprocessors](https://docs.cypress.io/api/plugins/preprocessors-api#See-also).

You've only configured E2E:

```ts
import { defineConfig } from 'cypress'

export default defineConfig({
  e2e: {
    baseUrl: 'http://127.0.0.1:3000',
    chromeWebSecurity: false,
    defaultCommandTimeout: 6000, // default value 4000
    specPattern: './src/modules/**/*.spec.ts',
    env: {
      apiUrl: 'http://127.0.0.1:4090',
      userEmail: 'info@rent.com',
      userPassword: 'mainPassword!@#$',
    },
  },
})
```

Since we use `webpack-preprocessor` by default, it's trying to process your `support/commands.js` file using webpack for E2E tests, and failing. It won't use Vite automatically for E2E tests. Unfortunately, we don't have a `vite-processor` for E2E tests. There's a [`cypress-rollup-preprocessor`](https://github.com/lmarqs/cypress-rollup-preprocessor), which is close to how Vite works, but it might be a bit annoying to configure.

For now, the easiest way to get your code running would be to use the `graphql-tag` helper to write your GraphQL queries, instead of `.graphql` with the `#import` syntax. This would alleviate the need for configuring `webpack-preprocessor`. I created a PR showing you how [here](https://github.com/websitevirtuoso/repo_cypress_gql/pull/1). It runs great on my machine - `npm run dev` in one terminal, `npm run cy:run` in the other :ok_hand: 

________

You **can** configure **component testing** with Vite, though, [like this](https://docs.cypress.io/guides/component-testing/component-framework-configuration#Vue-with-Vite). Generally, when doing component testing, you aren't concerned with things like authentication, but more modular and isolated tests, like buttons, widgets, and that sort of thing. Can give you some more examples, if this is something you are interested in.

Hopefully this helps a little. Let me know if you've got any other questions.
