### ISSUE TITLE
Cypress component testing Unexpected Error after first configuration

### ISSUE THREAD

**Issue by rsaleri** [cypress-io/cypress#22552]
### Current behavior

Just after cypress self configured the component testing for a vue-cli 2 project, it crashes with "Unexpected Error"
```
TypeError
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Stack trace
TypeError: Cannot read properties of undefined (reading 'tapPromise')
    at /home/rsaleri/projects/wlexpertsystem/frontend/node_modules/add-asset-html-webpack-plugin/lib/index.js:119:28
    at SyncHook.eval (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), :15:1)
    at SyncHook.lazyCompileHook (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Compiler.js:631:26)
    at /home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Compiler.js:667:29
    at eval (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), :12:1)
    at CypressCTWebpackPlugin.beforeCompile (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/CypressCTWebpackPlugin.js:30:17)
    at _next0 (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), :8:1)
    at eval (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), :21:1)
    at /home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/DllReferencePlugin.js:77:12
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), :17:1)
    at AsyncSeriesHook.lazyCompileHook (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Compiler.js:662:28)
    at /home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), :24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Watching.js:41:32)
    at /home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack/lib/Compiler.js:244:10)
    at wdm (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack-dev-middleware/index.js:41:33)
    at Server.setupDevMiddleware (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack-dev-server/lib/Server.js:207:23)
    at new Server (/home/rsaleri/projects/wlexpertsystem/frontend/node_modules/webpack-dev-server/lib/Server.js:118:10)
    at webpackDevServer3 (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/createWebpackDevServer.js:44:20)
    at createWebpackDevServer (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/createWebpackDevServer.js:18:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.devServer.create (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:91:34)
```
![image](https://user-images.githubusercontent.com/33120404/176130126-cbe40b2a-70ca-48fc-9a86-65b41697ae6f.png)

I don't know if it's of any help, but I don't have cypress.config.js, I have (and cypress correctly compiled) a cypress.config.ts.

### Desired behavior

In this situation cypress should either work or print out a little more meaningful output to try and understand what the issue might be

### Test code to reproduce

I'm not sure how or why this happens.
This is my full cypress.config.ts with component configuration:
```typescript
import {defineConfig} from 'cypress'
const createEsbuildPlugin = require('@badeball/cypress-cucumber-preprocessor/esbuild').createEsbuildPlugin
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor')
const nodePolyfills = require('@esbuild-plugins/node-modules-polyfill').NodeModulesPolyfillPlugin
const addCucumberPreprocessorPlugin = require('@badeball/cypress-cucumber-preprocessor').addCucumberPreprocessorPlugin
export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config) // to allow json to be produced
      // To use esBuild for the bundler when preprocessing
      on(
          'file:preprocessor',
          createBundler({
            plugins: [nodePolyfills(), createEsbuildPlugin(config)],
          })
      )
    },
    specPattern: 'tests/e2e/**/*.{feature,features,cy.js,cy.jsx,cy.ts,cy.tsx}',
    viewportHeight: 1080,
    viewportWidth: 1920,
  },

  component: {
    devServer: {
      framework: 'vue-cli',
      bundler: 'webpack',
    },
  },
});
```

### Cypress Version

10.2.0, 10.1.0

**Comment by rsaleri** [comment]
Fixed updating vue@cli-service and removing vue-cli-plugin-dll
