### ISSUE TITLE
Change the language by the google extension returns me a blank page in Cypress dashboard login page

### ISSUE THREAD

**Issue by ThalisonCosta** [cypress-io/cypress#22725]
### Current behavior

If I translate the page using the google extension and try to interact with the DOM, it returns an error that impossibilities me to use the website, being necessary update the page to use again.

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ao (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:74332)
    at Os `(https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:92815)`
    at t.unstable_runWithPriority (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:229:3884)
    at pa (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:41488)
    at js (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:90553)
    at hs (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:79292)
    at https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:41760
    at t.unstable_runWithPriority (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:229:3884)
    at pa (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:41488)
    at ya (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:41705)
    at ga (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:41640)
    at ys (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:79710)
    at In (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:221:31344)
    at HTMLDocument.r (https://dashboard.cypress.io/commons.474a305d39c02488de38.bundle.js:93:108267)
```

Follow video reproducing bug below:
[https://app.birdeatsbug.com/sessions/DYoHmjxkdUDoLxZBfyqE2VBRVXluKUh4cmSwudZR-D3P](url) 

### Desired behavior

Continue using the website normaly, but now translated to my language

### Test code to reproduce

Its not necessary becouse the bug occurs only with some clicks in Cypress website 

### Cypress Version

10.3.0

**Comment by BlueWinds** [comment]
The given link doesn't load for me. `Your account blue@cypress.io may not have permission to view this session, or it may have been deleted.`

Cypress is designed for test automation - interacting manually with the page under test is not recommended. Without repro steps, I'm just guessing at what you're doing - but you'd probably want to direct cypress straight to the translated page.

```
  it('works', () => {
    cy.visit("https://en-m-wikipedia-org.translate.goog/wiki/Main_Page?_x_tr_sl=auto&_x_tr_tl=es&_x_tr_hl=en&_x_tr_pto=wapp")
    cy.contains('Bienvenido a Wikipedia').should('be.visible')
  })
```

**Comment by ThalisonCosta** [comment]
I'm sorry, the link wasn't pulic, now it is, could you check again? [[https://app.birdeatsbug.com/sessions/DYoHmjxkdUDoLxZBfyqE2VBRVXluKUh4cmSwudZR-D3P](https://github.com/cypress-io/cypress/issues/url)](url)

 I'm not talking about my own test, the error ocurred during a login in cypress dashboard

**Comment by BlueWinds** [comment]
Ah, my bad, missed the 'dashboard' part of the title. You closed the issue - does that mean you've resolved it? If not, I can get someone who knows more about the dashboard in here to take a look.

**Comment by jaimefps** [comment]
We've added a ticket to our backlog. If this is a high priority issue for other users, we will move it up the priority list. Thanks for reporting, we will take a look at it.

**Comment by RobBickel** [comment]
Fixed! Translate away :)
