### ISSUE TITLE
Debug is not a function during cypress open

### ISSUE THREAD

**Issue by sauhaardac** [cypress-io/cypress#22770]
### Current behavior

I had previously used cypress in this Typescript/Javascript/React project, but upon upgrading cypress recently, and running 
`node_modules/.bin/cypress open` I get the following error:
```
/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/suppress_warnings.js:4
const debug = Debug("cypress:server:lib:util:suppress_warnings");
              ^
TypeError: Debug is not a function
    at Object.<anonymous> (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/suppress_warnings.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js:3:1)
```

On the Cypress Application UI side, I'm stuck with an endless spinner of death:
![CleanShot 2022-07-13 at 11 16 30@2x](https://user-images.githubusercontent.com/10953031/178803063-69f26518-6ba5-417c-bba0-20c03e403b56.png)

I tried removing the cypress folder in my project and removing the config files for cypress but the errors persisted... not sure what to do here as I couldn't find a similar error while googling. I did try reinstalling cypress and removing the cypress executable. Any advice would be appreciated as I'm still relatively new to the front end development ecosystem!

### Debug logs

```
  cypress:cli:cli cli starts with arguments ["/opt/homebrew/Cellar/node/18.3.0/bin/node","/Users/raunakc/Documents/Projects/analysis-suite-beta/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +0ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +88ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress +1ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app +0ms
  cypress:cli Reading binary package.json from: /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli Found binary version 10.3.0 installed in: /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app +3ms
  cypress:cli { verified: true } +3ms
  cypress:cli is Verified ? true +1ms
  cypress:cli opening from options {"project":"/Users/raunakc/Documents/Projects/analysis-suite-beta"} +0ms
  cypress:cli command line arguments ["--project","/Users/raunakc/Documents/Projects/analysis-suite-beta"] +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--project', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--cwd', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--userNodePath', '/opt/homebrew/Cellar/node/18.3.0/bin/node', '--userNodeVersion', '18.3.0' ] { detached: false, stdio: 'inherit' } +4ms
  cypress:cli spawning Cypress with executable: /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress +1ms
  cypress:ts registering ts-node on directory undefined +0ms
  cypress:ts Running without ts-node hook in environment "production" +38ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/browsers +38ms
  cypress:server:cypress starting cypress with argv [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress', '--no-sandbox', '--', '--project', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--cwd', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--userNodePath', '/opt/homebrew/Cellar/node/18.3.0/bin/node', '--userNodeVersion', '18.3.0' ] +0ms
  cypress:server:args argv array: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress', '--no-sandbox', '--project', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--cwd', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--userNodePath', '/opt/homebrew/Cellar/node/18.3.0/bin/node', '--userNodeVersion', '18.3.0' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0' } } +0ms
  cypress:server:args argv parsed: { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0', invokedFromCli: true } +1ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0', invokedFromCli: true, config: {} } +1ms
  cypress:server:args argv options: { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0', invokedFromCli: true, config: {}, projectRoot: '/Users/raunakc/Documents/Projects/analysis-suite-beta' } +0ms
  cypress:server:cypress from argv [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress', '--no-sandbox', '--project', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--cwd', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--userNodePath', '/opt/homebrew/Cellar/node/18.3.0/bin/node', '--userNodeVersion', '18.3.0' ] got options { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0', invokedFromCli: true, config: {}, projectRoot: '/Users/raunakc/Documents/Projects/analysis-suite-beta' } +3ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production +22ms
  cypress:server:cypress starting in mode interactive with options { _: [ '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/MacOS/Cypress' ], sandbox: false, project: '/Users/raunakc/Documents/Projects/analysis-suite-beta', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', userNodePath: '/opt/homebrew/Cellar/node/18.3.0/bin/node', userNodeVersion: '18.3.0', invokedFromCli: true, config: {}, projectRoot: '/Users/raunakc/Documents/Projects/analysis-suite-beta' } +38ms
  cypress:server:cypress running Electron currently +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudLatestRunUpdateSpecData +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectBySlug +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectsBySlugs +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudSpecByPath +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudViewer +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.versions +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for CurrentProject.cloudProject +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectResult.data +2ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectSpecResult.data +0ms
  cypress:server:browsers:utils getBrowsers +0ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +0ms
  cypress:data-context:sources:GitDataSource config: { isRunMode: false, projectRoot: '/Users/raunakc/Documents/Projects/analysis-suite-beta', onError: [Function (anonymous)], onBranchChange: [Function: onBranchChange], onGitInfoChange: [Function: onGitInfoChange] } +0ms
  cypress:scaffold-config:detect Detected cypress.config.ts - using TS +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/Users/raunakc/Documents/Projects/analysis-suite-beta', '--file', '/Users/raunakc/Documents/Projects/analysis-suite-beta/cypress.config.ts' ], childOptions: { stdio: 'pipe', cwd: '/Users/raunakc/Documents/Projects/analysis-suite-beta', execPath: '/opt/homebrew/Cellar/node/18.3.0/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +3ms
  cypress:server:util:editors get user editor +0ms
  cypress:server:saved_state making saved state from /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state making saved state from /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server +15ms
  cypress:server:saved_state for project path /Users/raunakc/Documents/Projects/analysis-suite-beta +0ms
  cypress:server:saved_state state path for project /Users/raunakc/Documents/Projects/analysis-suite-beta +23ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/analysis-suite-beta-5f70123816cb2e18204175a9bc22f6bb/state.json +600ms
  cypress:server:saved_state full state path /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/analysis-suite-beta-5f70123816cb2e18204175a9bc22f6bb/state.json +0ms
  cypress:server:saved_state making new state file around /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/analysis-suite-beta-5f70123816cb2e18204175a9bc22f6bb/state.json +1ms
  cypress:server:saved_state state path for global mode +3ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +4ms
  cypress:server:saved_state full state path /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:saved_state making new state file around /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:register-ts-node executing register_ts_node with args { _: [ '/opt/homebrew/Cellar/node/18.3.0/bin/node', '/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js' ], projectRoot: '/Users/raunakc/Documents/Projects/analysis-suite-beta', file: '/Users/raunakc/Documents/Projects/analysis-suite-beta/cypress.config.ts' } +0ms
  cypress:server:register-ts-node registering ts-node for projectRoot: /Users/raunakc/Documents/Projects/analysis-suite-beta and file: /Users/raunakc/Documents/Projects/analysis-suite-beta/cypress.config.ts +2ms
  cypress:server:ts-node projectRoot path: /Users/raunakc/Documents/Projects/analysis-suite-beta +0ms
  cypress:server:ts-node registeredFile: /Users/raunakc/Documents/Projects/analysis-suite-beta/cypress.config.ts +0ms
  cypress:server:plugins resolving typescript with projectRoot '/Users/raunakc/Documents/Projects/analysis-suite-beta' +0ms
  cypress:server:plugins resolved typescript /Users/raunakc/Documents/Projects/analysis-suite-beta/node_modules/typescript/lib/typescript.js +0ms
  cypress:server:ts-node typescript path: /Users/raunakc/Documents/Projects/analysis-suite-beta/node_modules/typescript/lib/typescript.js +0ms
  cypress:data-context:sources:GitDataSource On current branch master +114ms
  cypress:server:windows creating electron window with options { backgroundColor: 'white', width: 2560, height: 1415, minWidth: 597, minHeight: 400, x: 0, y: 120, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, webPreferences: { contextIsolation: true, partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false }, url: 'http://localhost:61329/__launchpad/index.html', contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
  cypress:server:ts-node registering project TS with options { compiler: '/Users/raunakc/Documents/Projects/analysis-suite-beta/node_modules/typescript/lib/typescript.js', compilerOptions: { module: 'commonjs', preserveValueImports: false }, dir: '/Users/raunakc/Documents/Projects/analysis-suite-beta', transpileOnly: true } +184ms
/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/suppress_warnings.js:4
const debug = Debug("cypress:server:lib:util:suppress_warnings");
              ^
TypeError: Debug is not a function
    at Object.<anonymous> (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/suppress_warnings.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js:3:1)
  cypress:server:util:editors return preferred editor: { id: 'code', name: 'Visual Studio Code', openerId: 'code', isOther: false } +2s
  cypress:server:util:editors user has the following editors: [ { id: 'code', binary: 'code', name: 'Visual Studio Code' }, { id: 'emacs', binary: 'emacs', name: 'Emacs' }, { id: 'vim', binary: 'vim', name: 'Vim' } ] +29ms
  cypress:server:saved_state making saved state from /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server +2s
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +4ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +2s
  cypress:server:saved_state full state path /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:browsers:utils found browsers { browsers: [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: '103.0.5060.114', path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', minSupportedVersion: 64, majorVersion: 103 } ] } +2s
  cypress:server:browsers:utils adding Electron browser { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '100.0.4896.160', path: '', majorVersion: 100, info: 'Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.' } +0ms
  cypress:server:util:editors saved preferred editor: { id: 'code', name: 'Visual Studio Code', openerId: 'code', isOther: false } +44ms
  cypress:server:util:editors return available editors: [ { id: 'computer', name: 'Finder', binary: 'computer' }, { id: 'code', name: 'Visual Studio Code', binary: 'code' }, { id: 'emacs', name: 'Emacs', binary: 'emacs' }, { id: 'vim', name: 'Vim', binary: 'vim' } ] +0ms
  cypress:server:saved_state making saved state from /Users/raunakc/Library/Caches/Cypress/10.3.0/Cypress.app/Contents/Resources/app/packages/server +41ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +0ms
  cypress:server:appdata path: /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +41ms
  cypress:server:saved_state full state path /Users/raunakc/Library/Application Support/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │   group   │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'cypress' │      1       │    '93696'     │    83.6    │      83.6      │   13.9   │     13.9     │    13.9     │
  cypress:server:util:process_profiler │    1    │  'other'  │      2       │ '93700, 93703' │     0      │       0        │   0.48   │     0.48     │    0.48     │
  cypress:server:util:process_profiler │    2    │  'TOTAL'  │      3       │      '-'       │    83.6    │      83.6      │  14.38   │    14.38     │    14.38    │
  cypress:server:util:process_profiler └─────────┴───────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing execution for Query.versions +2s
  cypress:network:agent addRequest called { isHttps: true, href: 'https://registry.npmjs.org/cypress' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'registry.npmjs.org', port: 80 } +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing execution for Query.cloudViewer +3ms
  cypress:graphql:remoteSchemaWrapped executing: {"operationName":"HeaderBar_HeaderBarQuery_cloudViewer","requestPolicy":"cache-first"} +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing Query.cloudViewer resolved immediately +4ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Query.versions did not resolve immediately +3ms
  cypress:network:connect got addresses { hostname: 'registry.npmjs.org', port: 80, addresses: [ { address: '104.16.20.35', family: 4 }, { address: '104.16.27.35', family: 4 }, { address: '104.16.17.35', family: 4 }, { address: '104.16.25.35', family: 4 }, { address: '104.16.19.35', family: 4 }, { address: '104.16.21.35', family: 4 }, { address: '104.16.26.35', family: 4 }, { address: '104.16.16.35', family: 4 }, { address: '104.16.18.35', family: 4 }, { address: '104.16.23.35', family: 4 }, { address: '104.16.24.35', family: 4 }, { address: '104.16.22.35', family: 4 } ] } +15ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://download.cypress.io/desktop.json' } +22ms
  cypress:network:connect beginning getAddress { hostname: 'download.cypress.io', port: 80 } +6ms
  cypress:network:connect got addresses { hostname: 'download.cypress.io', port: 80, addresses: [ { address: '104.22.11.239', family: 4 }, { address: '104.22.10.239', family: 4 }, { address: '172.67.25.250', family: 4 } ] } +1ms
  cypress:network:agent got family { family: 4, href: 'https://registry.npmjs.org/cypress' } +100ms
  cypress:network:agent got family { family: 4, href: 'https://download.cypress.io/desktop.json' } +12ms
  cypress:data-context:sources:VersionsDataSource NPM release dates received { modified: '2022-06-28T18:03:19.815Z' } +0ms
  cypress:data-context:sources:VersionsDataSource retrieving latest version information with headers: { 'Content-Type': 'application/json', 'x-cypress-version': '10.3.0', 'x-os-name': 'darwin', 'x-arch': 'arm64', 'x-initial-launch': 'true', 'x-machine-id': '4bb48d80dadfa3f7c94c778bc4dab5e1cf1e376f7bc580d38038adc45800477a' } +99ms
  cypress:data-context:sources:VersionsDataSource latest version information: { name: 'Cypress', version: '10.3.0', packages: { mac: { url: 'https://cdn.cypress.io/desktop/10.3.0/darwin-x64/cypress.zip' }, linux64: { url: 'https://cdn.cypress.io/desktop/10.3.0/linux-x64/cypress.zip' }, darwin: { url: 'https://cdn.cypress.io/desktop/10.3.0/darwin-x64/cypress.zip' }, linux: { url: 'https://cdn.cypress.io/desktop/10.3.0/linux-x64/cypress.zip' }, 'darwin-x64': { url: 'https://cdn.cypress.io/desktop/10.3.0/darwin-x64/cypress.zip' }, 'darwin-arm64': { url: 'https://cdn.cypress.io/desktop/10.3.0/darwin-arm64/cypress.zip' }, 'linux-x64': { url: 'https://cdn.cypress.io/desktop/10.3.0/linux-x64/cypress.zip' }, 'linux-arm64': { url: 'https://cdn.cypress.io/desktop/10.3.0/linux-arm64/cypress.zip' }, 'win32-x64': { url: 'https://cdn.cypress.io/desktop/10.3.0/win32-x64/cypress.zip' } } } +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing Query.versions eventually resolved with { latest: { id: '10.3.0', version: '10.3.0', released: '2022-06-28T17:26:39.026Z' }, current: { id: '10.3.0', version: '10.3.0', released: '2022-06-28T17:26:39.026Z' } } HeaderBar_HeaderBarQuery +403ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Resolving versions for pushFragment with {"latest":{"id":"10.3.0","version":"10.3.0","released":"2022-06-28T17:26:39.026Z"},"current":{"id":"10.3.0","version":"10.3.0","released":"2022-06-28T17:26:39.026Z"}} +1ms
  cypress:data-context:sources:GraphQLDataSource pushFragment value {"data":{"versions":{"current":{"id":"10.3.0","version":"10.3.0","released":"2022-06-28T17:26:39.026Z","__typename":"Version"},"latest":{"id":"10.3.0","version":"10.3.0","released":"2022-06-28T17:26:39.026Z","__typename":"Version"},"__typename":"VersionData"}}} +0ms
```

### Cypress Version

10.3.0

### Package Manager

npm

### Operating system

Mac

**Comment by astone123** [comment]
@sauhaardac I'm unable to reproduce this with a similar setup. A couple of questions:

1. Which version of Mac are you using and which architecture (M1 or Intel)?
2. How far do you have to downgrade Cypress to get to a version that doesn't produce this error?

Thanks

**Comment by feedmypixel** [comment]
I have a similar problem. I discovered that if I remove the `tsconfig.json` in my project. Cypress works

**Comment by astone123** [comment]
@feedmypixel thanks for that. I'm still not able to reproduce this by adding `"baseUrl": "."` in my `tsconfig.json` though. @sauhaardac What does your project's `tsconfig.json` file look like?

**Comment by marktnoonan** [comment]
@sauhaardac hopefully you are no longer experiencing this issue. We are beginning to implement a policy to close non-reproducible issues within 7 days of inactivity. Unfortunately, if we cannot reproduce an issue there isn't a whole lot that we can do, and in an effort to keep our issue backlog manageable we will be closing the issue.

If this is still a problem, please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
