### ISSUE TITLE
Internal Server Error (500) thrown on click of UI button which internally calls an endpoint

### ISSUE THREAD

**Issue by Sjain01** [cypress-io/cypress#2311]
Hi All ,

I am trying to automate a UI behaviour where click on a button internally calls a REST API but cypress is responding with 500 (Internal Server Error). 

When the same REST API is triggered separately via other REST API clients , it is working fine. 
It is only with cypress scripts I am facing an issue as manually the UI part too works fine.

**Cypress errored attempting to make an http request to the url**.
The error was:

```
ESOCKETTIMEDOUT


The stack trace was:

Error: ESOCKETTIMEDOUT
at ClientRequest. (/Users/shwetajain/Library/Caches/Cypress/3.0.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:812:19)
at Object.onceWrapper (events.js:314:30)
at emitNone (events.js:105:13)
at ClientRequest.emit (events.js:207:7)
at TLSSocket.emitTimeout (_http_client.js:722:34)
at Object.onceWrapper (events.js:314:30)
at emitNone (events.js:105:13)
at TLSSocket.emit (events.js:207:7)
at TLSSocket.Socket._onTimeout (net.js:402:8)
at ontimeout (timers.js:469:11)
at tryOnTimeout (timers.js:304:5)
at Timer.listOnTimeout (timers.js:264:5)
```

Also compared the response time of an endpoint which is around 321ms as opposed to 30000 as set by default by cypress script which confirms the endpoint is working as desired.

Cypress version used:- 3.0.0 and Chrome browser version - 68

**Comment by Sjain01** [comment]
Investigated this further and it seems like Cypress doesn't support 204 response code with empty body. The same script runs fine with 200 response code.

**Comment by stick710** [comment]
I have same problem, could you maybe help me ?
