### ISSUE TITLE
Cypress can not launch the firefox whose version is 102

### ISSUE THREAD

**Issue by Xiaogen-liu** [cypress-io/cypress#23388]
### Current behavior

Firefox version:  102.1.0 esr
https://ftp.mozilla.org/pub/firefox/releases/102.0esr/
nodejs: v16.16.0

![image](https://user-images.githubusercontent.com/19248390/185016543-c370e763-0fc1-4dc5-9577-b01e78e13d37.png)

### Desired behavior

it is able to launch the firefox.

### Test code to reproduce

the example of cypress can do this

### Cypress Version

10.4.0

### Node version

v16.16.0

### Operating System

Win10

### Debug Logs

```shell
20:49:13  This usually indicates there was a problem opening the Firefox browser.
20:49:13  
20:49:13  Error: Could not find url target in browser about:blank. Targets were []
20:49:13      at C:\WINDOWS\system32\config\systemprofile\AppData\Local\Cypress\Cache\10.4.0\Cypress\resources\app\packages\server\lib\browsers\browser-cri-client.js:90:27
20:49:13      at processTicksAndRejections (node:internal/process/task_queues:96:5)
20:49:13      at retry (C:\WINDOWS\system32\config\systemprofile\AppData\Local\Cypress\Cache\10.4.0\Cypress\resources\app\packages\server\lib\browsers\browser-cri-client.js:39:20)
20:49:13      at setupRemote (C:\WINDOWS\system32\config\systemprofile\AppData\Local\Cypress\Cache\10.4.0\Cypress\resources\app\packages\server\lib\browsers\firefox-util.js:109:27)
20:49:13  
20:49:13  2022-08-16T12:49:12.875Z cypress:server:cypress calling exit 1
20:49:13  2022-08-16T12:49:12.875Z cypress:server:cypress about to exit with code 1
20:49:13  2022-08-16T12:49:12.876Z cypress:server:browsers browsers.kill called with no active instance
20:49:13  2022-08-16T12:49:12.876Z cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 29, immediatelyMatchedRequests: 0, unmatchedRequests: 29, unmatchedPreRequests: 0 }
20:49:13  2022-08-16T12:49:12.927Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
20:49:13  2022-08-16T12:49:12.927Z cypress:cli child event fired { event: 'close', code: 1, signal: null }
```

**Comment by mjhenkes** [comment]
@Xiaogen-liu, this is intentional, as the error states there is a bug in firefox 101 and 102 which prevents cypress from working with those versions on windows. Please use firefox version 103.
