### ISSUE TITLE
Cypress v10.6.0 Stuck Loading Forever

### ISSUE THREAD

**Issue by lunaisnotaboy** [cypress-io/cypress#23499]
### Current behavior

Currently, Cypress is stuck on an infinite loop when the application is opened. Nothing is logged to the console, nor the console in the developer tools menu. I left it open all night, and nothing changed.

It looks like the app isn't even loading at all if you look at `[data-e2e]`.

![image](https://user-images.githubusercontent.com/63075513/185998695-87000a4b-7fbd-4747-9013-5ff8c235081f.png)

### Desired behavior

Load the dashboard for Cypress.

### Test code to reproduce

I've temporarily set the [repo containing the failing code](https://github.com/lunaisnotaboy/ina) to public, as it appears that the problem doesn't appear with the test fork.

I will set it back to private once the issue is closed, and will post any modifications needed to work here for reference.

### Cypress Version

10.6.0

### Node version

v18.7.0

### Operating System

Linux 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 GNU/Linux

### Debug Logs

```shell
ina on  main via  v18.7.0
❯ DEBUG=cypress:* yarn cypress open
  cypress:cli:cli cli starts with arguments ["/home/robert/.asdf/installs/nodejs/18.7.0/bin/node","/home/robert/ina/node_modules/.store/cypress-npm-10.6.0-4c3936a38f/node_modules/cypress/bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +4ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +126ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /home/robert/.cache/Cypress/10.6.0/Cypress/Cypress +4ms
  cypress:cli Binary is executable? : true +7ms
  cypress:cli binaryDir is  /home/robert/.cache/Cypress/10.6.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 10.6.0 installed in: /home/robert/.cache/Cypress/10.6.0/Cypress +8ms
  cypress:cli { verified: true } +9ms
  cypress:cli is Verified ? true +2ms
  cypress:cli opening from options {"project":"/home/robert/ina"} +0ms
  cypress:cli command line arguments ["--project","/home/robert/ina"] +0ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +2ms
  cypress:cli passing DISPLAY :0 +12ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--project', '/home/robert/ina', '--cwd', '/home/robert/ina', '--userNodePath', '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', '--userNodeVersion', '18.7.0' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +1ms
  cypress:cli spawning Cypress with executable: /home/robert/.cache/Cypress/10.6.0/Cypress/Cypress +6ms
  cypress:cli piping child STDERR to process STDERR +6ms
  cypress:ts registering ts-node on directory undefined +0ms
  cypress:ts Running without ts-node hook in environment "production" +83ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/cache +0ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/browsers +58ms
  cypress:server:cypress starting cypress with argv [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress', '--no-sandbox', '--', '--project', '/home/robert/ina', '--cwd', '/home/robert/ina', '--userNodePath', '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', '--userNodeVersion', '18.7.0' ] +0ms
  cypress:server:args argv array: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress', '--no-sandbox', '--project', '/home/robert/ina', '--cwd', '/home/robert/ina', '--userNodePath', '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', '--userNodeVersion', '18.7.0' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0' } } +3ms
  cypress:server:args argv parsed: { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0', invokedFromCli: true } +5ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0', invokedFromCli: true, config: {} } +3ms
  cypress:server:args argv options: { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0', invokedFromCli: true, config: {}, projectRoot: '/home/robert/ina' } +0ms
  cypress:server:cypress from argv [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress', '--no-sandbox', '--project', '/home/robert/ina', '--cwd', '/home/robert/ina', '--userNodePath', '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', '--userNodeVersion', '18.7.0' ] got options { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0', invokedFromCli: true, config: {}, projectRoot: '/home/robert/ina' } +14ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production +208ms
[10530:0822/151525.762632:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/robert/.cache/Cypress/10.6.0/Cypress/Cypress' ], sandbox: false, project: '/home/robert/ina', cwd: '/home/robert/ina', userNodePath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node', userNodeVersion: '18.7.0', invokedFromCli: true, config: {}, projectRoot: '/home/robert/ina' } +241ms
  cypress:server:cypress running Electron currently +1ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[10684:0822/151525.809355:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[10684:0822/151525.814718:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudLatestRunUpdateSpecData +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectBySlug +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectsBySlugs +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudSpecByPath +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudViewer +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.versions +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for CurrentProject.cloudProject +6ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectResult.data +9ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectSpecResult.data +1ms
  cypress:server:browsers:utils getBrowsers +0ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86, validator: [Function: validator] }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +0ms
  cypress:data-context:sources:GitDataSource config: { isRunMode: false, projectRoot: '/home/robert/ina', onError: [Function (anonymous)], onBranchChange: [Function: onBranchChange], onGitInfoChange: [Function: onGitInfoChange] } +0ms
  cypress:scaffold-config:detect Detected cypress.config.ts - using TS +0ms
  cypress:server:util:editors get user editor +0ms
  cypress:server:saved_state making saved state from /home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/home/robert/ina', '--file', '/home/robert/ina/cypress.config.ts' ], childOptions: { stdio: 'pipe', cwd: '/home/robert/ina', execPath: '/home/robert/.asdf/installs/nodejs/18.7.0/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +13ms
  cypress:server:saved_state making saved state from /home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/packages/server +42ms
  cypress:server:saved_state for project path /home/robert/ina +0ms
  cypress:server:saved_state state path for project /home/robert/ina +872ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/projects/ina-07112d34ebf23bc3460e72bb76df2871/state.json +2s
  cypress:server:saved_state full state path /home/robert/.config/Cypress/cy/production/projects/ina-07112d34ebf23bc3460e72bb76df2871/state.json +1ms
  cypress:server:saved_state making new state file around /home/robert/.config/Cypress/cy/production/projects/ina-07112d34ebf23bc3460e72bb76df2871/state.json +0ms
(node:10718) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10718) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/ts-node/esm/transpile-only.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:860:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '10530'     │    0.02    │      0.02      │  132.33  │    132.33    │   132.33    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '10532, 10533' │     0      │       0        │  96.41   │    96.41     │    96.41    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '10673, 10674' │     0      │       0        │   5.92   │     5.92     │    5.92     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │      '-'       │    0.02    │      0.02      │  234.66  │    234.66    │   234.66    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:server:saved_state state path for global mode +349ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +350ms
  cypress:server:saved_state full state path /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:server:saved_state making new state file around /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:data-context:sources:GitDataSource On current branch main +1s
  cypress:launcher:linux Could not extract version from stdout using regex: { stdout: '', versionRegex: /Chromium (\S+)/m } +0ms
  cypress:server:windows creating electron window with options { backgroundColor: 'white', width: 1200, height: 800, minWidth: 597, minHeight: 400, x: null, y: null, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage { toPNG: [Function: toPNG], toJPEG: [Function: toJPEG], toBitmap: [Function: toBitmap], getBitmap: [Function: getBitmap], getScaleFactors: [Function: getScaleFactors], getNativeHandle: [Function: getNativeHandle], toDataURL: [Function: toDataURL], isEmpty: [Function: isEmpty], getSize: [Function: getSize], setTemplateImage: [Function: setTemplateImage], isTemplateImage: [Function: isTemplateImage], isMacTemplateImage: [Getter/Setter], resize: [Function: resize], crop: [Function: crop], getAspectRatio: [Function: getAspectRatio], addRepresentation: [Function: addRepresentation] }, webPreferences: { contextIsolation: true, partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false }, url: 'http://localhost:37905/__launchpad/index.html', contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
  cypress:server:util:editors user has the following editors: [ { id: 'code', binary: 'code', name: 'Visual Studio Code' }, { id: 'vim', binary: 'vim', name: 'Vim' } ] +3s
  cypress:server:saved_state making saved state from /home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/packages/server +1s
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +2ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +1s
  cypress:server:saved_state full state path /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:server:util:editors saved preferred editor: undefined +19ms
  cypress:server:util:editors return available editors: [ { id: 'computer', name: 'File System', binary: 'computer' }, { id: 'code', name: 'Visual Studio Code', binary: 'code' }, { id: 'vim', name: 'Vim', binary: 'vim' } ] +0ms
  cypress:server:saved_state making saved state from /home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/packages/server +17ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +2ms
  cypress:server:appdata path: /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +20ms
  cypress:server:saved_state full state path /home/robert/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:launcher:linux Could not extract version from stdout using regex: { stdout: 'Mozilla Firefox 103.0', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m } +1s
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing execution for Query.versions +6s
  cypress:network:agent addRequest called { isHttps: true, href: 'https://registry.npmjs.org/cypress' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'registry.npmjs.org', port: 80 } +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing execution for Query.cloudViewer +22ms
  cypress:graphql:remoteSchemaWrapped executing: {"operationName":"HeaderBar_HeaderBarQuery_cloudViewer","requestPolicy":"cache-first"} +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing Query.cloudViewer resolved immediately +16ms
  cypress:server:browsers:utils found browsers { browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '103.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '103' } ] } +5s
  cypress:graphql:nexusDeferIfNotLoadedPlugin Query.versions did not resolve immediately +10ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://download.cypress.io/desktop.json' } +39ms
  cypress:network:connect beginning getAddress { hostname: 'download.cypress.io', port: 80 } +38ms
  cypress:network:connect got addresses { hostname: 'registry.npmjs.org', port: 80, addresses: [ { address: '104.16.16.35', family: 4 }, { address: '104.16.18.35', family: 4 }, { address: '104.16.26.35', family: 4 }, { address: '104.16.22.35', family: 4 }, { address: '104.16.24.35', family: 4 }, { address: '104.16.19.35', family: 4 }, { address: '104.16.21.35', family: 4 }, { address: '104.16.17.35', family: 4 }, { address: '104.16.20.35', family: 4 }, { address: '104.16.25.35', family: 4 }, { address: '104.16.23.35', family: 4 }, { address: '104.16.27.35', family: 4 }, { address: '2606:4700::6810:1523', family: 6 }, { address: '2606:4700::6810:1323', family: 6 }, { address: '2606:4700::6810:1723', family: 6 }, { address: '2606:4700::6810:1b23', family: 6 }, { address: '2606:4700::6810:1923', family: 6 }, { address: '2606:4700::6810:1623', family: 6 }, { address: '2606:4700::6810:1123', family: 6 }, { address: '2606:4700::6810:1223', family: 6 }, { address: '2606:4700::6810:1423', family: 6 }, { address: '2606:4700::6810:1023', family: 6 }, { address: '2606:4700::6810:1823', family: 6 }, { address: '2606:4700::6810:1a23', family: 6 } ] } +7ms
  cypress:network:connect got addresses { hostname: 'download.cypress.io', port: 80, addresses: [ { address: '104.22.10.239', family: 4 }, { address: '172.67.25.250', family: 4 }, { address: '104.22.11.239', family: 4 }, { address: '2606:4700:10::6816:bef', family: 6 }, { address: '2606:4700:10::ac43:19fa', family: 6 }, { address: '2606:4700:10::6816:aef', family: 6 } ] } +28ms
  cypress:network:agent got family { family: 4, href: 'https://registry.npmjs.org/cypress' } +41ms
  cypress:network:agent got family { family: 4, href: 'https://download.cypress.io/desktop.json' } +17ms
  cypress:data-context:sources:VersionsDataSource NPM release dates received { modified: '2022-08-16T20:29:16.517Z' } +0ms
  cypress:data-context:sources:VersionsDataSource retrieving latest version information with headers: { 'Content-Type': 'application/json', 'x-cypress-version': '10.6.0', 'x-os-name': 'linux', 'x-arch': 'x64', 'x-initial-launch': 'true', 'x-logged-in': 'false', 'x-machine-id': 'e77b1a695770471a59600141bb1cdfecdd3385fd9b63e0165f63177d560303dd' } +32ms
  cypress:data-context:sources:VersionsDataSource latest version information: { name: 'Cypress', version: '10.6.0', packages: { mac: { url: 'https://cdn.cypress.io/desktop/10.6.0/darwin-x64/cypress.zip' }, linux64: { url: 'https://cdn.cypress.io/desktop/10.6.0/linux-x64/cypress.zip' }, darwin: { url: 'https://cdn.cypress.io/desktop/10.6.0/darwin-x64/cypress.zip' }, linux: { url: 'https://cdn.cypress.io/desktop/10.6.0/linux-x64/cypress.zip' }, 'darwin-x64': { url: 'https://cdn.cypress.io/desktop/10.6.0/darwin-x64/cypress.zip' }, 'darwin-arm64': { url: 'https://cdn.cypress.io/desktop/10.6.0/darwin-arm64/cypress.zip' }, 'linux-x64': { url: 'https://cdn.cypress.io/desktop/10.6.0/linux-x64/cypress.zip' }, 'linux-arm64': { url: 'https://cdn.cypress.io/desktop/10.6.0/linux-arm64/cypress.zip' }, 'win32-x64': { url: 'https://cdn.cypress.io/desktop/10.6.0/win32-x64/cypress.zip' } } } +5ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Racing Query.versions eventually resolved with { latest: { id: '10.6.0', version: '10.6.0', released: '2022-08-16T19:36:37.075Z' }, current: { id: '10.6.0', version: '10.6.0', released: '2022-08-16T19:36:37.075Z' } } HeaderBar_HeaderBarQuery +234ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Resolving versions for pushFragment with {"latest":{"id":"10.6.0","version":"10.6.0","released":"2022-08-16T19:36:37.075Z"},"current":{"id":"10.6.0","version":"10.6.0","released":"2022-08-16T19:36:37.075Z"}} +7ms
  cypress:data-context:sources:GraphQLDataSource pushFragment value {"data":{"versions":{"current":{"id":"10.6.0","version":"10.6.0","released":"2022-08-16T19:36:37.075Z","__typename":"Version"},"latest":{"id":"10.6.0","version":"10.6.0","released":"2022-08-16T19:36:37.075Z","__typename":"Version"},"__typename":"VersionData"}}} +0ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │             pids             │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │ 'electron-shared' │      4       │ '10532, 10684, 10533, 10859' │    0.01    │       0        │  252.92  │    174.67    │   252.92    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │           '10530'            │    5.21    │      2.61      │  203.97  │    168.15    │   203.97    │
  cypress:server:util:process_profiler │    2    │    'launchpad'    │      1       │           '10906'            │    0.03    │      0.03      │  109.18  │    109.18    │   109.18    │
  cypress:server:util:process_profiler │    3    │      'other'      │      2       │        '10960, 10961'        │     0      │       0        │   5.86   │     5.89     │    5.92     │
  cypress:server:util:process_profiler │    4    │      'TOTAL'      │      8       │             '-'              │    5.25    │      2.63      │  571.93  │    403.29    │   571.93    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
^Cwrite EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Function.log (/home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/debug/src/node.js:194:24)
    at debug (/home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/node_modules/debug/src/common.js:113:10)
    at App.<anonymous> (/home/robert/.cache/Cypress/10.6.0/Cypress/resources/app/packages/server/lib/modes/interactive.js:150:13)
    at Object.onceWrapper (node:events:646:26)
    at App.emit (node:events:526:28)
    at App.emit (node:domain:475:12)
```

### Other

I'm am using Yarn as my package manager, and I have cleared the cache several times.

**Comment by mike-plummer** [comment]
Hi @lunaisnotaboy , thanks for opening an issue! The problem here is indicated by the "ERR_LOADER_CHAIN_INCOMPLETE" portion of your log - this has been reported a couple times now (#22795, #23393) and is a compatibility issue between newer versions of Node and the version of `ts-node`bundled in Cypress. Until we can get ts-node updated you can try using a slightly older version of Node, or removing the "type": "module" from your package json if you aren't set on using ESM modules

**Comment by lunaisnotaboy** [comment]
@mike-plummer - thanks for responding! I can't downgrade to `v16.x` because we're planning on using some `v18.x`-specific features, and we're using Vite, so ESM is required.

Should I go ahead and close this issue?

**Comment by mike-plummer** [comment]
@lunaisnotaboy I don't think you need to downgrade all the way to v16. The issue here is the new Experimental ESM Loader Hooks API in Node which appears to have been [added in 18.6.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.6.0), so maybe you could try 18.5.0?

I am going to mark this as a duplicate just to consolidate conversation into one of the existing issues. If using 18.5.0 is an option and resolves your issue I would certainly appreciate you reporting that here to help other users who may hit the same problem

**Comment by lunaisnotaboy** [comment]
Okay, thanks!
