### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promise'

### ISSUE THREAD

**Issue by aomaryus** [cypress-io/cypress#23533]
### Current behavior

This is happening in e2e pipelines - not all the times
Cypress 10.3.0 is installed in ..../tmp/.cypressCache/10.3.0

Command:
npx cypress run
--browser chrome --e2e
(node:333) UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promise'

### Desired behavior

I cannot tell what requires the @cypress/request-promise'
Plus it is deprecated
The desired behavior is that this package should not be used or needed 

### Test code to reproduce

This is only failing in pipelines 

### Cypress Version

 10.3.0

### Node version

v14.15.5

### Operating System

ubuntu

**Comment by nagash77** [comment]
@aomaryus I noticed in your ticket you had 

> UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promis'

Is promise actually spelled incorrectly or was this a copy/paste issue?

Also can you describe your pipeline in more depth please to help us understand what is happening and hopefully be able to reproduce the problem?

**Comment by aomaryus** [comment]
It is a typo.
The title of the issue has the error from the build log.
The pipeline is Jenkins running the build and test execution.

I am not sure what else to add.
Would it help if I provide packages.json?

Thank you.

**Comment by lmiller1990** [comment]
One way to check what uses a module is to run `npm why <module>`, so you could run `npm why "@cypress/request"`. In this case, cypress itself depends on `@cypress/request`:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/19196536/187558837-5180ce06-036d-4394-b759-13c9bf4bcdbf.png">

But installing Cypress should also install this automatically. First thing I'd recommend is running `npm why "@cypress/request"` and sharing the output. 

Fairly confused why this would only happen **sometimes** - this is very weird. Are you running Cypress via one of our Docker images? How is your pipeline architected?

**Comment by aomaryus** [comment]
```
 
# did not like why nor explain 
+ npm explain @cypress/request

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/m61407/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.13 /usr/bin/node-v14.17.0-linux-x64/lib/node_modules/npm

Did you mean this?
    explore

Then tried this. This build did not fail tho - so will have to one to fail 
+ npm version
{
   npm: '6.14.13',
...
  node: '14.17.0',
   
}
+ npm explore @cypress/request

Exploring 
.../node_modules/@cypress/request
Type 'exit' or ^D when finished

+ npm ls @cypress/request
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
astra@5.12.0 /home/m61407/node/community-seven/workspace/com.att.acp_aws-ui-e2e_cypress/pcastraui/astra
`-- cypress@10.3.1
  `-- @cypress/request@2.88.10 



No - not running Cypress via your docker images.
It runts inside a container with Jenkins

If you want me to put some additional debugging in Jenkinsfile, please let me know.

Thank you

```

**Comment by lmiller1990** [comment]
```
`-- cypress@10.3.1
  `-- @cypress/request@2.88.10 
```

Seems the module is present as expected. When do you see this error? As soon as you run `npx cypress run`?

**Comment by aomaryus** [comment]
```
Please see if this helps:
We have multiple users with different roles running Cypress in Jenkins on separate nodes. 
Each user does a full installation 

This is one user 
+ npm ci
npm WARN prepare removing existing node_modules/ before installation

redacted


Note: Overriding Cypress cache directory to: ......./tmp/.cypressCache

      Previous installs of Cypress may not be found.


Cypress 10.3.0 is installed in ........../tmp/.cypressCache/10.3.0


> ngcc

+ npm version
{
  npm: '6.14.13',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '38.1',
  icu: '68.2',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.0',
  openssl: '1.1.1k',
  tz: '2020d',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.63',
  zlib: '1.2.11'
}
+ npm ls @cypress/request
redactd
`-- cypress@10.3.0
  `-- @cypress/request@2.88.10

+ DEBUG='cypress:*'
+ npx grunt test:1:sequential --no-color
Running "shell:cypress:test:m42127:run" (shell) task

Command:
npx cypress run \
--env e2eEnv=test,MechID=m42127,TAGS='not @ignore' \
--browser chrome --e2e
2022-09-02T15:32:46.071Z cypress:cli:cli cli starts with arguments ["/usr/bin/node-v14.17.0-linux-x64/bin/node","....../node_modules/.bin/cypress","run","--env","e2eEnv=test,MechID=m42127,TAGS=not @ignore","--browser","chrome","--e2e"]
2022-09-02T15:32:46.074Z cypress:cli NODE_OPTIONS is not set
2022-09-02T15:32:46.074Z cypress:cli:cli program parsing arguments
2022-09-02T15:32:46.081Z cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: 'redactd/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, env: 'e2eEnv=test,MechID=m42127,TAGS=not @ignore', browser: 'chrome', e2e: true, args: [], [Symbol(kCapture)]: false } ]
2022-09-02T15:32:46.322Z cypress:cli:cli variable-length opts parsed { args: [ '/usr/bin/node-v14.17.0-linux-x64/bin/node', 'redactd/node_modules/.bin/cypress', 'run', '--env', 'e2eEnv=test,MechID=m42127,TAGS=not @ignore', '--browser', 'chrome', '--e2e' ], opts: Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: 'redactd/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, env: 'e2eEnv=test,MechID=m42127,TAGS=not @ignore', browser: 'chrome', e2e: true, args: [], [Symbol(kCapture)]: false } }
2022-09-02T15:32:46.324Z cypress:cli parsed cli options { browser: 'chrome', e2e: true, env: 'e2eEnv=test,MechID=m42127,TAGS=not @ignore' }
2022-09-02T15:32:46.325Z cypress:cli verifying Cypress app
2022-09-02T15:32:46.325Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-09-02T15:32:46.325Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-09-02T15:32:46.326Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER redacted/tmp/.cypressCache
2022-09-02T15:32:46.326Z cypress:cli checking environment variables
2022-09-02T15:32:46.336Z cypress:cli checking if executable exists redacted/tmp/.cypressCache/10.3.0/Cypress/Cypress
2022-09-02T15:32:46.340Z cypress:cli Binary is executable? : true
2022-09-02T15:32:46.341Z cypress:cli binaryDir is  redacted/tmp/.cypressCache/10.3.0/Cypress
2022-09-02T15:32:46.342Z cypress:cli Reading binary package.json from: redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/package.json
2022-09-02T15:32:46.352Z cypress:cli Found binary version 10.3.0 installed in: redacted/tmp/.cypressCache/10.3.0/Cypress
2022-09-02T15:32:46.356Z cypress:cli { verified: true }
2022-09-02T15:32:46.356Z cypress:cli is Verified ? true
2022-09-02T15:32:46.357Z cypress:cli:run processing run options { browser: 'chrome', e2e: true, env: 'e2eEnv=test,MechID=m42127,TAGS=not @ignore', key: null, spec: null, reporter: null, reporterOptions: null, project: 'redactd' }
2022-09-02T15:32:46.357Z cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY
2022-09-02T15:32:46.357Z cypress:cli:run run to spawn.start args ["--run-project","redactd","--browser","chrome","--env","e2eEnv=test,MechID=m42127,TAGS=not @ignore","--testing-type","e2e"]
2022-09-02T15:32:46.357Z cypress:cli undefined DISPLAY environment variable
2022-09-02T15:32:46.358Z cypress:cli Cypress will spawn its own Xvfb
2022-09-02T15:32:46.358Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-09-02T15:32:46.358Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-09-02T15:32:46.358Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER redacted/tmp/.cypressCache
2022-09-02T15:32:46.358Z cypress:cli needs to start own Xvfb? true
2022-09-02T15:32:46.359Z cypress:cli Starting Xvfb
2022-09-02T15:32:46.386Z cypress:xvfb _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

2022-09-02T15:32:46.387Z cypress:cli spawning, should retry on display problem? false
2022-09-02T15:32:46.404Z cypress:cli passing DISPLAY :99
2022-09-02T15:32:46.405Z cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', 'redactd', '--browser', 'chrome', '--env', 'e2eEnv=test,MechID=m42127,TAGS=not @ignore', '--testing-type', 'e2e', '--cwd', 'redactd', '--userNodePath', '/usr/bin/node-v14.17.0-linux-x64/bin/node', '--userNodeVersion', '14.17.0' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
2022-09-02T15:32:46.405Z cypress:cli spawning Cypress with executable: redacted/tmp/.cypressCache/10.3.0/Cypress/Cypress
2022-09-02T15:32:46.414Z cypress:cli piping child STDERR to process STDERR
  cypress:ts registering ts-node on directory undefined +0ms
  cypress:ts Running without ts-node hook in environment "production" +223ms
(node:369) UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promise'
Require stack:
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/exception.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/errors.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/unhandled_exceptions.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/index.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/exception.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(Use `Cypress --trace-warnings ...` to show where the warning was created)
(node:369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:369) UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promise'
Require stack:
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/exception.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/errors.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/unhandled_exceptions.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/index.js
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/exception.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[420:0902/153248.903167:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[443:0902/153248.998150:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[443:0902/153249.009041:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

```

**Comment by aomaryus** [comment]
Is it possible that the $CYPRESS_CACHE_FOLDER got corrupted shortly after installation - possibly by another process?

**Comment by lmiller1990** [comment]
That's weird. I see

> Note: Overriding Cypress cache directory to: ......./tmp/.cypressCache
> ...
> Cypress 10.3.0 is installed in ........../tmp/.cypressCache/10.3.0
> (node:369) UnhandledPromiseRejectionWarning: Error: Cannot find module '@cypress/request-promise'
Require stack:
- redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js

`npm` asserts the module is found, but it's not detected at runtime?

Looking at the module: https://github.com/cypress-io/request-promise/blob/master/package.json we do not have a `module` entry. Are you using `type: module` in your `package.json` by any chance?

A more primitive way to debug would be to ssh into your CI box, and you can simply edit `redacted/tmp/.cypressCache/10.3.0/Cypress/resources/app/packages/server/lib/api.js` with `vi` or something - before the `require('@cypress/request-promise')`, you could add some console logs or `require.resolve` or other debugging statements to figure out what's going on. 

I can keep suggesting things - I'm not too sure how to reproduce this one on my end to further debug. Let me know if you try any of those recommendations and if you make any progress.

**Comment by aomaryus** [comment]
Does this matter :
.../cypress/tsconfig.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "commonjs",
    "types": ["cypress", "node", "cypress-xpath"] // Are you referring to this type entry 
  }
}

**Comment by aomaryus** [comment]
The confusing thing to us is why this package https://github.com/cypress-io/request-promise is being used.
It is a a deprecated package and Cypress 10 would not be using it - isn't this the case.

**Comment by lmiller1990** [comment]
I was more thinking the `type` field in `package.json`.

Re: deprecation - `cypress/request` is a fork of `request`, which is deprecated, so our library is also deprecated for public usage. We still use it internally since we've made specific changes to make it do certain things, but it shouldn't lead to the "cannot find module" error you are experiencing.

**Comment by lmiller1990** [comment]
I'll need more info before proceeding. Happy to provide more help if you can provide something more actionable or a docker image that reproduces the issue. Until then, I'm not sure how much more assistance I can be.

Let me know if you've got any more suggestions on how we might continue debugging or if you have any more questions.
