### ISSUE TITLE
TS Error : Cannot find module @angular/core for my react app

### ISSUE THREAD

**Issue by vin-ai** [cypress-io/cypress#23750]
### Current behavior

I'm trying to migrate to Cypress 10.7.0 from 9.70. However almost fixed all the bug but stuck here at strange message, which says `@angular/core` or its corresponding type declarations cannot be found.

My app is a react app so why Cypress look for Angular not even mentioned in any config.

```
TypeScript error: /Users/vinay/cypress_testing_service/node_modules/cypress/angular/dist/mount.d.ts(5,22): Error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.
    at ProjectConfigIpc.<anonymous> (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigManager.js:216:60)
    at Object.onceWrapper (node:events:646:26)
    at ProjectConfigIpc.emit (node:events:526:28)
    at ProjectConfigIpc.emit (node:domain:475:12)
    at ProjectConfigIpc.emit (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigIpc.js:64:22)
    at ChildProcess.<anonymous> (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigIpc.js:40:18)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

```typescript
// cypress.config.ts
import { defineConfig } from "cypress";

export default defineConfig({
  viewportWidth: 1366,
  viewportHeight: 768,
  reporter: "mocha-junit-reporter",

  reporterOptions: {
    mochaFile: "cypress/reports/junit/test-results.[hash].xml",
    testsuitesTitle: false,
  },

  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    // https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed
    setupNodeEvents(on, config) {
      return require("./cypress/plugins/index.ts")(on, config);
    },
    baseUrl: "http://localhost:8082/",
    specPattern: "cypress/e2e/**/*.feature",
  },

  component: {
    devServer: {
      framework: "create-react-app",
      bundler: "webpack",
    },
  },
});
```

```typescript
// cypress/plugins/index.ts
const cucumber = require('cypress-cucumber-preprocessor').default;
const browserify = require('@cypress/browserify-preprocessor');

module.exports = (on, config) => {
  const options = {
    ...browserify.defaultOptions,
    typescript: require.resolve('typescript'),
  };

  options.browserifyOptions.plugin.unshift([
    'tsify',
    { project: 'cypress/tsconfig.json' },
  ]);

  on('file:preprocessor', browserify());
  on('file:preprocessor', cucumber(options));
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome') {
      launchOptions.args.push('--disable-dev-shm-usage');
    }
    return launchOptions;
  });
};
```

### Desired behavior

Cypress should just run my test successfully without showing any error.

### Test code to reproduce

There is no test code causing this error. This error is appearing even before listing test specs.

Upgraded Cypress to 10.7.0 from 9.7.0 and followed the GUI instructions to migrate. Then fixed some `chai` and `chai-subset` related bugs. Then started getting this error for E2E tests not for component tests.

### Cypress Version

10.7.0

### Node version

v16.14.2

### Operating System

macOS 12.5.1

### Debug Logs

```shell
TypeScript error: /Users/vinay/cypress_testing_service/node_modules/cypress/angular/dist/mount.d.ts(5,22): Error TS2307: Cannot find module '@angular/core' or its corresponding type declarations.
    at ProjectConfigIpc.<anonymous> (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigManager.js:216:60)
    at Object.onceWrapper (node:events:646:26)
    at ProjectConfigIpc.emit (node:events:526:28)
    at ProjectConfigIpc.emit (node:domain:475:12)
    at ProjectConfigIpc.emit (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigIpc.js:64:22)
    at ChildProcess.<anonymous> (/Users/vinay/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/data-context/src/data/ProjectConfigIpc.js:40:18)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by lmiller1990** [comment]
Hi! That is strange and very unexpected. I made a new app but I did not encounter this. Can you share your `package.json` so we can get the version of the dependencies you've got installed? Or, more ideally, a minimal reproduction I can clone to reproduce the error (this would be much faster to debug and fix the problem).

Thanks!

**Comment by vin-ai** [comment]
Sure,
Here is the package.json file content:

```json
{
  "name": "package.json",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "lint": "eslint 'cypress/**/*.{js,ts,tsx}'",
    "pretty": "prettier --write \"cypress/**/*.{ts,js,jsx,json}\"",
    "cy:run": "cypress run --config video=false",
    "cy:open": "cypress open",
    "initdb": "docker-compose run --rm backend sh -c './manage.py initcypress --skip-drop'",
    "generate-xlsx-files": "./generate_xlsx_files.sh"
  },
  "devDependencies": {
    "@types/faker": "4.1.12",
    "@typescript-eslint/eslint-plugin": "2.24.0",
    "@typescript-eslint/parser": "2.30.0",
    "cypress-multi-reporters": "1.2.4",
    "eslint": "6.8.0",
    "eslint-config-airbnb-typescript": "7.2.1",
    "eslint-config-prettier": "6.11.0",
    "eslint-plugin-cypress": "2.10.3",
    "eslint-plugin-import": "2.20.1",
    "eslint-plugin-prettier": "3.1.3",
    "mocha-junit-reporter": "1.23.3",
    "prettier": "2.0.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",
    "webpack": "^5.74.0"
  },
  "dependencies": {
    "@cypress/browserify-preprocessor": "2.2.4",
    "@types/cypress-cucumber-preprocessor": "1.14.1",
    "cypress": "10.7.0",
    "cypress-cucumber-preprocessor": "4.3.1",
    "faker": "4.1.0",
    "puppeteer": "2.1.1",
    "tsify": "4.0.1",
    "typescript": "4.8.3",
    "uuidv4": "6.0.8",
    "xlsx": "0.16.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepDefinitionsDir": "cypress/integration/steps",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/reports",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
}
```

This is the project structure:

```
project_root/
  |
  |- backend (Django App)
  |- frontend (React App)
  |- cypress_testing_service (Cypress things)
```

cypress_testing_service structure:
<img width="423" alt="Screenshot 2022-09-12 at 2 01 47 PM" src="https://user-images.githubusercontent.com/549946/189608530-80aeb827-de6b-45d7-bbc7-8e165c132293.png">

**Comment by lmiller1990** [comment]
No luck - here's my attempt to reproduce based on the information you've provided:

https://github.com/lmiller1990/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-23719?expand=1

Maybe you can create a stripped down version of your repository and upload it somewhere?

Also I found out the Cypress Cucumber Plugin v4 isn't working with Cypress 10, the fork that is actively supported [can be found here](https://github.com/badeball/cypress-cucumber-preprocessor), [see here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689) for more info.

**Comment by vin-ai** [comment]
After upgrading to `badeball/cypress-cucumber-preprocessor` it is working fine. But the question remains that how preprocessor makes cypress to go for angular instead.

**Comment by ZachJW34** [comment]
It's hard to say without a reproduction of the issue. The cucumber processor might have been trying to bundle `node_modules/cypress/angular` which relies on some Angular peer dependencies. We ship all of our mounts regardless if you use them or not, but they should be ignored as long as you the processor doesn't try to bundle them.

To verify, you've upgraded to the cucumber processor that has support for Cypress 10 and are no longer seeing this issue?

**Comment by vin-ai** [comment]
>To verify, you've upgraded to the cucumber processor that has support for Cypress 10 and are no longer seeing this issue?

Yes

**Comment by ZachJW34** [comment]
@vin-ai awesome, glad it's working now! I'm going to close this issue as it seems the error originated from using a plugin/preprocessor that was not compatible with your current version of Cypress.
