### ISSUE TITLE
BrowserslistError: Custom usage statistics was not provided

### ISSUE THREAD

**Issue by shaurgon** [cypress-io/cypress#2379]
### Current behavior:

After installing Cypress 3.1.0 all specs drops browserlist error (both browsers):

![image](https://user-images.githubusercontent.com/3669124/44408013-e9aeb680-a578-11e8-86f3-f25eddb721c9.png)

### Steps to reproduce:

```
{
"webpack": "^4.17.0",
"babel-preset-env": "^1.7.0",
}
```

browserlist config:
```
"browserslist": [
    "> 1% in my stats",
    "last 3 Chrome versions",
    "Firefox ESR",
    "last 3 Edge versions",
    "Safari >= 11",
    "not ie <= 11",
    "Electron >= 1.8"
  ],
```

Stacktrace:
```
GET /__cypress/iframes/integration/simple.spec.js 200 8.355 ms - 725
BrowserslistError: Custom usage statistics was not provided
    at Function.select (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/browserslist/index.js:482:15)
    at /Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/browserslist/index.js:140:33
    at Array.reduce (<anonymous>:null:null)
    at resolve (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/browserslist/index.js:121:18)
    at browserslist (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/browserslist/index.js:217:16)
    at getTargets (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/preset-env/lib/targets-parser.js:178:50)
    at _default (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/preset-env/lib/index.js:183:46)
    at /Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (native)
    at recurseDescriptors (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/config/full.js:100:6)
    at process.nextTick (/Users/user/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@babel/core/lib/transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Versions

Cypress 3.1.0
MacOS, Electron 59/Chrome 68

Cypress 3.0.2 is worked normally (3.0.3 - have svg bug, we can't use this version)

**Comment by shaurgon** [comment]
problem is located =)
String `> 1% in my stats` in package.json throws error, Cypress try get statistics, and can't locate it.
We exclude this row from package.json and append her in .babelrc.js
but I don't understand reasons for browserslist check.
okay, may be you add new param in cypress.json?

**Comment by jennifer-shehane** [comment]
Let me make sure I understand your issue. 

- You have the `browserslist` content above within your `package.json` file like [in this example](https://github.com/browserslist/browserslist#packagejson)? 
- Do you have code in your Cypress `plugins` file, like for preprocessing?

**Comment by shaurgon** [comment]
1) yes, of course
2) only default code
I don't understand, cypress try to check browserslist, why?

**Comment by jennifer-shehane** [comment]
Cypress does not check the `browserlist`, Cypress just displays any errors, including syntax errors that prevent the tests from running. I'm not sure what is causing this error to throw.
