### ISSUE TITLE
"TypeError: Cannot destructure property 'build' of 'architect' as it is undefined." when generating Cypress Angular Component test configuration

### ISSUE THREAD

**Issue by rujorgensen** [cypress-io/cypress#23841]
### Current behavior

I'm attempting to setup Angular component tests by using the Cypress UI tool:
![image](https://user-images.githubusercontent.com/6797319/190422551-7b608d66-e1b4-4a57-bace-222c5efc3a4c.png)

But I'm getting this error:
![image](https://user-images.githubusercontent.com/6797319/190423817-a9603a7e-ea93-4f34-a305-3700079c36b9.png)

Any advise would be much appreciated 🙏!

### Desired behavior

I'd like the tool to generate working configuration(s) enabling me to test Angular components (/not getting "Unexpecting Error").

### Test code to reproduce

I'm using a clean nx-workspace (Angular/NestJS/Cypress), which can be found here: https://github.com/rujorgensen/nx-workspace

### Cypress Version

10.7.0

### Node version

16.16.0

### Operating System

Windows 11

### Other

Complete outputs:
```
 21 |     const defaultProjectConfig = angularJson.projects[defaultProject];
  22 |     const { architect, root, sourceRoot } = defaultProjectConfig;
> 23 |     const { build } = architect;
     |             ^
  24 |     return {
  25 |         root,
  26 |         sourceRoot,
  27 |         buildOptions: Object.assign(Object.assign({}, build.options), ((_a = build.configurations) === null || _a === void 0 ? void 0 : _a.development) || {}),
```
```
TypeError: Cannot destructure property 'build' of 'architect' as it is undefined.
    at getProjectConfig (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:23:13)
    at async getAngularCliWebpackConfig (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:132:117)
    at async angularHandler (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:141:27)
    at async getPreset (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:76:20)
    at async Function.devServer.create (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:93:61)
    at async C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:25:24
```

**Comment by ZachJW34** [comment]
@rujorgensen have you tried setting up your project using the new nrwl generator? I cloned your repo and ran `nx g @nrwl/angular:cypress-component-configuration`, then added `apps/angular-app/src/app/app.component.cy.ts`:
```ts
import { HttpClientModule } from '@angular/common/http';
import { mount } from 'cypress/angular';
import { AppComponent } from './app.component';

it('should work', () => {
    cy.intercept('**/api/hello', { message: 'world' });
    mount(AppComponent, { imports: [HttpClientModule] });
});
```

and it was working (running `nx component-test angular-app --watch`). The default options for Cypress Angular CT Testing assume the structure of an `@angular/cli` project, so Nx has added some generators/builders to make it work inside an Nx workspace

**Comment by rujorgensen** [comment]
Thanks a lot for helping out @ZachJW34!

I tried the steps you described ([I pushed them here for reference](https://github.com/rujorgensen/nx-workspace/tree/testing/cy-component-tests/initial-configuration-setup)), but I actually get a similar error when running `nx component-test angular-app --watch`, so it seems to be an issue with my setup--very strange 🤔. I get the same error on my private, and my workplace, PC.

![image](https://user-images.githubusercontent.com/6797319/190854107-a6e4376b-c4b1-4e1b-a857-4d5016ecf21f.png)

```
Error: Unable to find the project configuration that includes apps\angular-app\cypress.config.
Found project name? undefined.
Graph has data? false
    at getProjectConfigByPath (C:\Users\rj\Desktop\nx-workspace\packages\cypress\plugins\cypress-preset.ts:97:11)
    at nxComponentTestingPreset (C:\Users\rj\Desktop\nx-workspace\packages\angular\plugins\component-testing.ts:64:49)
    at Object. (C:\Users\rj\Desktop\nx-workspace\apps\angular-app\cypress.config.ts:5:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions. [as .ts] (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter. (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:613:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
Does it mean anything to you?

**Comment by rujorgensen** [comment]
`nx component-test angular-app --watch` and `npx nx component-test angular-app --watch` works on my Linux machine though, but still no luck with any of them on Windows 10/11 😕.

**Comment by ZachJW34** [comment]
Looks to be a Windows paths issue on Nx's side. Could you open an issue with [Nx](https://github.com/nrwl/nx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)? I looked at your update and like you pointed out it works fine (I'm on Mac).

**Comment by rujorgensen** [comment]
> Could you open an issue with [Nx](https://github.com/nrwl/nx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)?

Absolutely, thanks for the help so far 🙏.

**Comment by ZachJW34** [comment]
Glad I could help 😃

**Comment by ZachJW34** [comment]
Going to close this issue, we can reopen if we need to make changes on our side to support Nx.
