### ISSUE TITLE
I can't do component test with Cypress

### ISSUE THREAD

**Issue by bernardo-zuchowski** [cypress-io/cypress#23923]
### Current behavior

First, I can't run test:component.

Then I update Cypress to 10.8.0 (latest version), then I remove the cypress folder and cypress.config.ts so I can do the initial configuration of component test.

When I try to mount the first component with Cypress mount, this error appears:
![image](https://user-images.githubusercontent.com/87351323/191603467-957410ae-5a17-48e0-a332-a0fc1395b890.png)

### Desired behavior

I want to mount the component and test them, with the Vitesse settings and with the Cypress tools.

### Test code to reproduce

https://github.com/bernardo-zuchowski/vitesse-cypress-issue

### Cypress Version

10.8.1

### Node version

16.17.0

### Operating System

Linux 5.15 Manjaro Linux

### Debug Logs

```shell
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.overwrite (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/magic-string@0.26.2/node_modules/magic-string/src/MagicString.js:344:10)
    at Object.expandVariantGroup (/home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+core@0.45.5/node_modules/@unocss/core/dist/index.cjs:246:16)
    at Object.transform (/home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+transformer-variant-group@0.45.5/node_modules/@unocss/transformer-variant-group/dist/index.cjs:10:12)
    at applyTransformers (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.0.4/node_modules/@unocss/vite/dist/index.mjs:815:13)
    at transform (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.0.4/node_modules/@unocss/vite/dist/index.mjs:842:16)
    at applyHtmlTransforms (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:41563:27)
    at Object.transformIndexHtml (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:57480:16)
    at /home/bernardo/.cache/Cypress/10.8.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/vite-dev-server/dist/plugins/cypress.js:66:57
    at call (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46058:7)
    at next (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46002:5)
    at Function.handle (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46005:3)
    at Server.app (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:45870:37)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by lmiller1990** [comment]
Something going on with the UnoCSS plugin:

```
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.overwrite (file:///Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/magic-string@0.26.2/node_modules/magic-string/src/MagicString.js:344:10)
    at Object.expandVariantGroup (/Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/@unocss+core@0.45.5/node_modules/@unocss/core/dist/index.cjs:246:16)
    at Object.transform (/Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/@unocss+transformer-variant-group@0.45.5/node_modules/@unocss/transformer-variant-group/dist/index.cjs:10:12)
    at applyTransformers (file:///Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.1.3/node_modules/@unocss/vite/dist/index.mjs:815:13)
    at transform (file:///Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.1.3/node_modules/@unocss/vite/dist/index.mjs:842:16)
    at applyHtmlTransforms (file:///Users/lachlan/code/dump/vitesse-cypress-issue/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:43823:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/lachlan/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/vite-dev-server/dist/plugins/cypress.js:67:44
```

If you comment out `UnoCSS()` in `vite.config.ts`, it works. This isn't a solution, obviously, but it should help with debugging.

Offending function:

```ts
function expandVariantGroup(str, seperators = ["-", ":"]) {
  regexClassGroup.lastIndex = 0;
  let hasChanged = false;
  let content = str.toString();
  do {
    const before = content;
    content = content.replace(
      regexClassGroup,
      (from, pre, sep, body) => {
        if (!seperators.includes(sep))
          return from;
        return body.split(/\s/g).filter(Boolean).map((i) => i === "~" ? pre : i.replace(/^(!?)(.*)/, `$1${pre}${sep}$2`)).join(" ");
      }
    );
    hasChanged = content !== before;
  } while (hasChanged);
  if (typeof str === "string")
    return content;
  else
    return str.overwrite(0, str.length(), content);
}
```

Specifically

```ts
    return str.overwrite(0, str.length(), content);
```

It's the magic string library: https://github.com/rich-harris/magic-string#readme

I logged the output:

```
{ str: MagicString {}, content: '' }
```

Original warning is `Cannot overwrite a zero-length range` - and content is `''` - I guess we should fine out why.

I started your project with `yarn dev` - log is now

```
{
  str: MagicString {},
  content: '<template>\n' +
    '  <main class="px-4 py-10 text-center text-gray-700 dark:text-gray-200">\n' +
    '    <RouterView />\n' +
    '    <Footer />\n' +
    '    <div class="mt-5 mx-auto text-center opacity-75 dark:opacity-50 text-sm">\n' +
    '      [Default Layout]\n' +
    '    </div>\n' +
    '  </main>\n' +
    '</template>\n'
}
```

Strange, I wonder what's the problem 🤔 I think [this line in the UnoCSS transformer](https://github.com/unocss/unocss/blob/main/packages/shared-integration/src/transformers.ts#L22) is getting called where `code` is `''`. I wonder if this transformer is applied at the wrong time relative to our Vite plugin.

Might be worth posting in the UnoCSS repo. Our Vite plugin is here https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/src/plugins/cypress.ts#L56-L94, that might help with debugging. Maybe @antfu has some suggestions, he's working on Vite and UnoCSS - does UnoCSS do anything special with Vite that we might need to consider if we are writing a Vite plugin using `transformIndexHtml`?

**Comment by bernardo-zuchowski** [comment]
Thanks, I also posted this issue in the Vitesse project because it's the basis of the project I used.

Considering that the project is from @antfu, maybe it will help me there too.

**Comment by lmiller1990** [comment]
Can you link the issue in the Vitesse project? That will be useful to reference.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
