### ISSUE TITLE
Mochawesome report returns TypeError: addContext is not a function when configuring it inside setupNodeEvents on (after:run)

### ISSUE THREAD

**Issue by idanElitzur** [cypress-io/cypress#23933]
### Current behavior

Since the last Cypress versions the 'after:run' API configuration is changed and the **mochawesome** **addContext** configuration is now part of the cypress config file and not in the support file anymore.
When I've tried to keep this there, Cypress _ignore_ the `Cypress.on("test:after:run")`.

So I've tried to refactor the `addContext` configuration for I can attach the failed tests screenshoots to the report in the end of the test execution but it yell about -->
````
An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

TypeError: addContext is not a function
...
````

### Test code to reproduce

`cypress.conf.ts`

````
// cypress/cypress.config.ts
/// <reference types="cypress" />
/**
 * @type {Cypress.PluginConfig}
 */

import { defineConfig } from 'cypress';
// @ts-ignore
import * as addContext from './node_modules/mochawesome/src/addContext';
const fs = require('fs');
const ansi = require('ansi-colors');
const webpackPreprocessor = require('@cypress/webpack-preprocessor');
const { execSync } = require('child_process');


export default defineConfig({
	env: {
		SMTP_HOST: process.env.SMTP_HOST,
	},
	e2e: {
		supportFile: './../my-shared-cy-infra/cypress/support/e2e.ts',
		downloadsFolder: './../my-shared-cy-infra/cypress/downloads',
		chromeWebSecurity: false,
		experimentalSourceRewriting: false,
		experimentalModifyObstructiveThirdPartyCode: true,
		numTestsKeptInMemory: 1,
		defaultCommandTimeout: 30000,
		requestTimeout: 30000,
		responseTimeout: 30000,
		taskTimeout: 30000,
		pageLoadTimeout: 30000,
		screenshotsFolder: './../my-shared-cy-infra/mochawesome-report/assets',
		screenshotOnRunFailure: true,
		reporter: './../my-shared-cy-infra/node_modules/mochawesome',
		reporterOptions: {
			reportDir: './../my-shared-cy-infra/cypress/report',
			code: false,
			charts: true,
			overwrite: false,
			html: false,
			json: true,
			embeddedScreenshots: true,
		},
		video: false,
		viewportHeight: 1080,
		viewportWidth: 1920,
		waitForAnimations: true,
		setupNodeEvents(on, config) {
			// @ts-ignore
			on('after:spec', (spec: any, results: any) => {
					const screenshot = `assets/${spec.name}/${results.tests[0].title[0]} -- ${results.tests[0].title[1]} (failed).png`;
				console.log('log', '>>>>>>> ' + screenshot);

				addContext({ spec }, screenshot);
			});

			on('task', {
				log(message) {
					console.log(ansi.yellow(message));
					return true;
				},
			});

			on('task', {
				err(message) {
					console.log(ansi.red(message));
					return true;
				},
			});
			return config;
		},
	},
});
````

### Cypress Version

10.7.0

### Node version

14.19.1

### Operating System

macOS 12.3.1

### Debug Logs

```shell
`
  cypress:lifecycle:ProjectConfigManager call event after:spec for invocation id inv70 +53s
  cypress:lifecycle:child:RunPlugins:32136 execute plugin event: after:spec ({ invocationId: 'inv70', eventId: 2 }) +53s
log >>>>>>> assets/Users/myname/repos/my-project/e2e-tests/test-files/init.cy.ts/Test for reference -- responsive views - Desktop iew - 1920 X 1080 (failed).png
  cypress:lifecycle:ProjectConfigManager promise rejected for id inv70 ':' TypeError: addContext is not a function
    at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)
    at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)
    at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)
    at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:482:12)
    at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:482:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) +6ms
  cypress:server:cypress exiting with err TypeError: addContext is not a function
    at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)
    at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)
    at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)
    at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:482:12)
    at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:482:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  isCypressErr: true,
  type: 'PLUGINS_RUN_EVENT_ERROR',
  details: 'TypeError: addContext is not a function\n' +
    '    at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)\n' +
    '    at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)\n' +
    '    at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14\n' +
    '    at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' +
    '    at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)\n' +
    '    at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)\n' +
    '    at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)\n' +
    '    at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)\n' +
    '    at EventEmitter.emit (node:events:513:28)\n' +
    '    at EventEmitter.emit (node:domain:482:12)\n' +
    '    at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)\n' +
    '    at process.emit (node:events:513:28)\n' +
    '    at process.emit (node:domain:482:12)\n' +
    '    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)\n' +
    '    at emit (node:internal/child_process:937:14)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  messageMarkdown: 'An error was thrown in your plugins file while executing the handler for the `after:spec` event.\n' +
    '\n' +
    'The error we received was:',
  originalError: Error [TypeError]: addContext is not a function
      at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)
      at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)
      at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
      at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
      at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
      at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)
      at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
      at EventEmitter.emit (node:events:513:28)
      at EventEmitter.emit (node:domain:482:12)
      at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
      at process.emit (node:events:513:28)
      at process.emit (node:domain:482:12)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
      at emit (node:internal/child_process:937:14)
      at processTicksAndRejections (node:internal/process/task_queues:83:21),
  stackWithoutMessage: '    at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)\n' +
    '    at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)\n' +
    '    at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14\n' +
    '    at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n' +
    '    at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)\n' +
    '    at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)\n' +
    '    at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)\n' +
    '    at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)\n' +
    '    at EventEmitter.emit (node:events:513:28)\n' +
    '    at EventEmitter.emit (node:domain:482:12)\n' +
    '    at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)\n' +
    '    at process.emit (node:events:513:28)\n' +
    '    at process.emit (node:domain:482:12)\n' +
    '    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)\n' +
    '    at emit (node:internal/child_process:937:14)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
} +1m
An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

TypeError: addContext is not a function
    at Object.handler (/Users/myname/repos/my-shared-cy-infra/cypress.config.ts:89:5)
    at invoke (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:43:18)
    at /Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:158:21)
    at EventEmitter.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:257:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:482:12)
    at process.<anonymous> (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:482:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/myname/Library/Caches/Cypress/10.7.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
  cypress:server:cypress calling exit 1 +1ms
  cypress:server:cypress about to exit with code 1 +0ms
  cypress:server:browsers killing browser process +1m
  cypress:server:browsers:chrome closing remote interface client +1m
  cypress:server:browsers:chrome closing chrome +0ms
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 99, proxyRequestsReceived: 63, immediatelyMatchedRequests: 38, unmatchedRequests: 3, unmatchedPreRequests: 39 } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +1m
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +0ms
````
```


### Other

_No response_

**Comment by idanElitzur** [comment]
I've changed the syntax from 'import' to 'require' and it works now.

**Comment by joakim-sch** [comment]
Thanks @idanElitzur 
Had the exact same problem
`const addContext = require("mochawesome/addContext.js")` did the trick

**Comment by andypalacio** [comment]
hello, where did you added that line?
