### ISSUE TITLE
Assertion scoping causes failures not to be reported.

### ISSUE THREAD

**Issue by ptletski** [cypress-io/cypress#23947]
### Current behavior

Four tests are executed via 

`npm run cypress:run -- --component --browser edge  --config video=false`

Where the expected result is four (4) failures. The results are presented as only two (2) errors occurring:
```
  Running:  display-user-message.service.cy.ts                                              (4 of 7)


  DisplayUserMessageService A
    1) Test 1
    √ Test 2 (37ms)
    2) Test 3
    √ Test 4 (54ms)


  2 passing (907ms)
  2 failing

  1) DisplayUserMessageService A
       Test 1:
     AssertionError: expected false to be true
      at captureUserInvocationStack (http://localhost:8081/__cypress/runner/cypress_runner.js:134308:102)
      at Assertion.assert (http://localhost:8081/__cypress/runner/cypress_runner.js:134338:9)
      at Assertion.<anonymous> (http://localhost:8081/__cypress/runner/cypress_runner.js:74937:10)
      at Assertion.propertyGetter (http://localhost:8081/__cypress/runner/cypress_runner.js:81850:29)
  at Reflect.get (<anonymous>)
      at Object.proxyGetter [as get] (http://localhost:8081/__cypress/runner/cypress_runner.js:83288:22)
      at Context.<anonymous> (http://localhost:8081/__cypress/src/spec-3.js:16:24)
      at ZoneDelegate.invoke (http://localhost:8081/__cypress/src/polyfills.js:8241:158)
      at ProxyZoneSpec.onInvoke (http://localhost:8081/__cypress/src/cypress_support_component_ts.js:734:33)
      at ZoneDelegate.invoke (http://localhost:8081/__cypress/src/polyfills.js:8241:46)

  2) DisplayUserMessageService A
       Test 3:
     AssertionError: expected false to be true
      at captureUserInvocationStack (http://localhost:8081/__cypress/runner/cypress_runner.js:134308:102)
      at Assertion.assert (http://localhost:8081/__cypress/runner/cypress_runner.js:134338:9)
      at Assertion.<anonymous> (http://localhost:8081/__cypress/runner/cypress_runner.js:74937:10)
      at Assertion.propertyGetter (http://localhost:8081/__cypress/runner/cypress_runner.js:81850:29)
  at Reflect.get (<anonymous>)
      at Object.proxyGetter [as get] (http://localhost:8081/__cypress/runner/cypress_runner.js:83288:22)
      at Context.<anonymous> (http://localhost:8081/__cypress/src/spec-3.js:37:25)
      at ZoneDelegate.invoke (http://localhost:8081/__cypress/src/polyfills.js:8241:158)
      at ProxyZoneSpec.onInvoke (http://localhost:8081/__cypress/src/cypress_support_component_ts.js:734:33)
      at ZoneDelegate.invoke (http://localhost:8081/__cypress/src/polyfills.js:8241:46)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     display-user-message.service.cy.ts                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

When tests are executed via 

`npx cypress open --component`

results are presented as:

![image](https://user-images.githubusercontent.com/44261878/191836581-d372f68d-2799-4883-9597-c5e661dad9d7.png)

### Desired behavior

In this situation Cypress should display 4 errors.

### Test code to reproduce

The test code: 

**display-user-message.service.cy.ts**

```
describe('DisplayUserMessageService A', () => {
  it('Test 1', () => {
    expect(false).to.be.true;
  })

  it('Test 2',  () => {
    let result: boolean = false;

    try {
      result = false;
      expect(result).to.be.true;
    }
    catch (err: any) {
      expect(false);
    }
  })

  it('Test 3',  () => {
    let result: boolean = false;

    try {
      result = false;
    }
    catch (err: any) {
      result = false;
    }

    expect(result).to.be.true;
  })

  it('Test 4', () => {
    const expectedMessage: string = 'THIS IS THE MESSAGE';
    const service: DisplayUserMessageService = new DisplayUserMessageService();
    const msgObs: Observable<string> = service.getMessage();
    
    msgObs.subscribe({
      next: (msg: string) => { expect(msg).not.to.be.equal(expectedMessage); },
      error: () => { expect(false).to.be.true}
    });
    
    service.updateMessage(expectedMessage);
  })
});
```

And DisplayUserMessageService is defined as:

**display-user-message.service.ts**

```
import { Injectable } from '@angular/core';
import { Subject, Observable } from 'rxjs';
@Injectable({
  providedIn: 'root'
})
export class DisplayUserMessageService {
  private userMessage$ = new Subject<string>();
  constructor() { }
  public getMessage(): Observable<string> {
    return this.userMessage$.asObservable();
  }
  public updateMessage(message: string): void {
    this.userMessage$.next(message);
  }
}
```

### Cypress Version

10.7.0

### Node version

v14.15.0

### Operating System

Windows 10

**Comment by chrisbreiding** [comment]
```js
it('Test 2',  () => {
    let result: boolean = false;

    try {
      result = false;
      expect(result).to.be.true;
    }
    catch (err: any) {
      expect(false);
    }
  })
```

`expect(false)` is not an assertion, so this test ends up being inert. Change it to `expect(false).to.be.true` and it should fail as expected.

```js
  it('Test 4', () => {
    const expectedMessage: string = 'THIS IS THE MESSAGE';
    const service: DisplayUserMessageService = new DisplayUserMessageService();
    const msgObs: Observable<string> = service.getMessage();
    
    msgObs.subscribe({
      next: (msg: string) => { expect(msg).not.to.be.equal(expectedMessage); },
      error: () => { expect(false).to.be.true}
    });
    
    service.updateMessage(expectedMessage);
  })
```

I'm guessing the `error` callback for `msObs.subscribe` gets called asynchronously. At this point, the test has already passed. You can use a `done` callback to let the test know to wait until it passes/fails.

```js
  it('Test 4', (done) => {
    const expectedMessage: string = 'THIS IS THE MESSAGE';
    const service: DisplayUserMessageService = new DisplayUserMessageService();
    const msgObs: Observable<string> = service.getMessage();
    
    msgObs.subscribe({
      next: (msg: string) => { expect(msg).not.to.be.equal(expectedMessage); },
      error: () => { 
        expect(false).to.be.true
        done()
      }
    });
    
    service.updateMessage(expectedMessage);
  })
```

**Comment by ptletski** [comment]
Your answer for Test 2 is wrong.

Note that in test 2 no exception is thrown. The catch is dead code. The try block is important and the error is not displayed.

**Comment by chrisbreiding** [comment]
> Note that in test 2 no exception is thrown

Exactly. Tests work by passing if there is not an exception thrown and failing if there is an exception thrown. Assertions (e.g. `expect(actual).to.equal(expect)`) work by throwing if they fail or not throwing if they pass. If something in a test doesn't throw an exception or if the test body doesn't return a promise that rejects, it is considered passing. 

It seems you'd expect individual assertions to be tracked and fail tests even if they're caught in a try/catch. That would take power away from the user since there could be a legitimate use-case for catching a failing assertion and not wanting the test to fail.

The current way it works gives you the ability to:
- not try/catch the assertion
- write an assertion in the catch block that may pass/fail the test
- re-throw the error in the catch block in order to fail the test.

**Comment by ptletski** [comment]
My apologies. Thanks for the clarification.
