### ISSUE TITLE
cy.wrap seems to manipulate global state 

### ISSUE THREAD

**Issue by ForzaMark** [cypress-io/cypress#23959]
### Current behavior

When I assign `cy.wrap` with different values to different variables, the variable values seem to get changed by each other.

### Desired behavior

Assigning a value to a variable should not have any effect on another completely independent variable.

### Test code to reproduce

```
describe('test cy.wrap', () => {
  it('should pass', () => {
    const val1 = cy.wrap(1);
    const val2 = cy.wrap(2);
    val1.should('eq', 1);
  })
})
```

I thought this test would easily pass, but unfortunately it does not.

The test log reads as follows:

![grafik](https://user-images.githubusercontent.com/28750031/191910127-b6957449-27de-4ca6-b08c-1ea439764f72.png)

### Cypress Version

10.8.0

### Node version

14.17.3

### Operating System

Windows 19043.1110

### Debug Logs

```shell
Error printed to console:


AssertionError: Timed out retrying after 4000ms: expected 2 to equal 1
    at ./cypress/e2e/wrap-test.cy.js/ (webpack:///./cypress/e2e/wrap-test.cy.js:5:9)
    at ../driver/src/cypress/cy.ts/setRunnable/runnable.fn (http://localhost:50332/__cypress/runner/cypress_runner.js:157447:43)
    at callFn (http://localhost:50332/__cypress/runner/cypress_runner.js:107881:21)
    at ../driver/src/cypress/runner.ts/create/onRunnableRun (http://localhost:50332/__cypress/runner/cypress_runner.js:164703:30)
    at finallyHandler (http://localhost:50332/__cypress/runner/cypress_runner.js:7872:23)
    at tryCatcher (http://localhost:50332/__cypress/runner/cypress_runner.js:11318:23)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:50332/__cypress/runner/cypress_runner.js:9253:31)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9310:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._fulfill (http://localhost:50332/__cypress/runner/cypress_runner.js:9379:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9323:21)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._fulfill (http://localhost:50332/__cypress/runner/cypress_runner.js:9379:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._resolveCallback (http://localhost:50332/__cypress/runner/cypress_runner.js:9173:57)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:50332/__cypress/runner/cypress_runner.js:9265:17)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9310:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._fulfill (http://localhost:50332/__cypress/runner/cypress_runner.js:9379:18)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._resolve (http://localhost:50332/__cypress/runner/cypress_runner.js:9652:19)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._promiseFulfilled (http://localhost:50332/__cypress/runner/cypress_runner.js:9670:14)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._iterate (http://localhost:50332/__cypress/runner/cypress_runner.js:9640:31)
    at init (http://localhost:50332/__cypress/runner/cypress_runner.js:9604:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9307:21)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._fulfill (http://localhost:50332/__cypress/runner/cypress_runner.js:9379:18)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._resolve (http://localhost:50332/__cypress/runner/cypress_runner.js:9652:19)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._promiseFulfilled (http://localhost:50332/__cypress/runner/cypress_runner.js:9670:14)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9315:26)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._fulfill (http://localhost:50332/__cypress/runner/cypress_runner.js:9379:18)
    at ../../node_modules/bluebird/js/release/promise_array.js/module.exports/PromiseArray.prototype._resolve (http://localhost:50332/__cypress/runner/cypress_runner.js:9652:19)
    at ../../node_modules/bluebird/js/release/map.js/module.exports/MappingPromiseArray.prototype._promiseFulfilled (http://localhost:50332/__cypress/runner/cypress_runner.js:8478:18)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:50332/__cypress/runner/cypress_runner.js:9315:26)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:50332/__cypress/runner/cypress_runner.js:9355:10)
    at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:50332/__cypress/runner/cypress_runner.js:9435:18)
    at _drainQueueStep (http://localhost:50332/__cypress/runner/cypress_runner.js:6025:12)
    at _drainQueue (http://localhost:50332/__cypress/runner/cypress_runner.js:6018:24)
    at ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues (http://localhost:50332/__cypress/runner/cypress_runner.js:6034:16)
    at ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues (http://localhost:50332/__cypress/runner/cypress_runner.js:5904:14)
```
```


### Other

_No response_

**Comment by chrisbreiding** [comment]
Cypress commands are run in a single, sequential queue. Commands like `cy.wrap()` work by setting the "subject" of the queue and passing it to the next command. There is only one subject at a time. When you call `cy.wrap(2)`, it's setting the subject, which replaces the previous value of `1`. 

Commands aren't meant to be assigned as variables and used later. It's simply not how Cypress was designed to work and we don't plan to change this behavior any time soon.

**Comment by ForzaMark** [comment]
thanks for the clarification
