### ISSUE TITLE
beforeSpecRun is not a function

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2401]
Cypress 3.1.0 Linux CircleCI job https://circleci.com/gh/cypress-io/cypress/33960

```
Warning: It looks like you are trying to record this run from a forked PR.

The 'Record Key' is missing. Your CI provider is likely not passing private environment variables to builds from forks.

These results will not be recorded.

This error will not alter the exit code.

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.0                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      16 found (app_spec.coffee, fixtures_spec.coffee, footer_spec.coffee, global_mode_… │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

beforeSpecRun is not a function
TypeError: beforeSpecRun is not a function
    at parallelWithRecord (/root/cypress/packages/server/lib/modes/run.coffee:282:5)
    at iterateThroughSpecs (/root/cypress/packages/server/lib/modes/run.coffee:307:7)
    at Object.runSpecs (/root/cypress/packages/server/lib/modes/run.coffee:789:5)
    at runAllSpecs (/root/cypress/packages/server/lib/modes/run.coffee:953:12)
    at /root/cypress/packages/server/lib/modes/record.coffee:451:9
From previous event:
    at /root/cypress/packages/server/lib/modes/record.coffee:449:6
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @packages/desktop-gui@0.0.0 cypress:run: `node ../../scripts/cypress run --project . "--record" "--parallel" "--group" "2x-desktop-gui"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @packages/desktop-gui@0.0.0 cypress:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bahmutov** [comment]
I started a branch `fix-beforespecrun-2401` with added check - the variable `beforeSpecRun` is `undefined` when called, but I did not look into why it is not set in this case (parallel recording, no variables, forked pull request)

**Comment by chrisbreiding** [comment]
@brian-mann If it's a forked PR run, we don't record. Does this mean it can't run in parallel? Should it just skip being parallel if it's forked or do we need special logic to run in parallel but not record?

**Comment by bahmutov** [comment]
We cannot record in that case because we don’t have any environment variables, so the run becomes normal serial run without recording
