### ISSUE TITLE
Component Testing - cy.intercept not caught by cy.wait in beforeEach block

### ISSUE THREAD

**Issue by ajlongcoy21** [cypress-io/cypress#24048]
### Current behavior

While testing a component, in a beforeEach block the cy.intercept setup is not being caught by the cy.wait during the second test. 

Note: the API call is activated during the mounting process of the component. 

### Failure

<img width="738" alt="Screen Shot 2022-09-29 at 9 10 41 PM" src="https://user-images.githubusercontent.com/2608643/193171748-2b969e69-1387-463a-9909-fdd5a9d813be.png">

### Stack Trace

```console
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `getImage`. No request ever occurred.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `<IngredientCard />`
    at cypressErr (http://localhost:5174/__cypress/runner/cypress_runner.js:160831:18)
    at Object.errByPath (http://localhost:5174/__cypress/runner/cypress_runner.js:160900:10)
    at checkForXhr (http://localhost:5174/__cypress/runner/cypress_runner.js:146070:92)
    at <unknown> (http://localhost:5174/__cypress/runner/cypress_runner.js:146093:28)
From previous event:
    at whenStable (http://localhost:5174/__cypress/runner/cypress_runner.js:152665:65)
    at <unknown> (http://localhost:5174/__cypress/runner/cypress_runner.js:152095:14)
From Your Spec Code:
    at Context.<anonymous> (/Users/alanlongcoy/Desktop/RecipeApp/family_recipe_app_vue/cypress/component/IngredientCard.cy.js:25:8)
    at runnable.fn (http://localhost:5174/__cypress/runner/cypress_runner.js:157625:19)
    at callFn (http://localhost:5174/__cypress/runner/cypress_runner.js:107910:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:5174/__cypress/runner/cypress_runner.js:107897:7)
    at <unknown> (http://localhost:5174/__cypress/runner/cypress_runner.js:164934:30)
    at PassThroughHandlerContext.finallyHandler (http://localhost:5174/__cypress/runner/cypress_runner.js:7872:23)
    at PassThroughHandlerContext.tryCatcher (http://localhost:5174/__cypress/runner/cypress_runner.js:11318:23)
    at Promise._settlePromiseFromHandler (http://localhost:5174/__cypress/runner/cypress_runner.js:9253:31)
```

### Desired behavior

I would expect that it would pass for each test.

### Repository

https://github.com/ajlongcoy21/family_recipe_app_vue

### Failing Test

<img width="1120" alt="Screen Shot 2022-09-29 at 9 45 10 PM" src="https://user-images.githubusercontent.com/2608643/193172312-9fff2177-7a1b-4cbb-851b-5f02ed8c36f3.png">

### Debug Log

[CypressDebugError.docx](https://github.com/cypress-io/cypress/files/9680070/CypressDebugError.docx)

### Test Setup

```javascript
import IngredientCard from "../../src/components/IngredientCard.vue";

describe("<IngredientCard />", () => {
  // code

  beforeEach(() => {
    // API Intercepts
    cy.intercept(
      "GET",
      "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      { fixture: "ingredients/images/apple.jpg" }
    ).as("getImage");
    // Mount Component
    cy.mount(IngredientCard, {
      propsData: {
        name: "apple",
        image: "apple.jpg",
        id: 9003,
      },
    });
    // Wait to catch API call
    cy.wait("@getImage");
  });

  it("renders", () => {
    // test code
  });

  it("has correct information displayed when ingredient information is present", () => {
    // test code
});
```

### Cypress Version

10.9.0

### Node version

16.17.0

### Operating System

macOS 12.6

**Comment by astone123** [comment]
@ajlongcoy21 this is an issue with browser caching. When the first test runs, the apple image is fetched over the network and gets intercepted by `cy.intercept` correctly. However, when the second test runs, the browser has already loaded the apple image from that same URL, so the request doesn't go over the network and it is instead retrieved from the cache.

Because the image isn't fetched over the network the second time, `cy.intercept` doesn't see the request so it times out waiting for this route to be called. One way that you can work around this by modifying the response headers to instruct the browser not to cache the image:

```javascript
  cy.intercept(
    "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
    (req) => {
      req.on('before:response', (res) => {
        // force image to not be cached
        res.headers['cache-control'] = 'no-store'
      })
    }
  ).as('getImage');
```
This way, every time the image is requested, it is retrieved over the network rather than from the browser cache.

You can read more about this in [our docs section about intercept and caching](https://docs.cypress.io/api/commands/intercept#cy-intercept-and-request-caching).

**Comment by ajlongcoy21** [comment]
@astone123, thank you for the response! My apologies for my lack of understanding / knowledge. I will read those docs you referenced and work to update the code :).
