### ISSUE TITLE
@cypress/webpack-preprocessor 5.13.0 causes module error

### ISSUE THREAD

**Issue by dobladov** [cypress-io/cypress#24051]
### Current behavior

After updating from *@cypress/webpack-preprocessor* `5.12.2` to version `5.13.0` this error appears
```bash
Error: Cannot find module 'md5'
Require stack:
- /Users/redacted/redacted/react-shop/node_modules/@cypress/webpack-preprocessor/dist/lib/utils.js
- /Users/redacted/redacted/react-shop/node_modules/@cypress/webpack-preprocessor/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/redacted/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object. (/Users/redacted/redacted/react-shop/node_modules/@cypress/webpack-preprocessor/dist/lib/utils.js:32:29)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Object.require.extensions. [as .js] (/Users/redacted/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object. (/Users/redacted/redacted/react-shop/node_modules/@cypress/webpack-preprocessor/dist/index.js:33:31)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Object.require.extensions. [as .js] (/Users/redacted/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at ModuleWrap. (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

`node_modules/@cypress/webpack-preprocessor/dist/lib/utils.js:32:29`
```javascript
  30 | var os = __importStar(require("os"));
  31 | var path_1 = __importDefault(require("path"));
> 32 | var md5_1 = __importDefault(require("md5"));
     |                             ^
  33 | var bluebird_1 = __importDefault(require("bluebird"));
  34 | var fs_extra_1 = __importDefault(require("fs-extra"));
  35 | function createDeferred() {
  36 |     var resolve;
```

### Desired behavior

Cypress should work without an issue.

### Test code to reproduce

Run Cypress `10.8.0` or newer with @cypress/webpack-preprocessor `5.13.0`

### Cypress Version

10.8.0

### Node version

v18.8.0

### Operating System

macOS 12.6

**Comment by dobladov** [comment]
Might be caused because `md5` was added as a devDependency
https://github.com/cypress-io/cypress/pull/23283/files#diff-2652bb78004354b4c0896b93e91646e537d1bf0e5c1e5163b2a997f1aa655957R53

**Comment by PericlesFeltrin** [comment]
I have the same problem when I run with Cypress ```8.3.0``` and @cypress/webpack-preprocessor ```5.13.0```.

**Comment by mahdikhashan** [comment]
I faced the same issue with Cypress 9.7.0 @cypress/webpack-preprocessor 5.13.0.

**Comment by chrisbreiding** [comment]
Thanks for reporting this issue. I've fixed it in https://github.com/cypress-io/cypress/pull/24098 and will hopefully have a new version of `@cypress/webpack-preprocessor` out soon.

**Comment by chrisbreiding** [comment]
[`@cypress/webpack-preprocessor v5.13.1`](https://www.npmjs.com/package/@cypress/webpack-preprocessor) has been released with the fix for this issue.
