### ISSUE TITLE
Can't import external modules to custom commands file

### ISSUE THREAD

**Issue by ashwinizanzad31** [cypress-io/cypress#24061]
### Current behavior

I have custom commads  written inside commands.js. I need to import external module to it Like import { MyCustomClass } from '../../imap-client/readmail';

import { emailCont } from '../../imap-client/readmail';

Cypress.Commands.add('getEmailContent', () => {
    emailCont.getEmail()

})

![image](https://user-images.githubusercontent.com/69709507/193285530-358071d1-54f9-4a29-9698-8e24ef16bd79.png)

When i am running my cypress tests , its throwing below error. Looks like it dont allow to import and use external functions
![image](https://user-images.githubusercontent.com/69709507/193285741-898ac13a-89b1-427a-91bd-00abcedcb562.png)

### Desired behavior

It should allow to import modules and call external functions within custom command block

### Test code to reproduce

// commands.js
```
import { emailCont } from '../../imap-client/readmail';


Cypress.Commands.add('getEmailContent', () => {
    emailCont.getEmail()

})
```
//spec.cy.js
```
 it('Test sign in with access', () => {
    cy.getEmailContent();
    cy.visit(Cypress.config('accessUrl'))
  })
```
### Cypress Version

10.9.0

### Node version

v16.17.0

### Operating System

windows

### Debug Logs

```shell
1) An uncaught error was detected outside of a test

  0 passing (400ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Invalid Version:

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at new SemVer (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:74499:11)
      at compare (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:74772:10)
      at Function.gte (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:74821:10)
      at Object.eval (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:75425:12)
      at ./node_modules/utf7/utf7.js (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:75542:30)
      at __webpack_require__ (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:20:30)
      at Object.eval (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:58072:12)
      at ./node_modules/imap/lib/Connection.js (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:60195:30)
      at __webpack_require__ (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:20:30)
      at ./imap-client/readmail.js (http://localhost:56106/__cypress/tests?p=cypress\support\e2e.js:39141:12)
```

**Comment by astone123** [comment]
@ashwinizanzad31 I tried to reproduce this by importing an external module (from the root of my project) into my commands file, and then calling it from a test. This works for me. Could you provide an example project that reproduces this issue? Thanks

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by gvimalan** [comment]
> @ashwinizanzad31 I tried to reproduce this by importing an external module (from the root of my project) into my commands file, and then calling it from a test. This works for me. Could you provide an example project that reproduces this issue? Thanks

Can you please show the code / how you did it? Do you have it somewhere in GitHub?
