### ISSUE TITLE
Cypress Compatibility with Openshift and RHEL 8 - FIPS Mode

### ISSUE THREAD

**Issue by apatel0708** [cypress-io/cypress#24156]
### What would you like?

Im looking for either a Cypress Binary that uses sha256 hashing instead of md5 or if there is a cypress binary already created that is FIPS compliant.

### Why is this needed?

We are attempting to run Cypress tests but are unable to due to FIPS Compliance

**Comment by nagash77** [comment]
Hello @apatel0708 Cypress does not use any encryption today.  It may internally hash things but only to generate stable/unique IDs.  Are you suggesting we need to swap out the algorithm to use sha256 rather md5 or are you asking us to generate a checksum.txt that you can use to verify that published binaries have not been altered?

**Comment by nagash77** [comment]
@apatel0708 Can you help point us to what openshift / RHEL 8 is saying that prevents you from using Cypress in that environment.

**Comment by apatel0708** [comment]
@nagash77  We resolved the issue modifying some of the js files for hashing

here was the original error:

Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:58:5)
    at successLoader (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:23:5)
    at LOADER_EXECUTION (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /builds/qvZ8Rvfw/0/gitlab/home/cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by nagash77** [comment]
Ok glad you have figured it out!

**Comment by sathismr** [comment]
Hi @apatel0708 , Could you please elaborate how did you fix this? Thanks!
