### ISSUE TITLE
Opening baseUrl in Webkit results in blank page

### ISSUE THREAD

**Issue by michallbanas** [cypress-io/cypress#24175]
### Current behavior

When baseUrl is not localhost, but regular website eg. https://www.michalbanas.dev, I get only blank page when using webkit (open mode), and this error `An SSL error has occurred and a secure connection to the server cannot be made ` in  headless mode. I've been facing this issue since experiment support for Webkit was released. It works good for other browsers. 

![CleanShot 2022-10-07 at 11 37 51](https://user-images.githubusercontent.com/63734693/194662738-0ab5ed83-15e0-4566-a7e1-d82d81688d6d.png)

### Desired behavior

Possibility to use webkit in cypress with any url. 

### Test code to reproduce

Example project:

https://github.com/michallbanas/cypress-webkit-blankPage

### Cypress Version

10.9.0

### Node version

18.7.0

### Operating System

macOS 12.6

### Debug Logs

```shell
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.9.0                                                                         │
  │ Browser:        WebKit 16 (headless)                                                           │
  │ Node Version:   v18.7.0 (/Users/michalbanas/.nvm/versions/node/v18.7.0/bin/node)               │
  │ Specs:          1 found (test.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  │ Experiments:    experimentalWebKitSupport=true                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  test.cy.js                                                                      (1 of 1)
page.goto: An SSL error has occurred and a secure connection to the server cannot be made.
=========================== logs ===========================
navigating to "https://michalbanas.dev/__/#/specs/runner?file=cypress/e2e/test.cy.js", waiting until "load"
============================================================
page.goto: An SSL error has occurred and a secure connection to the server cannot be made.
=========================== logs ===========================
navigating to "https://michalbanas.dev/__/#/specs/runner?file=cypress/e2e/test.cy.js", waiting until "load"
============================================================
    at WebKitAutomation.reset (/Users/michalbanas/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/webkit-automation.js:134:37)
    at Function.create (/Users/michalbanas/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/webkit-automation.js:108:9)
    at Object.open (/Users/michalbanas/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/webkit.js:84:20)
    at Object.open (/Users/michalbanas/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/index.js:109:27)
    at OpenProject.relaunchBrowser (/Users/michalbanas/Library/Caches/Cypress/10.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/open_project.js:152:20)
```

### Other

Hope I provided everything needed, it's my first issue here 🙂

**Comment by a-kotova** [comment]
Getting a similar error in headless & browser mode
Apple M1 macOS Monterey 12.2.1
Cypress 10.11.0
Node 16.14.2

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/52243657/209696030-1aa18e18-20a5-4af2-b6ee-955d483d808f.png">

**Comment by protono** [comment]
Cypress 12.8.1
Windows 10

1. headless:

```npx cypress run --browser webkit```

```
...
page.goto: WebKit encountered an internal error
=========================== logs ===========================
navigating to "{baseUrl}/__/#/specs/runner?file=cypress\e2e\change-address.cy.ts", waiting until "load"
============================================================
page.goto: WebKit encountered an internal error
=========================== logs ===========================
navigating to "{baseUrl}/__/#/specs/runner?file=cypress\e2e\change-address.cy.ts", waiting until "load"
============================================================
    at h.reset (<embedded>:4655:14631)
    at async h.create (<embedded>:4655:13936)
    at async Object.f (<embedded>:4655:21027)
    at async Object.open (<embedded>:4655:26066)
    at async v.relaunchBrowser (<embedded>:4721:433109)
```

2. ide

```npx cypress open```

Start E2E testing in WebKit

![image](https://user-images.githubusercontent.com/35472107/226344749-a85ce69f-bc18-452b-97df-b93f4f91bcec.png)

**Comment by AtofStryker** [comment]
possibly related to https://github.com/microsoft/playwright/issues/9466

**Comment by AtofStryker** [comment]
@a-kotova what version of `playwright-webkit` are you using? Have you tried upgrading Cypress to `12.8.1`?

**Comment by AtofStryker** [comment]
Looks to still be an issue on `12.8.1` with `playwright-webkit@1.31.2`

**Comment by jennifer-shehane** [comment]
Closing as I suspect this is likely fixed with our updating webkit. 

Open a new issue if you’re experiencing something similar.
