### ISSUE TITLE
Failure during cypress verify step Cypress --no-sandbox --smoke-test

### ISSUE THREAD

**Issue by kenobi-io** [cypress-io/cypress#24219]
### Current behavior

npx cypress verify

### Test code to reproduce

npm create vite@latest my-awesome-app -- --template react
cd my-awesome-app
npm install
npm install cypress -D
npx cypress open

### Cypress Version

10.10.0

### Node version

v16.14.2

### Operating System

wsl: linux-x64 (Ubuntu - 20.04)

### Debug Logs

```shell
❯ DEBUG=cypress:* npx cypress verify
  cypress:cli:cli cli starts with arguments ["/home/.../.nvm/versions/node/v16.14.2/bin/node","/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/.bin/cypress","verify"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +0ms
  cypress:cli parsed cli options {} +1ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /home/.../.cache/Cypress/10.10.0/Cypress/Cypress +1ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /home/.../.cache/Cypress/10.10.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/.../.cache/Cypress/10.10.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 10.10.0 installed in: /home/.../.cache/Cypress/10.10.0/Cypress +2ms
  cypress:cli could not read binary_state.json file at "/home/.../.cache/Cypress/10.10.0/binary_state.json" +3ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 10.10.0 +0ms


  cypress:cli clearing out the verified version +3ms
  cypress:cli DISPLAY environment variable is set to 192.168.1.67:0.0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +1ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/.../.cache/Cypress/10.10.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=172 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command timed out after 30000 milliseconds: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=172
Timed out
2022-10-12T07:16:50.178Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:16:50.211Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:16:50.633Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:16:50.660Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:16:50.664Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.664Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.665Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 172 } }
2022-10-12T07:16:50.666Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:16:50.666Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:16:50.667Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:16:50.667Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }
2022-10-12T07:16:50.667Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }
    at timeoutKill (/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/execa/lib/kill.js:65:23)
    at Timeout._onTimeout (/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/execa/lib/kill.js:81:4)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  timedOut: true,
  signal: 'SIGTERM',
  originalMessage: 'Timed out',
  shortMessage: 'Command timed out after 30000 milliseconds: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=172\n' +
    'Timed out',
  command: '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=172',
  exitCode: undefined,
  signalDescription: 'Termination',
  stdout: '',
  stderr: '2022-10-12T07:16:50.178Z cypress:ts registering ts-node on directory undefined\n' +
    '2022-10-12T07:16:50.211Z cypress:ts Running without ts-node hook in environment "production"\n' +
    '2022-10-12T07:16:50.633Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache\n' +
    '2022-10-12T07:16:50.660Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers\n' +
    "2022-10-12T07:16:50.664Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]\n" +
    "2022-10-12T07:16:50.664Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]\n" +
    "2022-10-12T07:16:50.665Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 172 } }\n" +
    "2022-10-12T07:16:50.666Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }\n" +
    "2022-10-12T07:16:50.666Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }\n" +
    "2022-10-12T07:16:50.667Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }\n" +
    "2022-10-12T07:16:50.667Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }\n" +
    "2022-10-12T07:16:50.667Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }",
  failed: true,
  isCanceled: false,
  killed: false
} +30s
  cypress:cli error message: 2022-10-12T07:16:50.178Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:16:50.211Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:16:50.633Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:16:50.660Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:16:50.664Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.664Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.665Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 172 } }
2022-10-12T07:16:50.666Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:16:50.666Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:16:50.667Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:16:50.667Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }
2022-10-12T07:16:50.667Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 } +1ms
  cypress:cli error timedOut is true +0ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' } +30s

Cypress verification timed out.

This command failed with the following output:

/home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=172

----------

2022-10-12T07:16:50.178Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:16:50.211Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:16:50.633Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:16:50.660Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:16:50.664Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.664Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ]
2022-10-12T07:16:50.665Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 172 } }
2022-10-12T07:16:50.666Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:16:50.666Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:16:50.667Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:16:50.667Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }
2022-10-12T07:16:50.667Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=172' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 172, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 172 }

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 10.10.0
```

### Other
```shell
❯ DEBUG=cypress:* npx cypress open  
  cypress:cli:cli cli starts with arguments ["/home/.../.nvm/versions/node/v16.14.2/bin/node","/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +53ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /home/.../.cache/Cypress/10.10.0/Cypress/Cypress +2ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /home/.../.cache/Cypress/10.10.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/.../.cache/Cypress/10.10.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 10.10.0 installed in: /home/.../.cache/Cypress/10.10.0/Cypress +2ms
  cypress:cli could not read binary_state.json file at "/home/.../.cache/Cypress/10.10.0/binary_state.json" +3ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 10.10.0 +0ms
It looks like this is your first time using Cypress: 10.10.0


  cypress:cli clearing out the verified version +3ms
  cypress:cli DISPLAY environment variable is set to 192.168.1.67:0.0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +1ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/.../.cache/Cypress/10.10.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=117 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command timed out after 30000 milliseconds: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=117
Timed out
2022-10-12T07:30:35.239Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:30:35.272Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:30:35.694Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:30:35.722Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:30:35.727Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 117 } }
2022-10-12T07:30:35.729Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:30:35.729Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:30:35.729Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:30:35.729Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }
2022-10-12T07:30:35.730Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }
    at timeoutKill (/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/execa/lib/kill.js:65:23)
    at Timeout._onTimeout (/home/.../repos/commersion/lm/ggg/my-awesome-app/node_modules/execa/lib/kill.js:81:4)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  timedOut: true,
  signal: 'SIGTERM',
  originalMessage: 'Timed out',
  shortMessage: 'Command timed out after 30000 milliseconds: /home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=117\n' +
    'Timed out',
  command: '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=117',
  exitCode: undefined,
  signalDescription: 'Termination',
  stdout: '',
  stderr: '2022-10-12T07:30:35.239Z cypress:ts registering ts-node on directory undefined\n' +
    '2022-10-12T07:30:35.272Z cypress:ts Running without ts-node hook in environment "production"\n' +
    '2022-10-12T07:30:35.694Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache\n' +
    '2022-10-12T07:30:35.722Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers\n' +
    "2022-10-12T07:30:35.727Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]\n" +
    "2022-10-12T07:30:35.727Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]\n" +
    "2022-10-12T07:30:35.727Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 117 } }\n" +
    "2022-10-12T07:30:35.729Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }\n" +
    "2022-10-12T07:30:35.729Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }\n" +
    "2022-10-12T07:30:35.729Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }\n" +
    "2022-10-12T07:30:35.729Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }\n" +
    "2022-10-12T07:30:35.730Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }",
  failed: true,
  isCanceled: false,
  killed: false
} +30s
  cypress:cli error message: 2022-10-12T07:30:35.239Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:30:35.272Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:30:35.694Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:30:35.722Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:30:35.727Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 117 } }
2022-10-12T07:30:35.729Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:30:35.729Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:30:35.729Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:30:35.729Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }
2022-10-12T07:30:35.730Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 } +1ms
  cypress:cli error timedOut is true +0ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' } +30s

Cypress verification timed out.

This command failed with the following output:

/home/.../.cache/Cypress/10.10.0/Cypress/Cypress --no-sandbox --smoke-test --ping=117

----------

2022-10-12T07:30:35.239Z cypress:ts registering ts-node on directory undefined
2022-10-12T07:30:35.272Z cypress:ts Running without ts-node hook in environment "production"
2022-10-12T07:30:35.694Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/cache
2022-10-12T07:30:35.722Z cypress:server:appdata path: /home/.../.config/Cypress/cy/production/browsers
2022-10-12T07:30:35.727Z cypress:server:cypress starting cypress with argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args argv array: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ]
2022-10-12T07:30:35.727Z cypress:server:args parsed argv options { options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 117 } }
2022-10-12T07:30:35.729Z cypress:server:args argv parsed: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app' }
2022-10-12T07:30:35.729Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2022-10-12T07:30:35.729Z cypress:server:args options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {} }
2022-10-12T07:30:35.729Z cypress:server:args argv options: { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }
2022-10-12T07:30:35.730Z cypress:server:cypress from argv [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=117' ] got options { _: [ '/home/.../.cache/Cypress/10.10.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 117, invokedFromCli: false, cwd: '/home/.../repos/commersion/lm/ggg/my-awesome-app', config: {}, pong: 117 }

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 10.10.0
```

**Comment by nagash77** [comment]
@kenobi-io I see you are running WSL.  Unfortunately we do not fully support WSL and have seen issues with using it in conjunction with Cypress.  Can you replicate this issue on a native ubuntu install?  Or a native windows install?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by kenobi-io** [comment]
> @kenobi-io I see you are running WSL. Unfortunately we do not fully support WSL and have seen issues with using it in conjunction with Cypress. Can you replicate this issue on a native ubuntu install? Or a native windows install?

No I can't, I exactly need to wsl
