### ISSUE TITLE
Module not found: Error: Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by tommy0831** [cypress-io/cypress#24234]
### Current behavior

I installed a third party package.  When I try to use it in Cypress with Typescript, I get this error.  I have tried isolating the problem by creating a JS and TS project and using that package.  It works fine.  So, I know it's an issue in Cypress.  More specifically, I think it's the @cypress/webpack-preprocessor.  

<img width="1786" alt="Screen Shot 2022-10-12 at 1 46 38 PM" src="https://user-images.githubusercontent.com/98181057/195449892-78c3239d-0d45-4d3b-a559-5e5c37847d30.png">

### Desired behavior

Able to use the third party package

### Test code to reproduce

```
webpack.config.js
`
const path = require("path");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

module.exports = {
  resolve: {
    extensions: [".ts", ".js"],
    fallback: {
      fs: false,
    },
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: "ts-loader",
            options: {
              transpileOnly: true,
            },
          },
        ],
      },
    ],
  },
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "dist"),
  },
  stats: {
    colors: true,
    modules: true,
    reasons: true,
    errorDetails: true,
  },
  plugins: [new NodePolyfillPlugin()],
};

```

### Cypress Version

9.2.1

### Node version

v17.3.1

### Operating System

macOS 12.5

### Debug Logs

```shell
cypress:webpack errored bundling /<path_to_my_spec>/mytest.spec.ts.js Webpack Compilation Error
Module not found: Error: Can't resolve 'async_hooks' in '<path_to_project>/node_modules/<thirdparty_package>/dist' +2ms
  cypress:webpack - compile finished for /<path_to_my_spec>/mytest.spec.ts, initial? true +35ms
  cypress:server:plugins promise rejected for id inv8 ':' Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'async_hooks' in '<path_to_project>/node_modules/<thirdparty_package>/dist'
    at Watching.handle [as handler] (<path_to_project>/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:290:9
    at Hook.eval [as callAsync] (eval at create (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/<path_to_project>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (<path_to_project>/node_modules/webpack/lib/Watching.js:287:28)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:209:21
    at Compiler.emitRecords (<path_to_project>/node_modules/webpack/lib/Compiler.js:919:5)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:187:22
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:882:27
    at <path_to_project>/node_modules/neo-async/async.js:2818:7
    at done (<path_to_project>/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (<path_to_project>/node_modules/webpack/lib/Compiler.js:714:8)
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:802:19
    at <path_to_project>/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) +1s
  cypress:server:controllers:spec preprocessor error for spec '/<path_to_my_spec>/mytest.spec.ts.js': Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'async_hooks' in '<path_to_project>/node_modules/<third_party_package>/dist'
    at Watching.handle [as handler] (<path_to_project>/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:290:9
    at Hook.eval [as callAsync] (eval at create (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (<path_to_project>/node_modules/webpack/lib/Watching.js:287:28)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:209:21
    at Compiler.emitRecords (<path_to_project>/node_modules/webpack/lib/Compiler.js:919:5)
    at <path_to_project>/node_modules/webpack/lib/Watching.js:187:22
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (<path_to_project>/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:882:27
    at <path_to_project>/node_modules/neo-async/async.js:2818:7
    at done (<path_to_project>/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (<path_to_project>/node_modules/webpack/lib/Compiler.js:714:8)
    at <path_to_project>/node_modules/webpack/lib/Compiler.js:802:19
    at <path_to_project>/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) +1s
Webpack Compilation Error
Module not found: Error: Can't resolve 'async_hooks' in '<path_to_project>/node_modules/<third_party_package>/dist'
```

**Comment by AtofStryker** [comment]
Hi @tommy0831 . Thank you for opening an issue. Would you be able to provide a reproduction repository to help me recreate the problem? Also, have you tried using node 16 or 18? We do not support Node 17.

**Comment by tommy0831** [comment]
I figured it out.  NodeJS modules cannot be called directly in Cypress.  You need to use cy.task to wrap NodeJS code and expose it to your test code.  https://docs.cypress.io/api/commands/task

**Comment by cjshelton** [comment]
@tommy0831 I'm having this same issue - it's good to hear you solved it with `cy.task`. Mind sharing some example code of how you used it?
