### ISSUE TITLE
CYPRESS CRASH: Pattern Is too long

### ISSUE THREAD

**Issue by alecmestroni** [cypress-io/cypress#24327]
### Current behavior

Cypress crash when trying to intercept a base64 url image with this error:
`
pattern is too long
TypeError: pattern is too long...
`

### Desired behavior

Cypress shouldnt crash but should complete the intercept correctly

### Test code to reproduce

Code:
```
for (let i = 1; i <= totalPhoto; i++) {
	cy.fixture('img/test-replaced.jpg').then(jpg => {
		let url = 'data:image/png;base64,' + jpg
		cy.intercept({
			method: 'GET',
			url: url,
		}).as('imageRequest')
		cy.wait('@imageRequest', { timeout: 100000 }).then(({ response }) => {
			expect(response.statusCode).to.eq(200)
		})
		cy.get('slide', { timeout: 100000 }).should('have.length', i)
	})
}
```

also tried in this way but same error occurred
```
for (let i = 1; i <= totalPhoto; i++) {
	cy.fixture('img/base64-replaced.json').then(jpg => {
		let url = 'data:image/png;base64,' + jpg.base64
		cy.intercept({
			method: 'GET',
			url: url,
		}).as('imageRequest')
		cy.wait('@imageRequest', { timeout: 100000 }).then(({ response }) => {
			expect(response.statusCode).to.eq(200)
		})
		cy.get('slide', { timeout: 100000 }).should('have.length', i)
	})
}
```
The base64.replaced.json is the base64 of the file attached below 

U dont need to actually intercept the request, its crashes when trying it

![test-replaced](https://user-images.githubusercontent.com/62354989/196994215-3f852efe-0d87-40cd-b465-80636d5cce03.jpg)

### Cypress Version

10.10

### Node version

v16.15.1

### Operating System

Win 10, 19044.1620

### Debug Logs

```shell
pattern is too long
TypeError: pattern is too long
    at assertValidPattern (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\minimatch\minimatch.js:279:11)   
    at minimatch (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\minimatch\minimatch.js:116:3)
    at stringMatch (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\net-stubbing\lib\server\route-matching.js:26:41)
    at _doesRouteMatch (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\net-stubbing\lib\server\route-matching.js:46:14)
    at getRoutesForRequest (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\net-stubbing\lib\server\route-matching.js:104:32)
    at getRoutesForRequest.next (<anonymous>:null:null)
    at Object.InterceptRequest (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\net-stubbing\lib\server\middleware\request.js:31:73)
    at C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:104:28
    at Promise._execute (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:79:10)   
    at runMiddlewareStack (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:52:16)       
    at Object.next (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:81:26)
    at Object.SendToDriver (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\request-middleware.js:114:10)
    at C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:104:28
    at Promise._execute (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:79:10)   
    at runMiddlewareStack (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:52:16)       
    at Object.next (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\index.js:81:26)
    at C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\request-middleware.js:106:14
    at Timeout._onTimeout (C:\Users\*\AppData\Local\Cypress\Cache\10.10.0\Cypress\resources\app\packages\proxy\lib\http\util\prerequests.js:120:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by alecmestroni** [comment]
So I publish a repo [here](https://github.com/alecmestroni/cypress-crash).
@nagash77 
To reproduce:
**Open cypress** (cypress open)
**Select e2e
Choose the 'cypress-crash.cy' file
Run the test
It'll fail (but it doesnt matter)
Wait between 2 and 5 minut with the test runned opened
After that time cypress will crash** 

If cypress isnt crashed yet, try to rename the 'cypress-crash.cy' in something else like 'cypress-testsupport.cy'
After this cypress will crash with the same error

**Comment by alecmestroni** [comment]
Some news? @nagash77

**Comment by mschile** [comment]
@alecmestroni, it doesn't appear the [repo](https://github.com/alecmestroni/cypress-crash) you created is public as I can't access it. Could you please make it public or give me privs. Thanks!

**Comment by alecmestroni** [comment]
> @alecmestroni, it doesn't appear the [repo](https://github.com/alecmestroni/cypress-crash) you created is public as I can't access it. Could you please make it public or give me privs. Thanks!

Done! @mschile

**Comment by mschile** [comment]
Thanks @alecmestroni! We use [minimatch](https://docs.cypress.io/api/utilities/minimatch) for our [route matching](https://docs.cypress.io/api/commands/intercept#routeMatcher-RouteMatcher) which has a max pattern length of [65536](https://github.com/isaacs/minimatch/blob/6410ef32f59e4842121ca13eefacdf0b3da8533c/minimatch.js#L122). The image you are trying to load has a length of 110274. You could try substring'ing the intercept url:

`let url = ('data:image/png;base64,' + jpg).substring(0, 65536 - 1)`

**Comment by alecmestroni** [comment]
Hello @mschile, thanks for the answer.
the solution you have provided is not working for my purpose.
Is this the correct way to intercept a base64 img? 
Is cypress able to do that? 
If it isn't clear I'm tring to intercept this req 
![image](https://user-images.githubusercontent.com/62354989/198253791-564b36b8-6c6c-4120-8a7c-a14ef1c5dc7f.png)
but I dont see it in the cypress log on the left pane, so I doubt that cypress can intercept it..

**Comment by mschile** [comment]
Ah yes, sorry for the confusion, intercept is designed for intercepting http/https network requests and not data urls.
