### ISSUE TITLE
Hard corded value of "integration", needs to update as "e2e" in stepDefinitionPath in node_modules

### ISSUE THREAD

**Issue by DevPerers** [cypress-io/cypress#24376]
### Current behavior

I am having Cypress project with Cucumber.
So I first clone the project into my local folder.
Then I ran following two commands
_npm install cypress --save-dev
npm install cypress-cucumber-preprocessor --save-dev_
I am getting an error, when I try to execute the Cypress by, _npx cypress open_
In order to fix the error I need to change the hard coded "integration" value into "e2e".
For that I needs to open the "stepDefinitionPath.js" file from the following location. 
Go to; node_modules > cypress-cucumber-preprocessor > lib, Replace the following code line with "e2e",
confStepDefinitions || cypress${path.sep}integration;
as followed
confStepDefinitions || cypress${path.sep}e2e;
Saved the file.

### Debug logs

```Text
Error: We've tried to resolve your step definitions at cypress/integration, but that doesn't seem to exist. As of version 2.0.0 it's required to set step_definitions in your cypress-cucumber-preprocessor configuration. Look for nonGlobalStepDefinitions and add stepDefinitions right next to it. It should match your cypress configuration has set for integrationFolder. We no longer rely on getting information from that file as it was unreliable and problematic across Linux/MacOS/Windows especially since the config file could have been passed as an argument to cypress.
    at module.exports (/home/devperera/VSC/Cypress/AAA/trax-cypress-test-automation/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js:20:15)
    at Object.handler (/home/devperera/VSC/Cypress/AAA/trax-cypress-test-automation/node_modules/cypress-cucumber-preprocessor/lib/index.js:78:16)
    at invoke (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:43:18)
    at /home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/preprocessor.js:47:8)
    at RunPlugins.execute (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:174:29)
    at EventEmitter.<anonymous> (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:279:12)
    at EventEmitter.emit (node:events:527:28)
    at process.<anonymous> (/home/devperera/.cache/Cypress/10.10.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### Cypress Version

10.10.0

### Node version

v16.15.1

### Package Manager

npm

### Package Manager Version

v16.15.1

### Operating system

Linux

### Operating System Version

20.04

**Comment by mschile** [comment]
@DevPerers, I believe you are using a no longer supported version of the cucumber preprocessor. Can you try using this one https://github.com/badeball/cypress-cucumber-preprocessor.

**Comment by DevPerers** [comment]
@mschile thanks for the reply. I tried with the solution you mention, but issue still exist. In my project I am using JavaScript only, not typescript.

**Comment by mschile** [comment]
@DevPerers, I successfully setup a project using the cucumber preprocessor with JavaScript if you want to take a look at it: https://github.com/mschile/issue-24376

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Luiz-henrique-lopes-viana** [comment]
Estou com esse  mesmo problema

**Comment by rodrigo0oliveira** [comment]
Anyone fix it? I have the same issue here using typescript, the error is : Error: We've tried to resolve your step definitions at cypress/e2e/step_definitions/features/**/*.ts  but that doesn't seem to exist.

**Comment by jennifer-shehane** [comment]
Right now there's no indication that this is a Cypress issue. This may be an issue with cucumber or particular setups.

**Comment by DevPerers** [comment]
I am not facing this issue anymore

**Comment by rodrigo0oliveira** [comment]
> I am not facing this issue anymore

Do you have any repository with the correct config to share? I still have this issue .
