### ISSUE TITLE
Component Test can't initialize due to ValidationError

### ISSUE THREAD

**Issue by miglesiasit12** [cypress-io/cypress#24392]
### Current behavior

This is the error that is being thrown whenever i try to start up component testing in any version higher than 10.6.0:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[721:1025/202627.842256:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
[@cypress/webpack-dev-server]: removing HtmlWebpackPlugin from configuration.
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

ValidationError: webpack Dev Server Invalid Options

options should NOT have additional properties
```

I attached a screenshot of the webpack.config that im using

### Desired behavior

Load component testing without any errors

### Test code to Reproduce

https://github.com/miglesiasit12/CypressIssue24392

### Cypress Version

10.11.0

### Node version

v16.13.1

### Operating System

MacOs 11.6.1/ official Cypress Linux containers

### Debug Logs

```shell
at validateOptions (/root/tmp/workspace/armature/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new Server (/root/tmp/workspace/armature/node_modules/webpack-dev-server/lib/Server.js:83:3)
    at webpackDevServer3 (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/createWebpackDevServer.js:50:20)
    at createWebpackDevServer (/root/.cache/Cypress/10.11.0/Cypress
![Screen Shot 2022-10-25 at 4 39 43 PM](https://user-images.githubusercontent.com/77424963/197879467-8105d778-3b66-4f0c-bd1a-8cca26b4fa9f.png)
/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/createWebpackDevServer.js:18:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.devS
![Screen Shot 2022-10-25 at 4 39 43 PM](https://user-images.githubusercontent.com/77424963/197877394-cc1a0fb3-5f02-456e-bb5d-3d8ab95c8390.png)
erver.create (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:94:34)wepack.config.js    at async /root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:25:24
```
![Screen Shot 2022-10-25 at 4 39 43 PM](https://user-images.githubusercontent.com/77424963/197879496-0fec255a-5f9d-4cc2-a02a-a9985b7e81f2.png)

**Comment by amehta265** [comment]
@miglesiasit12 Thank you for opening this issue and providing error logs and your webpack config.

While I investigate this would it be possible to provide a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/). This would greatly help me debug this issue.
From a quick look,  your `webpack config` seems to be correctly configured. However, I cannot be certain without trying to edit this webpack config and looking at how it interacts with Cypress.

Furthermore, have you tried to remove the `HtmlWebpackPlugin` in the `plugins` section of your config all together? We have had problems with the `HtmlWebpackPlugin` and maybe that is the cause of this issue.

**Comment by amehta265** [comment]
Unfortunately we have to close this issue due to inactivity and a lack of a reproducible example. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by miglesiasit12** [comment]
I have updated with a link to the repo to reproduce the issue

**Comment by marktnoonan** [comment]
@miglesiasit12 the link to your repo is 404 for me, is it private?

**Comment by miglesiasit12** [comment]
Sorry, just made it public.

**Comment by miglesiasit12** [comment]
https://github.com/miglesiasit12/CypressIssue24392

**Comment by marktnoonan** [comment]
Thanks for that! Confirmed this reproduces in 10.10.0, 10.11.0 and latest. So looks to have been introduced in 10.10.0. I'll forward to the team.

Notes:

There were some changes around webpack in 10.10.0: https://github.com/cypress-io/cypress/pull/24117 that might be a good starting point for this, though it doesn't seem obviously connected to me.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24392?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34
