### ISSUE TITLE
Cypress failed to make a connection to Firefox. Error: could not find CRI target

### ISSUE THREAD

**Issue by R-Schoe** [cypress-io/cypress#24421]
### Current behavior

Eynning Cypress 9.7.0 / Firefox 106 and our tests in out Gitlab CI Pipeline will intermittently fail as unable to connect to Firefox. Sometimes it will take several reruns of the pipeline job for the tests to connect to Firefox and pass.  

>cypress run --browser=firefox
It looks like this is your first time using Cypress: 9.7.0
[STARTED] Task without title.
✔ Browser application bundle generation complete.
Initial Chunk Files | Names   | Raw Size
runtime.js          | runtime |  8.34 kB |
5 unchanged chunks
Build at: 2022-10-27T11:46:24.853Z - Hash: 8b77d22b99a0d5d6 - Time: 7048ms
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning
(4797:3) autoprefixer: end value has mixed support, consider using flex-end instead
✔ Compiled successfully.
[SUCCESS] Task without title.
Opening Cypress...
[669:1027/074632.467400:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[669:1027/074632.471739:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
tput: No value for $TERM and no -T specified
==================================================================================
  (Run Starting)
  ┌──────────────────────────────────────────────────────────────────────────────
  │ Cypress:        9.7.0                                                                          │
  │ Browser:        Firefox 106 (headless)                                                         │
  │ Node Version:   v14.15.0 (/root/.nodenv/versions/14.15.0/bin/node)                             │
  │ Specs:          1 found (app.feature)                                                          │
  └──────────────────────────────────────────────────────────────────────────────
                                                                                                    
>Running:  app.feature                                                                     (1 of 1)
  Go to the home
Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
.........
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to Firefox.
This usually indicates there was a problem opening the Firefox browser.
Error: could not find CRI target
    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Desired behavior

Cypress should connect to Firefox every time to allow the tests to run. 

### Test code to reproduce

N/A

### Cypress Version

9.7.0

### Node version

14.15.0

### Operating System

centos:7.9.2009

### Debug Logs

```shell
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
  cypress:server:browsers:protocol error finding CRI target, maybe retrying { delay: 1000, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +1ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                      pids                       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │      'other'      │      9       │ '783, 814, 855, 944, 965, 967 ... 3 more items' │    0.05    │      0.97      │  679.45  │    585.32    │   750.61    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                      '548'                      │    0.05    │      0.34      │  158.26  │    166.17    │   207.27    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      4       │              '550, 703, 551, 748'               │     0      │       0        │  114.82  │    105.44    │   114.82    │
  cypress:server:util:process_profiler │    3    │     'plugin'      │      1       │                      '774'                      │     0      │      0.01      │  85.52   │    102.73    │   128.55    │
  cypress:server:util:process_profiler │    4    │      'TOTAL'      │      15      │                       '-'                       │    0.09    │      1.32      │ 1038.05  │    942.54    │   1134.37   │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
  cypress:server:browsers:protocol attempting to find CRI target... { retryIndex: 59 } +1s
  cypress:server:browsers:protocol CRI.List { host: '127.0.0.1', port: 34624, getDelayMsForRetry: [Function: getDelayMsForRetry] } +0ms
  cypress:server:browsers:protocol CRI List { numTargets: 2, targets: [ { description: '', devtoolsFrontendUrl: null, faviconUrl: '', id: '2b27a36e-3d7e-4eeb-95be-a70a8ad00370', type: 'page', url: 'http://localhost:4200/__/#/tests/integration/file-monitoring-top-revs.feature', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/page/2b27a36e-3d7e-4eeb-95be-a70a8ad00370' }, { description: 'Main process target', devtoolsFrontendUrl: '', faviconUrl: '', id: '7ddd41d3-9e39-4ba8-9316-10ca19966c30', title: 'Main process target', type: 'browser', url: '', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/browser/7ddd41d3-9e39-4ba8-9316-10ca19966c30' } ] } +4ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
  cypress:server:browsers:protocol error finding CRI target, maybe retrying { delay: 1000, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +0ms
  cypress:server:browsers:protocol attempting to find CRI target... { retryIndex: 60 } +1s
  cypress:server:browsers:protocol CRI.List { host: '127.0.0.1', port: 34624, getDelayMsForRetry: [Function: getDelayMsForRetry] } +0ms
  cypress:server:browsers:protocol CRI List { numTargets: 2, targets: [ { description: '', devtoolsFrontendUrl: null, faviconUrl: '', id: '2b27a36e-3d7e-4eeb-95be-a70a8ad00370', type: 'page', url: 'http://localhost:4200/__/#/tests/integration/file-monitoring-top-revs.feature', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/page/2b27a36e-3d7e-4eeb-95be-a70a8ad00370' }, { description: 'Main process target', devtoolsFrontendUrl: '', faviconUrl: '', id: '7ddd41d3-9e39-4ba8-9316-10ca19966c30', title: 'Main process target', type: 'browser', url: '', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/browser/7ddd41d3-9e39-4ba8-9316-10ca19966c30' } ] } +3ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
  cypress:server:browsers:protocol error finding CRI target, maybe retrying { delay: 1000, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +0ms
  cypress:server:browsers:protocol attempting to find CRI target... { retryIndex: 61 } +1s
  cypress:server:browsers:protocol CRI.List { host: '127.0.0.1', port: 34624, getDelayMsForRetry: [Function: getDelayMsForRetry] } +0ms
  cypress:server:browsers:protocol CRI List { numTargets: 2, targets: [ { description: '', devtoolsFrontendUrl: null, faviconUrl: '', id: '2b27a36e-3d7e-4eeb-95be-a70a8ad00370', type: 'page', url: 'http://localhost:4200/__/#/tests/integration/file-monitoring-top-revs.feature', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/page/2b27a36e-3d7e-4eeb-95be-a70a8ad00370' }, { description: 'Main process target', devtoolsFrontendUrl: '', faviconUrl: '', id: '7ddd41d3-9e39-4ba8-9316-10ca19966c30', title: 'Main process target', type: 'browser', url: '', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/browser/7ddd41d3-9e39-4ba8-9316-10ca19966c30' } ] } +3ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
  cypress:server:browsers:protocol error finding CRI target, maybe retrying { delay: 1000, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +0ms
  cypress:server:browsers:protocol attempting to find CRI target... { retryIndex: 62 } +1s
  cypress:server:browsers:protocol CRI.List { host: '127.0.0.1', port: 34624, getDelayMsForRetry: [Function: getDelayMsForRetry] } +0ms
  cypress:server:browsers:protocol CRI List { numTargets: 2, targets: [ { description: '', devtoolsFrontendUrl: null, faviconUrl: '', id: '2b27a36e-3d7e-4eeb-95be-a70a8ad00370', type: 'page', url: 'http://localhost:4200/__/#/tests/integration/file-monitoring-top-revs.feature', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/page/2b27a36e-3d7e-4eeb-95be-a70a8ad00370' }, { description: 'Main process target', devtoolsFrontendUrl: '', faviconUrl: '', id: '7ddd41d3-9e39-4ba8-9316-10ca19966c30', title: 'Main process target', type: 'browser', url: '', webSocketDebuggerUrl: 'ws://127.0.0.1:34624/devtools/browser/7ddd41d3-9e39-4ba8-9316-10ca19966c30' } ] } +3ms
  cypress:server:browsers:protocol error finding CRI target, maybe retrying { delay: undefined, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +0ms
  cypress:server:browsers:protocol failed to connect to CDP { connectOpts: { host: '127.0.0.1', port: 34624, getDelayMsForRetry: [Function: getDelayMsForRetry] }, err: Error: could not find CRI target at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14) at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28) at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5)  } +5ms
  cypress:server:cypress exiting with err Error: could not find CRI target
    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 {
  isCypressErr: true,
  type: 'FIREFOX_COULD_NOT_CONNECT',
  details: 'Error: could not find CRI target\n' +
    '    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)\n' +
    '    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)\n' +
    '    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n',
  messageMarkdown: 'Cypress failed to make a connection to Firefox.\n' +
    '\n' +
    'This usually indicates there was a problem opening the Firefox browser.',
  originalError: Error: could not find CRI target
      at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
      at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
      at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
   {
    isCypressErr: true,
    type: 'CDP_COULD_NOT_CONNECT',
    details: 'Error: could not find CRI target\n' +
      '    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)\n' +
      '    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)\n' +
      '    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n',
    messageMarkdown: 'Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.\n' +
      '\n' +
      'This usually indicates there was a problem opening the Firefox browser.\n' +
      '\n' +
      'The CDP port requested was `34624`.',
    originalError: Error: could not find CRI target
        at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
        at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
        at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ,
    stackWithoutMessage: '    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)\n' +
      '    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)\n' +
      '    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n'
  },
  stackWithoutMessage: '    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)\n' +
    '    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)\n' +
    '    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n'
} +55s
Cypress failed to make a connection to Firefox.
This usually indicates there was a problem opening the Firefox browser.
Error: could not find CRI target
    at lazyAssLogic (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/root/.cache/Cypress/9.7.0/Cypress/resources/app/node_modules/lazy-ass/index.js:115:28)
    at findStartPage (/root/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/browsers/protocol.js:56:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  cypress:server:cypress calling exit 1 +0ms
  cypress:server:cypress about to exit with code 1 +1ms
  cypress:server:browsers browsers.kill called with no active instance +29s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 123, immediatelyMatchedRequests: 0, eventuallyReceivedPreRequest: [], neverReceivedPreRequest: [ { , ... 23 more items ] } +0ms
2022-10-27T13:49:37.116Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
2022-10-27T13:49:37.116Z cypress:cli Stopping Xvfb
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aaaa-ui@0.0.0 cypress:run: `DEBUG=cypress:* cypress run --browser=firefox "--project=projects/file-monitoring-e2e" "--config-file=../../cypress.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aaaa-ui@0.0.0 cypress:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mschile** [comment]
Possibly related to #23897. @R-Schoe, could you please try updating to Cypress 10.10.0 and see if the issue still persists.

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
