### ISSUE TITLE
Cannot visit virtual domain

### ISSUE THREAD

**Issue by ezekel** [cypress-io/cypress#24458]
### Current behavior

I'm using this  

image
cypress/included:10.11.0 

O.S
windows 10

Node LTS

v18.12.0

when running this command below via Powershell

docker run -it -v ${PWD}:/cypress -w /cypress cypress/included:10.11.0

it shows me these errors

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

here is specs.js
using virtual domain name.

```
it('loads page', () => {
    cy.visit('http://myapp.local') 
  
})
```

now if I change to my host i.p , it works fine.
```
it('loads page', () => {
    cy.visit('http://192.168.1.5')
  
})
```

How can I pass my test if I will use the virtual domain name?

Note: 
 http://myapp.local  // running via docker

Thank you in advance

### Test code to reproduce

it('loads page', () => {
    cy.visit('http://myapp.local') 
  
})

### Cypress Version

cypress/included:10.11.0

### Node version

v18.12.0

### Operating System

WINDOWS 10

**Comment by mschile** [comment]
Hi @ezekel 👋 , thanks for logging an issue. Are you able to run cypress outside of the `cypress/included` docker image and connect to `http://myapp.local`?

Are you able to provide a reproducible example of the issue you're encountering? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by ezekel** [comment]
@mschile . I forgot to mention my site http://myapp.local is running inside the docker container . I did not use xamp or wampserver in my local development.

First  - I spin up my container for my website so that I can access http:://myapp.local

Second I run this command to my folder

```
C:\web\myapp> docker run -it -v ${PWD}:/cypress -w /cypress cypress/included:10.11.0
```

the cypress.config.js is in the root of my project folder

and this is my cypress folder structure

![image](https://user-images.githubusercontent.com/6830057/200566755-8798c9a1-550d-4198-938a-00940c01a881.png)


and this is the result in terminal after running the command

```
PS C:\web\myapp> docker run -it -v ${PWD}:/cypress -w /cypress cypress/included:10.11.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[204:1108/122726.391364:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.11.0                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v16.16.0 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (spec.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  spec.cy.js                                                                      (1 of 1)


  1) loads page

  0 passing (845ms)
  1 failing

  1) loads page:
     CypressError: `cy.visit()` failed trying to load:

http://myapp.local

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:80

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at <unknown> (http://localhost:33967/__cypress/runner/cypress_runner.js:142341:82)
      at visitFailedByErr (http://localhost:33967/__cypress/runner/cypress_runner.js:141629:12)
      at <unknown> (http://localhost:33967/__cypress/runner/cypress_runner.js:142340:11)
      at tryCatcher (http://localhost:33967/__cypress/runner/cypress_runner.js:11318:23)
      at Promise._settlePromiseFromHandler (http://localhost:33967/__cypress/runner/cypress_runner.js:9253:31)
      at Promise._settlePromise (http://localhost:33967/__cypress/runner/cypress_runner.js:9310:18)
      at Promise._settlePromise0 (http://localhost:33967/__cypress/runner/cypress_runner.js:9355:10)
      at Promise._settlePromises (http://localhost:33967/__cypress/runner/cypress_runner.js:9431:18)
      at _drainQueueStep (http://localhost:33967/__cypress/runner/cypress_runner.js:6025:12)
      at _drainQueue (http://localhost:33967/__cypress/runner/cypress_runner.js:6018:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:33967/__cypress/runner/cypress_runner.js:6034:5)
      at Async.drainQueues (http://localhost:33967/__cypress/runner/cypress_runner.js:5904:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/spec.cy.js:2:7)

  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:80
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     spec.cy.js                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /cypress/cypress/screenshots/spec.cy.js/loads page (failed).png                      (1280x720)


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /cypress/cypress/videos/spec.cy.js.mp4                         (0 seconds)


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  spec.cy.js                               837ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     837ms        1        -        1        -        -  

```


Thank you in advance.

**Comment by osmanconger** [comment]
Is there any update on this? I am facing a similar issue. Cypress cannot access my application when I use the virtual host. However, I can do so using any browser. Is there any way to access virtual hosts (e.g. http://myapp.local)?

**Comment by nagash77** [comment]
@osmanconger can you provide a [reproducible example](https://github.com/cypress-io/cypress-test-tiny)? We are still waiting for one to be abel to better investigate this issue.

**Comment by osmanconger** [comment]
You can follow the steps here to reproduce the issue: https://github.com/osmanconger/cypress-virtualhost @nagash77

**Comment by mschile** [comment]
Hi @osmanconger 👋, I have reproduced your issue in the latest version of Cypress and will forward this ticket to the appropriate team. They will evaluate the priority of this ticket and consider their capacity to pick it up. Please note that this does not guarantee that this issue will be resolved. The ticket will indicate status changes during evaluation.

As a workaround, I was able to get Cypress to resolve the virtual host by adding an entry into the `/etc/hosts` file.

`/etc/hosts`
```
127.0.0.1 myapp.localhost
```

![Image](https://github.com/cypress-io/cypress/assets/2002044/40c7e8c9-824f-47c5-89db-035b46c24f50)
