### ISSUE TITLE
CI with Jenkins doesn't work as expected

### ISSUE THREAD

**Issue by psadi** [cypress-io/cypress#24613]
### Current behavior

**package.json**
```
  "scripts": {
    "build": "react-scripts build",
    "start": "react-scripts start",
    "start:no-browser": "BROWSER=none react-scripts start",
    "cy:open": "cypress run open",
    "cy:run": "DEBUG=cypress:* cypress run --config video=false --headless",
    "ci": "start-server-and-test start:no-browser http://localhost:3000 cy:run"
  },
```

**command ran:**
```
  node("docker"){
      cleanWs()
      unstash repoName
      sh """
          docker run -v ${env.WORKSPACE}:/e2e -w /e2e --entrypoint='' -u root \
          cypress/included:10.11.0 \
          npm run ci
      """
  }
```

**Error Log:**

```
> cypress run --config video=false --headless

The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io/

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.4)
Cypress Version: 10.11.0
Error: Command failed with exit code 1: npm run cy:run
    at makeError (/e2e/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/e2e/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm run cy:run',
  command: 'npm run cy:run',
  escapedCommand: '"npm run cy:run"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Test code to reproduce

n/a

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

linux-x64 (Debian - 11.4)

### Debug Logs

```shell
> DEBUG=cypress:* cypress run --config video=false --headless

2022-11-09T12:55:10.552Z cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/e2e/node_modules/.bin/cypress","run","--config","video=false","--headless"]
2022-11-09T12:55:10.553Z cypress:cli NODE_OPTIONS is not set
2022-11-09T12:55:10.553Z cypress:cli:cli program parsing arguments
2022-11-09T12:55:10.557Z cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/e2e/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, config: 'video=false', headless: true, args: [], [Symbol(kCapture)]: false } ]
2022-11-09T12:55:10.662Z cypress:cli:cli variable-length opts parsed { args: [ '/usr/local/bin/node', '/e2e/node_modules/.bin/cypress', 'run', '--config', 'video=false', '--headless' ], opts: Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/e2e/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, config: 'video=false', headless: true, args: [], [Symbol(kCapture)]: false } }
2022-11-09T12:55:10.664Z cypress:cli parsed cli options { config: 'video=false', headless: true }
2022-11-09T12:55:10.664Z cypress:cli verifying Cypress app
2022-11-09T12:55:10.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-11-09T12:55:10.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-11-09T12:55:10.664Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /root/.cache/Cypress
2022-11-09T12:55:10.665Z cypress:cli checking environment variables
2022-11-09T12:55:10.667Z cypress:cli checking if executable exists /root/.cache/Cypress/10.11.0/Cypress/Cypress
2022-11-09T12:55:10.669Z cypress:cli Binary is executable? : true
2022-11-09T12:55:10.669Z cypress:cli binaryDir is  /root/.cache/Cypress/10.11.0/Cypress
2022-11-09T12:55:10.669Z cypress:cli Reading binary package.json from: /root/.cache/Cypress/10.11.0/Cypress/resources/app/package.json
2022-11-09T12:55:10.673Z cypress:cli Found binary version 10.11.0 installed in: /root/.cache/Cypress/10.11.0/Cypress
2022-11-09T12:55:10.674Z cypress:cli { verified: true }
2022-11-09T12:55:10.675Z cypress:cli is Verified ? true
2022-11-09T12:55:10.675Z cypress:cli:run processing run options { config: 'video=false', headless: true, key: null, spec: null, reporter: null, reporterOptions: null, project: '/e2e' }
2022-11-09T12:55:10.675Z cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY
2022-11-09T12:55:10.675Z cypress:cli:run run to spawn.start args ["--run-project","/e2e","--config","video=false","--headed",false]
2022-11-09T12:55:10.675Z cypress:cli undefined DISPLAY environment variable
2022-11-09T12:55:10.675Z cypress:cli Cypress will spawn its own Xvfb
2022-11-09T12:55:10.676Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-11-09T12:55:10.676Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2022-11-09T12:55:10.676Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /root/.cache/Cypress
2022-11-09T12:55:10.676Z cypress:cli needs to start own Xvfb? true
2022-11-09T12:55:10.676Z cypress:cli Starting Xvfb
2022-11-09T12:55:10.693Z cypress:cli spawning, should retry on display problem? false
2022-11-09T12:55:10.698Z cypress:cli passing DISPLAY :99
2022-11-09T12:55:10.699Z cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '/e2e', '--config', 'video=false', '--headed', false, '--cwd', '/e2e', '--userNodePath', '/usr/local/bin/node', '--userNodeVersion', '16.16.0' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
2022-11-09T12:55:10.699Z cypress:cli spawning Cypress with executable: /root/.cache/Cypress/10.11.0/Cypress/Cypress
2022-11-09T12:55:10.702Z cypress:cli piping child STDERR to process STDERR
  cypress:ts registering ts-node on directory undefined +0ms
  cypress:ts Running without ts-node hook in environment "production" +90ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/cache +0ms
  cypress:server:appdata path: /root/.config/Cypress/cy/production/browsers +59ms
  cypress:server:cypress starting cypress with argv [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress', '--no-sandbox', '--', '--run-project', '/e2e', '--config', 'video=false', '--headed', 'false', '--cwd', '/e2e', '--userNodePath', '/usr/local/bin/node', '--userNodeVersion', '16.16.0' ] +0ms
  cypress:server:args argv array: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress', '--no-sandbox', '--run-project', '/e2e', '--config', 'video=false', '--headed', 'false', '--cwd', '/e2e', '--userNodePath', '/usr/local/bin/node', '--userNodeVersion', '16.16.0' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress' ], sandbox: false, 'run-project': '/e2e', runProject: '/e2e', config: 'video=false', headed: 'false', cwd: '/e2e', userNodePath: '/usr/local/bin/node', userNodeVersion: '16.16.0' } } +1ms
  cypress:server:args argv parsed: { _: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress' ], sandbox: false, runProject: '/e2e', config: 'video=false', headed: false, cwd: '/e2e', userNodePath: '/usr/local/bin/node', userNodeVersion: '16.16.0', invokedFromCli: true } +3ms
  cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' } +0ms
  cypress:server:args options { _: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress' ], sandbox: false, runProject: '/e2e', config: { video: false }, headed: false, cwd: '/e2e', userNodePath: '/usr/local/bin/node', userNodeVersion: '16.16.0', invokedFromCli: true } +2ms
  cypress:server:args argv options: { _: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress' ], sandbox: false, runProject: '/e2e', config: { video: false }, headed: false, cwd: '/e2e', userNodePath: '/usr/local/bin/node', userNodeVersion: '16.16.0', invokedFromCli: true, projectRoot: '/e2e' } +0ms
  cypress:server:cypress from argv [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress', '--no-sandbox', '--run-project', '/e2e', '--config', 'video=false', '--headed', 'false', '--cwd', '/e2e', '--userNodePath', '/usr/local/bin/node', '--userNodeVersion', '16.16.0' ] got options { _: [ '/root/.cache/Cypress/10.11.0/Cypress/Cypress' ], sandbox: false, runProject: '/e2e', config: { video: false }, headed: false, cwd: '/e2e', userNodePath: '/usr/local/bin/node', userNodeVersion: '16.16.0', invokedFromCli: true, projectRoot: '/e2e' } +8ms
  cypress:server:cypress scaling electron app in headless mode +1ms
2022-11-09T12:55:12.175Z cypress:cli child event fired { event: 'exit', code: null, signal: 'SIGILL' }
2022-11-09T12:55:12.177Z cypress:cli detecting arch { osPlatform: 'linux', osArch: 'x64' }
2022-11-09T12:55:12.190Z cypress:cli arm uname -m result: { stdout: 'x86_64' } 
2022-11-09T12:55:12.191Z cypress:cli child event fired { event: 'close', code: null, signal: 'SIGILL' }
2022-11-09T12:55:12.204Z cypress:cli Stopping Xvfb
The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Debian - 11.4)
Cypress Version: 10.11.0
Error: Command failed with exit code 1: npm run cy:run
    at makeError (/e2e/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/e2e/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: npm run cy:run',
  command: 'npm run cy:run',
  escapedCommand: '"npm run cy:run"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by psadi** [comment]
is anyone looking at the issue ? its open for quite some time.

**Comment by mike-plummer** [comment]
Hi @psadi , sorry to hear you're having problems. Issues on CI are notoriously difficult for us to help diagnose since so much relies on the hardware and configuration of the specific CI system, and in this case there isn't a reproducible example I can run locally to debug the issue. A small CRA app with an E2E test against it executes fine for me locally via the 10.11.0 docker image using the setup you've described above, so there must be something unique about your CI environment or test suite.

Without a reproducible example, the first thing we would ask is to ensure you're using the latest-and-greatest version of all software involved. This includes Cypress (v12.0.1 as of today), Jenkins, Docker, and any other dependencies that may interact with your CI system. If the issue still presents and you can't create an example that fails outside of your CI setup then we would need to start collecting OS- and container-level logs to see if we can determine the precise command that is generating the `SIGILL`

**Comment by psadi** [comment]
Thanks for the suggestions, I agree it's an environment related issue. Same suite works well on my laptop hardware. 

It's very difficult to debug when such errors occur, especially with docker like ci environment where we don't control the configuration of the nodes.

I shall try again with the latest version (initially tested with included cypress image v11.x)

**Comment by psadi** [comment]
Issue seems with docker version which is now resolved after upgrade from v18 .x to v20.x

**Comment by Sheth90** [comment]
![image](https://user-images.githubusercontent.com/125349115/228445005-3a2e4ab1-99bc-45e6-aec6-4ba143327e9f.png)

**My package.json looks like as below:**

{
  "name": "samsung-kiosk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "launchcypress": "cypress open",
    "paralleltest": "npx cypress run --spec ./cypress/e2e/OtherTestcases/*.js",
    "cy:parallel": "cypress-parallel -d cypress/e2e/OtherTestcases/ -t 5 -s paralleltest",
   
    "testcases": "cypress run --spec ./cypress/e2e/SmokeTestSuite.cy.js --browser chrome",
    "allure:clear": "npx allure generate --clean -o allure-results",
    "testcases-allure": "npm run allure:clear && cypress run --spec ./cypress/e2e/SmokeTestSuite.cy.js --env allure=true",
    "allure:report": "allure generate allure-results --clean -o allure-report",
    "finaltest": "npm run allure:clear && npm run testcases-allure && npm run allure:report",
    
    "cy:run": "cypress run --env allure=true",
    "tests": "npm run cy:run || npm run aftertest"
   
  },

  "keywords": [],
  "author": "Sanjay Sonule",
  "license": "ISC",
  "devDependencies": {
    "@4tw/cypress-drag-drop": "^1.4.0",
    "@faker-js/faker": "^7.6.0",
    "@shelex/cypress-allure-plugin": "^2.35.2",
    "allure-commandline": "^2.21.0",
    "cypress": "^12.7.0",
    "cypress-file-upload": "^4.1.1",
    "cypress-xpath": "^1.8.0",
    "mocha-allure-reporter": "^1.4.0",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^6.2.0"
  },
  "dependencies": {
    "-": "^0.0.1",
    "cypress-downloadfile": "^1.2.0",
    "faker": "^5.5.3",
    "save-dev": "^0.0.1-security"
  }
}

**I am getting an error message as per attached Screenshot.**
**My Smoke test suite spec file looks like as below. It is properly running in local. But not running over the jenkin. Please help**.


// Execute this using  npx cypress run --spec=cypress/e2e/SmokeTestSuite.cy.js'

/* For All Common Settings */
import './SmokeTests/Settings.spec.js'

/* For Dynamic Order Types */
import './SmokeTests/10_DynamicOrderTypes_VerifyDisplayOrderOfOrderTypes.spec.js'
import './SmokeTests/3_DynamicOrderTypes_DineInOrderAndVerify.spec.js'
import './SmokeTests/4_DynamicOrderTypes_TakeoutOrderAndVerify.spec.js'
import './SmokeTests/5_DynamicOrderTypes_DeliveryOrderAndVerify.spec.js'

/* For Discount */
import './SmokeTests/36_Discount_VerifyItemFlatDiscount.spec.js'
import './SmokeTests/37_Discount_VerifyItemPercentageDiscount.spec.js'
import './SmokeTests/38_Discount_VerifySubtotalFlatDiscount.spec.js'
import './SmokeTests/39_Discount_VerifySubtotalPercentageDiscount.spec.js'

/* For Tip */
import './SmokeTests/25_Tip_VerifyDefaultTip.spec.js'
import './SmokeTests/26_Tip_VerifyEditTipCalculation.spec.js'

/* For Modifiers */
import './SmokeTests/85_Modifiers_VerifyDefaultIngredientSetInBackendShouldReflectOnTheKiosk.spec.js'
import './SmokeTests/80_Modifiers_VerifyThatMinMaxShouldWorkOnFrontendAsItIsEnteredInBackend.spec.js'
import './SmokeTests/76_Modifiers_VerifyShowOnKioskFlagIsOffModifierShouldNotDisplay.spec.js'
import './SmokeTests/79_Modifiers_VerifyIngredientsAreSoldOutKioskShouldNotAllowUserToAddThisIngredients.spec.js'

/* For Alcoholic limit */
import './SmokeTests/55_AlcoholicLimit_VerifyAlcoholicItemsNeedToAskIfCustomerIs21.spec.js'
import './SmokeTests/57_AlcoholicLimit_VerifyAfterDeteteAndReaddAlcoholItemShouldNotBreakMaxQtyLimitCalculations.spec.js'
import './SmokeTests/60_AlcoholicLimit_VerifyForComboItemsAlcoholLimitIsSatisfied.spec.js'
import './SmokeTests/61_AlcoholicLimit_VerifyImplementCheckForAlcoholUsingEmployeePin.spec.js'

/* For Items */
import './SmokeTests/68_Items_VerifyShowItemDetailScreenOnKioskIsCheckedRedirectToItemDetailsScreen.spec.js'
import './SmokeTests/71_Items_VerifyComboItemOnlyFlagEnableDisable.spec.js'
import './SmokeTests/99_Items_VerifyCommonLevelVariation.spec.js'
import './SmokeTests/102_Items_VerifyNestedModifiers.spec.js'
import './SmokeTests/105_Items_VerifyComboNestedModifiers.spec.js'
import './SmokeTests/75_Items_VerifyWhenUserClickOnPlusButtonTheQuantityOfItemWillIncreaseInsteadOfDuplicareItem.spec.js'

/* For Upsell */
import './SmokeTests/93_Upsell_VerifyUserCanAddMultiItemLevelUpsell.spec.js'
import './SmokeTests/92_Upsell_VerifyItemLevelUpsellQuantityUpdate.spec.js'
import './SmokeTests/94_Upsell_VerifyUpsellHeaderTextForItemLevelUpsell.spec.js'

/* For Special Request */
import './SmokeTests/65_SpecialRequest_SpecialRequestAddedForAnItemShouldBeDisplayedOnReviewOrderScreen.spec.js'

/* For Category settings */
import './SmokeTests/19_Category_VerifyCategoryHideHeaderTextFlag.spec.js'
import './SmokeTests/89_Category_VerifyLongNameForCategoryShouldBeManaged.spec.js'
import './SmokeTests/14_Category_VerifyCategoryShowKioskFlag.spec.js'
import './SmokeTests/21_Category_VerifyChildCategoryInsideParentCategory.spec.js'

/* For GENERAL SETTINGS */
import './SmokeTests/124_GeneralSettings_AllowAddItemToCartFlagCHECKEDdWithDefaultModifierIs86.spec.js'
import './SmokeTests/130_GeneralSettings_ShowItemDescriptioninNestedModifiersChecked.spec.js'
import './SmokeTests/128_GeneralSettings_ItemTableTentFlagChecked.spec.js'
import './SmokeTests/133_GeneralSettings_LoyaltyRedeemChecked.spec.js'

/* For KIOSK Settings */
import './SmokeTests/135_KioskSettings_Click5TimesOnLogoShouldLeadToKioskSettings.spec.js'
import './SmokeTests/138_KioskSettings_DeviceInfo.spec.js'
import './SmokeTests/137_KioskSettings_LogInLogOut.spec.js'
import './SmokeTests/136_KioskSettings_LaunchKiosk.spec.js'

/* For Loyalty */
import './SmokeTests/139_Loyalty_SignInWithExistingNumberWillRedirectedToLast5OrdersScreen.spec.js'
import './SmokeTests/140_Loyalty_SigningInWithNumberStartingFrom0ShouldNotBeAllowed.spec.js'
import './SmokeTests/141_Loyalty_VerifyLoyaltySignInFromMenuReviewOrderAndHomeScreen.spec.js'
import './SmokeTests/142_Loyalty_LoyaltyTotalPointsLastVisitCountAndPointsEarnedLastVisitShouldShow.spec.js
