### ISSUE TITLE
Component test intermittent failing both on local and CI

### ISSUE THREAD

**Issue by bob-lee** [cypress-io/cypress#24659]
### Current behavior

Migrated from 10.7.0 to 11.0.1 and having intermittent failure of component test both on local and CI.

On local (ubuntu, node 14.20.0):
```
$ cypress run --component
ℹ Compiling Client

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        11.0.1                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v14.20.0 (/home/bob/.nvm/versions/node/v14.20.0/bin/node)                      │
  │ Specs:          16 found (AddAttachment.cy.js, AttachIcon.cy.js, AttachedFile.cy.js, CompanyIn │
  │                 fo.cy.js, EntityType.cy.js, FormActivity.cy.js, FormClient.cy.js, FormLocation │
  │                 .cy.js, FormProduct.cy.js, IconAdd.cy.js, IconAttach.cy.js, IconCsv.cy.js, Lis │
  │                 tAttachment.cy.js, Main...)                                                    │
  │ Searched:       cypress/component/**/*.cy.js                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  AddAttachment.cy.js                                                            (1 of 16)

Timed out waiting for the browser to connect. Retrying...
✔ Client: Compiled successfully in 1.38m
   2524 modules
No issues found.

    AddAttachment
      AddAttachment
        ✓ renders correctly (132ms)
        ✓ renders correctly (142ms)
        ✓ shows given error correctly (71ms)
        - renders correctly when hovered
        ✓ shows given error correctly (163ms)
        - renders correctly when hovered
        ✓ opens file selector when clicked (177ms)

  5 passing (431ms)
  2 pending

. . .

Could not process 'reset:browser:tabs:for:next:test'. No automation clients connected.
Error: Could not process 'reset:browser:tabs:for:next:test'. No automation clients connected.
    at m.onAutomation (<embedded>:2802:63095)
    at L (<embedded>:2802:64132)
    at <embedded>:2744:217600
    at Promise.cancellationExecute [as _execute] (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/debuggability.js:335:9)
    at Promise._resolveFromExecutor (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:79:10)
    at m.requestAutomationResponse (<embedded>:2744:217281)
    at <embedded>:2744:217206
    at <embedded>:2744:218439
    at tryCatcher (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at m.normalize (<embedded>:2744:217732)
    at <embedded>:2744:218790
    at tryCatcher (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues [as _onImmediate] (/home/bob/.cache/Cypress/11.0.1/Cypress/resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at process.processImmediate (node:internal/timers:466:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

On CI (Aws Amplify)
```
2022-11-11T01:22:45.838Z [INFO]: ERR_FAILED (-2) loading 'http://localhost:8080/__/#/specs/runner?file=cypress/component/AttachIcon.cy.js'
2022-11-11T01:22:45.839Z [INFO]: Error: ERR_FAILED (-2) loading 'http://localhost:8080/__/#/specs/runner?file=cypress/component/AttachIcon.cy.js'
                                 at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
                                 at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
                                 at EventEmitter.emit (node:events:527:28)
```

### Desired behavior

Runs in consistent way

### Test code to reproduce

Private repo

### Cypress Version

11.0.1

### Node version

14.20.0

### Operating System

Ubuntu 22.10

### Other

It ran in consistent way at v10.7.0.

**Comment by lmiller1990** [comment]
Just to help with debugging, have you tried running with Chrome instead of Electron browser? `--browser chrome`. This will help narrow it down - we updated the Electron version in Cypress 11, could be related.

As an aside, another thing that might be worth your time is trying the `experimentalSingleTabRunMode` flag, that will speed things up on CI greatly: https://docs.cypress.io/guides/references/experiments#Component-Testing

**Comment by breencp** [comment]
I am experiencing persistent crashes testing with Electron in both my local environment and on AWS Amplify CI.

`...at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)`

It appears to be caused by `cy.get('[id="btn-download-output"]', {timeout: 60000}).click();`.  The file is successfully saved to cypress/downloads, and then immediately crashes with the above message afterward.  

`  "devDependencies": {
    "@angular-devkit/build-angular": "14.2.9",
    "@angular/cli": "~14.2.9",
    "@angular/compiler-cli": "~14.2.10",
    "@cypress/schematic": "^2.3.0",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^18.11.9",
    "cypress": "^11.0.1",
    "cypress-file-upload": "^5.0.8",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.4"
  }
`
Testing with Chrome on the other hand works perfectly.  Problem is AWS Amplify doesn't have Chrome available for me to use in testing and is part of my CI/CD.

**Comment by nagash77** [comment]
@breencp I am not sure your issue is related to the original posters.  Can you please open a separate issue?

**Comment by breencp** [comment]
> @breencp I am not sure your issue is related to the original posters. Can you please open a separate issue?

My bad.  Created a new one here: https://github.com/cypress-io/cypress/issues/24682#issue-1448718698

**Comment by bob-lee** [comment]
I'm pretty sure this is resource related (and quite understandable), until my project can migrate to `vite`, I'm downgrading to `10.7.0` and closing this.
