### ISSUE TITLE
"Cypress failed to verify that your server is running" Set proxy using host name doesn't work in above cypress v10

### ISSUE THREAD

**Issue by EIKINAKAYAMA** [cypress-io/cypress#24714]
### Current behavior

I run cypress by using docker agent by Jenkins CI.

I add host in docker agent because connecting Percy api requires ip6 name resolution.
(if I set proxy HTTPS_PROXY="http://[${secret but ip6}]:3128", cypress will work fine but it is unable to connect Percy api )

It is success to get the sever response by "curl" but not cypress. also it happens above cypress version 10.
When the cypress version is 9.6.0, cypress is able to detect the server.

proxy_name = "proxy"
args """
      --add-host ${proxy_name}:${secret but ip6}
  """
  
  I set the environment
  
  environment {
        HTTPS_PROXY="http://${proxy_name}:3128"
        HTTP_PROXY="http://${proxy_name}:3128"
        https_proxy="http://${proxy_name}:3128"
        http_proxy="http://${proxy_name}:3128"
        PERCY_TOKEN= ${secret}
    }
  
  

```
+ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
${secret but ip6} proxy
~~~~
+ curl https://${secret}.co.jp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!doctype html><html lang="en"><head><meta charset="utf-8"/>

~~~

+ yarn run cy:snapshot-prodPublic
yarn run v1.22.17
$ percy exec -- yarn cy:run
[percy] Downloading Chromium 929511...
[percy] Successfully downloaded Chromium 929511
[percy] Percy has started!
[percy] Running "yarn cy:run"
$ cypress run --config-file cypress/config/prodPublic.config.js
[STARTED] Task without title.
[SUCCESS] Task without title.
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[682:1117/114614.974196:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Cypress could not verify that this server is running:

  > https://${secret}.co.jp

We are verifying this server because it has been configured as your baseUrl.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[percy] Finalized build #103: https://percy.io/2701df23/Monitoring/builds/23009765
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
+ exit 0

```

### Desired behavior

It should be able to detect the sever is running

### Test code to reproduce

Sorry this repo is secret repo, so I can't share.

### Cypress Version

11.1.0

### Node version

16.13.2

### Operating System

linux

### Debug Logs

```
2022-11-17T03:32:32.806Z cypress:network:agent Creating proxied socket for https://${secret}/ through http://proxy:3128/
2022-11-17T03:32:32.819Z cypress:network:connect retries exhausted, bubbling up error { iteration: 0, err: Error: getaddrinfo ENOTFOUND proxy at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'proxy' } }
We will try connecting to it 1 more time...
```

### Other
I guess the ip6 name resolution is wrong...

**Comment by rockindahizzy** [comment]
Hi @EIKINAKAYAMA, thanks for reporting the issue! 

When you curl, is it also going through the proxy?

**Comment by EIKINAKAYAMA** [comment]
Hi @rockindahizzy, thanks for replying !

> When you curl, is it also going through the proxy?

Yes! I mede the log short, but executed command is actually used in a same step's env in Jenkins file. like this.
```
sh "curl https://${secret}.co.jp"
sh "yarn run cy:snapshot-prodPublic"
```

**Comment by lmiller1990** [comment]
I am trying to debug this. I'm trying to get Cypress working with a `baseUrl` of IPv6, seem this isn't valid. I'll try HTTP_PROXY.

```js
module.exports = {
  "e2e": {
    // "baseUrl": "http://127.0.0.1:8000",
    // NOT OK "baseUrl": "http://[::1]:8000/",
    "baseUrl": "http://[0000:0000:0000:0000:0000:0000:0000:0001]:8000/",
    "specPattern": "cypress/integration/**/*",
    "supportFile": false
  }
}
```

For my `cypress.config.js`, I cannot even open Cypress v12. It does not like IPv6. Let me try IPv4. curl does work with `-g -6`: `curl -g -6 "http://[0000:0000:0000:0000:0000:0000:0000:0001]:8000/"`.

Edit... same problem in v9:

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.getOriginPolicy (/home/lachlan/.cache/Cypress/9.7.0/Cypress/resources/app/packages/network/lib/cors.js:110:32)
```


Any luck @EIKINAKAYAMA? Did you end up fixing this?

**Comment by lmiller1990** [comment]
Ok, I can kind of reproduce. You cannot start Cypress 10+ with a `HTTP_PROXY=<some_ip_v6_address>`. @EIKINAKAYAMA says it's  working for him:

> HTTPS_PROXY="http://[${secret but ip6}]:3128"

I got this error. I guess my python server doesn't support IPv6. Are you using NGINX? I'd like to reproduce so I can debug locally.

<details><summary>Error here... open me</summary>

```

$ /home/lachlan/code/dump/vanilla/node_modules/.bin/cypress open
[184699:1223/101734.334538:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[184855:1223/101734.344559:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[184855:1223/101734.346153:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
RequestError: Error: Error establishing proxy connection. Response from server was: HTTP/1.0 501 Unsupported method ('CONNECT')
Server: SimpleHTTP/0.6 Python/3.8.10
Date: Fri, 23 Dec 2022 00:17:34 GMT
Connection: close
Content-Type: text/html;charset=utf-8
Content-Length: 500

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 501</p>
        <p>Message: Unsupported method ('CONNECT').</p>
        <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
    </body>
</html>

    at new RequestError (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/node_modules/@cypress/request/request.js:183:22)
    at Request.emit (node:events:390:28)
    at Request.emit (node:domain:475:12)
    at Request.onRequestError (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/node_modules/@cypress/request/request.js:869:8)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at _destroy (node:_http_client:798:13)
    at onSocketNT (node:_http_client:815:5)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
 {
  cause: Error: Error establishing proxy connection. Response from server was: HTTP/1.0 501 Unsupported method ('CONNECT')
  Server: SimpleHTTP/0.6 Python/3.8.10
  Date: Fri, 23 Dec 2022 00:17:34 GMT
  Connection: close
  Content-Type: text/html;charset=utf-8
  Content-Length: 500
  
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
          "http://www.w3.org/TR/html4/strict.dtd">
  <html>
      <head>
          <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
          <title>Error response</title>
      </head>
      <body>
          <h1>Error response</h1>
          <p>Error code: 501</p>
          <p>Message: Unsupported method ('CONNECT').</p>
          <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
      </body>
  </html>
  
      at Socket.onData (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/network/lib/agent.js:260:31)
      at Object.onceWrapper (node:events:510:26)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
  ,
  error: Error: Error establishing proxy connection. Response from server was: HTTP/1.0 501 Unsupported method ('CONNECT')
  Server: SimpleHTTP/0.6 Python/3.8.10
  Date: Fri, 23 Dec 2022 00:17:34 GMT
  Connection: close
  Content-Type: text/html;charset=utf-8
  Content-Length: 500
  
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
          "http://www.w3.org/TR/html4/strict.dtd">
  <html>
      <head>
          <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
          <title>Error response</title>
      </head>
      <body>
          <h1>Error response</h1>
          <p>Error code: 501</p>
          <p>Message: Unsupported method ('CONNECT').</p>
          <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
      </body>
  </html>
  
      at Socket.onData (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/network/lib/agent.js:260:31)
      at Object.onceWrapper (node:events:510:26)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
  ,
  options: {
    url: 'https://api.cypress.io/auth',
    json: true,
    cacheable: true,
    headers: {
      'x-route-version': '2',
      'x-os-name': 'linux',
      'x-cypress-version': '10.0.0'
    },
    method: 'GET',
    agent: CombinedAgent {
      familyCache: {},
      httpAgent: [HttpAgent],
      httpsAgent: [HttpsAgent]
    },
    proxy: null,
    gzip: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined,
  isApiError: true
}
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.getOriginPolicy (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/network/lib/cors.js:90:32)
    at RemoteStates.get (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/lib/remote_states.js:52:60)
    at RemoteStates.set (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/lib/remote_states.js:124:21)
    at /home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/lib/server-e2e.js:104:40
    at tryCatcher (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/lachlan/.cache/Cypress/10.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$                                                
```

</details>

**Comment by MikeMcC399** [comment]
@lmiller1990 

> I'm trying to get Cypress working with a `baseUrl` of IPv6, seem this isn't valid.

- I have logged this as #25950. I didn't mention `baseUrl` in the issue report, but the effect is the same. A literal IPv6 in `baseUrl` crashes Cypress, the same as it does when it is used in `cy.visit`.

**Comment by lmiller1990** [comment]
Sure. let's track progress there. I'll close this one off.
