### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'onFail')

### ISSUE THREAD

**Issue by fjf2002** [cypress-io/cypress#24806]
### Current behavior

In some (yet to me unknown) circumstances I get this error, see below.
I suspect this is a bug inside cypress, at least a cryptic error message you could improve.

Thank You.

```
     TypeError: Cannot set properties of undefined (setting 'onFail')
      at makeErrFromErr (https://mydomain/__cypress/runner/cypress_runner.js:161255:16)
      at Object.throwErr (https://mydomain/__cypress/runner/cypress_runner.js:161266:9)
      at <unknown> (https://mydomain/__cypress/runner/cypress_runner.js:141174:78)
      at tryCatcher (https://mydomain/__cypress/runner/cypress_runner.js:11327:23)
      at Promise._settlePromiseFromHandler (https://mydomain/__cypress/runner/cypress_runner.js:9262:31)
      at Promise._settlePromise (https://mydomain/__cypress/runner/cypress_runner.js:9319:18)
      at Promise._settlePromise0 (https://mydomain/__cypress/runner/cypress_runner.js:9364:10)
      at Promise._settlePromises (https://mydomain/__cypress/runner/cypress_runner.js:9440:18)
      at _drainQueueStep (https://mydomain/__cypress/runner/cypress_runner.js:6034:12)
      at _drainQueue (https://mydomain/__cypress/runner/cypress_runner.js:6027:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://mydomain/__cypress/runner/cypress_runner.js:6043:5)
      at Async.drainQueues (https://mydomain/__cypress/runner/cypress_runner.js:5913:14)
```

### Desired behavior

The error should not occur, or at least contain a message meaningful to the user.

### Test code to reproduce

unknown

### Cypress Version

10.11.0

### Node version

18.8

### Operating System

WSL2

**Comment by rockindahizzy** [comment]
Hey @fjf2002 thanks for reporting the issue. It looks like this is possibly a WSL2 + Cypress issue, but there isn't enough info for me to know for sure.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. 

It would be extremely helpful if you can confirm this happens even on a bare minimum cypress repo (preferably a github public repo).

**Comment by emilyrohrbough** [comment]
@fjf2002 Interesting....does this seem to happen on any specific set of commands or setup? Looks like the error is coming from [here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_utils.ts#L225), but it's a bit odd the error is undefined at this point.

**Comment by fjf2002** [comment]
@emilyrohrbough: Thank you for your response. The error is hard to reproduce.
* it only occurs in electron command line - so how to debug and investigate?
* the error message is not helpful - I have no idea how and when it happens.

So how can I help you?

Thanks in advance.

**Comment by fjf2002** [comment]
@emilyrohrbough: I can confirm ...
* The error occurs in cypress versions 10.11.0 and 11.2.0 (other versions not tested)
* The error occurs inside a docker-in-docker container from cypress/included:11.2.0
* The error does not occur without any docker involved
* The error does not occur with just the cypress/included container involved (and not any docker-in-docker)

An interesting point would be if docker-in-docker does any harm.
Nevertheless the cypress error message ("Cannot set properties of undefined (setting 'onFail')") isn't any helpful in investigating this.

**Comment by mike-plummer** [comment]
@fjf2002 I spun up a quick project using `cypress/included:11.2.0` within a `dind` container and I didn't hit the described error with either a basic passing or failing spec. This specific error condition must rely on a certain set of Cypress commands to reproduce and without more information I can't work out precisely what is unique about the `docker-in-docker` situation. From looking at the code that @emilyrohrbough helpfully identified it does appear that we are lacking appropriate type-safety on the `err` parameter - adding more TS typings and conditionals would likely help mitigate this particular failure. I can send this through to the team to look into adding those guards (or if you or another OSS contributor would like to take a stab), but without a [reproducible example](http://sscce.org/) I can't provide much guidance on what about your spec/environment is causing this issue to manifest. Barring that, I would ask you review the [Troubleshooting Guide](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) in order to provide debug logs to give us clues about what sort of internal Cypress activities might be sparking this condition.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by mm-matthias** [comment]
This just happened to me with Cypress 12.17.3 using Chrome on Mac without any Docker involved. It happened in the "After all" stage after a test failed in a `wrap` command. The traceback seems to be very similar to the one of the OP:

```plain
TypeError: Cannot set properties of undefined (setting 'onFail')
    at makeErrFromErr (http://localhost:4200/__cypress/runner/cypress_runner.js:75121:16)
    at Object.throwErr (http://localhost:4200/__cypress/runner/cypress_runner.js:75129:9)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:120331:70)
    at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:1697:18)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:2392:25)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:4200/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (http://localhost:4200/__cypress/runner/cypress_runner.js:1239:17)
    at Promise.then (http://localhost:4200/__cypress/runner/cypress_runner.js:1132:17)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:143627:39)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:143648:16)
    at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:4200/__cypress/runner/cypress_runner.js:1645:18)
    at Promise._resolveCallback (http://localhost:4200/__cypress/runner/cypress_runner.js:1439:57)
    at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:1531:17)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:4200/__cypress/runner/cypress_runner.js:1645:18)
    at Promise._resolveCallback (http://localhost:4200/__cypress/runner/cypress_runner.js:1439:57)
    at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:1531:17)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:4200/__cypress/runner/cypress_runner.js:1645:18)
    at PromiseArray._resolve (http://localhost:4200/__cypress/runner/cypress_runner.js:2932:19)
    at MappingPromiseArray._promiseFulfilled (http://localhost:4200/__cypress/runner/cypress_runner.js:4987:18)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:1581:26)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:1701:18)
```

I've found some code that does `cy.wrap(Promise.reject())`. This seems to be producing the error in Cypress when it tries to capture the stack trace or something.
