### ISSUE TITLE
when running feature files, there is an prompt saying process is not defined

### ISSUE THREAD

**Issue by huiyangns** [cypress-io/cypress#24913]
### Current behavior

index.1f5f580c.js:99925 ReferenceError: The following error originated from your test code, not from Cypress.

  > process is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at node_modules/figures/index.js (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:25242:22)
    at __require2 (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:19:52)
    at node_modules/cucumber/lib/formatter/helpers/issue_helpers.js (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:26217:22)
    at __require2 (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:19:52)
    at node_modules/cucumber/lib/formatter/helpers/index.js (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:27294:28)
    at __require2 (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:19:52)
    at node_modules/cucumber/lib/support_code_library_builder/define_helpers.js (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:32423:22)
    at __require2 (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:19:52)
    at node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:33281:11)
    at __require2 (https://one.xxx.co/__cypress/tests?p=tests/cypress/integration/login/loginBase.feature:19:52)
From previous event:
    at evalScripts (https://one.xxx.co/__cypress/runner/cypress_runner.js:165956:58)
    at <unknown> (https://one.xxx.co/__cypress/runner/cypress_runner.js:165968:152)
From previous event:
    at runScriptsFromUrls (https://one.xxx.co/__cypress/runner/cypress_runner.js:165968:136)
    at Object.runScripts (https://one.xxx.co/__cypress/runner/cypress_runner.js:165983:12)
    at $Cypress.onSpecWindow (https://one.xxx.co/__cypress/runner/cypress_runner.js:153939:75)

**Comment by huiyangns** [comment]
package.json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "author": "",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "remove-files": "node removeFiles.js",
    "cucumber-report": "node createreport.js",
    "cypress:open": "cypress open",
    "cy:rest-api": "cypress run --headless --spec tests/cypress/integration/restapi/**/*.spec.js"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "step_definitions": "tests/cypress/integration",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "tests/cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
  "devDependencies": {
    "@babel/core": "^7.13.8",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.13.9",
    "cheerio": "^1.0.0-rc.5",
    "cucumber-html-reporter": "^5.3.0",
    "cypress": "^11.2.0",
    "cypress-cucumber-preprocessor": "^2.5.5",
    "cypress-dotenv": "^1.2.2",
    "cypress-file-upload": "^4.1.1",
    "cypress-localstorage-commands": "^1.4.1",
    "cypress-wait-until": "^1.7.1",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "fs-extra": "^8.1.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-babel": "^8.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-debug": "^4.0.0",
    "gulp-eslint": "^6.0.0",
    "gulp-filter": "^6.0.0",
    "gulp-fs-cache": "^0.1.0",
    "gulp-iconfont": "^10.0.3",
    "gulp-if": "^3.0.0",
    "gulp-livereload": "^4.0.2",
    "gulp-order": "^1.2.0",
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-terser": "^1.4.1",
    "gulp-wait": "0.0.2",
    "lazypipe": "^1.0.2",
    "merge-stream": "^2.0.0",
    "node-sass": "^4.14.1"
  },
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 Safari versions",
    "last 2 Edge versions",
    "IE 11",
    "last 2 ChromeAndroid versions",
    "last 2 iOS versions",
    "last 2 Samsung versions",
    "last 2 FirefoxAndroid versions"
  ],
  "dependencies": {
    "auth0-js": "^9.14.3",
    "dotenv": "^8.2.0",
    "idb": "^6.0.0",
    "moment": "^2.29.1",
    "papaparse": "^5.3.0",
    "pdf-parse": "^1.1.1",
    "pdfjs-dist": "^2.6.347"
  }
}
