### ISSUE TITLE
Cypress-grep can't work with it.only 

### ISSUE THREAD

**Issue by VolodymyrLykhachov** [cypress-io/cypress#25062]
### Current behavior

I get " Cannot read properties of undefined (reading 'parent')" when I add it.only test to project with grep. it.skip works as expected.

I added repo https://github.com/violant/cypress-grep-example for reproducing. It works as expected with no it.only.
To reproduce run tests in spec app-spec.js using cypress:open or run cypress:run and search for the error in app-spec.js  spec logs.

all grep variables are stored in config file.

### Desired behavior

it.only test should run if it contains tag that is used in grepping.

### Test code to reproduce

https://github.com/violant/cypress-grep-example 

### Cypress Version

11.2.0

### Node version

14.18.2

### Operating System

macOS 13.0.1

### Debug Logs

```shell
index.14eacd7b.js:99925 TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read properties of undefined (reading 'parent')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at Object.only (http://localhost:8888/__cypress/runner/cypress_runner.js:103543:14)
    at context.it.only (http://localhost:8888/__cypress/runner/cypress_runner.js:103347:26)
    at createRunnable (http://localhost:8888/__cypress/runner/cypress_runner.js:162838:31)
    at Function.only (http://localhost:8888/__cypress/runner/cypress_runner.js:162903:16)
    at Object.create (http://localhost:8888/__cypress/runner/cypress_runner.js:103515:19)
    at context.describe.context.context (http://localhost:8888/__cypress/runner/cypress_runner.js:103291:27)
    at createRunnable (http://localhost:8888/__cypress/runner/cypress_runner.js:162838:31)
    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:162903:16)
    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:165963:23)
From previous event:
    at evalScripts (http://localhost:8888/__cypress/runner/cypress_runner.js:165956:58)
    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:165968:152)
From previous event:
    at runScriptsFromUrls (http://localhost:8888/__cypress/runner/cypress_runner.js:165968:136)
    at Object.runScripts (http://localhost:8888/__cypress/runner/cypress_runner.js:165983:12)
    at $Cypress.onSpecWindow (http://localhost:8888/__cypress/runner/cypress_runner.js:153939:75)
logError @ index.14eacd7b.js:99925


> cypress-grep-example@0.0.0-development cypress:open
> DEBUG=cypress-grep cypress open

Couldn't find tsconfig.json. tsconfig-paths will be skipped
  cypress-grep cypress-grep plugin version 3.1.0 +0ms
  cypress-grep Cypress config env object: { grepTags: '@smoke', grepFilterSpecs: true, grepOmitFiltered: true } +0ms
cypress-grep: filtering using tag(s) "@smoke"
cypress-grep: will omit filtered tests
  cypress-grep parsed grep tags [ [ { tag: '@smoke', invert: false } ] ] +1ms
  cypress-grep specPattern cypress/e2e/**/*spec.js +1ms
  cypress-grep excludeSpecPattern *.hot-update.js +0ms
  cypress-grep integrationFolder /Users/IdeaProjects/cypress-grep-example +0ms
  cypress-grep found 6 spec files +7ms
  cypress-grep [ '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/app-spec.js', '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/completed-spec.js', '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/counter-spec.js', '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/editing-spec.js', '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/persistence-spec.js', '/Users/IdeaProjects/cypress-grep-example/cypress/e2e/routing-spec.js' ] +0ms
  cypress-grep parsed grep tags { title: [], tags: [ [ [Object] ] ] } +0ms
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/app-spec.cy.js
Will run it to let the grep filter the tests
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/completed-spec.cy.js
Will run it to let the grep filter the tests
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/counter-spec.cy.js
Will run it to let the grep filter the tests
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/editing-spec.cy.js
Will run it to let the grep filter the tests
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/persistence-spec.cy.js
Will run it to let the grep filter the tests
Could not determine test names in file: /Users/IdeaProjects/cypress-grep-example/cypress/e2e/routing-spec.cy.js
Will run it to let the grep filter the tests
  cypress-grep found grep tags "@smoke" in 6 specs +58ms

```

**Comment by samueldmeyer** [comment]
I hit this issue as well. My workaround for local development is to wrap the test with a new `describe.only` block that has no tags. Of course, I would prefer to have `it.only` work.

```
describe('all tests', () => {
  describe.only('focused test', () = {
    it('has tags', { tags: ['@tag1'] } () => {
      // test here
    });
  });
});
```

**Comment by nereamarqueze** [comment]
Hi, I have the same issue here.
That makes it.only and grepTags incompatibles instead of complementaries, so it won't be necessary to put the it inside a especific describe.

**Cypress Version**
13.13.2

**Node version**
18.6.0

**Operating System**
Ubuntu 20.04.6 LTS

**Debug Logs**
```
An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read properties of undefined (reading 'parent')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object.only ([URL]/__cypress/runner/cypress_runner.js:161229:14)
      at context.it.only ([URL]/__cypress/runner/cypress_runner.js:160976:26)
      at createRunnable ([URL]/__cypress/runner/cypress_runner.js:145533:31)
      at Function.only ([URL]/__cypress/runner/cypress_runner.js:145592:16)
      at Object.create ([URL]/__cypress/runner/cypress_runner.js:161201:19)
      at context.describe.context.context ([URL]/__cypress/runner/cypress_runner.js:160920:27)
      at createRunnable ([URL]/__cypress/runner/cypress_runner.js:145533:31)
      at <unknown> ([URL]/__cypress/runner/cypress_runner.js:145592:16)
      at <unknown> ([URL]/__cypress/runner/cypress_runner.js:111745:23)
      at tryCatcher ([URL]/__cypress/runner/cypress_runner.js:1807:23)
      at Object.gotValue ([URL]/__cypress/runner/cypress_runner.js:6476:18)
      at Object.gotAccum ([URL]/__cypress/runner/cypress_runner.js:6465:25)
      at Object.tryCatcher ([URL]/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler ([URL]/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise ([URL]/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 ([URL]/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises ([URL]/__cypress/runner/cypress_runner.js:1701:18)
      at _drainQueueStep ([URL]/__cypress/runner/cypress_runner.js:2407:12)
      at _drainQueue ([URL]/__cypress/runner/cypress_runner.js:2400:9)
      at Async._drainQueues ([URL]/__cypress/runner/cypress_runner.js:2416:5)
      at Async.drainQueues ([URL]/__cypress/runner/cypress_runner.js:2286:14)
```

**Comment by jirigalis** [comment]
Hi, I have the same issue.
Cypress version: 13.8.1
Node: 20.14.0

Everything worked fine until I installed the @cypress/grep plugin. It would be great to have this issue fixed.
Thanks!

**Comment by mciruelos** [comment]
Hello there! 

I am encountering the same error as previously mentioned. My tests are configured with the "grep" plugin too. When I apply an additional filter on 'it' using the `.only `, the execution crashes with the (same) following message: " Cannot read properties of undefined (reading 'parent')".

Do you need any further information to investigate this issue?

Thanks! 


**Cypress Version**
13.10.0

**Node version**
18.16.0

**Operating System**
Ubuntu 22.04.4 LTS
