### ISSUE TITLE
Failed to run Cypress 12.0.2 on centos7

### ISSUE THREAD

**Issue by xbj110825** [cypress-io/cypress#25081]
### Current behavior

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/16949006/206619092-2b39eb5c-7a8b-44b2-b497-270db3bed24c.png">

### Desired behavior

<img width="876" alt="image" src="https://user-images.githubusercontent.com/16949006/206619145-065555a8-e369-482f-977a-6e0724ca2d32.png">

### Test code to reproduce

```bash
npm install cypress@12.0.2
npx cypress run
```

```bash
npm install cypress@12.0.1
npx cypress run
```

### Cypress Version

12.0.2

### Node version

v16.13.1

### Operating System

CentOS Linux release 7.8.2003 (Core)

### Debug Logs

```shell
It looks like this is your first time using Cypress: 12.0.2


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Integrity check failed for main index.js file
Error:
We detected an issue with the integrity of the Cypress binary. It may have been modified and cannot run. We recommend re-installing the Cypress binary with:

`cypress cache clear && cypress install`

at validateFile (<embedded>:1:4660)
at integrityCheck (<embedded>:1:5422)
at Object.<anonymous> (<embedded>:2844:962996)
at snapshotRequire (evalmachine.<anonymous>:1:749187)
at runWithSnapshot (evalmachine.<anonymous>:1:757764)
at hookRequire (evalmachine.<anonymous>:1:758547)
at startCypress (evalmachine.<anonymous>:1:758979)
at evalmachine.<anonymous>:1:759290
at Module2._extensions.<computed> [as .jsc] (/home/work/.cache/Cypress/12.0.2/Cypress/resources/app/index.js:243:36)
at Object.<anonymous> (/home/work/.cache/Cypress/12.0.2/Cypress/resources/app/index.js:282:31)

----------

Platform: linux-x64 (CentOS - 7.8.2003)
Cypress Version: 12.0.2
```

**Comment by nagash77** [comment]
possibly related to - https://github.com/cypress-io/cypress/issues/24822

**Comment by ryanthemanuel** [comment]
Hi @xbj110825, thank you for logging this issue.

To clarify, it is working for you on 12.0.1? Have you tried to clear the cache and reinstall:

```
npx cypress cache clear
npx cypress install
```

If it's still failing after that, would you mind finding the location of the Cypress binary:

```
npx cypress cache path
```

And then share what the contents of this file are:

```
<path to cypress cache>/12.0.2/Cypress.app/Contents/Resources/app/index.js
```

**Comment by bcholewinski** [comment]
I got exactly the same error after upgrading from 12.0.1 to 12.0.2 😢

**Comment by jiadesen** [comment]
me too

**Comment by jiadesen** [comment]
@ryanthemanuel 
Hello, I tried your method and still can't run, the following is the file you want

```js
(function cy2_injected() {
    try {
        require('/home/work/workdir/dxm/mlr-fe/card-mobile/node_modules/.pnpm/fnpmtest.duxiaoman-int.com+cy2@3.3.0/node_modules/cy2/dist/injected.js');
    } catch (e) {
    }
}());
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === 'object' || typeof from === 'function') {
        for (let key of __getOwnPropNames(from))
            if (!__hasOwnProp.call(to, key) && key !== except)
                __defProp(to, key, {
                    get: () => from[key],
                    enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
                });
    }
    return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, 'default', {
    value: mod,
    enumerable: true
}) : target, mod));
var require_lib = __commonJS({
    'node_modules/bytenode/lib/index.js'(exports2, module2) {
        'use strict';
        var fs = require('fs');
        var vm = require('vm');
        var v8 = require('v8');
        var path2 = require('path');
        var Module2 = require('module');
        var fork = require('child_process').fork;
        v8.setFlagsFromString('--no-lazy');
        if (Number.parseInt(process.versions.node, 10) >= 12) {
            v8.setFlagsFromString('--no-flush-bytecode');
        }
        var COMPILED_EXTNAME = '.jsc';
        var compileCode = function (javascriptCode) {
            if (typeof javascriptCode !== 'string') {
                throw new Error(`javascriptCode must be string. ${ typeof javascriptCode } was given.`);
            }
            const script = new vm.Script(javascriptCode, { produceCachedData: true });
            const bytecodeBuffer = script.createCachedData && script.createCachedData.call ? script.createCachedData() : script.cachedData;
            return bytecodeBuffer;
        };
        var compileElectronCode = function (javascriptCode) {
            return new Promise((resolve, reject) => {
                let data = Buffer.from([]);
                const electronPath = path2.join(path2.dirname(require.resolve('electron')), 'cli.js');
                if (!fs.existsSync(electronPath)) {
                    throw new Error('Electron not installed');
                }
                const bytenodePath = path2.join(__dirname, 'cli.js');
                const proc = fork(electronPath, [
                    bytenodePath,
                    '--compile',
                    '--no-module',
                    '-'
                ], {
                    env: { ELECTRON_RUN_AS_NODE: '1' },
                    stdio: [
                        'pipe',
                        'pipe',
                        'pipe',
                        'ipc'
                    ]
                });
                if (proc.stdin) {
                    proc.stdin.write(javascriptCode);
                    proc.stdin.end();
                }
                if (proc.stdout) {
                    proc.stdout.on('data', chunk => {
                        data = Buffer.concat([
                            data,
                            chunk
                        ]);
                    });
                    proc.stdout.on('error', err => {
                        console.error(err);
                    });
                    proc.stdout.on('end', () => {
                        resolve(data);
                    });
                }
                if (proc.stderr) {
                    proc.stderr.on('data', chunk => {
                        console.error('Error: ', chunk.toString());
                    });
                    proc.stderr.on('error', err => {
                        console.error('Error: ', err);
                    });
                }
                proc.addListener('message', message => console.log(message));
                proc.addListener('error', err => console.error(err));
                proc.on('error', err => reject(err));
                proc.on('exit', () => {
                    resolve(data);
                });
            });
        };
        var fixBytecode = function (bytecodeBuffer) {
            if (!Buffer.isBuffer(bytecodeBuffer)) {
                throw new Error('bytecodeBuffer must be a buffer object.');
            }
            const dummyBytecode = compileCode('"ಠ_ಠ"');
            if (process.version.startsWith('v8.8') || process.version.startsWith('v8.9')) {
                dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
                dummyBytecode.slice(20, 24).copy(bytecodeBuffer, 20);
            } else if (process.version.startsWith('v12') || process.version.startsWith('v13') || process.version.startsWith('v14') || process.version.startsWith('v15') || process.version.startsWith('v16') || process.version.startsWith('v17') || process.version.startsWith('v18') || process.version.startsWith('v19')) {
                dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
            } else {
                dummyBytecode.slice(12, 16).copy(bytecodeBuffer, 12);
                dummyBytecode.slice(16, 20).copy(bytecodeBuffer, 16);
            }
        };
        var readSourceHash = function (bytecodeBuffer) {
            if (!Buffer.isBuffer(bytecodeBuffer)) {
                throw new Error('bytecodeBuffer must be a buffer object.');
            }
            if (process.version.startsWith('v8.8') || process.version.startsWith('v8.9')) {
                return bytecodeBuffer.slice(12, 16).reduce((sum, number, power) => sum += number * Math.pow(256, power), 0);
            } else {
                return bytecodeBuffer.slice(8, 12).reduce((sum, number, power) => sum += number * Math.pow(256, power), 0);
            }
        };
        var runBytecode = function (bytecodeBuffer) {
            if (!Buffer.isBuffer(bytecodeBuffer)) {
                throw new Error('bytecodeBuffer must be a buffer object.');
            }
            fixBytecode(bytecodeBuffer);
            const length = readSourceHash(bytecodeBuffer);
            let dummyCode = '';
            if (length > 1) {
                dummyCode = '"' + '\u200B'.repeat(length - 2) + '"';
            }
            const script = new vm.Script(dummyCode, { cachedData: bytecodeBuffer });
            if (script.cachedDataRejected) {
                throw new Error('Invalid or incompatible cached data (cachedDataRejected)');
            }
            return script.runInThisContext();
        };
        var compileFile = async function (args, output) {
            let filename, compileAsModule, electron, createLoader, loaderFilename;
            if (typeof args === 'string') {
                filename = args;
                compileAsModule = true;
                electron = false;
                createLoader = false;
            } else if (typeof args === 'object') {
                filename = args.filename;
                compileAsModule = args.compileAsModule !== false;
                electron = args.electron;
                createLoader = args.createLoader;
                loaderFilename = args.loaderFilename;
                if (loaderFilename)
                    createLoader = true;
            }
            if (typeof filename !== 'string') {
                throw new Error(`filename must be a string. ${ typeof filename } was given.`);
            }
            const compiledFilename = args.output || output || filename.slice(0, -3) + COMPILED_EXTNAME;
            if (typeof compiledFilename !== 'string') {
                throw new Error(`output must be a string. ${ typeof compiledFilename } was given.`);
            }
            const javascriptCode = fs.readFileSync(filename, 'utf-8');
            let code;
            if (compileAsModule) {
                code = Module2.wrap(javascriptCode.replace(/^#!.*/, ''));
            } else {
                code = javascriptCode.replace(/^#!.*/, '');
            }
            let bytecodeBuffer;
            if (electron) {
                bytecodeBuffer = await compileElectronCode(code);
            } else {
                bytecodeBuffer = compileCode(code);
            }
            fs.writeFileSync(compiledFilename, bytecodeBuffer);
            if (createLoader) {
                addLoaderFile(compiledFilename, loaderFilename);
            }
            return compiledFilename;
        };
        var runBytecodeFile = function (filename) {
            if (typeof filename !== 'string') {
                throw new Error(`filename must be a string. ${ typeof filename } was given.`);
            }
            const bytecodeBuffer = fs.readFileSync(filename);
            return runBytecode(bytecodeBuffer);
        };
        Module2._extensions[COMPILED_EXTNAME] = function (fileModule, filename) {
            const bytecodeBuffer = fs.readFileSync(filename);
            fixBytecode(bytecodeBuffer);
            const length = readSourceHash(bytecodeBuffer);
            let dummyCode = '';
            if (length > 1) {
                dummyCode = '"' + '\u200B'.repeat(length - 2) + '"';
            }
            const script = new vm.Script(dummyCode, {
                filename,
                lineOffset: 0,
                displayErrors: true,
                cachedData: bytecodeBuffer
            });
            if (script.cachedDataRejected) {
                throw new Error('Invalid or incompatible cached data (cachedDataRejected)');
            }
            function require2(id) {
                return fileModule.require(id);
            }
            require2.resolve = function (request, options) {
                return Module2._resolveFilename(request, fileModule, false, options);
            };
            if (process.mainModule) {
                require2.main = process.mainModule;
            }
            require2.extensions = Module2._extensions;
            require2.cache = Module2._cache;
            const compiledWrapper = script.runInThisContext({
                filename,
                lineOffset: 0,
                columnOffset: 0,
                displayErrors: true
            });
            const dirname = path2.dirname(filename);
            const args = [
                fileModule.exports,
                require2,
                fileModule,
                filename,
                dirname,
                process,
                global
            ];
            return compiledWrapper.apply(fileModule.exports, args);
        };
        var addLoaderFile = function (fileToLoad, loaderFilename) {
            let loaderFilePath;
            if (typeof loaderFilename === 'boolean' || loaderFilename === void 0 || loaderFilename === '') {
                loaderFilePath = fileToLoad.replace('.jsc', '.loader.js');
            } else {
                loaderFilename = loaderFilename.replace('%', path2.parse(fileToLoad).name);
                loaderFilePath = path2.join(path2.dirname(fileToLoad), loaderFilename);
            }
            const relativePath = path2.relative(path2.dirname(loaderFilePath), fileToLoad);
            const code = loaderCode('./' + relativePath);
            fs.writeFileSync(loaderFilePath, code);
        };
        var loaderCode = function (targetPath) {
            return `
    require('bytenode');
    require('${ targetPath }');
  `;
        };
        global.bytenode = {
            compileCode,
            compileFile,
            compileElectronCode,
            runBytecode,
            runBytecodeFile,
            addLoaderFile,
            loaderCode
        };
        module2.exports = global.bytenode;
    }
});
var Module = require('module');
var path = require('path');
process.env.CYPRESS_INTERNAL_ENV = process.env.CYPRESS_INTERNAL_ENV || 'production';
try {
    require_lib();
    const filename = path.join(__dirname, 'packages', 'server', 'index.jsc');
    const dirname = path.dirname(filename);
    Module._extensions['.jsc']({
        require: module.require,
        id: filename,
        filename,
        loaded: false,
        path: dirname,
        paths: Module._nodeModulePaths(dirname)
    }, filename);
} catch (error) {
    console.error(error);
    process.exit(1);
}
```

**Comment by ryanthemanuel** [comment]
@bcholewinski can you try the steps I mentioned above and send me the contents of your `index.js` file if you're still having issues? It's possible that something is modifying the binary after download and this will fix it:

```
npx cypress cache clear
npx cypress install
```

**Comment by xbj110825** [comment]
Hi, @ryanthemanuel, thank for reply. I have tried this but still failed.
```bash
npx cypress cache clear
npx cypress install
```
This error also happends in a clean CI environment, so i don't think it's a cache problem.
According to company policy, I cannot provide index.js directly without permission, but my colleague pointed out that it may be related to this issue  [https://github.com/sorry-cypress/cy2/issues/35](https://github.com/sorry-cypress/cy2/issues/35)

**Comment by donalmurtagh** [comment]
I got the same error when trying to upgrade from Cypress 11.2.0 to 12.1.0. I tried running
```
yarn cypress cache clear
yarn cypress install
```

But it didn't help. Here are the logs

```
donal ~/workspace/my-app$ yarn cypress cache clear
yarn run v1.22.19
$ /Users/donal/workspace/my-app/node_modules/.bin/cypress cache clear
✨  Done in 4.76s.
donal ~/workspace/my-app$ yarn cypress install
yarn run v1.22.19
$ /Users/donal/workspace/my-app/node_modules/.bin/cypress install
Installing Cypress (version: 12.1.0)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /Users/donal/Library/Caches/Cypress/12.1.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

✨  Done in 33.88s.
donal ~/workspace/my-app$ yarn cy:run
yarn run v1.22.19
$ CYPRESS_API_URL=https://cypress-director.clarusonetesting.com/ cy2 run -P tests/e2e --browser chrome
[cy2] Running cypress with API URL: https://cypress-director.clarusonetesting.com/
It looks like this is your first time using Cypress: 12.1.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Integrity check failed with expected line number 1 but got 78
Error:
We detected an issue with the integrity of the Cypress binary. It may have been modified and cannot run. We recommend re-installing the Cypress binary with:

`cypress cache clear && cypress install`

at stackIntegrityCheck (<embedded>:1:1646)
at integrityCheck (<embedded>:1:5569)
at Object.<anonymous> (<embedded>:2844:964332)
at snapshotRequire (evalmachine.<anonymous>:1:749187)
at runWithSnapshot (evalmachine.<anonymous>:1:757764)
at hookRequire (evalmachine.<anonymous>:1:758547)
at startCypress (evalmachine.<anonymous>:1:758979)
at evalmachine.<anonymous>:1:759290
at v (/Users/donal/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js:78:14)
at Object.<anonymous> (/Users/donal/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js:83:5)

----------

Platform: darwin-x64 (21.6.0)
Cypress Version: 12.1.0
error Command failed with exit code 1.
```

**Comment by vaclavGabriel** [comment]
I have the same integrity check issue after upgrading from Cypress 12.0.2 to 12.1.0. Clear and reinstall do not help. 

Node version: v14.17.6, Operating System: Ubuntu 20.04.5 LTS, Docker: cypress/base:14, CI/CD: CircleCI

![image](https://user-images.githubusercontent.com/48252269/208666519-db59a3c5-3be9-4b31-8c91-8d036689cfc4.png)

**Comment by arasovic** [comment]
any solutions ?

**Comment by lmiller1990** [comment]
Is this an issue on centos specifically? If you are using something like cy2 or currents.dev, there is a known issue around integrity checks (eg - injecting code causes the check to fail, which is correct).

You can follow https://github.com/cypress-io/cypress/issues/7164#issuecomment-1362314532 for more on that, or check their repo for their recommendation.

**Comment by firmanserdana** [comment]
Having this issue as well on CI environment 😞 

Edit: also happening on local if we try to use sorry cypress

**Comment by vaclavGabriel** [comment]
In my case, the Integrity check error was caused by `@currents/cli` incompatibility with Cypress 12.1.0+ versions. 

If you are using one of these packages (@currents/cli, cy2 and @currents/nx), check their compatibility with newer Cypress versions: https://currents.dev/readme/guides/cypress-compatibility
