### ISSUE TITLE
Unable to run WebKit on TeamCity using Docker

### ISSUE THREAD

**Issue by IhorKWT** [cypress-io/cypress#25151]
### Current behavior

When running the Webkit locally using `npx cypress run --browser webkit` it works. But running same command on TeamCity giving the error and doesn't even start the browser. Also, tried on different versions of Node.
`[Step 2/2] npm ERR! code 1
[15:39:06][Step 2/2] npm ERR! path /e2e/node_modules/playwright-webkit
[15:39:06][Step 2/2] npm ERR! command failed
[15:39:06][Step 2/2] npm ERR! command sh -c node install.js
[15:39:06][Step 2/2] npm ERR! node:internal/process/promises:279
[15:39:06][Step 2/2] npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
[15:39:06][Step 2/2] npm ERR!             ^
[15:39:06][Step 2/2] npm ERR! 
[15:39:06][Step 2/2] npm ERR! [Error: EACCES: permission denied, mkdir '/root/.cache/ms-playwright'] {
[15:39:06][Step 2/2] npm ERR!   errno: -13,
[15:39:06][Step 2/2] npm ERR!   code: 'EACCES',
[15:39:06][Step 2/2] npm ERR!   syscall: 'mkdir',
[15:39:06][Step 2/2] npm ERR!   path: '/root/.cache/ms-playwright'
[15:39:06][Step 2/2] npm ERR! }
[15:39:06][Step 2/2] 
[15:39:06][Step 2/2] npm ERR! A complete log of this run can be found in:
[15:39:06][Step 2/2] npm ERR!     /root/.npm/_logs/2022-12-13T20_31_13_282Z-debug-0.log
[15:39:08][Step 2/2] libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[15:39:08][Step 2/2] [251:1213/203908.481090:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[15:39:10][Step 2/2] Your configFile threw an error from: /e2e/cypress.config.js
[15:39:10][Step 2/2] 
[15:39:10][Step 2/2] The error was thrown while executing your e2e.setupNodeEvents() function:
[15:39:10][Step 2/2] 
[15:39:10][Step 2/2] Error: Cannot find module 'cypress-failed-log/src/failed'
[15:39:10][Step 2/2] Require stack:
[15:39:10][Step 2/2] - /e2e/cypress/plugins/index.js
[15:39:10][Step 2/2] - /e2e/cypress.config.js
[15:39:10][Step 2/2] - /root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js
[15:39:10][Step 2/2] - /root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js
[15:39:10][Step 2/2]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[15:39:10][Step 2/2]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[15:39:10][Step 2/2]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[15:39:10][Step 2/2]     at require (node:internal/modules/cjs/helpers:102:18)
[15:39:10][Step 2/2]     at module.exports (/e2e/cypress/plugins/index.js:22:13)
[15:39:10][Step 2/2]     at setupNodeEvents (/e2e/cypress.config.js:33:51)
[15:39:10][Step 2/2]     at /root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:118:14
[15:39:10][Step 2/2]     at tryCatcher (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/bluebird/js/release/util.js:16:23)
[15:39:10][Step 2/2]     at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/bluebird/js/release/method.js:39:29)
[15:39:10][Step 2/2]     at RunPlugins.load (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:115:9)
[15:39:10][Step 2/2]     at RunPlugins.runSetupNodeEvents (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:276:10)
[15:39:10][Step 2/2]     at EventEmitter.<anonymous> (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:185:22)
[15:39:10][Step 2/2]     at EventEmitter.emit (node:events:527:28)
[15:39:10][Step 2/2]     at process.<anonymous> (/root/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
[15:39:10][Step 2/2]     at process.emit (node:events:527:28)
[15:39:10][Step 2/2]     at emit (node:internal/child_process:938:14)
[15:39:10][Step 2/2]     at processTicksAndRejections (node:internal/process/task_queues:84:21)
[15:39:12][Step 2/2] Process exited with code 1
[15:39:12][Step 2/2] Process exited with code 1 (Step: Run All Tests (Command Line))
[15:39:16][Step 2/2] Step Run All Tests (Command Line) failed`

### Test code to reproduce

From TeamCity :
npm install
cypress run --browser webkit --reporter teamcity --record --config baseUrl="https://google.com/" --spec "cypress/e2e/tests/test.spec.js"

### Cypress Version

10.11.0

### Node version

16.16.0

### Operating System

Linux

**Comment by mike-plummer** [comment]
Hi @IhorKWT , sorry that you're having issues getting Webkit working. Based on the logs it looks like there might be a couple different things going on.
1. Can you confirm that you accounted for the [Linux Setup](https://docs.cypress.io/guides/guides/launching-browsers#Linux-Dependencies) needed for Webkit support? Your TeamCity build agent may be lacking some base dependencies
2. The Webkit binaries are cached at `.cache/ms-playwright` but your logs indicate there are some filesystem permission issues - you may need to account for that in your agent.

Let me know if you are still seeing issues after validating those items in your TeamCity environment

**Comment by lmiller1990** [comment]
We need more information to continue debugging. Happy to reopen if more information becomes available. In the meantime, I don't see any actionable work on our end, so I am going to close this.
