### ISSUE TITLE
cy.selectFile within cy.origin not working correctly

### ISSUE THREAD

**Issue by mduft** [cypress-io/cypress#25261]
### Workarounds
https://github.com/cypress-io/cypress/issues/25261#issuecomment-1538417558
https://github.com/cypress-io/cypress/issues/25261#issuecomment-2739029669

### Current behavior

cy.selectFile behaves wrong as soon as wrapped in a cy.origin call. I had multiple different kinds of errors while playing with it, but did not get it to work properly somehow. I tried with the filename shortcut and the fixture syntax, both to no avail. The fixture syntax *does* look like it works, but somehow the file content is not properly attached to the input, e.g. an image is not shown correctly when uploading an image.

### Desired behavior

File should be attached to selectFile properly.

### Test code to reproduce

https://github.com/mduft/cypress-test-tiny/tree/master

### Cypress Version

12.2.0

### Node version

16.17.2

### Operating System

Windows 11

**Comment by mduft** [comment]
Also, in my real world use-case I get this (additionally to the path being undefined as in the tiny test case):
![image](https://user-images.githubusercontent.com/533793/209313007-2aafec02-c46e-4f77-a666-d4c98c6b5e14.png)
Which I did not manage to reproduce with the tiny test case, and I have NO idea why...?

```
xml.js:30 Uncaught TypeError: Cannot destructure property 'subject' of 'data' as it is null.
    at SpecBridgeCommunicator.handleSubjectAndErr (xml.js:30:2)
    at SpecBridgeCommunicator.toPrimary (xml.js:30:2)
    at SpecBridgeCommunicator.<anonymous> (xml.js:30:2)
    at SpecBridgeCommunicator.emit (xml.js:30:2)
    at SpecBridgeCommunicator.onMessage (xml.js:30:2)
    at xml.js:30:2
```

**Comment by emilyrohrbough** [comment]
@mduft Interesting! Thank you for the reproduction! I am able to reproduce the issue you are seeing with the example you provided and verifying it works without the use of `cy.origin()`. I also tried reading from the fixture like our documentation suggests and am seeing:
```js
      cy.origin('https://www.w3schools.com', () => {
        cy.visit('/howto/howto_html_file_upload_button.asp');
        cy.fixture('example.json', { encoding: null }).as('myFixture')
        cy.get('input[type=file]').selectFile('@myFixture', { force: true });
      });
```
and am seeing:

![Image](https://user-images.githubusercontent.com/14099737/209405409-23c44ec2-ac7c-4fc0-86ea-45f163665686.png)

Something is def acting wonky with `.selectFile()`, inside of the `.origin()` callback. Marking this as a bug.

**Comment by Danc9520** [comment]
Are there any workarounds for this in the meantime?

**Comment by mduft** [comment]
> Are there any workarounds for this in the meantime?

None that I know of. My 12.x update is completely blocked by this ATM.

**Comment by mduft** [comment]
Any news on this? I'm stuck on Cypress 11.x without any way to update to 12.x due to this issue.

**Comment by mduft** [comment]
We still cannot move forward with Cypress 12 due to this BLOCKER. Any plans to fix this anytime soon?

**Comment by georgwindhaber** [comment]
This issue is also blocking one of my tests, so +1

**Comment by fredbh** [comment]
Just wanted to chime in saying this issue is blocking the writing of our tests as well, would be great to have any updates.

**Comment by chrisbreiding** [comment]
I was able to find a workaround for this issue by reading a fixture and stringifying it into an alias:

```js
  cy.origin('https://www.w3schools.com', () => {
    cy.visit('/howto/howto_html_file_upload_button.asp');
    cy.fixture('example.json').then(JSON.stringify).as('myFixture'); // <= read the fixture with default encoding, then stringify it before saving it as an alias
    cy.get('input[type=file]').selectFile('@myFixture');
  });
```

**Comment by mduft** [comment]
Unfortunately that does not help with binaries (ZIP files, pictures, etc.), right? We're still blocked on this issue, and still are forced to stay on 11, even though it has been quite many 12 releases now - any chance to get this properly fixed?

**Comment by DariaBor** [comment]
Please, any news on it?=(( it is a blocker indeed
And can anyone tell which cypress version doesn't have this bug? I switched to 11.2.0 and it's not working as well((

**Comment by SemaEfe** [comment]
Hi, is there any solution about that. I have a problem same

**Comment by nageshcrest** [comment]
Thanks to @chrisbreiding,
By referring your code sample 
I tweaked a bit and tried below and it worked for me, thank you so much.

```js
cy.origin('https://example.com', () => {
    cy.visit('/upload');
     cy.fixture('user.csv').as('myFixture');
        cy.get('[data-testid="file-input"]').selectFile('@myFixture')
  });
```

**Comment by shastrisubramaniam** [comment]
Can a fix for this be prioritized and expedited ? We have multiple use cases for uploading image files within origin ?

I don't see any workaround for this.

**Comment by jennifer-shehane** [comment]
@shastrisubramaniam Have you tried the workaround described here? https://github.com/cypress-io/cypress/issues/25261#issuecomment-1538417558

**Comment by shastrisubramaniam** [comment]
@jennifer-shehane  My understanding is that the workaround above  does not work for image files

**Comment by ainkollu** [comment]
the issue persists for files of type image and PDF.....below is the error that is thrown on trying to upload an image or a PDF

![Screenshot 2024-10-24 at 9 51 16 PM](https://github.com/user-attachments/assets/980c26e2-3a17-45f5-a30b-9b082c907159)

**Comment by Neill83** [comment]
We also have this issue when using `cy.get(...).selectFile(...)` inside cy.origin. We have tried everything what was suggested.
![image](https://github.com/user-attachments/assets/731bf3fb-df7c-4f7a-b8d5-306fc10ae910)

**Comment by eshadboltadr** [comment]
I'm also having this problem in cypress 13.16.0 . The cy.origin is interfering with .selectFile for image files.

**Comment by eshadboltadr** [comment]
**Workaround for binary/image/PDF files**

- Move cy.fixture() / cy.readfile() outside of and before cy.origin()
- Pass the data through origin arguments as base64 string
- Convert base64 to Buffer which can be used in selectFile()

```js
const fileName = 'Sample Document.pdf';
const filePath = 'pathInsideFixturesFolder/' + fileName;
cy.fixture(filePath, 'base64').then(base64 => {
    cy.origin("...", { args: { fileName, base64 } }, (args) => {
        const { fileName, base64 } = args;
        const buffer = Cypress.Buffer.from(base64, 'base64');
        cy.get('#UploadInput').selectFile({ contents: buffer, fileName: fileName }, { force: true });
    });
});
```

Also works with readFile

```js
const fileName = 'Sample Document.pdf';
const filePath = 'cypress/fixtures/' + fileName;
cy.readFile(filePath, 'base64').then(base64 => {
    cy.origin("...", { args: { fileName, base64 } }, (args) => {
        const { fileName, base64 } = args;
        const buffer = Cypress.Buffer.from(base64, 'base64');
        cy.get('#UploadInput').selectFile({ contents: buffer, fileName: fileName }, { force: true });
    });
});
```
