### ISSUE TITLE
Cypress Launch Hanging on Ubuntu

### ISSUE THREAD

**Issue by naveen08k25** [cypress-io/cypress#25327]
### Current behavior

When i try to run `npm run cypress:open`, right after installing npm install cypress --save-dev i can see cypress lauch is loading forever,  i have tried to remove the chromium (it didnt helped even from the snap)
![Screenshot from 2023-01-02 18-10-17](https://user-images.githubusercontent.com/121804428/210232911-d9bd8fbf-6afe-406b-960b-283cfca362a2.png)

### Debug logs

```Text
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'cypress:open' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'precypress:open', 'cypress:open', 'postcypress:open' ]
5 info lifecycle cyp-12-project@1.0.0~precypress:open: cyp-12-project@1.0.0
6 info lifecycle cyp-12-project@1.0.0~cypress:open: cyp-12-project@1.0.0
7 verbose lifecycle cyp-12-project@1.0.0~cypress:open: unsafe-perm in lifecycle true
8 verbose lifecycle cyp-12-project@1.0.0~cypress:open: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/naveenkumar.k/Workout-Folder/cyp-12-project/node_modules/.bin:/home/naveenkumar.k/.asdf/shims:/home/naveenkumar.k/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle cyp-12-project@1.0.0~cypress:open: CWD: /home/naveenkumar.k/Workout-Folder/cyp-12-project
10 silly lifecycle cyp-12-project@1.0.0~cypress:open: Args: [ '-c', 'cypress open' ]
11 silly lifecycle cyp-12-project@1.0.0~cypress:open: Returned: code: 1  signal: null
12 info lifecycle cyp-12-project@1.0.0~cypress:open: Failed to exec cypress:open script
13 verbose stack Error: cyp-12-project@1.0.0 cypress:open: `cypress open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cyp-12-project@1.0.0
15 verbose cwd /home/naveenkumar.k/Workout-Folder/cyp-12-project
16 verbose Linux 5.15.0-56-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "cypress:open"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error cyp-12-project@1.0.0 cypress:open: `cypress open`
22 error Exit status 1
23 error Failed at the cyp-12-project@1.0.0 cypress:open script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Cypress Version

12.2.0

### Node version

10.19

### Package Manager

npm

### Package Manager Version

6.14.4

### Operating system

Linux

### Operating System Version

20

**Comment by naveen08k25** [comment]
I have tried the steps from the following thread but couldnt fix the issue https://github.com/cypress-io/cypress/issues/7020

**Comment by astone123** [comment]
@naveen08k25 could you try running cypress with 
```
DEBUG="cypress:*" npm run cypress:open
```

and paste the logs here? Thanks

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
