### ISSUE TITLE
Question: cy.task failed with typeError

### ISSUE THREAD

**Issue by CassieRyu** [cypress-io/cypress#2553]
### Current behavior:

Given I use "ssh2-sftp-client" as a sftp client to upload file to my local sftp server,
When I use task to wrap the upload function, and call in my test cases,
Then got following error msg, but in console log, but in fact I've already uploaded successful
```
CypressError: cy.task('uploadPremiseFile') failed with the following error:
TypeError: Cannot read property 'toString' of undefined
    at invoke (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:6:40)
    at /Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
    at tryCatcher (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:47:28)
    at Object.getBody (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:8:8)
    at execute (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:81:12)
    at EventEmitter.ipc.on (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:125:5)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at process.<anonymous> (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Desired behavior:

When function finished successfully, should pass without error;

### Steps to reproduce:

`plugins/index.js`
```js
let Client = require('ssh2-sftp-client');
let sftp = new Client();
let rootPath = process.cwd();

const uploadFile = (filePath) =>{
	sftp.connect({
		host: 'localhost',
		port: '22',
		username: 'foo',
		password: 'pass'
	}).then(() => {
		return sftp.fastPut(rootPath + filePath, '/upload/testFile.json', 'utf8');
	}).then((data) => {
		console.log('data info: ', data);
		sftp.end();
	});
};

module.exports = (on) => {
    on('task', {
    	uploadPremiseFile(filePath){
    		console.log('rootPath:', rootPath);
    		console.log('Start upload file: ', filePath);
		uploadFile(filePath);
	}
    })
};
```
`integration/testFile.spec.js`
```js
describe('Landing page test', ()=>{
	beforeEach(()=>{
		cy.visit('/');
	});
it('upload file', ()=>{
		const filePath = '/cypress/fixtures/testFile.json';
		 cy.task('uploadPremiseFile', filePath);
	});
```
### Versions

cypress: 3.1.0; Chrome 69; Mac

**Comment by jennifer-shehane** [comment]
Looks like the `taskEvent[event]` is `undefined` here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/child/task.js#L6

**Comment by chrisbreiding** [comment]
Yeah, definitely looks like a bug.

Cypress is trying to tell you that you need to return something instead of `undefined` from the task and show you where in your code you need to do it, but looks like there's a bug preventing it and causing the error you're seeing.

We'll get that bug sorted out, but for the sake of your test, if you return your promises (instead of undefined), it won't trigger that part of the code in Cypress and your test should work. Return `uploadFile(filePath)` from the task, and in the `uploadFile` function, return `sftp.connect(/* */)`.

**Comment by CassieRyu** [comment]
Thank you @chrisbreiding, the temporary solution works, and looking forward the bug been solved in later versions.

**Comment by CassieRyu** [comment]
Hi @chrisbreiding , here's another strange behavior happened even I used the method you provided. For upload function, as you recommend `Return uploadFile(filePath) from the task, and in the uploadFile function, return sftp.connect(/* */)` and it works fine. But when I manipulate same trick on delete files or remove dir functions, I got another server related error.
`plugins/index.js`
```
let Client = require('ssh2-sftp-client');
let sftp = new Client();
let rootPath = process.cwd();
const config = {
	host: 'localhost',
	port: '22',
	username: 'foo',
	password: 'pass'
};

const uploadFileToRemote = (filePath, remoteFile) =>{
	return sftp.connect(config).then(() => {
		return sftp.fastPut(rootPath + filePath, remoteFile, 'utf8');
	});
};

const deleteFileFromRemote = (remoteFile) =>{
	 return sftp.connect(config).then(() => {
		 return sftp.delete(remoteFile, 'utf8');
	});
};

module.exports = (on) => {
	on('task', {
		uploadPremiseFile: (Obj)=>{
    		console.log('rootPath:', rootPath);
    		console.log('Start upload file: ', Obj.localPath);
			return uploadFileToRemote(Obj.localPath, Obj.remotePath);
		},
		deletePremiseFile: (remoteFile)=>{
			console.log('start delete file from remote');
			 return deleteFileFromRemote(remoteFile);
		}
	});
};
```
`integration/landingPage.spec.js`
```
it('upload file', ()=>{
		const localFile = '/cypress/fixtures/testFile.json';
		const remoteFile = '/upload/testFile.json';
		cy.task('uploadPremiseFile', {localPath: localFile, remotePath: remoteFile});

	});

	it('delete file', ()=>{
		const remoteFile = '/upload/testFile.json';
		cy.task('deletePremiseFile', remoteFile);
	});
```
When I run this testing file, first case `upload file` is passed successful, but second case `delete file` got error as below, where file is already removed as expected.
```
CypressError: cy.task('deletePremiseFile') failed with the following error:

> TypeError: Cannot read property 'toString' of undefined
    at invoke (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:6:40)
    at /Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
    at tryCatcher (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:47:28)
    at Object.getBody (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:8:8)
    at execute (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:81:12)
    at EventEmitter.ipc.on (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:125:5)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at process.<anonymous> (/Users/shanliu/Library/Caches/Cypress/3.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Would you mind help take a look if there's any suggestion? Thank you in advance.

**Comment by chrisbreiding** [comment]
My guess is that `sftp.delete` resolves `undefined`, so it's hitting the same issue. You can return `null` from the promise chain to bypass the bug in that case.

```javascript
const deleteFileFromRemote = (remoteFile) =>{
	 return sftp.connect(config).then(() => {
		 return sftp.delete(remoteFile, 'utf8').then(() => {
             return null;
         });
	});
};
```

**Comment by CassieRyu** [comment]
Amazing, thank you again @chrisbreiding . It's woking now, very helpful to me.

**Comment by Prathibha-Das** [comment]
I am trying to copy the output from the logs to csv file in my project
Am getting cy.task('log') failed with the following error:
> csvdata is not defined
Also attaching the screenshot

[New Microsoft Word Document.docx](https://github.com/cypress-io/cypress/files/5379030/New.Microsoft.Word.Document.docx)

I have installed the npm install --save-dev csvdata

module.exports = (on) => {

  // configure plugins here
const csvdata = require('csvdata')
on('task', {
    log(message) {
        csvdata.write('./logs.csv', message, {
            append: true,
            header: 'stats,numusers'
        })
        return null
    }
})
}
