### ISSUE TITLE
Assigning alias twice leads to RangeError

### ISSUE THREAD

**Issue by LarissaKitzberger** [cypress-io/cypress#25641]
### Current behavior

If an alias is assigned twice by mistake, the tests break with a **"RangeError Maximum call stack size exceeded"**. Unfortunately, this behavior makes finding the mistake quite hard. This issue occurred after updating to version 12.3.0 or 12.4.0.

### Desired behavior

If such code is detected by Cypress, a clearer error message would be helpful. 

### Test code to reproduce

```js
it('RangeErrorExample', () => {
    cy.get('div').as('container');
    cy.get('@container').as('container');
});
```

### Cypress Version

12.4.0

### Node version

16.13.0

### Operating System

Windows

### Other
```bash
**Full Stack Trace:**
 at $Cy.SetterGetter [as state] (http://localhost:4200/__cypress/runner/cypress_runner.js:158897:35)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138845:13)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
    at $Cy.getSubjectFromChain (http://localhost:4200/__cypress/runner/cypress_runner.js:151571:34)
    at Array.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:138925:24)
From previous event:
    at CommandQueue.runCommand (http://localhost:4200/__cypress/runner/cypress_runner.js:149923:8)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:150123:19)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:150144:16)
From previous event:
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:150123:39)
From previous event:
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:163626:77)
From previous event:
    at CommandQueue.run (http://localhost:4200/__cypress/runner/cypress_runner.js:163621:21)
    at CommandQueue.run (http://localhost:4200/__cypress/runner/cypress_runner.js:150187:15)
    at $Cy.runQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:151078:14)
    at cy.<computed> [as visit] (http://localhost:4200/__cypress/runner/cypress_runner.js:151160:12)
    at runnable.fn (http://localhost:4200/__cypress/runner/cypress_runner.js:151339:19)
    at callFn (http://localhost:4200/__cypress/runner/cypress_runner.js:104935:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:104922:7)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:158288:30)
From previous event:
    at Object.onRunnableRun (http://localhost:4200/__cypress/runner/cypress_runner.js:158271:53)
    at $Cypress.action (http://localhost:4200/__cypress/runner/cypress_runner.js:147586:28)
    at Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:156289:13)
    at ../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:4200/__cypress/runner/cypress_runner.js:105594:10)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:105720:12)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:105503:14)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:105513:7)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:105415:14)
    at Hook.<anonymous> (http://localhost:4200/__cypress/runner/cypress_runner.js:105476:7)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:158182:24)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:158209:13)
From previous event:
    at onNext (http://localhost:4200/__cypress/runner/cypress_runner.js:158206:59)
    at done (http://localhost:4200/__cypress/runner/cypress_runner.js:104875:5)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:104940:11)
From previous event:
    at callFn (http://localhost:4200/__cypress/runner/cypress_runner.js:104938:14)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:104922:7)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:158288:30)
From previous event:
    at Object.onRunnableRun (http://localhost:4200/__cypress/runner/cypress_runner.js:158271:53)
    at $Cypress.action (http://localhost:4200/__cypress/runner/cypress_runner.js:147586:28)
    at Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:156289:13)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:105437:10)
    at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:105481:5)
    at timeslice (http://localhost:4200/__cypress/runner/cypress_runner.js:99407:27)
```
http://localhost:4200/#/main/station

ChromeChrome 109

1000x1300
(69%)

**Comment by warrensplayer** [comment]
This can be reproduced starting with Cypress version 12.  

See: 

[cypress_25641.zip](https://github.com/cypress-io/cypress/files/10582850/cypress_25641.zip)

Routing to E2E team
