### ISSUE TITLE
screenshotOnRunFailure setting is always true despite configuration set to false

### ISSUE THREAD

**Issue by Towerss** [cypress-io/cypress#25765]
### Current behavior

Currently, when running e2e tests with screenshotOnRunFailure = false, screenshots are still taken and stored when a test fails. As we have a few tests falling in developemnt, this is creating unnecessary files and folders.

I have tried using the config file as described in the settings object here -> [configuration#Screenshots](https://docs.cypress.io/guides/references/configuration#Screenshots) :

```
./cypress.config.ts

import { defineConfig } from "cypress";

export default defineConfig({
  video: false,
  screenshotOnRunFailure: false,
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
})
```

Also, I have tried calling the ... API as described here ...[screenshot-api#Disable-screenshots-on-run-failures](https://docs.cypress.io/api/cypress-api/screenshot-api#Disable-screenshots-on-run-failures) :

```
./cypress/support/e2e.ts

Cypress.Screenshot.defaults({
  screenshotOnRunFailure: false,
});
```

Last, I also tried to provide a value from cmd but also fails:
`npx Cypress run --spec ./cypress/e2e/2-advanced-examples/misc.cy.js -c screenshotOnRunFailure=false`

![image](https://user-images.githubusercontent.com/15847763/217994937-9078eeb1-a2e5-46de-affd-c93a911d4f76.png)

### Desired behavior

If the value of screenshotOnRunFailure is set to false, it should be honoured, screenshots of failing tests should not be taken, and a screenshots folder should not be created. 

### Test code to reproduce

1. Run: `npx create-react-app my-app --template typescript`
2. Install Cypress: `npm install Cypress -D`
3. Add to `./cypress.config.ts`:

```
import { defineConfig } from "cypress";

export default defineConfig({
  video: false,
  screenshotOnRunFailure: false,
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
})
```

4. Or add to `./cypress/support/e2e.ts`:

```
./cypress\support\e2e.ts

Cypress.Screenshot.defaults({
  screenshotOnRunFailure: false,
});
```

5. Run sample e2e test: `npx Cypress run --spec ./cypress/e2e/2-advanced-examples/misc.cy.js`

### Cypress Version

12.5.1

### Node version

18.13.0

### Operating System

Windows 10 64 bit

### Debug Logs

```shell
$ npx Cypress run --spec ./cypress/e2e/2-advanced-examples/misc.cy.js


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.5.1
        │
  │ Browser:        Electron 106 (headless)
        │
  │ Node Version:   v18.13.0 (C:\Program Files\nodejs\node.exe)
        │
  │ Specs:          1 found (misc.cy.js)
        │
  │ Searched:       C:\Users\...\cypress\e2e\2-advanced-examples\mi │
  │                 sc.cy.js
        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────


  Running:  misc.cy.js
 (1 of 1)


  Misc
    √ .end() - end the command chain (664ms)
    1) cy.exec() - execute a system command
    √ cy.focused() - get the DOM element that has focus (331ms)
    √ cy.wrap() - wrap an object (154ms)
    Cypress.Screenshot
      √ cy.screenshot() - take a screenshot (1207ms)
      √ Cypress.Screenshot.defaults() - change default config of screenshots (121ms)


  5 passing (5s)
  1 failing

  1) Misc
       cy.exec() - execute a system command:
     CypressError: `cy.exec('echo Jane Lane')` failed because the command exited with a non-zero code.

Pass `{failOnNonZeroExit: false}` to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
/c/Program: Files\Git\usr\bin\bash.exe: No such file or directory

https://on.cypress.io/exec
      at <unknown> (https://example.cypress.io/__cypress/runner/cypress_runner.js:136659:85)
      at tryCatcher (https://example.cypress.io/__cypress/runner/cypress_runner.js:8914:23)      at Promise._settlePromiseFromHandler (https://example.cypress.io/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (https://example.cypress.io/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (https://example.cypress.io/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (https://example.cypress.io/__cypress/runner/cypress_runner.js:7031:18)
      at _drainQueueStep (https://example.cypress.io/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue (https://example.cypress.io/__cypress/runner/cypress_runner.js:3614:9)      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:3500:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/2-advanced-examples/misc.cy.js:54:7)       




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6
        │
  │ Passing:      5
        │
  │ Failing:      1
        │
  │ Pending:      0
        │
  │ Skipped:      0
        │
  │ Screenshots:  2
        │
  │ Video:        false
        │
  │ Duration:     4 seconds
        │
  │ Spec Ran:     misc.cy.js
        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  C:\Users\...\cypress\screenshots\misc.cy.js\Misc      (1280x720)
     -- cy.exec() - execute a system command (failed).png

  -  C:\Users\...\cypress\screenshots\misc.cy.js\my-im    (1000x1816)
     age.png



====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  
Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  misc.cy.js                               00:04        6        5        1        -  
      - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:04        6        5        1        -
```

**Comment by warrensplayer** [comment]
@Towerss The methods you reference for setting `screenshotOnRunFailure` will only disable the automatic screenshots that Cypress will take if a test has a failure.  If your test is explicitly calling `cy.screenshot` before the test fails, then those screenshots will still be taken.  The scaffolded test you are showing in your screenshots and examples above is a test that explicitly calls `cy.screenshot`.
