### ISSUE TITLE
Unable to run component testing in Angular if cypress folder is not in root

### ISSUE THREAD

**Issue by vanyasav** [cypress-io/cypress#25887]
### Current behavior

I am trying to add cypress to an existing project with the following structure: 

angularApplication/
├─ projects/
│  ├─ testProject/
│  │  ├─ src/
│  │  ├─ tsconfig.app.json
│  │  ├─ tsconfig.json
│  │  ├─ tsconfig.spec.json
├─ angular.json
├─ package.json

I initiated and configured cypress so that cypress directory is located inside testProject directory.
e2e tests work just fine, while component testing outputs an error: 

```
Error: error TS5012: Cannot read file 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json': 
ENOENT: no such file or directory, open 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json'.
```

### Desired behavior

Cypress should find a path to tsconfig.app.json as stated in angular.json

` "tsConfig": "projects/testProject/tsconfig.app.json"`

### Test code to reproduce

[link to my repo](https://github.com/vanyasav/cypressTest)

1. npm i
2. npm run cypress:open
3. go to component testing

### Cypress Version

12.6.0

### Node version

16.19.1

### Operating System

Windows 11

### Debug Logs

```shell
cypress:lifecycle:ProjectConfigManager call event dev-server:start for invocation id inv1 +20ms
  cypress:lifecycle:child:RunPlugins:15996 execute plugin event: dev-server:start ({ invocationId: 'inv1', eventId: 2 }) +23ms
  cypress:lifecycle:child:run_require_async_child:15996 unhandled rejection: Error: error TS5012: Cannot read file 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json': ENOENT: no such file or directory, open 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json'.
error TS18003: No inputs were found in config file 'C:/Users/KDFXMO~1/AppData/Local/Temp/cypress-angular-ct/tsconfig.json'. Specified 'include' paths were '["C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/**/*
.cy.ts","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/cypress/support/component.js","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/node_modules/cypress/types/index.d.ts"]' and 'exclude' paths were '["C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/out-tsc/cy"]'.

    at readTsconfig (C:\Users\packages\angular_devkit\build_angular\src\utils\read-tsconfig.ts:35:11)
    at async generateWebpackConfig (C:\Users\packages\angular_devkit\build_angular\src\utils\webpack-browser-config.ts:43:20)
    at async generateBrowserWebpackConfigFromContext (C:\Users\packages\angular_devkit\build_angular\src\utils\webpack-browser-config.ts:155:18)
    at async getAngularCliWebpackConfig (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:145:24)     
    at async angularHandler (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:180:27)
    at async getPreset (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:76:20)
    at async Function.devServer.create (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:93:61)
    at async C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:25:24 +1s
  cypress:lifecycle:ProjectConfigIpc unhandled error in child process {
  name: 'Error',
  message: "\x1B[91merror\x1B[0m\x1B[90m TS5012: \x1B[0mCannot read file 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json': ENOENT: no such file or directory, open 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json'.\r\n" +
    `\x1B[91merror\x1B[0m\x1B[90m TS18003: \x1B[0mNo inputs were found in config file 'C:/Users/KDFXMO~1/AppData/Local/Temp/cypress-angular-ct/tsconfig.json'. Specified 'include' paths were '["C:/Users/KDFX Modes/WebstormProjects/cy
pressTest/projects/testProject/**/*.cy.ts","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/cypress/support/component.js","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/node_modules/cypress/types/index.d.ts"]' and 'exclude' paths were '["C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/out-tsc/cy"]'.\r\n`,
  stack: "Error: \x1B[91merror\x1B[0m\x1B[90m TS5012: \x1B[0mCannot read file 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json': ENOENT: no such file or directory, open 'C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/projects/testProject/tsconfig.app.json'.\r\n" +
    `\x1B[91merror\x1B[0m\x1B[90m TS18003: \x1B[0mNo inputs were found in config file 'C:/Users/KDFXMO~1/AppData/Local/Temp/cypress-angular-ct/tsconfig.json'. Specified 'include' paths were '["C:/Users/KDFX Modes/WebstormProjects/cy
pressTest/projects/testProject/**/*.cy.ts","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/cypress/support/component.js","C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/node_modules/cypress/types/index.d.ts"]' and 'exclude' paths were '["C:/Users/KDFX Modes/WebstormProjects/cypressTest/projects/testProject/out-tsc/cy"]'.\r\n` +
    '\n' +
    '    at readTsconfig (C:\\Users\\packages\\angular_devkit\\build_angular\\src\\utils\\read-tsconfig.ts:35:11)\n' +
    '    at async generateWebpackConfig (C:\\Users\\packages\\angular_devkit\\build_angular\\src\\utils\\webpack-browser-config.ts:43:20)\n' +
    '    at async generateBrowserWebpackConfigFromContext (C:\\Users\\packages\\angular_devkit\\build_angular\\src\\utils\\webpack-browser-config.ts:155:18)\n' +
    '    at async getAngularCliWebpackConfig (C:\\Users\\KDFX Modes\\AppData\\Local\\Cypress\\Cache\\12.6.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\node_modules\\@cypress\\webpack-dev-server\\dist\\helpers\\angularHandler.js:145:24)\n' +
    '    at async angularHandler (C:\\Users\\KDFX Modes\\AppData\\Local\\Cypress\\Cache\\12.6.0\\Cypress\\resources\\app\\node_modules\\@packages\\server\\node_modules\\@cypress\\webpack-dev-server\\dist\\helpers\\angularHandler.js:180:27)\n' +
    at async getAngularCliWebpackConfig (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:145:24)     
    at async angularHandler (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\helpers\angularHandler.js:180:27)
    at async getPreset (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:76:20)
    at async Function.devServer.create (C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:93:61)
    at async C:\Users\KDFX Modes\AppData\Local\Cypress\Cache\12.6.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\devServer.js:25:24 +0ms
```
```


### Other

_No response_

**Comment by lmiller1990** [comment]
Hmm I suspect you might need something in `cypress.config`, see here: https://docs.cypress.io/guides/component-testing/angular/overview#Options-API

Possibly:

```js
export default {
  component: {
    framework: 'angular',
    bundler: 'webpack',
    options: {
      projectConfig: {
        root: '',
        sourceRoot: 'apps/my-app',
        buildOptions: {
          tsConfig: 'apps/my-app/tsconfig.app.json', // <======== this option
        }
      }
    }
  }
}
```

Maybe cc @jordanpowell88?

**Comment by marktnoonan** [comment]
@vanyasav I'm going to close this issue due to inactivity for now, please comment again with more information if you still have this problem after the suggestion above ☝
