### ISSUE TITLE
Command expected to run against origin {oktaOrigin} but the application is at origin {previousOrigin}

### ISSUE THREAD

**Issue by jssoriao** [cypress-io/cypress#25911]
### Current behavior

I get this error when using `cy.origin` with the nextjs with-cypress example as well as the cypress-test-tiny

<img width="907" alt="Screenshot 2023-02-22 at 10 07 59 AM" src="https://user-images.githubusercontent.com/26679479/220506503-ed9fc2a4-1f50-49c8-89d6-730a28e447b1.png">

### Desired behavior

The test should run without error even with the use of `cy.origin`, and should find the `input[name="identifier"]` selector from the okta website

### Test code to reproduce

Here is my fork of the `cypress-test-tiny` repo
https://github.com/jssoriao/cypress-test-tiny

Here are my additions
```js
cy.origin(
    "<yourOktaOriginHere>",
    { args: { username: "myusername" } },
    ({ username }) => {
        cy.get('input[name="identifier"]').type(username);
    }
);
```

### Cypress Version

12.6.0

### Node version

18.12.1

### Operating System

macOS Ventura 13.1 (Macbook Air M1)

### Debug Logs

```shell
> cypress-test-tiny@1.0.0 cy:debug
> DEBUG=cypress:* cypress run


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.6.0                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v18.12.1 (/Users/jssoriao/.nvm/versions/node/v18.12.1/bin/node)                │
  │ Specs:          1 found (spec.cy.js)                                                           │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  spec.cy.js                                                                      (1 of 1)


  page
    1) works


  0 passing (7s)
  1 failing

  1) page
       works:
     CypressError: Timed out retrying after 4000ms: The command was expected to run against origin `https://dev-{oktaId}.okta.com` but the application is at origin `https://example.cypress.io`.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Using `cy.origin()` to wrap the commands run on `https://example.cypress.io` will likely fix this issue.

`cy.origin('https://example.cypress.io', () => {`
`  <commands targeting https://example.cypress.io go here>`
`})`

https://on.cypress.io/cy-visit-succeeded-but-commands-fail
      at Context.eval (webpack:///./cypress/e2e/spec.cy.js:5:7)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/spec.cy.js:5:7)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     spec.cy.js                                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/jssoriao/dev/play/cypress-test-tiny/cypress/screenshots/spec.cy.js/page -    (2560x1440)
     - works (failed).png                                                                           


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: 1 second                                                   

  -  Video output: /Users/jssoriao/dev/play/cypress-test-tiny/cypress/videos/spec.cy.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  spec.cy.js                               00:06        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:06        1        -        1        -        -
```

**Comment by nagash77** [comment]
Hi @jssoriao , I'm sorry to hear you are having issues using cy.origin.  Have you read through our [guide on using Okta](https://docs.cypress.io/guides/end-to-end-testing/okta-authentication)?

**Comment by jssoriao** [comment]
Hi @nagash77 . The Okta guide was the first thing I tried but in my case, the `cy.origin` does not work so I simplified my first sample code. I updated my code here https://github.com/jssoriao/cypress-test-tiny now to use this. Also, I use now the `baseUrl` of my actual nextjs webapp in my localhost (http://localhost:3000)

```js
// cypress/support/oktaLogin.js

Cypress.Commands.add("loginByOkta", (username, password) => {
  cy.session(
    `okta-${username}`,
    () => {
      Cypress.log({
        displayName: "OKTA LOGIN",
        message: [`🔐 Authenticating | ${username}`],
      });

      cy.visit("/");

      cy.origin(
        Cypress.env("okta_domain"),
        { args: { username, password } },
        ({ username, password }) => {
          cy.get('input[name="identifier"]').type(username);
          cy.get('input[name="credentials.passcode"]').type(password, {
            log: false,
          });
          cy.get('[type="submit"]').click();
        }
      );

      cy.get('[data-test="sidenav-username"]').should("contain", username);
    },
    {
      validate() {
        cy.visit("/");
        cy.get('[data-test="sidenav-username"]').should("contain", username);
      },
    }
  );
});

export {};
```

```js
// cypress/support/commands.js

import "./oktaLogin";
```

When I comment out the `loginByOkta` command, the test works.

<img width="434" alt="Screenshot 2023-02-24 at 11 36 35 AM" src="https://user-images.githubusercontent.com/26679479/221085898-ca992473-a3ce-44fe-849d-b8c722e6e4f7.png">

[debug-logs-passing.txt](https://github.com/cypress-io/cypress/files/10820450/debug-logs-passing.txt)

But if enable that command, it fails.

[debug-logs-failing.txt](https://github.com/cypress-io/cypress/files/10820468/debug-logs-failing.txt)

**Comment by flotwig** [comment]
@jssoriao could you please try updating to Cypress 12.7.0? We included some bugfixes related to session, origin, and cookies that may resolve your issues: https://docs.cypress.io/guides/references/changelog#12-7-0

**Comment by jssoriao** [comment]
Hi. I already made it work by using `cy.visit("/")` inside the `cy.origin`

```
Cypress.Commands.add("loginByOkta", (username: string, password: string) => {
    ...
    cy.visit("/")
    cy.origin(
        Cypress.env("okta_domain"),
        { args: { username, password } },
            ({ username, password }) => {
        
            // Put this line so that the cy commands below will run inside the okta domain instead of in the previous origin
            cy.visit("/");

            cy.get('input[name="identifier"]').type(username);
            cy.get('input[name="credentials.passcode"]').type(password, {
                log: false,
            });
            cy.get('[type="submit"]').click();
        }
    );

    // Put this line so that the cy commands below will run in the original domain instead of inside okta
    cy.visit("/")
```

I'm not sure if I missed some configuration since the docs show I don't need to do that to be able to use `cy.origin`.
