### ISSUE TITLE
vite-dev-server specifies invalid esbuild option `incremental` for Vite 4.2.0

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress#26138]
Vite updated esbuild to [v0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0) which removes the `incremental` build option that we set in `vite-dev-server` https://github.com/cypress-io/cypress/blob/a63a474baa81db55c065902ade716f45bc489ffb/npm/vite-dev-server/src/resolveConfig.ts#L87

The result is that when you try to run a Cypress test with a project that is using Vite 4.2.0, you get this error message in the logs:
```
[vite] error while updating dependencies:
Error: Context failed with 1 error:
/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in context() call: "incremental"
    at failureErrorWithLog (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:953:16
    at responseCallbacks.<computed> (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
Along with this error in the command log

![Screenshot 2023-03-16 at 4.07.26 PM.png](https://images.zenhubusercontent.com/629e1718380ab63be36ff3cc/1fe26a22-65b4-4bd4-9111-84de9fbcac80)

Fix component testing with Vite by removing the now invalid `incremental` esbuild option and figure out how to maintain the same build behavior.

**Comment by reintroducing** [comment]
I'm still seeing this as referenced by my [comment in the PR](https://github.com/cypress-io/cypress/pull/26139#issuecomment-1478406879), even after upgrading all my dependencies to the latest across the board.

**Comment by astone123** [comment]
@reintroducing I'll respond here too just to document, this fix has not yet been released. It will go out with the next Cypress release

**Comment by adamdehaven** [comment]
Any idea when this will be released (in which Cypress version)?

**Comment by adamdehaven** [comment]
This error is also thrown with Vite version `4.1.4` and is currently blocking our upgrade flow 😬

**Comment by reintroducing** [comment]
@adamdehaven according to the release cycle of Cypress (as referenced in the PR), it looks like it'll go out in roughly one week.

**Comment by lmiller1990** [comment]
Yes, roughly one week. Maybe Vite 4.1.0 is better until then.

Always impressed people are able to update to quickly, something in Vite 4.2 breaks our own internal workflow, no idea what... dependency hell. Have a personal project using native ESM, no bundler, no anything - DX is meh but having only a handful of deps that hardly change is 💯
