### ISSUE TITLE
Install on Jenkins fails: Error: Cannot find module 'listr2'

### ISSUE THREAD

**Issue by Tucaen** [cypress-io/cypress#26417]
### Current behavior

Running `npm install` on my local machine works fine.
However during build on Jenkins it fails with the message `Error: Cannot find module 'listr2'`

Any ideas how to fix it or what causes it?

### Debug logs

```Text
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (install)
[Pipeline] bat

D:\JenkinsBuilds\project\master\workspace>npm install 
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path D:\JenkinsBuilds\project\master\workspace\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'listr2'
npm ERR! Require stack:
npm ERR! - D:\JenkinsBuilds\project\master\workspace\node_modules\cypress\lib\tasks\install.js
npm ERR! - D:\JenkinsBuilds\project\master\workspace\node_modules\cypress\index.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (D:\JenkinsBuilds\project\master\workspace\node_modules\cypress\lib\tasks\install.js:10:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (D:\JenkinsBuilds\project\master\workspace\node_modules\cypress\index.js:12:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'D:\\JenkinsBuilds\\project\\master\\workspace\\node_modules\\cypress\\lib\\tasks\\install.js',
npm ERR!     'D:\\JenkinsBuilds\\project\\master\\workspace\\node_modules\\cypress\\index.js'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.15.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\srv_Jenkins\AppData\Local\npm-cache\_logs\2023-04-03T15_05_29_650Z-debug.log
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (inject version)
Stage "inject version" skipped due to earlier failure(s)
```

### Cypress Version

12.9.0

### Node version

18.15.0

### Package Manager

npm

### Package Manager Version

9.5.0

### Operating system

Windows

### Operating System Version

10

**Comment by Tucaen** [comment]
My current workaround is to directly include `listr2` as a `devDependency` in my package.json

**Comment by Tucaen** [comment]
Had to remove node_modules folder on Jenkins due to some other issue and now it's complaining about missing `lodash`.
```
Error: Cannot find module 'lodash'
```
Will be quite annoying, if I have to include all `devDependencies` step by step...

**Comment by Tucaen** [comment]
... seems like someone f*ck up the package-lock.json with some search&replace command.
After fixing it no more problems occur and `listr2` doesn't have to be inlcuded as direct `devDependency`.

Sorry for bothering 👼
