### ISSUE TITLE
Updating the Cypress GUI in Linux fails

### ISSUE THREAD

**Issue by cdownard** [cypress-io/cypress#267]
I'm on Ubuntu 16.04

This is the info @brian-mann gave me:

``` javascript
{
 '0': 
   { Error: Command failed: tar -zxvf "/tmp/cypress.zip" >/dev/null
   gzip: stdin has more than one entry--rest ignored
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now

     at ChildProcess.exithandler (child_process.js:218:12)
     at emitTwo (events.js:106:13)
     at ChildProcess.emit (events.js:191:7)
     at maybeClose (internal/child_process.js:877:16)
     at Socket.<anonymous> (internal/child_process.js:334:11)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at Pipe._handle.close [as _onclose] (net.js:493:12)

     killed: false,
     code: 2,
     signal: null,
     cmd: 'tar -zxvf "/tmp/cypress.zip" >/dev/null' },
  '1': '',
  '2': 'gzip: stdin has more than one entry--rest ignored\ntar: Child returned status 2\ntar: Error is not recoverable: exiting now\n' }
{ Error: Command failed: tar -zxvf "/tmp/cypress.zip" >/dev/null
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now

  at ChildProcess.exithandler (child_process.js:218:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar -zxvf "/tmp/cypress.zip" >/dev/null' 
}
```

**Comment by brian-mann** [comment]
To currently work-around this simply type this in your terminal:

```bash
cypress install
```

Or just redownload cypress from scratch.
