### ISSUE TITLE
Can't use Trpc with cypress due to .mjs webpack compilation error

### ISSUE THREAD

**Issue by vjau** [cypress-io/cypress#26752]
### Current behavior

I am trying to use trpc (a popular remote procedure call library) in my tests.
I need to do a trpc call to put the database in a state suitable for my e2e tests.
But when importing the function needed to create the trpc client, i receive an error related to webpack
```
Error: Webpack Compilation Error
./node_modules/@trpc/client/dist/index.mjs 33:24
Module parse failed: Unexpected token (33:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         const { promise , abort  } = observableToPromise(req$);
|         const abortablePromise = new Promise((resolve, reject)=>{
>             opts.signal?.addEventListener('abort', abort);
```

The error seems to be related to the optionnal chaining operator. I have tried various settings, with no success.

### Test code to reproduce

Repo demonstrating the problem https://github.com/vjau/cypress-test-tiny/tree/trpc-bug-webpack
(i created a branch). 

### Cypress Version

12.12.0

### Node version

v18.16.0

### Operating System

Ubuntu 20.04

### Debug Logs

```shell
Oops...we found an error preparing this test file:

  > cypress/e2e/spec.cy.js

The error was:

Error: Webpack Compilation Error
./node_modules/@trpc/client/dist/index.mjs 33:24
Module parse failed: Unexpected token (33:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         const { promise , abort  } = observableToPromise(req$);
|         const abortablePromise = new Promise((resolve, reject)=>{
>             opts.signal?.addEventListener('abort', abort);
|             promise.then((envelope)=>{
|                 resolve(envelope.result.data);
 @ ./cypress/e2e/spec.cy.js 3:14-37
    at handle (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/vincent/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23)
```

**Comment by jacobsmith** [comment]
I've had success putting any `trpc` calls into the `cypress.config.ts` file and then just executing those as `cy.task('thing-that-calls-trpc')` - that avoids putting it into the cypress tests themselves and sidesteps the webpack issue.

**Comment by mike-plummer** [comment]
Hi @vjau , sorry you're having trouble. The issue you're encountering is the result of the Webpack config that Cypress uses  not knowing how to handle `.mjs` files - we haven't yet baked in support for the more cutting-edge module formats since the vast majority of browser-side code doesn't use them. By using the library directly from your spec you're attempting to run it in the browser vs building a `task` definition (as suggested by @jacobsmith) which would run within Node (which has mjs support). 

It's probably easier (and more stable/reliable) to build this sort of logic as a `task`, but if you want to keep this logic in the browser you can fairly easily add `.mjs` support using the `@cypress/webpack-preprocessor` addon (or rather, an extension of it):

1. Add two new dev dependencies which allow you to modify how Cypress preprocesses your tests
`npm i -D @cypress/webpack-preprocessor @cypress/webpack-batteries-included-preprocessor`

2. Use the "batteries included" version (which bundles in our default configs) and add a new module rule to teach Webpack about `.mjs` files:

`cypress.config.js`
```js
setupNodeEvents(on, config) {
      const webpackPreprocessor = require('@cypress/webpack-batteries-included-preprocessor')

      on('file:preprocessor', webpackPreprocessor({
        module: {
          rules: [
            {
              test: /\.(mjs)$/,
              exclude: /node_modules/,
              use: {
                loader: require.resolve('babel-loader'),
              },
            },
          ]
        }
      }))

      return config
    },
```

**Comment by Fab1anB** [comment]
I had a similar issue, despite I am not using tcrp.

In addition to the solution of @mike-plummer I had to add `typescript: require.resolve('typescript')` to the webpackPreprocessor function.

My complete setupNodeEvents function looks like this:


```typescript

		setupNodeEvents(on, config) {
			// implement node event listeners here
			const webpackPreprocessor = require('@cypress/webpack-batteries-included-preprocessor')

			on('file:preprocessor', webpackPreprocessor({
				module: {
					rules: [
						{
							test: /\.(mjs)$/,
							exclude: /node_modules/,
							use: {
								loader: require.resolve('babel-loader'),
							},
						},
					]
				},
				typescript: require.resolve('typescript')
			}))

			return config
		},
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
