### ISSUE TITLE
Adding the Cypress.required command to cy.origin causes an error

### ISSUE THREAD

**Issue by PavelRybalko** [cypress-io/cypress#26790]
### Current behavior

![image](https://github.com/cypress-io/cypress/assets/60709039/46643cef-6777-408d-a2bf-a7a67c4713b5)
[Stack trace](https://app.development.inkit.com/__/#)

```
Error: ENOENT: no such file or directory, open '/output.js'
    at createError (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:128:17)
    at Volume.openFile (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:854:15)
    at Volume.openBase (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:858:25)
    at Volume.openSync (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:869:21)
    at Volume.readFileBase (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:955:23)
    at Volume.readFileSync (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:970:21)
    at handle (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\cross_origin.js:56:25)
    at finalCallback (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Git\inkit-next\inkit\node_modules\tapable\lib\HookCodeFactory.js:33:10), :6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:298:10
    at C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Git\inkit-next\inkit\node_modules\tapable\lib\HookCodeFactory.js:33:10), :6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:482:27
    at Object.eachLimit (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\neo-async\async.js:3461:14)
    at emitFiles (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\webpack\lib\Compiler.js:358:13)
    at Immediate. (C:\Users\Professional\AppData\Local\Cypress\Cache\12.12.0\Cypress\resources\app\node_modules\memfs\lib\volume.js:701:13)
    at processImmediate (node:internal/timers:476:21)
```
### Desired behavior

Adding the Cypress.required command to cy.origin imports the required function

### Test code to reproduce

bug.cy.js:
```js
describe("testing", () => {
  it("test", () => {
    cy.origin("https://github.com", () => {
      const { foo } = Cypress.require("./foo.js");
    });
  });
});
```
foo.js:
```js
export const foo = () => "1234";
```
### Cypress Version

12.12.0

### Node version

v18.16.0

### Operating System

Windows 10 LTSC, 21H2, 19044.2364

**Comment by chrisbreiding** [comment]
I was unable to reproduce this with the provided code. This error seems to originate in the `cypress.config.ts` file. Could you post the contents of that file?

**Comment by PavelRybalko** [comment]
```js
import * as webpack from "@cypress/webpack-preprocessor";
import { defineConfig } from "cypress";
import { plugin as cypressFirebasePlugin } from "cypress-firebase";
import admin from "firebase-admin";
import { resolve } from "path";

import baseConfig from "./cypress.base.config";
import developmentConfig from "./cypress.development.config";
import localConfig from "./cypress.local.config";
import productionConfig from "./cypress.production.config";
import stagingConfig from "./cypress.staging.config";

const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");
const localStoragePlugin = require("cypress-localstorage-commands/plugin");
const envVariablesConfigMap = {
  development: developmentConfig,
  staging: stagingConfig,
  production: productionConfig,
  local: localConfig,
};

const envConfigVariables = {
  ...baseConfig,
  ...envVariablesConfigMap[process.env.CYPRESS_ENV],
};

export default defineConfig({
  e2e: {
    reporter: "cypress-mochawesome-reporter",
    reporterOptions: {
      charts: true,
      embeddedScreenshots: true,
      inlineAssets: true,
      saveAllAttempts: false,
      reportDir: "cypress/report",
      reportPageTitle: "Inkit e2e tests",
    },
    experimentalModifyObstructiveThirdPartyCode: true,
    experimentalRunAllSpecs: true,
    video: false,
    keystrokeDelay: 20,
    baseUrl: envConfigVariables.APP_DOMAIN || "",
    viewportWidth: 1280,
    viewportHeight: 720,
    scrollBehavior: "center",
    numTestsKeptInMemory: 5,
    projectId: "8579t6",
    requestTimeout: 10000,
    execTimeout: 10000,
    taskTimeout: 10000,
    pageLoadTimeout: 15000,
    defaultCommandTimeout: 15000,
    responseTimeout: 15000,
    watchForFileChanges: false,
    excludeSpecPattern: [
      "**/e2e/contacts/*",
      "**/e2e/verify/**",
      "**/e2e/templates/pptx/**",
      "**/e2e/settings/billing/payment.cy.js",
    ],
    trashAssetsBeforeRuns: true,
    env: envConfigVariables,
    setupNodeEvents(on, config) {
      const options = {
        webpackOptions: {
          module: {
            rules: [
              {
                test: /\.(ts|js)?$/,
                exclude: /node_modules/,
                use: {
                  loader: "babel-loader",
                  options: {
                    presets: ["@babel/preset-env", "@babel/preset-typescript"],
                    plugins: [
                      "@babel/plugin-proposal-nullish-coalescing-operator",
                      "@babel/plugin-proposal-optional-chaining",
                    ],
                  },
                },
              },
            ],
          },
          resolve: {
            extensions: [".js", ".ts"],
            alias: {
              "@src": resolve(__dirname, "../../src"),
              "@constants": resolve(__dirname, "../constants"),
              "@fixtures": resolve(__dirname, "../fixtures"),
              "@functions": resolve(__dirname, "../functions"),
              "@support": resolve(__dirname, "../support"),
            },
          },
          plugins: [new NodePolyfillPlugin()],
        },
      };
      on("file:preprocessor", webpack(options));
      cypressFirebasePlugin(on, config, admin);
      localStoragePlugin(on, config);
      require("cypress-mochawesome-reporter/plugin")(on);
      return config;
    },
  },
});
```

**Comment by chrisbreiding** [comment]
Thanks for providing that. Are you able to provide a minimal reproduction that we can run to debug this issue? I recommend using [cypress-test-tiny](https://github.com/cypress-io/cypress-test-tiny) as a starting point.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
