### ISSUE TITLE
cypress run on aarch64 env failed

### ISSUE THREAD

**Issue by wwgnid** [cypress-io/cypress#26832]
### Current behavior

Hi, everyone

I'm try to run cypress e2e test on arm64(aarch64) environment.

1. I got cypress docker image for arm64 from https://hub.docker.com/r/cypress/included/ , but found the image does't include a browser by default. so I installed a firefox-102.11 browser in the docker container based on the Cypress/included image.

2. try to use  'docker run' command to run e2e test , but got error as below. 

```
root@3bc8976174d2:/# cypress run

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.12.0/Cypress/Cypress --no-sandbox --smoke-test --ping=27

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.12.0
root@3bc8976174d2:/# /root/.cache/Cypress/12.12.0/Cypress/Cypress
Trace/breakpoint trap (core dumped)
```
3. I tried to install Cypress on the arm64 environment. I downloaded the Cypress source code to the Linux Server and ran 'yarn install' command, encountered following error.

```
cypress:snapgen:info External sourcemaps written to "/root/cypress/tooling/v8-snapshot/cache/linux/base.snapshot.js.map" +0ms
  cypress:snapgen:info External sourcemaps written to "/root/cypress/tooling/v8-snapshot/cache/linux/base.snapshot.js.map" +7s
  cypress:snapgen:info Verifying snapshot script +15m
  cypress:snapgen:info Writing snapshot script to /root/cypress/tooling/v8-snapshot/cache/linux/snapshot.js +3s
Error: Failed `mksnapshot` command
    at SnapshotGenerator.makeSnapshot (/root/cypress/tooling/v8-snapshot/dist/generator/snapshot-generator.js:268:19)
    at async installSnapshot (/root/cypress/tooling/v8-snapshot/dist/setup/install-snapshot.js:46:51)
    at async setupV8Snapshots (/root/cypress/tooling/v8-snapshot/dist/setup/index.js:20:38)
Snapshot generation has failed. If you continue to see this error, you can generate snapshots from scratch by running:

  `V8_SNAPSHOT_FROM_SCRATCH=1 yarn build-v8-snapshot-{prod or dev}`

Note that this may take a while.

Alternatively, you can run the Update V8 Snapshot Cache github action against your branch to generate the snapshots for you on all platforms: https://github.com/cypress-io/cypress/actions/workflows/update_v8_snapshot_cache.yml
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
5. try to run `V8_SNAPSHOT_FROM_SCRATCH=1 yarn build-v8-snapshot-dev` to generate snapshots, got the same error.
  

### Cypress Version

12.12

### Node version

v16.20.0

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Linux

### Operating System Version

aarch64

**Comment by AtofStryker** [comment]
Hi @wwgnid. Thank you for opening an issue. Would you be able to provide us with a Dockerfile or a docker compose file that you are using to run this? Currently we [don't ship with browsers](https://github.com/cypress-io/cypress-docker-images/issues/695) with arm64 based docker images. Does Cypress run without installing firefox in the image by default?

**Comment by wwgnid** [comment]
@AtofStryker Thank you so much for your response.

I've ran test on Cypress include image at first, got below logs.

```
[root@enode1 easy_dqc-uitest]# docker run -i -v $PWD:/e2e -w /e2e --entrypoint=cypress cypress/included:latest info
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
node: error while loading shared libraries: libdl.so.2: ELF load command alignment not page-aligned
```
Than did test in Cypress container:

```
[easyops@enode1 ~]$ docker ps | grep cypress
be062b0e15b2   cypress-build:v1                                                                                    "sh"                     16 hours ago   Up 16 hours                                                                                                 hardcore_newton
f49b2f676cb5   cypress-build                                                                                       "docker-entrypoint.s…"   47 hours ago   Up 43 hours                                                                                                 dazzling_brahmagupta
3bc8976174d2   cypress/included:latest                                                                             "sh"                     47 hours ago   Up 47 hours                                                                                                 flamboyant_carson
630ca998ed2c   cypress/browsers:node16.16.0-chrome107-ff107-edge                                                   "sh"                     5 days ago     Up 5 days                                                                                                   blissful_ishizaka
9a0f390c97c5   cypress/included:cypress-12.6.0-node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1   "bash"                   6 days ago     Up 6 days                                                                                                   ecstatic_kepler

[easyops@enode1 ~]$ docker exec -it 3bc bash
root@3bc8976174d2:/# cypress
Usage: cypress <command> [options]

Options:
  -v, --version      prints Cypress version
Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.12.0

root@3bc8976174d2:/# cypress -v
Cypress package version: 12.12.0
Cypress binary version: 12.12.0
Electron version: 21.0.0
Bundled Node version: 16.16.0

root@3bc8976174d2:/# cypress verify

Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.
----------
Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.12.0/Cypress/Cypress --no-sandbox --smoke-test --ping=203
----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.12.0
root@3bc8976174d2:/#

root@3bc8976174d2:/# cypress info
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.12.0

root@3bc8976174d2:/#
```

**Comment by wwgnid** [comment]
Hi @AtofStryker Thank you so much for your response.

I’ve ran test on Cypress include image at first, got blow error log:

```
[root@enode1 easy_dqc-uitest]# docker run -i -v $PWD:/e2e -w /e2e --entrypoint=cypress cypress/included:latest info
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0
[root@enode1 easy_dqc-uitest]#
```
Then did test in docker container, and didn’t receive any further useful information.
```

[root@enode1 easy_dqc-uitest]# docker run cypress/included:latest
[STARTED] Task without title.
[FAILED] Cypress failed to start.
[FAILED]
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED]
[FAILED] Please refer to the error below for more details.
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=899
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-arm64 (Debian - 11.6)
[FAILED] Cypress Version: 12.13.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=899

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0


[root@enode1 easy_dqc-uitest]# docker run -itd --entrypoint=bash cypress/included:latest
cbd157e993d451e81d14312d610e72da6a826ed525f0a8d557cba047da4808e8

[root@enode1 easy_dqc-uitest]# docker exec -it cbd157 bash
root@cbd157e993d4:/# cypress -v
Cypress package version: 12.13.0
Cypress binary version: 12.13.0
Electron version: 21.0.0
Bundled Node version: 16.16.0
root@cbd157e993d4:/# cypress verify

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=948

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0
root@cbd157e993d4:/# cypress info
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0
root@cbd157e993d4:/#

```
debug log:

```
cypress:cli using Cypress executable /root/.cache/Cypress/12.13.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976
    at makeError (/usr/local/lib/node_modules/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/cypress/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976',
  command: '/root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976',
  exitCode: undefined,
  signal: 'SIGTRAP',
  signalDescription: 'Debugger breakpoint',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +170ms
  cypress:cli error message: Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976 +2ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'arm64' } +216ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=976

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.13.0
```

**Comment by wwgnid** [comment]
Hi @AtofStryker Any more suggestion for debugging?

I ran cypress on another linux server and encountered the same failure.
```
cd cypress-uitest
npm init -y 
npm install cypress --save-dev
npx cypress open

//error log
[easyops@enode3 cypress-uitest]$ npx cypress open
It looks like this is your first time using Cypress: 12.13.0

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------
Command was killed with SIGTRAP (Debugger breakpoint): /home/easyops/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=366
----------

Platform: linux-arm64 (Ubuntu - )
Cypress Version: 12.13.0

[easyops@enode3 cypress-uitest]$ uname -m
aarch64
```
I use 'yum' command on this linux server, so it's  likely a CentOS aarch64/v8 architecture.

**Comment by mschile** [comment]
Hi @wwgnid, I was able to run the `arm64` `cypress/included:12.13.0` docker image from my M1 Mac. Could you try running with debug logs turned on to see if that uncovers anything:

`DEBUG=cypress* cypress run`

**Comment by wwgnid** [comment]
Hi @mschile 
thank u for response，blow is the debug log run cypress on the linux server(arm64) .
```
[xxxxtest@enode3 easy_taskops-uitest]$ DEBUG=cypress:* ./node_modules/cypress/bin/cypress run
  cypress:cli:cli cli starts with arguments ["/home/xxxxtest/.nvm/versions/node/v18.16.0/bin/node","/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/cypress/bin/cypress","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 23, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/cypress/bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(kCapture)]: false } ] +1ms
  cypress:cli:cli variable-length opts parsed { args: [ '/home/xxxxtest/.nvm/versions/node/v18.16.0/bin/node', '/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/cypress/bin/cypress', 'run' ], opts: Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 23, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/cypress/bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(kCapture)]: false } } +252ms
  cypress:cli parsed cli options {} +259ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress +3ms
  cypress:cli Binary is executable? : true +3ms
  cypress:cli binaryDir is  /home/xxxxtest/.cache/Cypress/12.13.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 12.13.0 installed in: /home/xxxxtest/.cache/Cypress/12.13.0/Cypress +5ms
  cypress:cli could not read binary_state.json file at "/home/xxxxtest/.cache/Cypress/12.13.0/binary_state.json" +7ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli running binary verification check 12.13.0 +1ms
It looks like this is your first time using Cypress: 12.13.0
  cypress:cli clearing out the verified version +8ms
  cypress:cli undefined DISPLAY environment variable +0ms
  cypress:cli Cypress will spawn its own Xvfb +0ms
  cypress:cli needs Xvfb? true +2ms
  cypress:cli Starting Xvfb +0ms
  cypress:xvfb _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
  cypress:xvfb  +0ms
  cypress:cli disabling Electron sandbox +66ms
  cypress:cli running smoke test +1ms
  cypress:cli using Cypress executable /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:xvfb The XKEYBOARD keymap compiler (xkbcomp) reports:
  cypress:xvfb > Warning:          Unsupported high keycode 372 for name <I372> ignored
  cypress:xvfb >                   X11 cannot support keycodes above 255.
  cypress:xvfb >                   This warning only shows for the first high keycode.
  cypress:xvfb  +354ms
  cypress:xvfb > Internal error:   Could not resolve keysym XF86MonBrightnessCycle
  cypress:xvfb > Internal error:   Could not resolve keysym XF86RotationLockToggle
  cypress:xvfb > Internal error:   Could not resolve keysym XF86FullScreen
  cypress:xvfb  +93ms
  cypress:xvfb Errors from xkbcomp are not fatal to the X server
  cypress:xvfb  +1ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGTRAP (Debugger breakpoint): /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722
    at makeError (/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/xxxxtest/qatest/dxxxx_acceptance-7.0.0/code/easy_taskops-uitest/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGTRAP (Debugger breakpoint): /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722',
  command: '/home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722',
  exitCode: undefined,
  signal: 'SIGTRAP',
  signalDescription: 'Debugger breakpoint',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +552ms
  cypress:cli error message: Command was killed with SIGTRAP (Debugger breakpoint): /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722 +1ms
  cypress:cli detecting arch { osPlatform: 'linux', osArch: 'arm64' } +648ms
Cypress failed to start.
This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
Please refer to the error below for more details.
----------
Command was killed with SIGTRAP (Debugger breakpoint): /home/xxxxtest/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=722
----------
Platform: linux-arm64 (Ubuntu - )
Cypress Version: 12.13.0
```

**Comment by cacieprins** [comment]
Hi @wwgnid , thank you so much for the detailed log output.

`xvfb` seems to be failing to start with the error `_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.`. Can you verify the euid that is launching the cypress command on the docker image? Without xvfb, Cypress will not work correctly.

Thank you!

**Comment by wwgnid** [comment]
Hi @cacieprins  Thank u for your replay. 
I ran the cypress command on the docker image using root account.
It failed when doing smoke test, can we locate which library or dependency is missing?

debug log:
```
2023-07-20T12:11:25.179Z cypress:cli parsed cli options { configFile: 'tests/e2e/config/cypress.easyops.json' }
2023-07-20T12:11:25.179Z cypress:cli verifying Cypress app
2023-07-20T12:11:25.180Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2023-07-20T12:11:25.180Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2023-07-20T12:11:25.180Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /root/.cache/Cypress
2023-07-20T12:11:25.181Z cypress:cli checking environment variables
2023-07-20T12:11:25.186Z cypress:cli checking if executable exists /root/.cache/Cypress/12.6.0/Cypress/Cypress
2023-07-20T12:11:25.188Z cypress:cli Binary is executable? : true
2023-07-20T12:11:25.188Z cypress:cli binaryDir is  /root/.cache/Cypress/12.6.0/Cypress
2023-07-20T12:11:25.189Z cypress:cli Reading binary package.json from: /root/.cache/Cypress/12.6.0/Cypress/resources/app/package.json
2023-07-20T12:11:25.192Z cypress:cli Found binary version 12.6.0 installed in: /root/.cache/Cypress/12.6.0/Cypress
2023-07-20T12:11:25.194Z cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/12.6.0/binary_state.json"
2023-07-20T12:11:25.194Z cypress:cli {}
2023-07-20T12:11:25.194Z cypress:cli is Verified ? undefined
2023-07-20T12:11:25.194Z cypress:cli running binary verification check 12.6.0
[STARTED] Task without title.
2023-07-20T12:11:25.200Z cypress:cli clearing out the verified version
2023-07-20T12:11:25.201Z cypress:cli undefined DISPLAY environment variable
2023-07-20T12:11:25.201Z cypress:cli Cypress will spawn its own Xvfb
2023-07-20T12:11:25.201Z cypress:cli needs Xvfb? true
2023-07-20T12:11:25.202Z cypress:cli Starting Xvfb
2023-07-20T12:11:25.223Z cypress:cli disabling Electron sandbox
2023-07-20T12:11:25.223Z cypress:cli running smoke test
2023-07-20T12:11:25.223Z cypress:cli using Cypress executable /root/.cache/Cypress/12.6.0/Cypress/Cypress
2023-07-20T12:11:25.223Z cypress:cli smoke test command: /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499
2023-07-20T12:11:25.223Z cypress:cli smoke test timeout 30000 ms
2023-07-20T12:11:25.390Z cypress:cli Smoke test failed: Error: Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499
    at makeError (/usr/local/lib/node_modules/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/cypress/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499',
  command: '/root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499',
  exitCode: undefined,
  signal: 'SIGTRAP',
  signalDescription: 'Debugger breakpoint',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
2023-07-20T12:11:25.391Z cypress:cli error message: Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499
2023-07-20T12:11:25.392Z cypress:cli detecting arch { osPlatform: 'linux', osArch: 'arm64' }
2023-07-20T12:11:25.399Z cypress:cli Stopping Xvfb
[FAILED] Cypress failed to start.
[FAILED]
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED]
[FAILED] Please refer to the error below for more details.
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-arm64 (Debian - 11.6)
[FAILED] Cypress Version: 12.6.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTRAP (Debugger breakpoint): /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=499

----------

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.6.0
```

**Comment by jennifer-shehane** [comment]
@wwgnid The dependencies required are listed in our docs. That's all that's required to run cypress. https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies

**Comment by jennifer-shehane** [comment]
Closing as stale. If you're encountering a similar issue, please open a new issue.
