### ISSUE TITLE
"Cannot redefine property" when stubbing module exports

### ISSUE THREAD

**Issue by Lippiece** [cypress-io/cypress#26866]
### Current behavior

I haven't found any examples of stubbing imports in documentation.

The [functionality](https://vitest.dev/guide/mocking.html#modules) I seek in a Vite (or Jest) example:

```ts
// beginning of the test file
vi.mock("path/to/file", () => ({
    default: "value"
}))

// tests
```
Is this possible with Cypress?

### Desired behavior

There probably shouldn't be an error and `testConstant` should become "VALUE".

### Test code to reproduce

index.ts:
```ts
export const testConstant = "initial"
```
test file:
```ts
import * as testExports from "./index.ts";
it("changes the module", () => {
  cy.stub(testExports, "testConstant")
    .value("VALUE")
  expect(testExports.testConstant).to.eq("VALUE")
})
```
Result: 
```js
TypeError: Cannot redefine property: testConstant
    at Function.defineProperty (<anonymous>)
    at Object.value (/__cypress/runner/cy…runner.js:129024:16)
    at proto.<computed> [as value] (/__cypress/runner/cy…runner.js:128601:12)
    at Function.<anonymous> (/__cypress/runner/cy…runner.js:128594:46)
    at runnable.fn (/__cypress/runner/cy…runner.js:160854:19)
    at callFn (/__cypress/runner/cy…runner.js:114387:21)
    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (/__cypress/runner/cy…_runner.js:114374:7)
    at <unknown> (/__cypress/runner/cy…runner.js:167842:30)
    at PassThroughHandlerContext.finallyHandler (/__cypress/runner/cy…_runner.js:15298:23)
    at PassThroughHandlerContext.tryCatcher (/__cypress/runner/cy…_runner.js:18744:23)
    at Promise._settlePromiseFromHandler (/__cypress/runner/cy…_runner.js:16679:31)
    at Promise._settlePromise (/__cypress/runner/cy…_runner.js:16736:18)
    at Promise._settlePromise0 (/__cypress/runner/cy…_runner.js:16781:10)
    at Promise._settlePromises (/__cypress/runner/cy…_runner.js:16861:18)
    at Promise._fulfill (/__cypress/runner/cy…_runner.js:16805:18)
    at Promise._settlePromise (/__cypress/runner/cy…_runner.js:16749:21)
    at Promise._settlePromise0 (/__cypress/runner/cy…_runner.js:16781:10)
    at Promise._settlePromises (/__cypress/runner/cy…_runner.js:16861:18)
    at Promise._fulfill (/__cypress/runner/cy…_runner.js:16805:18)
    at Promise._resolveCallback (/__cypress/runner/cy…_runner.js:16599:57)
    at Promise._settlePromiseFromHandler (/__cypress/runner/cy…_runner.js:16691:17)
```

### Cypress Version

10.3.2

### Node version

20.2

### Operating System

Fedora 38

**Comment by warrensplayer** [comment]
@Lippiece Can you provide a bit more detail about the test you would like to write?  Perhaps there is a different way to structure it to avoid needing to mock/stub a constant this way.

Also, we recently released a Vite plugin to mock out ESM imports here: https://github.com/cypress-io/cypress/tree/develop/npm/vite-plugin-cypress-esm

It is currently still in Alpha as we test it out for as many scenarios as possible. The original GitHub issue for this plugin is here: https://github.com/cypress-io/cypress-internal/issues/564

Take a look and let me know if this works for your use case or not.

**Comment by warrensplayer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
