### ISSUE TITLE
Unable to use 'closest/parent' when the previous chain is 'should/and' followed by 'not.have.attr'

### ISSUE THREAD

**Issue by lflucasferreira** [cypress-io/cypress#26911]
### Current behavior

I am trying to get the parent of a selector after doing some validations, but it is not possible when I add the `.and('not.have.attr', 'placeholder')` right before the `.closest('form')` command.

`cy.closest() failed because it requires a DOM element or document.`

### Desired behavior

I expect to see the parent or closest selector yielded.

### Test code to reproduce
```js
cy.get(selector)
.should('be.enabled')
.and('be.visible')
.and('have.attr', 'maxlength', '14')
.and('have.attr', 'mask', 'separator.3')
.and('have.attr', 'thousandseparator', ',')
.and('have.attr', 'min', '0')
.and('not.have.attr', 'placeholder')
.closest('form')
```

### Cypress Version

12.13.0

### Node version

v18.13.0

### Operating System

Windows 10 Enterprise

### Debug Logs

```shell
Error:    CypressError: Timed out retrying after 4000ms: `cy.closest()` failed because it requires a DOM element or document.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.and()`
    at isElement (http://localhost:8080/__cypress/runner/cypress_runner.js:161438:66)
    at validateType (http://localhost:8080/__cypress/runner/cypress_runner.js:161287:14)
    at Object.isType (http://localhost:8080/__cypress/runner/cypress_runner.js:161318:7)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:151104:24)
    at Object.subjectFn (http://localhost:8080/__cypress/runner/cypress_runner.js:159292:16)
    at $Cy.verifyUpcomingAssertions (http://localhost:8080/__cypress/runner/cypress_runner.js:140514:31)
    at onRetry (http://localhost:8080/__cypress/runner/cypress_runner.js:159283:15)
From previous event:
    at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:156168:65)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:155609:14)
From Your Spec Code:
    at Context.<anonymous> (webpack://angular/./projects/customer-profile-components/src/lib/controls/annual-income/annual-income.component.cy.ts:51:7)
    at _ZoneDelegate.invoke (http://localhost:8080/__cypress/src/polyfills.js:7634:158)
    at ProxyZoneSpec.onInvoke (webpack://angular/./node_modules/zone.js/fesm2015/zone-testing.js:287:38)
    at _ZoneDelegate.invoke (http://localhost:8080/__cypress/src/polyfills.js:7634:46)
    at Zone.run (http://localhost:8080/__cypress/src/polyfills.js:7420:35)
    at Context.<anonymous> (webpack://angular/./node_modules/zone.js/fesm2015/zone-testing.js:1046:32)
    at runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:160854:19)
    at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:114387:21)
```

**Comment by warrensplayer** [comment]
@lflucasferreira Can you please provide a reproducible example of the issue you're encountering? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
