### ISSUE TITLE
cy.task() doesn't work with new Cypress version 12.15.0

### ISSUE THREAD

**Issue by Pavel-Lahutsin** [cypress-io/cypress#27099]
### Current behavior

With the latest Cypress version 12.15.0 cy.task() is broken. It says "cy.task() must only be invoked from the spec file or support file."

![12 15 0](https://github.com/cypress-io/cypress/assets/137287607/5656f9c5-0eff-4687-8ee0-ba37e0e6eb5d)
![documentation](https://github.com/cypress-io/cypress/assets/137287607/b1bdc9d5-1fd4-45ad-aa89-0daf37424b53)

### Desired behavior

It should work as in previous Cypress version

### Test code to reproduce

`cypress.config.js`
```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message)

          return null
        },
      })
    },
  },
})
```

`spec.cy.js`
```js
describe("Test for bug ", () => {
    it(`should be working`, () => {
        cy.task('log', 'This will be output to the terminal')
    })
});
```

### Cypress Version

12.15.0

### Node version

16.15

### Operating System

win10

**Comment by Phonesis** [comment]
Getting this too, seems like major issue

**Comment by Phonesis** [comment]
Further to this, it breaks stuff like the cypress code coverage lib because that uses cy.task() in an afterHook

**Comment by elGatoMantocko** [comment]
It looks like this is also breaking [`cypress-localstorage-commands`](https://github.com/javierbrea/cypress-localstorage-commands) as well. We are seeing errors when invoking `cy.saveLocalStorage()` from that lib.

```
CypressError: `cy.task()` must only be invoked from the spec file or support file.
      at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:151183:80)
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:4200/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at LocalStorage._clearNodeSnapshot (webpack:///./node_modules/cypress-localstorage-commands/src/LocalStorage.js:92:0)
      at LocalStorage.clearLocalStorageSnapshot (webpack:///./node_modules/cypress-localstorage-commands/src/LocalStorage.js:104:0)
      at LocalStorage.saveLocalStorage (webpack:///./node_modules/cypress-localstorage-commands/src/LocalStorage.js:109:0)
```

Locking our cypress version to `12.14.0` allows our tests to run.

**Comment by mike-plummer** [comment]
Hi everyone. We're aware of this issue and are looking into it now. Until a fix is identified, tested, and released you can temporarily downgrade to Cypress v12.14.0 which does not exhibit this issue.

**Comment by JomyGeo** [comment]
@mike-plummer I am getting the same issue for the 12.4.0 version

Issue 1 :
PayloadTooLargeError: request entity too large
at p (:2319:1358)
at s.exports (:2319:799)
at s.exports (:2338:1577)
at :2358:2007
at a.handle_request (:2640:1038)
at d (:2655:1285)

Issue 2 : CypressError: cy.task() must only be invoked from the spec file or support file.

Issue 3 : CypressError: cy.writeFile() must only be invoked from the spec file or support file.

**Comment by arundavid1987** [comment]
Issue in 12.5.0 and 12.4.0 as well for cy.readFile()

![image](https://github.com/cypress-io/cypress/assets/6092834/82de89e4-2a1f-4d1a-b360-55b3a7ae209a)

Works: Older version of node.js also does not work
