### ISSUE TITLE
Port missing on axios call in Cypress

### ISSUE THREAD

**Issue by averybross** [cypress-io/cypress#27236]
### Current behavior

An Axios call I am making is missing the port

My app runs on 3000

but the `/abc/` endpoint I want to call is on 6123

I am using Vite

When I try to `intercept` it and add the port the request is still made without the port

### Desired behavior

`https://localhost/abc/v3/registry` should be `https://localhost:6123/abc/v3/registry`

### Test code to reproduce

cypress.config:
```
import { defineConfig } from "cypress";

export default defineConfig({
    e2e: {
        setupNodeEvents(on, config) {
            // implement node event listeners here
        },
    },

    component: {
        devServer: {
            framework: "react",
            bundler: "vite",
            viteConfig: require("./vite.config.ts"),
        },
    },
});
```

Test:
```
describe("template spec", () => {
    beforeEach(() => {});

    it("passes", () => {
        cy.intercept({ url: "http://localhost/abc/v3/registry" }, (req) => {
            // Modify the request object to add a port
            const modifiedUrl = `http://localhost:6123/abc/v3/registry`;

            // Override the original request with the modified URL
            req.reply((res) => {
                res.url = modifiedUrl;
                res.headers["location"] = modifiedUrl;
                res.headers["x-cypress-redirect"] = "true";
            });
        });

        cy.intercept("POST", "/otherCall", {
            statusCode: 200,
            body: {},
        });

        cy.visit("http://localhost:3000/my-apps-url/");
    });
});

```

### Cypress Version

12.16.0

### Node version

v18.16.1

### Operating System

MacOS 13.4.1 (22F82) Ventura

### Debug Logs

```shell
Error:      HttpClientError: ERR_NETWORK: Connection to "https://localhost/abc/v3/registry" failed. The service may not be running or the connection information is incorrect. AxiosError: Network Error.
    at HttpClient.checkError (index.ts:268:27)
    at HttpClient.makeRequest (index.ts:174:28)
    at RequestClientBuilder.ts:142:27
    at Object.client_.<computed> [as registry] (RequestClientBuilder.ts:108:20)
    at index.tsx:49:26
```

**Comment by averybross** [comment]
@nagash77 @lmiller1990 thank you for the attention!

**Comment by averybross** [comment]
Here's my `vite.config.ts`:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import path from "path";
import fs from "fs";

const WRONG_CODE = `import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";`;

export function reactVirtualized() {
    return {
        name: "my:react-virtualized",
        configResolved() {
            const file = require
                .resolve("react-virtualized")
                .replace(
                    path.join("dist", "commonjs", "index.js"),
                    path.join("dist", "es", "WindowScroller", "utils", "onScroll.js")
                );
            const code = fs.readFileSync(file, "utf-8");
            const modified = code.replace(WRONG_CODE, "");
            fs.writeFileSync(file, modified);
        },
    };
}

export default defineConfig(({ command }) => ({
    base: "/my-apps-url/",
    plugins: [
        NodeGlobalsPolyfillPlugin({
            process: true,
            buffer: true,
        }),
        react(),
        reactVirtualized(),
    ],
    optimizeDeps: {
        include: [
            // internal monorepo deps
        ],
    },
    build: {
        commonjsOptions: {
            include: [/node_modules/],
        },
        outDir: "dist",
    },
    server: {
        port: 3000,
        proxy: {
            "/abc": "http://localhost:6080/",
        },
    },
    define: {
        "process.env.TZ": new String(),
        "process.version": new String(),
    },
    resolve: {
        preserveSymlinks: command === "build",
        alias: {
            process: "process/browser",
            path: "path-browserify",
            os: "os-browserify/browser",
            stream: "stream-browserify",
            http: "stream-http",
            https: "agent-base",
        },
    },
}));

```

**Comment by lmiller1990** [comment]
Can you please create a minimal reproduction by forking: https://github.com/cypress-io/cypress-test-tiny/tree/master. This will make it faster and easier to help debug your issue. Thanks!

**Comment by averybross** [comment]
In Cypress Chrome or Cypress Electron:
<img width="413" alt="Screenshot 2023-07-18 at 11 14 11 AM" src="https://github.com/cypress-io/cypress/assets/4257160/5fc06433-2fb6-47d1-8678-0da7f80b4628">


In my regular Chrome instance:
<img width="359" alt="Screenshot 2023-07-18 at 11 14 43 AM" src="https://github.com/cypress-io/cypress/assets/4257160/313c3142-9dc8-4fe4-86d8-265656d3f8fd">

**Comment by averybross** [comment]
I am using axios for the calls

**Comment by averybross** [comment]
@lmiller1990 I forked the repo... 

```javascript
describe("template spec", () => {
    beforeEach(() => {});

    it("passes", () => {
        // cy.intercept({ url: "https://localhost/abc/v3/registry" }, (req) => {
        //     // Modify the request object to add a port
        //     const modifiedUrl = `https://localhost:6080/abc/v3/registry`;

        //     // Override the original request with the modified URL
        //     req.reply((res) => {
        //         res.url = modifiedUrl;
        //         res.headers["location"] = modifiedUrl;
        //         res.headers["x-cypress-redirect"] = "true";
        //     });
        // });

        // cy.intercept("POST", "/ccfPing", {
        //     statusCode: 200,
        //     body: {},
        // });

        cy.visit("http://localhost:3000/my-app/");
    });
});

```

Setting the spec to this was enough to reproduce the issue...

but you would need my entire backend running to reproduce it... so I don't think that will be much help to you.

Is there anything else I can provide you that would help?

**Comment by lmiller1990** [comment]
Please create a minimal backend and include it in your repository. Someone has to do if it we are going to debug this, and I think it's much quicker and practical if you do, since you know what the bug looks like and how to reproduce it better than anyone else. I'm sorry, but I don't have the time or bandwidth to recreate the issue you are running into.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
