### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

### ISSUE THREAD

**Issue by thestalnaker** [cypress-io/cypress#27318]
### Current behavior

Running npx cypress open produces the following output:

```shell
ubuntu@DESKTOP-PIFL1I2:~/$ npm run open

> project@2023.3.1 open
> npx cypress open

The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 12.12.0
ubuntu@DESKTOP-PIFL1I2:~/$ ```
```
### Desired behavior

When npx cypress open is run, the cypress app opens as it normally should.

### Test code to reproduce

```js
describe('Test Links', () => {

    let urls = [
        "/pages/my/page",
        ...
    ];
    beforeEach(() => {
        cy.session('performLogin', () => {
            let username = 'me@aol.com'
            let password = '******'
            cy.login(username, password);
        }, {
            cacheAcrossSpecs: true
        })
    });
    it(`Visits /pages/myother/page and adds a role`, () => {
        cy.visit("/pages/myother/page")
        cy.get('a[data-module_code="modulecode"][data-module_action="add"]').click()
        cy.get('input[id=myid]').type(Math.floor(Math.random() * Date.now()).toString(36))
        cy.get('button[data-target="target"]').click()
    });

    urls.forEach(url => {

        it(`Visits ${url}`, () => {
            cy.visit(url)
            cy.logLinks()
        });
    });
});```
```
### Cypress Version

12.12.0

### Node version

18.16.0

### Operating System

ubuntu 20

### Other

This just randomly started

**Comment by gewesp** [comment]
Seeing the same issue on a MacBook Pro:
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-arm64 (21.2.0)
Cypress Version: 12.5.1
```

**Comment by 7999** [comment]
met same issue, and this issue already exist in previous versions.
https://github.com/cypress-io/cypress/issues/19569

**Comment by urubatan** [comment]
I see the same issue on Windows/WSL2/Ubuntu, and all tests passed, just the test runner crashed after...

```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 12.17.3
 
 >  NX   Running target cypress for project e2e failed
   Failed tasks:
   
   - e2e:cypress
   
   Hint: run the command with --verbose for more details.
Error: Command failed with exit code 1: npm run cypress
    at makeError (/home/urubatan/projects/pressdesk/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/urubatan/projects/pressdesk/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: npm run cypress',
  command: 'npm run cypress',
  escapedCommand: '"npm run cypress"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Warning: run-commands command "start-test msw http-get://localhost:3000 cypress" exited with non-zero status code
```
