### ISSUE TITLE
The After Run API fails in interactive mode via open even with experimentalInteractiveRunEvents

### ISSUE THREAD

**Issue by steveguerrero** [cypress-io/cypress#27335]
### Current behavior

In our project we use cypress in interactive mode and trying to use the after run api to run a delete function after the tests run. 

As described in the cypress documentation we use the flag experimentalInteractiveRunEvents in our config.

If you run the interactive mode the after run api doesn't trigger the delete function but displays an error message after closing the Cypress client:

"Error:        
Expected DataContext to already have been set via setCtx. If this is a testing context, make sure you are calling "setCtx" in a before hook, otherwise check the application flow."

### Desired behavior

The After Run API should trigger when the user closes the browser or probably even better on closing the Cypress client

### Test code to reproduce
```js
experimentalInteractiveRunEvents: true,
async setupNodeEvents(on, config) {
        on('after:run', async (results) => {
          await deleteStuff();
        });
    },
```
### Cypress Version

12.17.1

### Node version

v18.16.1

### Operating System

Windows 10 Enterprise 21H219044.3086

**Comment by nagash77** [comment]
@steveguerrero In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

Also check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by steveguerrero** [comment]
@nagash77 Thanks for your answer.
I created a fork from Cypress Test Tiny and I really appreciate your quick reply

https://github.com/steveguerrero/cypress-test-tiny

**Comment by steveguerrero** [comment]
Did you find a possible solution or workaround? @jennifer-shehane

**Comment by thearchitector** [comment]
i also am getting this error, running on Ubuntu 22.04 and Node v20.10.0 with Yarn 4.1.1:
```
Error: 
      Expected DataContext to already have been set via setCtx. If this is a
      testing context, make sure you are calling "setCtx" in a before hook,
      otherwise check the application flow.
    
    at c (<embedded>:4315:138737)
    at Object.u (<embedded>:4359:75697)
    at Object.<anonymous> (<embedded>:4392:28989)
    at Object.tryCatcher (~/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.execute (~/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:15:34)
    at C.close (<embedded>:4450:26869)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by cene-prometheum** [comment]
Havin the same issue, where the delete function that should be executed `after:run` won't get executed when closing the runner - same error:

```
Error: 
      Expected DataContext to already have been set via setCtx. If this is a
      testing context, make sure you are calling "setCtx" in a before hook,
      otherwise check the application flow.
    
    at c (<embedded>:2746:138737)
    at Object.u (<embedded>:2790:77126)
    at Object.<anonymous> (<embedded>:2823:28750)
    at Object.tryCatcher (~/Library/Caches/Cypress/13.12.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.execute (~/Library/Caches/Cypress/13.12.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:15:34)
    at C.close (<embedded>:2881:26880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by eshadboltadr** [comment]
Me too, same issue when closing Cypress window without running any browser.
```javascript
on('after:run', async () => {
  console.debug('In after run.');
});
```

```
Error: 
      Expected DataContext to already have been set via setCtx. If this is a
      testing context, make sure you are calling "setCtx" in a before hook,
      otherwise check the application flow.

    at c (<embedded>:2746:138779)
    at Object.u (<embedded>:2790:79114)
    at Object.<anonymous> (<embedded>:2823:28750)
From previous event:
    at C.close (<embedded>:2881:26880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by VladimirKovalenko** [comment]
Hello Here
I'm trying to use the `after:run` event in my project but have encountered the same issue. Event `after:run` is never triggered. For `before:run`, it works fine. I'm checking it for open mode (interactive). The flag is `experimentalInteractiveRunEvents: true`. 
Each time I close the project I have an error message like below
```
Error: 
      Expected DataContext to already have been set via setCtx. If this is a
      testing context, make sure you are calling "setCtx" in a before hook,
      otherwise check the application flow.
    
    at c (<embedded>:2590:129499)
    at Object.u (<embedded>:2793:86867)
    at Object.<anonymous> (<embedded>:2970:66891)
    at Object.tryCatcher (/Users/014509/Library/Caches/Cypress/13.15.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.execute (/Users/014509/Library/Caches/Cypress/13.15.2/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:15:34)
    at C.close (<embedded>:3028:26878)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I think it interrupts the flow and `after:run` event just not reached. To reproduce it you can use brand new project created from `npm install cypress --save-dev`. The only change which I did is configuration file
```
 e2e: {
    experimentalInteractiveRunEvents: true,
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('after:run', (results) => {
        console.log('+++++++++++++++++++')
      })
    },
  },
```

To reproduce
1. Install cypress using npm install cypress --save-dev
2. Change config as shown above
3. Run cypress npm cypress open
4. Choose E2E testing
5. Choose Chrome and press Start E2E testing in chrome
6. Go back to the Cypress "Choose browser" window and press Close button
7. Close the Cypress by clicking to the cross button in the top bar
Expected result: after:run is executed
Actual result: error is occured

OS: Mac 15.1
Node: 22.11.0
Cypress: 13.15.2

**Comment by eshadboltadr** [comment]
I'm making this comment to stop the issue going stale, but I haven't had time to test on latest version of Cypress. I say API lifetime events for cleanup should be guaranteed to execute.

**Comment by VladimirKovalenko** [comment]
I'm making this comment to stop the issue going stale
