### ISSUE TITLE
Can't upgrade from 3.1.0 to 3.1.1

### ISSUE THREAD

**Issue by kud** [cypress-io/cypress#2736]
```
$ npm install --save-dev cypress@3.1.1 --color=always
Command failed: npm install --save-dev cypress@3.1.1 --color=always
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.1.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kud/.npm/_logs/2018-11-07T16_44_03_162Z-debug.log

For more detail, add `--debug` to the command
```

`/Users/kud/.npm/_logs/2018-11-07T16_44_03_162Z-debug.log`

```
406 verbose stack Error: cypress@3.1.1 postinstall: `node index.js --exec install`
406 verbose stack Exit status 1
406 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
406 verbose stack     at EventEmitter.emit (events.js:182:13)
406 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
406 verbose stack     at ChildProcess.emit (events.js:182:13)
406 verbose stack     at maybeClose (internal/child_process.js:970:16)
406 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
407 verbose pkgid cypress@3.1.1
408 verbose cwd /Users/kud/Projects/_contexte/contexte/contexte/front/main
409 verbose Darwin 17.7.0
410 verbose argv "/usr/local/Cellar/node/11.1.0/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "cypress@3.1.1" "--color=always"
411 verbose node v11.1.0
412 verbose npm  v6.4.1
413 error code ELIFECYCLE
414 error errno 1
415 error cypress@3.1.1 postinstall: `node index.js --exec install`
415 error Exit status 1
416 error Failed at the cypress@3.1.1 postinstall script.
416 error This is probably not a problem with npm. There is likely additional logging output above.
417 verbose exit [ 1, true ]
```

I'm so sad you know. :(

**Comment by jennifer-shehane** [comment]
Did you try to install without the `--color=always` flag?

**Comment by kud** [comment]
Well, removing `--color=always` didn't change anything but now, it works like a charm. I have no clue why. It didn't work like for 1 week.

Thank you for your time, it's now fixed.
