### ISSUE TITLE
Cypress hangs when trying to close Chrome tab after test finishes

### ISSUE THREAD

**Issue by ramosbugs** [cypress-io/cypress#27360]
### Current behavior

Several times per week, our CI runs time out while waiting for Cypress to close the Chrome tab after a test finishes running. When this happens, Cypress produces debug logs that look as follows:

```
    2023-07-20T18:10:31.591Z   cypress:server:run No video found after spec ran - skipping compression. Video path: undefined +17ms
    2023-07-20T18:10:31.591Z   cypress:server:run attempting to close the browser tab +0ms
    2023-07-20T18:10:31.592Z   cypress:server:browsers:browser-cri-client Closing current target 8C6573E89C288B166F0180EF7D365808 +5s
    2023-07-20T18:10:31.593Z   cypress-verbose:server:browsers:cri-client:send:[-->] sending CDP command { id: 2, method: 'Target.closeTarget', params: { targetId: '8C6573E89C288B166F0180EF7D365808' } } +380ms
    2023-07-20T18:10:31.825Z   cypress:server:preprocessor removeFile /home/runner/work/unflakable-javascript/unflakable-javascript/packages/cypress-plugin/test/integration-input/cypress/e2e/hook-fail.cy.ts +2s
    2023-07-20T18:10:31.825Z   cypress:server:preprocessor base emitter plugin close event +0ms
    2023-07-20T18:10:31.826Z   cypress:server:preprocessor base emitter native close event +0ms
    2023-07-20T18:10:31.826Z   cypress:server:preprocessor base emitter native close event +0ms
    2023-07-20T18:10:31.826Z   cypress:server:browsers:chrome closing remote interface client +2s
    2023-07-20T18:10:31.826Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.webSocketFrameSent', params: { requestId: '3874.9', timestamp: 160.222961, response: { opcode: 1, mask: true, payloadData: '42[\"mocha\",\"suite end\",{\"id\":\"r2\",\"title\":\"describe block\",\"root\":false,\"pending\":false,\"type\":\"suite\",\"file\":null,\"invocationDetails\":{\"function\":\"Object.eval\",\"fileUrl\":\"http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts\",\"originalFile\":\"webpack:///./cypress/component/hook-fail.cy.ts\",\"relativeFile\":\"cypress/component/hook-fail.cy.ts\",\"absoluteFile\":\"/home/runner/work/unflakable-javascript/unflakable-javascript/packages/cypress-plugin/test/integration-input/cypress/component/hook-fail.cy.ts\",\"line\":3,\"column\":0,\"whitespace\":\"    \",\"stack\":\"Error\\\\n    at Object.eval (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:294:1)\\\\n    at ./cypress/component/hook-fail.cy.ts (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:352:30)\\\\n    at __webpack_require__ (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:20:30)\\\\n    at 0 (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:363:18)\\\\n    at __webpack_require__ (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:20:30)\\\\n    at eval (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:84:18)\\\\n    at eval (http://localhost:39907/__cypress/tests?p=cypress/e2e/hook-fail.cy.ts:87:10)\\\\n    at eval (<anonymous>)\"},\"retries\":-1,\"_slow\":10000}]' } } } +236ms
    2023-07-20T18:10:31.830Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { id: 2, result: { success: true } } +4ms
    2023-07-20T18:10:31.832Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 49312 } +3s
    2023-07-20T18:10:31.832Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 49286 } +1ms
    2023-07-20T18:10:31.833Z   cypress:server:socket-base socket-disconnecting transport close +620ms
    2023-07-20T18:10:31.834Z   cypress:server:socket-base socket-disconnect transport close +0ms
    2023-07-20T18:10:31.834Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.webSocketFrameSent', params: { requestId: '3874.9', timestamp: 160.222977, response: { opcode: 1, mask: true, payloadData: '42[\"mocha\",\"suite end\",{\"id\":\"r1\",\"title\":\"\",\"root\":true,\"pending\":false,\"type\":\"suite\",\"file\":\"cypress/e2e/hook-fail.cy.ts\",\"retries\":-1,\"_slow\":10000}]' } } } +4ms
    2023-07-20T18:10:31.834Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 54210 } +2ms
    2023-07-20T18:10:31.835Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 54230 } +1ms
    2023-07-20T18:10:31.835Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 54224 } +0ms
    2023-07-20T18:10:31.835Z   cypress:server:util:socket_allowed allowing socket { localPort: 54238 } +0ms
    2023-07-20T18:10:31.838Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.webSocketFrameSent', params: { requestId: '3874.9', timestamp: 160.22305, response: { opcode: 1, mask: true, payloadData: '42[\"mocha\",\"end\",{\"end\":\"2023-07-20T18:10:31.500Z\"}]' } } } +4ms
    2023-07-20T18:10:31.839Z   cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 54238 } +4ms
    2023-07-20T18:10:31.839Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { method: 'Network.webSocketFrameReceived', params: { requestId: '3874.9', timestamp: 160.251418, response: { opcode: 1, mask: false, payloadData: '42[\"tests:finished\"]' } } } +1ms
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │ (index) │       group       │ processCount │           pids           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │          '3238'          │   19.14    │      9.74      │  421.88  │    371.59    │   421.88    │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │    1    │ 'electron-shared' │      4       │ '3242, 3396, 3243, 3589' │    0.01    │      0.01      │  195.82  │    144.39    │   195.82    │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │    2    │     'plugin'      │      1       │          '3564'          │    0.83    │      0.83      │  183.07  │    183.07    │   183.07    │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │    3    │      'other'      │      2       │       '3901, 3902'       │     0      │       0        │   2.53   │     2.52     │    2.53     │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler │    4    │      'TOTAL'      │      8       │           '-'            │   19.98    │     10.17      │  803.3   │    610.03    │    803.3    │
    2023-07-20T18:10:34.204Z   cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │ (index) │       group       │ processCount │           pids           │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │          '3238'          │    0.64    │      6.71      │  421.16  │    388.11    │   421.88    │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │    1    │ 'electron-shared' │      4       │ '3242, 3396, 3243, 3589' │     0      │      0.01      │  195.82  │    161.53    │   195.82    │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │    2    │     'plugin'      │      1       │          '3564'          │     0      │      0.42      │  183.07  │    183.07    │   183.07    │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │    3    │      'other'      │      2       │       '4061, 4062'       │     0      │       0        │   2.53   │     2.52     │    2.53     │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler │    4    │      'TOTAL'      │      8       │           '-'            │    0.64    │      6.99      │  802.57  │    674.21    │    803.3    │
    2023-07-20T18:10:44.319Z   cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
    2023-07-20T18:10:54.425Z   cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
...
```
When this bug occurs, Cypress continues logging memory/CPU stats every 10 seconds until the CI test times out.

See https://github.com/unflakable/unflakable-javascript/actions/runs/5614396375/job/15212578267 for complete logs from a recent failure.

### Desired behavior

The same level of debug logging shows the following output when the tab is closed successfully:
```
    2023-07-20T22:14:20.912Z   cypress:server:run No video found after spec ran - skipping compression. Video path: undefined +4ms
    2023-07-20T22:14:20.912Z   cypress:server:run attempting to close the browser tab +0ms
    2023-07-20T22:14:20.912Z   cypress:server:browsers:browser-cri-client Closing current target B95564241762A215760C275D92E29642 +3s
    2023-07-20T22:14:20.913Z   cypress-verbose:server:browsers:cri-client:send:[-->] sending CDP command { id: 2, method: 'Target.closeTarget', params: { targetId: 'B95564241762A215760C275D92E29642' } } +73ms
    2023-07-20T22:14:20.914Z   cypress-verbose:server:browsers:cri-client:recv:[<--] received CDP message { id: 2, result: { success: true } } +3ms
    2023-07-20T22:14:20.914Z   cypress:server:run resetting server state +2ms
```

It looks like the `received CDP message` log line never occurs on failing runs in response to the `Target.closeTarget` command sent to Chrome.

### Test code to reproduce

This is an intermittent issue with no reliable repro. I don't believe it's related to our specific Cypress testing code, although it's available at https://github.com/unflakable/unflakable-javascript/tree/main/packages/cypress-plugin/test.

### Cypress Version

12.16, 12.17

### Node version

20.4.0

### Operating System

Ubuntu 22.04.2 image on GitHub Actions

### Debug Logs

```shell
See above.
```

### Other

This issue occurs on a variety of recent Cypress and Node versions, on both e2e and component tests.

**Comment by rene6502** [comment]
We face similar issues after we have upgraded to Cypress 12.
With Cypress 11 this problem was not there.
We are using Cypress 12.17.1, Node 16.20.1, on Ubuntu 22.04.2 image on GitHub Actions.
Debug logging shows that the test finishes successfully and Cypress closes the browser.
Browser close is successful (no more chrome processes are logged) but Cypress does not recognize this and waits forever.

**Comment by romanofski** [comment]
I've been looking into this issue as well. I can't reproduce it locally only in CI. I've found similar behavior (according to the logs) locally if I simply close the chrome browser with a mouse click. I had filed #27000 but it seems it was a red herring.

We run our CI on 20.04 Ubuntu LTS, against a headed Chrome (I've tried Edge, same issue).

The difference I saw compared to successful runs is that chrome exits:

```
2023-08-07T00:06:19.8097161Z 2023-08-07T00:06:19.801Z cypress:launcher:browsers chrome exited: { code: 0, signal: null }
2023-08-07T00:06:19.8097598Z 2023-08-07T00:06:19.801Z cypress:server:browsers:chrome closing remote interface client  
```
and a few lines later when Cypress prints chromes stderr it shows this:

```
2023-08-07T00:06:19.8100431Z 2023-08-07T00:06:19.802Z cypress:launcher:browsers chrome stderr: [0807/100619.801421:ERROR:nacl_helper_linux.cc(355)] NaCl helper process running without a sandbox!                                    2023-08-07T00:06:19.8100840Z Most likely you need to configure your SUID sandbox correctly
```
which is exactly what I get when I simply close the browser locally during a test run. The profiler continues in CI until killed.

For us the problem seems to have started prior to Cypress v11, however I'm not so sure any more where exactly as various tests seem to not show any specific issues to create a reproducer.

I've been digging around into the Cypress code and similarly to this comment: https://github.com/cypress-io/cypress/issues/25972#issuecomment-1487021361 it seems the call to `await openProject.resetBrowserTabsForNextTest(shouldKeepTabOpen)` never exits, because I'm missing the log entry of `resetting server state` for the final test run.

**Comment by kevingorry** [comment]
@romanofski did you find a solution ? I'm running into the same issue

**Comment by romanofski** [comment]
@kevingorry Unfortunately not. We decided to not spend more engineering time finding the culprit, but migrate over to Playwright.

**Comment by elmuerte** [comment]
We observe the same problem.

Cypress:        11.2.0
Browser:        Chrome 119 (headless) and Edge 119 (headless)
Node Version:   v14.21.1

The jobs run in docker containers. Also no reproducible case. After quite some debugging the process does appear to hang at `resetBrowserTabsForNextTest`. I checked the system, and there was no browser process around anymore.
