### ISSUE TITLE
Cypress error when updating cypress.json to cypress.config.ts

### ISSUE THREAD

**Issue by trtincher** [cypress-io/cypress#27628]
### Current behavior

I successfully installed cypress. However, when running `npx cypress open` I received this error. 

```
npx cypress open

DevTools listening on ws://127.0.0.1:58996/devtools/browser/51e206f7-8ab0-496a-8dcc-0b231a9c3103
(node:14965) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14965) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
/Users/travistincher/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/telemetry/dist/span-exporters/ipc-span-exporter.js:11
        super({});
        ^
TypeError: Class constructor OTLPTraceExporter cannot be invoked without 'new'
    at new OTLPTraceExporter (/Users/travistincher/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/telemetry/dist/span-exporters/ipc-span-exporter.js:11:9)
    at Object.<anonymous> (/Users/travistincher/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/Users/travistincher/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:857:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/Users/travistincher/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I then attempted to manually create a `cypress.json`. This however brought up a wizard that attempted to convert my `cypress.json` to a `cypress.config.ts` which then resulted in the same error as above. There is clearly a typescript error here but I am unsure if this is due to something with my local setup or an error with this cypress version.

### Cypress Version

12.17.4

### Node version

v16.17.0

### Package Manager

yarn

### Package Manager Version

1.22.19

### Operating system

Mac

### Operating System Version

13.5

**Comment by trtincher** [comment]
Ah I have found that the error was in my tsconfig.json. I need to set my target to "es6" instead of "es5".
