### ISSUE TITLE
Site is crashing when filters are upadated in overview page

### ISSUE THREAD

**Issue by mavric6705** [cypress-io/cypress#27785]
### Current behavior

URL - https://cloud.cypress.io/projects/***/runs/386/overview?runStatus=OVERLIMIT&roarHideRunsWithDiffGroupsAndTags=0
![Image](https://github.com/cypress-io/cypress/assets/142535835/6e877d54-bf3a-4ce3-878b-bcc8ac4e99cf)

### Desired behavior

should show only passed tests

### Test code to reproduce

na

### Cypress Version

na

### Node version

na

### Operating System

windows,
brave browser

**Comment by mavric6705** [comment]
Please fix this as soon as possible, not able to view the current status.

Error - `TypeError: Cannot read properties of undefined (reading 'label')
    at StatusesDropdown.tsx:109:11
    at Dt (StatusesDropdown.tsx:127:24)
    at To (react-dom.production.min.js:148:98)
    at zs (react-dom.production.min.js:245:452)
    at As (react-dom.production.min.js:216:164)
    at ks (react-dom.production.min.js:210:471)
    at ps (react-dom.production.min.js:206:372)
    at react-dom.production.min.js:114:115
    at t.unstable_runWithPriority (scheduler.production.min.js:20:134)
    at fa (react-dom.production.min.js:113:325)
    at ya (react-dom.production.min.js:114:61)
    at ga (react-dom.production.min.js:113:476)
    at ds (react-dom.production.min.js:204:235)
    at Zo (react-dom.production.min.js:156:232)
    at Object.next (react-hooks.esm.js:232:23)
    at b (Observable.js:135:18)
    at k (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at apollo-client.esm.js:1242:61
    at Array.forEach (<anonymous>)
    at se (apollo-client.esm.js:1242:25)
    at Object.next (apollo-client.esm.js:1215:25)
    at a (apollo-client.esm.js:2016:30)
    at apollo-client.esm.js:2101:17
    at apollo-client.esm.js:2359:25
    at Set.forEach (<anonymous>)
    at apollo-client.esm.js:2357:32
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (apollo-client.esm.js:2355:22)
    at apollo-client.esm.js:2446:27
    at Object.next (Observable.js:322:23)
    at b (Observable.js:135:18)
    at k (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at apollo-client.esm.js:1673:75
    at Set.forEach (<anonymous>)
    at Object.next (apollo-client.esm.js:1673:27)
    at b (Observable.js:135:18)
    at k (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at Object.next (Observable.js:327:22)
    at b (Observable.js:135:18)
    at k (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at Object.next (Observable.js:327:22)
    at b (Observable.js:135:18)
    at k (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at Object.next (bundle.esm.js:29:34)
    at b (Observable.js:135:18)`

**Comment by mavric6705** [comment]
@nagash77 - please fix this ASAP, not able to perform any action. let me know if you need any help

**Comment by nagash77** [comment]
Hi @mavric6705 are you using some sort of adblocker in your browser?  Do you have any other extensions or plugins enabled in your browser?

**Comment by mavric6705** [comment]
no, i am using brave browser - 
![Image](https://github.com/cypress-io/cypress/assets/142535835/ceec150a-7ce9-470c-b86c-19f18f922ad8)

Even after toggling off the brave shield still the same output.

**Comment by nagash77** [comment]
@mavric6705 can you try using another browser like chrome and see if the problem persists?

**Comment by mavric6705** [comment]
The same result, the site crashes in all browser

**Comment by ryanpei** [comment]
@mavric6705 I see in the URL you shared there is a filter param for status "OVERLIMIT". "OVERLIMIT" is not a common status anymore for most Cypress Cloud accounts. You also mentioned you wanted to see all passing tests. So if you replace "runStatus=OVERLIMIT" with "runStatus=PASSED" in the URL, does that work?

**Comment by mavric6705** [comment]
Yes, worked, but how did it take OVERLIMIT as a parameter?
