### ISSUE TITLE
Command was killed with SIGSEGV (Segmentation fault)

### ISSUE THREAD

**Issue by metal-draken** [cypress-io/cypress#27858]
### Current behavior

While starting cypress I get I get:

```
[FAILED] Cypress failed to start.
[FAILED]
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED]
[FAILED] Please refer to the error below for more details.
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Command was killed with SIGSEGV (Segmentation fault): /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=881
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-x64 (Ubuntu - 22.04)
[FAILED] Cypress Version: 12.13.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGSEGV (Segmentation fault): /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=881

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 12.13.0
```

### Desired behavior

Cypress should start as usual.

### Test code to reproduce

no Code needed.

### Cypress Version

12.13.0

### Node version

18.16.0

### Operating System

Linux Ubuntu 22.04

### Debug Logs

```shell
2023-09-20T15:23:36.565Z cypress:cli verifying Cypress app
2023-09-20T15:23:36.566Z cypress:cli checking environment variables
2023-09-20T15:23:36.566Z cypress:cli checking if executable exists /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress
2023-09-20T15:23:36.567Z cypress:cli Binary is executable? : true
2023-09-20T15:23:36.567Z cypress:cli binaryDir is  /home/marqo/.cache/Cypress/12.13.0/Cypress
2023-09-20T15:23:36.567Z cypress:cli Reading binary package.json from: /home/marqo/.cache/Cypress/12.13.0/Cypress/resources/app/package.json
2023-09-20T15:23:36.568Z cypress:cli Found binary version 12.13.0 installed in: /home/marqo/.cache/Cypress/12.13.0/Cypress
2023-09-20T15:23:36.569Z cypress:cli could not read binary_state.json file at "/home/marqo/.cache/Cypress/12.13.0/binary_state.json"
2023-09-20T15:23:36.569Z cypress:cli {}
2023-09-20T15:23:36.569Z cypress:cli is Verified ? undefined
2023-09-20T15:23:36.569Z cypress:cli running binary verification check 12.13.0
It looks like this is your first time using Cypress: 12.13.0
[STARTED] Task without title.
2023-09-20T15:23:36.570Z cypress:cli clearing out the verified version
2023-09-20T15:23:36.571Z cypress:cli DISPLAY environment variable is set to 172.21.16.1:0.0 on Linux
Assuming this DISPLAY points at working X11 server,
Cypress will not spawn own Xvfb
NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  see https://github.com/cypress-io/cypress/issues/4034
Solution: Unset the DISPLAY variable and try again:
  DISPLAY= npx cypress run ...
2023-09-20T15:23:36.571Z cypress:cli needs Xvfb? false
2023-09-20T15:23:36.571Z cypress:cli spawning, should retry on display problem? true
2023-09-20T15:23:36.571Z cypress:cli disabling Electron sandbox
2023-09-20T15:23:36.571Z cypress:cli running smoke test
2023-09-20T15:23:36.571Z cypress:cli using Cypress executable /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress
2023-09-20T15:23:36.571Z cypress:cli smoke test command: /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=219
2023-09-20T15:23:36.571Z cypress:cli smoke test timeout 30000 ms
2023-09-20T15:23:39.376Z cypress:cli Smoke test failed: Error: Command was killed with SIGSEGV (Segmentation fault): /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=219
2023-09-20T15:23:36.938Z cypress:snapshot:info Caching 3793, defining 4731 modules! Using cache
2023-09-20T15:23:36.939Z cypress:snapshot:debug initializing packherd require
2023-09-20T15:23:37.108Z cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 177.592ms
2023-09-20T15:23:37.168Z cypress:server:appdata path: /home/marqo/.config/Cypress/cy/production/browsers
2023-09-20T15:23:37.177Z cypress:server:cypress starting cypress with argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.178Z cypress:server:args argv array: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.179Z cypress:server:args parsed argv options { options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 219 } }
2023-09-20T15:23:37.185Z cypress:server:args argv parsed: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo' }
2023-09-20T15:23:37.185Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2023-09-20T15:23:37.188Z cypress:server:args options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {} }
2023-09-20T15:23:37.188Z cypress:server:args argv options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
2023-09-20T15:23:37.188Z cypress:server:cypress from argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ] got options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
    at makeError (/home/marqo/monorepo/node_modules/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/marqo/monorepo/node_modules/cypress/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGSEGV (Segmentation fault): /home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=219',
  command: '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress --no-sandbox --smoke-test --ping=219',
  exitCode: undefined,
  signal: 'SIGSEGV',
  signalDescription: 'Segmentation fault',
  stdout: '',
  stderr: '2023-09-20T15:23:36.938Z cypress:snapshot:info Caching 3793, defining 4731 modules! Using cache\n' +
    '2023-09-20T15:23:36.939Z cypress:snapshot:debug initializing packherd require\n' +
    '2023-09-20T15:23:37.108Z cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 177.592ms\n' +
    '2023-09-20T15:23:37.168Z cypress:server:appdata path: /home/marqo/.config/Cypress/cy/production/browsers\n' +
    "2023-09-20T15:23:37.177Z cypress:server:cypress starting cypress with argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]\n" +
    "2023-09-20T15:23:37.178Z cypress:server:args argv array: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]\n" +
    "2023-09-20T15:23:37.179Z cypress:server:args parsed argv options { options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 219 } }\n" +
    "2023-09-20T15:23:37.185Z cypress:server:args argv parsed: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo' }\n" +
    "2023-09-20T15:23:37.185Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }\n" +
    "2023-09-20T15:23:37.188Z cypress:server:args options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {} }\n" +
    "2023-09-20T15:23:37.188Z cypress:server:args argv options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }\n" +
    "2023-09-20T15:23:37.188Z cypress:server:cypress from argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ] got options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
2023-09-20T15:23:39.376Z cypress:cli error message: 2023-09-20T15:23:36.938Z cypress:snapshot:info Caching 3793, defining 4731 modules! Using cache
2023-09-20T15:23:36.939Z cypress:snapshot:debug initializing packherd require
2023-09-20T15:23:37.108Z cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 177.592ms
2023-09-20T15:23:37.168Z cypress:server:appdata path: /home/marqo/.config/Cypress/cy/production/browsers
2023-09-20T15:23:37.177Z cypress:server:cypress starting cypress with argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.178Z cypress:server:args argv array: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.179Z cypress:server:args parsed argv options { options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 219 } }
2023-09-20T15:23:37.185Z cypress:server:args argv parsed: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo' }
2023-09-20T15:23:37.185Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2023-09-20T15:23:37.188Z cypress:server:args options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {} }
2023-09-20T15:23:37.188Z cypress:server:args argv options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
2023-09-20T15:23:37.188Z cypress:server:cypress from argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ] got options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
[FAILED] Cypress failed to start.
[FAILED]
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED]
[FAILED] Please refer to the error below for more details.
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] 2023-09-20T15:23:36.938Z cypress:snapshot:info Caching 3793, defining 4731 modules! Using cache
[FAILED] 2023-09-20T15:23:36.939Z cypress:snapshot:debug initializing packherd require
[FAILED] 2023-09-20T15:23:37.108Z cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 177.592ms
[FAILED] 2023-09-20T15:23:37.168Z cypress:server:appdata path: /home/marqo/.config/Cypress/cy/production/browsers
[FAILED] 2023-09-20T15:23:37.177Z cypress:server:cypress starting cypress with argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
[FAILED] 2023-09-20T15:23:37.178Z cypress:server:args argv array: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
[FAILED] 2023-09-20T15:23:37.179Z cypress:server:args parsed argv options { options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 219 } }
[FAILED] 2023-09-20T15:23:37.185Z cypress:server:args argv parsed: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo' }
[FAILED] 2023-09-20T15:23:37.185Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
[FAILED] 2023-09-20T15:23:37.188Z cypress:server:args options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {} }
[FAILED] 2023-09-20T15:23:37.188Z cypress:server:args argv options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
[FAILED] 2023-09-20T15:23:37.188Z cypress:server:cypress from argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ] got options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
[FAILED]
[FAILED] ----------
[FAILED]
[FAILED] Platform: linux-x64 (Ubuntu - 22.04)
[FAILED] Cypress Version: 12.13.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

2023-09-20T15:23:36.938Z cypress:snapshot:info Caching 3793, defining 4731 modules! Using cache
2023-09-20T15:23:36.939Z cypress:snapshot:debug initializing packherd require
2023-09-20T15:23:37.108Z cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 177.592ms
2023-09-20T15:23:37.168Z cypress:server:appdata path: /home/marqo/.config/Cypress/cy/production/browsers
2023-09-20T15:23:37.177Z cypress:server:cypress starting cypress with argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.178Z cypress:server:args argv array: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ]
2023-09-20T15:23:37.179Z cypress:server:args parsed argv options { options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, 'smoke-test': true, smokeTest: true, ping: 219 } }
2023-09-20T15:23:37.185Z cypress:server:args argv parsed: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo' }
2023-09-20T15:23:37.185Z cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' }
2023-09-20T15:23:37.188Z cypress:server:args options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {} }
2023-09-20T15:23:37.188Z cypress:server:args argv options: { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }
2023-09-20T15:23:37.188Z cypress:server:cypress from argv [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress', '--no-sandbox', '--smoke-test', '--ping=219' ] got options { _: [ '/home/marqo/.cache/Cypress/12.13.0/Cypress/Cypress' ], sandbox: false, smokeTest: true, ping: 219, invokedFromCli: false, cwd: '/home/marqo/monorepo', config: {}, pong: 219 }

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 12.13.0
```

### Other

WSL2 on Windows 10
Use the https://sourceforge.net/projects/xming/ to run Cypress on Windows 10
Already install all dependencies recommended by cypress

**Comment by michael-mammut** [comment]
I run into a similary error:
```
The Test Runner unexpectedly exited via a exit event with signal SIGSEGV

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux-x64 (Ubuntu - 22.04)
Cypress Version: 13.1.0

Additional Information:
node --version: v20.7.0
```

The the page rund fast, but the page to select a browser is very slow and ends in this error.

**Comment by nagash77** [comment]
@metal-draken WSL/2 is not officially supported by Cypress at this time.  Please try using one of our supported OSes and see if that resolves your issues.  If the problem persists please comment back here and we can reopen.

@michael-mammut crashes can be caused by many different things.  The original issue is using WSL2 which is not officially supported by Cypress.  Your output says you are using Ubuntu, so I would suggest you open a new issue and include your debug logs.

**Comment by michael-mammut** [comment]
@metal-draken  OK, i try to find a way to show the logs while i start cypress but i can not find some information. `cypress --help` contains also no Informationen about it. Which debug so you mean?

**Comment by metal-draken** [comment]
@michael-mammut 
`DEBUG=cypress:* cypress run`

**Comment by miglocatiq** [comment]
Running into the same problem. Out of nowhere Cypress doesn't work anymore in WSL2

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 13.2.0
npm version: 9.7.1
node version: 20.3.0

**Comment by bpierard-mastery** [comment]
@miglocatiq, for what it's worth, we ran into the same and upgrading from Ubuntu 20.04 to Ubuntu 22.04 fixed the issue

**Comment by metal-draken** [comment]
> @miglocatiq, for what it's worth, we ran into the same and upgrading from Ubuntu 20.04 to Ubuntu 22.04 fixed the issue

I have a similar issue in both cases 🙁
This issue and also https://github.com/cypress-io/cypress/issues/27857

**Comment by miglocatiq** [comment]
> @miglocatiq, for what it's worth, we ran into the same and upgrading from Ubuntu 20.04 to Ubuntu 22.04 fixed the issue

@bpierard-mastery   Thanks! That worked for me as well
