### ISSUE TITLE
cypress opens  window but crashes immediately.

### ISSUE THREAD

**Issue by skoppdp** [cypress-io/cypress#27985]
### Current behavior

When running DEBUG=cypress:* ./node_modules/.bin/cypress open cypress opens a window but crashes immediately.

![grafik](https://github.com/cypress-io/cypress/assets/93104405/3c69e673-761f-442f-aa07-b4b90fb9aeaa)

### Desired behavior

Cypress should show me the playground.

### Test code to reproduce

Create fresh a nx monorepo anuglar app

npx create-nx-workspace@latest

or create a fresh angular app 

ng new my-app

same behavior

### Cypress Version

13.3.0

### Node version

v18.18

### Operating System

Debian 12

### Debug Logs

```shell
cypress:cli:cli cli starts with arguments ["/home/dennis/.nvm/versions/node/v18.18.0/bin/node","/home/dennis/yes/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +4ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +212ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress +3ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  /home/dennis/.cache/Cypress/13.3.0/Cypress +0ms
  cypress:cli Reading binary package.json from: /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 13.3.0 installed in: /home/dennis/.cache/Cypress/13.3.0/Cypress +6ms
  cypress:cli { verified: true } +7ms
  cypress:cli is Verified ? true +3ms
  cypress:cli opening from options {"project":"/home/dennis/yes"} +0ms
  cypress:cli command line arguments ["--project","/home/dennis/yes"] +0ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +1ms
  cypress:cli passing DISPLAY :0 +2ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--project', '/home/dennis/yes', '--cwd', '/home/dennis/yes', '--userNodePath', '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', '--userNodeVersion', '18.18.0' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +0ms
  cypress:cli spawning Cypress with executable: /home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress +2ms
  cypress:cli piping child STDERR to process STDERR +24ms
  cypress:snapshot:info Caching 3470, defining 4280 modules! Using cache +0ms
  cypress:snapshot:debug initializing packherd require +0ms
  cypress:server:performance-benchmark elapsed time at v8-snapshot-startup-time: 162.087ms +0ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/browsers +0ms
  cypress:server:cypress starting cypress with argv [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress', '--no-sandbox', '--', '--project', '/home/dennis/yes', '--cwd', '/home/dennis/yes', '--userNodePath', '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', '--userNodeVersion', '18.18.0' ] +0ms
  cypress:server:args argv array: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress', '--no-sandbox', '--project', '/home/dennis/yes', '--cwd', '/home/dennis/yes', '--userNodePath', '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', '--userNodeVersion', '18.18.0' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0' } } +1ms
  cypress:server:args argv parsed: { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0', invokedFromCli: true } +5ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0', invokedFromCli: true, config: {} } +3ms
  cypress:server:args argv options: { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0', invokedFromCli: true, config: {}, projectRoot: '/home/dennis/yes' } +0ms
  cypress:server:cypress from argv [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress', '--no-sandbox', '--project', '/home/dennis/yes', '--cwd', '/home/dennis/yes', '--userNodePath', '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', '--userNodeVersion', '18.18.0' ] got options { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0', invokedFromCli: true, config: {}, projectRoot: '/home/dennis/yes' } +11ms
[15174:1005/185715.733665:ERROR:udev_watcher.cc(63)] Failed to enable receiving udev events.
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production +218ms

DevTools listening on ws://127.0.0.1:53345/devtools/browser/d7bb18c4-8b1c-4fd4-842c-c5d7bb738c38
[15174:1005/185715.865189:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/Cypress' ], sandbox: false, project: '/home/dennis/yes', cwd: '/home/dennis/yes', userNodePath: '/home/dennis/.nvm/versions/node/v18.18.0/bin/node', userNodeVersion: '18.18.0', invokedFromCli: true, config: {}, projectRoot: '/home/dennis/yes' } +332ms
  cypress:server:cypress running Electron currently +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudLatestRunUpdateSpecData +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectBySlug +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectsBySlugs +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudSpecByPath +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudViewer +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.pollingIntervals +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.versions +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for CurrentProject.cloudProject +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RelevantRunInfo.status +3ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectResult.data +2ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectSpecResult.data +0ms
[15328:1005/185716.003397:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[15328:1005/185716.008455:WARNING:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
  cypress:server:browsers:utils getBrowsers +0ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86, validator: [Function: validator] }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/im, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge.+?(\S*(?= canary)|(?<=canary )\S*)/im, binary: [ 'edge-canary', 'microsoft-edge-canary' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge.+?(\S*(?= beta)|(?<=beta )\S*)/im, binary: [ 'edge-beta', 'microsoft-edge-beta' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge.+?(\S*(?= dev)|(?<=dev )\S*)/im, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +0ms
  cypress:server:browsers:utils WebKit is enabled, but there was an error constructing the WebKit browser: { err: Error: Cannot find module 'playwright-webkit' Require stack: - /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server/lib/browsers/utils.ts     at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)     at n._resolveFilename (node:electron/js2c/browser_init:2:117603)     at resolve (node:internal/modules/cjs/helpers:116:19) at Function.resolve (evalmachine.<anonymous>:1:744974) at P (<embedded>:4490:64463) at Object.I [as getBrowsers] (<embedded>:4490:65298) at b.machineBrowsers (<embedded>:4263:74332) at S._setCurrentProject (<embedded>:4446:73316) at new S (<embedded>:4446:66261) at new E (<embedded>:4446:127742) at N (<embedded>:4562:41206) at s.exports (<embedded>:4562:142783) at <embedded>:4569:3280 at tryCatcher (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23) at Function.<anonymous> (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29) at Object.runElectron (<embedded>:4569:3050) at Object.startInMode (<embedded>:4569:6086) at <embedded>:4569:4826 at tryCatcher (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at PromiseArray._resolve (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:126:19) at PromiseArray._promiseFulfilled (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:144:14) at Promise._settlePromise (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:574:26) at Promise._settlePromise0 (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._settlePromise (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:582:21) at Promise._settlePromise0 (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._settlePromise (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:582:21) at Promise._settlePromise0 (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at PromiseArray._resolve (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:126:19) at PromiseArray._promiseFulfilled (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise_array.js:144:14) at Promise._settlePromise (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:574:26) at Promise._settlePromise0 (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:694:18) at Promise._fulfill (/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:638:18) at /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/bluebird/js/release/nodeback.js:42:21 at <embedded>:2086:115512 { code: 'MODULE_NOT_FOUND', requireStack: [ '/home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server/lib/browsers/utils.ts' ] } } +4ms
  cypress:data-context:sources:GitDataSource config: { isRunMode: false, projectRoot: '/home/dennis/yes', onError: [Function (anonymous)], onBranchChange: [Function: onBranchChange], onGitInfoChange: [Function: onGitInfoChange], onGitLogChange: [AsyncFunction: onGitLogChange] } +0ms
  cypress:data-context:sources:GitDataSource Refreshing git data +10ms
  cypress:data-context:sources:EventCollectorSource Starting +0ms
  cypress:scaffold-config:detect Checking for default Cypress config file +0ms
  cypress:scaffold-config:detect Resolved typescript from /home/dennis/yes/node_modules/typescript/lib/typescript.js +2ms
  cypress:scaffold-config:detect Detected typescript in package.json - using TS +0ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/cache +377ms
  cypress:data-context:actions:LocalSettingsActions refresh local settings +0ms
  cypress:server:util:editors get user editor +0ms
  cypress:server:saved_state making saved state from /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state making saved state from /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server +91ms
  cypress:server:saved_state for project path /home/dennis/yes +0ms
  cypress:server:saved_state state path for project /home/dennis/yes +0ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/projects/yes-34f3261a94602e3086c5e752520f3b08/state.json +287ms
  cypress:server:saved_state full state path /home/dennis/.config/Cypress/cy/production/projects/yes-34f3261a94602e3086c5e752520f3b08/state.json +191ms
  cypress:server:saved_state making new state file around /home/dennis/.config/Cypress/cy/production/projects/yes-34f3261a94602e3086c5e752520f3b08/state.json +0ms
  cypress:data-context:sources:GitDataSource Loading git hashes +320ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '15174'     │     0      │       0        │  295.22  │    295.22    │   295.22    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '15176, 15177' │     0      │       0        │  60.49   │    60.49     │    60.49    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '15316, 15317' │     11     │       11       │   3.8    │     3.8      │     3.8     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │      '-'       │     11     │       11       │  359.52  │    359.52    │   359.52    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:server:saved_state state path for global mode +149ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +149ms
  cypress:server:saved_state full state path /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:server:saved_state making new state file around /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:data-context:sources:GitDataSource Error loading git hashes r [Error]: fatal: your current branch 'main' does not have any commits yet

    at Object.action (<embedded>:3215:509607)
    at Xs.exec (<embedded>:3215:510033)
    at <embedded>:3215:514443
    at new Promise (<anonymous>)
    at uo.handleTaskData (<embedded>:3215:514329)
    at uo.<anonymous> (<embedded>:3215:513951)
    at Generator.next (<anonymous>)
    at r (<embedded>:3215:494750) {
  task: [Object]
} +143ms
  cypress:data-context:sources:GitDataSource On current branch  +135ms
  cypress:data-context:sources:GitDataSource Creating watcher +0ms
  cypress:data-context:sources:GitDataSource Watcher initialized +8ms
  cypress:server:windows creating electron window with options { url: 'http://localhost:53354/__launchpad/index.html', backgroundColor: 'white', width: 1200, height: 800, minWidth: 597, minHeight: 400, x: null, y: null, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage { toPNG: [Function: toPNG], toJPEG: [Function: toJPEG], toBitmap: [Function: toBitmap], getBitmap: [Function: getBitmap], getScaleFactors: [Function: getScaleFactors], getNativeHandle: [Function: getNativeHandle], toDataURL: [Function: toDataURL], isEmpty: [Function: isEmpty], getSize: [Function: getSize], setTemplateImage: [Function: setTemplateImage], isTemplateImage: [Function: isTemplateImage], isMacTemplateImage: [Getter/Setter], resize: [Function: resize], crop: [Function: crop], getAspectRatio: [Function: getAspectRatio], addRepresentation: [Function: addRepresentation] }, webPreferences: { contextIsolation: true, partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false }, contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
  cypress:server:util:editors user has the following editors: [ { id: 'code', binary: 'code', name: 'Visual Studio Code' } ] +2s
  cypress:server:saved_state making saved state from /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server +2s
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +284ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +2s
  cypress:server:saved_state full state path /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +1ms
  cypress:server:browsers:utils found browsers { browsers: [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: '117.0.5938.149', path: 'google-chrome', minSupportedVersion: 64, majorVersion: '117' } ] } +3s
  cypress:server:util:editors saved preferred editor: undefined +458ms
  cypress:server:util:editors return available editors: [ { id: 'computer', name: 'File System', binary: 'computer' }, { id: 'code', name: 'Visual Studio Code', binary: 'code' } ] +1ms
  cypress:server:saved_state making saved state from /home/dennis/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server +175ms
  cypress:server:saved_state missing project path, looking for project here +1ms
[15174:1005/185718.609034:ERROR:interface_endpoint_client.cc(697)] Message 1829861366 rejected by interface blink.mojom.FrameWidgetHost
Renderer process clean-exit - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
Error: ERR_FAILED (-2) loading 'http://localhost:53354/__launchpad/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:84929)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85316)
    at WebContents.emit (node:events:513:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'http://localhost:53354/__launchpad/index.html'
}
  cypress:server:browsers browsers.kill called with no active instance +0ms
  cypress:server:saved_state state path for global mode +14ms
  cypress:server:appdata path: /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +190ms
  cypress:server:saved_state full state path /home/dennis/.config/Cypress/cy/production/projects/__global__/state.json +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +4s
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +1ms
```

**Comment by jennifer-shehane** [comment]
Oh no. This looks like Electron is just crashing for some reason. @dev8893 Does this happen on previous versions of Cypress? Specifically 13.1.0? We updated Electron in 13.2.0.

**Comment by skoppdp** [comment]
How can I check it? Electron starts without specially installing it. Think it comes with Cypress or?
Tried to install the last version (26.3.0) of Electron (npm install --save-dev electron) in my Angular project.

But no luck. Same issue.

**Comment by andrii-lundiak** [comment]
I have Cypress `13.3.0` and I test one test during a few days and I thought that an issue is my code in test (not able to find DOM element). But I realize a few things: 
1) I observe more crashes at least since Cypress `v13.2.0` and `v13.3.0` 
2) Electron (`v114`) crashes more frequent and in DIFFERENT time points of my test execution (at middle of test, at the end of the test, etc. So it is NOT my code as issue).
3) Cypress also crashes when I execute tests onto Chrome.


Note.
I execute in 3 modes:
A) e2e code on Windows but executes (`cypress open` (headed mode) or `cypress run` (headless mode) via Windows Chrome/Electron/Edge) towards `http://localhost` on local WSL/Ubuntu application

B) e2e code still on Windows but executes (`cypress open` via Windows Chrome/Electron) towards REMOTE https server of application (I can)
![image](https://github.com/cypress-io/cypress/assets/85486996/53904975-0078-4766-862c-c388bb962f98)

C) e2e code checked out on Azure/CI and executes (`cypress run` via Headless Chrome on CI Ubuntu) tests towards REMOTE https server of application
![image](https://github.com/cypress-io/cypress/assets/85486996/d369441c-48c8-456b-87c1-43f9a93a2f00)


![image](https://github.com/cypress-io/cypress/assets/85486996/5429b1b7-2b12-4c0c-9044-7399a2bc5f43)

Electron is visibly crashes in mode B. And mode C does not provide crash info but CI pipeline FAILS then and I can't debug it - (`DEBUG:*` doesn't help much).


```
displayError: 'CypressError: 
Timed out retrying after 30000ms: `cy.clear()` failed 
because it requires a DOM element or document.\n' + 
 'No elements in the current DOM matched your query:\n'
```

**But next time execution element is FOUND, so my CODE IS CORRECT !!!**

```
cypress:server:browsers:electron closed event fired +2m

cypress:server:windows error removing all extensions { 

err: TypeError: Object has been destroyed at Object.j (<embedded>:4490:85696) 
at BrowserWindow.<anonymous> (<embedded>:4490:98982)     
at Object.onceWrapper (node:events:628:26)     
at BrowserWindow.emit (node:events:525:35) 
at k.sendCloseCommandFn (<embedded>:4490:93836)     
at process.processTicksAndRejections (node:internal/process/task_queues:95:5), 

extensions: undefined 

} +0ms
```

![image](https://github.com/cypress-io/cypress/assets/85486996/befaaefe-c777-4557-a93e-e66fc4c1e058)


I don't know what `extension` is meant here. Chrome extension maybe? Yeas my corporate Windows blocks extensions on Chrome and maybe it influences Electron instance?


PS. What is interesting - I see that Electron CPU usage locally (Windows + remote app host) gives 7-14 % and Electron CPU usage on CI (Ubuntu + same remote app host) gives 30-40%

local + remote:
![Electron_CPU_p_1 2](https://github.com/cypress-io/cypress/assets/85486996/41d1f1b8-44a6-443f-9766-3e553aff06ed)

CI + remote
![Electron_CPU_p_3 1_CI](https://github.com/cypress-io/cypress/assets/85486996/48ca40d9-f46b-49e6-b8e0-097a12383e45)

Why would Electron use much more CPU for the same test/suite?
