### ISSUE TITLE
30% component test slowdown after upgrading from version 11 to 13

### ISSUE THREAD

**Issue by denis-domanskii** [cypress-io/cypress#27995]
### Current behavior

After migration from Cypress 11 to Cypress 13 I noticed that our component test pack was slowdown by 30%.

### Test code to reproduce

I have created a repo with 2 cypress projects (11 and 13):
https://github.com/DeniDoman/cypress-13-component-tests-slowdown

Open a directory with the specific Cypress version, execute `yarn && yarn test` and compare execution time provided by Cypress runner. I have 23 seconds for cy11 and 32 seconds for cy13. 

### Cypress Version

13.3.0

### Node version

Node 16, Node 20

### Operating System

macOS, Linux

**Comment by jennifer-shehane** [comment]
@denis-domanskii I'm seeing an error running the v13 version. 

There was a webpack upgrade in [12.17.4](https://docs.cypress.io/guides/references/changelog#12-17-4).

```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

Error: Failed to require webpack config at /Users/jennifer/Dev/cypress-13-component-tests-slowdown/react-ts-cypress-13/node_modules/react-scripts/config/webpack.config.js with error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/jennifer/Dev/cypress-13-component-tests-slowdown/react-ts-cypress-13/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at loadWebpackConfig (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:70:15)
    at createReactAppHandler (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/createReactAppHandler.js:18:27)
    at getPreset (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:86:70)
    at Function.devServer.create (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:111:67)
    at /Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:26:40
    at new Promise (<anonymous>)
    at devServer (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:24:12)
    at Object.handler (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:166:24)
    at RunPlugins.invoke (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:183:25)
    at /Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/dev-server.js:18:8)
    at RunPlugins.execute (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:155:26)
    at EventEmitter.<anonymous> (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:26)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/jennifer/Library/Caches/Cypress/13.3.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
error Command failed with exit code 1.
```

**Comment by denis-domanskii** [comment]
@jennifer-shehane please try this repo: https://github.com/DeniDoman/cypress-13-ct-slowdown . 

I have 15% slowdown here. It based on https://github.com/cypress-io/cypress-component-testing-apps repo, without any infrastructure changes. 

My prod tests (sadly I can't share the code) slowdown is more than 30% (800 tests, 8 min -> 12 min).

**Comment by mateustalles** [comment]
Im having the same issue, In my case, e2es are 100% slower :/

**Comment by Benjamin-Re** [comment]
The same here. Cypress 13 is consistently 1 minute slower than Cypress 11. Maybe there is a new property that I have to set to false?

**Comment by jennifer-shehane** [comment]
We've made lots of improvements to v13 performance. Please try the most recent version. If you have an example that still runs slower, please provide the tests we can run to check.
