### ISSUE TITLE
No tests found. Cypress could not detect tests in this file.

### ISSUE THREAD

**Issue by zainsadaqat** [cypress-io/cypress#28191]
### Current behavior

Initially, it was showing error on expect and then I read documentation and install Chai and @types/Mocha to use describe and expect. After running `npx cypress open` command it's showing a list of error messages with heading no tests found.
<img width="1373" alt="Screenshot 2023-11-01 at 1 09 02 AM" src="https://github.com/cypress-io/cypress/assets/83048208/2b67881a-6189-4ff7-8773-84e13597748d">

### Desired behavior

It should not show any errors on describe, it and expect and detect my test files on the GUI

### Test code to reproduce

Initially, it was showing error on expect and then I read documentation and install Chai and @types/Mocha to use describe and expect. After running `npx cypress open` command it's showing a list of error messages with heading no tests found.
```js
import { expect } from 'chai';

describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true);
  });
});
```
when I remove expect import then it starts showing the tests results but shows error (red underline) on expect.
### Cypress Version

13.4.0

### Node version

20.9.0

### Operating System

macOS 13

### Debug Logs

```shell
Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'process/browser.js' in '/Users/zain/Desktop/property-management/node_modules/loupe'

Cannot read properties of undefined (reading 'module')
    at Watching.handle [as handler] (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:303:9
    at Hook.eval [as callAsync] (eval at create (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:299:28)
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:191:22
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:714:8)
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:802:19
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/zain/Library/Caches/Cypress/13.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

**Comment by jennifer-shehane** [comment]
You don't need to import chai in order to run Cypress. I would remove the import statement.

**Comment by pdhami007** [comment]
When I removed the import files it worked for me. Thanks!
