### ISSUE TITLE
3.1.1 -> 3.1.2 breaks click()

### ISSUE THREAD

**Issue by misoguy** [cypress-io/cypress#2820]
### Current behavior:
click() fails with the following error
related to https://github.com/kentcdodds/cypress-testing-library/pull/25

```
CypressError: cy.click() failed because it requires a DOM element.

The subject received was:

  > [<button>, <button>]

The previous command that ran was:

  > cy.then()
      at Object.cypressErr (http://localhost:13370/__cypress/runner/cypress_runner.js:63008:11)
      at Object.throwErr (http://localhost:13370/__cypress/runner/cypress_runner.js:62973:18)
      at Object.throwErrByPath (http://localhost:13370/__cypress/runner/cypress_runner.js:63000:17)
      at ensureElement (http://localhost:13370/__cypress/runner/cypress_runner.js:56011:21)
      at validateType (http://localhost:13370/__cypress/runner/cypress_runner.js:55897:16)
      at Object.ensureSubjectByType (http://localhost:13370/__cypress/runner/cypress_runner.js:55919:9)
      at pushSubjectAndValidate (http://localhost:13370/__cypress/runner/cypress_runner.js:58778:15)
      at Context.<anonymous> (http://localhost:13370/__cypress/runner/cypress_runner.js:58940:18)
      at http://localhost:13370/__cypress/runner/cypress_runner.js:58649:33
      at tryCatcher (http://localhost:13370/__cypress/runner/cypress_runner.js:124249:23)
      at Promise._settlePromiseFromHandler (http://localhost:13370/__cypress/runner/cypress_runner.js:122267:31)
      at Promise._settlePromise (http://localhost:13370/__cypress/runner/cypress_runner.js:122324:18)
      at Promise._settlePromiseCtx (http://localhost:13370/__cypress/runner/cypress_runner.js:122361:10)
      at Async._drainQueue (http://localhost:13370/__cypress/runner/cypress_runner.js:119178:12)
      at Async._drainQueues (http://localhost:13370/__cypress/runner/cypress_runner.js:119183:10)
      at Async.drainQueues (http://localhost:13370/__cypress/runner/cypress_runner.js:119057:14)
```
### Desired behavior:
click() to work. (works on 3.1.1)

### Steps to reproduce:
clone https://github.com/kentcdodds/cypress-testing-library
run `npm setup`
confirm test fails.
run `npm install cypress@3.1.1`
run `npm run test:cypress:run`
confirm test passes

### Versions
cypress: 3.1.2

**Comment by misoguy** [comment]
I'd like to resolve this if someone could point me to the right direction :)

**Comment by Bkucera** [comment]
@misoguy this doesn't seem like click is broken, but the command before the `.click` that yielded `[button, button]`

**Comment by Bkucera** [comment]
It appears that `cy.wrap` no longer works for dom element arrays. A bug on our end for sure

**Comment by misoguy** [comment]
@Bkucera If the difficulty to fix this is somewhat easy, could I try it?

**Comment by Bkucera** [comment]
@misoguy this is high priority on our end. We'll have a fix soon, but thank you!

**Comment by misoguy** [comment]
Understood 😄 Hope to have a fix soon 👍

**Comment by egucciar** [comment]
I have a feeling this also fixed a regression to my custom commands which yielded jquery arrays which stopped working in 3.1.2, but was working again in 3.1.3. Though i didnt use `cy.wrap` i suspect the underlying mechanism was the same, If so then thank you!

**Comment by Bkucera** [comment]
@egucciar yes, you are correct this would have broken any command who's subject was a n element array
