### ISSUE TITLE
cy.task() must only be invoked from the spec file or support file.

### ISSUE THREAD

**Issue by SuprunO** [cypress-io/cypress#28413]
### Current behavior

When I'm getting credentials from DB, the Cypress run fails with ERROR:
```
Error: CypressError: 
cy.task()` must only be invoked from the spec file or support file.

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
    at <unknown> (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:135599:72)
    at tryCatcher (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1697:18)
    at <unknown> (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:2392:25)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:1239:17)
    at Promise._passThrough (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:4110:17)
    at Promise.lastly.Promise.finally (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:4119:17)
    at Object.onRunnableRun (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:163620:53)
    at $Cypress.action (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:41031:28)
    at Runnable.run (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:145932:13)
    at next (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:155993:10)
    at <unknown> (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:156037:5)
    at timeslice (https://creditcube.qa.creditsense.ai/__cypress/runner/cypress_runner.js:146272:27)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/WSAPISuite/myProfileEmailVerification-CRP-3739.cy.js:21:5)`
```
### Desired behavior

Cypress should get credentials from DB

### Test code to reproduce
In **cypress.config.js**
```js
function readFromDB({ dbConfig, sql }) {
        return new Promise((resolve, reject) => {
          const client = new pg.Client(dbConfig);
          client
            .connect()
            .then(() => {
              client
                .query(sql)
                .then((response) => {
                  client.end();
                  resolve(response);
                })
                .catch(reject);
            })
            .catch(reject);
        });
      }
```
```js
on("task", {
        readFromDB,
        getCredentials({ config, sql }) {
          return new Promise((resolve, reject) => {
            readFromDB({
              dbConfig: config,
              sql,
            })
              .then((result) => {
                const credentials = result.rows[0];
                resolve(credentials);
              })
              .catch((error) => {
                reject(error);
              });
          });
        },
      });
```

**In test:**
```js
cy.task("getCredentials", {
    config: credQA_DBConfig,
    sql: DBRequestsBuilder.selectByEmail(
      "crpCredentials",
      "xxxxxxxxxxxxxxxx"
    ),
  }).then((CRPCredentials) => {
 cy.APILogin(APIUrl, CRPCredentials.userLogin, CRPCredentials.userHash);
})
```

### Cypress Version

13.5.0

### Node version

18.14.1

### Operating System

Ubuntu 20

**Comment by jennifer-shehane** [comment]
@SuprunO We'll look into this. Thanks for reporting

**Comment by SuprunO** [comment]
Still an issue in v 13.6.1 with all the tasks 
![Screenshot from 2023-12-07 18-34-56](https://github.com/cypress-io/cypress/assets/13238622/35c8b4f4-371d-4253-9333-af1b964b0b38)
