### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module ... not supported

### ISSUE THREAD

**Issue by coindegen** [cypress-io/cypress#28432]
### Current behavior

Hi, when I run my tests I see this error:

```shell
$ DEBUG=cypress* npm run test:e2e:dev

> test:e2e:dev
> start-server-and-test dev http://localhost:3000 "npx cypress open"

1: starting server using command "npm run dev"
and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
running tests using command "npx cypress open"


> dev
> cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev

🔶 Mock server running

 💿  remix dev

[info] building...
[info] built (1s)

/Users/madhava/Sites/guminc/uploader/build/index.js:157
var import_node3 = require("@remix-run/node"), import_react4 = require("@remix-run/react"), import_chains = require("@wagmi/chains"), import_ethereum = require("@web3modal/ethereum"), import_react5 = require("@web3modal/react"), import_react6 = require("react"), import_wagmi = require("wagmi");
                                                                                                                                                        ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/madhava/Sites/guminc/uploader/node_modules/@web3modal/ethereum/dist/index.es.js from /Users/madhava/Sites/guminc/uploader/build/index.js not supported.
Instead change the require of index.es.js in /Users/madhava/Sites/guminc/uploader/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/madhava/Sites/guminc/uploader/build/index.js:157:153)
Error: Timed out waiting for: http://localhost:3000
    at /Users/madhava/Sites/guminc/uploader/node_modules/wait-on/lib/wait-on.js:131:31
    at doInnerSub (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at AsyncAction.work (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
    at AsyncAction._execute (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:79:18)
    at AsyncAction.execute (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:67:26)
    at AsyncScheduler.flush (/Users/madhava/Sites/guminc/uploader/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:38:33)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```
    
The repo is private but here are some relevant config files: https://gist.github.com/coindegen/85a2c24ad045a4b82ebc5dbb0a3f0dd1

In my root tsconfig.json (https://gist.githubusercontent.com/coindegen/85a2c24ad045a4b82ebc5dbb0a3f0dd1/raw/1d4495b7effa8e9e013af2c5bea8b4a0c0603e59/tsconfig.json), if I change from:

```
    "module": "ES2022",
    "moduleResolution": "Bundler",
```

to this: 

```
    "module": "CommonJS",
    "moduleResolution": "node",
```

the error goes away.

One of my packages needs `Bundler` so I'm hoping I can make this work. 

### Desired behavior

I want to `npx cypress open` without any errors

### Test code to reproduce

Also, I'm running tests in CI like this:
```
    "start:mocks": "binode --require ./mocks -- @remix-run/serve:remix-serve build",
```

and seeing this error in Github actions: 
```
Error: Directory import '/home/runner/work/uploader/uploader/build' is not supported resolving ES modules imported from /home/runner/work/uploader/uploader/node_modules/@remix-run/serve/dist/cli.js
Did you mean to import /home/runner/work/uploader/uploader/build/index.js?
```

Is that related to this tsconfig setting?

```
    "allowImportingTsExtensions": true,
```
    
(more: https://gist.githubusercontent.com/coindegen/85a2c24ad045a4b82ebc5dbb0a3f0dd1/raw/9e74f9a2a0539a4fb6f4cf5d5556b925f457a575/github-action-logs.txt)

### Cypress Version

^12.10.0

### Node version

v18.18.2

### Operating System

macOS 14.1.1

### Debug Logs

```shell
see above
```

### Other

This issue looks similar to this older one that was patched in Cypress 10: https://github.com/cypress-io/cypress/issues/22038

My project is a Remix site, loosely based on this: https://github.com/remix-run/indie-stack

**Comment by coindegen** [comment]
Update: I managed to fix this issue:

```
Error: Directory import '/home/runner/work/uploader/uploader/build' is not supported resolving ES modules imported from /home/runner/work/uploader/uploader/node_modules/@remix-run/serve/dist/cli.js
Did you mean to import /home/runner/work/uploader/uploader/build/index.js?
```

This had nothing to do with Cypress, it was a Remix problem fixed by following this: https://github.com/remix-run/remix/discussions/7586

Only issue at present is this:

```
waiting on "http://localhost:8811" with timeout of 60 seconds
/opt/hostedtoolcache/node/18.18.2/x64/bin/npm run start:mocks

> start:mocks
> binode --require ./mocks -- @remix-run/serve:remix-serve ./build/index.js

🔶 Mock server running
[remix-serve] http://localhost:8811 (http://10.1.0.6:8811)
GET / 200 - - 224.752 ms

DevTools listening on ws://127.0.0.1:38393/devtools/browser/78911662-2c6b-48f0-aa88-96cd27fe5c4b
[3004:1201/141008.085917:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Your configFile is invalid: /home/runner/work/uploader/uploader/cypress.config.ts

It threw an error when required, check the stack trace below:

TSError: ⨯ Unable to compile TypeScript:
error TS5095: Option 'bundler' can only be used when 'module' is set to 'es2015' or later.

    at createTSError (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:311:16)
    at reportTSError (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:314:23)
    at /home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:686:17
    at Object.compile (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:743:35)
    at Module.m._compile (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:8[56](https://github.com/guminc/uploader/actions/runs/7061059328/job/19221920756?pr=195#step:8:57):36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:8[59](https://github.com/guminc/uploader/actions/runs/7061059328/job/19221920756?pr=195#step:8:60):16)
    at Module.load (node:internal/modules/cjs/loader:10[76](https://github.com/guminc/uploader/actions/runs/7061059328/job/19221920756?pr=195#step:8:77):32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at loadFile (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/home/runner/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
```

However, my module in my root tsconfig is set as follows:

```
    "module": "es2015",
    "moduleResolution": "Bundler",
```

**Comment by coindegen** [comment]
I was able to fix this by adding this `ts-node` object to my tsconfig:

```
  "ts-node": {
    "compilerOptions": {
      "module": "ESNext",
      "moduleResolution": "Node"
    }
  },
```

found the answer here in this related issue: https://github.com/cypress-io/cypress/issues/27731

**Comment by Klencodes** [comment]
adding this to your package.json should resolve the issue:

"resolutions": {
    "string-width": "4.2.3"
 }
