### ISSUE TITLE
Workflow "Handle Issue/PR Comment Workflow" fails (reading 'id')

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#28479]
### Current behavior

[.github/workflows/triage_handle_new_comments.yml](https://github.com/cypress-io/cypress/blob/develop/.github/workflows/triage_handle_new_comments.yml) fails with

Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')

see [Workflow runs](https://github.com/cypress-io/cypress/actions/workflows/triage_handle_new_comments.yml)

for instance

https://github.com/cypress-io/cypress/actions/runs/7128022489/job/19409163189

### Desired behavior

Adding a comment to an [issue](https://github.com/cypress-io/cypress/issues) or [PR](https://github.com/cypress-io/cypress/pulls)  should not cause an error report by GitHub.

### Test code to reproduce

As a non-org member add a comment to any [issue](https://github.com/cypress-io/cypress/issues) or [PR](https://github.com/cypress-io/cypress/pulls) in this repository.

### Cypress Version

N/A

### Node version

N/A

### Operating System

N/A

### Debug Logs

```shell
Run actions/github-script@v6
  with:
    github-token: ***
    script: const script = require('./scripts/triage/comment_workflow.js')
  await script.handleComment(github, context);
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,422
not from an org member
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:75
    at Array.find (<anonymous>)
    at Object.handleComment (/home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:4:1)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:20)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')
```

**Comment by MikeMcC399** [comment]
Add comment to this issue.

Edit: caused the workflow error https://github.com/cypress-io/cypress/actions/runs/7128982107

**Comment by jennifer-shehane** [comment]
Yah I probably broke it with my recent changes. Let me take a look.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Now it's a different error message:

```text
Run actions/github-script@v6
  with:
    github-token: ***
    script: const script = require('./scripts/triage/comment_workflow.js')
  await script.handleComment(github, context);
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,4[2](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:2)2
not from an org member
ReferenceError: projectId is not defined
    at /home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:8[3](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:3)
    at Array.find (<anonymous>)
    at Object.handleComment (/home/runner/work/cypress/cypress/scripts/triage/comment_workflow.js:115:[4](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:4)7)
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:5))
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v[6](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:6)/dist/index.js:15[14](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:15)3:16), <anonymous>:4:1)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:[15](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:16)236:[20](https://github.com/cypress-io/cypress/actions/runs/7151287111/job/19475445743#step:4:21))
Error: Unhandled error: ReferenceError: projectId is not defined

```

**Comment by MikeMcC399** [comment]
- See #28491 for follow-on issue
