### ISSUE TITLE
Getting errors on CI after upgrading to newest nextjs and cypress versions

### ISSUE THREAD

**Issue by ckruppe** [cypress-io/cypress#28534]
### Current behavior

Running tests on Github Actions with "cypress-io/github-action@v5" i get this error:

DevTools listening on ws://127.0.0.1:38723/devtools/browser/47e7d8ea-66c6-45a9-ac36-564899c75b6f
[2347:1215/135257.537582:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
Your configFile threw an error from: cypress.config.ts

We stopped running your tests because your config file crashed.

Error: Failed to load "next/dist/build/webpack-config" with error: Headers is not defined
    at getNextJsPackages (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:43:15)
    at loadWebpackConfig (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:177:96)
    at nextHandler (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/helpers/nextHandler.js:12:33)
    at getPreset (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:92:56)
    at Function.devServer.create (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:111:67)
    at /home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:26:40
    at new Promise (<anonymous>)
    at devServer (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-dev-server/dist/devServer.js:24:12)
    at Object.handler (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:166:24)
    at invoke (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:185:18)
    at /home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/bluebird/js/release/method.js:[39](https://github.com/nfqde/nextjs-typescript-template/actions/runs/7222686681/job/19680772213#step:6:40):29)
    at Object.wrapChildPromise (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
    at Object.wrap (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/dev-server.js:18:8)
    at RunPlugins.execute (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:155:26)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:[48](https://github.com/nfqde/nextjs-typescript-template/actions/runs/7222686681/job/19680772213#step:6:49)9:12)
    at process.<anonymous> (/home/runner/.cache/Cypress/13.6.1/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:[51](https://github.com/nfqde/nextjs-typescript-template/actions/runs/7222686681/job/19680772213#step:6:52)3:28)
    at process.emit (node:domain:489:12)

Locally it works.

### Desired behavior

To have it run through as it does on my local maschine.

### Test code to reproduce

Here is my cypress config:

import coverage from '@cypress/code-coverage/task';
import {loadEnvConfig} from '@next/env';
import {defineConfig} from 'cypress';

import resetDB from './cypress/tasks/resetDB';
import seedDB from './cypress/tasks/seedDB';

const {combinedEnv} = loadEnvConfig(process.cwd());

export default defineConfig({
    component: {
        devServer: {
            bundler: 'webpack',
            framework: 'next'
        },
        reporter: 'mochawesome',
        reporterOptions: {
            html: false,
            json: true,
            overwrite: false,
            reportDir: 'cypress/reports'
        },
        video: false,
        /**
         * Sets up plugins and so on.
         *
         * @param on     Cypress event handler.
         * @param config Cypress configuration.
         * @returns Cypress configuration.
         */
        setupNodeEvents(on, config) {
            coverage(on, config);

            return config;
        }
    },
    e2e: {
        baseUrl: 'http://localhost:3000',
        retries: {runMode: 3},
        screenshotOnRunFailure: false,
        video: false,
        viewportHeight: 1080,
        viewportWidth: 1920,
        /**
         * Sets up plugins and so on.
         *
         * @param on     Cypress event handler.
         * @param config Cypress configuration.
         */
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        setupNodeEvents(on, config) {
            on('task', {
                resetDB,
                seedDB
            });
        }
    },
    env: {
        ...combinedEnv,
        codeCoverage: {exclude: ['cypress/**/*.*']}
    },
    video: false
});

### Cypress Version

13.6.1

### Node version

20.10.0

### Operating System

Ubuntu 22.04.3

**Comment by ckruppe** [comment]
Have now looked into it and it seems that the action itself was at fault. After upgrading to v6 its working again.
