### ISSUE TITLE
Webpack Compilation Error when using Lighthouse in Cypress

### ISSUE THREAD

**Issue by davzhardy** [cypress-io/cypress#28750]
### Current behavior

When trying to run the latest version of lighthouse in the latest version of Cypress, a webpack compilation error is received. 

Screenshot: 
<img width="1497" alt="image" src="https://github.com/cypress-io/cypress/assets/23018368/8d2c08e1-af54-4651-9aa3-9ba29f0493b7">

Full error:
```
Error: Webpack Compilation Error
export 'urlToHttpOptions' (imported as 'urlToHttpOptions') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)

export 'URL' (imported as 'URL') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
    at Watching.handle [as handler] (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:303:9
    at Hook.eval [as callAsync] (eval at create (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:299:28)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:191:22
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:714:8)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:802:19
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)

```

### Desired behavior

It should compile without any errors

### Test code to reproduce

Failing test repo: https://github.com/davzhardy/cypress-test-tiny/tree/lighthouse-problem

### Cypress Version

13.6.3

### Node version

v20.6.1

### Operating System

macOS 14.1.1

### Debug Logs

```shell
GET /__cypress/iframes/cypress%2Fe2e%2Fspec.cy.js?browserFamily=chromium 200 1.925 ms - -
  cypress:server:controllers:spec request for { spec: 'cypress/support/e2e.js' } +22s
  cypress:server:preprocessor getting file cypress/support/e2e.js +22s
  cypress:server:preprocessor getFile /Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/support/e2e.js +0ms
  cypress:lifecycle:EventRegistrar execute plugin event 'file:preprocessor' Node 'v18.15.0' with args: EventEmitter { _events: [Object: null prototype] { rerun: [Function (anonymous)] }, _eventsCount: 1, _maxListeners: undefined, filePath: '/Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/support/e2e.js', shouldWatch: true, outputPath: '/Users/davidhardy/Library/Application Support/Cypress/cy/production/projects/cypress-test-tiny-873a834623cad091f98dbfb980f09cdd/bundles/cypress/support/e2e.js', [Symbol(kCapture)]: false } undefined undefined +22s
  cypress:lifecycle:ProjectConfigManager call event file:preprocessor for invocation id inv12 +22s
  cypress:server:controllers:spec request for { spec: 'cypress/e2e/spec.cy.js' } +1ms
  cypress:server:preprocessor getting file cypress/e2e/spec.cy.js +1ms
  cypress:server:preprocessor getFile /Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/e2e/spec.cy.js +0ms
  cypress:lifecycle:EventRegistrar execute plugin event 'file:preprocessor' Node 'v18.15.0' with args: EventEmitter { _events: [Object: null prototype] { rerun: [Function (anonymous)] }, _eventsCount: 1, _maxListeners: undefined, filePath: '/Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/e2e/spec.cy.js', shouldWatch: true, outputPath: '/Users/davidhardy/Library/Application Support/Cypress/cy/production/projects/cypress-test-tiny-873a834623cad091f98dbfb980f09cdd/bundles/cypress/e2e/spec.cy.js', [Symbol(kCapture)]: false } undefined undefined +1ms
  cypress:lifecycle:ProjectConfigManager call event file:preprocessor for invocation id inv13 +1ms
  cypress:lifecycle:child:RunPlugins:81183 execute plugin event: file:preprocessor ({ invocationId: 'inv12', eventId: 3 }) +22s
  cypress:webpack user options: { webpackOptions: { mode: 'development', node: { global: true, __filename: true, __dirname: true }, module: { rules: [Array] }, plugins: [ [ProvidePlugin], [LimitChunkCountPlugin], [LimitChunkCountPlugin] ], resolve: { extensions: [Array], fallback: [Object], plugins: [] }, entry: [ '/Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/support/e2e.js' ], output: { publicPath: '', path: '/Users/davidhardy/Library/Application Support/Cypress/cy/production/projects/cypress-test-tiny-873a834623cad091f98dbfb980f09cdd/bundles/cypress/support', filename: 'e2e.js' }, devtool: 'inline-source-map' } } +22s
  cypress:webpack get /Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/support/e2e.js +0ms
  cypress:webpack already have bundle for /Users/davidhardy/Documents/GitHub/cypress-test-tiny/cypress/support/e2e.js +0ms
  cypress:lifecycle:ProjectConfigManager promise rejected for id inv12 ':' Error: Webpack Compilation Error
export 'urlToHttpOptions' (imported as 'urlToHttpOptions') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)

export 'URL' (imported as 'URL') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
    at Watching.handle [as handler] (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:303:9
    at Hook.eval [as callAsync] (eval at create (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/davidhardy/Library/Caches/Webpack Compilation Error
export 'urlToHttpOptions' (imported as 'urlToHttpOptions') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)

export 'URL' (imported as 'URL') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:299:28)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Watching.js:191:22
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:714:8)
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:802:19
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/davidhardy/Library/Caches/Cypress/13.6.3/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) +3ms
  cypress:server:controllers:spec preprocessor error for spec 'cypress/support/e2e.js': Error: Webpack Compilation Error
export 'urlToHttpOptions' (imported as 'urlToHttpOptions') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
```

**Comment by 28development** [comment]
@davzhardy how did you solve this, facing the same issue.

**Comment by mildfuzz** [comment]
Also having the same issue. This is the only google result.
