### ISSUE TITLE
Opening the same bootstrap modal twice does not work

### ISSUE THREAD

**Issue by blaszczakphoto** [cypress-io/cypress#2877]
### Current behavior:
I have following test:
```javascript
cy.visit('https://getbootstrap.com/docs/4.1/components/modal/')

cy.get("body > div > div > main > div:nth-child(20) > button").as('open_modal_btn')
cy.get('#exampleModalLive > div > div > div.modal-header > button span').as('close_modal_btn')

cy.get('@open_modal_btn').scrollIntoView().click()

cy.get('@close_modal_btn').click()

cy.get('@open_modal_btn').scrollIntoView().click()
cy.get('@close_modal_btn').click()
```
It should:
1. open bootstrap modal documentation, 
2. click button to open sample modal
3. close the sample modal
4. again click button to open sample modal
5. again close the sample modal

But on 4th step it doesn't open the modal. The cypress says:

> CypressError: Timed out retrying: cy.click() failed because this element is not visible:
> 
> <span aria-hidden="true">×</span>
> 
> This element '<span>' is not visible because its parent '<div#exampleModalLive.modal.fade>' has CSS property: 'display: none'
> 
> Fix this problem, or use {force: true} to disable error checking.
> 
> https://on.cypress.io/element-cannot-be-interacted-with

And it is true, because the modal didn't appear second time.

### Desired behavior:
I think this might be a bug in cypress. The modal should open normally the second time.

### Workaround
I noticed that if I add cy.wait in 2 places it will work:
```js
cy.visit('https://getbootstrap.com/docs/4.1/components/modal/')

cy.get("body > div > div > main > div:nth-child(20) > button").as('open_modal_btn')
cy.get('#exampleModalLive > div > div > div.modal-header > button span').as('close_modal_btn')
const number_of_wait = 200;

cy.get('@open_modal_btn').scrollIntoView().click()

cy.wait(number_of_wait)

cy.get('@close_modal_btn').click()

cy.wait(number_of_wait)

cy.get('@open_modal_btn').scrollIntoView().click()
cy.get('@close_modal_btn').click()
```

### Steps to reproduce:
I created repo with the [failing test and workaround](https://github.com/blaszczakphoto/cypress-test-tiny/blob/master/cypress/integration/spec.js):
https://github.com/blaszczakphoto/cypress-test-tiny

### Versions
- Cypress version: 3.1.2
- Operating system: Mac OS Mojave, 10.14.1
- Browser: Chrome Version 70.0.3538.110

**Comment by jennifer-shehane** [comment]
We typically recommend sprinkling in assertions within your test to assert that the state of the DOM is ready to proceed. In a test like opening and closing a modal, I may add a check to ensure that the modal is visible when clicking to launch the modal and that the modal is not visible after clicking to close the modal. Otherwise, Cypress would click "Launch" "Close" "Launch" immediately one right after the other.

Something like this:

```js
it('cy.hash() - get the current URL hash', () => {
  cy.visit('https://getbootstrap.com/docs/4.1/components/modal/')

  cy.get('body > div > div > main > div:nth-child(20) > button').as('open_modal_btn')
  cy.get('#exampleModalLive > div > div > div.modal-header > button span').as('close_modal_btn')

  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('.modal-title').should('be.visible')

  cy.get('@close_modal_btn').click()
  cy.get('.modal-title').should('not.be.visible')

  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('.modal-title').should('be.visible')

  cy.get('@close_modal_btn').click()
})
```

**Comment by blaszczakphoto** [comment]
I tried your code @jennifer-shehane, but unfortunately it produces similar error.
![image](https://user-images.githubusercontent.com/5549011/49438080-89f1b980-f7bd-11e8-824e-ba25b09a553e.png)
Does your snippet work on your machine?

**Comment by jennifer-shehane** [comment]
Oh, sorry, I didn't run it 🙈 

I think you need to be more specific with the `.modal-title` because it's trying to verify that all 9 titles are visible. 

```js
it('cy.hash() - get the current URL hash', () => {
  cy.visit('https://getbootstrap.com/docs/4.1/components/modal/')

  cy.get('body > div > div > main > div:nth-child(20) > button').as('open_modal_btn')
  cy.get('#exampleModalLive > div > div > div.modal-header > button span').as('close_modal_btn')

  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('#exampleModalLiveLabel').should('be.visible')

  cy.get('@close_modal_btn').click()
  cy.get('#exampleModalLiveLabel').should('not.be.visible')

  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('#exampleModalLiveLabel').should('be.visible')

  cy.get('@close_modal_btn').click()
  cy.get('#exampleModalLiveLabel').should('not.be.visible')
})
```

**Comment by blaszczakphoto** [comment]
I've just tried running your test with opened test runner and it apparently worked, **BUT** when I run it without the test runner it fails.

Here is the spec (copy/pasted your code @jennifer-shehane ) I tried to run: https://github.com/blaszczakphoto/cypress-test-tiny/blob/master/cypress/integration/another_fixed_version_spec.js

The command I used to run the spec:
`npx cypress run  --spec cypress/integration/another_fixed_version_spec.js`

And error for above command:
```
1)  cy.hash() - get the current URL hash:
     CypressError: Timed out retrying: expected '<h5#exampleModalLiveLabel.modal-title>' not to be 'visible'
      at Object.cypressErr (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63008:11)
      ....
      ....
```
---
and:
`npx cypress run -b chrome --spec cypress/integration/another_fixed_version_spec.js`

And error for above command:
```
cy.hash() - get the current URL hash:
     CypressError: Timed out retrying: expected '<h5#exampleModalLiveLabel.modal-title>' to be 'visible'

This element '<h5#exampleModalLiveLabel.modal-title>' is not visible because its parent '<div#exampleModalLive.modal.fade>' has CSS property: 'display: none'
      at Object.cypressErr (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63008:11)
      at Object.throwErr (https://getbootstrap.com/__cypress/runner/cypress_runner.js:62973:18)
      at Object.throwErrByPath (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63000:17)
      at retry (https://getbootstrap.com/__cypress/runner/cypress_runner.js:56611:16)
      at https://getbootstrap.com/__cypress/runner/cypress_runner.js:48721:18
      at tryCatcher (https://getbootstrap.com/__cypress/runner/cypress_runner.js:124249:23)
      at Promise._settlePromiseFromHandler (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122267:31)
      at Promise._settlePromise (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122324:18)
      at Promise._settlePromise0 (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122369:10)
      at Promise._settlePromises (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122444:18)
      at Async._drainQueue (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119173:16)
      at Async._drainQueues (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119183:10)
      at Async.drainQueues (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119057:14)
```

**Comment by jennifer-shehane** [comment]
The test runner when run using `cypress run` runs in Electron, and an older version of Chrome. This may be the reason for failure, or there may be some variability in the speed in which things are run. Do you have the screenshot or video of the test failure during `cypress run`? That should give some better insights into the issue.

**Comment by blaszczakphoto** [comment]
I just updated cypress to newest version: 
```
❯ npx cypress -v
Cypress package version: 3.1.4
Cypress binary version: 3.1.4
```
And it once worked in the visual test runner and in the command line runner.

So I thought that new version of cypress fixed something that was causing this issue.

But I when I run it second time it failed in visual test runner and in command line. I tried to run it few more times and it was failing randomly.

The failing test stacktrace:
```bash
❯ npx cypress run --spec cypress/integration/another_fixed_version_spec.js

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.4                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (another_fixed_version_spec.js)                                            │
  │ Searched:   cypress/integration/another_fixed_version_spec.js                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running: another_fixed_version_spec.js...                                                (1 of 1)


  1) cy.hash() - get the current URL hash

  0 passing (17s)
  1 failing

  1)  cy.hash() - get the current URL hash:
     CypressError: Timed out retrying: expected '<h5#exampleModalLiveLabel.modal-title>' to be 'visible'

This element '<h5#exampleModalLiveLabel.modal-title>' is not visible because its parent '<div#exampleModalLive.modal.fade>' has CSS property: 'display: none'
      at Object.cypressErr (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63091:11)
      at Object.throwErr (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63056:18)
      at Object.throwErrByPath (https://getbootstrap.com/__cypress/runner/cypress_runner.js:63083:17)
      at retry (https://getbootstrap.com/__cypress/runner/cypress_runner.js:56628:16)
      at https://getbootstrap.com/__cypress/runner/cypress_runner.js:48746:18
      at tryCatcher (https://getbootstrap.com/__cypress/runner/cypress_runner.js:124905:23)
      at Promise._settlePromiseFromHandler (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122923:31)
      at Promise._settlePromise (https://getbootstrap.com/__cypress/runner/cypress_runner.js:122980:18)
      at Promise._settlePromise0 (https://getbootstrap.com/__cypress/runner/cypress_runner.js:123025:10)
      at Promise._settlePromises (https://getbootstrap.com/__cypress/runner/cypress_runner.js:123100:18)
      at Async._drainQueue (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119829:16)
      at Async._drainQueues (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119839:10)
      at Async.drainQueues (https://getbootstrap.com/__cypress/runner/cypress_runner.js:119713:14)
      at <anonymous>




  (Results)

  ┌─────────────────────────────────────────────┐
  │ Tests:        1                             │
  │ Passing:      0                             │
  │ Failing:      1                             │
  │ Pending:      0                             │
  │ Skipped:      0                             │
  │ Screenshots:  1                             │
  │ Video:        true                          │
  │ Duration:     16 seconds                    │
  │ Spec Ran:     another_fixed_version_spec.js │
  └─────────────────────────────────────────────┘


  (Screenshots)

  - /Users/mariusz/Projects/JavaScript/cypress-test-tiny/cypress/screenshots/another_fixed_version_spec.js/cyhash() - get the current URL hash (failed).png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/mariusz/Projects/JavaScript/cypress-test-tiny/cypress/videos/another_fixed_version_spec.js.mp4 (4 seconds)


====================================================================================================

  (Run Finished)


      Spec                                                Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖ another_fixed_version_spec.js             00:16        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    1 of 1 failed (100%)                        00:16        1        -        1        -        -

```

The screenshot of failing test:
![cyhash - get the current url hash failed](https://user-images.githubusercontent.com/5549011/51965479-fd384480-2469-11e9-95d7-c0968e750bff.png)

The video of failing test:
https://youtu.be/qZu-9vYsoS0

**Comment by jennifer-shehane** [comment]
I wonder if this has anything to do with a recent blog post we published, involving the button's `click` event handler not being ready when it is clicked. 🤔 	https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

**Comment by jennifer-shehane** [comment]
I think this has to have something to do with the click event handlers not being ready. If I add an arbitrary wait before the click, it works. 

```js
it('cy.hash() - get the current URL hash', () => {
  cy.visit('https://getbootstrap.com/docs/4.1/components/modal/')

  cy.get('body > div > div > main > div:nth-child(20) > button').as('open_modal_btn')
  cy.get('#exampleModalLive > div > div > div.modal-header > button span').as('close_modal_btn')

  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('#exampleModalLiveLabel').should('be.visible')

  cy.wait(500)
  cy.get('@close_modal_btn').click()
  cy.get('#exampleModalLiveLabel').should('not.be.visible')

  cy.get('@open_modal_btn').scrollIntoView()
  cy.wait(500)
  cy.get('@open_modal_btn').scrollIntoView().click()
  cy.get('#exampleModalLiveLabel').should('be.visible')

  cy.get('@close_modal_btn').click()
  cy.get('#exampleModalLiveLabel').should('not.be.visible')
})
```

I'm going to close this as I don't see this being an issue with Cypress. I'd suggest reading this blog and guarding your tests with checks to ensure event handlers are ready before clicking an element. https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/ 

I don't see anything that Cypress could change in this situation that wouldn't add arbitrary waits to everyones test execution.
