### ISSUE TITLE
Cypress crashes when using cy.visit with % parameter in 13.6.1

### ISSUE THREAD

**Issue by irahov** [cypress-io/cypress#28801]
### Current behavior

The entire cypress window crashes when using 
   cy.visit(''/login/?any=%);

### Desired behavior

Cypress does not crash and navigates to that URL

### Test code to reproduce

cy.visit(''/login/?any=%);

### Cypress Version

13.6.1

### Node version

v14.20.1

### Operating System

macOS Sonoma 14.2.1

### Debug Logs

```shell
URI malformed
URIError: URI malformed
    at decodeURI (<anonymous>)
    at u.addPending (<embedded>:4454:27423)
    at A.addPendingBrowserPreRequest (<embedded>:4454:37977)
    at a.addPendingBrowserPreRequest (<embedded>:4454:38767)
    at Q.addBrowserPreRequest (<embedded>:4526:13193)
    at c.onBrowserPreRequest (<embedded>:4526:27079)
    at T.onNetworkRequestWillBeSent (<embedded>:4454:49453)
    at _.emit (node:events:513:28)
    at _._handleMessage (<embedded>:2466:580235)
    at A.<anonymous> (<embedded>:2466:579669)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:564853)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:545228)
    at g.getData (<embedded>:2466:544410)
    at g.startLoop (<embedded>:2466:541117)
    at g._write (<embedded>:2466:540472)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.H (<embedded>:2466:565539)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
URI malformed
URIError: URI malformed
    at decodeURI (<anonymous>)
    at u.get (<embedded>:4454:29289)
    at Object.getPreRequest (<embedded>:4454:36526)
    at Object.CorrelateBrowserPreRequest (<embedded>:4436:317350)
    at <embedded>:4454:34010
    at Promise.cancellationExecute [as _execute] (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:335:9)
    at Promise._resolveFromExecutor (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:79:10)
    at d (<embedded>:4454:32927)
    at Object.next (<embedded>:4454:33769)
    at Object.MaybeSimulateSecHeaders (<embedded>:4436:315953)
    at <embedded>:4454:34010
    at Promise.cancellationExecute [as _execute] (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:335:9)
    at Promise._resolveFromExecutor (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:79:10)
    at d (<embedded>:4454:32927)
    at Object.next (<embedded>:4454:33769)
    at Object.ExtractCypressMetadataHeaders (<embedded>:4436:315554)
    at <embedded>:4454:34010
    at Promise.cancellationExecute [as _execute] (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:335:9)
    at Promise._resolveFromExecutor (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:79:10)
    at d (<embedded>:4454:32927)
    at Object.next (<embedded>:4454:33769)
    at Object.LogRequest (<embedded>:4436:314743)
    at <embedded>:4454:34010
    at Promise.cancellationExecute [as _execute] (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/debuggability.js:335:9)
    at Promise._resolveFromExecutor (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/irahov/Library/Caches/Cypress/13.6.1/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:79:10)
    at d (<embedded>:4454:32927)
    at E (<embedded>:4454:34295)
    at A.handleHttpRequest (<embedded>:4454:37266)
    at a.handleHttpRequest (<embedded>:4454:39175)
    at <embedded>:4513:68505
    at i.handle_request (<embedded>:2701:1038)
    at d (<embedded>:2716:1285)
    at p.dispatch (<embedded>:2716:1307)
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3353
    at _ (<embedded>:2724:4350)
    at _ (<embedded>:2724:4544)
    at y.process_params (<embedded>:2724:4687)
    at h (<embedded>:2724:3296)
    at y.handle (<embedded>:2724:4188)
    at o (<embedded>:2724:1048)
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at i.handle_request (<embedded>:2701:1030)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2948:1731
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2525:2495
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2545:1156
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:4526:11174
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:4526:10849
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2732:330
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at <embedded>:2740:544
    at i.handle_request (<embedded>:2701:1038)
    at <embedded>:2724:3774
    at <embedded>:2724:3796
    at y.process_params (<embedded>:2724:4284)
    at h (<embedded>:2724:3296)
    at y.handle (<embedded>:2724:4188)
    at T.handle (<embedded>:2796:3475)
    at Server.e (<embedded>:2827:742)
    at Server.<anonymous> (<embedded>:4423:71058)
    at <embedded>:4526:13978
    at Array.map (<anonymous>)
    at Q._callRequestListeners (<embedded>:4526:13968)
    at Server.<anonymous> (<embedded>:4526:14118)
    at <embedded>:4526:13978
    at Array.map (<anonymous>)
    at Q._callRequestListeners (<embedded>:4526:13968)
    at Q.callListeners (<embedded>:4526:15879)
    at Object._onRequest (<embedded>:4423:124731)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1072:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:
```

### Other

This seems a regression in 13.6.1.
It was working in ^12.10.0

Similar bug #8356

**Comment by jennifer-shehane** [comment]
@irahov This was [fixed in 13.6.2](https://docs.cypress.io/guides/references/changelog#13-6-2). Please ensure you update to the latest version of Cypress before posting an issue.
