### ISSUE TITLE
Unable to use cy.FrameLoaded() within cy.origin

### ISSUE THREAD

**Issue by shastrisubramaniam** [cypress-io/cypress#28945]
### Current behavior

Get the following error 
```
TypeError
cy.frameLoaded is not a function
[cypress/e2e/Filter_Available_Appointments_By_Location.cy.js:26:8](https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__/#)

  24 |     today.setDate(today.getDate() + 1);
  25 |     const args = {practitioner:'Lloyd,Cristina',specialty:'General Practice',appointment_type:'Primary Care',appointment_reason: 'Feeling Sick',appointment_month:'February',appointment_date:today.toISOString().substring(0,10),frame_title: 'Filter By Location'}
> 26 |     cy.origin("https://ljlpuvgahc3e35hzyplv6sqf4u.apigateway.us-ashburn-1.oci.customer-oci.com",{args: args},({specialty,appointment_type, appointment_reason,appointment_month,appointment_date,frame_title}) => {  
     |        ^
  27 |       cy.get('.rw-PageHeader-title').should('have.text','Appointments');
  28 |       cy.get('#schedule_btn').click();
  29 |       cy.get('.rw-PageHeader-title').should('have.text','Scheduling Options');
```
### Desired behavior

Should work without issues

### Test code to reproduce
```js
it("Verify that filtering of Single Locations works as expected", () => {
    cy.PasLogin();
    let today= new Date();
    today.setDate(today.getDate() + 1);
    const args = {practitioner:'Lloyd,Cristina',specialty:'General Practice',appointment_type:'Primary Care',appointment_reason: 'Feeling Sick',appointment_month:'February',appointment_date:today.toISOString().substring(0,10),frame_title: 'Filter By Location'}
    cy.origin("https://ljlpuvgahc3e35hzyplv6sqf4u.apigateway.us-ashburn-1.oci.customer-oci.com",{args: args},({specialty,appointment_type, appointment_reason,appointment_month,appointment_date,frame_title}) => {  
      cy.get('.rw-PageHeader-title').should('have.text','Appointments');
      cy.get('#schedule_btn').click();
      cy.get('.rw-PageHeader-title').should('have.text','Scheduling Options');
      cy.get('[data-otel-label="FIND_CARE"]').click();
      cy.get('.rw-GP-ProcessTitle').should('have.text','Find Care');
      cy.get('[data-otel-label="START_FIND_CARE"]').click();
      cy.get('.rw-PageHeader-title').should('have.text','Search For Care');
      cy.get('#P150_SPECIALTY').click();
      cy.get(".a-PopupLOV-search").type(specialty).type('{enter}');
      cy.get('.u-Processing-spinner').should('not.exist');
      cy.get(".popup-lov-highlight").click(); 
      cy.get("#P150_APPOINTMENT_REASON").type(appointment_reason);
      cy.get("#P150_APPOINTMENT_TYPE").click();
      cy.get(".a-PopupLOV-search").last().type(appointment_type);
      cy.get(".a-PopupLOV-search").last().type('{enter}');
      cy.get('.u-Processing-spinner').should('not.exist');
      cy.get(".popup-lov-highlight").last().click();
      cy.get('[data-otel-label="SEARCH"]').click();
      cy.get('.rw-PageHeader-title').should('have.text','Choose a Provider');
      cy.get('#card1').click();
      cy.get('.rw-PageHeader-title').should('have.text','Select date and time');
      cy.get('#P144_START_DATE_input').click();
      cy.get('[aria-controls="P144_START_DATE_calendar"]').get('[title="Next Month"]').click();
      cy.get('#P144_START_DATE_month').select(appointment_month);
      cy.get('[data-date="'+ appointment_date+ '"]').click();
      cy.get('#appointments_Cards').should('not.have.text','No appointments available. Try changing your filters or the selected date.');
      cy.get('#filterButton').should('not.have.attr','style').as("display: none");
      cy.get('#filterButton').click();
      cy.get('.a-CardView-headerBody > br').invoke('text').as('available_locations');  
      cy.frameLoaded('[title="Filter By Location"]')
    }); 
 })
})
```
### Cypress Version

13.6.2

### Node version

v16.17.0

### Operating System

macOS Sonoma v 14.3

### Debug Logs

```shell
TypeError: cy.frameLoaded is not a function
    at  (webpack://newmillenium/./cypress/e2e/Filter_Available_Appointments_By_Location.cy.js:26:7)
    at __webpack_modules__</setRunnable/runnable.fn (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:138533:43)
    at callFn (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:157430:21)
    at __webpack_modules__</Runnable.prototype.run (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:157417:13)
    at __webpack_modules__</create/onRunnableRun (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:163341:30)
    at finallyHandler (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:4072:23)
    at tryCatcher (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1807:23)
    at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1519:31)
    at __webpack_modules__</module.exports/Promise.prototype._settlePromise (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1576:18)
    at __webpack_modules__</module.exports/Promise.prototype._settlePromise0 (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1621:10)
    at __webpack_modules__</module.exports/Promise.prototype._settlePromises (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1701:18)
    at _drainQueueStep (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:2407:12)
From previous event:
    at captureStackTrace (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:3919:23)
    at CapturedTrace (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:3811:22)
    at longStackTracesCaptureStackTrace (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:3486:19)
    at __webpack_modules__</module.exports/Promise.prototype._then (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:1239:17)
    at __webpack_modules__</module.exports/Promise.prototype._passThrough (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:4110:17)
    at __webpack_modules__</module.exports/Promise.prototype.finally (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:4119:17)
    at onRunnableRun (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:163324:46)
    at action (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:41042:28)
    at __webpack_modules__</patchRunnableRun/Runnable.prototype.run (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:145636:13)
    at __webpack_modules__</Runner.prototype.runTest (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155854:10)
    at __webpack_modules__</Runner.prototype.runTests/next (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155980:12)
    at next (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155763:14)
    at __webpack_modules__</Runner.prototype.hooks/next (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155773:11)
    at next (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155675:14)
    at __webpack_modules__</Runner.prototype.hook (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:155741:9)
    at timeslice (https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:145976:27) index-caf2649c.js:133767:13
    logError https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__/assets/index-caf2649c.js:133767
    addGlobalListeners https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__/assets/index-caf2649c.js:146111
    emit2 https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__/assets/index-caf2649c.js:139476
    listen https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:182343
    emit https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:146419
    emit https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:182406
    onPrint https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:198547
    _onPrintClick https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:198551
    initializer https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:198251
    executeAction https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:181048
    n https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:181048
    ca https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:245
    ja https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:246
    ka https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:246
    wa https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:248
    Aa https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:249
    ya https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:249
    Da https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:252
    Ad https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:315
    Gi https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:481
    Kb https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:270
    Dd https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:317
    Ii https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:482
    unstable_runWithPriority https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:537
    Ii https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:482
    Cd https://idcs-51dd0ec6c26a40d8b289a06a9c4bcedc.identity.oraclecloud.com/__cypress/runner/cypress_runner.js:316
```

**Comment by jennifer-shehane** [comment]
Where have you defined the custom `cy.frameLoaded` command? This isn’t a built in command included with Cypress.

**Comment by nikepol** [comment]
correct me if I am wrong, but in order to use custom commands in **cy.origin** you have to define **Cypress.require**
https://docs.cypress.io/api/cypress-api/require

**Comment by shastrisubramaniam** [comment]
That's right. I figured that out based on documentation and all is good. Issue can be closed.

**Comment by hamzabughunter** [comment]
@shastrisubramaniam can you plz elaborate, how you resolve this issue because I am unable to resolve it.

Getting the same issue that "cy.frameLoaded is not a function"

`cardPayment(){
        cy.fixture('paymentData').then((data)=>{
            cy.get(this.cardNumberField).should('be.visible').and('be.enabled').type(data.cardNumber);
            cy.get(this.cardMonthField).should('be.visible').and('be.enabled').type(data.cardMonth);
            cy.get(this.cardYearField).should('be.visible').and('be.enabled').type(data.cardYear);
            cy.get(this.cardCvcField).should('be.visible').and('be.enabled').type(data.cardCvc);

            cy.get(this.makePaymentButton).should('be.enabled').click()
            cy.origin(data.cardUrl, { args: { data, cardPaymentFrame: this.cardPaymentFrame, cardOtpField: this.cardOtpField, cardSubmitButton: this.cardSubmitButton} }, ({ data, cardPaymentFrame, cardOtpField, cardSubmitButton })=>{
                cy.visit("/silent/payer_authentication/hybrid?ccaAction=load", {timeout: 20000})
                console.log("NEW URL"+cy.url())
                cy.url().should('include', data.cardUrl)

                cy.frameLoaded(cardPaymentFrame)

                cy.iframe().find(cardOtpField).should('be.visible').and('be.enabled').type(data.cardOtp)
                cy.iframe().find(cardSubmitButton).should('be.enabled').click()
            })

        })
    }`
