### ISSUE TITLE
Error upon request

### ISSUE THREAD

**Issue by dudeNumber4** [cypress-io/cypress#2923]
### Current behavior:

Upon `cy.request` with a seemingly valid header, following is the stack trace of the error.  Note that changing the header key "content-type" to "ContentType" makes the error go away.  

```
TypeError: str.replace is not a function
    at Querystring.rfc3986 (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\lib\querystring.js:43:14)
    at Request.json (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:1293:30)
    at Request.init (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:406:10)
    at Request.RP$initInterceptor [as init] (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:127:8)
    at request (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\index.js:53:10)
    at C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\index.js:100:12
    at Object.create (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\lib\request.js:170:18)
    at C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\lib\request.js:364:26
    at tryCatcher (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### Desired behavior:

Network call made.  I realize now that "form":true is the accepted method of setting that content type; still minor bug.

Create this options object:
```js
const options = {
  "method": "POST",
  "url": "some valid url",
  "headers": {
    "Accept": "application/json",
    "content-type": "application/x-www-form-urlencoded"
  },
  "body": {
    "scope": "my_scope"
  }
};

cy.request(options).then // ...
```

### Versions

3.1.3

**Comment by jennifer-shehane** [comment]
I am able to verify this seems like a bug. 

**Reproducible example**

```js
it('throws an error', function () {
  cy.request({
    'method': 'POST',
    'url': 'https://jsonplaceholder.cypress.io/comments',
    'headers': {
      'Accept': 'application/json',
      'content-type': 'application/x-www-form-urlencoded',
    },
    'body': {
      'scope': 'my_scope',
    },
  })
})
```

**Comment by flotwig** [comment]
This `options` object also causes an exception when passed to the `request` library directly: https://runkit.com/embed/hewk0u53ebr6

The root of the issue seems to be that the `body` is not a string. `application/x-www-form-urlencoded` expects a urlencoded string to be passed as the `body`. If you wrap your `body` in `qs.stringify`, the request will work fine: https://runkit.com/flotwig/issue-2923-qs This will also fix the exception that arises within Cypress.

If you look at [the docs for `request` options](https://github.com/request/request#requestoptions-callback), you'll see the following definition for `body`, which lines up with what we're seeing here:

> body - entity body for PATCH, POST and PUT requests. Must be a Buffer, String or ReadStream. If json is true, then body must be a JSON-serializable object.

`request.coffee` probably needs to be updated to account for the edge case described in this issue and warn the user that something unexpected is going to happen.
