### ISSUE TITLE
Using Cypress.IO to to setData on CKeditor 4

### ISSUE THREAD

**Issue by godomainz** [cypress-io/cypress#29246]
### Current behavior

I'm using cypress to automate my project. I have CKeditor4. So I tried below code to type in CKEditor because type method in cypress is very SLOW

```
it('does work2', async() => {
        cy.visit('https://ckeditor.com/ckeditor-4/demo/')

        cy.get('#cke_1_contents iframe[title="Editor, ckdemoarticle"]').then(async(el)=>{
            const body = await el.contents().find("body")[0];
            // @ts-ignore
            const editor = body.ckeditorInstance;
            editor.setData("<p>'Typing some stuff'</p>")
        });
}
```
But I can see below error on console

```

Unhandled rejection TypeError: Cannot read properties of undefined (reading 'setData')  
at eval (https://ckeditor.com/__cypress/tests?p=cypress\e2e\test.cy.ts:75:36)  
 at step (https://ckeditor.com/__cypress/tests?p=cypress\e2e\test.cy.ts:43:23)   
 at Object.eval [as next] (https://ckeditor.com/__cypress/tests?p=cypress\e2e\test.cy.ts:24:53)    
at fulfilled (https://ckeditor.com/__cypress/tests?p=cypress\e2e\test.cy.ts:15:58)From previous event:    
at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://ckeditor.com/__cypress/runner/cypress_runner.js:3486:19)    
at Promise._then (https://ckeditor.com/__cypress/runner/cypress_runner.js:1239:17)
```

I realized `ckeditorInstance` is NOT available in CKEditor4.

Tried everything available in internet but couldn't find a solution in Cypress.IO.

So how to use `setData` method using cypress code

### Desired behavior

user should be able to call `setData()`

### Test code to reproduce

  ```
it('does work2', async() => {
        cy.visit('https://ckeditor.com/ckeditor-4/demo/')

        cy.get('#cke_1_contents iframe[title="Editor, ckdemoarticle"]').then(async(el)=>{
            const body = await el.contents().find("body")[0];
            // @ts-ignore
            const editor = body.ckeditorInstance;
            editor.setData("<p>'Typing some stuff'</p>")
        });
}
```

### Cypress Version

13.6.6

### Node version

v20.10.0

### Operating System

Windows 10 Pro 22H2 19045.4239

**Comment by someshver-pri** [comment]
On Drupal 10 Ckeditor 5 we can use the below code.

```js
cy.window().then(win => {
  win.Drupal.CKEditor5Instances.forEach(editor => editor.setData('<p>Test</p>'))
})

```
