### ISSUE TITLE
DOMException: Failed to set the 'domain' property on 'Document': 'azure.com' is a top-level domain.

### ISSUE THREAD

**Issue by Magesgsm2016** [cypress-io/cypress#29445]
### Current behavior

Hi
I'm trying to tests a website on an Azure domain which looks like:
```js
cy.visit("https://smart-05.eastus.cloudapp.azure.com/ps/it/ui/smart/global/")
```
I'm facing this issue that above Url not launching in chrome and edge browser. Still it is working fine with electron browser.
it was worked fine earlier in all my browser. Recently chrome version is updated to 124 .post update of chrome I'm facing the below mentioned issue.
my terminal just hangs after (Tests Starting) without stopping or showing any error.
When I try to run cypress, I'm getting the following error:
```
Uncaught(in promise) DOMException: Failed to set the 'domain' property on 'Document': 'azure.com' is a top-level domain.
    at $Cypress.configure (https://smart-05.eastus.cloudapp.azure.com/__cypress/runner/cypress_runner.js:40723:23)
    at $Cypress.create (https://smart-05.eastus.cloudapp.azure.com/__cypress/runner/cypress_runner.js:41231:13)
    at EventManager.setup (https://smart-05.eastus.cloudapp.azure.com/__/assets/index-9bf45ce8.js:133048:52)
    at Object.executeSpec (https://smart-05.eastus.cloudapp.azure.com/__/assets/index-9bf45ce8.js:133627:27)**
```
    Error is throwing in the  domainName
    =========================
```js
     if (domainName && config.testingType === 'e2e') {
      document.domain = domainName
    }
```
cypress version :13.7.3
could you please help to resolve it ?
Reference:Issue with domains in 'baseUrl' having several dots #1680

### Test code to reproduce

when i command "npx cypress open" and click on the specific specs file
```js
cy.configurationPage(envData.aiopsLogInUrl, envData.userName, envData.password, envData.projectName);
```
 should be launch in cypress runner
 -------------------------------
```js
Cypress.Commands.add("loginProjectPage", (url, username, password) => {
  cy.visit(url);
  // cy.wait(10000)
  cy.get(homePage.txtUserName).type(username);
  cy.wait(1000)
  cy.get(homePage.txtPassword).type(password);
  cy.wait(1000)
  cy.get(homePage.btnLogin).click();
  cy.get(homePage.txtProjectListing, { timeout: Cypress.config("defaultCommandTimeout") }).should("be.visible");

});
```
--------------------------
envData
=====
```js
export class Utility {
  getEnvData() {
    const qa = {
      userName: "adxxxxx",
      password: "23456",
      aiopsLogInUrl:
        "https://smart-05.eastus.cloudapp.azure.com/ps/it/ui/smart/global/"
}
```

### Cypress Version

13.7.3

### Node version

v18.16.1

### Operating System

window 10

**Comment by HiQ-MartinMichalek** [comment]
Hello there,

I am facing the same issue with 'azureedge.net' since Chrome version 124.

I tried using experimentalSkipDomainInjection, but to no avail.

Chrome: V 124
Cypress: V 12.5.1
Node: v20.5.1
OS:  Windows 10

**Comment by AbdelazizBannani** [comment]
@Magesgsm2016 
  this solved it for me:
  add the following to your config file. → experimentalSkipDomainInjection: ["*azure.com"],

**Comment by AOT1000** [comment]
I am facing the exact same issue with another application installed in an Azure machine that is exposed to the internet.
@AbdelazizBannani , could you please elaborate on which config file you added this to?

**Comment by AbdelazizBannani** [comment]
@AOT1000 I am using the most recent cyperss version (13.10.0) and I just added the following to my "cypress.config.js" 


`**experimentalSkipDomainInjection: ["*azure.com"],**
    video: true,
    chromeWebSecurity: true,
    screenshotsFolder: "cypress/screenshots",
    videosFolder: "cypress/videos",`

**Comment by jennifer-shehane** [comment]
We are working on a fix for this in Cypress 14.

**Comment by AbdelazizBannani** [comment]
@jennifer-shehane great to hear. Thnx for the feedback

**Comment by AtofStryker** [comment]
closing as this is resolved with #30770 and will be released with Cypress 14
