### ISSUE TITLE
`cypress open` failed to start on Mac M1 (Sonoma 14.0)

### ISSUE THREAD

**Issue by trandaison** [cypress-io/cypress#29513]
### Current behavior

Cypress failed to start when running command `cypress open`

### Debug logs

```Text
> start-server-and-test 'vite dev --port 4173' http://localhost:4173 'cypress open --e2e'

1: starting server using command "vite dev --port 4173"
and when url "[ 'http://localhost:4173' ]" is responding with HTTP status code 200
running tests using command "cypress open --e2e"


  VITE v5.2.11  ready in 353 ms

  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
  ➜  Vue DevTools: Open http://localhost:4173/__devtools__/ as a separate window
  ➜  Vue DevTools: Press Option(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

  cypress:cli:cli cli starts with arguments ["/Users/nals_macbook_109/.nvm/versions/node/v18.16.0/bin/node","/Users/nals_macbook_109/workspace/internal/vue-test-e2e/node_modules/.bin/cypress","open","--e2e"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli opening Cypress +0ms
  cypress:cli parsed cli options { e2e: true } +52ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress +1ms
  cypress:cli Binary is executable? : true +0ms
  cypress:cli binaryDir is  /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app +1ms
  cypress:cli Reading binary package.json from: /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli Found binary version 13.9.0 installed in: /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app +2ms
  cypress:cli could not read binary_state.json file at "/Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/binary_state.json" +2ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +0ms
  cypress:cli running binary verification check 13.9.0 +0ms
It looks like this is your first time using Cypress: 13.9.0


  cypress:cli clearing out the verified version +3ms
  cypress:cli needs Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress +0ms
  cypress:cli smoke test command: /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGTERM (Termination): /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705
    at makeError (/Users/nals_macbook_109/workspace/internal/vue-test-e2e/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/nals_macbook_109/workspace/internal/vue-test-e2e/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGTERM (Termination): /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705',
  command: '/Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705',
  exitCode: undefined,
  signal: 'SIGTERM',
  signalDescription: 'Termination',
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +200ms
  cypress:cli error message: Command was killed with SIGTERM (Termination): /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705 +1ms

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGTERM (Termination): /Users/nals_macbook_109/Library/Caches/Cypress/13.9.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=705

----------

Platform: darwin-arm64 (23.0.0)
Cypress Version: 13.9.0
```

### Cypress Version

13.9.0

### Node version

v18.16.0 & v20.11.0

### Package Manager

npm

### Package Manager Version

9.5.1

### Operating system

Mac

### Operating System Version

14.0

**Comment by jennifer-shehane** [comment]
@trandaison How did you install Cypress originally? What command did you run? Is this your first time using Cypress?

**Comment by trandaison** [comment]
> @trandaison How did you install Cypress originally? What command did you run? 

I tried 2 different ways to install Cypress. 

- First, I followed this guide https://docs.cypress.io/guides/getting-started/installing-cypress, and use the command `npx cypress open`
- Second, I used `create-vue` (https://vuejs.org/guide/quick-start.html) to create a new Vue project and select the cypress as a e2e testing tool. Then I run `npm run test:e2e:dev` to open the Cypress GUI which is defined in the `package.json` file.
```
  "scripts": {
    "test:e2e": "start-server-and-test preview http://localhost:4173 'cypress run --e2e'",
    "test:e2e:dev": "start-server-and-test 'vite dev --port 4173' http://localhost:4173 'cypress open --e2e'",
  },
```
Both of them have the same issue.

> Is this your first time using Cypress?

Yes!
