### ISSUE TITLE
set up Mac OS X build on Circle

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#2958]
Set test runner binary build on CircleCI

- https://circleci.com/build-environments/xcode/osx/

need to upgrade our CircleCI plan first, so we can add Mac os builds

## blocked

hmm, Fastlane match might not work for signing Mac apps (and they target it at iOS only)

- https://github.com/fastlane/fastlane/issues/11980
- https://github.com/fastlane/fastlane/issues/8178

and CircleCI support forum issues from people trying to sign Mac apps (not iOS): 

- https://discuss.circleci.com/t/install-code-signing-credentials-in-circleci-2-0/18423/6
- https://discuss.circleci.com/t/build-and-test-macos-app-help-with-config-yml-file/19682/2
- https://discuss.circleci.com/t/is-a-macos-project-supported-by-circleci/25020
- https://discuss.circleci.com/t/after-fastlane-match-cant-find-signing-identity/7901
- https://discuss.circleci.com/t/manual-macos-code-signing/22587/7

I have opened CircleCI issue https://discuss.circleci.com/t/mac-os-app-signing-without-fastlane/27292 on their discussion board

**Comment by bahmutov** [comment]
CircleCI forum has responded with a suggestion how to sign iOS app without using FastLane https://medium.com/@m4rr/circleci-2-0-and-the-ios-code-signing-df434d0086e2 This post talks about iOS signing (and not Mac app signing) so it remains to be seen if this would work

**Comment by bahmutov** [comment]
Even when I am able to get the profile installed, code sign hangs
```
9:08:38 PM #codeSign /Users/distiller/cypress/build/darwin/Cypress.app darwin
  electron-osx-sign electron-osx-sign@0.4.11 +0ms
  electron-osx-sign:warn No `identity` passed in arguments... +2ms
  electron-osx-sign Finding `Developer ID Application` certificate for distribution outside the Mac App Store... +0ms
  electron-osx-sign Executing... security find-identity -v +0ms
  electron-osx-sign Identity: 
 > Name: Developer ID Application: Brian Mann (HBY9248HZY) 
 > Hash: 67591F94D95F86820F07DE764BAB39F4D95470DD +152ms
  electron-osx-sign Found 1 identity. +1ms
  electron-osx-sign:warn No `entitlements` passed in arguments: 
 * Provide `entitlements` to specify entitlements file for codesign. +0ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile: 
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +0ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +1ms
  electron-osx-sign No provisioning profile found, will not embed profile in app contents. +3ms
  electron-osx-sign Signing application... 
 > Application: /Users/distiller/cypress/build/darwin/Cypress.app 
 > Platform: darwin 
 > Entitlements: undefined 
 > Child entitlements: undefined 
 > Additional binaries: undefined 
 > Identity: { name: 'Developer ID Application: Brian Mann (HBY9248HZY)',
  hash: '67591F94D95F86820F07DE764BAB39F4D95470DD' } +0ms
  electron-osx-sign Walking... /Users/distiller/cypress/build/darwin/Cypress.app/Contents +1ms
  electron-osx-sign Signing... /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +2s
  electron-osx-sign Executing... codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +0ms
```

**Comment by bahmutov** [comment]
Importing profile into keychain itself is _very flaky_ on Circle. It fails, then if rerunning the workflow can pass. Rerunning just the command does not solve it! Here is a private project that just tries to import the profile running on Circle (no code changes)

<img width="1060" alt="screen shot 2019-01-04 at 9 20 14 pm" src="https://user-images.githubusercontent.com/2212006/50719191-b02da200-1066-11e9-8c91-386fefaae9d5.png">

**Comment by bahmutov** [comment]
Hmm, if the codesign is stuck, maybe it is prompting the user to sign the app (source https://stackoverflow.com/questions/13078033/xcode-project-on-jenkins-stuck-at-codesign)

**Comment by bahmutov** [comment]
In Fastlane examples from other users I see the following (I have removed extra lines)
```ruby
private_lane :prepare_certificates do |options|
  unlock_keychain(path:"default_keychain", password:"default")
  sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/default_keychain-db"

  # we don't care about signing app using fastlane
  # sigh(readonly: true, adhoc: true, skip_certificate_verification: true)
end
```

Maybe we need to use Fastlane to unlock keychain and then it won't prompt us?

**Comment by bahmutov** [comment]
Hmm, could not switch default keychain on circle
```
Will not set default: UID=0 does not own directory /Users/distiller
security: SecKeychainSetDefault: Write permissions error.
Exited with code 1
```

**Comment by bahmutov** [comment]
when making separate keychain and unlocking it, got the following error
```
10:52:46 PM #codeSign /Users/distiller/cypress/build/darwin/Cypress.app darwin
  electron-osx-sign electron-osx-sign@0.4.11 +0ms
  electron-osx-sign:warn No `identity` passed in arguments... +1ms
  electron-osx-sign Finding `Developer ID Application` certificate for distribution outside the Mac App Store... +0ms
  electron-osx-sign Executing... security find-identity -v +1ms
  electron-osx-sign Identity: 
 > Name: Developer ID Application: Brian Mann (HBY9248HZY) 
 > Hash: 67591F94D95F86820F07DE764BAB39F4D95470DD +66ms
  electron-osx-sign Found 1 identity. +0ms
  electron-osx-sign:warn No `entitlements` passed in arguments: 
 * Provide `entitlements` to specify entitlements file for codesign. +0ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile: 
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +1ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +0ms
  electron-osx-sign No provisioning profile found, will not embed profile in app contents. +3ms
  electron-osx-sign Signing application... 
 > Application: /Users/distiller/cypress/build/darwin/Cypress.app 
 > Platform: darwin 
 > Entitlements: undefined 
 > Child entitlements: undefined 
 > Additional binaries: undefined 
 > Identity: { name: 'Developer ID Application: Brian Mann (HBY9248HZY)',
  hash: '67591F94D95F86820F07DE764BAB39F4D95470DD' } +1ms
  electron-osx-sign Walking... /Users/distiller/cypress/build/darwin/Cypress.app/Contents +0ms
  electron-osx-sign Signing... /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +2s
  electron-osx-sign Executing... codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +0ms
  electron-osx-sign Error executing file: 
 > Stdout:  
 > Stderr: /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: unknown error -1=ffffffffffffffff
 +664ms
  electron-osx-sign Sign failed: +3ms
  electron-osx-sign Command failed: codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH
  electron-osx-sign /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: unknown error -1=ffffffffffffffff
  electron-osx-sign  +0ms
🔥 deploy error
{ Error: Command failed: codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH
/Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: unknown error -1=ffffffffffffffff
```

**Comment by bahmutov** [comment]
When specifying new custom keychain name

```
log("#codeSign #{appFolder}")
    sign({
      app: appFolder
      platform
      keychain: "MyKeychain.keychain"
      verbose: true
    })
```
getting the error `errSecInternalComponent`
```
12:38:30 AM #codeSign /Users/distiller/cypress/build/darwin/Cypress.app darwin
  electron-osx-sign electron-osx-sign@0.4.11 +0ms
  electron-osx-sign:warn No `identity` passed in arguments... +2ms
  electron-osx-sign Finding `Developer ID Application` certificate for distribution outside the Mac App Store... +0ms
  electron-osx-sign Executing... security find-identity -v MyKeychain.keychain +1ms
  electron-osx-sign Identity: 
 > Name: Developer ID Application: Brian Mann (HBY9248HZY) 
 > Hash: 67591F94D95F86820F07DE764BAB39F4D95470DD +83ms
  electron-osx-sign Found 1 identity. +0ms
  electron-osx-sign:warn No `entitlements` passed in arguments: 
 * Provide `entitlements` to specify entitlements file for codesign. +1ms
  electron-osx-sign Pre-sign operation enabled for provisioning profile: 
 * Disable by setting `pre-embed-previsioning-profile` to `false`. +0ms
  electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
 * Disable by setting `pre-auto-entitlements` to `false`. +0ms
  electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +0ms
  electron-osx-sign No provisioning profile found, will not embed profile in app contents. +4ms
  electron-osx-sign Signing application... 
 > Application: /Users/distiller/cypress/build/darwin/Cypress.app 
 > Platform: darwin 
 > Entitlements: undefined 
 > Child entitlements: undefined 
 > Additional binaries: undefined 
 > Identity: { name: 'Developer ID Application: Brian Mann (HBY9248HZY)',
  hash: '67591F94D95F86820F07DE764BAB39F4D95470DD' } +0ms
  electron-osx-sign Walking... /Users/distiller/cypress/build/darwin/Cypress.app/Contents +1ms
  electron-osx-sign Signing... /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +2s
  electron-osx-sign Executing... codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force --keychain MyKeychain.keychain /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH +0ms
  electron-osx-sign Error executing file: 
 > Stdout:  
 > Stderr: /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: errSecInternalComponent
 +992ms
  electron-osx-sign Sign failed: +2ms
  electron-osx-sign Command failed: codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force --keychain MyKeychain.keychain /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH
  electron-osx-sign /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: errSecInternalComponent
  electron-osx-sign  +0ms
🔥 deploy error
{ Error: Command failed: codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force --keychain MyKeychain.keychain /Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH
/Users/distiller/cypress/build/darwin/Cypress.app/Contents/Frameworks/Cypress Helper EH.app/Contents/MacOS/Cypress Helper EH: errSecInternalComponent
```

**Comment by bahmutov** [comment]
Pretty good guide for Travis how to sign electron apps - https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html Seems to have all the same steps as I do already on Circle

**Comment by bahmutov** [comment]
Trying the above steps locally brings the following dialog when running
```
codesign --deep --force --verbose --sign "<identity>" Application.app
```
<img width="434" alt="screen shot 2019-01-07 at 2 05 24 pm" src="https://user-images.githubusercontent.com/2212006/50787796-6cfd4a00-1285-11e9-9ff8-c071659d6985.png">

**Comment by bahmutov** [comment]
According to another user https://discuss.circleci.com/t/mac-os-app-signing-without-fastlane/27292/8 one can pass certificate and password to sign Mac binaries as environment variables.

But this is done through `electron-builder`, not through `electron-osx-sign` 

https://www.electron.build/code-signing

**Comment by bahmutov** [comment]
Interesting, I have installed globally and could pack built app and sign it

```
$ npm i -g electron-builder
/Users/gleb/.nvm/versions/node/v8.9.4/bin/electron-builder -> /Users/gleb/.nvm/versions/node/v8.9.4/lib/node_modules/electron-builder/out/cli/cli.js
/Users/gleb/.nvm/versions/node/v8.9.4/bin/build -> /Users/gleb/.nvm/versions/node/v8.9.4/lib/node_modules/electron-builder/out/cli/cli.js
/Users/gleb/.nvm/versions/node/v8.9.4/bin/install-app-deps -> /Users/gleb/.nvm/versions/node/v8.9.4/lib/node_modules/electron-builder/out/cli/install-app-deps.js
+ electron-builder@20.38.4
added 192 packages from 129 contributors in 20.548s
```

using this app I could sign built app (using environment variables)

```
$ security find-identity -v -p codesigning
     0 valid identities found
```
checking signature before signing
```
18:01:31 #verifyAppCanOpen /Users/gleb/git/cypress/build/darwin/Cypress.app darwin
/Users/gleb/git/cypress/build/darwin/Cypress.app: rejected
source=no usable signature
🔥 deploy error
Error: Verifying App via GateKeeper failed
```

Then

```
$ build --prepackaged build/darwin/Cypress.app
```
```
$ build --prepackaged build/darwin/Cypress.app
  • electron-builder version=20.38.4
  • writing effective config file=dist/builder-effective-config.yaml
  • signing         file=build/darwin/Cypress.app identityName=Developer ID Application: Brian Mann (HBY9248HZY) identityHash=<...> provisioningProfile=none
  • building        target=macOS zip arch=x64 file=dist/Cypress-3.1.4-mac.zip
  • building        target=DMG arch=x64 file=dist/Cypress-3.1.4.dmg
  • default Electron icon is used reason=application icon is not set
  • building block map blockMapFile=dist/Cypress-3.1.4.dmg.blockmap
  • building embedded block map file=dist/Cypress-3.1.4-mac.zip
```
the signed app now passes our verification
```
#build
17:53:53 #verifyAppCanOpen /Users/gleb/git/cypress/build/darwin/Cypress.app darwin
/Users/gleb/git/cypress/build/darwin/Cypress.app: accepted
source=Developer ID
origin=Developer ID Application: Brian Mann (HBY9248HZY)
✅ build completed
```

**Comment by bahmutov** [comment]
Running build with `DEBUG=electron-builder,electron-osx-sign*` revealed making new keychains with partition 
```
• executing       file=security args=import /private/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/t-oodsC2/2.p12 -k /private/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/t-oodsC2/1.keychain -T /usr/bin/codesign -T /usr/bin/productbuild -P 363d84769be552a874f83ca41e121122bc63581d061aaaa2c27173f120b3aab3 (sha256 hash)
...
• executing       file=security args=set-key-partition-list -S apple-tool:,apple: -s -k <password> /private/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/t-oodsC2/1.keychain
```

so it seems different in two aspects from from `codesign`...

**Comment by bahmutov** [comment]
On CircleCI run https://circleci.com/gh/cypress-io/cypress/47270 we have signed the app!

```
Tue, 08 Jan 2019 23:51:22 GMT electron-osx-sign Signing... /Users/distiller/cypress/build/darwin/Cypress.app
Tue, 08 Jan 2019 23:51:22 GMT electron-osx-sign Executing... codesign --sign 67591F94D95F86820F07DE764BAB39F4D95470DD --force --keychain /p*** /Users/distiller/cypress/build/darwin/Cypress.app
Tue, 08 Jan 2019 23:51:30 GMT electron-osx-sign Verifying...
Tue, 08 Jan 2019 23:51:30 GMT electron-osx-sign Verifying application bundle with codesign...
Tue, 08 Jan 2019 23:51:30 GMT electron-osx-sign Executing... codesign --verify --deep --strict --verbose=2 /Users/distiller/cypress/build/darwin/Cypress.app
Tue, 08 Jan 2019 23:51:40 GMT electron-osx-sign Verifying Gatekeeper acceptance for darwin platform...
Tue, 08 Jan 2019 23:51:40 GMT electron-osx-sign Executing... spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/distiller/cypress/build/darwin/Cypress.app
Tue, 08 Jan 2019 23:51:48 GMT electron-osx-sign Verified.
Tue, 08 Jan 2019 23:51:48 GMT electron-osx-sign Application signed.
```

Then it continues and fails with the following error

```
Tue, 08 Jan 2019 23:51:48 GMT electron-osx-sign Verified.
Tue, 08 Jan 2019 23:51:48 GMT electron-osx-sign Application signed.
  • building        target=macOS zip arch=x64 file=dist/Cypress-3.1.4-mac.zip
  • building        target=DMG arch=x64 file=dist/Cypress-3.1.4.dmg
  • path doesn't exist        path=/Users/distiller/cypress/build/icon.icns
  • path doesn't exist        path=/Users/distiller/cypress/icon.icns
  • path doesn't exist        path=/Users/distiller/cypress/build/icons
  • path doesn't exist        path=/Users/distiller/cypress/icons
  • path doesn't exist        path=/Users/distiller/cypress/build/icon.png
  • path doesn't exist        path=/Users/distiller/cypress/icon.png
  • no icons found, using provided fallback sources
  • default Electron icon is used reason=application icon is not set
  • copy files                from=/Users/distiller/cypress/node_modules/dmg-builder/templates/background.tiff isUseHardLinks=false to=/Volumes/Cypress 3.1.4/.background/background.tiff
  • building block map blockMapFile=dist/Cypress-3.1.4.dmg.blockmap
  • building embedded block map file=dist/Cypress-3.1.4-mac.zip

    at Promise.all.then.arr (/Users/distiller/cypress/node_modules/execa/index.js:236:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

  code: 1,
  killed: false,

stderr:
   'Tue, 08 Jan 2019 23:51:01 GMT electron-osx-sign:warn No `entitlements` passed in arguments: \n * Provide `entitlements` to specify entitlements file for codesign.\nGitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"\n',
```

why does it need GitHub access token?!

**Comment by bahmutov** [comment]
Seems this is `electron-builder` trying to publish built artifact to GitHub because it found the origin repo https://www.electron.build/configuration/publish, need to disable it

**Comment by bahmutov** [comment]
my final command that worked in https://circleci.com/gh/cypress-io/cypress/47449 was
```
build --publish never --prepackaged <appFolder>
```
that just signs the app I have built before

tears of happiness
