### ISSUE TITLE
node-sass will cause Cypress to crash on Windows

### ISSUE THREAD

**Issue by silbinarywolf** [cypress-io/cypress#2967]
### Current behavior:
If you're trying to run unit tests in Cypress directly and want to use your webpack build as-is on Windows, it will crash if you use node-sass due to the DLL not initializing properly.

```
The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

./styles/main.scss (./node_modules/css-loader!./node_modules/postcss-loader/src??ref--12-2!./node_modules/sass-loader/lib/loader.js??ref--12-3!./styles/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: A dynamic link library (DLL) initialization routine failed. 
\\?\{rootDir}\node_modules\node-sass\vendor\win32-x64-57\binding.node
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
at Object.Module._extensions..node (module.js:598:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at module.exports ({rootDir}\node_modules\node-sass\lib\binding.js:19:10)
at Object. ({rootDir}\node_modules\node-sass\lib\index.js:14:35)
at Object. ({rootDir}\node_modules\node-sass\lib\index.js:477:3)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object.sassLoader ({rootDir}\node_modules\sass-loader\lib\loader.js:46:72)
@ ./styles/main.scss 2:14-182
@ ./src/main.ts
```

### Desired behavior:
Ideally it should just work with node-sass!

However if that's a non-trivial effort, catching this kind of error and telling a user to try and use the "dart-sass" implementation for Cypress unit testing instead would be helpful.

### Steps to reproduce: (app code and test code)
If you pull down this WIP repo at commit ID: a6de78b1bbf336fa683514e44b5582579ddc272e
...and remove the following Webpack config line (so it defaults to node-sass)
https://github.com/silbinarywolf/collapo/blob/master/webpack.common.js#L48

If you run `cypress open` and try to run the test, it should show the error message inside the Cypress Electron app.

Any sort of project where you try to load/compile SASS files with node-sass on a Windows machine should make this bug occur.

### Versions
- Windows 10
- Cypress: 3.1.3

**Comment by jennifer-shehane** [comment]
Closing as resolved. We removed `node-sass` as a dependency in Cypress 6.3.0. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
