### ISSUE TITLE
Issue running test with husky on pre-commit

### ISSUE THREAD

**Issue by JonathanJeune** [cypress-io/cypress#29723]
### Current behavior

When I run this command `vue-cli-service test:e2e --headless --component` in a terminal, it works fine but when I commit my changes , I have this error :

> node:internal/modules/cjs/loader:1087
>   throw err;
>   ^
> 
> Error: Cannot find module '/Users/xxx/Library/Caches/Cypress/13.6.6/Cypress.app/Contents/MacOS/Contents/Resources/app/index.js'
>     at Function._resolveFilename (node:internal/modules/cjs/loader:1084:15)
>     at node:internal/modules/cjs/loader:929:27
>     at Function._load (node:electron/js2c/asar_bundle:2:13327)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:96:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> Node.js v18.17.1
>  ERROR  Error: Command failed: /Users/xxx/Projects/nbs-admi-zero-vue/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8082/ --headless --component
> Error: Command failed: /Users/xxx/Projects/nbs-admi-zero-vue/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8082/ --headless --component
>     at makeError (/Users/xxx/Projects/nbs-admi-zero-vue/node_modules/@vue/cli-shared-utils/node_modules/execa/index.js:174:9)
>     at /Users/xxx/Projects/nbs-admi-zero-vue/node_modules/@vue/cli-shared-utils/node_modules/execa/index.js:278:16
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Seems not to be a husky's issue because I tried an other pre-commit's module and I had the same issue.

### Desired behavior

Should works :) 

### Test code to reproduce

My package.json :

```
{
  "name": "nbs-admin-zero-vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve & yarn sprite",
    "build": "yarn test && vue-cli-service build & yarn sprite",
    "watch": "vue-cli-service build --mode development --watch & yarn sprite",
    "test:unit": "vue-cli-service test:unit --coverage",
    "test:e2e": "vue-cli-service test:e2e --mode development",
    "test": "vue-cli-service test:unit && vue-cli-service test:e2e --headless --component",
    "lint": "vue-cli-service lint",
    "sprite": "svg-sprite -d --dx --dest=./public/sprite/ ./src/assets/icons/*.svg & node ./scripts/icons.js",
    "prepare": "husky"
  },
  "pre-commit": [
    "test"
  ],
  "dependencies": {
    "@jonathanjeune/ppp-vue-datepicker": "^7.3.1-b",
    "@ungap/structured-clone": "^1.2.0",
    "@vueuse/core": "^10.5.0",
    "axios": "^1.5.1",
    "core-js": "^3.8.3",
    "dotenv": "^16.4.5",
    "fs": "^0.0.1-security",
    "moment": "^2.29.4",
    "object.groupby": "^1.0.1",
    "pinia": "^2.1.6",
    "register-service-worker": "^1.7.2",
    "reset-css": "^5.0.2",
    "vue": "^3.2.13",
    "vue-router": "^4.0.3",
    "vue3-rich-accordion": "^0.0.7",
    "vuedraggable": "^4.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-e2e-cypress": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-pwa": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-unit-jest": "~5.0.0",
    "@vue/cli-service": "^5.0.8",
    "@vue/eslint-config-standard": "^6.1.0",
    "@vue/test-utils": "^2.0.0-0",
    "@vue/vue3-jest": "^27.0.0-alpha.1",
    "babel-jest": "^27.0.6",
    "cypress": "13.6.6",
    "eslint": "^7.32.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-vue": "^8.0.3",
    "husky": "^9.0.11",
    "jest": "^27.0.5",
    "jest-mock-axios": "^4.7.3",
    "path": "^0.12.7",
    "sass": "^1.32.7",
    "sass-loader": "^12.0.0",
    "sass-mq": "^6.0.0",
    "svg-sprite": "^2.0.2"
  }
}
```

### Cypress Version

13.6.6

### Node version

v20.5.0

### Operating System

macOs 14.5

**Comment by JonathanJeune** [comment]
Ok, it seems that the issue was caused by VS Code...
Added this line to my pre-commit config file and it is resolved :
```
echo "***Running unit tests***"
unset ELECTRON_RUN_AS_NODE
```
