### ISSUE TITLE
"process is not defined"

### ISSUE THREAD

**Issue by nichoth** [cypress-io/cypress#30264]
### Current behavior

Install cypress, follow the GUI prompts for e2e testing, choose the first example, `todo`. Get an error,

> process is not defined

![image](https://github.com/user-attachments/assets/4fe945c8-154f-4ce0-94c0-b31022860ca6)

> The following error originated from your test code, not from Cypress.
> process is not defined
> When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
> Cypress could not associate this error to any specific test.
> We dynamically generated a new test to display this failure.

### Desired behavior

Example tests should work

### Test code to reproduce

https://github.com/nichoth/example-cypress

### Cypress Version

13.14.2

### Node version

20.16.0

### Operating System

macOS 14.5

### Debug Logs

```shell
================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.14.2                                                                        │
  │ Browser:        Electron 118 (headless)                                                        │
  │ Node Version:   v20.16.0 (/Users/nick/.nvm/versions/node/v20.16.0/bin/node)                    │
  │ Specs:          20 found (1-getting-started/todo.cy.js, 2-advanced-examples/actions.cy.js, 2-a │
  │                 dvanced-examples/aliasing.cy.js, 2-advanced-examples/assertions.cy.js, 2-advan │
  │                 ced-examples/connectors.cy.js, 2-advanced-examples/cookies.cy.js, 2-advanced-e │
  │                 xamples/cypress_api.cy....)                                                    │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  1-getting-started/todo.cy.js                                                   (1 of 20)


  1) An uncaught error was detected outside of a test

  0 passing (166ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     ReferenceError: The following error originated from your test code, not from Cypress.

  > process is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at ./node_modules/ci-info/index.js (webpack:///./node_modules/ci-info/index.js:5:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./node_modules/is-ci/index.js (webpack:///./node_modules/is-ci/index.js:3:0)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./node_modules/cypress/lib/util.js (webpack:///./node_modules/cypress/lib/util.js:12:13)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at ./node_modules/cypress/index.js (webpack:///./node_modules/cypress/index.js:6:13)
      at __webpack_require__ (webpack:///webpack/bootstrap:19:0)
      at eval (webpack:///./cypress/e2e/1-getting-started/todo.cy.js:1:0)
      at eval (http://localhost:56581/__cypress/tests?p=cypress/e2e/1-getting-started/todo.cy.js:159206:3)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     1-getting-started/todo.cy.js                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/nick/code/cardpost/cypress/screenshots/1-getting-started/todo.cy.js/An un     (1280x720)
     caught error was detected outside of a test (failed).png                                       


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/actions.cy.js                                              (2 of 20)


  Actions
    ✓ .type() - type into a DOM element (4019ms)
    ✓ .focus() - focus on a DOM element (217ms)
    ✓ .blur() - blur off a DOM element (421ms)
    ✓ .clear() - clears an input or textarea element (541ms)
    ✓ .submit() - submit a form (428ms)
    ✓ .click() - click on a DOM element (2046ms)
    ✓ .dblclick() - double click on a DOM element (260ms)
    ✓ .rightclick() - right click on a DOM element (265ms)
    ✓ .check() - check a checkbox or radio element (898ms)
    ✓ .uncheck() - uncheck a checkbox element (893ms)
    ✓ .select() - select an option in a <select> element (917ms)
    ✓ .scrollIntoView() - scroll an element into view (177ms)
    ✓ .trigger() - trigger an event on a DOM element (143ms)
    ✓ cy.scrollTo() - scroll the window or element to a position (2162ms)


  14 passing (15s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        14                                                                               │
  │ Passing:      14                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     14 seconds                                                                       │
  │ Spec Ran:     2-advanced-examples/actions.cy.js                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/aliasing.cy.js                                             (3 of 20)


  Aliasing
    ✓ .as() - alias a DOM element for later use (1619ms)
    ✓ .as() - alias a route for later use (1181ms)


  2 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/aliasing.cy.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/assertions.cy.js                                           (4 of 20)


  Assertions
    Implicit Assertions
      ✓ .should() - make an assertion about the current subject (1326ms)
      ✓ .and() - chain multiple assertions together (143ms)
    Explicit Assertions
      ✓ expect - make an assertion about a specified subject (143ms)
      ✓ pass your own callback function to should() (142ms)
      ✓ finds element by class name regex (133ms)
      ✓ can throw any error (142ms)
      ✓ matches unknown text between two elements (136ms)
      ✓ assert - assert shape of an object (137ms)
      ✓ retries the should callback until assertions pass (1640ms)


  9 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      9                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     5 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/assertions.cy.js                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/connectors.cy.js                                           (5 of 20)


  Connectors
    ✓ .each() - iterate over an array of elements (448ms)
    ✓ .its() - get properties on the current subject (126ms)
    ✓ .invoke() - invoke a function on the current subject (374ms)
    ✓ .spread() - spread an array as individual args to callback function (267ms)
    .then()
      ✓ invokes a callback function with the current subject (115ms)
      ✓ yields the returned value to the next command (423ms)
      ✓ yields the original subject without return (107ms)
      ✓ yields the value yielded by the last Cypress command inside (98ms)


  8 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        8                                                                                │
  │ Passing:      8                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/connectors.cy.js                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/cookies.cy.js                                              (6 of 20)


  Cookies
    ✓ cy.getCookie() - get a browser cookie (542ms)
    ✓ cy.getCookies() - get browser cookies for the current domain (246ms)
    ✓ cy.getAllCookies() - get all browser cookies (144ms)
    ✓ cy.setCookie() - set a browser cookie (116ms)
    ✓ cy.clearCookie() - clear a browser cookie (190ms)
    ✓ cy.clearCookies() - clear browser cookies for the current domain (191ms)
    ✓ cy.clearAllCookies() - clear all browser cookies (120ms)


  7 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        7                                                                                │
  │ Passing:      7                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/cookies.cy.js                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/cypress_api.cy.js                                          (7 of 20)


  Cypress APIs
    Cypress.Commands
      ✓ .add() - create a custom command (372ms)
    Cypress.Cookies
      ✓ .debug() - enable or disable debugging (120ms)
    Cypress.arch
      ✓ Get CPU architecture name of underlying OS (102ms)
    Cypress.config()
      ✓ Get and set configuration options (107ms)
    Cypress.dom
      ✓ .isHidden() - determine if a DOM element is hidden (109ms)
    Cypress.env()
      ✓ Get environment variables (103ms)
    Cypress.log
      ✓ Control what is printed to the Command Log (101ms)
    Cypress.platform
      ✓ Get underlying OS name (123ms)
    Cypress.version
      ✓ Get current version of Cypress being run (98ms)
    Cypress.spec
      ✓ Get current spec information (133ms)


  10 passing (2s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        10                                                                               │
  │ Passing:      10                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/cypress_api.cy.js                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/files.cy.js                                                (8 of 20)


  Files
    ✓ cy.fixture() - load a fixture (1042ms)
    ✓ cy.fixture() or require - load a fixture (161ms)
    ✓ cy.readFile() - read file contents (153ms)
    ✓ cy.writeFile() - write to a file (320ms)


  4 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/files.cy.js                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/location.cy.js                                             (9 of 20)


  Location
    ✓ cy.hash() - get the current URL hash (728ms)
    ✓ cy.location() - get window.location (125ms)
    ✓ cy.url() - get the current URL (106ms)


  3 passing (2s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     2-advanced-examples/location.cy.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/misc.cy.js                                                (10 of 20)


  Misc
    ✓ cy.exec() - execute a system command (2680ms)
    ✓ cy.focused() - get the DOM element that has focus (273ms)
    ✓ cy.wrap() - wrap an object (119ms)
    Cypress.Screenshot
      ✓ cy.screenshot() - take a screenshot (646ms)
      ✓ Cypress.Screenshot.defaults() - change default config of screenshots (102ms)


  5 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/misc.cy.js                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/nick/code/cardpost/cypress/screenshots/2-advanced-examples/misc.cy.js/my-    (1000x1816)
     image.png                                                                                      


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/navigation.cy.js                                          (11 of 20)


  Navigation
    ✓ cy.go() - go back or forward in the browser's history (1152ms)
    ✓ cy.reload() - reload the page (527ms)
    ✓ cy.visit() - visit a remote url (448ms)


  3 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     3 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/navigation.cy.js                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/network_requests.cy.js                                    (12 of 20)


  Network Requests
    ✓ cy.request() - make an XHR request (1064ms)
    ✓ cy.request() - verify response using BDD syntax (413ms)
    ✓ cy.request() with query parameters (278ms)
    ✓ cy.request() - pass result to the second request (502ms)
    ✓ cy.request() - save response in the shared test context (462ms)
    ✓ cy.intercept() - route responses to matching requests (1187ms)


  6 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        6                                                                                │
  │ Passing:      6                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     5 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/network_requests.cy.js                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/querying.cy.js                                            (13 of 20)


  Querying
    ✓ cy.get() - query DOM elements (508ms)
    ✓ cy.contains() - query DOM elements with matching content (123ms)
    ✓ .within() - query DOM elements within a specific element (111ms)
    ✓ cy.root() - query the root DOM element (117ms)
    ✓ best practices - selecting elements (683ms)


  5 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/querying.cy.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/spies_stubs_clocks.cy.js                                  (14 of 20)


  Spies, Stubs, and Clock
    ✓ cy.spy() - wrap a method in a spy (433ms)
    ✓ cy.spy() retries until assertions pass (2538ms)
    ✓ cy.stub() - create a stub and/or replace a function with stub (148ms)
    ✓ cy.clock() - control time in the browser (212ms)
    ✓ cy.tick() - move time in the browser (271ms)
    ✓ cy.stub() matches depending on arguments (17ms)
    ✓ matches call arguments using Sinon matchers (16ms)


  7 passing (5s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        7                                                                                │
  │ Passing:      7                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/spies_stubs_clocks.cy.js                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/storage.cy.js                                             (15 of 20)


  Local Storage / Session Storage
    ✓ cy.clearLocalStorage() - clear all data in localStorage for the current origin (779ms)
    ✓ cy.getAllLocalStorage() - get all data in localStorage for all origins (226ms)
    ✓ cy.clearAllLocalStorage() - clear all data in localStorage for all origins (189ms)
    ✓ cy.getAllSessionStorage() - get all data in sessionStorage for all origins (202ms)
    ✓ cy.clearAllSessionStorage() - clear all data in sessionStorage for all origins (196ms)


  5 passing (3s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/storage.cy.js                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/traversal.cy.js                                           (16 of 20)


  Traversal
    ✓ .children() - get child DOM elements (566ms)
    ✓ .closest() - get closest ancestor DOM element (146ms)
    ✓ .eq() - get a DOM element at a specific index (142ms)
    ✓ .filter() - get DOM elements that match the selector (150ms)
    ✓ .find() - get descendant DOM elements of the selector (135ms)
    ✓ .first() - get first DOM element (137ms)
    ✓ .last() - get last DOM element (127ms)
    ✓ .next() - get next sibling DOM element (128ms)
    ✓ .nextAll() - get all next sibling DOM elements (125ms)
    ✓ .nextUntil() - get next sibling DOM elements until next el (125ms)
    ✓ .not() - remove DOM elements from set of DOM elements (134ms)
    ✓ .parent() - get parent DOM element from DOM elements (130ms)
    ✓ .parents() - get parent DOM elements from DOM elements (129ms)
    ✓ .parentsUntil() - get parent DOM elements from DOM elements until el (124ms)
    ✓ .prev() - get previous sibling DOM element (127ms)
    ✓ .prevAll() - get all previous sibling DOM elements (133ms)
    ✓ .prevUntil() - get all previous sibling DOM elements until el (131ms)
    ✓ .siblings() - get all sibling DOM elements (128ms)


  18 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        18                                                                               │
  │ Passing:      18                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     3 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/traversal.cy.js                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/utilities.cy.js                                           (17 of 20)


  Utilities
    ✓ Cypress._ - call a lodash method (605ms)
    ✓ Cypress.$ - call a jQuery method (213ms)
    ✓ Cypress.Blob - blob utilities and base64 string conversion (479ms)
    ✓ Cypress.minimatch - test out glob patterns against strings (97ms)
    ✓ Cypress.Promise - instantiate a bluebird promise (1107ms)


  5 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      5                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     3 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/utilities.cy.js                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/viewport.cy.js                                            (18 of 20)


  Viewport
    ✓ cy.viewport() - set the viewport size and dimension (3007ms)


  1 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/viewport.cy.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/waiting.cy.js                                             (19 of 20)


  Waiting
    ✓ cy.wait() - wait for a specific amount of time (4987ms)
    ✓ cy.wait() - wait for a specific route (371ms)


  2 passing (6s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     2-advanced-examples/waiting.cy.js                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  2-advanced-examples/window.cy.js                                              (20 of 20)


  Window
    ✓ cy.window() - get the global window object (552ms)
    ✓ cy.document() - get the document object (116ms)
    ✓ cy.title() - get the title (99ms)


  3 passing (2s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     2-advanced-examples/window.cy.js                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  1-getting-started/todo.cy.js             167ms        1        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/actions.cy.js        00:14       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/aliasing.cy.js       00:04        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/assertions.cy.j      00:05        9        9        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/connectors.cy.j      00:02        8        8        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/cookies.cy.js        00:02        7        7        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/cypress_api.cy.      00:02       10       10        -        -        - │
  │    js                                                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/files.cy.js          00:02        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/location.cy.js       00:01        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/misc.cy.js           00:04        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/navigation.cy.j      00:03        3        3        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/network_request      00:05        6        6        -        -        - │
  │    s.cy.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/querying.cy.js       00:02        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/spies_stubs_clo      00:04        7        7        -        -        - │
  │    cks.cy.js                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/storage.cy.js        00:02        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/traversal.cy.js      00:03       18       18        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/utilities.cy.js      00:03        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/viewport.cy.js       00:04        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/waiting.cy.js        00:06        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  2-advanced-examples/window.cy.js         00:01        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 20 failed (5%)                      01:20      118      117        1        -        -
```

**Comment by nichoth** [comment]
Can't reproduce
