### ISSUE TITLE
Cypress failed to start.  This may be due to a missing library or dependency. 

### ISSUE THREAD

**Issue by XuNiWangXiang** [cypress-io/cypress#30474]
### Current behavior

i am use image cypress/base:20.18.0-arm in windows.
```
yarn cy:run to test.
Error: Cypress failed to start.  This may be due to a missing library or dependency. 
```

### Desired behavior
```json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc -b && vite build",
    "preview": "vite preview",
    "cy:open": "cypress open",
    "cy:run": "cypress run",
    "cy:merge": "mochawesome-merge cypress/reports/.jsons/*.json > cypress/reports/combined-report.json"
  },
  "dependencies": {
    "axios": "^1.7.4",
    "element-plus": "^2.8.0",
    "pinia": "^2.2.2",
    "vue": "^3.4.37",
    "vue-router": "^4.4.3"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.2",
    "cypress": "^13.13.3",
    "cypress-mochawesome-reporter": "^3.8.2",
    "mochawesome-merge": "^4.3.0",
    "typescript": "^5.5.3",
    "vite": "^5.4.1",
    "vue-tsc": "^2.0.29"
  }
}
```

### Test code to reproduce
```
i run DEBUG=cypress:* yarn cy:run.
This is Log:
DEBUG=cypress:* yarn cy:run          
yarn run v1.22.22                                                                                                                                        
$ cypress run                                                                                                                                            
  cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/home/nodetest-cypress/node_modules/.bin/cypress","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +19ms
  cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:runner-ui': [Function (anonymous)], 'option:no-runner-ui': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 25, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/nodetest-cypress/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false } ] +16ms
  cypress:cli:cli variable-length opts parsed { args: [ '/usr/local/bin/node', '/home/nodetest-cypress/node_modules/.bin/cypress', 'run' ], opts: Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:runner-ui': [Function (anonymous)], 'option:no-runner-ui': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 25, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/nodetest-cypress/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false } } +780ms
  cypress:cli parsed cli options {} +843ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable +6ms
  cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable +1ms
  cypress:cli using environment variable CYPRESS_CACHE_FOLDER /root/.cache/Cypress +0ms
  cypress:cli checking environment variables +13ms
  cypress:cli checking if executable exists /root/.cache/Cypress/13.15.1/Cypress/Cypress +69ms
  cypress:cli Binary is executable? : true +96ms
  cypress:cli binaryDir is  /root/.cache/Cypress/13.15.1/Cypress +4ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/13.15.1/Cypress/resources/app/package.json +180ms
  cypress:cli Found binary version 13.15.1 installed in: /root/.cache/Cypress/13.15.1/Cypress +32ms
  cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/13.15.1/binary_state.json" +37ms
  cypress:cli {} +3ms
  cypress:cli is Verified ? undefined +19ms
  cypress:cli running binary verification check 13.15.1 +3ms

  cypress:cli clearing out the verified version +63ms
  cypress:cli DISPLAY environment variable is set to :99 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +18ms
  cypress:cli spawning, should retry on display problem? true +2ms
  cypress:cli disabling Electron sandbox +2ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /root/.cache/Cypress/13.15.1/Cypress/Cypress +1ms
  cypress:cli smoke test command: /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
    at makeError (/home/nodetest-cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/nodetest-cypress/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632',
  command: '/root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632',
  exitCode: undefined,
  signal: 'SIGSEGV',
  signalDescription: 'Segmentation fault',
  stdout: '',
  stderr: 'qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n' +
    'qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n' +
    '[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n' +
    'qemu: uncaught target signal 11 (Segmentation fault) - core dumped',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2s
  cypress:cli error message: qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
qemu: uncaught target signal 11 (Segmentation fault) - core dumped +9ms
```
### Cypress Version

13.13.3

### Node version

v20.18.0

### Operating System

Windows 

### Debug Logs

```shell
i run DEBUG=cypress:* yarn cy:run.
This is Log:
DEBUG=cypress:* yarn cy:run          
yarn run v1.22.22                                                                                                                                        
$ cypress run                                                                                                                                            
  cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/home/nodetest-cypress/node_modules/.bin/cypress","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +19ms
  cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:runner-ui': [Function (anonymous)], 'option:no-runner-ui': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 25, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/nodetest-cypress/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false } ] +16ms
  cypress:cli:cli variable-length opts parsed { args: [ '/usr/local/bin/node', '/home/nodetest-cypress/node_modules/.bin/cypress', 'run' ], opts: Command { _events: [Object: null prototype] { 'option:auto-cancel-after-failures': [Function (anonymous)], 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:runner-ui': [Function (anonymous)], 'option:no-runner-ui': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 25, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/nodetest-cypress/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _storeOptionsAsPropertiesCalled: false, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _combineFlagAndOptionalValue: true, _hidden: false, _hasHelpOption: true, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, args: [], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false } } +780ms
  cypress:cli parsed cli options {} +843ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable +6ms
  cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable +1ms
  cypress:cli using environment variable CYPRESS_CACHE_FOLDER /root/.cache/Cypress +0ms
  cypress:cli checking environment variables +13ms
  cypress:cli checking if executable exists /root/.cache/Cypress/13.15.1/Cypress/Cypress +69ms
  cypress:cli Binary is executable? : true +96ms
  cypress:cli binaryDir is  /root/.cache/Cypress/13.15.1/Cypress +4ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/13.15.1/Cypress/resources/app/package.json +180ms
  cypress:cli Found binary version 13.15.1 installed in: /root/.cache/Cypress/13.15.1/Cypress +32ms
  cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/13.15.1/binary_state.json" +37ms
  cypress:cli {} +3ms
  cypress:cli is Verified ? undefined +19ms
  cypress:cli running binary verification check 13.15.1 +3ms

  cypress:cli clearing out the verified version +63ms
  cypress:cli DISPLAY environment variable is set to :99 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +18ms
  cypress:cli spawning, should retry on display problem? true +2ms
  cypress:cli disabling Electron sandbox +2ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /root/.cache/Cypress/13.15.1/Cypress/Cypress +1ms
  cypress:cli smoke test command: /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
    at makeError (/home/nodetest-cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/nodetest-cypress/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632',
  command: '/root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632',
  exitCode: undefined,
  signal: 'SIGSEGV',
  signalDescription: 'Segmentation fault',
  stdout: '',
  stderr: 'qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n' +
    'qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n' +
    '[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n' +
    'qemu: uncaught target signal 11 (Segmentation fault) - core dumped',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +2s
  cypress:cli error message: qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[2025:1028/080115.502565:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
qemu: uncaught target signal 11 (Segmentation fault) - core dumped +9ms
```

**Comment by MikeMcC399** [comment]
@XuNiWangXiang 

It looks like emulation is being used and causing an issue:

```text
cypress:cli smoke test command: /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632 +0ms
cypress:cli smoke test timeout 30000 ms +0ms
cypress:cli Smoke test failed: Error: Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
```

Please supply information about your configuration.

When you run `systeminfo` in a terminal under Windows, what do the fields say?

- OS Name
- OS Version
- System Type

Are you using Docker Desktop on Windows? If yes, which version? Is this a Beta version for Arm?
Are you using WSL2?
Which Linux operating system is running under WSL2?

What command are you using to run the Cypress Docker image as container?

If you follow the example [README > base](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md), what happens?

```shell
git clone https://github.com/cypress-io/cypress-docker-images
cd cypress-docker-images
cd examples/basic         # Use a pre-configured simple Cypress E2E project
npm ci                    # Install Cypress
docker run -it --rm -v .:/e2e -w /e2e cypress/base  # Run image as container
```

then at the OS `bash` prompt `/e2e#`:

```shell
npx cypress install
npx cypress run
```

**Comment by XuNiWangXiang** [comment]
> @XuNiWangXiang
> 
> It looks like emulation is being used and causing an issue:
> 
> ```
> cypress:cli smoke test command: /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632 +0ms
> cypress:cli smoke test timeout 30000 ms +0ms
> cypress:cli Smoke test failed: Error: Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/13.15.1/Cypress/Cypress --no-sandbox --smoke-test --ping=632
> qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
> qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
> ```
> 
> Please supply information about your configuration.
> 
> When you run `systeminfo` in a terminal under Windows, what do the fields say?
> 
> * OS Name
> * OS Version
> * System Type
> 
> Are you using Docker Desktop on Windows? If yes, which version? Is this a Beta version for Arm? Are you using WSL2? Which Linux operating system is running under WSL2?
> 
> What command are you using to run the Cypress Docker image as container?
> 
> If you follow the example [README > base](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md), what happens?
> 
> ```shell
> git clone https://github.com/cypress-io/cypress-docker-images
> cd cypress-docker-images
> cd examples/basic         # Use a pre-configured simple Cypress E2E project
> npm ci                    # Install Cypress
> docker run -it --rm -v .:/e2e -w /e2e cypress/base  # Run image as container
> ```
> 
> then at the OS `bash` prompt `/e2e#`:
> 
> ```shell
> npx cypress install
> npx cypress run
> ```

/
What command are you using to run the Cypress Docker image as container?
> Platform: linux-arm64 (Debian - 12.7)
Cypress Version: 12.17.0
Node.js: v18.16.0
Docker run in Linux：
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

If you follow the example [README > base](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md), what happens?
> I installed Cypress in the image using yarn install and ran yarn cypress run. (The version of Cypress is managed in the package.json file.)

**Comment by MikeMcC399** [comment]
@XuNiWangXiang 

You write that you are using CentOS Linux 8 to run Docker, however I don't see answers to the other questions, which would clarify other details of your configuration and how you are using the Cypress Docker image.

You may be able to get help from the Docker community.
