### ISSUE TITLE
Support --dev mode with Yarn Modern Plug'n'Play (pnp)

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#30656]
### What would you like?

Following the instructions in [CONTRIBUTING > Getting Started](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started) should allow selecting and running an otherwise working Cypress (E2E) project using Yarn Modern pnp without error.

Cypress however fails with the error

> Your configFile is invalid

and the stack trace shows

> Error: Cannot find module 'cypress'

where it presumably is trying to look for `cypress` in the non-existent `node_modules` directory, that is not created for Yarn Modern pnp configurations.

### Why is this needed?

[Yarn Modern Plug'n'Play](https://yarnpkg.com/features/pnp) is the default installation strategy for new Yarn Modern installations (in which case [`.yarnrc.yml` > `nodeLinker`](https://yarnpkg.com/configuration/yarnrc#nodeLinker) is undefined). Setting `nodeLinker` explicitly to `pnp` also has the same effect.

It should be possible to test the WIP Cypress [develop](https://github.com/cypress-io/cypress/tree/develop) branch against a default Yarn Modern E2E project.

The `--project` option is not suitable here because it uses the `package.json`file  (and by implication the package manager) of the root directory. `--project` does not allow to use a different package manager.

#### Steps to reproduce error

Ubuntu `24.04.3` LTS, Node.js ~~`v22.14.0`~~ `v22.19.0`

```shell
corepack enable yarn

git clone https://github.com/cypress-io/github-action
cd github-action
cd examples/yarn-modern-pnp
yarn
cd ../../..
git clone https://github.com/cypress-io/cypress
cd cypress
n auto # or set Node.js manually according to .node-version
yarn
yarn cypress run --project ../github-action/examples/yarn-modern-pnp --dev
```

#### Logs

```
$ yarn cypress run --project ../github-action/examples/yarn-modern-pnp --dev
yarn run v1.22.22
$ /home/mike/github/tmp/cy-yarn-pnp-test/cypress/node_modules/.bin/cypress run --project ../github-action/examples/yarn-modern-pnp --dev

DevTools listening on ws://127.0.0.1:39029/devtools/browser/eb4abf83-1e72-4e00-a7e7-8a4844eb6198
Your configFile is invalid: /home/mike/github/tmp/cy-yarn-pnp-test/github-action/examples/yarn-modern-pnp/cypress.config.js

It threw an error when required, check the stack trace below:

Error: Cannot find module 'cypress'
Require stack:
- /home/mike/github/tmp/cy-yarn-pnp-test/github-action/examples/yarn-modern-pnp/cypress.config.js
- /home/mike/github/tmp/cy-yarn-pnp-test/cypress/packages/server/lib/plugins/child/run_require_async_child.js
- /home/mike/github/tmp/cy-yarn-pnp-test/cypress/packages/server/lib/plugins/child/require_async_child.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/mike/github/tmp/cy-yarn-pnp-test/github-action/examples/yarn-modern-pnp/cypress.config.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at loadFile (/home/mike/github/tmp/cy-yarn-pnp-test/cypress/packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/home/mike/github/tmp/cy-yarn-pnp-test/cypress/packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:514:28)
    at process.<anonymous> (/home/mike/github/tmp/cy-yarn-pnp-test/cypress/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:514:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Related

- See https://github.com/cypress-io/cypress/labels/package%20manager%3A%20yarn for [related open Yarn issues](https://github.com/cypress-io/cypress/labels/package%20manager%3A%20yarn)

**Comment by MikeMcC399** [comment]
This is not resolved. Cypress.io should decide if they want to put in the investment to support Yarn Plug'n'Play which would need enhancements across the board. The Cypress app expects there to be a classic `node_modules` folder available, and if not it fails all over the place. Possibly there should just be a clear statement that Yarn Plug'n'Play is simply not supported, and never will be, if there are no plans and no strategy to cover Yarn Plug'n'Play consistently in the future.

**Comment by MikeMcC399** [comment]
Installing dependencies with Yarn Plug'n'Play enabled, outputs the warning:

> ESM support for PnP uses the experimental loader API and is therefore experimental

Yarn Plug'n'Play has had several compatibility issues with Node.js lately (for example with Node.js 24.15.0) due to its experimental nature.

Experiments are generally not suitable for production usage, so I'm withdrawing this request to support Yarn Plug'n'Play. It can be reviewed if Yarn Plug'n'Play migrates to using supported APIs.

Yarn Modern with `nodeLinker node-modules` is not affected by these issues.
