### ISSUE TITLE
Cypress errored in Azure DevOps CI/CD

### ISSUE THREAD

**Issue by LeBwa1221** [cypress-io/cypress#30687]
### Current behavior

I'm using Cypress v13.1.0 and update it to the latest version 13.16.0, locally it works fine, but when I try to run tests in Azure DevOps, I see this error:
```
[FAILED] Cypress failed to start.
[FAILED] 
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] Please refer to the error below for more details.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Command failed with exit code 3221225785: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: win32-x64 (6.3.9600)
[FAILED] Cypress Version: 13.16.0
```

### Test code to reproduce

There is no specific code to provide here, it doesn't work at all.

### Cypress Version

13.16.0

### Node version

22.11.0 x64

### Operating System

win32-x64 (6.3.9600)

### Debug Logs

```shell
cypress:cli verifying Cypress app
cypress:cli checking environment variables
cypress:cli Binary is executable? : true
cypress:cli {}
cypress:cli is Verified ? undefined
cypress:cli running binary verification check 13.16.0
It looks like this is your first time using Cypress: 13.16.0

[STARTED] Task without title.
cypress:cli clearing out the verified version
cypress:cli needs Xvfb? false
cypress:cli spawning, should retry on display problem? false
cypress:cli running smoke test
cypress:cli using Cypress executable <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe
cypress:cli smoke test command: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830
cypress:cli smoke test timeout 30000 ms
cypress:cli Smoke test failed: Error: Command failed with exit code 3221225785: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830
    at makeError (J:\azagent\P2\_work\r67\a\imeexternalapi\ImeApi\cypress\node_modules\execa\lib\error.js:59:11)
    at handlePromise (J:\azagent\P2\_work\r67\a\imeexternalapi\ImeApi\cypress\node_modules\execa\index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  shortMessage: 'Command failed with exit code 3221225785: <path>\\Cypress\\Cache\\13.16.0\\Cypress\\Cypress.exe --smoke-test --ping=830',
  command: '<path>\\Cypress\\Cache\\13.16.0\\Cypress\\Cypress.exe --smoke-test --ping=830',
  exitCode: 3221225785,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
cypress:cli error message: Command failed with exit code 3221225785: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830
cypress:cli detecting arch { osPlatform: 'win32', osArch: 'x64' }
[FAILED] Cypress failed to start.
[FAILED] 
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] Please refer to the error below for more details.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Command failed with exit code 3221225785: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: win32-x64 (6.3.9600)
[FAILED] Cypress Version: 13.16.0
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 3221225785: <path>\Cypress\Cache\13.16.0\Cypress\Cypress.exe --smoke-test --ping=830

----------

Platform: win32-x64 (6.3.9600)
Cypress Version: 13.16.0
```

**Comment by MikeMcC399** [comment]
@LeBIIIa 

- The same problem was reported in https://github.com/cypress-io/cypress/issues/28598 where the user reported they solved the problem by updating the Windows agent version.

According to https://en.wikipedia.org/wiki/Ver_(command), the version string `6.3.9600` is used by Windows 8.1 Update 1 /
Windows Server 2012 R2. These are old software versions.

**Comment by LeBwa1221** [comment]
@MikeMcC399 thanks for the reply! I was looking for similar problem but didn't find this topic...
I will close the issue.
