### ISSUE TITLE
spawn cmd ENOENT

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3093]
### Current behavior:

Getting an error when using Module API (`cypress.run`). Some notes:
* Running under Jenkins from Windows. The error doesn't happen when running outside of Jenkins.
* Using TypeScript and `@cypress/webpack-preprocessor`

```
Running specs: [...]
{ Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: 
   [ '/c',
     'WMIC path win32_process get Name,Processid,ParentProcessId,Commandline' ] }
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
### Versions

Cypress 3.1.4, Windows 10, Jenkins 2.150.1

**Comment by fr0** [comment]
Adding C:\Windows\System32 to my system PATH (not user PATH) fixed it; I don't think this has anything to do with cypress.
