### ISSUE TITLE
Got install error from cypress install

### ISSUE THREAD

**Issue by yuanyuanlimaggie** [cypress-io/cypress#3179]
Hi, my cypress tests were all good in gitlab. But started 1 week ago, it has cypress install error and always install failed now. 

### Current behavior:

Gitlab cypress tests fail at the first step: installation:
```
$ yarn cypress:install
yarn run v1.10.1
$ cypress install
/frontend/node_modules/cypress/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                         ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (
/frontend/node_modules/cypress/node_modules/chalk/index.js:72:75)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/frontend/node_modules/cypress/lib/util.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior:

Cypress install successfully in gitlab like it did before. 

### Versions

npm package: "cypress": "^3.1.0"
image: cypress/base:10
gitlab: 11.5.4

**Comment by jennifer-shehane** [comment]
Hey @yuanyuanlimaggie, could you verify that this is happening on a specific version of Cypress? So, update your npm package.json to describe a specific version like `3.1.4` - run, then go down to `3.1.3`, etc. After doing this, can you specify which versions throw the error and which don't? Thanks.

**Comment by yuanyuanlimaggie** [comment]
After downgrade to Cypress 3.1.3. it solved the problem. Thanks! @jennifer-shehane .

**Comment by jennifer-shehane** [comment]
You may also want to try version 3.1.5 - this may have been fixed.
