### ISSUE TITLE
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by DmitryBaldinTutu** [cypress-io/cypress#3193]
Hello!
I have a very strange problem. After starting tests in my second project by Cypress I have strange error.

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:89:17)
    at Server.addContext (_tls_wrap.js:959:32)
    at /Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:185:28
    at tryCatcher (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/baldin/Library/Caches/Cypress/3.1.4/Cypress.app/Contents/Resources/app/packages/https-proxy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

But my colleges don't have this problem. And I didn't have with problem with my first project. 
The error appears on a specific url. Another urls work correct.

I have macOS High Sierra 10.13.4

**Comment by jennifer-shehane** [comment]
Hey @DmitryBaldinTutu, can you provide the specific url that is causing the issue? If you do not want to make public, you can email to support@cypress.io 

Googling this issue seems to indicate there is some kind of certificate issue.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
