### ISSUE TITLE
Element covered by iframe

### ISSUE THREAD

**Issue by azdanov** [cypress-io/cypress#3418]
### Current behavior:

When running tests in CircleCI this issue appears with `cy.click()`. I don't understand where this `iframe` comes from or why it interferes only in CI. I using tried both Electron and Chrome.

<details>
	<summary>Error Log Excerpt</summary>
	
```
  Running: navigation.ts...                                                                (3 of 6) 


  navigation
    ✓ should have navigation buttons (725ms)
    ✓ should have home with proper url (514ms)
    1) should change language to estonian and back to english


  2 passing (6s)
  1 failing

  1) navigation should change language to estonian and back to english:
     CypressError: Timed out retrying: cy.click() failed because this element:

<a data-language="en" href="en" class="item">English</a>

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)
```
</details>

<details>
	<summary>Full Error Log</summary>

```
#!/bin/bash -eo pipefail
npx cypress run \
   \
   --browser chrome  \
  

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.5                                                                              │
  │ Browser:    Chrome 69                                                                          │
  │ Specs:      6 found (footer.ts, hero.ts, navigation.ts, results.ts, search.ts, translation.ts) │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: footer.ts...                                                                    (1 of 6) 


  footer
    ✓ should exist with current year (7785ms)


  1 passing (8s)


  (Results)

  ┌─────────────────────────┐
  │ Tests:        1         │
  │ Passing:      1         │
  │ Failing:      0         │
  │ Pending:      0         │
  │ Skipped:      0         │
  │ Screenshots:  0         │
  │ Video:        false     │
  │ Duration:     7 seconds │
  │ Spec Ran:     footer.ts │
  └─────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: hero.ts...                                                                      (2 of 6) 


  hero
    ✓ should have hero text (713ms)


  1 passing (790ms)


  (Results)

  ┌─────────────────────────┐
  │ Tests:        1         │
  │ Passing:      1         │
  │ Failing:      0         │
  │ Pending:      0         │
  │ Skipped:      0         │
  │ Screenshots:  0         │
  │ Video:        false     │
  │ Duration:     0 seconds │
  │ Spec Ran:     hero.ts   │
  └─────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: navigation.ts...                                                                (3 of 6) 


  navigation
    ✓ should have navigation buttons (725ms)
    ✓ should have home with proper url (514ms)
    1) should change language to estonian and back to english


  2 passing (6s)
  1 failing

  1) navigation should change language to estonian and back to english:
     CypressError: Timed out retrying: cy.click() failed because this element:

<a data-language="en" href="en" class="item">English</a>

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)




  (Results)

  ┌─────────────────────────────┐
  │ Tests:        3             │
  │ Passing:      2             │
  │ Failing:      1             │
  │ Pending:      0             │
  │ Skipped:      0             │
  │ Screenshots:  1             │
  │ Video:        false         │
  │ Duration:     5 seconds     │
  │ Spec Ran:     navigation.ts │
  └─────────────────────────────┘


  (Screenshots)

  - /root/project/cypress/screenshots/navigation.ts/navigation -- should change language to estonian and back to english (failed).png (1050x932)


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: results.ts...                                                                   (4 of 6) 


  results
    1) should show results on enter
    2) should show results on action button click
    3) should show loading


  0 passing (14s)
  3 failing

  1) results should show results on enter:
     CypressError: Timed out retrying: cy.click() failed because this element:

<input placeholder="Search for a word …" type="text" value="">

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)

  2) results should show results on action button click:
     CypressError: Timed out retrying: cy.type() failed because this element:

<input placeholder="Search for a word …" type="text" value="">

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)

  3) results should show loading:
     CypressError: Timed out retrying: cy.type() failed because this element:

<input placeholder="Search for a word …" type="text" value="">

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)




  (Results)

  ┌──────────────────────────┐
  │ Tests:        3          │
  │ Passing:      0          │
  │ Failing:      3          │
  │ Pending:      0          │
  │ Skipped:      0          │
  │ Screenshots:  3          │
  │ Video:        false      │
  │ Duration:     13 seconds │
  │ Spec Ran:     results.ts │
  └──────────────────────────┘


  (Screenshots)

  - /root/project/cypress/screenshots/results.ts/results -- should show results on enter (failed).png (1050x932)
  - /root/project/cypress/screenshots/results.ts/results -- should show results on action button click (failed).png (1050x932)
  - /root/project/cypress/screenshots/results.ts/results -- should show loading (failed).png (1050x932)


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: search.ts...                                                                    (5 of 6) 


  search
    ✓ should find search bar (784ms)
    ✓ should find action button (304ms)


  2 passing (1s)


  (Results)

  ┌─────────────────────────┐
  │ Tests:        2         │
  │ Passing:      2         │
  │ Failing:      0         │
  │ Pending:      0         │
  │ Skipped:      0         │
  │ Screenshots:  0         │
  │ Video:        false     │
  │ Duration:     1 second  │
  │ Spec Ran:     search.ts │
  └─────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: translation.ts...                                                               (6 of 6) 


  translation
    ✓ should have home (1005ms)
    ✓ should have hero text
    ✓ should find search bar (42ms)
    1) should show results


  3 passing (5s)
  1 failing

  1) translation should show results:
     CypressError: Timed out retrying: cy.click() failed because this element:

<input placeholder="Otsi sõna …" type="text" value="">

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:65275:17)
      at Object.retry (http://localhost:3000/__cypress/runner/cypress_runner.js:58816:16)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:50595:19)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:124569:29)
      at tryFn (http://localhost:3000/__cypress/runner/cypress_runner.js:59052:24)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:59080:12)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:58840:16
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:125394:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:125339:18)




  (Results)

  ┌──────────────────────────────┐
  │ Tests:        4              │
  │ Passing:      3              │
  │ Failing:      1              │
  │ Pending:      0              │
  │ Skipped:      0              │
  │ Screenshots:  1              │
  │ Video:        false          │
  │ Duration:     5 seconds      │
  │ Spec Ran:     translation.ts │
  └──────────────────────────────┘


  (Screenshots)

  - /root/project/cypress/screenshots/translation.ts/translation -- should show results (failed).png (1050x932)


====================================================================================================

  (Run Finished)


      Spec                                                Tests  Passing  Failing  Pending  Skipped 
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔ footer.ts                                 00:07        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔ hero.ts                                   790ms        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖ navigation.ts                             00:05        3        2        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖ results.ts                                00:13        3        -        3        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔ search.ts                                 00:01        2        2        -        -        - │
  ├─────────────────────────────────────────────���──────────────────────────────────────────────────┤
  │ ✖ translation.ts                            00:05        4        3        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    3 of 6 failed (50%)                         00:34       14        9        5        -        -  

Exited with code 5
```
</details>

### Desired behavior:

This only happens on CI. When running test locally no issues occur.

### Steps to reproduce: (app code and test code)

My app uses a number of React dependencies on top of Create React App. Maybe something is interfering.

Here is the GitHub repo: https://github.com/azdanov/translations

I would be glad to produce a minimal repo, but don't see where this originates.

### Versions

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome69
          browser: chrome
          start: 'npm test'
```

```json
"cypress": "3.1.5",
```

**Comment by azdanov** [comment]
Ok, I found the culprit. Lack of sleep..

I added a directory inside my `src` folder to `.gitignore`, which made the app work locally, but not on CI.

💤

**Comment by bahmutov** [comment]
🛌

**Comment by NurbekGithub** [comment]
Hey! I have the same issue and my .gitignore seems fine. What else might cause this?
---
Error log:
CypressError: Timed out retrying: cy.click() failed because this element:

<a class="MuiListItem-root MuiListItem-gutters MuiListItem-divider" href="/restaurants/1">Sushi P...</a>

is being covered by another element:

<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
---
### my git repo: https://github.com/NurbekGithub/tdd-cra

**Comment by jennifer-shehane** [comment]
@NurbekGithub If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
