### ISSUE TITLE
Cannot make the mochawesome to work

### ISSUE THREAD

**Issue by karthikamirapu** [cypress-io/cypress#3698]
I am having hard time to make the mochawesome work with cypress. I followed the instructions in the website and installed everything that I should but I always get this error while running the specs 

TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/Users/qa-engg/Documents/testing_tools/node_modules/mocha/lib/reporters/base.js:318:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:239:55)
    at Object.server.startWebsockets.onMocha (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:296:22)
    at Socket.<anonymous> (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/Users/qa-engg/Documents/testing_tools/node_modules/mocha/lib/reporters/base.js:318:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:239:55)
    at Object.server.startWebsockets.onMocha (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:296:22)
    at Socket.<anonymous> (/Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /Users/qa-engg/Library/Caches/Cypress/3.1.5/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

My package.json dev dependencies are here -

  "devDependencies": {
    "cypress": "^3.1.5",
    "mocha": "^6.0.2",
    "mochawesome": "^3.1.1"
  }

Any help is greatly appreciated.

**Comment by bahmutov** [comment]
Try using Mocha v5

**Comment by karthikamirapu** [comment]
It works, thanks so much.
