### ISSUE TITLE
Error while trying to install cypress with ubuntu 18.04

### ISSUE THREAD

**Issue by 0xIslamTaha** [cypress-io/cypress#3841]
## Description:
Error while trying to install cypress with ubuntu 18.04

```bash
mkdir cypressTest
cd cypressTest
npm init
npm install cypress --save-dev                                                                                                                                                                   
```

### Actual result:
```bash
!10391

> cypress@3.2.0 postinstall /root/cypresstest/node_modules/cypress
> node index.js --exec install

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/root/cypresstest/node_modules/cypress/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm WARN cypresstest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.2.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xtrremx/.npm/_logs/2019-03-28T08_33_18_514Z-debug.log
```

## Env:
OS: ubuntu 18.04 64bit
npm: 6.7.0

**Comment by jennifer-shehane** [comment]
Is there any extra information in the `/home/xtrremx/.npm/_logs/2019-03-28T08_33_18_514Z-debug.log`?

**Comment by 0xIslamTaha** [comment]
```
4723 silly postinstall repeating@2.0.1
4724 info lifecycle repeating@2.0.1~postinstall: repeating@2.0.1
4725 silly postinstall indent-string@2.1.0
4726 info lifecycle indent-string@2.1.0~postinstall: indent-string@2.1.0
4727 silly postinstall restore-cursor@1.0.1
4728 info lifecycle restore-cursor@1.0.1~postinstall: restore-cursor@1.0.1
4729 silly postinstall cli-cursor@1.0.2
4730 info lifecycle cli-cursor@1.0.2~postinstall: cli-cursor@1.0.2
4731 silly postinstall log-update@1.0.2
4732 info lifecycle log-update@1.0.2~postinstall: log-update@1.0.2
4733 silly postinstall safe-buffer@5.1.2
4734 info lifecycle safe-buffer@5.1.2~postinstall: safe-buffer@5.1.2
4735 silly postinstall safer-buffer@2.1.2
4736 info lifecycle safer-buffer@2.1.2~postinstall: safer-buffer@2.1.2
4737 silly postinstall asn1@0.2.4
4738 info lifecycle asn1@0.2.4~postinstall: asn1@0.2.4
4739 silly postinstall ecc-jsbn@0.1.2
4740 info lifecycle ecc-jsbn@0.1.2~postinstall: ecc-jsbn@0.1.2
4741 silly postinstall semver@5.7.0
4742 info lifecycle semver@5.7.0~postinstall: semver@5.7.0
4743 silly postinstall shebang-regex@1.0.0
4744 info lifecycle shebang-regex@1.0.0~postinstall: shebang-regex@1.0.0
4745 silly postinstall shebang-command@1.2.0
4746 info lifecycle shebang-command@1.2.0~postinstall: shebang-command@1.2.0
4747 silly postinstall signal-exit@3.0.2
4748 info lifecycle signal-exit@3.0.2~postinstall: signal-exit@3.0.2
4749 silly postinstall slice-ansi@0.0.4
4750 info lifecycle slice-ansi@0.0.4~postinstall: slice-ansi@0.0.4
4751 silly postinstall stream-to-observable@0.1.0
4752 info lifecycle stream-to-observable@0.1.0~postinstall: stream-to-observable@0.1.0
4753 silly postinstall string_decoder@1.1.1
4754 info lifecycle string_decoder@1.1.1~postinstall: string_decoder@1.1.1
4755 silly postinstall strip-ansi@3.0.1
4756 info lifecycle strip-ansi@3.0.1~postinstall: strip-ansi@3.0.1
4757 silly postinstall chalk@1.1.3
4758 info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
4759 silly postinstall chalk@1.1.3
4760 info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
4761 silly postinstall log-symbols@1.0.2
4762 info lifecycle log-symbols@1.0.2~postinstall: log-symbols@1.0.2
4763 silly postinstall chalk@1.1.3
4764 info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
4765 silly postinstall listr-verbose-renderer@0.4.1
4766 info lifecycle listr-verbose-renderer@0.4.1~postinstall: listr-verbose-renderer@0.4.1
4767 silly postinstall chalk@1.1.3
4768 info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
4769 silly postinstall log-symbols@1.0.2
4770 info lifecycle log-symbols@1.0.2~postinstall: log-symbols@1.0.2
4771 silly postinstall chalk@1.1.3
4772 info lifecycle chalk@1.1.3~postinstall: chalk@1.1.3
4773 silly postinstall ora@0.2.3
4774 info lifecycle ora@0.2.3~postinstall: ora@0.2.3
4775 silly postinstall string-width@1.0.2
4776 info lifecycle string-width@1.0.2~postinstall: string-width@1.0.2
4777 silly postinstall cli-truncate@0.2.1
4778 info lifecycle cli-truncate@0.2.1~postinstall: cli-truncate@0.2.1
4779 silly postinstall listr-update-renderer@0.2.0
4780 info lifecycle listr-update-renderer@0.2.0~postinstall: listr-update-renderer@0.2.0
4781 silly postinstall strip-eof@1.0.0
4782 info lifecycle strip-eof@1.0.0~postinstall: strip-eof@1.0.0
4783 silly postinstall supports-color@5.5.0
4784 info lifecycle supports-color@5.5.0~postinstall: supports-color@5.5.0
4785 silly postinstall chalk@2.4.2
4786 info lifecycle chalk@2.4.2~postinstall: chalk@2.4.2
4787 silly postinstall symbol-observable@1.0.1
4788 info lifecycle symbol-observable@1.0.1~postinstall: symbol-observable@1.0.1
4789 silly postinstall rxjs@5.5.12
4790 info lifecycle rxjs@5.5.12~postinstall: rxjs@5.5.12
4791 silly postinstall throttleit@0.0.2
4792 info lifecycle throttleit@0.0.2~postinstall: throttleit@0.0.2
4793 silly postinstall punycode@1.4.1
4794 info lifecycle punycode@1.4.1~postinstall: punycode@1.4.1
4795 silly postinstall tough-cookie@2.4.3
4796 info lifecycle tough-cookie@2.4.3~postinstall: tough-cookie@2.4.3
4797 silly postinstall tunnel-agent@0.6.0
4798 info lifecycle tunnel-agent@0.6.0~postinstall: tunnel-agent@0.6.0
4799 silly postinstall tweetnacl@0.14.5
4800 info lifecycle tweetnacl@0.14.5~postinstall: tweetnacl@0.14.5
4801 silly postinstall bcrypt-pbkdf@1.0.2
4802 info lifecycle bcrypt-pbkdf@1.0.2~postinstall: bcrypt-pbkdf@1.0.2
4803 silly postinstall sshpk@1.16.1
4804 info lifecycle sshpk@1.16.1~postinstall: sshpk@1.16.1
4805 silly postinstall typedarray@0.0.6
4806 info lifecycle typedarray@0.0.6~postinstall: typedarray@0.0.6
4807 silly postinstall universalify@0.1.2
4808 info lifecycle universalify@0.1.2~postinstall: universalify@0.1.2
4809 silly postinstall uri-js@4.2.2
4810 info lifecycle uri-js@4.2.2~postinstall: uri-js@4.2.2
4811 silly postinstall ajv@6.10.0
4812 info lifecycle ajv@6.10.0~postinstall: ajv@6.10.0
4813 silly postinstall har-validator@5.1.3
4814 info lifecycle har-validator@5.1.3~postinstall: har-validator@5.1.3
4815 silly postinstall punycode@1.3.2
4816 info lifecycle punycode@1.3.2~postinstall: punycode@1.3.2
4817 silly postinstall util-deprecate@1.0.2
4818 info lifecycle util-deprecate@1.0.2~postinstall: util-deprecate@1.0.2
4819 silly postinstall readable-stream@2.3.6
4820 info lifecycle readable-stream@2.3.6~postinstall: readable-stream@2.3.6
4821 silly postinstall concat-stream@1.6.2
4822 info lifecycle concat-stream@1.6.2~postinstall: concat-stream@1.6.2
4823 silly postinstall uuid@3.3.2
4824 info lifecycle uuid@3.3.2~postinstall: uuid@3.3.2
4825 silly postinstall verror@1.10.0
4826 info lifecycle verror@1.10.0~postinstall: verror@1.10.0
4827 silly postinstall jsprim@1.4.1
4828 info lifecycle jsprim@1.4.1~postinstall: jsprim@1.4.1
4829 silly postinstall http-signature@1.2.0
4830 info lifecycle http-signature@1.2.0~postinstall: http-signature@1.2.0
4831 silly postinstall which@1.3.1
4832 info lifecycle which@1.3.1~postinstall: which@1.3.1
4833 silly postinstall cross-spawn@6.0.5
4834 info lifecycle cross-spawn@6.0.5~postinstall: cross-spawn@6.0.5
4835 silly postinstall wrappy@1.0.2
4836 info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
4837 silly postinstall once@1.4.0
4838 info lifecycle once@1.4.0~postinstall: once@1.4.0
4839 silly postinstall inflight@1.0.6
4840 info lifecycle inflight@1.0.6~postinstall: inflight@1.0.6
4841 silly postinstall fd-slicer@1.1.0
4842 info lifecycle fd-slicer@1.1.0~postinstall: fd-slicer@1.1.0
4843 silly postinstall @cypress/listr-verbose-renderer@0.4.1
4844 info lifecycle @cypress/listr-verbose-renderer@0.4.1~postinstall: @cypress/listr-verbose-renderer@0.4.1
4845 silly postinstall @cypress/xvfb@1.2.4
4846 info lifecycle @cypress/xvfb@1.2.4~postinstall: @cypress/xvfb@1.2.4
4847 silly postinstall bluebird@3.5.0
4848 info lifecycle bluebird@3.5.0~postinstall: bluebird@3.5.0
4849 silly postinstall cachedir@1.3.0
4850 info lifecycle cachedir@1.3.0~postinstall: cachedir@1.3.0
4851 silly postinstall check-more-types@2.24.0
4852 info lifecycle check-more-types@2.24.0~postinstall: check-more-types@2.24.0
4853 silly postinstall commander@2.15.1
4854 info lifecycle commander@2.15.1~postinstall: commander@2.15.1
4855 silly postinstall common-tags@1.8.0
4856 info lifecycle common-tags@1.8.0~postinstall: common-tags@1.8.0
4857 silly postinstall execa@0.10.0
4858 info lifecycle execa@0.10.0~postinstall: execa@0.10.0
4859 silly postinstall executable@4.1.1
4860 info lifecycle executable@4.1.1~postinstall: executable@4.1.1
4861 silly postinstall extract-zip@1.6.7
4862 info lifecycle extract-zip@1.6.7~postinstall: extract-zip@1.6.7
4863 silly postinstall fs-extra@4.0.1
4864 info lifecycle fs-extra@4.0.1~postinstall: fs-extra@4.0.1
4865 silly postinstall getos@3.1.0
4866 info lifecycle getos@3.1.0~postinstall: getos@3.1.0
4867 silly postinstall glob@7.1.3
4868 info lifecycle glob@7.1.3~postinstall: glob@7.1.3
4869 silly postinstall is-ci@1.2.1
4870 info lifecycle is-ci@1.2.1~postinstall: is-ci@1.2.1
4871 silly postinstall is-installed-globally@0.1.0
4872 info lifecycle is-installed-globally@0.1.0~postinstall: is-installed-globally@0.1.0
4873 silly postinstall lazy-ass@1.6.0
4874 info lifecycle lazy-ass@1.6.0~postinstall: lazy-ass@1.6.0
4875 silly postinstall listr@0.12.0
4876 info lifecycle listr@0.12.0~postinstall: listr@0.12.0
4877 silly postinstall log-symbols@2.2.0
4878 info lifecycle log-symbols@2.2.0~postinstall: log-symbols@2.2.0
4879 silly postinstall minimist@1.2.0
4880 info lifecycle minimist@1.2.0~postinstall: minimist@1.2.0
4881 silly postinstall moment@2.24.0
4882 info lifecycle moment@2.24.0~postinstall: moment@2.24.0
4883 silly postinstall ramda@0.24.1
4884 info lifecycle ramda@0.24.1~postinstall: ramda@0.24.1
4885 silly postinstall request@2.88.0
4886 info lifecycle request@2.88.0~postinstall: request@2.88.0
4887 silly postinstall request-progress@0.4.0
4888 info lifecycle request-progress@0.4.0~postinstall: request-progress@0.4.0
4889 silly postinstall tmp@0.0.33
4890 info lifecycle tmp@0.0.33~postinstall: tmp@0.0.33
4891 silly postinstall url@0.11.0
4892 info lifecycle url@0.11.0~postinstall: url@0.11.0
4893 silly postinstall yauzl@2.10.0
4894 info lifecycle yauzl@2.10.0~postinstall: yauzl@2.10.0
4895 silly postinstall cypress@3.2.0
4896 info lifecycle cypress@3.2.0~postinstall: cypress@3.2.0
4897 verbose lifecycle cypress@3.2.0~postinstall: unsafe-perm in lifecycle false
4898 verbose lifecycle cypress@3.2.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/cypresstest/node_modules/cypress/node_modules/.bin:/root/cypresstest/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
4899 verbose lifecycle cypress@3.2.0~postinstall: CWD: /root/cypresstest/node_modules/cypress
4900 silly lifecycle cypress@3.2.0~postinstall: Args: [ '-c', 'node index.js --exec install' ]
4901 silly lifecycle cypress@3.2.0~postinstall: Returned: code: 1  signal: null
4902 info lifecycle cypress@3.2.0~postinstall: Failed to exec postinstall script
4903 timing action:postinstall Completed in 53ms
4904 verbose unlock done using /home/xtrremx/.npm/_locks/staging-233604d260dd1d25.lock for /root/cypresstest/node_modules/.staging
4905 timing stage:rollbackFailedOptional Completed in 220ms
4906 timing stage:runTopLevelLifecycles Completed in 11234ms
4907 silly saveTree cypresstest@1.0.0
4907 silly saveTree └─┬ cypress@3.2.0
4907 silly saveTree   ├─┬ @cypress/listr-verbose-renderer@0.4.1
4907 silly saveTree   │ ├─┬ chalk@1.1.3
4907 silly saveTree   │ │ ├── ansi-styles@2.2.1
4907 silly saveTree   │ │ ├── escape-string-regexp@1.0.5
4907 silly saveTree   │ │ ├─┬ has-ansi@2.0.0
4907 silly saveTree   │ │ │ └── ansi-regex@2.1.1
4907 silly saveTree   │ │ ├── strip-ansi@3.0.1
4907 silly saveTree   │ │ └── supports-color@2.0.0
4907 silly saveTree   │ ├─┬ cli-cursor@1.0.2
4907 silly saveTree   │ │ └─┬ restore-cursor@1.0.1
4907 silly saveTree   │ │   ├── exit-hook@1.1.1
4907 silly saveTree   │ │   └── onetime@1.1.0
4907 silly saveTree   │ ├── date-fns@1.30.1
4907 silly saveTree   │ └─┬ figures@1.7.0
4907 silly saveTree   │   └── object-assign@4.1.1
4907 silly saveTree   ├─┬ @cypress/xvfb@1.2.4
4907 silly saveTree   │ ├─┬ debug@3.1.0
4907 silly saveTree   │ │ └── ms@2.0.0
4907 silly saveTree   │ └── lodash.once@4.1.1
4907 silly saveTree   ├── bluebird@3.5.0
4907 silly saveTree   ├─┬ cachedir@1.3.0
4907 silly saveTree   │ └── os-homedir@1.0.2
4907 silly saveTree   ├─┬ chalk@2.4.2
4907 silly saveTree   │ ├─┬ ansi-styles@3.2.1
4907 silly saveTree   │ │ └─┬ color-convert@1.9.3
4907 silly saveTree   │ │   └── color-name@1.1.3
4907 silly saveTree   │ └─┬ supports-color@5.5.0
4907 silly saveTree   │   └── has-flag@3.0.0
4907 silly saveTree   ├── check-more-types@2.24.0
4907 silly saveTree   ├── commander@2.15.1
4907 silly saveTree   ├── common-tags@1.8.0
4907 silly saveTree   ├── debug@3.1.0
4907 silly saveTree   ├─┬ execa@0.10.0
4907 silly saveTree   │ ├─┬ cross-spawn@6.0.5
4907 silly saveTree   │ │ ├── nice-try@1.0.5
4907 silly saveTree   │ │ ├── path-key@2.0.1
4907 silly saveTree   │ │ ├── semver@5.7.0
4907 silly saveTree   │ │ ├─┬ shebang-command@1.2.0
4907 silly saveTree   │ │ │ └── shebang-regex@1.0.0
4907 silly saveTree   │ │ └─┬ which@1.3.1
4907 silly saveTree   │ │   └── isexe@2.0.0
4907 silly saveTree   │ ├── get-stream@3.0.0
4907 silly saveTree   │ ├── is-stream@1.1.0
4907 silly saveTree   │ ├── npm-run-path@2.0.2
4907 silly saveTree   │ ├── p-finally@1.0.0
4907 silly saveTree   │ ├── signal-exit@3.0.2
4907 silly saveTree   │ └── strip-eof@1.0.0
4907 silly saveTree   ├─┬ executable@4.1.1
4907 silly saveTree   │ └── pify@2.3.0
4907 silly saveTree   ├─┬ extract-zip@1.6.7
4907 silly saveTree   │ ├─┬ concat-stream@1.6.2
4907 silly saveTree   │ │ ├── buffer-from@1.1.1
4907 silly saveTree   │ │ ├── inherits@2.0.3
4907 silly saveTree   │ │ ├─┬ readable-stream@2.3.6
4907 silly saveTree   │ │ │ ├── core-util-is@1.0.2
4907 silly saveTree   │ │ │ ├── isarray@1.0.0
4907 silly saveTree   │ │ │ ├── process-nextick-args@2.0.0
4907 silly saveTree   │ │ │ ├── safe-buffer@5.1.2
4907 silly saveTree   │ │ │ ├── string_decoder@1.1.1
4907 silly saveTree   │ │ │ └── util-deprecate@1.0.2
4907 silly saveTree   │ │ └── typedarray@0.0.6
4907 silly saveTree   │ ├── debug@2.6.9
4907 silly saveTree   │ ├─┬ mkdirp@0.5.1
4907 silly saveTree   │ │ └── minimist@0.0.8
4907 silly saveTree   │ └─┬ yauzl@2.4.1
4907 silly saveTree   │   └─┬ fd-slicer@1.0.1
4907 silly saveTree   │     └── pend@1.2.0
4907 silly saveTree   ├─┬ fs-extra@4.0.1
4907 silly saveTree   │ ├── graceful-fs@4.1.15
4907 silly saveTree   │ ├── jsonfile@3.0.1
4907 silly saveTree   │ └── universalify@0.1.2
4907 silly saveTree   ├─┬ getos@3.1.0
4907 silly saveTree   │ └─┬ async@2.4.0
4907 silly saveTree   │   └── lodash@4.17.11
4907 silly saveTree   ├─┬ glob@7.1.3
4907 silly saveTree   │ ├── fs.realpath@1.0.0
4907 silly saveTree   │ ├─┬ inflight@1.0.6
4907 silly saveTree   │ │ ├─┬ once@1.4.0
4907 silly saveTree   │ │ │ └── wrappy@1.0.2
4907 silly saveTree   │ │ └── wrappy@1.0.2
4907 silly saveTree   │ ├─┬ minimatch@3.0.4
4907 silly saveTree   │ │ └─┬ brace-expansion@1.1.11
4907 silly saveTree   │ │   ├── balanced-match@1.0.0
4907 silly saveTree   │ │   └── concat-map@0.0.1
4907 silly saveTree   │ ├── once@1.4.0
4907 silly saveTree   │ └── path-is-absolute@1.0.1
4907 silly saveTree   ├─┬ is-ci@1.2.1
4907 silly saveTree   │ └── ci-info@1.6.0
4907 silly saveTree   ├─┬ is-installed-globally@0.1.0
4907 silly saveTree   │ ├─┬ global-dirs@0.1.1
4907 silly saveTree   │ │ └── ini@1.3.5
4907 silly saveTree   │ └─┬ is-path-inside@1.0.1
4907 silly saveTree   │   └── path-is-inside@1.0.2
4907 silly saveTree   ├── lazy-ass@1.6.0
4907 silly saveTree   ├─┬ listr@0.12.0
4907 silly saveTree   │ ├─┬ chalk@1.1.3
4907 silly saveTree   │ │ └── supports-color@2.0.0
4907 silly saveTree   │ ├─┬ cli-truncate@0.2.1
4907 silly saveTree   │ │ ├── slice-ansi@0.0.4
4907 silly saveTree   │ │ └─┬ string-width@1.0.2
4907 silly saveTree   │ │   ├── code-point-at@1.1.0
4907 silly saveTree   │ │   └─┬ is-fullwidth-code-point@1.0.0
4907 silly saveTree   │ │     └── number-is-nan@1.0.1
4907 silly saveTree   │ ├─┬ indent-string@2.1.0
4907 silly saveTree   │ │ └─┬ repeating@2.0.1
4907 silly saveTree   │ │   └── is-finite@1.0.2
4907 silly saveTree   │ ├── is-promise@2.1.0
4907 silly saveTree   │ ├── listr-silent-renderer@1.1.1
4907 silly saveTree   │ ├─┬ listr-update-renderer@0.2.0
4907 silly saveTree   │ │ ├─┬ chalk@1.1.3
4907 silly saveTree   │ │ │ └── supports-color@2.0.0
4907 silly saveTree   │ │ ├── elegant-spinner@1.0.1
4907 silly saveTree   │ │ ├── indent-string@3.2.0
4907 silly saveTree   │ │ ├── log-symbols@1.0.2
4907 silly saveTree   │ │ └─┬ log-update@1.0.2
4907 silly saveTree   │ │   └── ansi-escapes@1.4.0
4907 silly saveTree   │ ├─┬ listr-verbose-renderer@0.4.1
4907 silly saveTree   │ │ └─┬ chalk@1.1.3
4907 silly saveTree   │ │   └── supports-color@2.0.0
4907 silly saveTree   │ ├── log-symbols@1.0.2
4907 silly saveTree   │ ├── log-update@1.0.2
4907 silly saveTree   │ ├─┬ ora@0.2.3
4907 silly saveTree   │ │ ├─┬ chalk@1.1.3
4907 silly saveTree   │ │ │ └── supports-color@2.0.0
4907 silly saveTree   │ │ └── cli-spinners@0.1.2
4907 silly saveTree   │ ├── p-map@1.2.0
4907 silly saveTree   │ ├─┬ rxjs@5.5.12
4907 silly saveTree   │ │ └── symbol-observable@1.0.1
4907 silly saveTree   │ └── stream-to-observable@0.1.0
4907 silly saveTree   ├── lodash@4.17.11
4907 silly saveTree   ├── log-symbols@2.2.0
4907 silly saveTree   ├── minimist@1.2.0
4907 silly saveTree   ├── moment@2.24.0
4907 silly saveTree   ├── ramda@0.24.1
4907 silly saveTree   ├─┬ request-progress@0.4.0
4907 silly saveTree   │ ├── node-eta@0.1.1
4907 silly saveTree   │ └── throttleit@0.0.2
4907 silly saveTree   ├─┬ request@2.88.0
4907 silly saveTree   │ ├── aws-sign2@0.7.0
4907 silly saveTree   │ ├── aws4@1.8.0
4907 silly saveTree   │ ├── caseless@0.12.0
4907 silly saveTree   │ ├─┬ combined-stream@1.0.7
4907 silly saveTree   │ │ └── delayed-stream@1.0.0
4907 silly saveTree   │ ├── extend@3.0.2
4907 silly saveTree   │ ├── forever-agent@0.6.1
4907 silly saveTree   │ ├─┬ form-data@2.3.3
4907 silly saveTree   │ │ ├── asynckit@0.4.0
4907 silly saveTree   │ │ └─┬ mime-types@2.1.22
4907 silly saveTree   │ │   └── mime-db@1.38.0
4907 silly saveTree   │ ├─┬ har-validator@5.1.3
4907 silly saveTree   │ │ ├─┬ ajv@6.10.0
4907 silly saveTree   │ │ │ ├── fast-deep-equal@2.0.1
4907 silly saveTree   │ │ │ ├── fast-json-stable-stringify@2.0.0
4907 silly saveTree   │ │ │ ├── json-schema-traverse@0.4.1
4907 silly saveTree   │ │ │ └─┬ uri-js@4.2.2
4907 silly saveTree   │ │ │   └── punycode@2.1.1
4907 silly saveTree   │ │ └── har-schema@2.0.0
4907 silly saveTree   │ ├─┬ http-signature@1.2.0
4907 silly saveTree   │ │ ├── assert-plus@1.0.0
4907 silly saveTree   │ │ ├─┬ jsprim@1.4.1
4907 silly saveTree   │ │ │ ├── extsprintf@1.3.0
4907 silly saveTree   │ │ │ ├── json-schema@0.2.3
4907 silly saveTree   │ │ │ └── verror@1.10.0
4907 silly saveTree   │ │ └─┬ sshpk@1.16.1
4907 silly saveTree   │ │   ├─┬ asn1@0.2.4
4907 silly saveTree   │ │   │ └── safer-buffer@2.1.2
4907 silly saveTree   │ │   ├─┬ bcrypt-pbkdf@1.0.2
4907 silly saveTree   │ │   │ └── tweetnacl@0.14.5
4907 silly saveTree   │ │   ├── dashdash@1.14.1
4907 silly saveTree   │ │   ├─┬ ecc-jsbn@0.1.2
4907 silly saveTree   │ │   │ └── jsbn@0.1.1
4907 silly saveTree   │ │   ├── getpass@0.1.7
4907 silly saveTree   │ │   ├── jsbn@0.1.1
4907 silly saveTree   │ │   ├── safer-buffer@2.1.2
4907 silly saveTree   │ │   └── tweetnacl@0.14.5
4907 silly saveTree   │ ├── is-typedarray@1.0.0
4907 silly saveTree   │ ├── isstream@0.1.2
4907 silly saveTree   │ ├── json-stringify-safe@5.0.1
4907 silly saveTree   │ ├── mime-types@2.1.22
4907 silly saveTree   │ ├── oauth-sign@0.9.0
4907 silly saveTree   │ ├── performance-now@2.1.0
4907 silly saveTree   │ ├── qs@6.5.2
4907 silly saveTree   │ ├─┬ tough-cookie@2.4.3
4907 silly saveTree   │ │ ├── psl@1.1.31
4907 silly saveTree   │ │ └── punycode@1.4.1
4907 silly saveTree   │ ├── tunnel-agent@0.6.0
4907 silly saveTree   │ └── uuid@3.3.2
4907 silly saveTree   ├── supports-color@5.5.0
4907 silly saveTree   ├─┬ tmp@0.0.33
4907 silly saveTree   │ └── os-tmpdir@1.0.2
4907 silly saveTree   ├─┬ url@0.11.0
4907 silly saveTree   │ ├── punycode@1.3.2
4907 silly saveTree   │ └── querystring@0.2.0
4907 silly saveTree   └─┬ yauzl@2.10.0
4907 silly saveTree     ├── buffer-crc32@0.2.13
4907 silly saveTree     └── fd-slicer@1.1.0
4908 warn cypresstest@1.0.0 No repository field.
4909 verbose stack Error: cypress@3.2.0 postinstall: `node index.js --exec install`
4909 verbose stack Exit status 1
4909 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
4909 verbose stack     at EventEmitter.emit (events.js:197:13)
4909 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4909 verbose stack     at ChildProcess.emit (events.js:197:13)
4909 verbose stack     at maybeClose (internal/child_process.js:988:16)
4909 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
4910 verbose pkgid cypress@3.2.0
4911 verbose cwd /root/cypresstest
4912 verbose Linux 4.15.0-46-generic
4913 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "cypress" "--save-dev"
4914 verbose node v11.12.0
4915 verbose npm  v6.7.0
4916 error code ELIFECYCLE
4917 error errno 1
4918 error cypress@3.2.0 postinstall: `node index.js --exec install`
4918 error Exit status 1
4919 error Failed at the cypress@3.2.0 postinstall script.
4919 error This is probably not a problem with npm. There is likely additional logging output above.
4920 verbose exit [ 1, true ]

xtrremx@0xIslamTaha ~
  %                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     !10092

```

**Comment by 0xIslamTaha** [comment]
@jennifer-shehane any updates?

**Comment by jennifer-shehane** [comment]
Sorry, nothing is pointing to the exact reason yet. Can you run the install with the DEBUG logs? https://on.cypress.io/debugging#Print-DEBUG-logs

**Comment by mark-c-woodard** [comment]
@0xIslamTaha did you resolve this? I'm getting the same issue in my ubuntu 16 environment.

@jennifer-shehane i tried running my install with the debug command
`DEBUG=cypress:* npm install cypress`

but didn't get any more logging, just saw what has already been posted above. Did I write the debug command incorrectly?

**Comment by 0xIslamTaha** [comment]
@mark-c-woodard no I didnt resolve it. I think there is a bug in building using npm.

But, U can download the binary  and run it

**Comment by kris4345** [comment]
Hi I am using mac and have the same issue
npm ERR! Failed at the cypress@3.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  can you help me please

**Comment by jg572h** [comment]
Hello.  I'm trying to install on Windows 10, and am getting the same issue:

```
Installing Cypress (version: 3.4.0)

 ×  Downloading Cypress
   → Cypress Version: 3.4.0
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.4.0?platform=win32&arch=x64
Error: connect ETIMEDOUT 104.25.215.23:443

----------

Platform: win32 (10.0.16299)
Cypress Version: 3.4.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.4.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jg572h\AppData\Roaming\npm-cache\_logs\2019-07-12T13_40_01_364Z-debug.log
```

Although the error suggests there is a problem with network connectivity, there is not; my network works just fine.  I am behind a Proxy, however.  I have npm configured to work with the Proxy, but is there other configuration that needs to be done for Cypress?

**Comment by flotwig** [comment]
@jg572h Do you have an `HTTP_PROXY` environment variable set? The CLI uses that to download the Cypress package. If not, just set `HTTP_PROXY` to the same proxy you're using for NPM.

**Comment by jg572h** [comment]
@flotwig That fixed the problem.  Thanks!

**Comment by tristanwilson-caredove** [comment]
Update to this:

The above issue was resolved for me by unchecking "Read-only" in the properties of the "C:/Users/[USER]/AppData/Local/Temp" folder.

**Comment by jonathan-martz** [comment]
I was facing the same issue with:
npm 6.13.4
ubuntu 18.04
node 12.14.0

Found another issue on google with the solution.
Try to add `--unsafe-perm=true --allow-root` to the end and for me it worked.

**Comment by miticv** [comment]
The exact same issue was happening to me. 
However when I downgraded 4.0.2 to 3.8.0, I did not get the error, and it worked fine.

**Comment by misjaz** [comment]
Currently facing this issue:
Error: Cannot find module '@cypress/listr-verbose-renderer'

My setup
npm 6.11.3
node 10.17.0
ubuntu 18.04
cypress 3.8.3

Facing same issue when running `npm install --save listr-verbose-renderer` .

**Comment by zahramemar** [comment]
The same issue for me, did anyone find any solution?

**Comment by hsnprsd** [comment]
Still having this issue. Any solution?

**Comment by pserafini** [comment]
> Try to add `--unsafe-perm=true --allow-root` to the end and for me it worked.

This worked for me and allowed me to run cypress as a dev dependency.

**Comment by bahmutov** [comment]
closing as stale.

**Comment by vijaychandra24** [comment]
This is happening to me as well 
C:\DONTWANTTOSHARE\Fun\node_modules\fs-extra\lib\mkdirs\make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\DONTWANTTOSHARE\Fun\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm WARN enoent ENOENT: no such file or directory, open 'C:\DONTWANTTOSHARE\Fun\package.json'
npm WARN Fun No description
npm WARN Fun No repository field.
npm WARN Fun No README data
npm WARN Fun No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@5.5.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@5.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
