### ISSUE TITLE
Hang in Jenkins CI when run on Windows node

### ISSUE THREAD

**Issue by judsoncarver** [cypress-io/cypress#3914]
My team runs Cypress E2E tests in Jenkins on Mac/Windows10 Jenkins nodes with latest Chrome. 

We've noticed recently that Cypress hangs indefinitely in Jenkins with certain tests on the Windows node, and it seems isolated to when it calls to `cy.screenshot` and `cy.viewport` (we resize viewport to test responsive, etc.) 

### Current behavior:

The test runs are set up in freestyle projects that execute cypress with `npm run cypress -- --browser chrome` after `npm install`. I've duplicated this with our test code, and also with the kitchen sync demo tests included with cypress too.

Same tests pass when we remote into the Windows box and run it locally - it only hangs during a job run. Same tests pass in Jenkins job on any Mac E2E VM we run against. Duplicated on Windows 10 and 7 set up as Jenkins node with latest Chrome browser installed (running headed).

To take our code out of the equation, I'd set up a repo containing just the cypress default kitchen sink tests and the run hangs when it hits `misc.spec.js`, on the `Cypress.screenshot` step. Job never fails, it just spins and continues running:

```
set DEBUG=cypress:*
call npx cypress run --browser chrome 
```

Logs (duplicating using cypress example tests, specifically the misc test that hangs):
```
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:buffers found request buffer { url: 'https://example.cypress.io/commands/misc', originalUrl: 'https://example.cypress.io/commands/misc' }
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:proxy received response for { url: 'https://example.cypress.io/commands/misc', headers: { date: 'Mon, 08 Apr 2019 21:56:40 GMT', 'content-type': 'text/html; charset=utf-8', 'transfer-encoding': 'chunked', connection: 'close', 'set-cookie': [ '__cfduid=d7c0e80bdfc3fda3175423bdac017ca241554760600; expires=Tue, 07-Apr-20 21:56:40 GMT; path=/; domain=.cypress.io; HttpOnly; Secure' ], 'last-modified': 'Fri, 15 Mar 2019 11:59:24 GMT', 'access-control-allow-origin': '*', expires: 'Mon, 08 Apr 2019 22:06:37 GMT', 'cache-control': 'max-age=600', 'x-github-request-id': '23B2:3EE6:73F20:7ED29:5CABC394', via: '1.1 varnish', age: '3', 'x-served-by': 'cache-sea1046-SEA', 'x-cache': 'HIT', 'x-cache-hits': '1', 'x-timer': 'S1554760600.322066,VS0,VE1', vary: 'Accept-Encoding', 'x-fastly-request-id': 'dbf563cf56009c212c07dc5543849229fa5fef8d', 'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', server: 'cloudflare', 'cf-ray': '4c477e17eed68cf9-PDX' }, statusCode: 200, isGzipped: undefined, wantsInjection: 'full', wantsSecurityRemoved: true }
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers clearing timer id 157 from queue { '152': { args: [], ms: 85000, cb: [Function] }, '157': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers queuing timer id 158 after 85000 ms
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers child received timer id 158
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers clearing timer id 158 from queue { '152': { args: [], ms: 85000, cb: [Function] }, '158': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers queuing timer id 159 after 85000 ms
Mon, 08 Apr 2019 21:56:39 GMT cypress:server:timers child received timer id 159

Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers clearing timer id 152 from queue { '152': { args: [], ms: 85000, cb: [Function] }, '159': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers queuing timer id 160 after 85000 ms
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:project onMocha hook end
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers child received timer id 160
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:reporter got mocha event 'hook end' with args: [ { id: 'r8', title: '"before each" hook', hookName: 'before each', hookId: 'h1', body: 'function () {\n    cy.visit(\'https://example.cypress.io/commands/misc\');\n  }', type: 'hook', duration: 154 } ]
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers clearing timer id 160 from queue { '159': { args: [], ms: 85000, cb: [Function] }, '160': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers queuing timer id 161 after 85000 ms
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:timers child received timer id 161
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:socket automation:request take:screenshot { titles: [ 'Misc', 'Cypress.Screenshot', 'cy.screenshot() - take a screenshot' ], testId: 'r8', name: 'my-image', capture: 'fullPage', clip: { x: 0, y: 0, width: 1000, height: 660 }, viewport: { width: 1024, height: 696 }, scaled: false, blackout: [], startTime: '2019-04-08T21:56:40.021Z', current: 1, total: 3 }
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:screenshot (s1) capturing screenshot { titles: [ 'Misc', 'Cypress.Screenshot', 'cy.screenshot() - take a screenshot' ], testId: 'r8', name: 'my-image', capture: 'fullPage', clip: { x: 0, y: 0, width: 1000, height: 660 }, viewport: { width: 1024, height: 696 }, scaled: false, blackout: [], startTime: '2019-04-08T21:56:40.021Z', current: 1, total: 3, specName: 'examples\\misc.spec.js' }
Mon, 08 Apr 2019 21:56:40 GMT cypress:server:screenshot (s1) capture and check { tries: 1, totalDuration: 0 }

Mon, 08 Apr 2019 21:56:41 GMT cypress:server:server Getting remote state: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null }
Mon, 08 Apr 2019 21:56:41 GMT cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://ptpxperv/', headers: { host: 'ptpxperv', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null } }
Mon, 08 Apr 2019 21:56:41 GMT cypress:server:server Getting remote state: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null }
Mon, 08 Apr 2019 21:56:41 GMT cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://jncvlekftagwa/', headers: { host: 'jncvlekftagwa', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null } }
Mon, 08 Apr 2019 21:56:41 GMT cypress:server:server Getting remote state: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null }
Mon, 08 Apr 2019 21:56:41 GMT cypress:server:proxy handling proxied request { url: '/', proxiedUrl: 'http://kstgoxraogti/', headers: { host: 'kstgoxraogti', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36', 'accept-encoding': 'gzip, deflate' }, remoteState: { auth: null, props: { port: '443', tld: 'io', domain: 'cypress' }, origin: 'https://example.cypress.io', strategy: 'http', visiting: false, domainName: 'cypress.io', fileServer: null } }

Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers queuing timer id 162 after 30000 ms
Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers child received timer id 162
Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers queuing timer id 163 after 30000 ms
Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers queuing timer id 164 after 30000 ms
Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers child received timer id 163
Mon, 08 Apr 2019 21:56:43 GMT cypress:server:timers child received timer id 164

Mon, 08 Apr 2019 21:56:45 GMT cypress:server:timers clearing timer id 162 from queue { '159': { args: [], ms: 85000, cb: [Function] }, '161': { args: [], ms: 85000, cb: [Function] }, '162': { args: [], ms: 30000, cb: [Function] }, '163': { args: [], ms: 30000, cb: [Function] }, '164': { args: [], ms: 30000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:cors Parsed URL { port: '80', tld: 'jncvlekftagwa', domain: '' }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy received response for { url: 'http://jncvlekftagwa/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy request failed { url: 'http://jncvlekftagwa/', status: 500, error: 'Error: getaddrinfo ENOTFOUND jncvlekftagwa jncvlekftagwa:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:timers clearing timer id 163 from queue { '159': { args: [], ms: 85000, cb: [Function] }, '161': { args: [], ms: 85000, cb: [Function] }, '163': { args: [], ms: 30000, cb: [Function] }, '164': { args: [], ms: 30000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:cors Parsed URL { port: '80', tld: 'kstgoxraogti', domain: '' }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy received response for { url: 'http://kstgoxraogti/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy request failed { url: 'http://kstgoxraogti/', status: 500, error: 'Error: getaddrinfo ENOTFOUND kstgoxraogti kstgoxraogti:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:timers clearing timer id 164 from queue { '159': { args: [], ms: 85000, cb: [Function] }, '161': { args: [], ms: 85000, cb: [Function] }, '164': { args: [], ms: 30000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:cors Parsed URL { port: '80', tld: 'ptpxperv', domain: '' }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy received response for { url: 'http://ptpxperv/', headers: { 'content-type': 'text/html' }, statusCode: 500, isGzipped: undefined, wantsInjection: false, wantsSecurityRemoved: false }
Mon, 08 Apr 2019 21:56:45 GMT cypress:server:proxy request failed { url: 'http://ptpxperv/', status: 500, error: 'Error: getaddrinfo ENOTFOUND ptpxperv ptpxperv:80\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)\n' }

Mon, 08 Apr 2019 21:56:59 GMT cypress:server:timers clearing timer id 159 from queue { '159': { args: [], ms: 85000, cb: [Function] }, '161': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:56:59 GMT cypress:server:timers queuing timer id 165 after 85000 ms
Mon, 08 Apr 2019 21:56:59 GMT cypress:server:timers child received timer id 165

Mon, 08 Apr 2019 21:57:02 GMT cypress:server:timers clearing timer id 161 from queue { '161': { args: [], ms: 85000, cb: [Function] }, '165': { args: [], ms: 85000, cb: [Function] } }
Mon, 08 Apr 2019 21:57:02 GMT cypress:server:timers queuing timer id 166 after 85000 ms
Mon, 08 Apr 2019 21:57:02 GMT cypress:server:timers child received timer id 166

Mon, 08 Apr 2019 21:57:03 GMT cypress:server:timers child sending timer id 3

Mon, 08 Apr 2019 21:57:06 GMT cypress:server:timers child sending timer id 27
Mon, 08 Apr 2019 21:57:07 GMT cypress:server:timers child sending timer id 34

Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 57
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 58
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 59
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 60

Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 61
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 62
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 63
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 64
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 65
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 80
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 86
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 87
Mon, 08 Apr 2019 21:57:08 GMT cypress:server:timers child sending timer id 88

Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 107
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 113
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 114
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 115
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 130
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 136
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 137
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 138
Mon, 08 Apr 2019 21:57:09 GMT cypress:server:timers child sending timer id 154

Mon, 08 Apr 2019 21:57:13 GMT cypress:server:timers child sending timer id 162
Mon, 08 Apr 2019 21:57:13 GMT cypress:server:timers child sending timer id 163
Mon, 08 Apr 2019 21:57:13 GMT cypress:server:timers child sending timer id 164
```

### Desired behavior:

Cypress tests should run identically on Mac and Windows E2E nodes.

### Steps to reproduce: (app code and test code)

1. Install latest Jenkins, connect a Windows VM or physical box configured with `node 10.15.3` and latest Chrome and git. 
2. Create a repo containing cypress and just the kitchen sync tests. 
3. Create job in Jenkins that pulls down this repo, executes `npm install` and then `cypress run -- --browser chrome`.
4. Run job. 
5. Cypress will proceed through a lot of the tests but get stuck on `misc`:

```                                                                            
  Running: examples\misc.spec.js...                                                      (10 of 19) 

Warning: Cypress can only record videos when using the built in 'electron' browser.

You have set the browser to: 'chrome'

A video will not be recorded when using this browser.

  Misc

    âˆš .end() - end the command chain (766ms)

    âˆš cy.exec() - execute a system command (354ms)

    âˆš cy.focused() - get the DOM element that has focus (473ms)

    âˆš cy.wrap() - wrap an object (256ms)
    Cypress.Screenshot
```

It seems to hang on `Cypress.screenshot`, but we see it hang in our tests on this as well as `cy.viewport('ipad')`, et al.

### Versions

Cypress 3.2.0 / Node 10.15.3 / Chrome Version 73.0.3683.86 (Official Build) (64-bit) / Jenkins 2.164.1

**Comment by judsoncarver** [comment]
We updated our e2e machine to the newer chrome 74, and the test sequence now completes. Closing since it appears to be a chrome issue.
