### ISSUE TITLE
Argument parsing crashes badly if passing "spec: {}"

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3957]
3.2.0

Crash Cypress by using `npx cypress run --spec {}`

<img width="942" alt="Screen Shot 2019-04-12 at 9 34 33 AM" src="https://user-images.githubusercontent.com/2212006/56041606-221d2380-5d07-11e9-8df7-d11d27983007.png">

Same using NPM module

```js
const cypress = require('cypress')
cypress.run({
  // this works fine
  // spec: 'cypress/integration/spec.js'
  // this crashes badly - hanging Cypress
  spec: {}

  /*
    this exits because no specs were found
    Can't run because no spec files were found.
    We searched for any files matching this glob pattern:
  */
  // spec: []
})
```

I have created example in https://github.com/cypress-io/cypress-test-tiny/pull/44

**Comment by bahmutov** [comment]
On CI it shows the error message but keeps hanging https://circleci.com/gh/cypress-io/cypress-test-tiny/2120

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: strToArray(...).map is not a function
    at Object.toObject (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/util/args.js:221:39)
    at Object.start (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/cypress.js:70:40)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/index.js:21:43)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/index.js:23:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by bahmutov** [comment]
cannot trust those users like me, defensive programming

**Comment by ivanprotsykfreetour** [comment]
had this issue using a glob pattern in package.json
`"cy:run:local": "cypress run -spec \"cypress/integration/!(examples)**/*.spec.js\""`

**Comment by duncdrum** [comment]
yup running into this on travis as well. Funnily only for pull-request builds. We have CI configured to run different specs on different major versions via ENV variables. 
You can see the expected result of a commit in [my fork](https://travis-ci.com/duncdrum/e2e-core/builds/115825199) yet in the [Pull-request](https://travis-ci.com/eXist-db/e2e-core/builds/115825220) for that commit cypress hangs.

**Comment by saharshMMC** [comment]
I am also facing it.
I am running a single spec file for testing and then uploading screenshots and videos to artifacts.
