### ISSUE TITLE
Cypress with Jenkins Getting Exit status 3221225477

### ISSUE THREAD

**Issue by akeresztesgh** [cypress-io/cypress#3958]
Hi,

I'm using cypress on Windows with Jenkins to run my e2e tests.  I have about 120 tests and Cypress starts just fine (in headless mode), however, around half way it crashes with Exit status 3221225477.  It never crashes at a particular test, usually random.

Here's the output of the crash:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cypress:headless' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'precypress:headless',
4 verbose run-script   'cypress:headless',
4 verbose run-script   'postcypress:headless' ]
5 info lifecycle cypress-project@1.0.0~precypress:headless: cypress-project@1.0.0
6 info lifecycle cypress-project@1.0.0~cypress:headless: cypress-project@1.0.0
7 verbose lifecycle cypress-project@1.0.0~cypress:headless: unsafe-perm in lifecycle true
8 verbose lifecycle cypress-project@1.0.0~cypress:headless: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files (x86)\Jenkins\jobs\Tracker Qa E2E tests\workspace\cypress\node_modules\.bin;%Path%;c:\code;C:\Program Files\nodejs;C:\Program Files\Git\bin;C:\Program Files (x86)\AWS Tools\Deployment Tool
9 verbose lifecycle cypress-project@1.0.0~cypress:headless: CWD: C:\Program Files (x86)\Jenkins\jobs\Tracker Qa E2E tests\workspace\cypress
10 silly lifecycle cypress-project@1.0.0~cypress:headless: Args: [ '/d /s /c', 'cypress run' ]
11 silly lifecycle cypress-project@1.0.0~cypress:headless: Returned: code: 3221225477  signal: null
12 info lifecycle cypress-project@1.0.0~cypress:headless: Failed to exec cypress:headless script
13 verbose stack Error: cypress-project@1.0.0 cypress:headless: `cypress run`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cypress-project@1.0.0
15 verbose cwd C:\Program Files (x86)\Jenkins\jobs\Tracker Qa E2E tests\workspace\cypress
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cypress:headless"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3221225477
22 error cypress-project@1.0.0 cypress:headless: `cypress run`
22 error Exit status 3221225477
23 error Failed at the cypress-project@1.0.0 cypress:headless script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```
I've done some searching for the error code and it seems to have something to do with electron but I haven't been able to find a fix.  Would running this in a docker image be better? Or is there anything that I can provide to help wit this issue?

### Versions

Windows Server 2019
Cypress version 3.2.0

**Comment by jennifer-shehane** [comment]
Exit code `3221225477` appears to be `Access violation.` It indicates that the executed program has terminated abnormally or crashed.

Using the docker image may be better, but it could be something specific within the tests that is crashing Cypress. It's hard to say when it is seemingly random. We'd need some way to reproduce it or narrow down the area where it's crashing to look into it further.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by jennifer-shehane** [comment]
In order to direct better focus on the overall problem that is being described in several issues - we opened one issue to track this behavior https://github.com/cypress-io/cypress/issues/4625 Please add any information about how we can reproduce this bug there. 🙏
