### ISSUE TITLE
cy.request fails with error incorrect header check

### ISSUE THREAD

**Issue by kundaiAtPropertyMe** [cypress-io/cypress#3971]
### Current behavior:

I'm calling an API endpoint to run test by `cy.request`,  

here is my request code

```js
cy.request({
      method: 'POST',
      url: Cypress.config().baseApiUrl ,                
      body:{
          TestUser: testUser
      }
  }) .then((response) =>{
      console.log(response);
  });
```

When I try use Postman to verify it then I get correct result in a 200 with a json response. 

```json
{
    "CustomerId":"00000000-0000-0000-0000-000000000000",
    "ResponseStatus":null,
    "IsSuccessful":true
}
```

but `cy.reques`t returns error

```
CypressError: cy.request() failed trying to load:

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: incorrect header check
```

### Desired behavior:

`cy.request` should return a 200 for this request

### Extra information
The response header likes

```
Cache-Control →private
Content-Length →68
Content-Type →application/json; charset=utf-8
Content-Encoding →deflate
Vary →Accept
Server →Microsoft-IIS/10.0
X-SourceFiles →=?UTF-8?B?QzpcRGV2ZWxvcG1lbnRcUE1ccE0uQXBpSG9zdFxhcGlcdGVzdFxwb3J0Zm9saW9cbmV3?=
X-Powered-By →ASP.NET
Date →Tue, 16 Apr 2019 02:40:44 GMT
```

### Complete error output
```
CypressError: cy.request() failed trying to load:

http://xxxx

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: incorrect header check

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://xxxx

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

RequestError: Error: incorrect header check
    at new RequestError (C:\Users\Kun\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Kun\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Kun\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Kun\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\request\request.js:185:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Inflate.<anonymous> (C:\Users\Kun\AppData\Local\Cypress\Cache\3.2.0\Cypress\resources\app\packages\server\node_modules\request\request.js:1086:12)
    at emitOne (events.js:120:20)
    at Inflate.emit (events.js:210:7)
    at Inflate.zlibOnError (zlib.js:155:8)
```

### Versions

Cypress version 3.2.0

**Comment by AlainPilon** [comment]
I am having the same issue.

**Comment by IanWalston** [comment]
instead of this: `cy.request(cy.request({
      method: 'POST',
      url: Cypress.config().baseApiUrl ,                
      body:{
          TestUser: testUser
      }
  })`

use this: `cy.request('POST', Cypress.config().baseApiUrl, {TestUser: testUser})`

**Comment by jennifer-shehane** [comment]
I wasn't able to reproduce the issue with the information provided. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
