### ISSUE TITLE
Cannot parse value from yield object using "then"

### ISSUE THREAD

**Issue by learningandworking** [cypress-io/cypress#4118]
### Current behavior:

Inside `.then()`, I could not get value from a nested array of an object

### Desired behavior:
Inside `.then()`, I could get value from a nested array of an object

```js
describe('Check return value', () => {
  it('Check return value', () => {
    let key
    let obj = {
        "firstName": "John",
        "lastName" : "doe",
        "age"      : 26,
        "address"  : {
          "streetAddress": "naist street",
          "city"         : "Nara",
          "postalCode"   : "630-0192"
        },
        "phoneNumbers": [
          {
            "type1"  : "iPhone",
            "number1": "0123-4567-8888"
          },
          {
          "type2"  : "home",
            "number2": "0123-4567-8910"
        }
        ]
      }

    //   let myFirstPromise = new Promise((resolve, reject) => {
    //     resolve(obj)
    //   })
    //   let getPhoneType = phone => {
    //       return new Promise((resolve, reject) => {
    //           resolve(phone[0])
    //       })
    //   }

    // myFirstPromise
    //     .then((o) => {
    //       cy.log(o.phoneNumbers[0]);
    //       return o.phoneNumbers[0];
    //     })
    //     .then((re) => {
    //         cy.log(re)
    //         cy.log(re.type1)
    //     })

    cy.log('Be able parse an obj', obj.phoneNumbers[0].type1)

    cy.request({
      url: 'http://localhost:45458/api/business/article1',
      method: 'GET',
    })
    .its('body')
    .then((res) => {
      key = res.phoneNumbers[0].type1

      return key
    })
    .as('key')
    cy.get('@key')
  })
})
```
### Steps to reproduce: (app code and test code)

Assuming that the response of the API is the same as obj (please take a look at the code)

1. Run code and check the result
  a. `cy.log('Be able parse an obj', obj.phoneNumbers[0].type1)`
=> PASSED. return "iPhone"
 b.  cy.get('@key')
=> FAILED. get error 

Please get the attached image for more detail

![image](https://user-images.githubusercontent.com/26406558/57155876-c70eb600-6e06-11e9-9876-cea2508c4dfb.png)

Log
```shell
cypress_runner.js:171427 TypeError: Cannot read property '0' of undefined
    at Context.<anonymous> (http://localhost:63049/__cypress/tests?p=cypress\integration\checking\tes.spec.js-373:47:29)
From previous event:
    at Context.thenFn (http://localhost:63049/__cypress/runner/cypress_runner.js:71611:26)
    at Context.then (http://localhost:63049/__cypress/runner/cypress_runner.js:71871:21)
    at Context.<anonymous> (http://localhost:63049/__cypress/runner/cypress_runner.js:78803:21)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:78508:33
From previous event:
    at runCommand (http://localhost:63049/__cypress/runner/cypress_runner.js:78498:14)
    at next (http://localhost:63049/__cypress/runner/cypress_runner.js:78582:14)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:78594:18
From previous event:
    at next (http://localhost:63049/__cypress/runner/cypress_runner.js:78582:34)
From previous event:
    at http://localhost:63049/__cypress/runner/cypress_runner.js:78601:37
From previous event:
    at run (http://localhost:63049/__cypress/runner/cypress_runner.js:78599:15)
    at Object.cy.<computed> [as log] (http://localhost:63049/__cypress/runner/cypress_runner.js:78827:11)
    at Context.runnable.fn (http://localhost:63049/__cypress/runner/cypress_runner.js:78957:20)
    at callFn (http://localhost:63049/__cypress/runner/cypress_runner.js:51150:21)
    at Test.Runnable.run (http://localhost:63049/__cypress/runner/cypress_runner.js:51143:7)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:81902:28
From previous event:
    at Object.onRunnableRun (http://localhost:63049/__cypress/runner/cypress_runner.js:81897:20)
    at $Cypress.action (http://localhost:63049/__cypress/runner/cypress_runner.js:77254:51)
    at Test.Runnable.run (http://localhost:63049/__cypress/runner/cypress_runner.js:80963:20)
    at Runner.runTest (http://localhost:63049/__cypress/runner/cypress_runner.js:51613:10)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:51719:12
    at next (http://localhost:63049/__cypress/runner/cypress_runner.js:51533:14)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:51543:7
    at next (http://localhost:63049/__cypress/runner/cypress_runner.js:51475:14)
    at http://localhost:63049/__cypress/runner/cypress_runner.js:51511:5
    at timeslice (http://localhost:63049/__cypress/runner/cypress_runner.js:46752:27)
```
### Versions

- Cypress: 3.2.0
- Windows 10
- Node: 10.15.2

**Comment by CoryDanielson** [comment]
The promise might be executing asynchronously, so the code `cy.get('@key')` actually runs before the promise finishes.

Try adding some console logs to see what the output looks like

```js
    console.log(1); // log here
    cy.request({
      url: 'http://localhost:45458/api/business/article1',
      method: 'GET',
    })
    .its('body')
    .then((res) => {
      key = res.phoneNumbers[0].type1
      console.log(2); // log here
      return key
    })
    .as('key')
    console.log(3); // log here
    cy.get('@key')
    console.log(4); // log here
```

If your console displays `1, 3, 4` and then `2`, your issue is the async nature of your code rather than a cypress bug.

**Comment by jennifer-shehane** [comment]
Can you run `cy.log(res)` within then `.then` to see what is output from the body response?

**Comment by jennifer-shehane** [comment]
@learningandworking Any updates here?

**Comment by learningandworking** [comment]
I think this issue could be solved. So closed it.
