### ISSUE TITLE
Loading Config by file 

### ISSUE THREAD

**Issue by akshayverma172** [cypress-io/cypress#4122]
I am using this 

```js
function getConfigurationByFile(file) {
  const pathToConfigFile = path.resolve(`${file}.json`)
  return fs.readJson(pathToConfigFile)
}
```

// plugins file
```js
module.exports = (on, config) => {
  // accept a configFile value or use development by default
  const file = config.env.configFile || 'develop'

  return getConfigurationByFile(file)
}
```

from the docs. It's getting the correct path for the config file but its giving this error.

```
Cannot set property '0' of undefined
```

and the logs says this

```
cypress:server:events sending ipc data { 
  type: 'open:project', 
  data: { 
    id: 0.11164175542728327, 
    __error: { 
      name: 'TypeError', 
      stack: 'TypeError: Cannot set property \'0\' of undefined\n 
        at //Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:280:37\n 
        at arrayEach (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:516:11)\n 
        at Function.forEach (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9344:14)\n 
        at setResolvedOn (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:276:18)\n 
        at //Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:278:20\n 
        at //Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4911:15\n 
        at baseForOwn (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:2996:24)\n 
        at //Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4880:18\n at Function.forEach (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9344:14)\n at setResolvedOn (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:276:18)\n at Object.updateWithPluginValues (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:287:7)\n at //Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:124:27\n at tryCatcher (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)\n at Promise._settlePromise (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)\n at Promise._settlePromise0 (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)\n at Promise._settlePromises (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)\n at Async._drainQueue (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)\n at Async._drainQueues (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)\n at Immediate.Async.drainQueues (//Library/Caches/Cypress/3.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)\n at runCallback (timers.js:781:20)\n at tryOnImmediate (timers.js:743:5)\n at processImmediate [as _immediateCallback] (timers.js:714:5)\n', message: 'Cannot set property \'0\' of undefined' } } } +2ms≈
```

Cypress 3.2.0

**Comment by jennifer-shehane** [comment]
The error looks to be thrown here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/config.coffee#L288

Can you also paste what you have within this `configFile`?

**Comment by JohnnyChiang** [comment]
Same errors here. When there are more than one layer in `env`, the error occurs

**develop.json**
``` json
{
    "env": {
        "test1": {
            "test2": "test2"
        }
    }
}
```

Cypress version: 3.8.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by n370** [comment]
> Same errors here. When there are more than one layer in `env`, the error occurs
> 
> **develop.json**
> 
> ```json
> {
>     "env": {
>         "test1": {
>             "test2": "test2"
>         }
>     }
> }
> ```
> 
> Cypress version: 3.8.0

@JohnnyChiang I can confirm this is not an issue with Cypress 4.11.0
