### ISSUE TITLE
Crash when plugins event handler is undefined

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4261]
## Bug

Crashes in 3.2.0 and 3.3.0, have not tried earlier versions
Mac

Reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/no-plugins-export

```
npm install
npm run cypress:open
```
and click on spec file

## Reproduction

Register undefined event handler in `plugins.js` file for an event like

```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('file:preprocessor')
}
```

and get the following crash

<img width="1279" alt="Screen Shot 2019-05-20 at 3 23 40 PM" src="https://user-images.githubusercontent.com/2212006/58046620-d898d300-7b13-11e9-86a3-60a37f5d7dad.png">

Stack trace in the terminal

```
GET /__cypress/tests?p=cypress/support/index.js-383 200 8.371 ms - 146
TypeError: event.handler is not a function
    at invoke (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:17:16)
    at /Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
    at tryCatcher (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:47:28)
    at Object.wrap (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/preprocessor.js:25:8)
    at execute (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:80:20)
    at EventEmitter.ipc.on (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:136:5)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at process.<anonymous> (/Users/gleb/Library/Caches/Cypress/3.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
GET /__cypress/tests?p=cypress/integration/spec.js-143 200 8.418 ms - 146
```

It would be nicer to have a much better error message here

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#6725](https://github.com/cypress-io/cypress/pull/5356). 

Released in [`4.2.0`](https://on.cypress.io/changelog#4-2-0).

This comment thread has been locked. If you are still experiencing this issue after upgrading to Cypress 4.2.0, please open a new issue.
