### ISSUE TITLE
Can't load static file with ERR_SSL_VERSION_INTERFERENCE

### ISSUE THREAD

**Issue by flintliu** [cypress-io/cypress#4336]
### Current behavior:

Static files cannot be loaded with ERR_SSL_VERSION_INTERFERENCE errors, if I refresh the test for 4-5 times, they are coming out.

```
  cypress:server:server Got CONNECT request from t-ec.bstatic.com:443 +1ms
  cypress:https-proxy Writing browserSocket connection headers { url: 't-ec.bstatic.com:443', headLength: 0, headers: { host: 't-ec.bstatic.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' } } +1ms
  cypress:https-proxy Got first head bytes { url: 's-ec.bstatic.com:443', head: '\u0016\u0003\u0001\u0000�\u0001\u0000\u0000�\u0003\u0003�F�=���l/�U*� �\n$;��px�\u0001�\u0012���M�\u0000\u0000\u001c���+�/�,�0̨̩�\u0013�\u0014\u0000�\u0000' } +4ms
  cypress:server:cors Parsed URL { port: '443', tld: 'com', domain: 'bstatic' } +6ms
  cypress:server:server HTTPS request does not match URL: https://s-ec.bstatic.com:443 with props: { port: '443', tld: 'com', domain: 'booking' } +4ms
  cypress:https-proxy Making connection to s-ec.bstatic.com:443 +0ms
  cypress:https-proxy Got first head bytes { url: 't-ec.bstatic.com:443', head: '\u0016\u0003\u0001\u0000�\u0001\u0000\u0000�\u0003\u0003`�(j�\u0011\u0003w\u000bjް�\u0018dn�gC���v\\��ӽ6\u0019g�\u0000\u0000\u001cJJ�+�/�,�0̨̩�\u0013�\u0014\u0000�\u0000�' } +0ms
  cypress:server:cors Parsed URL { port: '443', tld: 'com', domain: 'bstatic' } +0ms
  cypress:server:server HTTPS request does not match URL: https://t-ec.bstatic.com:443 with props: { port: '443', tld: 'com', domain: 'booking' } +1ms
  cypress:https-proxy Making connection to t-ec.bstatic.com:443 +1ms
  cypress:server:server Got CONNECT request from s-ec.bstatic.com:443 +0ms
  cypress:https-proxy Writing browserSocket connection headers { url: 's-ec.bstatic.com:443', headLength: 0, headers: { host: 's-ec.bstatic.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' } } +0ms
  cypress:https-proxy Got first head bytes { url: 's-ec.bstatic.com:443', head: '\u0016\u0003\u0001\u0000�\u0001\u0000\u0000�\u0003\u0003�,\u001a�\u0000�â\u0006�\u0000U\u001c�\u0016G\b\u0011Oa|��1����M2A\u0000\u0000\u001c���+�/�,�0̨̩�\u0013�\u0014\u0000�\u0000�' } +0ms
  cypress:server:cors Parsed URL { port: '443', tld: 'com', domain: 'bstatic' } +2ms
  cypress:server:server HTTPS request does not match URL: https://s-ec.bstatic.com:443 with props: { port: '443', tld: 'com', domain: 'booking' } +1ms
  cypress:https-proxy Making connection to s-ec.bstatic.com:443 +1ms
  cypress:network:connect successfully connected { opts: { port: '443', host: 't-ec.bstatic.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +24ms
  cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 't-ec.bstatic.com', err: undefined } +1ms
  cypress:network:connect successfully connected { opts: { port: '443', host: 's-ec.bstatic.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +1ms
  cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 's-ec.bstatic.com', err: undefined } +1ms
  cypress:network:connect successfully connected { opts: { port: '443', host: 't-ec.bstatic.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +8ms
  cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 't-ec.bstatic.com', err: undefined } +8ms
  cypress:network:connect successfully connected { opts: { port: '443', host: 's-ec.bstatic.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +1ms
  cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 's-ec.bstatic.com', err: undefined } +1ms
  cypress:network:connect successfully connected { opts: { port: '443', host: 's-ec.bstatic.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +2ms
  cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 's-ec.bstatic.com', err: undefined } +2ms
GET /__cypress/runner/cypress_runner.css 200 6.177 ms - -
  cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 't-ec.bstatic.com:443' } +6ms
  cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 's-ec.bstatic.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 't-ec.bstatic.com:443' } +4ms
  cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 's-ec.bstatic.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 's-ec.bstatic.com:443' } +1ms
```

### Desired behavior:

Can load static files properly.

### Versions

Cypress: 3.3.1
System: macOS Mojave 10.14.4
Chome: 74.0.3729.169

**Comment by flotwig** [comment]
Are you running the tests with Chrome or Electron? If Chrome, what version of Chrome are you using? `ERR_SSL_VERSION_INTERFERENCE` and the policy that generates it was removed in Chrome 74: https://chromium.googlesource.com/chromium/src/+/d61bd53e385e2e249687cec28fe28f488a25fa0c

**Comment by jennifer-shehane** [comment]
@flotwig The user agent is in the DEBUG logs: Chrome/74.0.3729.169

**Comment by flintliu** [comment]
@flotwig I tried with my home network instead of in my office, the errors are gong, so I believe there is something related to network settings. I also tried by using our HTTP proxy, but the request is rejected directly which did not happen with version 3.2.0 (on 3.2.0, the problem is static files cannot be loaded with long waiting time). Then I tried to add our domain into NO_PROXY, but it is still using HTTPS_PROXY.

**Comment by jennifer-shehane** [comment]
@flintliu Could you update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed. Thanks!

**Comment by flintliu** [comment]
@jennifer-shehane it has been fixed on the latest version, thanks.

**Comment by ptoshniw** [comment]
@flintliu can you please tell us which version of cypress you have used to make it work as I am stuck in the same issue from weeks and not getting any resolution so far? 
I am using current version 3.4.1

**Comment by flintliu** [comment]
@ptoshniw After cypress can handle system proxy properly, I didn't see the problem.
