### ISSUE TITLE
"port" TypeDef mismatch on v3.3.1

### ISSUE THREAD

**Issue by joekarasek** [cypress-io/cypress#4359]
### Current behavior:

With version 3.3.1, when I run `cypress run` I am getting the following error...

```TypeError: "port" option should be a number or string: null
    at lookupAndConnect (net.js:1051:13)
    at Socket.connect (net.js:1028:5)
    at Object.connect (net.js:103:35)
    at createSocket (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/network/lib/connect.js:52:26)
    at tryConnect (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/network/lib/connect.js:83:20)
    at Object.createRetryingSocket (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/network/lib/connect.js:86:5)
    at Server._makeConnection (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:176:22)
    at Server._makeDirectConnection (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:131:19)
    at Server._onFirstHeadBytes (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:87:23)
    at Socket.<anonymous> (/Users/karasek/Library/Caches/Cypress/3.3.1/Cypress.app/Contents/Resources/app/packages/https-proxy/lib/server.js:73:24)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)```

Rolling back to 3.3.0 resolves the issue.

### Desired behavior:

It does not error out. 

### Steps to reproduce: (app code and test code)

Sorry, but I'm way too busy to do that... If you close this then so be it, I tried.

### Versions

v3.3.1, Mac, Chrome

**Comment by flotwig** [comment]
Do you have a baseUrl set? Is it HTTPS or HTTP? Are you behind a proxy? Can you share your spec code?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
