### ISSUE TITLE
Sync file system operation in net_profiler.js:161

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#4448]
while building Cypress on Mac got this error when running smoke test:
```
Unhandled rejection Error: ENFILE: file table overflow, open '/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/lib/logger.js'
```

`develop` branch at 3.3.1
Mac plaftorm

Full stacktrace

```
Unhandled rejection Error: ENFILE: file table overflow, open '/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/lib/logger.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at Object.Module._extensions..js (module.js:652:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at /Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:347:16
    at tryCatcher (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.log (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:337:26)
    at exitErr (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:32:32)
    at tryCatcher (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/gleb/git/cypress/build/darwin/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Seems we are calling `fs.openSync` which we should never do - all FS actions should go through `graceful-fs` which retries actions.

Probably this place
```
packages/server/lib/util/net_profiler.js:161:  this.logStream = fs.openSync(this.logPath, 'a')
```

**Comment by flotwig** [comment]
@bahmutov `net_profiler` is only `require`'d if you run with `CY_NET_PROFILE=1`, so it's probably not coming from there

**Comment by bahmutov** [comment]
ok, so that is ok, but then it seems we are hitting file system limit while doing `require` (looks like from the stacktrace). Unless we bundle code before putting into ASAR, we can hit this limit @brian-mann
