### ISSUE TITLE
`run_plugins_spec` test is leaking into other tests

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4481]
`@ipc.send` in `run_plugins_spec` is somehow leading to failing tests later on:

https://github.com/cypress-io/cypress/blob/bbff24dc6799a2e9464eebff8e1f9ad468fa5635/packages/server/test/unit/plugins/child/run_plugins_spec.coffee#L67-L80

https://circleci.com/gh/cypress-io/cypress/123148#tests/containers/1 -
```
AssertionError: expected 'error' to equal 'load:error'
    at Object.ipc.send (/root/cypress/packages/server/test/unit/plugins/child/run_plugins_spec.coffee:76:26)
    at process.on (/root/cypress/packages/server/lib/plugins/child/run_plugins.js:1:1)
    at emitOne (events.js:1:1)
    at process.emit (events.js:1:1)
    at process.emit (/root/cypress/packages/ts/node_modules/source-map-support/source-map-support.js:1:1)
    at processEmit (/root/cypress/packages/server/node_modules/signal-exit/index.js:1:1)
    at processEmit [as emit] (/root/cypress/packages/launcher/node_modules/signal-exit/index.js:1:1)
    at process._fatalException (bootstrap_node.js:1:1)
```

https://circleci.com/gh/cypress-io/cypress/128235#tests/containers/1

**Comment by bahmutov** [comment]
in a node PR I had to refactor these tests a little bit - because they would NOT wait for the IPC promise to resolve, leaving a dangling promise which I think might be leaking. See https://github.com/cypress-io/cypress/pull/4436/files#diff-8b6216a59d7d745ad0cd2973c43f63c9R29
