### ISSUE TITLE
Cypress 3.3.1 does not load plugins/index.js on Linux

### ISSUE THREAD

**Issue by edoloughlin** [cypress-io/cypress#4557]
### Current behavior:

I tried adding the cypress-cucumber-preprocessor plugin so I can use feature files. Cypress loads the preprocessor on Windows but not if I run the same config on Linux.

I have a `cypress/plugins/index.js` file that is not loaded. On Windows 10, my `.feature` file is run successfully. On Linux (Ubuntu 19.04) I see:

```
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type.
> Feature: It runs
| 
|   I want to see the startup page

Oops...we found an error preparing this test file:

  cypress/integration/smoke.feature

The error was:

./cypress/integration/smoke.feature 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type.
> Feature: It runs
| 
|   I want to see the startup page

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

If I run with `DEBUG=cypress:*` then on Windows I see a log statement I put in my `cypress/plugins/index.js` in the log:

```javascript
const cucumber = require('cypress-cucumber-preprocessor').default
module.exports = (on, config) => {
  console.log('CUCUMBER', config);
  on('file:preprocessor', cucumber());
}
```
 Note the lines following `CUCUMBER { animationDistanceThreshold: 5,` below.

```
2019-06-25T09:38:26.607Z cypress:server:plugins:child require pluginsFile
2019-06-25T09:38:28.534Z cypress:server:plugins:child run plugins function
2019-06-25T09:38:28.534Z cypress:server:plugins:child register event _get:task:body with id 0
2019-06-25T09:38:28.534Z cypress:server:plugins:child register event _get:task:keys with id 1
CUCUMBER { animationDistanceThreshold: 5,
  fileServerFolder: 'C:\\Users\\user\\project',
  baseUrl: null,
  fixturesFolder: 'C:\\Users\\user\\project\\cypress\\fixtures',
  chromeWebSecurity: false,
  modifyObstructiveCode: false,
  integrationFolder: 'C:\\Users\\user\\project\\cypress\\integration',
  env: 
   { http_proxy: '<my proxy>',
     https_proxy: '<my proxy>',
     no_proxy: 'localhost' },
  pluginsFile: 'C:\\Users\\user\\project\\cypress\\plugins\\index.js',
  hosts: null,
  screenshotsFolder: 'C:\\Users\\user\\project\\cypress\\screenshots',
  numTestsKeptInMemory: 0,
  supportFile: 'C:\\Users\\user\\project\\cypress\\support\\index.js',
  port: null,
  supportFolder: 'C:\\Users\\user\\project\\cypress\\support',
  reporter: 'spec',
  videosFolder: 'C:\\Users\\user\\project\\cypress\\videos',
  reporterOptions: null,
  testFiles: '**/*.*',
  defaultCommandTimeout: 4000,
  trashAssetsBeforeRuns: true,
  execTimeout: 60000,
  blacklistHosts: null,
  pageLoadTimeout: 60000,
  userAgent: null,
  requestTimeout: 5000,
  viewportWidth: 1000,
  responseTimeout: 30000,
  viewportHeight: 800,
  taskTimeout: 60000,
  video: true,
  videoCompression: 32,
  videoUploadOnPasses: true,
  watchForFileChanges: false,
  waitForAnimations: true }
2019-06-25T09:38:28.546Z cypress:server:plugins:child register event file:preprocessor with id 2
2019-06-25T09:38:28.552Z cypress:server:plugins register plugins process event _get:task:body with id 0
2019-06-25T09:38:28.552Z cypress:server:plugins register event '_get:task:body'
2019-06-25T09:38:28.552Z cypress:server:plugins register plugins process event _get:task:keys with id 1
2019-06-25T09:38:28.552Z cypress:server:plugins register event '_get:task:keys'
```

The log from Linux does not show the `console.log` being run:

```
2019-06-24T16:34:28.959Z cypress:server:plugins:child require pluginsFile
2019-06-24T16:34:29.609Z cypress:webpack user options: { webpackOptions: { resolve: { extensions: [Array] }, module: { rules: [Array] } } }
2019-06-24T16:34:29.613Z cypress:server:plugins:child run plugins function
2019-06-24T16:34:29.613Z cypress:server:plugins:child register event _get:task:body with id 0
2019-06-24T16:34:29.614Z cypress:server:plugins:child register event _get:task:keys with id 1
2019-06-24T16:34:29.614Z cypress:server:plugins:child register event file:preprocessor with id 2
2019-06-24T16:34:29.618Z cypress:server:plugins register plugins process event _get:task:body with id 0
2019-06-24T16:34:29.618Z cypress:server:plugins register event '_get:task:body'
2019-06-24T16:34:29.619Z cypress:server:plugins register plugins process event _get:task:keys with id 1
2019-06-24T16:34:29.619Z cypress:server:plugins register event '_get:task:keys'

```

### Desired behavior:

It should preprocess `.feature` files on Windows and Linux.

### Steps to reproduce: (app code and test code)

Add `"cypress-cucumber-preprocessor": "^1.12.0"` to your `package.json` file and run `npm install`

Add the following to `cypress/plugins/index.js`:

```javascript
const cucumber = require('cypress-cucumber-preprocessor').default
module.exports = (on, config) => {
  console.log('CUCUMBER', config);
  on('file:preprocessor', cucumber());
}
```
Create a file `cypress/integration/test.feature` file with these contents:
Note the `console.log`.

```
Feature: It runs

  I want to see the startup page

  @smoke
  Scenario: Open the app
    Given I open the app
    Then I see something
```

Create a file `cypress/integration/test/test.js` with these contents:

```javascript
import { Given } from "cypress-cucumber-preprocessor/steps";
import { Then } from 'cypress-cucumber-preprocessor/steps';

const url = 'http://localhost:4200';
Given('I open the app', () => {
  cy.visit(url)
})

Then(`I see something`, () => {
  cy.title().should('exist')
})
```

### Versions

Cypress 3.3.1 and 3.1.0
cypress-cucumber-preprocessor 1.12.0
Windows 10 and Ubuntu 19.04
Electron (whatever version is installed by cypress)

**Comment by edoloughlin** [comment]
I just checked the debug logs on Windows vs Linux.
The successful Windows run uses browserify to preprocess the `.feature` files. On Linux, webpack is used.

The relevant parts of the Windows log:

```
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins call event file:preprocessor for invocation id inv2
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:controllers:spec request for { spec: 'cypress\\integration\\smoke.feature' }
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:preprocessor getFile C:\Users\user\git\project\cypress\integration\smoke.feature
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:appdata path: C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\integration\smoke.feature
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv2' })
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins plugin event registered? { event: 'file:preprocessor', isRegistered: true }
2019-06-25T12:03:39.012Z cypress:browserify received user options: { browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee', '.cjsx' ], transform: [ [Function: transform], [Array], [Array] ], plugin: [] }, watchifyOptions: { ignoreWatch: [ '**/.git/**', '**/.nyc_output/**', '**/.sass-cache/**', '**/bower_components/**', '**/coverage/**', '**/node_modules/**' ] } }
2019-06-25T12:03:39.012Z cypress:browserify get: C:\Users\user\git\project\cypress\support\index.js
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins execute plugin event 'file:preprocessor' with args: EventEmitter { domain: null, _events: { rerun: [Function] }, _eventsCount: 1, _maxListeners: undefined, filePath: 'C:\\Users\\user\\git\\\project\\cypress\\integration\\smoke.feature', shouldWatch: false, outputPath: 'C:\\Users\\user\\AppData\\Roaming\\Cypress\\cy\\production\\projects\\project-7b1fd9333094324ea77689fb063b45a4\\bundles\\cypress\\integration\\smoke.feature' } undefined undefined
2019-06-25T12:03:39.012Z cypress:browserify input: C:\Users\user\git\project\cypress\support\index.js
2019-06-25T12:03:39.012Z cypress:browserify output: C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\support\index.js
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins call event file:preprocessor for invocation id inv3
2019-06-25T12:03:39.013Z cypress:browserify browserifyOptions { extensions: [ '.js', '.jsx', '.coffee', '.cjsx' ], transform: [ [Function: transform], [ 'C:\\Users\\user\\git\\\project\\node_modules\\@cypress\\browserify-preprocessor\\cjsxify.js', [Object] ], [ 'C:\\Users\\user\\git\\\project\\node_modules\\babelify\\index.js', [Object] ] ], plugin: [], cache: {}, packageCache: {}, entries: [ 'C:\\Users\\user\\git\\\project\\cypress\\support\\index.js' ] }:
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv3' })
2019-06-25T12:03:39.022Z cypress:browserify received user options: { browserifyOptions: { extensions: [ '.js', '.jsx', '.coffee', '.cjsx' ], transform: [ [Function: transform], [Array], [Array] ], plugin: [] }, watchifyOptions: { ignoreWatch: [ '**/.git/**', '**/.nyc_output/**', '**/.sass-cache/**', '**/bower_components/**', '**/coverage/**', '**/node_modules/**' ] } }
2019-06-25T12:03:39.023Z cypress:browserify get: C:\Users\user\git\project\cypress\integration\smoke.feature
2019-06-25T12:03:39.023Z cypress:browserify input: C:\Users\user\git\project\cypress\integration\smoke.feature
2019-06-25T12:03:39.023Z cypress:browserify output: C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\integration\smoke.feature
2019-06-25T12:03:39.023Z cypress:browserify browserifyOptions { extensions: [ '.js', '.jsx', '.coffee', '.cjsx' ], transform: [ [Function: transform], [ 'C:\\Users\\user\\git\\\project\\node_modules\\@cypress\\browserify-preprocessor\\cjsxify.js', [Object] ], [ 'C:\\Users\\user\\git\\\project\\node_modules\\babelify\\index.js', [Object] ] ], plugin: [], cache: {}, packageCache: {}, entries: [ 'C:\\Users\\user\\git\\\project\\cypress\\integration\\smoke.feature' ] }:
2019-06-25T12:03:39.040Z cypress:browserify making bundle C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\support\index.js
2019-06-25T12:03:39.044Z cypress:browserify making bundle C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\integration\smoke.feature
2019-06-25T12:03:39.064Z cypress:browserify errored bundling: C:\Users\user\AppData\Roaming\Cypress\cy\production\projects\project-7b1fd9333094324ea77689fb063b45a4\bundles\cypress\integration\integration\smoke.feature { Error: Cannot find module 'C:\Users\user\git\project\cypress\integration\integration\smoke.feature' from 'C:\Users\user\git\project'
    at C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at C:\Users\user\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Array],
        error: [Function],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' },
  filePath: 'C:\\Users\\user\\git\\\project\\cypress\\integration\\integration\\smoke.feature',
  originalStack: 'Error: Cannot find module \'C:\\Users\\user\\git\\\project\\cypress\\integration\\integration\\smoke.feature\' from \'C:\\Users\\user\\git\\\project\'\n    at C:\\Users\\user\\git\\\project\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:55:21\n    at load (C:\\Users\\user\\git\\\project\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:69:43)\n    at onex (C:\\Users\\user\\git\\\project\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:92:31)\n    at C:\\Users\\user\\git\\\project\\node_modules\\browser-resolve\\node_modules\\resolve\\lib\\async.js:22:47\n    at C:\\Users\\user\\AppData\\Local\\Cypress\\Cache\\3.1.0\\Cypress\\resources\\app\\packages\\server\\node_modules\\graceful-fs\\polyfills.js:284:29\n    at FSReqWrap.oncomplete (fs.js:152:21)' }
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:plugins promise rejected for id inv1 ':' Error: Cannot find module 'C:\Users\user\git\project\cypress\integration\integration\smoke.feature' from 'C:\Users\user\git\project'
    at C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\user\git\project\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at C:\Users\user\AppData\Local\Cypress\Cache\3.1.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
Tue, 25 Jun 2019 12:03:39 GMT cypress:server:timers child sending timer id 8
2019-06-25T12:03:41.083Z cypress:cucumber compiling feature  C:\Users\user\git\project\cypress\integration\smoke.feature
2019-06-25T12:03:41.083Z cypress:cucumber compiling Feature: It runs

  I want to see the startup page

  @smoke
  Scenario: Open the app
    Given I open the app
    Then I see the title
```
And the Linux log, showing webpack:

```
2019-06-24T16:34:32.970Z cypress:server:plugins call event file:preprocessor for invocation id inv1
2019-06-24T16:34:32.975Z cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv1' })
2019-06-24T16:34:32.979Z cypress:webpack get /home/user/project/cypress/integration/smoke.feature
2019-06-24T16:34:32.982Z cypress:webpack webpackOptions: { resolve: { extensions: [ '.ts', '.js' ] }, module: { rules: [ [Object] ] } }
2019-06-24T16:34:32.984Z cypress:webpack watchOptions: {}
2019-06-24T16:34:32.984Z cypress:webpack input: /home/user/project/cypress/integration/smoke.feature
2019-06-24T16:34:32.984Z cypress:webpack output: /home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/integration/smoke.feature
2019-06-24T16:34:33.077Z cypress:server:server Getting remote state: { auth: undefined, props: null, origin: 'http://localhost:39941', strategy: 'file', visiting: undefined, domainName: 'localhost', fileServer: 'http://localhost:36265' }
2019-06-24T16:34:33.199Z cypress:server:video capture stderr log { message: '[mjpeg @ 0x649efc0] EOI missing, emulating' }
2019-06-24T16:34:33.252Z cypress:server:controllers:spec request for { spec: 'cypress/support/index.js' }
2019-06-24T16:34:33.256Z cypress:server:preprocessor getFile /home/user/project/cypress/support/index.js
2019-06-24T16:34:33.257Z cypress:server:appdata path: /home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/support/index.js
2019-06-24T16:34:33.257Z cypress:server:plugins plugin event registered? { event: 'file:preprocessor', isRegistered: true }
2019-06-24T16:34:33.258Z cypress:server:plugins execute plugin event 'file:preprocessor' with args: EventEmitter { domain: null, _events: { rerun: [Function] }, _eventsCount: 1, _maxListeners: undefined, filePath: '/home/user/project/cypress/support/index.js', shouldWatch: false, outputPath: '/home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/support/index.js' } undefined undefined
2019-06-24T16:34:33.261Z cypress:server:plugins call event file:preprocessor for invocation id inv2
2019-06-24T16:34:33.272Z cypress:server:controllers:spec request for { spec: 'cypress/integration/smoke.feature' }
2019-06-24T16:34:33.282Z cypress:server:preprocessor getFile /home/user/project/cypress/integration/smoke.feature
2019-06-24T16:34:33.282Z cypress:server:plugins plugin event registered? { event: 'file:preprocessor', isRegistered: true }
2019-06-24T16:34:33.283Z cypress:server:preprocessor headless and already processed
2019-06-24T16:34:33.750Z cypress:server:timers child sending timer id 9
2019-06-24T16:34:34.066Z cypress:server:plugins:child execute plugin event: file:preprocessor ({ eventId: 2, invocationId: 'inv2' })
2019-06-24T16:34:34.067Z cypress:webpack get /home/user/project/cypress/support/index.js
2019-06-24T16:34:34.067Z cypress:webpack webpackOptions: { resolve: { extensions: [ '.ts', '.js' ] }, module: { rules: [ [Object] ] }, entry: '/home/user/project/cypress/integration/smoke.feature', output: { path: '/home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/integration', filename: 'smoke.feature' }, devtool: 'inline-source-map' }
2019-06-24T16:34:34.067Z cypress:webpack watchOptions: {}
2019-06-24T16:34:34.068Z cypress:webpack input: /home/user/project/cypress/support/index.js
2019-06-24T16:34:34.068Z cypress:webpack output: /home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/support/index.js
2019-06-24T16:34:34.223Z cypress:webpack errored bundling /home/user/.config/Cypress/cy/production/projects/project-4eb139d2469fe207937452f07ef29904/bundles/cypress/integration/smoke.feature { ./cypress/integration/smoke.feature 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type.
> Feature: It runs
|
|   I want to see the startup page
  filePath: '/home/user/project/cypress/integration/smoke.feature',
  originalStack: './cypress/integration/smoke.feature 1:12\nModule parse failed: Unexpected token (1:12)\nYou may need an appropriate loader to handle this file type.\n> Feature: It runs\r\n| \r\n|   I want to see the startup page\r' }
```

**Comment by bahmutov** [comment]
please provide a reproduction repository - it can be a simple https://github.com/cypress-io/cypress-test-tiny fork with your plugins and feature file added so we can see the problem.

**Comment by edoloughlin** [comment]
I can't repro this with the `cypress-test-tiny` repo. It works. Something in my config is forcing cypress to use webpack on Linux. 

My cypress/plugins/index.js file contains

```javascript
module.exports = (on, config) => {
  console.log('CUCUMBER ', config);
  on('file:preprocessor', return cucumber());
}
```

On Windows it uses browserify and cypress-cucumber-preprocessor is called and handles `.feature` files. I see the `console.log` from above in the log. On Linux, it uses webpack (I don't know why) and looks like that file is never run. 

I thought it might be Angular 8 config getting in the way but I took the `cypress-test-tiny` repo and added Angular 8 to it and it still worked.

I'd really appreciate if anyone has any ideas.

**Comment by lgandecki** [comment]
@edoloughlin you don't have to reproduce with cypress-test-tiny, but try to reproduce regardless, it would be helpful for the cypress guys as well as at at the cypress-cucumber . :) Otherwise it's as hard for us to understand what's going on, and to be honest - probably even harder. :) 
If you could make a tiny angularjs app , add your config, and confirm that still brakes, then push it somewhere for us to look at, that would be very helpful.

**Comment by malixsys** [comment]
@edoloughlin : Stupid question but, is your `pluginsFile` set to false?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
