### ISSUE TITLE
cy.exec timed out

### ISSUE THREAD

**Issue by YaroslavMolchan** [cypress-io/cypress#4558]
### Current behavior:

Some `cy.exec` commands fails with timeout, I updated to Cypress 3.3.1 and all will be fine, but 3-4 days ago some tests just failed.

For example:
```
cy.exec('docker exec someCommand') timed out after waiting 60000ms.

CypressError: cy.exec('docker exec someCommand') timed out after waiting 60000ms.
at Object.cypressErr (http://website.local/__cypress/runner/cypress_runner.js:83220:11)
at Object.throwErr (http://website.local/__cypress/runner/cypress_runner.js:83185:18)
at Object.throwErrByPath (http://website.local/__cypress/runner/cypress_runner.js:83212:17)
at http://website.local/__cypress/runner/cypress_runner.js:72451:23
at tryCatcher (http://website.local/__cypress/runner/cypress_runner.js:132142:23)
at http://website.local/__cypress/runner/cypress_runner.js:127452:41
at tryCatcher (http://website.local/__cypress/runner/cypress_runner.js:132142:23)
at Promise._settlePromiseFromHandler (http://website.local/__cypress/runner/cypress_runner.js:130160:31)
at Promise._settlePromise (http://website.local/__cypress/runner/cypress_runner.js:130217:18)
at Promise._settlePromise0 (http://website.local/__cypress/runner/cypress_runner.js:130262:10)
at Promise._settlePromises (http://website.local/__cypress/runner/cypress_runner.js:130337:18)
at Async._drainQueue (http://website.local/__cypress/runner/cypress_runner.js:127066:16)
at Async._drainQueues (http://website.local/__cypress/runner/cypress_runner.js:127076:10)
at Async.drainQueues (http://website.local/__cypress/runner/cypress_runner.js:126950:14)
at <anonymous>
```
When I restart tests this command can execute, but another will be failed, sometimes all tests passed, last days every 2-3 build was failed with this error. To fix it I repalce all `cy.exec` calls with`cy.request` and move commands to web, and now all ok, so problem in `cy.exec`, not in my commands.

And one more thing, commands are executed, I don't need to check response, but get timeout.

### Desired behavior:

Command just executed like some days ago or in previous versions.

### Steps to reproduce: (app code and test code)

I can't do it, because it is happens every build in different specs, and not all `cy.exec` calls failed.

### Versions
Cypress 3.3.1
Linux (CircleCI machine)

**Comment by jennifer-shehane** [comment]
Hey @YaroslavMolchan, sorry I'm having a little trouble understanding where this failure is happening. You said:

>I updated to Cypress 3.3.1 and all will be fine

Is this error occurring in 3.3.1 or only in 3.2.0?

**Comment by YaroslavMolchan** [comment]
@jennifer-shehane only in 3.3.1 and not after update, when I update to 3.3.1 from 3.1.0 (I don't use 3.2.0) all works fine and some days ago got first errors.

**Comment by jennifer-shehane** [comment]
This only fails in CircleCI? Can you provide the full code for the command you are running in cy.exec()?

**Comment by bdiz** [comment]
I'm getting this failure too. Cypress 3.2.0 locally on Ubuntu 18.04.1 LTS.

My exec statement takes about 20 seconds so I uped the timeout to 60 seconds. I regularly hit the 1 minute timeout even though the command finished much earlier. It times out about 30% of the time for me. Quite frustrating.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
