### ISSUE TITLE
Calling Cypress.env() in fixture throws: Can't start server

### ISSUE THREAD

**Issue by edouard-lopez** [cypress-io/cypress#4572]
### Current behavior:

![image](https://user-images.githubusercontent.com/1212392/60163447-f1279780-97fb-11e9-95c7-14fb9ac7b665.png)

That throws this: 

	ReferenceError: Cypress is not defined

If I remove the `Cypress.env()` call it works but that forces me to export the variable in the `env` instead of using the `cypress.env.json`

	ReferenceError: Cypress is not defined
	    at Object.Cypress (/data/projects/Wazo/nestbox-ui-ng/acceptance/fixtures/master-reseller.js:3:61)
	    at Object.<anonymous> (/data/projects/Wazo/nestbox-ui-ng/acceptance/fixtures/master-reseller.js:14:3)
	    at Module._compile (module.js:642:30)
	    at Module._compile (/data/projects/Wazo/nestbox-ui-ng/node_modules/pirates/lib/index.js:99:24)
	    at Module._extensions..js (module.js:653:10)
	    at Object.newLoader [as .js] (/data/projects/Wazo/nestbox-ui-ng/node_modules/pirates/lib/index.js:104:7)
	    at Module.load (module.js:561:32)
	    at tryModuleLoad (module.js:504:12)
	    at Function.Module._load (module.js:496:3)
	    at Module.require (module.js:586:17)
	    at require (internal/module.js:11:18)
	    at require (/data/projects/Wazo/nestbox-ui-ng/acceptance/plugins/cleanup-data.js:32:26)
	    at tryCatch (/data/projects/Wazo/nestbox-ui-ng/node_modules/regenerator-runtime/runtime.js:62:40)
	    at Generator.invoke [as _invoke] (/data/projects/Wazo/nestbox-ui-ng/node_modules/regenerator-runtime/runtime.js:288:22)
	    at Generator.prototype.(anonymous function) [as next] (/data/projects/Wazo/nestbox-ui-ng/node_modules/regenerator-runtime/runtime.js:114:21)
	    at asyncGeneratorStep (/data/projects/Wazo/nestbox-ui-ng/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
	From previous event:
	    at load (/home/ed8/.cache/Cypress/3.3.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:61:7)
	    at EventEmitter.ipc.on (/home/ed8/.cache/Cypress/3.3.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:132:5)
	    at emitOne (events.js:116:13)
	    at EventEmitter.emit (events.js:211:7)
	    at process.<anonymous> (/home/ed8/.cache/Cypress/3.3.1/Cypress/resources/app/packages/server/lib/plugins/util.js:25:29)
	    at emitTwo (events.js:126:13)
	    at process.emit (events.js:214:7)
	    at emit (internal/child_process.js:772:12)
	    at _combinedTickCallback (internal/process/next_tick.js:141:11)
	    at process._tickCallback (internal/process/next_tick.js:180:9)

### Steps to reproduce: (app code and test code)

```js
	export default {
	  email: 'john',
	  password: process.env.CYPRESS_MASTER_PASSWORD || Cypress.env('MASTER_PASSWORD'),
	};
```

### Versions

**cypress**
	3.3.1
Browser: 
	Chromium
**OS**
	NAME="Linux Mint"
	VERSION="19.1 (Tessa)"
	ID=linuxmint
	ID_LIKE=ubuntu
	PRETTY_NAME="Linux Mint 19.1"
	VERSION_ID="19.1"
	HOME_URL="https://www.linuxmint.com/"
	SUPPORT_URL="https://forums.ubuntu.com/"
	BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
	PRIVACY_POLICY_URL="https://www.linuxmint.com/"
	VERSION_CODENAME=tessa
	UBUNTU_CODENAME=bionic

**Comment by jennifer-shehane** [comment]
I think this is ultimately related to this issue https://github.com/cypress-io/cypress/issues/1271 with some explanation on why from @brian-mann  here https://github.com/cypress-io/cypress/issues/1271#issuecomment-394127173 Will close as duplicate.
