### ISSUE TITLE
stubbing a XHR call using a fixture file with null content raises an error

### ISSUE THREAD

**Issue by andreaazzara** [cypress-io/cypress#472]
### Current behavior:
when stubbing a XHR call using a fixture file with `null` content an error is raised

### Expected behavior:
`JSON.parse('null')` returns `null`, no error is raised

### How to reproduce the current behavior:

```js
cy.server().route({
  method: 'GET',
  url: 'some/url',
  response: 'fixture:stub_file.json'
})
```
where `stub_file.json` is a file containing the string 
```null```

### Additional Info (images, notes, stack traces, etc)
Error trace
```
Error:        CypressError: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:259:9)
    at Function.Buffer.from (buffer.js:96:10)
    at new Buffer (buffer.js:75:17)
    at Object.<anonymous> (/Applications/Cypress.app/Contents/Resources/app/index.js:1804:21)
    at Object.tryCatcher (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at /Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Applications/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

* Operating System: OSX Sierra
* Cypress Version: 0.19.1

**Comment by jennifer-mann** [comment]
Can verify this bug. This actually occurs on the XHR Stub of the route, not on the invocation of the `cy.route()` with `null` fixture data itself.

This is fine:
```js
cy
  .server()
  .route({
    method: "GET",
    url: /comments/,
    response: 'fixture:null-data.json'
  })
```

This is not fine:
```js
cy
  .server()
  .route({
    method: "GET",
    url: /comments/,
    response: 'fixture:null-data.json'
  })

  // clicking this button initiates out GET to /comments/
  .get('.fixture-btn').click()
```

<img width="545" alt="screen shot 2017-03-23 at 1 05 38 pm" src="https://cloud.githubusercontent.com/assets/1271364/24260235/a5669240-0fc9-11e7-8d2f-a4ff19ff3bd2.png">
