### ISSUE TITLE
Error: Cannot find module 'rxjs-compat/Subject'

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#4944]
```
yarn add cypress@latest
yarn add v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/2] ⠁ core-js
error /Users/tnrich/Sites/lims/e2e-tests/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /Users/tnrich/Sites/lims/e2e-tests/node_modules/cypress
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'rxjs-compat/Subject'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tnrich/Sites/lims/node_modules/rxjs/Subject.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/tnrich/Sites/lims/e2e-tests/node_modules/listr/lib/task.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

Command failed: /Users/tnrich/.yvm/versions/v1.16.0/bin/yarn.js --ignore-engines add cypress@latest
```

I'm getting this error currently when trying to install the latest version of cypress. Has anyone else run into this issue?

Thanks!

**Comment by tnrich** [comment]
@jennifer-shehane I think re-opening and merging in PR #3416 will fix this issue I'm seeing.

**Comment by jkrehm** [comment]
@tnrich I just ran into this issue, too. Did you figure out a work-around for it?

**Comment by CypressCecelia** [comment]
Hi @jkrehm can you provide more info on what command you are running that causes this error? Also, what operating system, version of node, yarn/npm, etc.?

**Comment by jkrehm** [comment]
Thanks @CypressCecelia. The command is `yarn install`. It's failing on Cypress's postinstall script.

Windows 8.1 (6.3.9600)
Node 12.10
Yarn 1.22

```
[4/4] Rebuilding all packages...
error E:\001-agent1\_work\436\s\Aviato\node_modules\cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: E:\001-agent1\_work\436\s\Aviato\node_modules\cypress
Output:
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'rxjs-compat/Subject'
Require stack:
- E:\001-agent1\_work\436\s\Aviato\node_modules\rxjs\Subject.js
- E:\001-agent1\_work\436\s\Aviato\node_modules\listr\lib\task.js
- E:\001-agent1\_work\436\s\Aviato\node_modules\listr\index.js
- E:\001-agent1\_work\436\s\Aviato\node_modules\cypress\lib\tasks\install.js
- E:\001-agent1\_work\436\s\Aviato\node_modules\cypress\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\001-agent1\_work\436\s\Aviato\node_modules\rxjs\Subject.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\001-agent1\_work\436\s\Aviato\node_modules\listr\lib\task.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\001-agent1\\_work\\436\\s\\Aviato\\node_modules\\rxjs\\Subject.js',
    'E:\\001-agent1\\_work\\436\\s\\Aviato\\node_modules\\listr\\lib\\task.js',
    'E:\\001-agent1\\_work\\436\\s\\Aviato\\node_modules\\listr\\index.js',
    'E:\\001-agent1\\_work\\436\\s\\Aviato\\node_modules\\cypress\\lib\\tasks\\install.js',
    'E:\\001-agent1\\_work\\436\\s\\Aviato\\node_modules\\cypress\\index.js'
  ]
}
```

**Comment by jazeee** [comment]
I hit this issue when I upgraded to node 10 recently.
It looks like, however, that cypress v4.0.2 does not have this issue. (In addition, my tests are passing, so that's good :rofl: )

**Comment by CypressCecelia** [comment]
@jkrehm can you confirm if you are still experiencing the issue on v4.0.2? Thanks for the info @jazeee!

**Comment by jazeee** [comment]
It is not broken in 4.0.2

**Comment by CypressCecelia** [comment]
Closing as resolved.

**Comment by jkrehm** [comment]
Upgrading to v4.0.2 is proving difficult. If/when we can get there I'll look forward to the issue going away.
