### ISSUE TITLE
Aborted /sockjs-node call causes `tick` command to fail

### ISSUE THREAD

**Issue by andycarrell** [cypress-io/cypress#4949]
# Current behavior:
/sockjs-node call fails:
```
Event:        xhr
cypress_runner.js:174416 Method:       GET
cypress_runner.js:174416 URL:          http://localhost:3000/sockjs-node/info?t=4102448400001
cypress_runner.js:174416 Stubbed:      No
cypress_runner.js:174416 Request:      {body: null}
cypress_runner.js:174416 XHR:          XMLHttpRequest {method: "GET", url: "http://localhost:3000/sockjs-node/info?t=4102448400001", id: "xhr271", aborted: true, …}aborted: trueid: "xhr271"method: "GET"onabort: nullonloadend: nullonloadstart: nullonprogress: nullontimeout: nullreadyState: 0response: ""responseText: ""responseType: ""responseURL: ""responseXML: nullstatus: 0statusText: ""timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}url: "http://localhost:3000/sockjs-node/info?t=4102448400001"withCredentials: falseonerror: (...)onload: (...)onreadystatechange: (...)get onerror: ƒ ()set onerror: ƒ (fn)get onload: ƒ ()set onload: ƒ (fn)get onreadystatechange: ƒ ()set onreadystatechange: ƒ (fn)__proto__: XMLHttpRequest
cypress_runner.js:174416 Error:            at XMLHttpRequest.XHR.abort (http://localhost:3000/__cypress/runner/cypress_runner.js:84594:18)
    at callTimer (http://localhost:3000/__cypress/runner/cypress_runner.js:46282:24)
    at Object.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:46641:25)
    at Object.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:79380:18)
    at Object.clock.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:72777:20)
    at Context.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:72806:13)
    at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:80518:21)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:80223:33
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:134216:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:132234:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:132291:18)
    at Promise._settlePromiseCtx (http://localhost:3000/__cypress/runner/cypress_runner.js:132328:10)
    at Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:129145:12)
    at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:129150:10)
```
At the same time `cy.tick()` fails:
```
Command:           tick
cypress_runner.js:174416 Now:               4102448460000
cypress_runner.js:174416 Methods replaced:  (5) ["setInterval", "clearInterval", "setTimeout", "clearTimeout", "Date"]
cypress_runner.js:174416 Ticked:            60000 milliseconds
cypress_runner.js:174416 Error:             Uncaught Error: Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the 'crossorigin' attribute and setting a CORS header.

https://on.cypress.io/cross-origin-script-error

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at createErrFromMsg (http://localhost:3000/__cypress/runner/cypress_runner.js:77556:14)
    at Object.createUncaughtException (http://localhost:3000/__cypress/runner/cypress_runner.js:77563:13)
    at Object.onUncaughtException (http://localhost:3000/__cypress/runner/cypress_runner.js:80631:20)
    at onError (http://localhost:3000/__cypress/runner/cypress_runner.js:80109:39)
    at callTimer (http://localhost:3000/__cypress/runner/cypress_runner.js:46282:24)
    at Object.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:46641:25)
    at Object.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:79380:18)
    at Object.clock.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:72777:20)
    at Context.tick (http://localhost:3000/__cypress/runner/cypress_runner.js:72806:13)
    at Context.<anonymous> (http://localhost:3000/__cypress/runner/cypress_runner.js:80518:21)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:80223:33
From previous event:
    at run (http://localhost:3000/__cypress/runner/cypress_runner.js:80314:15)
    at Object.cy.(anonymous function) [as clock] (http://localhost:3000/__cypress/runner/cypress_runner.js:80542:11)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:80680:20)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:52609:21)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:52602:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:83886:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:83881:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:78925:51)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:82926:20)
    at Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:53072:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:53178:12
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:52992:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:53002:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:52934:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:52970:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:48211:27)
```
Test runner:
![image](https://user-images.githubusercontent.com/22784983/62675671-09debc00-b9fc-11e9-8d9e-597f20ac9353.png)

### Desired behavior:

Unclear, but there's no reason for the aborted call to fail the tick command? 
> Check your Developer Tools Console for the actual error - it should be printed there.

This is printed in the developer tools console 🤦‍♀️but there's no error in there - some more documentation around this error would be helpful. It's not clear where to add a 'crossorigin' attribute to get the desired behaviour.

### Versions

Cypress: 3.4.0
Electron: 61
`cypress run` & `cypress open` both reproduce this

**Comment by mchl18** [comment]
Could this be related to https://github.com/cypress-io/cypress/issues/8223 ?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
