### ISSUE TITLE
The module 'node_expat.node' was compiled against a different Node.js version

### ISSUE THREAD

**Issue by philjones88** [cypress-io/cypress#4956]
### Current behavior:

Suddenly this cryptic error has appeared. I'm trying to write an NPM package of custom commands + tasks.

```
Error: The module '/work/vq/node-packages/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (/work/vq/node-packages/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/work/vq/node-packages/node_modules/node-expat/lib/node-expat.js:4:32)
    at Object.<anonymous> (/work/vq/node-packages/node_modules/node-expat/lib/node-expat.js:116:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/work/vq/node-packages/node_modules/xml2json/lib/xml2json.js:1:168)
    at Object.<anonymous> (/work/vq/node-packages/node_modules/xml2json/lib/xml2json.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
```

### Desired behavior:

It to be more descriptive on how to fix it

### Steps to reproduce: (app code and test code)

Run cypress:open.

It's an NPM package that's Typescript based but compiled to JS.

Tried `rm -rf node_modules` and yarn restoring but issue persists.

### Versions

node v10.16.0
cypress 3.4.1
MacOS 10.14.6 (Mojave on iMac Pro)

**Comment by philjones88** [comment]
think I've tracked it down to usage of https://www.npmjs.com/package/xml2json as commenting out code using that package gets it to work again. Using 0.11.2.

**Comment by philjones88** [comment]
I ended up reworking the code from xml2json to xml-js to avoid this issue
