### ISSUE TITLE
require msnodesqlv8 giving the error in cypress - Error: None of the binaries loaded successfully

### ISSUE THREAD

**Issue by rodrigrichrod** [cypress-io/cypress#5058]
### Current behavior:

I am trying to run msnodesqlv8 in cypress and I get the following output:

λ npx cypress run

The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\cypress\plugins\index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: None of the binaries loaded successfully. Is your node version >= 10.15 ?
    at failIfNoBinaryExported (C:\node_modules\msnodesqlv8\lib\bootstrap.js:64:15)
    at Object.liveLoad (C:\node_modules\msnodesqlv8\lib\bootstrap.js:51:5)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\bootstrap.js:80:12)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\bootstrap.js:82:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at connectionModule (C:\node_modules\msnodesqlv8\lib\connection.js:10:21)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\connection.js:445:3)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\connection.js:449:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)

### Desired behavior:

The above error should not be thrown and I should be able to run cypress tests.   It works fine if I just have a regular node project, but only throws this error when trying to run it in cypress.

### Steps to reproduce: (app code and test code)

Here are the contents of the index.js file in the plugins folder:

const sql = require('msnodesqlv8');

module.exports = (on, config) => {
}

### Versions

I am running windows 10, cypress 3.4.1, chrome Version 76.0.3809.100.
I have also tried previous versions of cypress and it also gives the same results.

**Comment by bahmutov** [comment]
This is because Cypress tasks run in the Node 8.9.3 that is currently bundled with Cypress application, and thus do not match the Node 10+ that your sql driver requires. Soon you will be able to run tasks using system Node version, watch this pull request to be merged and released: https://github.com/cypress-io/cypress/pull/4436

**Comment by jennifer-shehane** [comment]
You can now set a different Node version than the one bundled in Cypress. See these instructions: https://on.cypress.io/configuration#Node-version
