### ISSUE TITLE
Cypress fails on Windows if the URL contains a port number

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#5129]
### Current behavior:

If the URL contains a port number - which is incredibly common if you're running tests against a webpack dev server - then Cypress attempts to put a colon and the port number into a directory name for video files. Colons are not allowed in filenames on Windows, so this causes everything to fail with a stack trace:

```
...\test-e2e-artifacts\localhost:3001\metrics contains invalid WIN32 path characters.
Error: ...\test-e2e-artifacts\localhost:3001\metrics contains invalid WIN32 path characters.
    at Object.mkdirs (...\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Object.mkdirs (...\node_modules\universalify\index.js:5:67)
    at Object.tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as ensureDirAsync] (<anonymous>:14:23)
    at Object.createVideoRecording (...\lib\modes\run.js:400:15)
    at Object.<anonymous> (...\lib\modes\run.js:442:17)
    at Object.tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Object.maybeStartVideoRecording (...\node_modules\bluebird\js\release\method.js:15:34)
    at Object.runSpec (...\lib\modes\run.js:833:19)
    at ...\lib\modes\run.js:786:24
    at tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (...\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (...\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (...\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromiseCtx (...\node_modules\bluebird\js\release\promise.js:604:10)
    at Async._drainQueue (...\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (...\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (...\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Desired behavior:

For Cypress to work!

### Steps to reproduce: (app code and test code)

Run Cypress on Windows against a URL with a port number in it.

### Versions

Cypress: 3.4.1
Windows 10

**Comment by kaiyoma** [comment]
Never mind, false alarm, this was a problem in our code that runs the tests.
