### ISSUE TITLE
Cypress run hangs on CI server spawn ENOMEM

### ISSUE THREAD

**Issue by Kimserey** [cypress-io/cypress#5144]
### Current behavior:

`cypress run` runs locally but hangs on a CI server with the following logs:

```
DEBUG=cypress:*  npx cypress run

2019-09-15T07:33:20.970Z cypress:cli cli starts with arguments ["/usr/bin/node","/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client/node_modules/.bin/cypress","run"]
2019-09-15T07:33:20.972Z cypress:cli NODE_OPTIONS is not set
2019-09-15T07:33:20.973Z cypress:cli program parsing arguments
2019-09-15T07:33:20.973Z cypress:cli running Cypress
2019-09-15T07:33:21.090Z cypress:cli parsed cli options {}
2019-09-15T07:33:21.092Z cypress:cli verifying Cypress app
2019-09-15T07:33:21.092Z cypress:cli checking environment variables
2019-09-15T07:33:21.095Z cypress:cli checking if executable exists /home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress
2019-09-15T07:33:21.098Z cypress:cli Binary is executable? : true
2019-09-15T07:33:21.099Z cypress:cli binaryDir is  /home/ubuntu/.cache/Cypress/3.4.1/Cypress
2019-09-15T07:33:21.099Z cypress:cli Reading binary package.json from: /home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/package.json
2019-09-15T07:33:21.102Z cypress:cli Found binary version 3.4.1 installed in: /home/ubuntu/.cache/Cypress/3.4.1/Cypress
2019-09-15T07:33:21.107Z cypress:cli { verified: true }
2019-09-15T07:33:21.107Z cypress:cli is Verified ? true
2019-09-15T07:33:21.108Z cypress:cli processing run options
2019-09-15T07:33:21.108Z cypress:cli --key is not set, looking up environment variable CYPRESS_RECORD_KEY
2019-09-15T07:33:21.108Z cypress:cli run to spawn.start args ["--run-project","/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client"]
2019-09-15T07:33:21.108Z cypress:cli undefined DISPLAY environment variable
2019-09-15T07:33:21.108Z cypress:cli Cypress will spawn its own Xvfb
2019-09-15T07:33:21.109Z cypress:cli needs to start own Xvfb? true
2019-09-15T07:33:21.109Z cypress:cli Starting Xvfb
2019-09-15T07:33:21.212Z cypress:cli spawning, should retry on display problem? false
2019-09-15T07:33:21.216Z cypress:cli passing DISPLAY :99
2019-09-15T07:33:21.216Z cypress:cli spawning Cypress with executable: /home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress
2019-09-15T07:33:21.217Z cypress:cli spawn args [ '--run-project', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', '--cwd', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
  cypress:ts Running without ts-node hook in environment "production" +0ms
  cypress:server:cypress starting cypress with argv [ '/home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress', '--run-project', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', '--cwd', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client' ] +0ms
  cypress:server:args argv array: [ '/home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress', '--run-project', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', '--cwd', '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client' ] +0ms
  cypress:server:args argv parsed: { _: [ '/home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress' ], runProject: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', cwd: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', invokedFromCli: true } +24ms
  cypress:server:util:proxy found proxy environment variables { npm_config_proxy: '', npm_config_https_proxy: '' } +0ms
  cypress:server:args options { _: [ '/home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress' ], runProject: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', cwd: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', invokedFromCli: true, config: {} } +2ms
  cypress:server:args argv options: { _: [ '/home/ubuntu/.cache/Cypress/3.4.1/Cypress/Cypress' ], runProject: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', cwd: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', invokedFromCli: true, config: {}, projectRoot: '/home/ubuntu/builds/5hmMLN_X/0/my-project/my-project-client', run: true } +1ms
  cypress:server:appdata path: /home/ubuntu/.config/Cypress/cy/production +0ms
  cypress:server:cypress starting in mode run +2s
  cypress:server:appdata path: /home/ubuntu/.config/Cypress/cy/production +2s
  cypress:server:appdata path: /home/ubuntu/.config/Cypress/cy/production/cache +27ms
```

Configuration is:

```
{
    "baseUrl": "http://localhost:4200",
    "video": false
}
```

and screenshot is disabled:

```
Cypress.Screenshot.defaults({
  screenshotOnRunFailure: false
});

```

Am I missing a setting that would ease the run of Cypress? and are there any minimum required specifications for my CI server to be able to run Cypress?

Thank you!

### Steps to reproduce

Unfortunately I am not able to reproduce it locally.

### Versions

Cypress: 3.4.1
CI Server: 3.3 GHz 1 GiB

**Comment by Kimserey** [comment]
When I ssh into our build server and run cypress manually I see the following:

```
npx cypress run
Warning: We failed to remove old browser profiles from previous runs.

This error will not alter the exit code.

Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:193:20)
    at Object.exports.exec (child_process.js:154:18)
    at Object.exec (ELECTRON_ASAR.js:721:23)
    at Object.exec (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/utils.js:19:8)
    at Promise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find_process.js:64:13)
    at new Promise (<anonymous>:null:null)
    at darwin (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find_process.js:56:12)
    at Promise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find_process.js:229:5)
    at new Promise (<anonymous>:null:null)
    at findProcess (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find_process.js:219:10)
    at Object.pid (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find.js:24:12)
    at Promise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find.js:60:17)
    at new Promise (<anonymous>:null:null)
    at find (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/find-process/lib/find.js:56:10)
    at Object.byPid (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/util/find_process.js:4:10)
    at inactivePids (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/util/profile_cleaner.js:37:22)
    at tryCatcher (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at MappingPromiseArray.PromiseArray._resolve (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/map.js:101:18)
    at MappingPromiseArray.PromiseArray._iterate (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/nodeback.js:42:21
    at f (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:197:8)
    at done (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:434:12)
    at /home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:371:17
    at RES (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/inflight/inflight.js:31:16)
    at f (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/once/once.js:25:25)
    at Glob._readdirEntries (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:578:10)
    at /home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/glob/glob.js:555:12
    at ReaddirReq.Req.done (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:90:22)
    at go$readdir$cb (/home/ubuntu/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.4.1                                                                              │
  │ Browser:    Electron 61 (headless)                                                             │
  │ Specs:      2 found (application-routes.spec.js, enterprise.spec.js)                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: application-routes.spec.js...                                                   (1 of 2) 

Timed out waiting for the browser to connect. Retrying...
       
Timed out waiting for the browser to connect. Retrying again...
```

**Comment by Kimserey** [comment]
I've tried to install Chrome and run with `-b chrome` thinking that Electron might be the cause but it does not make any difference.

**Comment by jennifer-shehane** [comment]
>Warning: We failed to remove old browser profiles from previous runs.

This is a warning and will not affect the build. 

>spawn ENOMEM

This is an out of memory error. Are you sure your machine has enough CPU to run Cypress and browsers?

I have no idea what environment you are running under, so can't really tell you how to monitor your CPU usage exactly, but that's where I would start looking.

**Comment by Kimserey** [comment]
> This is an out of memory error. Are you sure your machine has enough CPU to run Cypress and browsers?

Thanks for the reply. I am not 100% sure, but I am quite confident that I don't have enough CPU and RAM to run the Cypress process.

I was just waiting to get your opinion on this. I'll close this ticket now, thank you!
