### ISSUE TITLE
Issue when running parallel runners within K8 pod

### ISSUE THREAD

**Issue by mattrlong** [cypress-io/cypress#5168]
### Current behavior:
Our docker containers run within a K8 pod. When the starting the all complete to setup xvfb, as all containers share the same network interface they clash: 

```
+ yarn cy:run:ci

yarn run v1.13.0

$ DEBUG='cypress:xvfb,xvfb' CYPRESS_RETRIES=2 cypress run --record --parallel --ci-build-id $BUILD_TAG

2019-09-19T15:22:14.490Z xvfb lock filename /tmp/.X99-lock

2019-09-19T15:22:14.492Z xvfb lock filename /tmp/.X99-lock

2019-09-19T15:22:14.492Z xvfb setting DISPLAY :99

2019-09-19T15:22:14.494Z xvfb all Xvfb arguments [ ':99' ]

2019-09-19T15:22:14.510Z xvfb checking if started by looking for the lock file /tmp/.X99-lock

2019-09-19T15:22:14.514Z cypress:xvfb _XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed

_XSERVTransMakeAllCOTSServerListeners: server already running

(EE) 

Fatal server error:

(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 



2019-09-19T15:22:14.515Z xvfb xvfb closed with error code 1

2019-09-19T15:22:14.516Z xvfb after receiving signal null

2019-09-19T15:22:14.516Z xvfb and stderr output

2019-09-19T15:22:14.516Z xvfb _XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed

_XSERVTransMakeAllCOTSServerListeners: server already running

(EE) 

Fatal server error:

(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 



2019-09-19T15:22:14.516Z xvfb XVFB spawn failed

2019-09-19T15:22:14.516Z xvfb Error: _XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed

_XSERVTransMakeAllCOTSServerListeners: server already running

(EE) 

Fatal server error:

(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 



    at ChildProcess.self._process.on (/home/jenkins/agent/workspace/ty-checks_fix_cypress-containers/node_modules/@cypress/xvfb/index.js:189:23)

    at ChildProcess.emit (events.js:182:13)

    at maybeClose (internal/child_process.js:962:16)

    at Socket.stream.socket.on (internal/child_process.js:381:11)

    at Socket.emit (events.js:182:13)

    at Pipe._handle.close (net.js:606:12)

2019-09-19T15:22:14.532Z xvfb checking if started by looking for the lock file /tmp/.X99-lock

2019-09-19T15:22:14.532Z xvfb while checking for lock file, saw that spawn failed

2019-09-19T15:22:15.355Z xvfb restoring process.env.DISPLAY variable

2019-09-19T15:22:15.355Z xvfb lock filename /tmp/.X99-lock

2019-09-19T15:22:15.355Z xvfb lock file /tmp/.X99-lock

2019-09-19T15:22:15.355Z xvfb lock file /tmp/.X99-lock not found when stopping

Xvfb exited with a non zero exit code.



There was a problem spawning Xvfb.



This is likely a problem with your system, permissions, or installation of Xvfb.



----------



Error: _XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed

_XSERVTransMakeAllCOTSServerListeners: server already running

(EE) 

Fatal server error:

(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)



----------



Platform: linux (Debian - 8.11)

Cypress Version: 3.4.0

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

script returned exit code 1
```

### Desired behavior:

ability to config Xvfb socket number through config

### Steps to reproduce: (app code and test code)

Our Jenkins file looks like this: 

```
String cron_string = BRANCH_NAME == 'master' ? 'H H(0-2) * * *' : ''
String pod_yaml = """
apiVersion: v1
kind: Pod
metadata:
  generateName: flux-sanity-checks-
  namespace: spinnaker
spec:
  containers:
  - name: yarn
    image: quay.io/clearscore/jenkins-node-lts:lts-10.15.1-yarn-1.13.0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
  - name: cypress-1
    image: quay.io/clearscore/jenkins-node-browsers:cypress_v3_4_0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
  - name: cypress-2
    image: quay.io/clearscore/jenkins-node-browsers:cypress_v3_4_0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
  - name: cypress-3
    image: quay.io/clearscore/jenkins-node-browsers:cypress_v3_4_0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
  - name: cypress-4
    image: quay.io/clearscore/jenkins-node-browsers:cypress_v3_4_0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /dev/shm
      name: dev-shm
  volumes:
  - name: dev-shm
    emptyDir:
      medium: Memory
"""

pipeline {
    environment {
        CYPRESS_RECORD_KEY = credentials('Cypress_record_key')

    }
    triggers { cron(cron_string) }
    agent {
        kubernetes {
            yaml pod_yaml
        }
    }
    stages {
        stage('Install') {
            steps {
                container('yarn') {
                    sh 'node --version'
                    sh 'ln -s /root/.npmrc /home/jenkins/.npmrc'
                    sh 'yarn install --frozen-lockfile'
                }
            }
        }
        stage('Test') {
            environment {
                CYPRESS_trashAssetsBeforeRuns = 'false'
            }
            parallel {
                stage('runner-1') {
                    steps {
                        container('cypress-1') {
                            echo "Running build ${env.BUILD_TAG}"
                            sh "yarn cy:run:ci"
                        }
                    }
                }
                stage('runner-2') {
                    steps {
                        container('cypress-2') {
                            echo "Running build ${env.BUILD_TAG}"
                            sh "yarn cy:run:ci"
                        }
                    }
                }
                stage('runner-3') {
                    steps {
                        container('cypress-3') {
                            echo "Running build ${env.BUILD_TAG}"
                            sh "yarn cy:run:ci"
                        }
                    }
                }
                stage('runner-4') {
                    steps {
                        container('cypress-4') {
                            echo "Running build ${env.BUILD_TAG}"
                            sh "yarn cy:run:ci"
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            junit 'cypress/results/*.xml'
        }
        failure {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'cypress/videos/**/*.mp4'
            archiveArtifacts allowEmptyArchive: true, artifacts: 'cypress/screenshots/**/*.png'
            script {
                if(env.GIT_BRANCH == 'master') {
                    slackSend teamDomain: 'cs55',
                        tokenCredentialId: 'flux-sanity-token',
                        channel: '#flux-sanity',
                        color: 'bad',
                        message: "@here *${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
                }
            }
        }
    }
}
```

### Versions

Currently running Cypress v3.4.0

**Comment by jennifer-shehane** [comment]
We've updated our docs to include better instructions on working with Xvfb that we hope will better help with the setup: https://on.cypress.io/continuous-integration#Xvfb

I'll be closing this issue since this is more about the setup required on the machine than an actual bug in Cypress.
