### ISSUE TITLE
cypress crash when run lot of tests - JavaScript heap out of memory

### ISSUE THREAD

**Issue by asafbenm** [cypress-io/cypress#5192]
### Current behavior:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[3816:0000000000276C90]   789909 ms: Mark-sweep 2060.7 (2135.0) -> 2060.6 (2135.0) MB, 1777.1 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002A4FD6AB0A1 <JSObject>
    1: bindContainer(aka bindContainer) [C:\ws\ng-portals\node_modules\typescript\lib\typescript.js:~27833] [pc=000001B6479794A4](this=00000206CB282311 <undefined>,node=000002CE615D2C41 <NodeObject map = 0000024BD01BD351>,con
tainerFlags=45)
    2: bind(aka bind) [C:\ws\ng-portals\node_modules\typescript\lib\typescript.js:~29213] [pc=000001B647974657](this=00000206CB282311 <undefined>,node=0000...

**screenshot:**
![image](https://user-images.githubusercontent.com/2478600/65505146-3b8ae400-ded1-11e9-8ae0-3f4417eea516.png)

**and after the error all the test returned:**

The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Object.send (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\plugins\util.js:34:27)
    at EventEmitter.<anonymous> (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\plugins\preprocessor.js:60:18)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at Object.removeFile (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\plugins\preprocessor.js:108:19)
    at Object.options.onBrowserClose (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\open_project.js:100:30)
    at EventEmitter.<anonymous> (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\browsers\index.js:131:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at EventEmitter.emit (events.js:208:7)
    at BrowserWindow.<anonymous> (C:\Users\jenkins-service\AppData\Local\Cypress\Cache\3.4.1\Cypress\resources\app\packages\server\lib\browsers\electron.js:248:29)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at BrowserWindow.emit (events.js:211:7)

**screenshot:**
![image](https://user-images.githubusercontent.com/2478600/65505238-6a08bf00-ded1-11e9-9940-14fe5178ef30.png)

### Desired behavior:

No crash

### Steps to reproduce: (app code and test code)

1. cypress-typescript-preprocessor on angular
2. npm run cypress - headless with electron 61
3  run over 49 tests
4. system crashes on test 23 and on

### Versions
windows 7
cypress 3.4.1
electron 61

**Comment by asafbenm** [comment]
yes i will split the tests more, although my tests are very small.

**Comment by asafbenm** [comment]
it's seem that transpileOnly: true fix the issue
https://github.com/cypress-io/cypress/issues/2316
