### ISSUE TITLE
Connecting to an external API in a task results in ECONNREFUSED

### ISSUE THREAD

**Issue by coleHafner** [cypress-io/cypress#5304]
### Current behavior:

Running Cypress task which reaches out to 3rd party API fails with `Error: connect ECONNREFUSED 127.0.0.1:80 ` error. This only happens in certain environments.

### Desired behavior:
The task should pass on all environments.

### Steps to reproduce: (app code and test code)

```bash
/****** FILE: cypress/plugins/index.js ******/
'lte-device:create': ({
	apiHost,
	apiKey,
}) => {
	const deviceId = `e2etest-${Math.floor(1000000000 + Math.random() * 9000000000).toString()}`,
		deviceOwnershipCode = '123456';

        // it's failing on this right here. This function uses axios to reach out to 
       // an external API to get some sane defaults for our new simulated device
       // on most machines this works great, but on our build server and a few of our dev's 
      // machines, it fails on the first request with an "Error: connect ECONNREFUSED 
      // 127.0.0.1:80" error.
	return getDefaults({
		apiKey,
		apiHost,
		deviceId,
		verbose: true,
		deviceOwnershipCode,
		mqttMessagesPrefix: '',
		certsResponse: '',
		endpoint: '',

	})
	.then(({
		endpoint,
		mqttMessagesPrefix,
		certsResponse,
	}) =>
		new Promise((resolve, reject) => {
			try{
				simulator({
					deviceId,
					endpoint,
					mqttMessagesPrefix,
					appFwVersion: 1,
					certsResponse: JSON.stringify(certsResponse),
					onConnect: (deviceId, client) => {
						console.log(`device id "${deviceId}" connected!`);

						if (!(client && typeof client.end === 'function')) {
							throw new Error(`Expected client, got ${client}`);
						}
						
						console.log('STOPPING CLIENT!');
						client.end();

						resolve({
							deviceId,
							deviceOwnershipCode,
						});
					}
				});
			} catch (err) {
				console.log(`did reject promise because ${err}`);
				reject(err);
			}
		})
	);
}

/****** FILE: cypress/integration/lteDevice.spec.js ******/
// create device
cy.task('lte-device:create', {
	apiHost,
	apiKey,
}).then(({
	deviceId,
	deviceOwnershipCode,
}) => {
       // code never gets to this point
	cy.log(`Created device "${deviceId}" with pin "${deviceOwnershipCode}"`);

        // run the test...
});
```

The error returned is:
```
> Error: connect ECONNREFUSED 127.0.0.1:80 
    at Object._errnoException (util.js:1024:11) 
    at _exceptionWithHostPort (util.js:1046:20) 
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) 
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85348:11) 
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85303:18) 
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:85335:17) 
      at http://localhost:3000/__cypress/runner/cypress_runner.js:75372:23 
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:118962:23) 
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:116898:31) 
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:116955:18) 
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:117000:10) 
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:117075:18) 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:113687:16) 
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113697:10) 
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113571:14) 
      at <anonymous> 
```

### Versions

|OS                        |Node Version(s)                                                 |Cypress Version | Result |
|-----------------|---------------------------------------------|-----------------|-------|
|MacOS 10.14.6    | v10.15.0, v10.15.3, v11.2.0, v12.0.0, v12.10.0 |v3.4.1                    | PASS   |
|Windows 10 ENT| v12.10.0                                                             |v3.4.1                   | PASS   |
|Windows 10 ENT| v10.15.0                                                             |v3.4.1                   | FAIL     |
|Windows 10 ENT| v11.2.0                                                               |v3.4.1                   | FAIL     |
|AMZ Linux 2.0 standard | v10                                                       |v3.4.1                    | FAIL     |

This is probably TMI, but I wanted to record my test results. Potentially this is something that's right under my nose, but I can't for the life of me figure it out. 

Any help would be much appreciated.

**Comment by coleHafner** [comment]
Hi Cypress Team,

Any word on this?

**Comment by jennifer-shehane** [comment]
Are you setting HTTP_PROXY? 

Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the full set of logs here?

**Comment by coleHafner** [comment]
This was a config error with my test, nothing to do with Cypress. Oops. 🤦‍♂
