### ISSUE TITLE
Separating spec into smaller it blocks or using commands.js fails a passing test

### ISSUE THREAD

**Issue by telangn** [cypress-io/cypress#5363]
Hi @jennifer-shehane @flotwig 
The following spec below passes if it is left this way. But, if I put certain commands of the spec into their own it block, the authentication and login fails. Does it have something to do with not preserving cookies correctly, I don't know.Same thing if I make functions in commands.js and call them from cy into individual it blocks. I have placed the debug log further below.

`describe('Visit GMC page', function() {

    it('Opens meeting room', function() {

      cy.visit('https://pgi.globalmeet.com/eric1')

      cy.get('#continueInBrowserBtn').should('be.visible').click()

      cy.get('#cpp-agree-btn').should('be.visible').click()

      cy.get('#input_email-info').should('be.visible').type('eric+test@centraldesktop.com')

      cy.get('#email-continue-btn').should('be.visible').click()

      cy.get('pgi-label-input.guest-input.first-name.web-input-area.ng-untouched.ng-pristine').should('be.visible')

      cy.get('pgi-label-input.guest-input.first-name.web-input-area.ng-untouched.ng-pristine > div > input').type('Eric')

      cy.get('pgi-label-input.guest-input.last-name.web-input-area.ng-untouched.ng-pristine > div > input').type('Test')

      cy.get('div.guest-continue-button.continue-button > pgi-text-button > button').click()

      cy.get('pgi-text-button.ng-tns-c8-0.ng-star-inserted > button > span').should('be.visible').click()

      cy.wait(3000)

      cy.get('bottom-container-right > div > div > div').should('be.visible').click()

      cy.get('pgi-text-button.yes-button > button > span').should('be.visible').click()

      cy.wait(2000)

      cy.get('feedback-panel > pgi-panel > h2').should('be.visible')
    })
  })`

`GET /oauth2/login 200 101.874 ms - -
GET /2019.15.1/assets/uipages/globalmeet/assets/animation-styles.css 200 27.540 ms - -
GET /2019.15.1/assets/uipages/globalmeet/polyfills.bundle.js 200 28.865 ms - -
GET /2019.15.1/assets/uipages/globalmeet/inline.bundle.js 200 34.843 ms - -
GET /2019.15.1/assets/uipages/globalmeet/scripts.bundle.js 200 52.605 ms - -
GET /2019.15.1/assets/uipages/globalmeet/styles.bundle.css 200 30.828 ms - -
GET /2019.15.1/assets/uipages/globalmeet/vendor.bundle.js 200 28.633 ms - -
GET /2019.15.1/assets/uipages/globalmeet/main.bundle.js 200 76.928 ms - -
GET /2019.15.1/assets/uipages/globalmeet/assets/i18n/en.json 200 17.554 ms - -
GET /2019.15.1/assets/uipages/globalmeet/assets/iconSet.svg 200 23.994 ms - -
POST /users/locale 204 83.479 ms - -
POST /users/setCookiePolicy 204 89.632 ms - -
GET /saml/domain/eric%2Btest%40centraldesktop.com/check 404 83.852 ms - -
GET /users/eric%2Btest%40centraldesktop.com/exists 404 126.517 ms - -
POST /users/authenticate 403 85.057 ms - -
`

`lookup [as oncomplete] (dns.js:92:26) code: 'EAI_AGAIN', errno: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'einhmoxwoxw', host: 'einhmoxwoxw', port: 80 } } +1ms
  cypress:server:proxy request failed in proxy layer { res: { headersSent: false, statusCode: 200 }, req: { url: '/', proxiedUrl: 'http://einhmoxwoxw/', headers: { host: 'einhmoxwoxw', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120  Safari/537.36', 'accept-encoding': 'gzip' }, method: 'HEAD' }, err: { Error: getaddrinfo EAI_AGAIN einhmoxwoxw:80 at Object._errnoException (util.js:1024:11) at errnoException (dns.js:55:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26) code: 'EAI_AGAIN', errno: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'einhmoxwoxw', host: 'einhmoxwoxw', port: 80 } } +3ms
  cypress:server:request aborting { requestId: 'request107' } +1ms
HEAD / - - ms - -
  cypress:server:request received an error making http request { timeout: null, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://fehqsdbglafmipg/', requestId: 'request108', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [], err: { Error: getaddrinfo EAI_AGAIN fehqsdbglafmipg:80 at Object._errnoException (util.js:1024:11) at errnoException (dns.js:55:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26) code: 'EAI_AGAIN', errno: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'fehqsdbglafmipg', host: 'fehqsdbglafmipg', port: 80 } } +0ms
  cypress:server:request exhausted all attempts retrying request { timeout: null, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://fehqsdbglafmipg/', requestId: 'request108', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [], err: { Error: getaddrinfo EAI_AGAIN fehqsdbglafmipg:80 at Object._errnoException (util.js:1024:11) at errnoException (dns.js:55:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26) code: 'EAI_AGAIN', errno: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'fehqsdbglafmipg', host: 'fehqsdbglafmipg', port: 80 } } +0ms
  cypress:server:proxy request failed in proxy layer { res: { headersSent: false, statusCode: 200 }, req: { url: '/', proxiedUrl: 'http://fehqsdbglafmipg/', headers: { host: 'fehqsdbglafmipg', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120  Safari/537.36', 'accept-encoding': 'gzip' }, method: 'HEAD' }, err: { Error: getaddrinfo EAI_AGAIN fehqsdbglafmipg:80 at Object._errnoException (util.js:1024:11) at errnoException (dns.js:55:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26) code: 'EAI_AGAIN', errno: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'fehqsdbglafmipg', host: 'fehqsdbglafmipg', port: 80 } } +2ms
  cypress:server:request aborting { requestId: 'request108' } +1ms
HEAD / - - ms - -
  cypress:server:events got request for event: get:project:status, { id: 'GM5Test', path: '/home/ninad/cypress-project' } +9s
  cypress:server:project get project status for GM5Test /home/ninad/cypress-project +10s
  cypress:server:file get values from /home/ninad/.config/Cypress/cy/production/cache +10s
  cypress:server:file attempt to get lock on /home/ninad/.config/Cypress/cy/production/cache +0ms
  cypress:server:file gettin lock succeeded or failed for /home/ninad/.config/Cypress/cy/production/cache +2ms
  cypress:server:file read /home/ninad/.config/Cypress/cy/production/cache +0ms
  cypress:server:file read succeeded or failed for /home/ninad/.config/Cypress/cy/production/cache +0ms
  cypress:server:file attempt to unlock /home/ninad/.config/Cypress/cy/production/cache +1ms
  cypress:server:file unlock succeeded or failed for /home/ninad/.config/Cypress/cy/production/cache +0ms
  cypress:server:events send error: { Error: You're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/errors.js:306:11) at /home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/user.js:63:26 at tryCatcher (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31) at Promise._settlePromise (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18) at Promise._settlePromise0 (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10) at Promise._settlePromises (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18) at Async._drainQueue (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16) at Async._drainQueues (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:789:20) at tryOnImmediate (timers.js:751:5) at processImmediate [as _immediateCallback] (timers.js:722:5) isCypressErr: true, type: 'NOT_LOGGED_IN', details: undefined, isApiError: true } +5ms
  cypress:server:events sending ipc data { type: 'get:project:status', data: { id: 0.7038045575125567, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: 'Error: You\'re not logged in.\n\nRun `cypress open` to open the Desktop App and log in.\n    at Object.get (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/errors.js:306:11)\n    at /home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/user.js:63:26\n    at tryCatcher (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/ninad/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)\n', message: 'You\'re not logged in.\n\nRun `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } } } +1ms
^C
ninad@ninad-Gazelle:~/cypress-project$ 
`

**Comment by telangn** [comment]
Non - issue. 
Need to follow "Best Practices" in Cypress Docs, better.
