### ISSUE TITLE
Failed cy.exec should log full error

### ISSUE THREAD

**Issue by mxstbr** [cypress-io/cypress#5470]
### Current behavior:

When calling a command that fails with `cy.exec`, the stderr output is truncated:

```
CypressError: cy.exec('script/setup') failed because the command exited with a non-zero code.
Stderr:
go: finding github.com/package1 v2.3.1
go: finding github.com/package2 v0.0.3
go: finding github.com/package3 v0.0.0
go: finding g...
      at Object.cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://localhost:3001/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:85335:17)
      at http://localhost:3001/__cypress/runner/cypress_runner.js:72714:23
      at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:117079:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>
```

### Desired behavior:

Cypress should log the full stderr output to allow debugging of the issue:

```
CypressError: cy.exec('script/setup') failed because the command exited with a non-zero code.
Stderr:
go: finding github.com/package1 v2.3.1
go: finding github.com/package2 v0.0.3
go: finding github.com/package3 v0.0.0
go: finding golang.org/x/net v0.0.0-20190613194153-d28f0bde5980
go: github.com/package3@v0.0.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/runner/go/pkg/mod/cache/vcs/075ee809aae0177b65597ee0f28e756d8e2e5e438325d9b042470844e74f817e: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### Steps to reproduce: (app code and test code)

Call `cy.exec` with a command that fails with a long error (e.g. stack trace).

### Versions

Cypress 3.4.1

**Comment by Leksat** [comment]
Example code:
```
cy.exec('(yes "Very long output" | head -n 100) && false')
```

**Comment by Leksat** [comment]
Workaround:
```js
const exec = command => {
  cy.exec(command, { failOnNonZeroExit: false }).then(result => {
    if (result.code) {
      throw new Error(`Execution of "${command}" failed
      Exit code: ${result.code}
      Stdout:\n${result.stdout}
      Stderr:\n${result.stderr}`);
    }
  })
}
exec('(yes "Very long output" | head -n 100) && false')
```

**Comment by B-Galati** [comment]
Thanks for this workaround that works like a charm.

**Comment by bodinsamuel** [comment]
+1 on this

**Comment by dokterbob** [comment]
Here's some activity. Still relevant!

**Comment by jennifer-shehane** [comment]
The truncation you are seeing is deliberate but too aggressive: when a command exits non-zero, we cut both stdout and stderr to 200 characters before putting them in the error message.

Because cy.exec() was deprecated in [Cypress 15.21.0](https://docs.cypress.io/app/references/changelog#15-21-0) and will be removed in a future major release, we won't be changing this behavior. cy.exec() runs your command through the shell on the machine running Cypress, so its behavior depends on your operating system, your shell, your login environment, and whether a terminal is attached. That is the root of this issue and several others like it. 

The replacement is [cy.task()](https://docs.cypress.io/api/commands/task), which runs in the Node process that already loads your Cypress config. Moving to cy.task() also fixes this specific problem, because you own the error handling in Node and decide how much output to keep:

```js
// cypress.config.js
const { defineConfig } = require('cypress')
const { execFileSync } = require('child_process')

module.exports = defineConfig({
  e2e: {
    setupNodeEvents (on, config) {
      on('task', {
        setup () {
          try {
            return execFileSync('script/setup', [], {
              cwd: config.projectRoot,
              encoding: 'utf8',
              stdio: 'pipe',
            })
          } catch (err) {
            throw new Error(`script/setup failed with exit code ${err.status}\n\nStdout:\n${err.stdout}\n\nStderr:\n${err.stderr}`)
          }
        },
      })
    },
  },
})
```

```js
// in your spec
cy.task('setup')
```

The message you throw from the task is the message Cypress shows, in full, with no 200 character cap. A few things worth knowing when you migrate:

- A task must return a value or null. Returning undefined fails the task.
- Tasks time out after 60 seconds by default. Use [taskTimeout](https://docs.cypress.io/app/references/configuration#Timeouts), or pass { timeout } to cy.task(), for longer work.
- Tasks are registered once for the whole project, so an exec call duplicated across specs usually collapses into a single task.

We are going to close this issue as part of the cy.exec() deprecation. If you move to cy.task() and still hit output that Cypress truncates, please open a new issue.
