### ISSUE TITLE
Cypress not handling circular objects in `cy.task`

### ISSUE THREAD

**Issue by c32hedge** [cypress-io/cypress#5539]
Cypress does not appear to handle objects passed as arguments to `cy.task` that contain circular references.

### Current behavior:

We have some code that passes an object to a command-line tool using `cy.task` to populate a database. Due to the database structure, there is a circular reference, but we implement `toJSON` on one of the objects to remove the circular reference when calling `JSON.stringify` on the object as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior

**This worked up through Cypress 3.3.1, but as of 3.3.2 and later, the call to `cy.task` throws a `RangeError: Maximum call stack size exceeded` error.**

I have a somewhat minimal reproducible example, but it isn't _quite_ the same as the problem I'm seeing in my production tests because it gives the error in earlier versions as well (I tested on Cypress 3.3.1 and 3.2.0). It also depends on using TypeScript, but I suspect I can strip that out.

I still think the behavior represented by my example is a bug, though.

### Desired behavior:

Passing an object with circular references through `cy.task` should not blow the call stack.

### Steps to reproduce: (app code and test code)

In my test code, note that the JSON.stringify call succeeds, but calling `cy.task` and passing the object to the `example` task fails.

https://github.com/c32hedge/cypress-test-tiny/tree/5539

### Versions

Cypress 3.3.2, 3.4.1, and 3.5.0 tested
Chrome 77.0.3865.120 (Official Build) (64-bit)
Ubuntu 18.04 LTS

**Comment by c32hedge** [comment]
Call stack from 3.5.0 (from my actual tests, not the minimal example):

```
CypressError: cy.task(<our task name>) failed with the following error:

> RangeError: Maximum call stack size exceeded
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144418:23)
    at <redacted>/__cypress/runner/cypress_runner.js:144489:34
    at arrayEach (<redacted>/__cypress/runner/cypress_runner.js:142314:11)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144483:7)
    at <redacted>/__cypress/runner/cypress_runner.js:144489:34
    at arrayEach (<redacted>/__cypress/runner/cypress_runner.js:142314:11)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:144483:7)
    at Function.cloneDeep (<redacted>/__cypress/runner/cypress_runner.js:152886:14)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:26)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:128213:12)
From previous event:
    at runCommand (<redacted>/__cypress/runner/cypress_runner.js:100007:14)
    at next (<redacted>/__cypress/runner/cypress_runner.js:100142:14)
    at <redacted>/__cypress/runner/cypress_runner.js:100165:18
From previous event:
    at next (<redacted>/__cypress/runner/cypress_runner.js:100142:34)
From previous event:
    at <redacted>/__cypress/runner/cypress_runner.js:100179:37
From previous event:
    at run (<redacted>/__cypress/runner/cypress_runner.js:100171:15)
    at Object.cy.<computed> [as task] (<redacted>/__cypress/runner/cypress_runner.js:100537:11)
    at Context.runnable.fn (<redacted>/__cypress/runner/cypress_runner.js:100724:20)
    at callFn (<redacted>/__cypress/runner/cypress_runner.js:30931:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:30924:7)
    at <redacted>/__cypress/runner/cypress_runner.js:103593:28
From previous event:
    at Object.onRunnableRun (<redacted>/__cypress/runner/cypress_runner.js:103582:17)
    at $Cypress.action (<redacted>/__cypress/runner/cypress_runner.js:97300:30)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:102519:20)
    at next (<redacted>/__cypress/runner/cypress_runner.js:31274:10)
    at <redacted>/__cypress/runner/cypress_runner.js:31296:5
    at timeslice (<redacted>/__cypress/runner/cypress_runner.js:26364:27)
```

**Comment by c32hedge** [comment]
Call stack from 3.3.2:

```
CypressError: cy.task(<our task name>) failed with the following error:

> RangeError: Maximum call stack size exceeded
    at baseKeys (<redacted>/__cypress/runner/cypress_runner.js:32294:22)
    at keys (<redacted>/__cypress/runner/cypress_runner.js:42114:60)
    at baseGetAllKeys (<redacted>/__cypress/runner/cypress_runner.js:31864:20)
    at getAllKeys (<redacted>/__cypress/runner/cypress_runner.js:34664:14)
    at baseClone (<redacted>/__cypress/runner/cypress_runner.js:31496:39)
    at Function.cloneDeep (<redacted>/__cypress/runner/cypress_runner.js:39895:14)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:26)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
    at hasBinary (<redacted>/__cypress/runner/cypress_runner.js:179528:12)
From previous event:
    at runCommand (<redacted>/__cypress/runner/cypress_runner.js:80052:14)
    at next (<redacted>/__cypress/runner/cypress_runner.js:80136:14)
    at <redacted>/__cypress/runner/cypress_runner.js:80148:18
From previous event:
    at next (<redacted>/__cypress/runner/cypress_runner.js:80136:34)
From previous event:
    at <redacted>/__cypress/runner/cypress_runner.js:80155:37
From previous event:
    at run (<redacted>/__cypress/runner/cypress_runner.js:80153:15)
    at Object.cy.<computed> [as task] (<redacted>/__cypress/runner/cypress_runner.js:80380:11)
    at Context.runnable.fn (<redacted>/__cypress/runner/cypress_runner.js:80518:20)
    at callFn (<redacted>/__cypress/runner/cypress_runner.js:52609:21)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:52602:7)
    at <redacted>/__cypress/runner/cypress_runner.js:83512:28
From previous event:
    at Object.onRunnableRun (<redacted>/__cypress/runner/cypress_runner.js:83507:20)
    at $Cypress.action (<redacted>/__cypress/runner/cypress_runner.js:78777:51)
    at Hook.Runnable.run (<redacted>/__cypress/runner/cypress_runner.js:82573:20)
    at next (<redacted>/__cypress/runner/cypress_runner.js:52948:10)
    at <redacted>/__cypress/runner/cypress_runner.js:52970:5
    at timeslice (<redacted>/__cypress/runner/cypress_runner.js:48211:27)
```

**Comment by jennifer-shehane** [comment]
I am able to see the Maximum call stack error with the repo provided. And yes, it would be ideal if it could be narrowed down without the TypeScript and such. 

<img width="450" alt="Screen Shot 2019-10-30 at 2 46 18 PM" src="https://user-images.githubusercontent.com/1271364/67888890-46feaa00-fb24-11e9-89b4-4da92575d714.png">

**Comment by c32hedge** [comment]
Just pushed an update that removes the TypeScript dependency.

**Comment by jennifer-shehane** [comment]
A simplified example of this below:

spec.js

```js
class A {
  constructor() {
    this.B = [new B(this)]
  }
}

class B {
  constructor(a) {
    this.A = a
  }
}

it('works', () => {
  cy.task('example', {
    A: new A()
  })
})
```

plugins/index.js

```js
module.exports = (on) => {
  on('task', {
    example() {}
  })
}
```

<img width="450" alt="Screen Shot 2019-10-30 at 5 15 53 PM" src="https://user-images.githubusercontent.com/1271364/67899567-f3e32200-fb38-11e9-913f-864bb56bd3ea.png">

**Comment by sainthkh** [comment]
Internally, Cypress uses [`child_process.fork()`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) to create a child process and runs the command inside it.

By default, `child_process` uses json as serializer. And it doesn't provide custom serializer. Because of that, it fails serializing circular objects. 

The workaround is to manually serialize/deserialize it. 

```js
before(() => {
  cy.log(JSON.stringify(obj))
  cy.task('example', JSON.stringify(obj))
})
```
