### ISSUE TITLE
Bug: Crash "Error: write EPIPE" when running all specs

### ISSUE THREAD

**Issue by lassesteffen** [cypress-io/cypress#5581]
# Current behavior:
Update:
It also crashes on my Mac now:
- Vue 2.6.11
- cypress 3.8.3
- macOS 10.15.2

When running all of my tests cypress crashes with this error. This only happens on Ubuntu, it does not crash on Mac. It also works if I run it without GUI, Chrome and Electron crash in GUI mode. I have 18 specs file, when I run only one of them it works:

```
GET /orders/z3iipa7oas= 200 0.537 ms - -
GET /css/app.e4aeefad.css 304 5.918 ms - -
GET /css/chunk-vendors.62fbbd79.css 304 8.601 ms - -
GET /css/chunk-0aa61690.e4b926f1.css 304 4.638 ms - -
GET /js/app.fc62f77b.js 304 9.212 ms - -
GET /js/chunk-vendors.b651c705.js 304 8.521 ms - -
GET /css/chunk-0cb812a3.0697acb2.css 304 11.145 ms - -
GET /css/chunk-27278954.cf0a50b7.css 304 7.038 ms - -
GET /css/chunk-3475f92a.a9a9c9d3.css 304 9.682 ms - -
GET /css/chunk-410a22a2.75c0ec7e.css 304 5.664 ms - -
GET /css/chunk-43ed880c.e4b926f1.css 304 5.350 ms - -
GET /css/chunk-4a05dc94.e4b926f1.css 304 3.410 ms - -
GET /css/chunk-572f142b.568f3b40.css 304 2.519 ms - -
GET /css/chunk-677fc686.62c976ab.css 304 2.452 ms - -
GET /css/chunk-68cd030a.e4b926f1.css 304 7.274 ms - -
GET /css/chunk-76d417c4.e4b926f1.css 304 8.198 ms - -
GET /css/chunk-a5351ff6.9262b598.css 304 8.077 ms - -
GET /css/chunk-f317d272.3e8d6abe.css 304 7.762 ms - -
GET /js/chunk-0aa61690.9716f6eb.js 304 7.349 ms - -
GET /js/chunk-0cb812a3.4c8f6a6c.js 304 4.126 ms - -
GET /js/chunk-2575eb62.8749f216.js 304 1.822 ms - -
GET /js/chunk-26f3001a.945feef7.js 304 5.930 ms - -
GET /js/chunk-27278954.95f07836.js 304 8.060 ms - -
GET /js/chunk-27b4eec5.90d6688e.js 304 7.316 ms - -
GET /js/chunk-29ba0487.403c9aa4.js 304 6.504 ms - -
GET /js/chunk-2d0a3a88.04798676.js 304 5.955 ms - -
GET /js/chunk-2d210bf7.96992bf6.js 304 1.416 ms - -
GET /js/chunk-2d0cc5ab.c0dbc070.js 304 5.338 ms - -
GET /js/chunk-2d217367.182f7440.js 304 4.745 ms - -
GET /js/chunk-2d22dcfd.6060fc76.js 304 6.336 ms - -
GET /js/chunk-2d2306e4.c980efbd.js 304 5.714 ms - -
GET /js/chunk-2d2308b3.37e3cdda.js 304 5.298 ms - -
GET /js/chunk-3118b5a8.94dc33e6.js 304 4.623 ms - -
GET /js/chunk-3475f92a.c30c3e32.js 304 4.405 ms - -
GET /js/chunk-410a22a2.bd0ea147.js 304 1.474 ms - -
GET /js/chunk-43ed880c.e9dcfa5e.js 304 4.878 ms - -
GET /js/chunk-4a05dc94.b69cc69d.js 304 4.440 ms - -
GET /js/chunk-572f142b.9873e1b5.js 304 4.131 ms - -
GET /js/chunk-677fc686.3d6d359e.js 304 3.829 ms - -
GET /js/chunk-68c4881c.f4ba337b.js 304 3.469 ms - -
GET /js/chunk-68cd030a.28ffa58c.js 304 4.384 ms - -
GET /js/chunk-754253e0.0939945f.js 304 3.356 ms - -
GET /js/chunk-76d417c4.5f54176f.js 304 4.477 ms - -
GET /js/chunk-7f475849.18b97256.js 304 3.844 ms - -
GET /js/chunk-a5351ff6.7b40634e.js 304 2.673 ms - -
GET /js/chunk-f317d272.a8cdd434.js 304 2.372 ms - -
GET /service-worker.js 304 1.949 ms - -
[10845:1101/202121.029179:INFO:CONSOLE(1)] "App is being served from cache by a service worker.
For more details, visit https://goo.gl/AFskqB", source: http://localhost:8080/js/app.fc62f77b.js (1)
GET /sockjs-node/info?t=1572664881023 200 2.107 ms - -
[10845:1101/202121.037736:INFO:CONSOLE(1)] "Service worker has been registered.", source: http://localhost:8080/js/app.fc62f77b.js (1)
GET /img/craftdrive_icon.8b53641e.svg 304 1.930 ms - -
GET /img/craftdrive_white.c9120152.svg 304 1.597 ms - -
GET /orders/Hello%20World 304 1.626 ms - -
GET /service-worker.js 200 3.898 ms - -
[10845:1101/202122.863560:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
[10845:1101/202122.864417:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
GET /service-worker.js 200 2.627 ms - -
[10845:1101/202152.837603:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
[10845:1101/202223.184258:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
[10845:1101/202253.501712:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
[10845:1101/202323.814396:INFO:CONSOLE(7)] "TypeError: Cannot read property 'edges' of undefined", source: http://localhost:8080/js/chunk-vendors.b651c705.js (7)
GET /__/ 200 1.841 ms - -
GET /__cypress/runner/cypress_runner.css 200 1.228 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.532 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2 200 0.475 ms - 77160
GET /__cypress/iframes/__all 200 7.326 ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-608 200 1.853 ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-845 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Details.spec.ts-541 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Edit.spec.ts-897 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Create.spec.ts-661 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Create.spec.ts-011 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/All.spec.ts-152 - - ms - -
GET /__cypress/iframes/__all 200 9.001 ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-586 - - ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-851 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Edit.spec.ts-825 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Create.spec.ts-822 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/All.spec.ts-796 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Create.spec.ts-120 - - ms - -
[10845:1101/202345.212747:INFO:CONSOLE(97507)] "Uncaught TypeError: Cannot read property 'stop' of null", source: http://localhost:8080/__cypress/runner/cypress_runner.js (97507)
GET /__cypress/iframes/__all 200 8.020 ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Create.spec.ts-001 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Create.spec.ts-988 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Edit.spec.ts-250 200 52.522 ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-999 200 11.543 ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-802 200 8.895 ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/All.spec.ts-592 - - ms - -
GET /__cypress/iframes/__all 200 12.201 ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-310 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/All.spec.ts-481 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Create.spec.ts-256 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-608 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Create.spec.ts-764 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Edit.spec.ts-000 - - ms - -
GET /__cypress/iframes/__all 200 9.757 ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Create.spec.ts-778 200 86.848 ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/Create.spec.ts-247 200 86.719 ms - -
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)

GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-213 200 88.397 ms - -
GET /__cypress/tests?p=tests/e2e/specs/orders/All.spec.ts-450 200 86.747 ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-016 200 88.550 ms - -
GET /__cypress/tests?p=tests/e2e/specs/memberships/Edit.spec.ts-959 200 86.784 ms - -
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)

GET /__cypress/iframes/__all 200 10.529 ms - -
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:443:21)

Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:443:21)

(node:10845) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:443:21)

Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/lasse/snap/code/common/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:443:21)

GET /__cypress/tests?p=tests/e2e/specs/memberships/All.spec.ts-295 - - ms - -
GET /__cypress/tests?p=tests/e2e/support/index.js-856 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/unauthenticated/RegisterTenant.spec.ts-199 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/unauthenticated/Login.spec.ts-567 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/subcontractors/Create.spec.ts-310 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/subcontractors/All.spec.ts-108 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/projects/Edit.spec.ts-517 - - ms - -
GET /__cypress/tests?p=tests/e2e/specs/projects/Details.spec.ts-988 - - ms - -
```

### Versions
- Vue 2.6
- cypress 3.6.0
- Ubuntu 19.10

If you need more info let me know.

**Comment by gabbersepp** [comment]
Have you checked where the error ERR_HTTP_HEADERS_SENT might come from?

**Comment by lassesteffen** [comment]
How would I be able to check that?

**Comment by gabbersepp** [comment]
Good question without knowing your code :-) Have you tried each of the 18 tests isolated? Maybe this error is responsible for the crash.

**Comment by lassesteffen** [comment]
I will try that when I am at my laptop and let you know. 👍

**Comment by paulfalgout** [comment]
I'm also seeing the `Error: write EPIPE` issues on 3.6 and not on 3.4.  I can't exactly narrow it down yet, but I can consistently cause it to happen by attempting to open devtools in the gui while it's GETing all the spec files in the background.  Very rarely it'll happen without that.  I'm also seeing tests hang somewhat consistently on circleci after they've begun to run with 3.6 and not in 3.4.  I don't know if it's a related issue though.

**Comment by RadovanBednar** [comment]
I have the same experience:
- when all specs are run in headless mode - everything :ok:
- when a single suite is run in GUI mode - everything :ok:
- but whenever all specs are run in GUI mode, the test runner crashes :x:

Before the crash one or two instances of `Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)` and then two or four instances of `Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` appear in the console.

This is the first time I tried to run the GUI mode since upgrading to 3.6 a few days ago (usually I only use the headless mode).

**Comment by Lukaszli** [comment]
I can occasionally see this error when running even a single spec in GUI mode :/
"Cypress 3.6.1"

**Comment by denesstreambright** [comment]
I experience the same issue, headless is OK, running each and every test by hand: OK, run all: crash
Ver: 3.7.0
...
`(node:7646) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`
...
`(node:7961) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added. Use emitter.setMaxListeners() to increase limit`
...
`Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16)`
...
`Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/home/xx/.cache/Cypress/3.7.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/xx/.cache/Cypress/3.7.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/xx/.cache/Cypress/3.7.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/home/xx/.cache/Cypress/3.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)`
...

**Comment by lassesteffen** [comment]
I also ran the tests on my machine again, and the single tests work fine, just all of them together seem to crash it for me.

**Comment by rbaxter08** [comment]
Getting a similar errror, unable to run all tests, but running a test individually works.  

Sometimes after running a single test it will let me run all and will complete without error.  It's really intermittent so I'm having a hard time offering anything else that will be useful for debugging.  

```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writevGeneric (internal/stream_base_commons.js:129:3)
    at Socket._writeGeneric (net.js:696:11)
    at Socket._writev (net.js:705:8)
    at doWrite (_stream_writable.js:416:12)
    at clearBuffer (_stream_writable.js:521:5)
    at Socket.Writable.uncork (_stream_writable.js:322:7)
    at connectionCorkNT (_http_outgoing.js:628:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:464:11)
    at ServerResponse.header (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/spec.js:44:22
    at tryCatcher (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/robertbaxter/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

Ver: 3.8.1
Chrome: 79
Node: 12.8.1
Os: MacOS Catalina

**Comment by Auchindoun** [comment]
Seeing this on `3.8.2`. As above, tests work individually, headless on CI, but not via the GUI when running all specs. If I blow everything away with `git clean -xdf` and run it again I can get the spec to run, but any second attempts usually fail.

**Comment by rbaxter08** [comment]
I found [this comment](https://github.com/cypress-io/cypress/issues/2028#issuecomment-400356563) in another issue explaining that "running 'All Tests' from the GUI is not a good idea" and shouldn't be done.  

I'm not sure if that's still the case and curious if this is related, but I think we'll move away from running all specs in interactive mode.

**Comment by Auchindoun** [comment]
If Cypress authors are suggesting not to use the feature, then why does it still exist for end users? 🤔

**Comment by rbaxter08** [comment]
They discuss that briefly in one of the linked issues https://github.com/cypress-io/cypress/issues/681

> This could be solved by removing the Run All Tests button but users would likely complain about this and it's unexpected.

> > Why can every other testing tool run all tests but Cypress can't?

I can understand the concern about removing the button, not sure if I agree with it, but adding a note to the Docs might be helpful.

**Comment by sgronblo** [comment]
I'm also seeing the same error as @rbaxter08 

However I actually got it when running a single test. NOT using the "Run all tests" feature. Today was the first time I saw it, but one of my team members was mentioning Cypress crashing as well.

Running Cypress 3.8.3, MacOS Mojave 10.14.6

**Comment by kicktipp** [comment]
We encounter this problem to. It is very annoying. I would really love to run all tests with GUI.
Single

-  Test: OK
- All Test headless: OK
- All Tests with GUI crashes most of the time. Sometimes it works for no obvious reason.

**Comment by ianberdin** [comment]
The same problem.
macOS Catalina 10.15.4
Cypress 3.8.3

**Comment by Ozzyjtjustin** [comment]
I am Having the same Problem 
macOS Catalina 10.15.4
"cypress": "^4.0.2"

**Comment by KoenCa** [comment]
I also have this error sometimes while I'm running my tests locally in the GUI. Most of the times it happens when I just want to run a **single** test via the GUI. The browser opens for a second and then it crashes with the error below. This doesn't happen very frequently (not enough to be annoying... yet).

```
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/spec.js:37:20
    at tryCatcher (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/koen/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

Also the whole Cypress process stops running when this happens and for some reason it also out puts something like this before it stops:

```
✨  Done in 1954.32s.
```

So it thinks it is running a test suite or something? 🤔  I was just running single tests while developing.

More info:
Cypress version `4.11.0`
Chrome version `84`
MacOS Catalina version `10.15.6`
Node version `12.13.0`

**Comment by tstackhouse** [comment]
I've also had this happen intermittently, haven't been able to reproduce it at all.  I can rerun the exact command again and all my specs load and execute just fine, but wanted to add my voice to give some additional context:

Cypress: 4.5.0
Chrome: 89
Ubuntu: 20.04.2
Node: 12.18.3

**Comment by jennifer-shehane** [comment]
I see many different stack traces and errors in this thread. Across several issues of Cypress. This thread is not completely clear how to reproduce and whether the errors are related.

Please update to the latest version of Cypress. After that, open a new issue providing a reproducible example of the error, clear screenshots/descriptions of the error you're encountering so we can investigate.
