### ISSUE TITLE
Can't start server - socket hang up in Chrome

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#5783]
### Current behavior:

Using `cypress open` or `cypress run` in Chrome browser and running specfile (with any tests) results in error: `Can't start server socket hang up` as shown below in picture.

Running in Electron 73 on either `cypress open` or `cypress run` works fine.

`cypress open` error message with Chrome

<img width="912" alt="Screen Shot 2019-11-25 at 9 53 06 AM" src="https://user-images.githubusercontent.com/1271364/69510905-f89aca80-0f6c-11ea-93e6-15b6643bf777.png">

If I click *Try again*, the spec list reloads so I click back on my specfile, then it attempts to connect to Chrome DevTools Protocol but is unsuccessful after 32 failed attempts with:

```
Can't start server

Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 50806.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:50806 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

<img width="912" alt="Screen Shot 2019-11-25 at 10 35 50 AM" src="https://user-images.githubusercontent.com/1271364/69511981-a5c31200-0f70-11ea-97c3-fc33c549263d.png">

 
`cypress run --browser chrome` error message

```
socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:334:17)
    at Socket.socketCloseListener (_http_client.js:375:25)
    at Socket.emit (events.js:199:15)
    at TCP.<anonymous> (net.js:593:12)
```

### Steps to reproduce: (app code and test code)

Weeellll, I'm working from another country, which is the only thing that has changed since I last ran Cypress.

- I thought it may have to do with my being on a VPN, but I turned off VPN and the same error occurs.
- I thought it may have to do with something I am visiting, but a simple `expect(true).to.be.false` also creates this error.
- I thought it may be isolated to Chrome version - and I SEEMED to have some evidence of that, with Canary 80 and Chromium 74 seemingly working and Chrome 78 not, but when I tried to rerun these again - all of these versions are failing now, so there may be some randomness involved.
- I don't have any `baseUrl` or Proxy setup.
- I've had weird issues before with my Wifi connection blocking things that I was able to resolve before, but I am connected through a hotspot on a 4g cell signal, so no weird WiFi configuration other than that fact.

Full DEBUG logs during `cypress open`: 
[socket-hang-up-cypress-open.log](https://github.com/cypress-io/cypress/files/3884776/socket-hang-up-cypress-open.log)

Logs after clicking 'Try again' during `cypress open`: 

[socket-hang-up-cypress-open-try-again.log](https://github.com/cypress-io/cypress/files/3884815/socket-hang-up-cypress-open-try-again.log)

Full DEBUG logs during `cypress run --browser chrome`: 
[socket-hang-up-cypress-run.log](https://github.com/cypress-io/cypress/files/3884772/socket-hang-up-cypress-run.log)

### Versions

Cypress 3.6.1
Chrome 78, Canary 80, Chromium 74
MacOS Mojave

**Comment by jennifer-shehane** [comment]
Well, I can no longer recreate this. It just stopped happening after a few hours. 😞 Closing as there is no way for us to move forward investigating.

Please comment if you see this behavior and have any more information on why it is occurring and we will consider reopening.
