### ISSUE TITLE
Cypress does not kill all node processes after run

### ISSUE THREAD

**Issue by jlei523** [cypress-io/cypress#5837]
### Current behavior:
 
I have an Next.js + Express.js app.  All my tests pass. During testing, I see 4 node processes in Activity (Mac OS). After Cypress finishes the test, 3 gets killed. One remains. If I try to run cypress again, it says the port is in use.

npm command

```json 
"cypress": "NODE_ENV=test TEST=true node serverStart.js & wait-on http://localhost:3000 && node_modules/.bin/cypress run",
```

![image](https://user-images.githubusercontent.com/3815607/69915539-da5c2f80-1482-11ea-86a7-97b6f84b61b6.png)

System: Mac OS Catalina
Node: v10.16.3
Cypress: 3.7.0

```javascript
// / <reference types="Cypress" />
// cypress spec files runs in the browser so we can't import things that can only run in the browser

const email = 'authy1@Cypress.io';

describe('auth', () => {
  it('shows home page reg dialog correctly', () => {
    cy.visit('/');

    cy.get('.pure-button').click();
    cy.get('.MuiModal-root-45').should('exist');
    cy.get('.MuiButton-label-77').click({ multiple: true, force: true });
    cy.contains('One last step.').should('exist');
    cy.contains('Enter a valid email').should('not.exist');
    cy.contains('The password must be at least 6 characters').should('not.exist');

    cy.get('input[name=email]').type('wefjwof@sdfsf');
    cy.contains('Enter a valid email').should('exist');
    cy.get('input[name=email]').clear();
    cy.get('input[name=email]').type('wefjwof@sdfsf.com');
    cy.contains('Enter a valid email').should('not.exist');

    cy.get('input[name=password]').type('pasrd');
    cy.contains('The password must be at least 6 characters').should('exist');
    cy.get('input[name=password]').clear();
    cy.get('input[name=password]').type('password');
    cy.contains('The password must be at least 6 characters').should('not.exist');
  });

  it('registers a new user', () => {
    cy.visit('/condition/acid-reflux');

    cy.get('.titleRight button.followButton').click();
    cy.get('.react-swipeable-view-container').should('exist');

    cy.get('input[name="username"]').should((value) => {
      expect(value[0].value.length).to.be.above(1);
    });

    cy.get('.usernameForm .MuiButtonBase-root-16').click();

    cy.get('button.toggleButton').should('have.text', 'Acid reflux (GERD)');

    cy.get('#multiSearchBoxInput').click();
    cy.wait(1000);

    cy.get('.resultWrapper').should('exist');
    cy.wait(2000);

    cy.get('a.hit').click({ multiple: true });
    cy.get('.result')
      .children()
      .should('have.length', 5);

    cy.wait(1000);

    cy.get('.conditionFollowForm .MuiButton-label-96').click({ force: true });
    cy.wait(1000);

    cy.get('input[name=email]').type(`${email}`);
    cy.get('input[name=password]').type('password{enter}');

    cy.location('pathname', { timeout: 10000 }).should('eq', '/condition/acid-reflux');

    cy.window()
      .its('__NEXT_REDUX_STORE__')
      .invoke('getState')
      .its('session')
      .its('isLoggedIn')
      .should((val) => {
        expect(val).to.be.true;
      });
  });

  it('should log in', () => {
    cy.visit('/condition/acid-reflux');

    cy.get('.auth')
      .find('a')
      .first()
      .click();

    cy.contains('Welcome back').should('exist');
    cy.get('input[name=email]').type(email);

    cy.get('input[name=password]').type('password{enter}');

    cy.wait(5000);
    cy.location('pathname', { timeout: 10000 }).should('eq', '/condition/acid-reflux');

    cy.window()
      .its('__NEXT_REDUX_STORE__')
      .invoke('getState')
      .its('session')
      .its('isLoggedIn')
      .should((val) => {
        expect(val).to.be.true;
      });
  });
  it('should show dialog when clicking on voting', () => {
    cy.visit('/condition/acid-reflux/treatments');

    cy.get('.effect')
      .first()
      .click({ force: true });

    cy.get('.selectionWrapper')
      .first()
      .click();

    cy.get('.react-swipeable-view-container').should('exist');
  });

  after(async () => {
    cy.task('deleteEmail', email);
  });
});
```

```javascript
const knex = require('../../db/db');

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // register plugin's task
  // and register my own task
  on('task', {
    deleteEmail(email) {
      return new Promise(async (resolve) => {
        // tasks should not resolve with undefined

        await knex.raw(`delete from users where email = '${email}'`);

        resolve(null);
      });
    },
  });
};
```

### First test passes fine. Cypress exits. But it does not kill node. Second test says port is being used.
```
 git:(cypress) ✗ npm run cypress

> wecured@1.0.0 cypress /Users/Dropbox/medtally/medtally-app
> NODE_ENV=test TEST=true node serverStart.js & wait-on http://localhost:3000 && node_modules/.bin/cypress run

[styled-jsx] Loading plugin from path: /Users/joelei/Dropbox/medtally/medtally-app/node_modules/styled-jsx-plugin-sass/index.js
> Using external babel configuration
> Location: "/Users/joelei/Dropbox/medtally/medtally-app/.babelrc"
[ ready ] compiled successfully
[ wait ]  compiling ...
info: > Medtally ready
[ ready ] compiled successfully
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: TransitionGroup
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: CSSTransitionGroupChild
[ event ] client pings, but there's no entry for page: /conditionPage
[ event ] build page: /_error
[ wait ]  compiling ...
[ ready ] compiled successfully
[ event ] build page: /conditionPage
[ wait ]  compiling ...

=================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.7.0                                                                              │
  │ Browser:    Electron 73 (headless)                                                             │
  │ Specs:      1 found (auth_spec.js)                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  auth_spec.js                                                                    (1 of 1)


  auth
[ ready ] compiled successfully
info: fetching feed data for condition 582
    ✓ shows home page reg dialog correctly (6752ms)
info: fetching feed data for condition 582
info: fetching feed data for condition 582
info: checking whether username exists MusicalDeer
info: Register new account successfully for authy1@Cypress.io
info: fetching feed data for condition 582
    ✓ registers a new user (30841ms)
info: fetching feed data for condition 582
info: Log in successfully as authy1@Cypress.io
info: fetching feed data for condition 582
    ✓ should log in (19739ms)
info: fetching treatment data for condition 582
info: fetching all treatment tags from table
[ event ] disposing inactive page(s): /_error
    ✓ should show dialog when clicking on voting (4772ms)


  4 passing (1m)

(node:60638) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      4                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 2 seconds                                                              │
  │ Spec Ran:     auth_spec.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: /Users/joelei/Dropbox/medtally/medtally-app/cypress/videos/    (6 seconds)
                          auth_spec.js.mp4


=================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  auth_spec.js                             01:02        4        4        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        01:02        4        4        -        -        -

➜  medtally-app git:(cypress) ✗ npm run cypress

> wecured@1.0.0 cypress /Users/Dropbox/medtally/medtally-app
> NODE_ENV=test TEST=true node serverStart.js & wait-on http://localhost:3000 && node_modules/.bin/cypress run

[styled-jsx] Loading plugin from path: /Users/Dropbox/medtally/medtally-app/node_modules/styled-jsx-plugin-sass/index.js
> Using external babel configuration
> Location: "/Users/joelei/Dropbox/medtally/medtally-app/.babelrc"

=================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.7.0                                                                              │
  │ Browser:    Electron 73 (headless)                                                             │
  │ Specs:      1 found (auth_spec.js)                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  auth_spec.js                                                                    (1 of 1)
[ ready ] compiled successfully
[ wait ]  compiling ...


  auth
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Function.listen (/Users/Dropbox/medtally/medtally-app/node_modules/express/lib/application.js:618:24)
    at app.prepare.then (/Users/Dropbox/medtally/medtally-app/serverStart.js:23:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[ event ] build page: /_error
[ wait ]  compiling ...
[ ready ] compiled successfully
➜  medtally-app git:(cypress) ✗
```

**Comment by jennifer-shehane** [comment]
You are calling `npm run cypress` which calls the `startServer.js` file to run your server on `http://localhost:3000`. 

You are then calling `npm run cypress` again, which calls the `startServer.js` file to run your server on `http://localhost:3000` - when you call the `startServer.js` file, it attempts to run your server on the port that you never closed. 

In this case, it seems the leftover running process is your server started from your file. 

You'll want to split out the calling of starting your server into a single call, maybe before multiple calls of `cypress run`, so that it is not trying to start the server over the existing running server - or stop and restart your server in between calling `cypress run`.

**Comment by jlei523** [comment]
> You are calling `npm run cypress` which calls the `startServer.js` file to run your server on `http://localhost:3000`.
> 
> You are then calling `npm run cypress` again, which calls the `startServer.js` file to run your server on `http://localhost:3000` - when you call the `startServer.js` file, it attempts to run your server on the port that you never closed.
> 
> In this case, it seems the leftover running process is your server started from your file.
> 
> You'll want to split out the calling of starting your server into a single call, maybe before multiple calls of `cypress run`, so that it is not trying to start the server over the existing running server - or stop and restart your server in between calling `cypress run`.

Hey @jennifer-shehane.  Thank you so much for answering.

```
cypress": "NODE_ENV=test TEST=true node serverStart.js & wait-on http://localhost:3000 && node_modules/.bin/cypress run
```

I run `npm run cypress" which starts the server. `wait-on` waits for the server to start. Then I run `node_modules/.bin/cypress run` which starts cypress only.

I don't see where I start the server twice.

**Comment by bahmutov** [comment]
@jlei523 you are starting the server process in the background with `node serverStart.js &` - Cypress has no control over it, it has no idea how to kill any server process, it is up to you to stop the server. You can easily do this using https://github.com/bahmutov/start-server-and-test utility, see https://on.cypress.io/ci#Boot-your-server
