### ISSUE TITLE
wslbridge (Ubuntu on Windows) The display compositor is frequently crashing.

### ISSUE THREAD

**Issue by 3epnm** [cypress-io/cypress#5918]
Using cypress in a Ubuntu on Windows fails with an error:

```
It looks like this is your first time using Cypress: 3.7.0

 ✔  Verified Cypress! /home/johnsmith/.cache/Cypress/3.7.0/Cypress

Opening Cypress...
[23948:1209/141647.044586:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
Unhandled rejection Error: The Test Runner unexpectedly exited via a close event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.7.0
    at /mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/cypress/lib/errors.js:193:15
    at tryCatcher (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/mnt/c/Users/johnsmith/Desktop/Development/dermalog-document/node_modules/bluebird/js/release/promise.js:569:18)
```

Can someone help?

**Comment by google-mac** [comment]
Running into the same issue.

**Comment by jennifer-shehane** [comment]
- Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here? 
- How are you installing Cypress? Are you running in a docker container?
- Are you running with a `--browser` flag or any other configuration?

There seems to be some indication that this may be solved by passing `--disable-features=VizDisplayCompositor` to Chrome (mentioned in this puppeteer issue https://github.com/puppeteer/puppeteer/issues/3774#issuecomment-480210268) 

Can you try setting this flag below in your `plugins/index.js` file and comment if this resolved the issue?

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-features=VizDisplayCompositor')

      return args
    }
  })
}
```

**Comment by google-mac** [comment]
It still fails for me.

```
$ cypress run
[21091:0116/074706.628978:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
The Test Runner unexpectedly exited via a exit event with signal SIGILL
```

I did run it on WSL2 on my personal machine and it worked (even without this plugin code), but my work machine is still on WSL1 until the required Windows update is out of beta.

**Comment by jennifer-shehane** [comment]
Sorry, I did not document this correctly. This error is coming when launching through Electron, so the instructions for sending this app switch to Electron are here: https://on.cypress.io/browser-launch-api#Modify-Electron-app-switches

Can you set the following environment variable on your system, run `cypress run` again and comment on the result?

### Windows

```
set ELECTRON_EXTRA_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
```

### Linux/OSX

```
export ELECTRON_EXTRA_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
```

**Comment by richworx** [comment]
I am having the same problem on WSL1 with cypress 3.8.2. I tried to use the environment variable workaround but it did not help.

I noticed that this issue is also documented at [https://github.com/cypress-io/cypress/issues/5526](https://github.com/cypress-io/cypress/issues/5526) where they suggested potentially implementing a slightly different environment variable, so I tried several variants (listed below). None worked.

```sh
#Environment variables that don't work
export ELECTRON_EXTRA_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
export EXTRA_ELECTRON_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
export EXTRA_ELECTRON_ARGS=--disable-features=VizDisplayCompositor
export CYPRESS_ELECTRON_EXTRA_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
export CYPRESS_EXTRA_ELECTRON_LAUNCH_ARGS=--disable-features=VizDisplayCompositor
export CYPRESS_EXTRA_ELECTRON_ARGS=--disable-features=VizDisplayCompositor
```
@jennifer-shehane are you sure that environment variable is actually used by cypress?

I will also mention that in the issue I linked above, another workaround was suggested that involves patching the file `node_modules/cypress/lib/exec/spawn.js`. Find the line that contains the text `child = cp.spawn` and add a line *above it* with the text `electronArgs.push('--disable-features=VizDisplayCompositor');`
When you finish, it should look like this (without the comments): 

```javascript
electronArgs.push('--disable-features=VizDisplayCompositor'); // add this line
var child = cp.spawn(executable, electronArgs, stdioOptions); // find this line
```

Several people mentioned this worked for them with older Cypress versions, but I have not been able to get it to work with Cypress 3.8.2.

**Comment by cgreene87** [comment]
I'm also experiencing the same issues listed by @richworx and tried everything suggested. I've defaulted back to not using WSL1 (can't update to WSL2 at the moment) for now just to get around the issue.

**Comment by danni-popova** [comment]
Any updates on this? I am having the same issue.

**Comment by Hecsall** [comment]
Recently I've been struggling with this issue with WSL 1, and I discovered a workaround.

Here the tests I tried (WSL 1, not 2):
- npm install with WSL & cypress open with WSL --> ERROR
- npm install with WSL & cypress open with cmd.exe --> ERROR
- npm install with cmd.exe & cypress open with cmd.exe --> **WORKING**

So, if you run everything with the standard windows command prompt (*cmd.exe*), and not with WSL, everything works fine, but you will also have to run the **npm install** with the command prompt, because *I think* that running npm install with WSL downloads something that's specific for Linux and not for Windows.

Hope this helps someone!

**Comment by bpallares** [comment]
In addition to the above, I was able to run cypress from `wsl` by doing 
`powershell.exe npx cypress open`

**Comment by justinstander** [comment]
Still happens for me in Cypress 4.5.0, Win 10, WSL Ubuntu 16.04.

**Comment by justinmchase** [comment]
I was able to successfully install and run this on wsl and cypress latest, I ran `cypress open` and got:

```
Verifying Cypress can run /home/justin/.cache/Cypress/4.5.0/Cypress [started]
```

So that's good news, but of course nothing is popping up, how would it I guess. But I'm wondering if there is a way for cypress to just print out a port so I can run it in a browser instead of a custom tool?

**Comment by justinstander** [comment]
You can do `cypress run` for CLI, or if you want to do `cypress open`,
you'll need to install:  http://www.straightrunning.com/XmingNotes/

The browser spawned will be running in the linux subsystem.

**Comment by vince1995** [comment]
> In addition to the above, I was able to run cypress from `wsl` by doing
> ` > powershell.exe npx cypress open`

Not the way it should work but the best (and the easiest) way it works. Thanks a lot! That should be written down in the troubleshooting as a workaround.

**Comment by pschlette** [comment]
Fwiw, while using WSL 1, I saw all the issues described by https://github.com/cypress-io/cypress/issues/5918#issuecomment-579414224 -- `The display compositor is frequently crashing`, then exiting with `SIGSEGV` after adding that Electron flag in `spawn.js`. Upgraded my distro to WSL 2 and Cypress works out of the box now.

**Comment by jennifer-shehane** [comment]
Just wanted to make sure everyone was aware of this comment showing how to get setup with WSL. https://github.com/cypress-io/cypress/issues/444#issuecomment-501744722 I'm not sure if this is completely up to date.

**Comment by jennifer-shehane** [comment]
This crash is a limitation of WSL1, its syscall translation doesn’t fully support Electron/Chromium’s GPU display compositor, which is what produces The display compositor is frequently crashing followed by SIGILL/SIGSEGV. The --disable-features=VizDisplayCompositor flag didn’t reliably resolve it on WSL1, and as several people confirmed in this thread, upgrading to WSL2 fixes it out of the box (no flags or patches needed).

Since WSL2 has been the default for years and resolves this, and the original report was against Cypress 3.7.0 / Electron 5 (Cypress is now on 15.x), we’re going to close this out. 

If you’re on WSL2 and still hitting a display compositor crash on a current Cypress version, please open a new issue with debug logs (DEBUG=cypress:* cypress run) and we’ll take a look.

For running the GUI (cypress open) under WSL2, you’ll want WSLg or an X server — see the WSL setup notes.

Closing as resolved by WSL2.
