### ISSUE TITLE
Multiple environment variables not loading into Cypress using CLI tool

### ISSUE THREAD

**Issue by RobertMartinGMSL** [cypress-io/cypress#5932]
Multiple environment variables not loading into Cypress using CLI tool

### Desired behavior:

I want to pass CYPRESS_USERNAME and CYPRESS_PASSWORD into cypress from the CLI tool.  I seem to be able to pass the first, but none proceeding the first, into the CLI tool.

NB: I have tried the following, but still unable to pass second arg to `--env`:
```
--env "CYPRESS_USERNAME=user","CYPRESS_PASSWORD=pass"
--env `CYPRESS_USERNAME=user`,`CYPRESS_PASSWORD=pass`
--env CYPRESS_USERNAME=user,CYPRESS_PASSWORD=pass
--env ["CYPRESS_USERNAME"=user,"CYPRESS_PASSWORD=pass"]
--env [`CYPRESS_USERNAME=user`,`CYPRESS_PASSWORD=pass`]
--env [CYPRESS_USERNAME=user,CYPRESS_PASSWORD=pass]
```

I want to pass the username and password into my cypress tests from the CLI tool.  Documentation [here](https://docs.cypress.io/guides/guides/environment-variables.html#Option-4-env) suggests I can just separate the environment variables with a comma, but only the first variable is loaded.

### Steps to reproduce: (app code and test code)

./test.spec.js
```
context("test", () => {
  specify("valid username from environment variable", () => {
    let validUsername = Cypress.env("USERNAME");
    expect(validUsername, "username was set").to.be.a("string").and.not.be      .empty;
  });
  specify("valid password from environment variable", () => {
    let validPassword = Cypress.env("PASSWORD");
    expect(validPassword, "password was set").to.be.a("string").and.not.be.empty;
  });
});
```

CLI command (from Powershell)
[CD to installed cypress directory]
```
./node_modules/.bin/cypress run --env "CYPRESS_USERNAME=user","CYPRESS_PASSWORD=pass"
```

#### Results
```
 Running:  test.spec.js                                                                    (1 of 1)


  test
    √ valid username from environment variable
    1) valid password from environment variable


  1 passing (438ms)
  1 failing

  1) test
       valid password from environment variable:
     AssertionError: password was set: expected undefined to be a string
      at Context.runnable.fn (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:101081:20)
      at callFn (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:30931:21)
      at https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:104009:28
      at PassThroughHandlerContext.finallyHandler (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:135962:23)
      at PassThroughHandlerContext.tryCatcher (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:139407:23)
      at Promise._settlePromiseFromHandler (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137343:31)
      at Promise._settlePromise (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137400:18)
      at Promise._settlePromise0 (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137445:10)
      at Promise._settlePromises (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137524:18)
      at Promise._fulfill (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137469:18)
      at Promise._settlePromise (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137413:21)
      at Promise._settlePromise0 (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137445:10)
      at Promise._settlePromises (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137524:18)
      at Promise._fulfill (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137469:18)
      at Promise._resolveCallback (https://esp.awstest.gasops.co.uk/__cypress/runner/cypress_runner.js:137263:57)
```

### Versions

 Cypress:    3.7.0
Browser:    Electron 73 (headless)
OS: Windows 10 (Powershell)

**Comment by bahmutov** [comment]
Please read our https://on.cypress.io/environment-variables guide, you are setting them with wrong names.

```
./node_modules/.bin/cypress run --env "username=user,password=pass"
```
then from your code 
```js
Cypress.env('username')
Cypress.env('password')
```
or using environment variables
```
export CYPRESS_username=user
export CYPRESS_password=pass
./node_modules/.bin/cypress run
```
As another guide, read this blog post [Keep passwords secret in E2E tests](https://glebbahmutov.com/blog/keep-passwords-secret-in-e2e-tests/)

**Comment by RobertMartinGMSL** [comment]
@bahmutov Thanks for taking the time for the speedy respone, fixed the issue.

As a side note, I read both of those guides (very helpful!) but missed the `CYPRESS_` prefix not being required for the CLI tool command.  Might suggest updating [here](https://docs.cypress.io/guides/guides/environment-variables.html#Option-4-env) in the yellow "hint" section to not include the `CYPRESS_` prefix for the CLI tool only.  Might have saved an issue and some time 😄 

Thanks again, really do appreciate the work you guys are doing!

**Comment by RobertMartinGMSL** [comment]
Also note that seems to be case sensitive

`./node_modules/.bin/cypress run --env "USERNAME=user","PASSWORD=pass"`

For anybody reading this in the future and using window environment 👍
