### ISSUE TITLE
RangeError crash on opening Cypress Electron app inside project

### ISSUE THREAD

**Issue by taniotanio7** [cypress-io/cypress#5936]
### Current behavior:
Cypress crashes in projects, that it was installed as dev-dependency. It happens when running `cypress open` command using npm / yarn scripts inside any project.
 
However, it works normally with `--global` flag or running `cypress open` command from globally installed npm package (not as npm scripts). I also tried running the command with `sudo`, but to no success.

For the record, the error persists also in the cypress-test-tiny repo

Stack trace:
```
RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:213:11)
    at exceptionWithHostPort (internal/errors.js:458:21)
    at internalConnect (net.js:840:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:19)
    at net.js:931:9
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:213:11)
    at exceptionWithHostPort (internal/errors.js:458:21)
    at internalConnect (net.js:840:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:19)
    at net.js:931:9
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:213:11)
    at exceptionWithHostPort (internal/errors.js:458:21)
    at internalConnect (net.js:840:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:19)
    at net.js:931:9
    at processTicksAndRejections (internal/process/task_queues.js:79:9)

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174
    at Object.getSystemErrorName (util.js:213:11)
    at exceptionWithHostPort (internal/errors.js:458:21)
    at internalConnect (net.js:840:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:288:19)
    at net.js:931:9
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

[Full stack trace with `DEBUG=cypress:*`](https://hastebin.com/tagivujuzu.coffeescript)

### Desired behavior:

Opening normally...

### Steps to reproduce: (app code and test code)

1. Install Cypress as dev dependency with npm / yarn
> Note: it doesn't download Cypress binaries in this step, as shown on the [documentation page](https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install)
![Recording from installing Cypress as yarn dev-dependency](https://user-images.githubusercontent.com/4144459/70667197-8f0b0380-1c70-11ea-9b95-74005009ffe3.gif)
2. Download Cypress binaries (`cypress install`)
3. Create new command in the `package.json` that uses `cypress open`
4. Use the newly created command
> Recording of the error: https://dsh.re/45a2ee
> Normally working by using global installation: https://dsh.re/86f8d

### Versions
Cypress: 3.7.0
OS: macOS 10.15.1 (19B77a)
Browser: Chrome / Canary (both failing)

**Comment by taniotanio7** [comment]
This might be related to #5658. Although the author had the problems after upgrading, I had made a fresh install. He also didn't mention running the command successfully with the global install.

By the way, I'm also new to the project 😊

**Comment by jennifer-shehane** [comment]
This is an error thrown from Node, specifically here: https://coverage.nodejs.org/coverage-1ecc406b77ba7573/lib/internal/errors.js.html#L1091

- Did you try this with npm?
- What versions of Node / yarn are you using?
- Are you behind some sort of firewall / corporate proxy?

**Comment by taniotanio7** [comment]
I've used [Volta](https://volta.sh/) for my node version management but noticed it caused some problems with other globally installed packages as well.

So I've moved to nvm and everything works like charm both for npm and yarn.
I'm using latest LTS node version – v12.13.1 and newest Cypress 3.8.0
