### ISSUE TITLE
Cypress cannot reach address while using proxy

### ISSUE THREAD

**Issue by sergiomap** [cypress-io/cypress#5942]
After update from 3.4.1 to 3.7.0 Cypress cannot reach the base url while using a proxy. I also tried 3.5.0 and has the same behavior of 3.7.0.
If I don't connect to a proxy everything runs fine. 
 
Error:
```
Cypress could not verify that this server is running:

  > https://xxxxx.xx

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.
```

Debug:
```
cypress:server:ensure-url checking that baseUrl is available { baseUrl: 'https://xxxxx.xx',
  delaysRemaining: [],
  retryIntervals: [ 3000, 3000, 4000 ] } +4s
  cypress:network:agent addRequest called { isHttps: true, href: 'https://xxxxx.xx/' } +4s
  cypress:network:agent got family { family: undefined, href: 'https://xxxxx.xx/' } +0ms
  cypress:network:agent Creating proxied socket for https://xxxxx.xx/ through http://192.168.10.1:8080 +1ms
  cypress:network:connect successfully connected { opts: { port: 8080, host: '192.168.10.1', useTls: false, getDelayMsForRetry: [Function] }, iteration: 0 } +4s
  cypress:network:agent Proxy socket for https://xxxxx.xx/ established +151ms
  cypress:server:server RequestError: Error: Parse Error
  cypress:server:server     at new RequestError (/Users/sergiopinheiro/Library/Caches/Cypress/3.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:14:15)
  cypress:server:server     at Request.plumbing.callback (/Users/sergiopinheiro/Library/Caches/Cypress/3.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:87:29)
  cypress:server:server     at Request.RP$callback [as _callback] (/Users/sergiopinheiro/Library/Caches/Cypress/3.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
  cypress:server:server     at self.callback (/Users/sergiopinheiro/Library/Caches/Cypress/3.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)
  cypress:server:server     at Request.emit (events.js:194:13)
  cypress:server:server     at Request.onRequestError (/Users/sergiopinheiro/Library/Caches/Cypress/3.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:877:8)
  cypress:server:server     at ClientRequest.emit (events.js:194:13)
  cypress:server:server     at TLSSocket.socketOnData (_http_client.js:457:9)
  cypress:server:server     at TLSSocket.emit (events.js:194:13)
  cypress:server:server     at addChunk (_stream_readable.js:296:12)
  cypress:server:server     at readableAddChunk (_stream_readable.js:277:11)
  cypress:server:server     at TLSSocket.Readable.push (_stream_readable.js:232:10)
  cypress:server:server     at TLSWrap.onStreamRead (internal/stream_base_commons.js:165:17)
  cypress:server:server  +11s
  cypress:server:server Setting remoteAuth undefined +1ms
  cypress:server:cors Parsed URL { port: '443', tld: 'xx', domain: 'xxxxx' } +0ms
  cypress:server:server Setting remoteOrigin https://xxxxx.xx +2ms
  cypress:server:server Setting remoteHostAndPort { port: '443', tld: 'qa', domain: 'xxxxx' } +0ms
  cypress:server:server Setting remoteDocDomain xxxxx.xx +0ms
  cypress:server:server Getting remote state: { auth: undefined, props: { port: '443', tld: 'qa', domain: 'xxxxx' }, origin: 'https://xxxxx.xx', strategy: 'http', visiting: undefined, domainName: 'xxxxx.xx', fileServer: null } +0ms
  cypress:server:cypress exiting with err { Error: Cypress failed to verify that your server is running.
```

**Comment by jennifer-shehane** [comment]
Could you update to the [current version of Cypress](https://on.cypress.io/changelog) and let me know if this is still happening for you? Your issue may have already been fixed. 

Could you also explain the proxy settings you have set up for your and give an idea of what the domain looks like?

**Comment by sergiomap** [comment]
Still not working with new version.

I found a workaround. If I run it using `NODE_OPTIONS=--max-http-header-size=1000000` before `cypress run` it works.

Can this help you fixing the issue?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
