### ISSUE TITLE
Cypress tests for cross-origin iframes fails on CI, but works locally

### ISSUE THREAD

**Issue by SupratikRulz** [cypress-io/cypress#6015]
I am trying to test **Plaid** bank linking process, I am able to get it test locally but the test fails in Gitlab CI. I have already added `"chromeWebSecurity": false` to `cypress.json` but it does not seem to work

### Steps to reproduce:

```js
cy.get('[testid="link-banks--link-bank-button"]')
  .click()
  .wait(10000)

cy.get('iframe')
    .then($iframe => {
      const $body = $iframe.contents().find('body')
      cy.wrap($body)
        .find('button')
        .first()
        .click({force: true})
    })
```

This opens the `iframe` when I test it out locally but it fails to display the iframe when run in Gitlab CI.

Following error is displayed in CI:
```
492      CypressError: Timed out retrying: Expected to find element: 'button', but never found it. Queried from element: <body>
493       at Object.cypressErr (http://localhost:5001/__cypress/runner/cypress_runner.js:104968:11)
494       at Object.throwErr (http://localhost:5001/__cypress/runner/cypress_runner.js:104923:18)
495       at Object.throwErrByPath (http://localhost:5001/__cypress/runner/cypress_runner.js:104955:17)
496       at retry (http://localhost:5001/__cypress/runner/cypress_runner.js:96290:16)
497       at onFailFn (http://localhost:5001/__cypress/runner/cypress_runner.js:85359:16)
498       at tryCatcher (http://localhost:5001/__cypress/runner/cypress_runner.js:139045:23)
499       at Promise._settlePromiseFromHandler (http://localhost:5001/__cypress/runner/cypress_runner.js:136981:31)
500       at Promise._settlePromise (http://localhost:5001/__cypress/runner/cypress_runner.js:137038:18)
501       at Promise._settlePromise0 (http://localhost:5001/__cypress/runner/cypress_runner.js:137083:10)
502       at Promise._settlePromises (http://localhost:5001/__cypress/runner/cypress_runner.js:137158:18)
503       at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:5001/__cypress/runner/cypress_runner.js:133770:16)
504       at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:5001/__cypress/runner/cypress_runner.js:133780:10)
505       at Async.drainQueues (http://localhost:5001/__cypress/runner/cypress_runner.js:133654:14)
```

### Versions
cypress: 3.6.1
browser: chrome69

**Comment by SupratikRulz** [comment]
Even tried the solution mentioned [here](https://github.com/cypress-io/cypress/issues/1763#issuecomment-394492373) which seems to work for many. But didn't worked for me

**Comment by jennifer-shehane** [comment]
We would need an HTML provided to run the test code against in order to recreate this issue.

Unfortunately we'll have to close this issue without this. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with the HTML code to run the failing tests against and we will reopen the issue. 🙏
