### ISSUE TITLE
Cypress verification fails randomly during Docker CI

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#6082]
Making a new post as requested here: https://github.com/cypress-io/cypress/issues/4624#issuecomment-570129903

We are running Cypress 3.7.0 and we see this problem (failed verification) periodically. We run Cypress in Docker containers as part of our CI and sometimes they may be underpowered, as has been noted in other issues. Unfortunately the logs don't really provide any color here:

```
15:51:06  [23:51:01]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.7.0/Cypress [started]
15:51:38  [23:51:35]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.7.0/Cypress [failed]
```

It would appear that 30 seconds is sometimes just not enough time. Is there some way we can set this timeout in our Cypress config? Or a way we can disable this test altogether? Either of these would be much more preferable than Cypress failing, which wastes a lot of our time because our tasks have to be restarted.

**Comment by kaiyoma** [comment]
Here's the entire relevant portion of the log when this failure occurs:

```
08:57:37  It looks like this is your first time using Cypress: 3.7.0
08:57:37  
08:57:37  [16:57:24]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.7.0/Cypress [started]
08:58:00  [16:57:57]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.7.0/Cypress [failed]
08:58:00  Cypress verification timed out.
08:58:00  
08:58:00  This command failed with the following output:
08:58:00  
08:58:00  /home/jenkins/.cache/Cypress/3.7.0/Cypress/Cypress --no-sandbox --smoke-test --ping=835
08:58:00  
08:58:00  ----------
08:58:00  
08:58:00  Command failed: /home/jenkins/.cache/Cypress/3.7.0/Cypress/Cypress --no-sandbox --smoke-test --ping=835
08:58:00  
08:58:00  ----------
08:58:00  
08:58:00  Platform: linux (Debian - 9.9)
08:58:00  Cypress Version: 3.7.0
```

**Comment by jennifer-shehane** [comment]
@kaiyoma Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here? Something like `DEBUG=cypress* cypress verify`

**Comment by kaiyoma** [comment]
Sure thing, I'll add this to our CI automation and get back to you when the next failure occurs.

**Comment by lmiller1990** [comment]
I get this all the time. I'm yet to be able to run on our CI (Jenkins). Logs:

```
+ DEBUG=cypress:* CYPRESS_CACHE_FOLDER=. CYPRESS_RUN_BINARY=./3.8.0/Cypress/Cypress yarn cypress verify
yarn run v1.21.1
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-112".
$ /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/node_modules/.bin/cypress verify
warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
2020-01-06T05:43:07.994Z cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/node_modules/.bin/cypress","verify"]
2020-01-06T05:43:07.997Z cypress:cli NODE_OPTIONS is not set
2020-01-06T05:43:07.998Z cypress:cli:cli program parsing arguments
2020-01-06T05:43:08.002Z cypress:cli parsed cli options {}
2020-01-06T05:43:08.053Z cypress:cli verifying Cypress app
2020-01-06T05:43:08.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2020-01-06T05:43:08.054Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2020-01-06T05:43:08.054Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER .
2020-01-06T05:43:08.055Z cypress:cli checking environment variables
2020-01-06T05:43:08.055Z cypress:cli Using CYPRESS_RUN_BINARY from environment variable
2020-01-06T05:43:08.055Z cypress:cli Using CYPRESS_RUN_BINARY from environment variable
2020-01-06T05:43:08.056Z cypress:cli CYPRESS_RUN_BINARY exists, = ./3.8.0/Cypress/Cypress
Note: You have set the environment variable:

CYPRESS_RUN_BINARY=./3.8.0/Cypress/Cypress

This overrides the default Cypress binary path used.

2020-01-06T05:43:08.065Z cypress:cli CYPRESS_RUN_BINARY is executable? : true
2020-01-06T05:43:08.072Z cypress:cli CYPRESS_RUN_BINARY has realpath: /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress/Cypress
2020-01-06T05:43:08.072Z cypress:cli CYPRESS_RUN_BINARY has binaryDir: /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress
2020-01-06T05:43:08.073Z cypress:cli checking if executable exists /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress/Cypress
2020-01-06T05:43:08.073Z cypress:cli Binary is executable? : true
2020-01-06T05:43:08.073Z cypress:cli binaryDir is  /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress
2020-01-06T05:43:08.074Z cypress:cli Reading binary package.json from: /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress/resources/app/package.json
2020-01-06T05:43:08.077Z cypress:cli Found binary version 3.8.0 installed in: /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress
2020-01-06T05:43:08.079Z cypress:cli could not read binary_state.json file
2020-01-06T05:43:08.079Z cypress:cli {}
2020-01-06T05:43:08.079Z cypress:cli is Verified ? undefined
2020-01-06T05:43:08.079Z cypress:cli force verify
2020-01-06T05:43:08.079Z cypress:cli running binary verification check 3.8.0
It looks like this is your first time using Cypress: 3.8.0

[?25l[05:43:08]  Verifying Cypress can run /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress [started]
2020-01-06T05:43:08.086Z cypress:cli clearing out the verified version
2020-01-06T05:43:08.087Z cypress:cli undefined DISPLAY environment variable
2020-01-06T05:43:08.087Z cypress:cli Cypress will spawn its own Xvfb
2020-01-06T05:43:08.087Z cypress:cli needs Xvfb? true
2020-01-06T05:43:08.088Z cypress:cli Starting Xvfb
2020-01-06T05:43:08.110Z cypress:cli disabling Electron sandbox
2020-01-06T05:43:08.110Z cypress:cli running smoke test
2020-01-06T05:43:08.110Z cypress:cli using Cypress executable /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress/Cypress
2020-01-06T05:43:08.110Z cypress:cli smoke test command: /var/lib/jenkins/workspace/DoseMe_cypress_master/cypress/3.8.0/Cypress/Cypress --no-sandbox --smoke-test --ping=85
2020-01-06T05:43:08.110Z cypress:cli smoke test timeout 30000 ms
```

I am using a locally cached and installed Cypress as you can see from the ENV variables. Not sure why It just hangs... it hangs for ever, until I cancel it (10+ min).

**Comment by dvngnt** [comment]
I'm getting a similar issue. I think a good new feature would be to pass an argument to skip the verification step until it is more reliable since this is breaking multiple people's builds. 

Since I'm using docker I would expect Cypress to work provided that the docker engine in installed. 

```
> e2e_tests@1.0.0 ci:staging /e2eTests
> npx cypress run --env configFile=staging

[15:09:25]  Verifying Cypress can run /root/.cache/Cypress/3.8.1/Cypress [started]
[15:10:00]  Verifying Cypress can run /root/.cache/Cypress/3.8.1/Cypress [failed]
[15:10:00] → Cypress verification timed out.

This command failed with the following output:

/root/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=693

----------
```

**Comment by kaiyoma** [comment]
@jennifer-shehane Sorry for the delay, but we finally got debug logs for the verification failure.

```
[2020-01-14T19:29:17.233Z] 2020-01-14T19:29:15.495Z cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/home/jenkins/workspace/geiger-merge/node_modules/.bin/cypress","verify"]
[2020-01-14T19:29:17.233Z] 2020-01-14T19:29:15.499Z cypress:cli NODE_OPTIONS is not set
[2020-01-14T19:29:17.233Z] 2020-01-14T19:29:15.499Z cypress:cli:cli program parsing arguments
[2020-01-14T19:29:17.233Z] 2020-01-14T19:29:15.504Z cypress:cli parsed cli options {}
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.619Z cypress:cli verifying Cypress app
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.621Z cypress:cli checking environment variables
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.628Z cypress:cli checking if executable exists /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.641Z cypress:cli Binary is executable? : true
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.642Z cypress:cli binaryDir is  /home/jenkins/.cache/Cypress/3.8.1/Cypress
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.643Z cypress:cli Reading binary package.json from: /home/jenkins/.cache/Cypress/3.8.1/Cypress/resources/app/package.json
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.735Z cypress:cli Found binary version 3.8.1 installed in: /home/jenkins/.cache/Cypress/3.8.1/Cypress
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.738Z cypress:cli could not read binary_state.json file
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.738Z cypress:cli {}
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.739Z cypress:cli is Verified ? undefined
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.739Z cypress:cli force verify
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.739Z cypress:cli running binary verification check 3.8.1
[2020-01-14T19:29:27.233Z] It looks like this is your first time using Cypress: 3.8.1
[2020-01-14T19:29:27.233Z] 
[2020-01-14T19:29:27.233Z] [19:29:25]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.8.1/Cypress [started]
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.756Z cypress:cli clearing out the verified version
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.760Z cypress:cli DISPLAY environment variable is set to :99 on Linux
[2020-01-14T19:29:27.233Z] Assuming this DISPLAY points at working X11 server,
[2020-01-14T19:29:27.233Z] Cypress will not spawn own Xvfb
[2020-01-14T19:29:27.233Z] 
[2020-01-14T19:29:27.233Z] NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
[2020-01-14T19:29:27.233Z]   see https://github.com/cypress-io/cypress/issues/4034
[2020-01-14T19:29:27.233Z] Solution: Unset the DISPLAY variable and try again:
[2020-01-14T19:29:27.233Z]   DISPLAY= npx cypress run ...
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.760Z cypress:cli needs Xvfb? false
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.760Z cypress:cli spawning, should retry on display problem? true
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.761Z cypress:cli disabling Electron sandbox
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.761Z cypress:cli running smoke test
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.761Z cypress:cli using Cypress executable /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.761Z cypress:cli smoke test command: /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126
[2020-01-14T19:29:27.233Z] 2020-01-14T19:29:25.761Z cypress:cli smoke test timeout 30000 ms
[2020-01-14T19:30:05.972Z] 2020-01-14T19:29:59.105Z cypress:cli Smoke test failed: { Error: Command failed: /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126
[2020-01-14T19:30:05.972Z] [743:0100/000000.093378:ERROR:zygote_linux.cc(653)] write: Broken pipe (32)
[2020-01-14T19:30:05.972Z] 
[2020-01-14T19:30:05.972Z] 
[2020-01-14T19:30:05.972Z]     at makeError (/home/jenkins/workspace/geiger-merge/node_modules/cypress/node_modules/execa/index.js:172:9)
[2020-01-14T19:30:05.972Z]     at Promise.all.then.arr (/home/jenkins/workspace/geiger-merge/node_modules/cypress/node_modules/execa/index.js:277:16)
[2020-01-14T19:30:05.972Z]     at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-01-14T19:30:05.972Z]   code: null,
[2020-01-14T19:30:05.972Z]   stdout: '',
[2020-01-14T19:30:05.972Z]   stderr:
[2020-01-14T19:30:05.972Z]    '[743:0100/000000.093378:ERROR:zygote_linux.cc(653)] write: Broken pipe (32)\n',
[2020-01-14T19:30:05.972Z]   failed: true,
[2020-01-14T19:30:05.972Z]   signal: 'SIGTERM',
[2020-01-14T19:30:05.972Z]   cmd:
[2020-01-14T19:30:05.972Z]    '/home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126',
[2020-01-14T19:30:05.972Z]   timedOut: true,
[2020-01-14T19:30:05.972Z]   killed: true }
[2020-01-14T19:30:05.972Z] 2020-01-14T19:29:59.670Z cypress:cli error message: [743:0100/000000.093378:ERROR:zygote_linux.cc(653)] write: Broken pipe (32)
[2020-01-14T19:30:05.972Z] 
[2020-01-14T19:30:05.972Z] 2020-01-14T19:29:59.671Z cypress:cli error timedOut is true
[2020-01-14T19:30:06.541Z] [19:30:06]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.8.1/Cypress [failed]
[2020-01-14T19:30:06.541Z] Cypress verification timed out.
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] This command failed with the following output:
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] ----------
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] [743:0100/000000.093378:ERROR:zygote_linux.cc(653)] write: Broken pipe (32)
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] ----------
[2020-01-14T19:30:06.541Z] 
[2020-01-14T19:30:06.541Z] Platform: linux (Debian - 9.9)
[2020-01-14T19:30:06.541Z] Cypress Version: 3.8.1
[2020-01-14T19:30:07.926Z] It looks like this is your first time using Cypress: 3.8.1
[2020-01-14T19:30:07.926Z] 
[2020-01-14T19:30:07.926Z] [19:30:07]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.8.1/Cypress [started]
[2020-01-14T19:30:40.005Z] [19:30:38]  Verifying Cypress can run /home/jenkins/.cache/Cypress/3.8.1/Cypress [failed]
[2020-01-14T19:30:40.005Z] Cypress verification timed out.
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] This command failed with the following output:
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=395
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] ----------
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] Command failed: /home/jenkins/.cache/Cypress/3.8.1/Cypress/Cypress --no-sandbox --smoke-test --ping=395
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] ----------
[2020-01-14T19:30:40.005Z] 
[2020-01-14T19:30:40.005Z] Platform: linux (Debian - 9.9)
[2020-01-14T19:30:40.005Z] Cypress Version: 3.8.1
```

**Comment by dominicroessner** [comment]
We've been seeing the same issue with Cypress 4.0.0 (and earlier versions before we upgraded) which causes CI builds to fail randomly. Subscribing for updates.

**Comment by Sebosek** [comment]
Same here, Cypress **3.8.3** running docker image `cypress/browsers:node10.16.3-chrome80-ff73` in Gitlab CI

**Comment by Tuman829** [comment]
Any progress on this?

**Comment by shiba24** [comment]
Getting the same issue. My workaround was to use `cypress:base` and install cypress every time.
I'm using Jenkins. The below is my Jenkinsfile (in declarative format).

Before (resulting in the timeout error):

```
# Jenkinsfile
    agent {
        dockerfile {
            filename 'Dockerfile'
        }
    }

    stage("mystage") {
        steps {
            sh 'cypress verify'
            sh 'cypress run'
        }
    }


# Dockerfile
FROM cypress/included:5.5.0
# Chmod for cache directory permission
RUN chmod -R 777 /root/.cache/Cypress

# ..other process...
```


After (work around):
```
# Jenkinsfile
    agent {
        docker {
            image 'cypress/base:14'.  // directly pulling the base image
        }
    }

    stage("mystage") {
        steps {
            sh 'npm ci'
            sh 'npm run cy:run'
        }
    }

# Not using my Dockerfile
```

The reason why I use `cypress/base` and install cypress separately is because of the permission issue reported in https://github.com/cypress-io/cypress/issues/1281 .

My guess is something around cache is the cause of the random error / timeout. I stopped the further investigation, but hope this helps you to fix this soon.

Thank you for this great product!

**Comment by kaiyoma** [comment]
Any updates here? We still see this all the time in our CI and it's a pretty big waste of our time, because it causes the build to fail and we have to restart from the beginning. If we could increase this timeout by just a few minutes, it could easily save us hours of wasted time every day. What's the opposition from Cypress for letting users increase the timeout? Just make it an advanced setting that most people will never touch.

**Comment by kaiyoma** [comment]
It seems that Cypress 6 prints out more information now when this happens. Not sure if this is helpful at all, but here's the console output when verification times out:

```
16:03:55  This command failed with the following output:
16:03:55  
16:03:55  /home/jenkins/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=781
16:03:55  
16:03:55  ----------
16:03:55  
16:03:55  Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
16:03:55  2020-12-04T00:03:28.284Z cypress:ts Running without ts-node hook in environment "production"
16:03:55  2020-12-04T00:03:35.619Z cypress:server:appdata path: /home/jenkins/.config/Cypress/cy/production/browsers
16:03:55  2020-12-04T00:03:35.672Z cypress:server:util:node_options NODE_OPTIONS check failed, forking { NODE_OPTIONS: '--max-http-header-size=1048576 ', ORIGINAL_NODE_OPTIONS: '' }
16:03:55  Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
16:03:55  2020-12-04T00:03:37.563Z cypress:ts Running without ts-node hook in environment "production"
16:03:55  2020-12-04T00:03:38.641Z cypress:server:appdata path: /home/jenkins/.config/Cypress/cy/production/browsers
16:03:55  2020-12-04T00:03:38.647Z cypress:server:util:node_options NODE_OPTIONS check passed, not forking { NODE_OPTIONS: '--max-http-header-size=1048576 ' }
16:03:55  2020-12-04T00:03:38.647Z cypress:server:util:node_options restoring NODE_OPTIONS { NODE_OPTIONS: '--max-http-header-size=1048576 ', ORIGINAL_NODE_OPTIONS: '' }
16:03:55  [656:1204/000340.118270:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
16:03:55  2020-12-04T00:03:41.896Z cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
16:03:55  ┌─────────┬───────────────────┬──────────────┬─────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
16:03:55  │ (index) │       group       │ processCount │      pids       │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
16:03:55  ├─────────┼───────────────────┼──────────────┼─────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
16:03:55  │    0    │     'cypress'     │      1       │      '656'      │     0      │       0        │  97.83   │    97.83     │    97.83    │
16:03:55  │    1    │ 'electron-shared' │      2       │   '662, 665'    │     0      │       0        │  83.66   │    83.66     │    83.66    │
16:03:55  │    2    │      'other'      │      3       │ '682, 683, 684' │     0      │       0        │   6.13   │     6.13     │    6.13     │
16:03:55  │    3    │      'TOTAL'      │      6       │       '-'       │     0      │       0        │  187.61  │    187.61    │   187.61    │
16:03:55  └─────────┴───────────────────┴──────────────┴─────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘
16:03:55  [710:1204/000343.596013:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
16:03:55  [710:1204/000343.596243:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: GLX is not present.
16:03:55  [710:1204/000343.596311:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
16:03:55  [710:1204/000343.596459:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: GLX is not present.
16:03:55  [710:1204/000343.596532:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: GLX is not present.
16:03:55  [710:1204/000343.596583:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
16:03:55  [710:1204/000343.596639:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
16:03:55  [710:1204/000343.936252:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
16:03:55  
16:03:55  ----------
16:03:55  
16:03:55  Platform: linux (Debian - 9.13)
16:03:55  Cypress Version: 6.0.1
```

**Comment by bahmutov** [comment]
Seems from the last messages some kind of OS error preventing Electron from running.

**Comment by kaiyoma** [comment]
At the risk of overloading this issue with too much, there's another issue we see occasionally in our CI, which you just reminded me of. Sometimes Cypress reports that the specified browser is invalid, even though it's completely valid and the browser is installed.

Here's what that looks like:

```
12:01:02  Can't run because you've entered an invalid browser name.
12:01:02  
12:01:02  Browser: 'chrome' was not found on your system or is not supported by Cypress.
12:01:02  
12:01:02  Cypress supports the following browsers:
12:01:02  - chrome
12:01:02  - chromium
12:01:02  - edge
12:01:02  - electron
12:01:02  - firefox
12:01:02  
12:01:02  You can also use a custom browser: https://on.cypress.io/customize-browsers
12:01:02  
12:01:02  Available browsers found on your system are:
12:01:02  - electron
```

The bizarre thing is that the test run just before this worked fine and so did the test run afterwards. Possibly related to the verification timeout?

**Comment by kaiyoma** [comment]
Any ideas from Cypress folks? We see this problem a lot every day and it's a big waste of our time. No one's chimed in with any debugging steps or workarounds.

**Comment by piyush290884** [comment]
HI @jennifer-shehane  @bahmutov 

Could you please help me with the following, i am getting the following error while opening cypress runner with ver 5.0.0 or 6.4.0



Below are the detailed log of the error I am getting

[Cypress-Error.txt](https://github.com/cypress-io/cypress/files/5946748/Cypress-Error.txt)
Your help is really appreciated as I have uninstalled and installed Cypress 5-7 times but still the same issue.

Thanks
Piyush

**Comment by kaiyoma** [comment]
For others running into this problem, I have a workaround suggestion that has helped us: instead of letting Cypress run the verification on its own (when it's started for the first time), run it yourself in a loop, before you run your tests. For instance, this is what we have in our test runner shell script:

```
  for i in $(seq 5)
  do
    yarn cypress verify &> cypress-verify.log

    if [[ $? -eq 0 ]]
    then
      break
    elif [[ $i -eq 5 ]]
    then
      echo
      cat cypress-verify.log
      echo
      error "Cypress verification failed."
      exit 1
    fi
  done
```

This still isn't perfect, as we still run into verification problems occasionally, but the number of CI failures has gone way down.

**Comment by ChapDDR** [comment]
> It seems that Cypress 6 prints out more information now when this happens. Not sure if this is helpful at all, but here's the console output when verification times out:
>....

I am encountering a similar error with my own docker image (fedora 30), see the following error log:
```
/var/project/.cache/Cypress/5.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=91

----------

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Path must be absolute
at App.l._setDefaultAppPaths (electron/js2c/browser_init.js:5:1450)
at Object.<anonymous> (electron/js2c/browser_init.js:185:2469)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3698)
at __webpack_require__ (electron/js2c/browser_init.js:1:128)
at electron/js2c/browser_init.js:1:1200
at electron/js2c/browser_init.js:1:1267
at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:279:7)
at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10)
at loadNativeModule (internal/modules/cjs/helpers.js:26:9)
at Module._load (internal/modules/cjs/loader.js:852:15)
[416:0208/141628.414103:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[440:0208/141628.435807:ERROR:angle_platform_impl.cc(43)] initialize(795): ANGLE Display::initialize error 12289: GLX is not present.
[440:0208/141628.435967:ERROR:gl_surface_egl.cc(741)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[440:0208/141628.436048:ERROR:gl_surface_egl.cc(1247)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[440:0208/141628.436222:ERROR:angle_platform_impl.cc(43)] initialize(795): ANGLE Display::initialize error 12289: GLX is not present.
[440:0208/141628.436324:ERROR:gl_surface_egl.cc(741)] EGL Driver message (Critical) eglInitialize: GLX is not present.
[440:0208/141628.436401:ERROR:gl_surface_egl.cc(1247)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[440:0208/141628.436472:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
[440:0208/141628.438443:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization

----------

Platform: linux (Fedora - 30)
Cypress Version: 5.6.0
```
The cause might be different though, so feel free to correct me if this is not related!

**Comment by TheBokiya** [comment]
In v6.5.0, I see that the timeout is set to 30000

`const VERIFY_TEST_RUNNER_TIMEOUT_MS = 30000;`

Even then it's not enough sometimes. We run verify in Gitlab CI and about 50% of the time it fails cause the server takes longer longer to verify. Really depends on the OS.

**Comment by kaiyoma** [comment]
Until we get a better solution from Cypress, I'll actually plug the workaround I had posted above: https://github.com/cypress-io/cypress/issues/6082#issuecomment-775456215

We used to see verification errors a lot and now they're really rare. In fact, I can't remember the last time I saw one. Running the verify yourself in a loop seems to be worth the small investment.

**Comment by maximenathan** [comment]
We had the same problem 90% of the time. Probably due to the CI runner _(network problem?)_
The trick was to change the timeout const in the CI script:

> sed -i 's/const VERIFY_TEST_RUNNER_TIMEOUT_MS.*;/const VERIFY_TEST_RUNNER_TIMEOUT_MS = 100000;/g' node_modules/cypress/lib/tasks/verify.js

> npx cypress verify

**Comment by lukeapage** [comment]
I combined the 2 scripts and wrote it in powershell - this is what we use

```
                    # https://github.com/cypress-io/cypress/issues/6082#issuecomment-861452454
                    ((Get-Content -path node_modules/cypress/lib/tasks/verify.js -Raw) -replace 'const VERIFY_TEST_RUNNER_TIMEOUT_MS = 30000;','const VERIFY_TEST_RUNNER_TIMEOUT_MS = 100000;') | Set-Content -Path node_modules/cypress/lib/tasks/verify.js

                    $maxRetries = 3;
                    $tries = 0;
                    while($tries -lt $maxRetries){
                        $tries++
                        $ErrorActionPreference = 'SilentlyContinue'
                        Measure-Command { yarn cypress verify }
                        if (-not $?) {
                          Write-Error "Failed $tries times"
                          Write-Error $_;
                          $ErrorActionPreference = 'Stop'
                          if($tries -eq $maxRetries){
                            exit 1;
                          }
                          yarn cypress install -f
                        } else{
                          break;
                        }
                    }
```

**Comment by donegjookim** [comment]
[Solution](https://stackoverflow.com/a/70867864)

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please open a new issue if you're encountering similar behavior in a newer version of Cypress.
