### ISSUE TITLE
`cy.visit()` Error - DOM Element `id` Attribute Set to `jquery`

### ISSUE THREAD

**Issue by kenchandev** [cypress-io/cypress#6193]
### Current behavior:

Given a static webpage with zero JavaScript present (no jQuery library), if there exists a DOM element with an `id` attribute set to `jquery` (for example, `<p id="jquery">jQuery</p>`), then the `cy.visit()` method throws a TypeError: `TypeError: item.first is not a function.`

![](https://www.dl.dropboxusercontent.com/s/9wkqletdgr30zsb/Screenshot%202020-01-18%2002.31.52.png)

Debug Logs:
```
cypress_runner.js:159529 TypeError: item.first is not a function

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'homepage'
    at Object.unwrapFirst (http://localhost:5000/__cypress/runner/cypress_runner.js:86108:19)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:80941:33
From previous event:
    at runCommand (http://localhost:5000/__cypress/runner/cypress_runner.js:80933:8)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:81014:14)
From previous event:
    at http://localhost:5000/__cypress/runner/cypress_runner.js:81055:37
From previous event:
    at run (http://localhost:5000/__cypress/runner/cypress_runner.js:81048:19)
    at Object.cy.<computed> [as visit] (http://localhost:5000/__cypress/runner/cypress_runner.js:81457:11)
    at Context.runnable.fn (http://localhost:5000/__cypress/runner/cypress_runner.js:81699:24)
    at callFn (http://localhost:5000/__cypress/runner/cypress_runner.js:30929:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:30922:7)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:84876:28
From previous event:
    at Object.onRunnableRun (http://localhost:5000/__cypress/runner/cypress_runner.js:84864:20)
    at $Cypress.action (http://localhost:5000/__cypress/runner/cypress_runner.js:78026:61)
    at Hook.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:83558:13)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:31272:10)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:31294:5
    at timeslice (http://localhost:5000/__cypress/runner/cypress_runner.js:26362:27)
logError @ cypress_runner.js:159529
```

Added a breakpoint to view the object that's considered a "jQuery object:"

![](https://www.dl.dropboxusercontent.com/s/skb4otgx99ceuj5/Screenshot%202020-01-18%2002.40.12.png)

### Desired behavior:

In a previous issue, this type of error was thrown when an older version of jQuery was found on the webpage being tested: https://github.com/cypress-io/cypress/issues/2927. According to the issue thread, it was resolved in Cypress v3.2.0. 

I'd expect that a webpage with zero JavaScript present shouldn't encounter this error.

### Test code to reproduce

https://github.com/kenchandev/cypress-bug-reduced-test-case

The `README.md` file will contain directions on how to quickly reproduce this bug.

### Versions

**Cypress**: v3.8.2
**Operating System**: Mac OS X
**Browser**: Cypress Test Runner's Default Browser

**Comment by jennifer-shehane** [comment]
This is very weird. Reproducible example below. 

`index.html`

```html
<!DOCTYPE html>
<body>
  <p id="jquery">jQuery</p>
</body>
</html>
```

`spec.js`

```js
it('should find the jQuery text', () => {
  cy.visit('index.html')
  cy.contains('jQuery').should('exist')
})
```

<img width="634" alt="Screen Shot 2020-01-22 at 1 37 52 PM" src="https://user-images.githubusercontent.com/1271364/72872901-d333fe00-3d1c-11ea-8470-174ac0c629c9.png">

## Code

This is being thrown from this line of code:

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/utils.coffee#L67

### With `id="jquery"`

<img width="1097" alt="Screen Shot 2020-01-22 at 1 44 15 PM" src="https://user-images.githubusercontent.com/1271364/72873157-7a189a00-3d1d-11ea-88d4-65f9051230cf.png">

### Without `id="jquery"`

<img width="1103" alt="Screen Shot 2020-01-22 at 1 44 48 PM" src="https://user-images.githubusercontent.com/1271364/72873166-7e44b780-3d1d-11ea-8f99-f1d687594e08.png">

**Comment by protyay** [comment]
Hello, @jennifer-shehane , can i work on this issue ?
