### ISSUE TITLE
Cypress / xvfb related segmentation fault

### ISSUE THREAD

**Issue by m4s9** [cypress-io/cypress#6235]
### Current behavior:

When running cypress tests, it fails to start.

Here is some commands and logs:

```
ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ rm node_modules/ ~/.cache/Cypress/ -rf

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ npm install

> cypress@3.8.2 postinstall /home/ubuntu/temp/mysoftware-e2e-testing/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 3.8.2)

 ✔  Downloaded Cypress
 ✔  Unzipped Cypress
 ✔  Finished Installation /home/ubuntu/.cache/Cypress/3.8.2

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

npm notice created a lockfile as package-lock.json. You should commit this file.
added 191 packages from 133 contributors and audited 317 packages in 63.857s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ node -v
v10.18.1

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ npm -v
6.13.4

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ ./node_modules/.bin/cypress run --spec cypress/integration/mysoftware.js
It looks like this is your first time using Cypress: 3.8.2

 ✖  Verifying Cypress can run /home/ubuntu/.cache/Cypress/3.8.2/Cypress
   → Cypress Version: 3.8.2
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: /home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=732

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.2

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ Xvfb :1 -screen 5 1024x768x8 &
[1] 14026

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ export DISPLAY=:1.5

ubuntu@my.hostname.dev:~/temp/mysoftware-e2e-testing$ gdb --args /home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=732
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/ubuntu/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=732
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8f14700 (LWP 14047)]
[New Thread 0x7fffe7ed3700 (LWP 14049)]
[New Thread 0x7fffe76d2700 (LWP 14050)]
[New Thread 0x7fffe6ed1700 (LWP 14051)]
[New Thread 0x7fffde9d1700 (LWP 14052)]
[New Thread 0x7fffde1d0700 (LWP 14053)]

Thread 1 "Cypress" received signal SIGSEGV, Segmentation fault.
0x00007fffe5d292dd in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
(gdb) bt
#0  0x00007fffe5d292dd in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#1  0x00007fffe5d2b145 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#2  0x00007fffe5d1df68 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#3  0x00007fffe5d195d4 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#4  0x00007fffe5d19a41 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#5  0x00007fffef6a8af9 in epoxy_glx_version () at /usr/lib/x86_64-linux-gnu/libepoxy.so.0
#6  0x00007ffff3a8eb3f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff3a8efaa in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff3a97b30 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007ffff3a94ca6 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#10 0x00007ffff3a84e3d in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#11 0x00007ffff3a59d5d in gdk_display_manager_open_display () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007ffff3f4969a in gtk_init_check () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff3f496c9 in gtk_init () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x000055555bf0d007 in  ()
#15 0x0000018e091b86c0 in  ()
#16 0x0000000500000000 in  ()
#17 0x0000000509142b40 in  ()
#18 0x0000018e0918c8c0 in  ()
#19 0x0000018e09142b40 in  ()
#20 0x0000018e091b81e0 in  ()
#21 0x0000018e0918ca28 in  ()
#22 0x0000000000000000 in  ()
```

### Desired behavior:

`cypress run` should run without a crash

### Test code to reproduce

I was running headless cypress tests on a AWS Ubuntu 18.04 server. See the steps above. This failure seems to require a server version (+xvfb), because tests run smoothly on my desktop ubuntu.

### Versions

 - Ubuntu 18.04
 - node v10.18.1
 - npm 6.13.4
 - cypress 3.8.2
 - This problem seemed to start when I ran `apt-get upgrade` and these mesa-related packages were upgraded:
   - libglapi-mesa:amd64 (19.0.8-0ubuntu0-18.04.3 -> 19.2.1-1ubuntu1-18.04.1)
   - libgl1-mesa-glx:amd64 (19.0.8-0ubuntu0-18.04.3 -> 19.2.1-1ubuntu1-18.04.1)
   - libglx-mesa0:amd64 (19.0.8-0ubuntu0-18.04.3 -> 19.2.1-1ubuntu1-18.04.1)

**Comment by jennifer-shehane** [comment]
Duplicate of #6184
