### ISSUE TITLE
cypress about to exit with code 39

### ISSUE THREAD

**Issue by maurocolella** [cypress-io/cypress#6240]
Not a question.

### Current behavior:

On a Manjaro host, kernel `5.4.13-3-MANJARO`
With `Docker version 19.03.5-ce, build 633a0ea838`
On multiple container types: Either from `cypress/base`, `cypress/browsers`, or from any node base > 12 with cypress dependencies added, after the test run and the test reports, I get the following output when running cypress with `DEBUG=cypress:*`

Based on the error, I presume cypress or the runtime somehow is trying to remove a non-empty directory. 

But I'd be hard-pressed to tell - which. The FE itself is a `create-react-app` with TypeScript. The tests run, some work and some fail, screenshots are recorded, etc.

I have tried to change reporters and a number of things (Electron, Chrome..) to no avail yet.

```
matching-frontend_1    | 2020-01-24T02:08:17.681Z cypress:server:cypress about to exit with code 39
matching-frontend_1    | 2020-01-24T02:08:17.704Z cypress:cli child event fired { event: 'exit', code: 39, signal: null }
matching-frontend_1    | 2020-01-24T02:08:17.705Z cypress:cli Stopping Xvfb
matching-frontend_1    | 2020-01-24T02:08:17.706Z cypress:cli child event fired { event: 'close', code: 39, signal: null }
matching-frontend_1    | npm ERR! code ELIFECYCLE
matching-frontend_1    | npm ERR! errno 39
matching-frontend_1    | npm ERR! my-app@0.1.0 test:e2e: `cypress run --browser chrome`
matching-frontend_1    | npm ERR! Exit status 39
matching-frontend_1    | npm ERR! 
matching-frontend_1    | npm ERR! Failed at the my-app@0.1.0 test:e2e script.
matching-frontend_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
matching-frontend_1    | 
matching-frontend_1    | npm ERR! A complete log of this run can be found in:
matching-frontend_1    | npm ERR!     /root/.npm/_logs/2020-01-24T02_08_17_760Z-debug.log
matching-frontend_1    | Error: Command failed with exit code 39 (ENOTEMPTY): npm run test:e2e
matching-frontend_1    |     at makeError (/usr/src/app/node_modules/start-server-and-test/node_modules/execa/lib/error.js:59:11)
matching-frontend_1    |     at handlePromise (/usr/src/app/node_modules/start-server-and-test/node_modules/execa/index.js:112:26)
matching-frontend_1    |     at processTicksAndRejections (internal/process/task_queues.js:89:5) {
```

### Desired behavior:

* No errors after the test report OR
* A message that lets me identify the file system object on which the operation is attempted (ie. probably a directory).

### Test code to reproduce

Test code is subject to NDA.

### Versions

Cypress 3.8.2 w/without instrumentation (`@cypress/instrument-cra`)
Docker 19.03.5 CE
Linux Manjaro (Arch) / Kernel 5.4.13
Multiple container types/bases. Most recently `node:13.5-stretch`
Babel and TypeScript.

**Comment by jennifer-shehane** [comment]
This error is being thrown from the `start-server-and-test` node module as can be seen from the stacktrace. 

```
Error: Command failed with exit code 39 (ENOTEMPTY): npm run test:e2e
  at makeError (/usr/src/app/node_modules/start-server-and-test/node_modules/execa/lib/error.js:59:11)
  at handlePromise (/usr/src/app/node_modules/start-server-and-test/node_modules/execa/index.js:112:26)
  at processTicksAndRejections (internal/process/task_queues.js:89:5) {
```

Also check the `/root/.npm/_logs/2020-01-24T02_08_17_760Z-debug.log` file for more info as explained in the error. This is not an issue with Cypress.

**Comment by maurocolella** [comment]
`start-server-and-test` does `npm start` and `cypress run` asynchronously in this case. 

The promise that fails from the stack trace is the promise that actually spawns `cypress`.

However: in my case, this might be an error with permissions between the container environment (docker/ci) and the host. I'll verify that.

**Comment by maurocolella** [comment]
Here is the verbose log.

I am not sure which change caused a change in error code, but currently, the error code reported is `41`. Behavior is the same. This has been consistent for the past couple of days.

The issue traces back to cypress `maybeClose`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test:e2e' ]
2 info using npm@6.10.2
3 info using node@v12.4.0
4 verbose run-script [ 'pretest:e2e', 'test:e2e', 'posttest:e2e' ]
5 info lifecycle my-app@0.1.0~pretest:e2e: my-app@0.1.0
6 info lifecycle my-app@0.1.0~test:e2e: my-app@0.1.0
7 verbose lifecycle my-app@0.1.0~test:e2e: unsafe-perm in lifecycle true
8 verbose lifecycle my-app@0.1.0~test:e2e: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle my-app@0.1.0~test:e2e: CWD: /usr/src/app
10 silly lifecycle my-app@0.1.0~test:e2e: Args: [ '-c', 'cypress run' ]
11 silly lifecycle my-app@0.1.0~test:e2e: Returned: code: 41  signal: null
12 info lifecycle my-app@0.1.0~test:e2e: Failed to exec test:e2e script
13 verbose stack Error: my-app@0.1.0 test:e2e: `cypress run`
13 verbose stack Exit status 41
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid my-app@0.1.0
15 verbose cwd /usr/src/app
16 verbose Linux 5.3.0-28-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:e2e"
18 verbose node v12.4.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 41
22 error my-app@0.1.0 test:e2e: `cypress run`
22 error Exit status 41
23 error Failed at the my-app@0.1.0 test:e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```
