### ISSUE TITLE
I'm facing this error without use any cy.screenshot() command in our project

### ISSUE THREAD

**Issue by jemishgopani** [cypress-io/cypress#6278]
```
CypressError: cy.screenshot() timed out waiting '60000ms' to complete.
      at Object.cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:86207:11)
      at Object.throwErr (http://localhost:8080/__cypress/runner/cypress_runner.js:86162:18)
      at Object.throwErrByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:86194:17)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:72611:21
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:120203:23)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:115344:41
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:120203:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:118139:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:118196:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:118241:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:118316:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:114928:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:114938:10)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:114812:14)
```

**Comment by jennifer-shehane** [comment]
A screenshot is automatically taken when a test fails, so you may see this error if it could not complete at that time. This behavior can be turned off by setting screenshotOnRunFailure to false in the [`Cypress.Screenshot.defaults()`](https://on.cypress.io/screenshot-api).

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

This issue will be closed as per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we will reopen the issue. 🙏
