### ISSUE TITLE
Cypress on Azure CI for a CRA app

### ISSUE THREAD

**Issue by aozora** [cypress-io/cypress#6395]
Hi! I have a React app scaffolded from Create-React-App with several Cypress 4.0.1 tests that run fine on localhost; I've setup an Azure build pipeline to run the tests in Azure DevOps CI but 
Cypress always gets a timeout since it cannot find the web app running.

### Current behavior:
Here the Azure DevOps log while running cypress run task:
```
2020-01-19T14:12:28.2027450Z ##[section]Starting: Run Cypress tests
2020-01-19T14:12:28.2030129Z ==============================================================================
2020-01-19T14:12:28.2030173Z Task         : Command line
2020-01-19T14:12:28.2030201Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-01-19T14:12:28.2030279Z Version      : 2.163.0
2020-01-19T14:12:28.2030305Z Author       : Microsoft Corporation
2020-01-19T14:12:28.2030333Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-01-19T14:12:28.2030396Z ==============================================================================
2020-01-19T14:12:28.3288351Z Generating script.
2020-01-19T14:12:28.3309317Z Script contents:
2020-01-19T14:12:28.3309813Z npm run cypress-ci
2020-01-19T14:12:28.3310045Z ========================== Starting Command Output ===========================
2020-01-19T14:12:28.3347838Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/690b2e7d-782d-4840-b68f-41bd2d9b9062.sh
2020-01-19T14:12:28.5983778Z 
2020-01-19T14:12:28.5984707Z > mvp@1.0.0 cypress-ci /home/vsts/work/1/s
2020-01-19T14:12:28.5985381Z > start-server-and-test start http-get://localhost:3000 cypress-ci
2020-01-19T14:12:28.5985738Z 
2020-01-19T14:12:28.9205577Z starting server using command "npm run start"
2020-01-19T14:12:28.9213560Z and when url "http-get://localhost:3000" is responding
2020-01-19T14:12:28.9213835Z running tests using command "npm run cypress-ci"
2020-01-19T14:12:29.1869502Z 
2020-01-19T14:12:29.1871146Z > mvp@1.0.0 start /home/vsts/work/1/s
2020-01-19T14:12:29.1871503Z > react-scripts start
2020-01-19T14:12:29.1871650Z 
2020-01-19T14:12:31.0672068Z [34mâ„¹[39m [90mï½¢wdsï½£[39m: Project is running at http://10.1.0.4/
2020-01-19T14:12:31.0673845Z [34mâ„¹[39m [90mï½¢wdsï½£[39m: webpack output is served from /
2020-01-19T14:12:31.0674476Z [34mâ„¹[39m [90mï½¢wdsï½£[39m: Content not from webpack is served from /home/vsts/work/1/s/public
2020-01-19T14:12:31.0674950Z [34mâ„¹[39m [90mï½¢wdsï½£[39m: 404s will fallback to /index.html
2020-01-19T14:12:31.0675844Z Starting the development server...
2020-01-19T14:12:31.0676122Z 
2020-01-19T14:13:03.7218989Z Compiled with warnings.
2020-01-19T14:13:03.7219588Z 
2020-01-19T14:13:03.7338209Z ./src/components/checks/MibiDetailedChecks.js
2020-01-19T14:13:03.7338980Z   Line 141:36:  Expected to return a value at the end of arrow function  array-callback-return
2020-01-19T14:13:03.7339027Z 
2020-01-19T14:13:03.7339141Z ./src/components/SummaryTable.js
2020-01-19T14:13:03.7339420Z   Line 29:9:  'locale' is assigned a value but never used  no-unused-vars
2020-01-19T14:13:03.7349909Z 
2020-01-19T14:13:03.7350143Z Search for the keywords to learn more about each warning.
2020-01-19T14:13:03.7351081Z To ignore, add // eslint-disable-next-line to the line before.
2020-01-19T14:13:03.7351484Z 
2020-01-19T14:13:07.2349884Z 
2020-01-19T14:13:07.2351680Z > mvp@1.0.0 cypress-ci /home/vsts/work/1/s
2020-01-19T14:13:07.2352490Z > start-server-and-test start http-get://localhost:3000 cypress-ci
2020-01-19T14:13:07.2352947Z 
2020-01-19T14:13:07.6014690Z starting server using command "npm run start"
2020-01-19T14:13:07.6021495Z and when url "http-get://localhost:3000" is responding
2020-01-19T14:13:07.6023371Z running tests using command "npm run cypress-ci"
2020-01-19T14:13:07.8683198Z 
2020-01-19T14:13:07.8684104Z > mvp@1.0.0 start /home/vsts/work/1/s
2020-01-19T14:13:07.8684286Z > react-scripts start
2020-01-19T14:13:07.8684316Z 
2020-01-19T14:13:09.5394564Z Something is already running on port 3000.
2020-01-19T14:13:09.5725408Z Error: server closed unexpectedly
2020-01-19T14:13:09.5726241Z     at ChildProcess.onClose (/home/vsts/work/1/s/node_modules/start-server-and-test/src/index.js:68:14)
2020-01-19T14:13:09.5726626Z     at ChildProcess.emit (events.js:198:13)
2020-01-19T14:13:09.5726797Z     at maybeClose (internal/child_process.js:982:16)
2020-01-19T14:13:09.5726913Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2020-01-19T14:13:09.5775626Z npm ERR! code ELIFECYCLE
2020-01-19T14:13:09.5779261Z npm ERR! errno 1
2020-01-19T14:13:09.5791461Z npm ERR! mvp@1.0.0 cypress-ci: `start-server-and-test start http-get://localhost:3000 cypress-ci`
2020-01-19T14:13:09.5791587Z npm ERR! Exit status 1
2020-01-19T14:13:09.5794585Z npm ERR! 
2020-01-19T14:13:09.5795030Z npm ERR! Failed at the mvp@1.0.0 cypress-ci script.
2020-01-19T14:13:09.5795088Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-19T14:13:09.5863811Z 
2020-01-19T14:13:09.5864101Z npm ERR! A complete log of this run can be found in:
2020-01-19T14:13:09.5865077Z npm ERR!     /home/vsts/.npm/_logs/2020-01-19T14_13_09_580Z-debug.log
2020-01-19T14:13:09.6085172Z { Error: Command failed with exit code 1 (EPERM): npm run cypress-ci
2020-01-19T14:13:09.6088932Z     at makeError (/home/vsts/work/1/s/node_modules/start-server-and-test/node_modules/execa/lib/error.js:59:11)
2020-01-19T14:13:09.6089658Z     at handlePromise (/home/vsts/work/1/s/node_modules/start-server-and-test/node_modules/execa/index.js:112:26)
2020-01-19T14:13:09.6089869Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-01-19T14:13:09.6090307Z   command: 'npm run cypress-ci',
2020-01-19T14:13:09.6090487Z   exitCode: 1,
2020-01-19T14:13:09.6091102Z   exitCodeName: 'EPERM',
2020-01-19T14:13:09.6091305Z   stdout: undefined,
2020-01-19T14:13:09.6091426Z   stderr: undefined,
2020-01-19T14:13:09.6091700Z   failed: true,
2020-01-19T14:13:09.6091847Z   timedOut: false,
2020-01-19T14:13:09.6091961Z   isCanceled: false,
2020-01-19T14:13:09.6092070Z   killed: false,
2020-01-19T14:13:09.6092213Z   signal: undefined }
2020-01-19T14:13:09.6176611Z npm ERR! code ELIFECYCLE
2020-01-19T14:13:09.6200254Z npm ERR! errno 1
2020-01-19T14:13:09.6200985Z npm ERR! mvp@1.0.0 cypress-ci: `start-server-and-test start http-get://localhost:3000 cypress-ci`
2020-01-19T14:13:09.6201231Z npm ERR! Exit status 1
2020-01-19T14:13:09.6202301Z npm ERR! 
2020-01-19T14:13:09.6202662Z npm ERR! Failed at the mvp@1.0.0 cypress-ci script.
2020-01-19T14:13:09.6202711Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-19T14:13:09.6269272Z 
2020-01-19T14:13:09.6274674Z npm ERR! A complete log of this run can be found in:
2020-01-19T14:13:09.6275300Z npm ERR!     /home/vsts/.npm/_logs/2020-01-19T14_13_09_619Z-debug.log
2020-01-19T14:13:09.6593220Z ##[error]Bash exited with code '1'.
2020-01-19T14:13:09.6604871Z ##[section]Finishing: Run Cypress tests
```

### Desired behavior:
Cypress should connect successfully to the CRA web app and run the tests.

### Test code to reproduce
package.json (scripts):
```json  
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "build-demo": "env-cmd -f .env.demo npm run build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint-staged": "eslint --ignore-path cypress --max-warnings 0",
    "cypress": "cypress open",
    "cypress:verify": "cypress verify",
    "cypress-ci-smoke": "npx cypress run -–record --group 'Azure CI' –ci-build-id $(build.BuildNumber)_$(Build.SourceBranchName) –parallel --reporter junit --spec 'cypress/integration/smoke-tests/**/*'",
    "cypress-ci": "start-server-and-test start http://localhost:3000 cypress-ci",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
```

azure-pipeline.yml
```yml
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: npm run cypress:verify
    displayName: 'Cypress verify'

 - script: |
      npm run cypress-ci
    displayName: 'Run Cypress tests'
    env:
      # avoid warnings about terminal
      TERM: xterm

  - task: CmdLine@2
    inputs:
      script: |
        echo Write your commands here
        npx cypress run –record --group "Azure CI" –ci-build-id $(build.BuildNumber)_$(Build.SourceBranchName) –parallel --reporter junit --spec 'cypress/integration/smoke-tests/**/*'
      failOnStderr: false
    displayName: 'Cypress Smoke Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'Cypress Test Results'
```

### Versions
Cypress v4.0.1
Cypress v3.8.2
Azure DevOps

**Comment by jennifer-shehane** [comment]
This error is being thrown from the [`start-server-and-test`](https://github.com/bahmutov/start-server-and-test) node module, not Cypress. 

There is an error in your log saying `Something is already running on port 3000.`, make sure nothing else is occupying the port you are running your server on before starting.

Closing as this error has nothing to do with Cypress.
