### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by LienLotus** [cypress-io/cypress#6412]
### Current behavior:

Get a DOM element by ID and it fails immediately

![Screenshot from 2020-02-11 16-37-02](https://user-images.githubusercontent.com/51039899/74225227-dbb0a080-4cec-11ea-9768-f1f6853db57f.png)

**### Note that it works fine on Cypress 3.2.0**

### Desired behavior:

Should find the element and continue working

### Test code to reproduce

```js
cy.visit('https://www.buydrm.com/multikey-demo')
cy.get('#sourceUrl');
```

### Versions

Cypress package version: 4.0.1
Cypress binary version: 4.0.1
Chrome version 79
Electron version 78

**Comment by LienLotus** [comment]
hi @jennifer-shehane   do you have any suggestion ?
Thanks

**Comment by jennifer-shehane** [comment]
@LienLotus Thank you for providing a reproducible example. I am able to reproduce this in Cypress 4.0.1. I wasn't able to reproduce this by just pulling out the pages HTML, so it likely has something to do with the JS or CSS on the page. 

This is a regression introduced in Cypress version 3.5.0.

## 3.4.1
<img width="851" alt="Screen Shot 2020-02-12 at 4 03 08 PM" src="https://user-images.githubusercontent.com/1271364/74321792-4deab900-4db1-11ea-9feb-96a92f2976ae.png">

## 3.5.0

<img width="963" alt="Screen Shot 2020-02-12 at 3 35 44 PM" src="https://user-images.githubusercontent.com/1271364/74322482-627b8100-4db2-11ea-8d8e-a008f0a8cc06.png">

**Stack trace:**

```
cypress_runner.js:177710 TypeError: Illegal invocation
    at Module.getNativeProp (https://www.buydrm.com/__cypress/runner/cypress_runner.js:105932:28)
    at isAutIframe (https://www.buydrm.com/__cypress/runner/cypress_runner.js:105285:21)
    at getRectFromAutIframe (https://www.buydrm.com/__cypress/runner/cypress_runner.js:105321:13)
    at Object.getElementPositioning (https://www.buydrm.com/__cypress/runner/cypress_runner.js:105344:21)
    at elIsOutOfBoundsOfAncestorsOverflow (https://www.buydrm.com/__cypress/runner/cypress_runner.js:107590:30)
    at isHidden (https://www.buydrm.com/__cypress/runner/cypress_runner.js:107446:10)
    at Array.isVisible (https://www.buydrm.com/__cypress/runner/cypress_runner.js:107383:11)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:13942:22
    at superMatcher (https://www.buydrm.com/__cypress/runner/cypress_runner.js:14163:12)
    at Sizzle.select (https://www.buydrm.com/__cypress/runner/cypress_runner.js:14342:44)
    at Sizzle (https://www.buydrm.com/__cypress/runner/cypress_runner.js:12510:9)
    at Function.Sizzle.matchesSelector (https://www.buydrm.com/__cypress/runner/cypress_runner.js:13169:9)
    at tryFn (https://www.buydrm.com/__cypress/runner/cypress_runner.js:84598:30)
    at tryCatchFinally (https://www.buydrm.com/__cypress/runner/cypress_runner.js:84571:12)
    at Function.../driver/src/config/jquery.js.$.find.matchesSelector (https://www.buydrm.com/__cypress/runner/cypress_runner.js:84596:10)
    at Function.jQuery.filter (https://www.buydrm.com/__cypress/runner/cypress_runner.js:14514:22)
From previous event:
    at resolveElements (https://www.buydrm.com/__cypress/runner/cypress_runner.js:91428:27)
    at Context.get (https://www.buydrm.com/__cypress/runner/cypress_runner.js:91436:9)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:100025:33
From previous event:
    at runCommand (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100007:14)
    at next (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100142:14)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:100165:18
From previous event:
    at next (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100142:34)
From previous event:
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:100179:37
From previous event:
    at run (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100171:15)
    at Object.cy.<computed> [as visit] (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100537:11)
    at Context.runnable.fn (https://www.buydrm.com/__cypress/runner/cypress_runner.js:100724:20)
    at callFn (https://www.buydrm.com/__cypress/runner/cypress_runner.js:30931:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://www.buydrm.com/__cypress/runner/cypress_runner.js:30924:7)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:103593:28
From previous event:
    at Object.onRunnableRun (https://www.buydrm.com/__cypress/runner/cypress_runner.js:103582:17)
    at $Cypress.action (https://www.buydrm.com/__cypress/runner/cypress_runner.js:97300:30)
    at Test.Runnable.run (https://www.buydrm.com/__cypress/runner/cypress_runner.js:102519:20)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://www.buydrm.com/__cypress/runner/cypress_runner.js:31398:10)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:31504:12
    at next (https://www.buydrm.com/__cypress/runner/cypress_runner.js:31318:14)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:31328:7
    at next (https://www.buydrm.com/__cypress/runner/cypress_runner.js:31260:14)
    at https://www.buydrm.com/__cypress/runner/cypress_runner.js:31296:5
    at timeslice (https://www.buydrm.com/__cypress/runner/cypress_runner.js:26364:27)
```

**Comment by gabbersepp** [comment]
I had the same problem while answering this question:
https://stackoverflow.com/questions/60073225/in-cypress-how-can-i-check-the-response-time-of-an-action/60115486#60115486

If I change the JS within the HTML to this:

```js
var parent = document.querySelector(".many");
var prom = () => new Promise(resolve => {
    var e = document.createElement("div");
    e.classList.add("red");
    parent.append(e);
    setTimeout(resolve, 1000);
})
```

So when moving the definition of `parent` outside of the Promise callback, I get that exception.

**Comment by LienLotus** [comment]
Hi @jennifer-shehane ,
Do you know which cypress version > 3.4.1 will not happen this issue ?
Thanks!

**Comment by jennifer-shehane** [comment]
@LienLotus This issue is not fixed. This issue will happen in every version after 3.4.1 until the issue is closed and fixed.

**Comment by LienLotus** [comment]
Hi @jennifer-shehane ,
Thank you for your information,
This issue will cause my task stuck, do you have any suggestion or workaround to bypass it?
Thanks!

**Comment by jennifer-shehane** [comment]
I can recreate this with the test below. If I change the `var parent` to any other name, this passes. 

`index.html`

```html
<html>
<body>
<div class="many"></div>
<button id="manyadd">add many</button>
<script>
  // if I change this var name to anything else, it passes.
  var parent = document.querySelector(".many")
</script>
</body>
</html>
```

`spec.js`

```js
it('illegal invocation', () => {
  cy.visit('index.html')
  cy.get('#manyadd').click()
})
```

<img width="434" alt="Screen Shot 2020-07-01 at 12 45 13 PM" src="https://user-images.githubusercontent.com/1271364/86209517-c1426b00-bb98-11ea-9dec-efea9495ab89.png">
