### ISSUE TITLE
Cannot find module - macOS - 4.0.2

### ISSUE THREAD

**Issue by josephzidell** [cypress-io/cypress#6470]
### Current behavior:
Get this error:

    Error: Cannot find module 'micromatch'
    Require stack:
    - /usr/local/lib/node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js
    - /usr/local/lib/node_modules/webpack/lib/WebpackOptionsApply.js
    - /usr/local/lib/node_modules/webpack/lib/webpack.js
    - /Users/<username>/code/<dir>/node_modules/@cypress/webpack-preprocessor/index.js
    - /Users/<username>/code/<dir>/cypress/plugins/index.js
    - /Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
    - /Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
        at Module._load (internal/modules/cjs/loader.js:622:27)
        at Module._load (electron/js2c/asar.js:717:26)
        at Function.Module._load (electron/js2c/asar.js:717:26)
        at Module.require (internal/modules/cjs/loader.js:775:19)
        at require (internal/modules/cjs/helpers.js:68:18)
        at Object.<anonymous> (/usr/local/lib/node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js:7:12)
        at Module._compile (internal/modules/cjs/loader.js:880:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
        at Module.load (internal/modules/cjs/loader.js:735:32)
        at Module._load (internal/modules/cjs/loader.js:648:12)
        at Module._load (electron/js2c/asar.js:717:26)
        at Function.Module._load (electron/js2c/asar.js:717:26)
        at Module.require (internal/modules/cjs/loader.js:775:19)
        at require (internal/modules/cjs/helpers.js:68:18)
        at WebpackOptionsApply.process (/usr/local/lib/node_modules/webpack/lib/WebpackOptionsApply.js:345:34)
        at webpack (/usr/local/lib/node_modules/webpack/lib/webpack.js:57:48)
        at Object.handler (/Users/<username>/code/<dir>/node_modules/@cypress/webpack-preprocessor/index.js:97:22)
        at invoke (/Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:25:16)
        at /Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
        at tryCatcher (/Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
        at Function.Promise.attempt.Promise.try (/Users/<username>/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)

### Desired behavior:
Test should run

### Test code to reproduce
Run tests on a mac, with any of the supported browsers

### Versions
4.0.2, macOS Catalina, Firefox/Chrome/Edge/Electron, installed via npm

**Comment by josephzidell** [comment]
It worked in 4.0.1

**Comment by josephzidell** [comment]
Nevermind. It was an npm issue
