### ISSUE TITLE
Feature Request: Custom error messages

### ISSUE THREAD

**Issue by manuelJung** [cypress-io/cypress#6474]
if this is not the right place for feature-request, I apologize.

I have an idea for more project-individual error messages:

```javascript
cy.get('my-element > li.product-widget')
  .pinCustomError('ops! not enough product widgets were rendered')
  .should('have.length', 12)
  .unpinCustomError()
```

When some error is thrown between a `.pinCustomErrro(msg)` and `.unpinCustomError()` the original error message gets replaced with the provided message. That would make the errors way more descriptive

another example:

```javascript
cy.pinCustomError('product widget did not render')
  .get('.product-widget')
```
As a developer I write a lot of tests. An error like `CypressError: Timed out retrying: Expected to find element: '.product-widget', but never found it.` may not really tell me why the test failed. especially if it is a way more complex test than above.

Custom error messages could really help me to identify the problem faster for tests i wrote months ago

**Comment by jennifer-shehane** [comment]
The error messages of assertions are customizable when using the explicit `expect` or `assert` assetions, although this is poorly documented so I understand it not being found. 

```js
it('repro', () => {
  cy.get('div').should((div) => {
    expect(div, 'Text should match here').to.contain('foo')
  })
})
```

Unfortunately, this signature doesn't quite work from within Cypress commands `.should()` or `.and()` chainer. I'll double check on this, but I'm not aware of a way.

**Comment by estefafdez** [comment]
I would love to have that, I will give it a try to the way you add @jennifer-shehane. Thanks!

**Comment by Nogias9x** [comment]
You saved my day @jennifer-shehane ! It works perfectly.
Thank you so much

**Comment by github-ronk** [comment]
@jennifer-shehane - it doesn't seem to work, at least in the following case.   Any idea?  Thanks.

```
export function assertLoggedIn(): void {
    cy.get('navigation-tree').should((tree) => {
        expect(tree, "Not logged in - can't locate navigation tree").to.be.visible;
    });
}
```

The log:  (note the error messgage it's not the custom one)

```
  1) UI tests for JUnit test in CypressPocTestWithCmdLine.java
       uses a bogus user in UI:
     AssertionError: Timed out retrying: Expected to find element: `navigation-tree`, but never found it.
      at Object.assertLoggedIn (http://localhost:49159/__cypress/tests?p=cypress/integration/tests/basicCypressSuiteInvoking.ts:172:31)
      at Context.eval (http://localhost:49159/__cypress/tests?p=cypress/integration/tests/basicCypressSuiteInvoking.ts:209:17)
```

Using the latest Cypress version.

**Comment by mwren-mshanken** [comment]
Allowing .should() and .and() chainers to take an options array that could contain a custom errorMessage option or something of the sort would be wonderful!

**Comment by sandra-ouadghiri** [comment]
If you use this one
` expect(value1).to.deep.include.members(value2)`
Then you get 3 assertions: `value1 is an array`, `value2 is an array`, and `one is a superset of the other`. Which is very nice.

But in this assertion case, if I add a custome error message
` expect(value1, 'Expected that and that').to.deep.include.members(value2)`

The error appears in last assertion as expected but... the 2 previous assert on variables being an array do not behave properly. They display only the first word of the string.

Weird. @jennifer-shehane should this be declared as its own issue or... ?
![image](https://user-images.githubusercontent.com/77396345/129194491-c1feb5f9-91c9-4642-8771-82c340d35bf8.png)

**Comment by zolirevesz** [comment]
Hello! 😊
@jennifer-shehane Is there any update on this?
I think it would be a useful feature that I could use at work to give more insight on what that check does.

**Comment by orennu** [comment]
@jennifer-shehane for some reason expect(element, 'custom message).to.contain('some text') works while expect(element, 'custom message').to.exist doesn't

```
it('test custom error message', () => {
        cy.visit('https://mywebsite.com/')
        cy.get('button[type="submitfoo"]').should((button) => {
            expect(button, 'submit button should exist').to.exist;
        })
    })
```
AssertionError: Timed out retrying after 20000ms: Expected to find element: `button[type="submitfoo"]`, but never found it.

```
it('test custom error message', () => {
        cy.visit('https://mywebsite.com/')
        cy.get('button[type="submit"]').should((button) => {
            expect(button, 'submit button should exist').to.exist;
            expect(button, 'the button should contain NEXT').to.contain('Next');
        })
    })
```
AssertionError: Timed out retrying after 20000ms: the button should contain NEXT: expected '\<button\>' to contain 'foo'

**Comment by justasdev** [comment]
This is a must have and would make reports like allure more informative and easier to debug.
You guys are already awesome for making a cypress, but if you make something like
`
cy.findByTestId('some-test-id').should('be.visible', {error: 'Response was successful but notification is not visible'})
`
you would be even more awesome.

**Comment by BillyTom** [comment]
It would be great if it were possible to add custom messages to the "get" selector as well.

Sometimes I have a complex "get" expression that is not easy to read. I try compensate this by adding comments:

```
// Search inside the user grid
cy.get('.x-grid').within(element => {
    // Get the fifth column of the user grid
    cy.get('.x-grid-cell:nth-child(5)').contains('John');
})
```

If the second "get" selector fails you get a reather cryptic error message: `Error: Timed out retrying after 4000ms: Expected to find element: .x-grid-cell:nth-child(5), but never found it.`.

It would be nice if cypress would support custom messages for selectors as well. Then the following would be possible:

```
cy.get('.x-grid', { message: 'Get the user grid'}).within(element => {
    cy.get('.x-grid-cell:nth-child(5)', { message: 'Get the fifth column in user grid'}).contains('John');
})
```

And the error message would be: `Error: Timed out retrying after 4000ms: Get the fifth column in user grid.`.

**Comment by machineghost** [comment]
Just one more "me too" vote.

Virtually every other test runner/assertion library provides a way to supply a custom assertion message.  For instance, here's how they do it in [Jest](https://stackoverflow.com/questions/45348083/how-to-add-custom-message-to-jest-expect), [Chai](https://stackoverflow.com/questions/45678706/how-to-provide-chai-expect-with-custom-error-message-for-mocha-unit-test), and [Ava](https://github.com/avajs/ava/blob/main/docs/03-assertions.md#enhanced-assertion-messages).

Cypress should have this essential feature also!

**Comment by balrajOla** [comment]
I vote on this too.

**Comment by justasdev** [comment]
This feature request is 4yo now. Is there any plans to implement it?

**Comment by SebMoreno** [comment]
As per @jennifer-shehane comment above:
> Unfortunately, this signature doesn't quite work from within Cypress commands `.should()` or `.and()` chainer. I'll double check on this, but I'm not aware of a way.


Is there a way to:
1. have a custom error displayed for an assertion made with .should()?
2. have a custom error be displayed without the original chai/cypress error?

```
cy.visit("https://www.google.com/en");

cy.get("input[type=submit]").eq(2).should("have.value", "Google Search"); // error message: expected <input.gNO89b> to have value Google Search

cy.get("input[type=submit]").eq(2).should("have.value", "Google Search", "Custom error"); // error message is the same as the original, does nothing

cy.get("input[type=submit]").eq(2).should(btn => {
    expect(btn, "Custom error").to.have.value("Google Search");
}); // error message: Custom error: expected <input.gNO89b> to have value Google Search
// this displays the custom error but appends the original chai/cypress
```

**Comment by hnykda** [comment]
wow, I am surprised, I considered this to be a very default usecase that I know from e.g. vitest, jest, or pytest. There really isnt a way to put in higher level summary of the error? I would really love to be able to return e.g. "No new message found" instead of "has length 4 instead of 5"...

**Comment by dah-fari7009** [comment]
Also upvoting this issue as custom error messaging would be beneficial to quickly identify test failure reasons in code pipelines.
