### ISSUE TITLE
Cypress is unable to run test after update

### ISSUE THREAD

**Issue by LukeClone** [cypress-io/cypress#6524]
### Current behavior:

Hi, I updated my cypress package to 4.0.2 from 3.8.3. Since this upgrade I cannot run tests. Once I start any test, new automated window is opened and after few seconds I get pop-up with one asking me for project data. It doesn't matters if I choose project, because at the end I get another same pop-up asking me for project. This is affecting both `run` and `open` commands. After clossing all cypress windows I have this in my terminal:

```
GET /__/ 200 13.925 ms - -
GET /__cypress/runner/cypress_runner.css 200 8.541 ms - -
GET /__cypress/runner/cypress_runner.js 200 2.233 ms - -
GET /__cypress/iframes/integration/loginPage.spec.js 200 2.145 ms - 747
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 2.354 ms - 75728
[9325:0220/182803.732610:ERROR:child_process_sandbox_support_impl_linux.cc(81)] FontService unique font name matching request did not receive a response.
[10015:0220/182817.966964:ERROR:child_process_sandbox_support_impl_linux.cc(81)] FontService unique font name matching request did not receive a response.
SyntaxError: Unexpected token  in JSON at position 0 while parsing file: /home/luke/Public/tf-erp/tf-erp-client/cypress/integration/loginPage.spec.js
    at JSON.parse (<anonymous>:null:null)
    at loadNycConfig (/home/luke/Public/tf-erp/tf-erp-client/node_modules/babel-plugin-istanbul/lib/index.js:55:23)
    at findConfig (/home/luke/Public/tf-erp/tf-erp-client/node_modules/babel-plugin-istanbul/lib/index.js:91:10)
    at PluginPass.enter (/home/luke/Public/tf-erp/tf-erp-client/node_modules/babel-plugin-istanbul/lib/index.js:121:28)
    at newFn (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /home/luke/.cache/Cypress/4.0.2/Cypress/resources/app/packages/server/node_modules/@babel/core/lib/transform.js:34:34
```
### Current behavior record
![cypress-upgraded](https://user-images.githubusercontent.com/50261222/74962618-91c46a80-5410-11ea-8f82-07231fd9e970.gif)

### Desired behavior:

Cypress start executing tests

### Test code to reproduce

*cypress.json*
```
{
  "baseUrl": "http://localhost:8080"
}
```

*cypress/integration/loginPage.spec.js*
```js
import { adminEmail, adminPassword } from '../fixtures/baseFixtures';

describe('Login page', () => {
  it('Can access login page', () => {
    cy.visit('/');
    cy.get('[data-cy="login-button"]');
  });

  it('Can login without google sso', () => {
    cy.login(adminEmail, adminPassword).then(response => {
      cy.setAuthState(response.body);

      cy.visit(`/#/app/home`);
      cy.get('[data-cy="logout"]').click();
      cy.url().should('include', '/#/login');
    });
  });
});
```

*cypress/support/commands.js*
```js
import { serverUrl } from '../fixtures/baseFixtures';

Cypress.Commands.add('login', (email, password) => {
  cy.visit('/');
  return cy.request('POST', `${serverUrl}/api/auth/login`, {
    email,
    password,
  });
});

Cypress.Commands.add('setAuthState', (state) => {
  cy.window().its('app.$store').then(store => {
    store.commit('LOGIN_WITH_GOOGLE_SUCCESS', state);
  });
});
```
*cypress/support/index.js*
```
import '@cypress/code-coverage/support';
import './commands';
```

*cypress/plugins/index.js*
```js
module.exports = (on, config) => {
  on('task', require('@cypress/code-coverage/task'))
};
```

### Versions

Cypress: 4.0.2
@cypress/code-coverage/task: 1.12.2
OS: Linux Mint 19.1 Cinamon (same behaviour on Windows 10)
Node: 11.14.0

**Comment by jennifer-shehane** [comment]
I was not able to reproduce this. Of course, I can't exactly run the tests as provided. This is really weird though, I've never seen this behavior. 

- Can you include the exact npm / yarn command you are running?
- Could you try to [follow these instructions](https://on.cypress.io/debugging#Clear-App-Data) to Clear App Data?
- Also if you can narrow down the issue further to find the smallest repo (like, remove code-coverage - does it still happen, remove x custom command - does it still happen) that would be helpful.

**Comment by LukeClone** [comment]
Hi, I already "solved" this problem. We're using `instanbul` with `nyc` for code coverage. Described behaviour was caused by `babel-plugin-istanbul@6.x.x`. Downgrading to `babel-plugin-istanbul@5.2.0` solved this weird pop-up behaviour. Anyway thanks for help :)

**Comment by lianzhao** [comment]
> Hi, I already "solved" this problem. We're using `instanbul` with `nyc` for code coverage. Described behaviour was caused by `babel-plugin-istanbul@6.x.x`. Downgrading to `babel-plugin-istanbul@5.2.0` solved this weird pop-up behaviour. Anyway thanks for help :)

I met exactly same issue when upgrading cypress from v4.10.0 to v5.3.0. Downgrade to babel-plugin-istanbul@5.x worked. But, why? 😂😂
