### ISSUE TITLE
Cannot yarn install Cypress deps locally

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6542]
### Current behavior:

Running `yarn` on `develop` returns the following error:

```
@packages/ui-components: error Command failed with exit code 2.
lerna ERR! yarn run build exited 2 in '@packages/ui-components'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
error Command failed with exit code 2.
child_process.js:660
    throw err;
    ^

Error: Command failed: yarn run postinstall
lerna notice cli v3.18.3
lerna info Executing command in 10 packages: "yarn run build"
@packages/example: set -e
@packages/example: rm -rf app
@packages/example: mkdir app
@packages/example: cp -r /Users/jennifer/Dev/cypress/node_modules/cypress-example-kitchensink/app .
@packages/example: rm -rf cypress
@packages/example: cp -r /Users/jennifer/Dev/cypress/node_modules/cypress-example-kitchensink/cypress .
@packages/example: exec node ./bin/convert.js
cypress: set -e
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/blob-util types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/bluebird types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/lodash types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/mocha types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/minimatch types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/sinon types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/sinon-chai types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/chai types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/chai-jquery types
cypress: cp -R /Users/jennifer/Dev/cypress/node_modules/@types/jquery types
cypress: rm -rf types/jquery/dist
cypress: sed -i <reference types="chai" /> <reference path="../chai/index.d.ts" /> types/chai-jquery/index.d.ts
cypress: sed -i <reference types="jquery" /> <reference path="../jquery/index.d.ts" /> types/chai-jquery/index.d.ts
cypress: sed -i <reference types="chai" /> <reference path="../chai/index.d.ts" /> types/sinon-chai/index.d.ts
cypress: sed -i <reference types="sinon" /> <reference path="../sinon/index.d.ts" /> types/sinon-chai/index.d.ts
cypress: sed -i from 'sinon'; from '../sinon'; types/sinon-chai/index.d.ts
cypress: set -e
cypress: rm -rf build
cypress: mkdir -p build/bin
cypress: mkdir -p build/types
cypress: cp bin/cypress build/bin/cypress
cypress: cp NPM_README.md build/README.md
cypress: cp .release.json build/.release.json
cypress: cp -R types/*.ts build/types/
cypress: cp -R types/blob-util build/types
cypress: cp -R types/bluebird build/types
cypress: cp -R types/lodash build/types
cypress: cp -R types/mocha build/types
cypress: cp -R types/minimatch build/types
cypress: cp -R types/sinon build/types
cypress: cp -R types/sinon-chai build/types
cypress: cp -R types/chai build/types
cypress: cp -R types/chai-jquery build/types
cypress: cp -R types/jquery build/types
cypress: exec babel lib -d build/lib
cypress: exec babel index.js -o build/index.js
@packages/ui-components: error Command failed with exit code 2.
lerna ERR! yarn run build exited 2 in '@packages/ui-components'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
error Command failed with exit code 2.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/Users/jennifer/Dev/cypress/node_modules/postinstall-postinstall/run.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  status: 2,
  signal: null,
  output: [
    null,
    <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 32 32 2e 30 0a 24 20 70 61 74 63 68 2d 70 61 63 6b 61 67 65 20 26 26 20 79 61 72 6e 20 62 75 69 6c 64 0a 70 61 74 ... 15121 more bytes>,
    <Buffer 6c 65 72 6e 61 20 6e 6f 74 69 63 65 20 63 6c 69 20 76 33 2e 31 38 2e 33 0a 6c 65 72 6e 61 20 69 6e 66 6f 20 45 78 65 63 75 74 69 6e 67 20 63 6f 6d 6d ... 2811 more bytes>
  ],
  pid: 97711,
```

### Test code to reproduce

I didn't do anything unusual. It was working in my branch, I changed branches to `develop` and now it won't install. 

- I tried `yarn clean-deps`

### Versions

`develop` branch and other branches.

**Comment by kevinccbsg** [comment]
Hi @jennifer-shehane , I'm getting the same error, is there any workaround to run cypress locally?

**Comment by kevinccbsg** [comment]
@jennifer-shehane I retry today and I was able to install dependencies. 👍 🚀

**Comment by flotwig** [comment]
@jennifer-shehane is this still happening?

**Comment by jennifer-shehane** [comment]
No, Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
