### ISSUE TITLE
When no server is up cypress crashes with stackoverflow

### ISSUE THREAD

**Issue by akoidan** [cypress-io/cypress#6557]
If the server (which cypress tests), e.g. localhost:8000, is not accessible during the start of the test - cypress will crash with stackoverflow. The setup is simple. The test start and then exist immediately
```
describe("Main page", (): void => {
  it("Should display main page", (): void => {
  });
});
```
cypress just crashes. 

### Current behavior:
```
RangeError: Maximum call stack size exceeded
    at get (internal/bootstrap/pre_execution.js:286:8)
    at hasBinary (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/socket/node_modules/has-binary2/index.js:44:3)
    at hasBinary (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
.... MORE 10000 of those
    at hasBinary (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/socket/node_modules/has-binary2/index.js:37:11)
    at /Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/lib/socket.js:385:13
    at /Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/socket.js:401:18
    at tryCatcher (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/deathangel908/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

### Versions

cypres 4.0.2/Chrome 79/MacOS 13

**Comment by akoidan** [comment]
Ok, this probably duplicates [this](https://github.com/cypress-io/cypress/pull/5528) one
