### ISSUE TITLE
Run tests on web server with IPv6 address

### ISSUE THREAD

**Issue by stanislav-chlebec** [cypress-io/cypress#6579]
### Current behavior:

Does not work `cypress/included:3.8.3` with IPv6 `baseUrl` address such as `[fe80::24ef:9eff:fee6:2082%ens18]:`

```
$ docker run -v /home/jenkins/workspace/frinx-machine-cypress-testing:/e2e -w /e2e -e NO_COLOR=1 -e 'CYPRESS_baseUrl=http://[fe80::24ef:9eff:fee6:2082%ens18]:3000' -e 'CYPRESS_inventory=http://[fe80::24ef:9eff:fee6:2082%ens18]:5601' -e CYPRESS_login=test@test.test -e CYPRESS_password=testtest --entrypoint=cypress cypress/included:3.8.3 run --browser chrome --headless
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
(node:18) [DEP0118] DeprecationWarning: The provided hostname "" is not a valid hostname, and is supported in the dns module solely for compatibility.
(node:18) [DEP0118] DeprecationWarning: The provided hostname "" is not a valid hostname, and is supported in the dns module solely for compatibility.
Cypress could not verify that this server is running:

  > http://[fe80::24ef:9eff:fee6:2082%ens18]:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
```

### Desired behavior:

The same server tested with IPv4 address - it works:

```
$ docker run -v /home/jenkins/workspace/frinx-machine-cypress-testing:/e2e -w /e2e -e NO_COLOR=1 -e CYPRESS_baseUrl=http://10.103.5.231:3000 -e CYPRESS_inventory=http://10.103.5.231:5601 -e CYPRESS_login=test@test.test -e CYPRESS_password=testtest --entrypoint=cypress cypress/included:3.8.3 run --browser chrome --headless
```

### Versions

Docker image `cypress/included:3.8.3`

**Comment by jennifer-shehane** [comment]
Is this only an issue within the docker container? Have you run this locally in Cypress on your machine? Does visiting an IPv6 address usually resolve outside of docker?

**Comment by stanislav-chlebec** [comment]
well I tried it also outside of the container
but I encountered the same errors
vagrant@ubuntu-1604:~$ cat b
NO_COLOR=1 \
CYPRESS_baseUrl=http://[fe80::24ef:9eff:fee6:2082]:3000 \
CYPRESS_inventory=http://[fe80::24ef:9eff:fee6:2082%ens18]:5601 \
CYPRESS_login=test@test.test \
CYPRESS_password=testtest \
~/node_modules/.bin/cypress run --browser chrome --headless | tee fm_test.out

vagrant@ubuntu-1604:~$ bash b
Cypress could not verify that this server is running:

  > http://[fe80::24ef:9eff:fee6:2082]:3000

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
vagrant@ubuntu-1604:~$

It works with curl like this:
vagrant@ubuntu-1604:~$ curl -iL -g -6  "http://[fe80::24ef:9eff:fee6:2082%ens18]:3000/"
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Fri, 28 Feb 2020 06:45:02 GMT
ETag: W/"a97-1708a8a91b0"
Content-Type: text/html; charset=UTF-8
Content-Length: 2711
Date: Fri, 28 Feb 2020 08:25:08 GMT
Connection: keep-alive

<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="./favicon.ico"/><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="./manifest.json"/><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"><link rel="stylesheet" href="https://codemirror.net/theme/neat.css"/><link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/mono-blue.min.css"><title>UniConfig CLI</title><link href="/static/css/2.64816f08.chunk.css" rel="stylesheet"><link href="/static/css/main.78731ec9.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(l){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],f=0,i=[];f<n.length;f++)t=n[f],p[t]&&i.push(p[t][0]),p[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(l[r]=o[r]);for(s&&s(e);i.length;)i.shift()();return c.push.apply(c,u||[]),a()}function a(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==p[u]&&(n=!1)}n&&(c.splice(r--,1),e=f(f.s=t[0]))}return e}var t={},p={1:0},c=[];function f(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return l[e].call(r.exports,r,r.exports,f),r.l=!0,r.exports}f.m=l,f.c=t,f.d=function(e,r,t){f.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(r,e){if(1&e&&(r=f(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)f.d(t,n,function(e){return r[e]}.bind(null,n));return t},f.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="/";var r=window.webpackJsonp=window.webpackJsonp||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;a()}([])</script><script src="/static/js/2.c26d90db.chunk.js"></script><script src="/static/js/main.6a9e30ae.chunk.js"></script></body></html>vagrant@ubuntu-1604:~$

But it does not work if I open http://[fe80::24ef:9eff:fee6:2082]:3000/ in google-chrome
It seems that I need some route rule...

________________________________

**Comment by stanislav-chlebec** [comment]
I assigned the global scope IPv6 address to the Subject Under Test.
The host where cypress resides has assigned also global scope IPv6 address.

I am able to ping in-between both like this:
`ping6  fd89:41e8:b895:2cc6::2`

I got the `HTTP/1.1 200 OK` to the curl commands:
`curl -iL -g -6 'http://[fd89:41e8:b895:2cc6::2]:5601'`
`curl -iL -g -6 'http://[fd89:41e8:b895:2cc6::2]:3000'`

But when I tried to run cypress it got stuck - I was checking via tcpdump:
` sudo tcpdump -i ens18 -vv ip6`
No IPv6 packet came through...

The way how I run cypress is:
NO_COLOR=1 \
CYPRESS_baseUrl=http://[fd89:41e8:b895:2cc6::2]:3000 \
CYPRESS_inventory=http://[fd89:41e8:b895:2cc6::2]:5601 \
CYPRESS_login=test@test.test \
CYPRESS_password=testtest \
~/node_modules/.bin/cypress run --browser chrome --headless | tee fm_test.out

This all works when I test via IPv4 network (the same command like above but with IPv4 addresses)

When I run chrome-browser at the same machine and try to browse the site http://[fd89:41e8:b895:2cc6::2]:3000 it works.

**Comment by stanislav-chlebec** [comment]
[fe80::24ef:9eff:fee6:2082%ens18] is IPv6 scope link address
The problem with this type of addresses is that they are[ not supported in browsers](https://stackoverflow.com/questions/45299648/how-to-access-devices-with-ipv6-link-local-address-from-browserlike-ie-firefox)

**Comment by stanislav-chlebec** [comment]
1 .Start cypress
CYPRESS_baseUrl=http://[fd89:41e8:b895:2cc6::2]:3000 \
~/node_modules/.bin/cypress open --browser chrome
2. Choose the test
3. Chrome browser opens the window with url
http://[fd89:41e8:b895:2cc6::2]:3000/__/#/tests/integration/01mount_device_spec.js
Browser displays notification: Chrome is being controlled by automated test software.
There are javascript errors found in Chrome dev tools 
http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:168422 Console was cleared
http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42039 DOMException: Failed to set the 'domain' property on 'Document': 'fd89:41e8:b895:2cc6::2' could not be parsed properly.
    at $Cypress.setConfig (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133318:25)
    at new $Cypress (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133289:10)
    at Function.create (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133778:14)
    at Object.setup (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:168156:86)
    at Iframes._this._run (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:167175:32)
    at Iframes.componentDidMount (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:167291:12)
    at ik (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42094:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057:437)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:325)
    at Yj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42087:437)
    at Lj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42066:420)
    at http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964:115
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057:437)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:325)
    at ig (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964:61)
    at jg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:496)
Pi @ http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42039
http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42039 TypeError: Cannot read property 'getSizeContainer' of undefined
    at App._handleScreenshots (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:165461)
    at App.componentDidMount (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:165431)
    at ik (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42094)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963)
    at Yj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42087)
    at Lj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42066)
    at http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963)
    at ig (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964)
    at jg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963)
    at bk (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42067)
    at reactionScheduler (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:33852)
    at runReactions (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:33852)
    at endBatch (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:33852)
Pi @ http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42039
http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964 Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'fd89:41e8:b895:2cc6::2' could not be parsed properly.
    at $Cypress.setConfig (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133318:25)
    at new $Cypress (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133289:10)
    at Function.create (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:133778:14)
    at Object.setup (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:168156:86)
    at Iframes._this._run (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:167175:32)
    at Iframes.componentDidMount (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:167291:12)
    at ik (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42094:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057:437)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:325)
    at Yj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42087:437)
    at Lj (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:42066:420)
    at http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964:115
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:45057:437)
    at fg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:325)
    at ig (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41964:61)
    at jg (http://[fd89:41e8:b895:2cc6::2]:3000/__cypress/runner/cypress_runner.js:41963:496)
~                                                                                                                                                                                                                                                                        
~

**Comment by stanislav-chlebec** [comment]
Cypress testing of IPv6 works 
1
after the DNS record is put to /etc/hosts:
fd89:41e8:b895:2cc6::2 fm
2
after the configuration added to cypress.json
  "chromeWebSecurity": false,
3
And then
NO_COLOR=1
CYPRESS_baseUrl=http://fm:3000
CYPRESS_inventory=http://fm:5601
CYPRESS_login=test@test.test
CYPRESS_password=testtest
~/node_modules/.bin/cypress run --browser chrome --headless | tee fm_test.out

**Comment by stanislav-chlebec** [comment]
Cypress testing of IPv6 works 
1
after the DNS record is put to /etc/hosts:
fd89:41e8:b895:2cc6::2 fm
2
after the configuration added to cypress.json
  "chromeWebSecurity": false,
3
And then
NO_COLOR=1
CYPRESS_baseUrl=http://fm:3000
CYPRESS_inventory=http://fm:5601
CYPRESS_login=test@test.test
CYPRESS_password=testtest
~/node_modules/.bin/cypress run --browser chrome --headless | tee fm_test.out

**Comment by jennifer-shehane** [comment]
@stanislav-chlebec Thanks for investigation - and very grateful for you sharing your results since this may help someone else. 🙏

**Comment by vish-stack** [comment]
@stanislav-chlebec its worked thanks

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress/issues/25950
