### ISSUE TITLE
`patch-package` not correctly applied since Yarn upgrade

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#6582]
`patch-package` has not been applied to built binaries ever since #5555 was merged, leading to regressions coming from an unpatched `has-binary2` when users send certain circular data over WebSockets:

```
RangeError: Maximum call stack size exceeded
at get (internal/bootstrap/pre_execution.js:286:8)
at hasBinary (/builds/platform/ui/client/cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:44:3)
at hasBinary (/builds/platform/ui/client/cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
at hasBinary (/builds/platform/ui/client/cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
at hasBinary (/builds/platform/ui/client/cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
```

The patch is correctly applied during development, but during production builds it is not. This is probably because `has-binary2` is in `node_modules` in dev, but in `packages/socket/node_modules` in the built binary.

**Comment by flotwig** [comment]
This patch in `driver` does seem to still be applied correctly in both production and development:

https://github.com/cypress-io/cypress/blob/cb0f32b0b4913cbb403f2e7c51b23ecad50ece9f/packages/driver/patches/sinon+8.1.1.patch#L1-L20

I believe this is a coincidence though, there is an earlier version of `sinon` installed in the root node_modules which causes this `sinon` to be installed in the `driver` folder in both development and production.

`node_modules` in development and production should probably be aligned and then we can have confidence in where the patches will be applied every time.

**Comment by bahmutov** [comment]
Can we move patch into build step or duplicate it?

**Comment by flotwig** [comment]
I think we just need to add the `has-binary2` dep to [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/), then it will work (turns out @packages/driver/sinon is also in nohoist, which is why the patch works)
