### ISSUE TITLE
"Cannot find any observable" error when upgrading from 3.x to 4.x

### ISSUE THREAD

**Issue by dthomason** [cypress-io/cypress#6600]
### Current behavior:

We have cypress in our mono repo and when attempting to upgrade from any 3.x version to 4.x version we receive the following error
```
error /node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory:/node_modules/cypress
Output:
/node_modules/any-observable/register.js:29
                throw new Error('Cannot find any-observable implementation nor' +
                ^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/node_modules/any-observable/register.js:29:9)
    at /node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (/node_modules/any-observable/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/node_modules/@samverschueren/stream-to-observable/index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)```
```
### Desired behavior:

Upgrade to 4.0.2

### Versions
initial version 3.4.1
wanting to upgrade to version 4.0.2
MacOS Mojave

**Comment by jennifer-shehane** [comment]
@dthomason Are you using yarn 2 to install? Also, do you have yarn 2 installed globally? Looks like a duplicate of https://github.com/cypress-io/cypress/issues/6377 if this is the case. 

If this is the case, we recommend installing yarn 2 per project as yarn advises: https://github.com/cypress-io/cypress/issues/6377#issuecomment-592742158

**Comment by dthomason** [comment]
@jennifer-shehane we are still on yarn 1.x.  Adding rjxs and rjxs-compat seemed to do the trick.  Thanks!

**Comment by onlywei** [comment]
I don't think having to install `rxjs` and `rxjs-compat` is a good solution to this problem. This sounds like one of Cypress's packages failed to properly declare a dependency.

**Comment by nyoblick** [comment]
rxjs or zen-observables is required here due to this: https://github.com/SamVerschueren/stream-to-observable/blob/v0.3.0/package.json#L19
cypress5 -> listr -> stream-to-observable

zen-observables is preferable because it is smaller (70kb vs 5Mb)
