### ISSUE TITLE
Unable to use 'cypress run' or 'cypress open' with custom browser.

### ISSUE THREAD

**Issue by kyle-mcknight** [cypress-io/cypress#6653]
### Current behavior:

I have downloaded a version of Chromium from chromium.cypress.io and am attempting to use it with either cypress run or cypress open commands but cannot. Using cypress open I get the error in the following screenshot.

![2020-03-05 12_08_20-D__development_accesso_applications_angular-pos](https://user-images.githubusercontent.com/17067600/76006134-09e36380-5eda-11ea-98eb-f0eef0b60d26.png)

Using cypress run I get an error on the command line that states it cannot find a known browser.

![2020-03-05 12_11_19-Window](https://user-images.githubusercontent.com/17067600/76006527-9beb6c00-5eda-11ea-9636-836f21d89560.png)

I have attempted using both relative and absolute paths to the version of Chromium that was downloaded.

### Desired behavior:

Cypress should run as normal using the specified browser

### Test code to reproduce

Clone repo https://github.com/kyle-mcknight/cypress-test-tiny

Run npm install

So as to not upload large files I did not add the chromium folder to the repo. Download Chromium here https://chromium.cypress.io/win/stable/80.0.3987.87 and place the unzipped folder in <project root>\chromium

Run command npm run cypress:open:relative and see that it doesn't find any browser there at all
Run command npm run cypress:open:absolute and see that it opens and prints the version of chrome but still doesn't work

Following is the error output

**Message:** We could not identify a known browser at the path you provided: `D:\development\accesso\applications\cypress-test-tiny\cypress\chromium\chrome-win\chrome.exe`

The output from the command we ran was:

**Details:** Version=80.0.3987.0

**Stack trace:**
```
[object Object]
    at get (<app data path>\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\errors.js:344:11)
    at Object.throwErr [as throw] (<app data path>\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\errors.js:359:11)
    at <app data path>\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\browsers\index.js:119:28
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
From previous event:
    at fn (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88596:14)
    at ipcBus (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88614:10)
    at Object.ipc.<computed> [as openProject] (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88655:69)
    at Object.openProject (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:91044:67)
    at Project.componentDidMount (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:90630:78)
    at ik (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63603:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at Yj (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63596:437)
    at Lj (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63575:420)
    at file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63473:115
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at ig (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63473:61)
    at jg (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:496)
    at bk (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63576:156)
    at reactionScheduler (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:37214:47)
    at runReactions (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:37190:5)
    at endBatch (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:36890:9)
From previous event:
    at App.componentDidMount (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:86643:77)
    at ik (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63603:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at Yj (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63596:437)
    at Lj (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63575:420)
    at Rg (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63566:137)
    at rk (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63631:43)
    at file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63634:301
    at ck (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63576:210)
    at zk (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63634:287)
    at render (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63638:416)
    at Object.start (file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:89216:61)
    at file:///<app data path>/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/index.html:29:11
```

### Versions

This is happening in version 3.8.3 for my actual project, but it's happening in the forked project as well which is the latest stable version 4.1.0

**Comment by CypressCecelia** [comment]
Hello, it looks like you are providing a path to a `.exe` file. Per the [documentation here](https://docs.cypress.io/guides/guides/launching-browsers.html#Launching-by-a-path) you need to specifying a path to the binary. 

Please let me know if that does not resolve the issue.

**Comment by CypressCecelia** [comment]
Actually, I apologize, I just found [this documentation](https://docs.cypress.io/guides/references/troubleshooting.html#Windows) that on Windows it should be a `.exe`. 

Are you using the `--browser` flag when you run your command? The documentation [here about launching browsers](https://docs.cypress.io/guides/references/troubleshooting.html#Launching-browsers) in the Troubleshooting guide has some workarounds.

**Comment by kyle-mcknight** [comment]
OH good, I had thought the exe was the binary!

Yes I do have the --browser flag when running the command. When using cypress run I get the following error onthe command line. With cypress open, I get the same output showing the version just like in the command line but in the red error box

```
We could not identify a known browser at the path you provided: `C:\<path-to-project>\cypress\chrome-win\chrome.exe`

The output from the command we ran was:

 Version=80.0.3987.0
```

**Comment by kyle-mcknight** [comment]
I did realize I didn't push my commit to my forked test. Ihave pushed a commit that has the --browser option. The path would need to be changed and chromium needs to be downloaded since I couldn't add it to the repo because it's too large. But it shows the commands I am using in the package.json file

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) specifically logging `cypress:launcher` logs and run `cypress info` and print the entire set of logs here?

**Comment by kyle-mcknight** [comment]
I ran the command `npx cypress run --browser "C:\development\accesso\applications\cypress-test-tiny\cypress\\chromium\chrome-win\chrome.exe"`

I have attached two files, one with DEBUG set to cypress:* and one with it set to cypress:launcher

I then ran the command
[run-with-browser-debug-all.txt](https://github.com/cypress-io/cypress/files/4313350/run-with-browser-debug-all.txt)
[run-with-browser-debug-launcher.txt](https://github.com/cypress-io/cypress/files/4313351/run-with-browser-debug-launcher.txt)

**Comment by flotwig** [comment]
This is a known issue with passing `--browser` on Windows, a workaround is to supply the browser via the plugin file instead: #6389

**Comment by kyle-mcknight** [comment]
Will this work for cypress run though? It only mentions that it will work for cypress open. I need to be able to use run for CI

**Comment by jennifer-shehane** [comment]
@kyle-mcknight Yes, the workaround will work for `cypress run` also.
