### ISSUE TITLE
Test hangs when failed to get accounts.google.com

### ISSUE THREAD

**Issue by MakDon** [cypress-io/cypress#6786]
### Current behavior:

A test hangs occasionally, without being marked failed or timeout.

### Desired behavior:

Connect error causes an error and other tests go on.

### Test code to reproduce

The code is private for some reasons. Here's the debug log.

The healthy test's log:

```
2020-03-18T08:08:47.687Z cypress:network:connect received error on connect, retrying { iteration: 0, delay: 0, err: { 
  Error: connect ETIMEDOUT 172.217.27.141:443 
    at Object._errnoException (util.js:1024:11) 
    at _exceptionWithHostPort (util.js:1046:20) 
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) 
  code: 'ETIMEDOUT', 
  errno: 'ETIMEDOUT', 
  syscall: 'connect', 
  address: '172.217.27.141', 
  port: 443 
} }
2020-03-18T08:08:48.838Z cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:08:49.486Z cypress:server:project onMocha hook end
2020-03-18T08:08:49.486Z cypress:server:reporter got mocha event 'hook end' with args: [ { <private info> } ]
2020-03-18T08:08:49.518Z cypress:server:project onMocha pass
2020-03-18T08:08:49.518Z cypress:server:reporter got mocha event 'pass' with args: [ { <private info> } ]
2020-03-18T08:08:49.519Z cypress:server:project onMocha test end
2020-03-18T08:08:49.519Z cypress:server:reporter got mocha event 'test end' with args: [ { <private info>} ]
2020-03-18T08:08:49.555Z cypress:server:project onMocha test:after:run
2020-03-18T08:08:49.556Z cypress:server:reporter got mocha event 'test:after:run' with args: [ {  <private info> } ]
2020-03-18T08:08:49.562Z cypress:server:project onMocha suite end
2020-03-18T08:08:49.563Z cypress:server:reporter got mocha event 'suite end' with args: [ { <private info> } ]
2020-03-18T08:08:49.563Z cypress:server:project onMocha suite end
2020-03-18T08:08:49.563Z cypress:server:reporter got mocha event 'suite end' with args: [ { <private info>} ]
2020-03-18T08:08:49.563Z cypress:server:project onMocha end
2020-03-18T08:08:49.564Z cypress:server:reporter got mocha event 'end' with args: [ { <private info> } ]
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="87.891" tests="13" failures="0">
  <testsuite name="Root Suite" timestamp="2020-03-18T08:07:19" tests="0" failures="0" time="0">
  </testsuite>
```

The log that hangs:
```
2020-03-18T08:10:01.112Z cypress:https-proxy received error on client browserSocket { err: { Error: read ECONNRESET at _errnoException (util.js:1024:11) at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }, url: 'api.wesure.cn:443' }
2020-03-18T08:10:01.113Z cypress:server:preprocessor removeFile /home/node/app/cypress/integration/foo.js
2020-03-18T08:10:01.113Z cypress:server:preprocessor base emitter plugin close event
2020-03-18T08:10:01.113Z cypress:server:preprocessor base emitter native close event
2020-03-18T08:10:01.113Z cypress:browserify close: /home/node/app/cypress/integration/foo.js
2020-03-18T08:10:01.113Z cypress:browserify close: /home/node/app/cypress/integration/foo.js
2020-03-18T08:10:12.039Z cypress:network:connect received error on connect, retrying { iteration: 2, delay: 200, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:10:22.279Z cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:10:25.607Z cypress:network:connect received error on connect, retrying { iteration: 2, delay: 200, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:10:26.247Z cypress:network:connect received error on connect, retrying { iteration: 3, delay: 200, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:10:28.039Z cypress:network:connect received error on connect, retrying { iteration: 0, delay: 0, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
2020-03-18T08:10:54.919Z cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: { Error: connect ETIMEDOUT 172.217.27.141:443 at Object._errnoException (util.js:1024:11) at _exceptionWithHostPort (util.js:1046:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect', address: '172.217.27.141', port: 443 } }
```

### Versions

It actually returns nothing

```
root@585ceb14c5a0:/home/node/app# ./node_modules/.bin/cypress version
root@585ceb14c5a0:/home/node/app#
```

Here is my dockerfile:

```yml
FROM cypress/browsers:chrome67
RUN node --version
RUN npm --version
WORKDIR /home/node/app
EXPOSE 8000
COPY package.json package-lock.json ./
RUN npm install
COPY cypress.json ./
COPY cypress ./cypress
COPY run.sh run.sh
COPY send_report.js send_report.js
RUN mkdir logs
RUN ["touch", "logs/result.log"]
RUN ["chmod", "+x", "./run.sh"]
RUN ["chmod", "+x", "./send_report.js"]
CMD ["./run.sh"]
```

### Other info

- I used [cypress-plugin-retries](https://github.com/Bkucera/cypress-plugin-retries).
- It seems that it retries too much times without stopping it.
- The "cypress:server:project onMocha hook end" does not appears in the hanging test.
- The "connect ETIMEDOUT" address is belongs to accounts.google.com, which i never visit in my test case.

**Comment by jennifer-shehane** [comment]
Does this happen when you do not use the `cypress-plugin-retries` plugin?

**Comment by MakDon** [comment]
> Does this happen when you do not use the `cypress-plugin-retries` plugin?

I have been using this plugin for a long time, but the issue appears since not long ago. So i don't suppose it is strongly relevant. Maybe these's something updated on the target site that makes cypress hangs. How could i debug these test case?
Thanks for your reply.

**Comment by jennifer-shehane** [comment]
Honestly we'll need a reproducible example we can run on our machine to look into why this is happening. Can you provide one?

**Comment by MakDon** [comment]
I am sorry that i could not provide more info cause something in these test cases is private.
The test never hangs again since i removed some test cases.
Thanks for your help.

**Comment by ycwdaaaa** [comment]
is there any update?  I meet this error as well in docker

**Comment by ycwdaaaa** [comment]
maybe I'm in china, and i cannot access accounts.google.com， so it hangs?
