### ISSUE TITLE
Error when opening Cypress in develop branch in Mac - 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6850]
### Current behavior:

When running `yarn start` in Cypress in `develop` branch on my Mac Mojave 10.14.6 - this error always displays and I cannot proceed:

```
execa_1.default.stdout is not a function
```

<img width="1133" alt="Screen Shot 2020-03-26 at 11 58 06 AM" src="https://user-images.githubusercontent.com/1271364/77613952-6f1af980-6f5a-11ea-99f1-e877905cf6ac.png">

It looks like @bahmutov touched this `darwin/utils.js` file in https://github.com/cypress-io/cypress/issues/6013 This may be masking the real error that's not bubbling up.

https://github.com/cypress-io/cypress/pull/6013/files#diff-8196058edd4df324a343fc7abaa81f9b

Looks like `execa` was updated in this PR - this should be noted in the User Changelog of the PR for all dependency updates and *ideally* done in a separate PR so we can isolate the changes of the dep update. 

## Big question

Why didn't our tests catch this??

**Stack trace:**

```
[object Object]
    at mdfind (/Users/jennifer/Dev/cypress/packages/launcher/lib/darwin/util.js:50:10)
    at tryMdFind (/Users/jennifer/Dev/cypress/packages/launcher/lib/darwin/util.js:72:16)
    at Object.findApp (/Users/jennifer/Dev/cypress/packages/launcher/lib/darwin/util.js:79:12)
    at Object.detect (/Users/jennifer/Dev/cypress/packages/launcher/lib/darwin/index.js:93:19)
    at lookup (/Users/jennifer/Dev/cypress/packages/launcher/lib/detect.js:48:19)
    at checkOneBrowser (/Users/jennifer/Dev/cypress/packages/launcher/lib/detect.js:88:12)
    at /Users/jennifer/Dev/cypress/packages/launcher/lib/detect.js:58:20
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at fn (cypress:///./src/lib/ipc-bus.js:108:14)
    at ipcBus (cypress:///./src/lib/ipc-bus.js:127:10)
    at Object.ipc.<computed> [as openProject] (cypress:///./src/lib/ipc.js:29:69)
    at Object.openProject (cypress:///./src/projects/projects-api.js:175:67)
    at Project.componentDidMount (cypress:///./src/project/project.jsx:123:78)
    at commitLifeCycles (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:22101:22)
    at commitLayoutEffects (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:25344:7)
    at HTMLUnknownElement.callCallback (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:385:16)
    at invokeGuardedCallback (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:440:31)
    at commitRootImpl (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:25082:9)
    at unstable_runWithPriority (cypress:////Users/jennifer/Dev/cypress/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at runWithPriority$2 (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
    at commitRoot (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:24922:3)
    at finishSyncRender (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:24329:3)
    at performSyncWorkOnRoot (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:24307:9)
    at eval (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:12199:24)
    at unstable_runWithPriority (cypress:////Users/jennifer/Dev/cypress/node_modules/scheduler/cjs/scheduler.development.js:697:12)
    at runWithPriority$2 (cypress:////Users/jennifer/Dev/cypress/node_modules/react-dom/cjs/react-dom.development.js:12149:10)
```

### Test code to reproduce

- Pull `develop`
- Run `yarn start`

### Versions

- pre-release in `develop`
- Mac Mojave 10.14.6
- Node.js v12.8.1

**Comment by jennifer-shehane** [comment]
Fixed by running `yarn clean-js` in `packages/launcher` - there were leftover js files being read over the new ts files. thanks @bahmutov
