### ISSUE TITLE
EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by errohitrana2013** [cypress-io/cypress#6871]
### Current behavior:
EEXIST: file already exists, mkdir 'C:\Users\Happy_PC\CypressAutomation\node_modules.bin\cypress'

Stack trace
[object Object]
at fn (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88596:14)
at ipcBus (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88614:10)
at Object.ipc.<computed> [as openProject] (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88655:69)
    at Object.openProject (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:91044:67)
    at Project.componentDidMount (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:90630:78)
    at ik (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63603:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at Yj (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63596:437)
    at Lj (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63575:420)
    at file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63473:115
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at ig (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63473:61)
    at jg (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:496)
    at bk (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63576:156)
    at reactionScheduler (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:37214:47)
    at runReactions (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:37190:5)
    at endBatch (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:36890:9)
From previous event:
    at App.componentDidMount (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:86643:77)
    at ik (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63603:360)
    at ../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:73703:437)
    at fg (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63472:325)
    at Yj (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63596:437)
    at Lj (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63575:420)
    at Rg (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63566:137)
    at rk (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63631:43)
    at file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63634:301
    at ck (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63576:210)
    at zk (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63634:287)
    at render (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:63638:416)
    at Object.start (file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:89216:61)
    at file:///C:/Users/Happy_PC/AppData/Local/Cypress/Cache/4.1.0/Cypress/resources/app/

### Desired behavior:
Test runner should be lunched.

### Test code to reproduce
C:\Users\Happy_PC\CypressAutomation\node_modules\.bin>cypress open

### Versions
Cypress: 4.1.0

**Comment by errohitrana2013** [comment]
fixed. thanks
