### ISSUE TITLE
SyntaxError: Unexpected token * in `var NODE_OPTIONS = '--max-http-header-size=' + 1024 ** 2`

### ISSUE THREAD

**Issue by wulfsolter** [cypress-io/cypress#6885]
### Current behavior:

running
```
# show node/npm versions on the executor machine
node -v
npm -v

# npm install
npm install -g cypress
```

produces

```
v6.1.0
6.9.0
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/opt/circleci/.nvm/versions/node/v6.1.0/bin/cypress -> /opt/circleci/.nvm/versions/node/v6.1.0/lib/node_modules/cypress/bin/cypress

> cypress@4.3.0 postinstall /opt/circleci/.nvm/versions/node/v6.1.0/lib/node_modules/cypress
> node index.js --exec install

/opt/circleci/.nvm/versions/node/v6.1.0/lib/node_modules/cypress/lib/util.js:274
    var NODE_OPTIONS = '--max-http-header-size=' + 1024 ** 2 + ' --http-parser=legacy';
                                                         ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/circleci/.nvm/versions/node/v6.1.0/lib/node_modules/cypress/index.js:6:12)
    at Module._compile (module.js:541:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@4.3.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@4.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-03-30T23_11_26_316Z-debug.log


Exited with code exit status 1
CircleCI received exit code 1
```

### Desired behavior:

cypress to install

### Test code to reproduce

On a CircleCI executor 16.04 machine, run `npm install -g cypress`.

### Versions

Caused by cypress 4.3.0. Works on previous release 4.2.0

Node v6.1.0
npm 6.9.0
Ubuntu 16.04 (what CircleCI uses as executor machine)

**Comment by bahmutov** [comment]
Hmm the exponent notation should have been transpiled in CLI

**Comment by flotwig** [comment]
Hey @wulfsolter, as of Cypress 4.0.0, Node 8 or higher is required. Please update your Node version to 8 or higher.
