### ISSUE TITLE
Parse Error on URL 303 Redirection

### ISSUE THREAD

**Issue by himanshu-dixit** [cypress-io/cypress#6921]
### Current behavior:

https://www.stage-headout.com/book/8959/checkout?date=2020-03-27&variantId=16137&pax.adult=1

This URL has a 303 redirection. Apparently, while visiting this I'm getting an 

```
cy.visit() failed trying to load:

https://www.stage-headout.com/book/8959/checkout?date=2020-03-27&variantId=16137&pax.adult=1
```

Not an appropriate stack trace or log present.

### Desired behavior:

Load page normally after redirection.

### Test code to reproduce

```js
context('Actions', () => {
    it('open_homepage', function () {
      cy.visit('https://www.stage-headout.com/book/8959/checkout?date=2020-03-27&variantId=16137&pax.adult=1')
    });
})
```

### Versions
4.3

**Comment by jennifer-shehane** [comment]
<img width="1262" alt="Screen Shot 2020-04-06 at 12 59 46 PM" src="https://user-images.githubusercontent.com/1271364/78528912-8386ae00-7806-11ea-9385-a75f5010b502.png">

```
cy.visit() failed trying to load:

https://www.stage-headout.com/book/8959/checkout?date=2020-03-27&variantId=16137&pax.adult=1

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: Parse Error

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
```
