### ISSUE TITLE
Cypress version 3.8.3 no longer installs since April 3th (Ubuntu 18.04)

### ISSUE THREAD

**Issue by WesleySmits** [cypress-io/cypress#6940]
### Current behavior:
When you run npm i cypress@3.8.3 it returns an error. '_Error: Cannot find module 'elegant-spinner'_' since late last Friday afternoon.

#### Stack trace
```
> cypress@3.8.3 postinstall /application/symfony/node_modules/cypress
> node index.js --exec install

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'elegant-spinner'
Require stack:
- /application/symfony/node_modules/listr-update-renderer/lib/utils.js
- /application/symfony/node_modules/listr-update-renderer/index.js
- /application/symfony/node_modules/listr/lib/renderer.js
- /application/symfony/node_modules/listr/lib/task.js
- /application/symfony/node_modules/listr/index.js
- /application/symfony/node_modules/cypress/lib/tasks/install.js
- /application/symfony/node_modules/cypress/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/application/symfony/node_modules/listr-update-renderer/lib/utils.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/application/symfony/node_modules/listr-update-renderer/index.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/application/symfony/node_modules/listr-update-renderer/lib/utils.js',
    '/application/symfony/node_modules/listr-update-renderer/index.js',
    '/application/symfony/node_modules/listr/lib/renderer.js',
    '/application/symfony/node_modules/listr/lib/task.js',
    '/application/symfony/node_modules/listr/index.js',
    '/application/symfony/node_modules/cypress/lib/tasks/install.js',
    '/application/symfony/node_modules/cypress/index.js'
  ]
}
npm WARN natuurhuisje@1.0.0 No repository field.
npm WARN The package jquery is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.8.3 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-06T05_26_38_084Z-debug.log
root@c6e1f7c5f421:/application/symfony#
```

### Desired behavior:

The package should install on a clean install without issue.

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this issue running `npm i cypress@3.8.3`. 

Please make sure to clear all previously installed node_modules and any cache and install again. 

<img width="745" alt="Screen Shot 2020-04-06 at 12 53 25 PM" src="https://user-images.githubusercontent.com/1271364/78528538-a369a200-7805-11ea-915b-feae0eeb095e.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Please also include your OS and OS version if still occurring.
