### ISSUE TITLE
window:load is no longer a valid event name

### ISSUE THREAD

**Issue by lpanger** [cypress-io/cypress#7019]
### Current behavior:

in `cypress/plugins/index.js` it does not support event named `window:load` as described in https://docs.cypress.io/api/events/catalog-of-events.html#App-Events

probably caused by https://github.com/cypress-io/cypress/pull/5356

```
Error: You must pass a valid event name when registering a plugin.

You passed: window:load

The following are valid events:
- file:preprocessor
- before:browser:launch
- task
- after:screenshot

    at createErrorResult (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\validate_event.js:3:71)
    at validateEvent (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\validate_event.js:33:12)
    at register (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:35:32)
    at module.exports (C:\dev\cypress-example-kitchensink\cypress\plugins\index.js:22:3)
    at C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:75:12
    at tryCatcher (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at load (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:72:7)
    at EventEmitter.<anonymous> (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:196:5)
    at EventEmitter.emit (events.js:210:5)
    at process.<anonymous> (C:\Users\lucas\AppData\Local\Cypress\Cache\4.2.0\Cypress\resources\app\packages\server\lib\plugins\util.js:25:29)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Desired behavior:

Should support all events listed in documentation

### Test code to reproduce

in the `cypress/plugins/index.js` add

`  on('window:load', () => {
    // noop
  })`

I have this change in https://github.com/lpanger/cypress-example-kitchensink. run npm test

### Versions

cypress 4.4.0

**Comment by jennifer-shehane** [comment]
The events from https://on.cypress.io/catalog-of-events are different for the [pluginsFile events](https://docs.cypress.io/api/plugins/writing-a-plugin.html#List-of-events) (as noted in the error - it listed all available plugin events). 

These events will need to be listened to from within a test file or support file. See the examples in the docs: https://on.cypress.io/catalog-of-events
