### ISSUE TITLE
Running Cypress is flaky in CI

### ISSUE THREAD

**Issue by AleksanderBodurri** [cypress-io/cypress#7022]
### Current behavior:
Cypress running in CircleCI fails intermittently with a generic error message.

### Desired behavior:
For Cypress to run reliably in CI. 

### Versions

in package.json:
```json
"scripts": {
    ...
    "start": "ng serve",
    "cy:run": "$(yarn bin)/cypress run",
    "cy:ci": "start-server-and-test start http-get://localhost:4200 cy:run",
    ...
  },
  ...
  "devDependencies": {
   ...
    "cypress": "^4.0.0",
    "cypress-browser-extension-plugin": "^0.1.0",
    "cypress-iframe": "^1.0.1",
    "start-server-and-test": "^1.10.11",
   ...
    },

```

in .circleci/config.yml:
```yml
      - run:
          name: 'Run Cypress tests'
          command: yarn cy:ci
```
circle logs:

```
#!/bin/bash -eo pipefail
yarn cy:ci
yarn run v1.22.4
$ start-server-and-test start http-get://localhost:4200 cy:run
starting server using command "npm run start"
and when url "[ 'http-get://localhost:4200' ]" is responding with HTTP status code 200
running tests using command "npm run cy:run"

> app@0.0.0 start /home/circleci/repo
> ng serve

... // App builds


** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

> app@0.0.0 cy:run /home/circleci/repo
> $(yarn bin)/cypress run

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.0 cy:run: `$(yarn bin)/cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-04-15T21_27_08_984Z-debug.log
Error: Command failed with exit code 1: npm run cy:run
    at makeError (/home/circleci/repo/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/circleci/repo/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  command: 'npm run cy:run',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

I realize that it's difficult to debug CI issues since so many systems are working at once so I tried to supply as much info as possible. Running `yarn cy:ci` locally works perfectly every time.

It seems that everything works fine until the `cy:run` script runs. I have no idea why it fails randomly and was wondering if anyone has any experience with a similar issue.

**Comment by jennifer-shehane** [comment]
This error is being thrown from the [`start-server-and-test`](https://github.com/bahmutov/start-server-and-test) package, so does not appear to be an issue with the Cypress project. You can see from the log here:

```
    at makeError (/home/circleci/repo/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
```

Check the debug log from your circle run for more details (you'll need to save this as archive) `/home/circleci/.npm/_logs/2020-04-15T21_27_08_984Z-debug.log`

**Comment by damasofc** [comment]
Hi, I was getting the same issue, and this comment help me to get what was the error: [Cypress-CI-Error-Solution](https://github.com/cypress-io/cypress/issues/5143#issuecomment-533796858)
