### ISSUE TITLE
The Test Runner unexpectedly exited via a exit event with signal SIGILL

### ISSUE THREAD

**Issue by TonnTamerlan** [cypress-io/cypress#7045]
### Current behavior:

On Jenkins server Cypress crashes after starting with error

The Test Runner unexpectedly exited via a exit event with signal SIGILL

locally everything works as expected

![image](https://user-images.githubusercontent.com/25105232/79507238-0fd37500-8040-11ea-8e7c-57b5f1231015.png)

### Versions

Cypress 4.4.0
 operating system Ubuntu 16.04

**Comment by mirzamusic** [comment]
I found that the version of cypress must be the same one which is added to your package.json when you installed it.

So if your package.json says:
```    
"cypress": "^4.2.0",
```

just remove ^ so you will have 
```    
"cypress": "4.2.0",
```

I tried with lover and higher versions but only this works for me...

**Comment by jereaameli** [comment]
OK, I've been doing some testing, and discovered the following:

Last version where Cypress works with Jenkins is 4.1.0. Any newer version throws this error.

My setup is:
- Ubuntu 16.04
- Cypress 4.8.0

It would be really nice if this issue get attention and get fixed.

**Comment by hindsc52** [comment]
Also seeing this on versions 4.7, 4.8 & 4.9 when running on Jenkins

**Comment by davidhu2000** [comment]
i've tried 4.2.0 and 4.10.0. both gets this error. 

I wonder if 
```
21:25:03 resize:  can't open terminal /dev/tty
21:25:03 tput: No value for $TERM and no -T specified
```
has anything to do with it. 


```
21:24:58 It looks like this is your first time using Cypress: 4.2.0
21:24:58 
21:24:58 [04:24:58]  Verifying Cypress can run /var/lib/jenkins/.cache/Cypress/4.2.0/Cypress [started]
21:24:59 [04:24:59]  Verifying Cypress can run /var/lib/jenkins/.cache/Cypress/4.2.0/Cypress [completed]
21:24:59 
21:24:59 Opening Cypress...
21:25:03 
21:25:03 resize:  can't open terminal /dev/tty
21:25:03 tput: No value for $TERM and no -T specified
21:25:03 ================================================================================
21:25:03 
21:25:03   (Run Starting)
21:25:03 
21:25:03   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
21:25:03   │ Cypress:    4.2.0                                                                              │
21:25:03   │ Browser:    Electron 80 (headless)                                                             │
21:25:03   │ Specs:      1 found (homePageSpec.ts)                                                          │
21:25:03   └────────────────────────────────────────────────────────────────────────────────────────────────┘
21:25:03 
21:25:03 
21:25:03 ────────────────────────────────────────────────────────────────────────────────────────────────────
21:25:03                                                                                                     
21:25:03   Running:  homePageSpec.ts                                                                 (1 of 1)
21:25:03 The Test Runner unexpectedly exited via a exit event with signal SIGILL
21:25:03 
21:25:03 Please search Cypress documentation for possible solutions:
21:25:03 
21:25:03 https://on.cypress.io
21:25:03 
21:25:03 Check if there is a GitHub issue describing this crash:
21:25:03 
21:25:03 https://github.com/cypress-io/cypress/issues
21:25:03 
21:25:03 Consider opening a new issue.
21:25:03 
21:25:03 ----------
21:25:03 
21:25:03 Platform: linux (Ubuntu Linux - 16.04)
21:25:03 Cypress Version: 4.2.0
```

**Comment by jennifer-shehane** [comment]
Can anyone else verify if this issue is fixed when rolling back to 4.1.0? Isolating to a specific version would be helpful. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here also?

**Comment by jennifer-shehane** [comment]
I also see that everyone is using Electron headless browser. Has anyone tried running on a Chrome browser, passing the `--browser` flag?

**Comment by olleblom** [comment]
My solution
------------------
Dont start Xvfb like this: https://docs.cypress.io/guides/guides/continuous-integration.html#Xvfb
Start it like this: Xvfb -screen 0 1024x768x24 :99 &
Because this: https://github.com/microsoft/vscode/issues/95415
More specifically this: https://github.com/microsoft/vscode/issues/95415#issuecomment-617994685

Hope this helps someone else.

**Comment by jereaameli** [comment]
> I also see that everyone is using Electron headless browser. Has anyone tried running on a Chrome browser, passing the `--browser` flag?

I have tried. Same result.

**Comment by jonthomp** [comment]
@jennifer-shehane can confirm rollback to 4.1.0 resolved this for us using Chrome on GitLab CI.

**Comment by csvan** [comment]
Confirming this issue on Cypress 5.0, using Electron browser and bundled Node. 

CI env is CentOS 8 with externally started xvfb server (started via `/usr/bin/Xvfb :99 -screen 0 1920x1080x24+32 &`)

**Comment by UncleGus** [comment]
Confirming this issue, or at least something very similar, on Cypress 5.2.0

```
TypeError: Cannot read property 'length' of undefined
    at isInvalidSuite (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:130:62)
    at MochaJUnitReporter.<anonymous> (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:202:10)
    at Runner.emit (events.js:228:7)
    at Reporter.emit (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/reporter.js:322:46)
    at Object.onMocha (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/project.js:360:18)
    at Socket.<anonymous> (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/socket.js:320:32)
    at Socket.emit (events.js:223:5)
    at /home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

TypeError: Cannot read property 'length' of undefined
    at isInvalidSuite (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:130:62)
    at MochaJUnitReporter.<anonymous> (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/node_modules/mocha-junit-reporter/index.js:202:10)
    at Runner.emit (events.js:228:7)
    at Reporter.emit (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/reporter.js:322:46)
    at Object.onMocha (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/project.js:360:18)
    at Socket.<anonymous> (/home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/server/lib/socket.js:320:32)
    at Socket.emit (events.js:223:5)
    at /home/LETO/dk7239/.cache/Cypress/5.2.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu - 18.04)
Cypress Version: 5.2.0
```

**Comment by UncleGus** [comment]
Update: I just discovered that I had a `context` inside an `it`, which is clearly wrong, but I guess the error handling for this situation is not working properly.

**Comment by kazakevich-alexei** [comment]
![image](https://user-images.githubusercontent.com/60583226/164676960-20a106e5-ee43-4f46-b1d9-43616f15fdf6.png)

**Comment by cmrd-senya** [comment]
@far11ven 
With Cypress v10 when I did local yarn install of Cypress 
```
yarn add -D cypress
yarn install
```

And  running from local `node_modules` it with 
```
npx cypress info
```
 I received the SIGILL error. 

But then I tried installing Cypress globally like it's done in the official cypress docker image: https://github.com/cypress-io/cypress-docker-images/blob/6d7b9eb738d1904a01a7148e89854cd2188f66be/included/10.10.0/Dockerfile

So I installed Cypress as 
```
npm install -g "cypress@10.10.0"
```

And ran it as (without npx)
```
cypress info
```

Surprisingly it fixed the issue for me, after that Cypress ran without SIGILL.

**Comment by GrumpyMeow** [comment]
The reason that "cypress info" worked the second time, probably is because you didn't run "npx cypress info".
This worked for me:

.vscode/devcontainer.json:
```
{
  "name": "Ubuntu",
  "build": { "dockerfile": "Dockerfile" },
  "mounts": [
    "source=/home/me/.npmrc,target=/home/node/.npmrc,type=bind,consistency=cached,readonly",
    "source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind",
    "source=/mnt/wslg,target=/mnt/wslg,type=bind"
  ],
  "containerEnv": {
    "DISPLAY": ":0",
    "WAYLAND_DISPLAY": "${localEnv:WAYLAND_DISPLAY}",
    "XDG_RUNTIME_DIR": "${localEnv:XDG_RUNTIME_DIR}",
    "PULSE_SERVER": "${localEnv:PULSE_SERVER}"
  },
  "remoteUser": "node"
}
```

.vscode/Dockerfile:
```
FROM cypress/included:10.11.0

ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupmod --gid $USER_GID $USERNAME \
    && usermod --uid $USER_UID --gid $USER_GID $USERNAME \
    && chown -R $USER_UID:$USER_GID /home/$USERNAME

USER $USERNAME
```

If it doesnt work for you. You should run `id` in your container and on your host. You'll probably see that different uid/gid are used.
