### ISSUE TITLE
Getting `Failed to execute 'createElementNS' on 'Document'` using `its`

### ISSUE THREAD

**Issue by mjaeggi** [cypress-io/cypress#7076]
### Current behavior:

I'm getting the next error using `its` command. It doesn't matter what I request inside `its` always fails with the same error. 

```
Failed to execute 'createElementNS' on 'Document': The qualified name provided ('[object Object]') contains the invalid name-start character '['.
```

### Test code to reproduce

The HTML structure is

```html
<div id="scrolling-view" style="transform: translate(-2.5px, 0px);" class="svelte-1jbbmk8">
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-0-0-29" style="border-radius: 0px;"> 
            <img alt="Text" class="svelte-1cey5em" src="">
        </div> 
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;"> 
            <img alt="" class="svelte-1cey5em" src="">
        </div> 
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;">
            <img alt="" class="svelte-1cey5em" src="">
        </div>
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;">
            <img alt="" class="svelte-1cey5em" src="">
        </div>
    </div>
</div>
```

And in my test:

```JS
cy.get('.asset-container').its('length').should('eq', 12);
```

And fails with the same error using 
```JS
cy.get('.slider-item').should('have.length.of.at.least', assetAmount);
```

This works fine:
```JS
cy.get('.slider-item').should('have.length', 3);
```

The stack in the console is:
```
Error:    InvalidCharacterError: Failed to execute 'createElementNS' on 'Document': The qualified name provided ('[object Object]') contains the invalid name-start character '['.
InvalidCharacterError: Timed out retrying: Failed to execute 'createElementNS' on 'Document': The qualified name provided ('[object Object]') contains the invalid name-start character '['.
    at $ (https://localhost:4443/fd8aa164e43e10cddfb838550deb8108/app:1:1186)
From previous event:
    at retryValue (https://localhost:4443/__cypress/runner/cypress_runner.js:132389:25)
    at tryFn (https://localhost:4443/__cypress/runner/cypress_runner.js:140318:21)
    at whenStable (https://localhost:4443/__cypress/runner/cypress_runner.js:140353:12)
    at https://localhost:4443/__cypress/runner/cypress_runner.js:139897:16
```

### Versions
Cypress: 4.4.0
OS: macOS Mojave
Browser: Chrome 80 & 81

**Comment by jennifer-shehane** [comment]
I can't recreate the issue from the code provided. Please provide the full HTML/CSS/JS and Cypress tests required to recreate the issue and we will consider reopening. 

The test code I am running is below:

`index.html`

```html
<!doctype html>
<html>
<body>
<div id="scrolling-view" style="transform: translate(-2.5px, 0px);" class="svelte-1jbbmk8">
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-0-0-29" style="border-radius: 0px;">
            <img alt="Text" class="svelte-1cey5em" src="">
        </div>
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;">
            <img alt="" class="svelte-1cey5em" src="">
        </div>
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;">
            <img alt="" class="svelte-1cey5em" src="">
        </div>
    </div>
    <div class="slider-item svelte-1hofx7s" style="width: 205px; --hGap:5px; --assetsAmount:1;">
        <div class="asset-container svelte-1cey5em" id="asset-1-0-20" style="border-radius: 0px;">
            <img alt="" class="svelte-1cey5em" src="">
        </div>
    </div>
</div>
</body>
</html>
```

`spec.js`

```js
it('test 1', () => {
  cy.visit('index.html')
  cy.get('.asset-container').its('length').should('eq', 12);
})

it('test 2', () => {
  cy.visit('index.html')
  cy.get('.slider-item').should('have.length.of.at.least', 5);
})

it('test 3', () => {
  cy.visit('index.html')
  cy.get('.slider-item').should('have.length', 3);
})
```

<img width="654" alt="Screen Shot 2020-04-21 at 3 33 49 PM" src="https://user-images.githubusercontent.com/1271364/79847283-84623700-83e5-11ea-951a-4033203500da.png">
