### ISSUE TITLE
Error spawn UNKNOWN during `cypress run`

### ISSUE THREAD

**Issue by smrtyviks87** [cypress-io/cypress#7123]
Not able to run my spec files using the below mentioned command

```
npx cypress run --spec <spec path>
```

Getting Error:
```
Warning: We failed to trash the existing run results.

This error will not alter the exit code.

spawn UNKNOWN

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:553:9)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:152:24
    at FfmpegCommand.proto._getFfmpegPath (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:132:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\capabilities.js:517:10)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\capabilities.js:568:14
    at nextTask (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:4576:27)
    at Object.waterfall (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:4587:9)
    at Object.awaitable (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:208:32)
    at FfmpegCommand.proto._checkCapabilities (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\capabilities.js:565:11)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:298:14
    at nextTask (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:4576:27)
    at Object.waterfall (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:4587:9)
    at Object.awaitable (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\node_modules\async\dist\async.js:208:32)
    at FfmpegCommand.proto._prepare (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:295:11)
    at FfmpegCommand.proto.exec.proto.execute.proto.run (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\processor.js:431:10)
    at FfmpegCommand.proto.saveToFile.proto.save (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fluent-ffmpeg\lib\recipes.js:28:25)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\video_capture.js:191:20
    at Promise.cancellationExecute [as _execute] (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\debuggability.js:449:9)
    at Promise._resolveFromExecutor (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:103:10)
    at startCapturing (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\video_capture.js:132:14)
    at Object.start (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\video_capture.js:195:12)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\lib\modes\run.js:669:6
    at tryCatcher (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16
    at callback (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\fs-extra\node_modules\graceful-fs\polyfills.js:295:20)
    at callback (C:\Users\<username>\AppData\Local\Cypress\Cache\4.1.0\Cypress\resources\app\packages\server\node_modules\graceful-fs\polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:166:5)
```
I would like to run all my spec files in integration folder

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by bahunov** [comment]
Hi @jennifer-shehane 
I just saw this error on 5.1.0
`2020-11-25T06:57:44.501Z] 2020-11-25T06:57:44.446Z cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 }
[2020-11-25T06:57:44.501Z] Error: spawn ENOMEM
[2020-11-25T06:57:44.501Z]     at ChildProcess.spawn (internal/child_process.js:394:11)
[2020-11-25T06:57:44.501Z]     at spawn (child_process.js:549:9)
[2020-11-25T06:57:44.501Z]     at Object.execFile (child_process.js:233:17)
[2020-11-25T06:57:44.501Z]     at Object.module.<computed> [as execFile] (electron/js2c/asar.js:163:31)
[2020-11-25T06:57:44.501Z]     at exec (child_process.js:154:25)
[2020-11-25T06:57:44.501Z]     at electron/js2c/asar.js:727:23
[2020-11-25T06:57:44.501Z]     at /root/.cache/Cypress/5.1.0/Cypress/resources/app/packages/server/node_modules/systeminformation/lib/processes.js:636:17
[2020-11-25T06:57:44.501Z]     at ChildProcess.exithandler (child_process.js:295:7)
[2020-11-25T06:57:44.501Z]     at ChildProcess.emit (events.js:223:5)
[2020-11-25T06:57:44.501Z]     at maybeClose (internal/child_process.js:1021:16)
[2020-11-25T06:57:44.501Z]     at Socket.<anonymous> (internal/child_process.js:430:11)
[2020-11-25T06:57:44.501Z]     at Socket.emit (events.js:223:5)
[2020-11-25T06:57:44.501Z]     at Pipe.<anonymous> (net.js:664:12)
[2020-11-25T06:57:44.501Z]  {
[2020-11-25T06:57:44.501Z]   errno: 'ENOMEM',
[2020-11-25T06:57:44.501Z]   code: 'ENOMEM',
[2020-11-25T06:57:44.501Z]   syscall: 'spawn'
[2020-11-25T06:57:44.501Z] }
[2020-11-25T06:57:44.501Z] Error: spawn ENOMEM
[2020-11-25T06:57:44.501Z]     at ChildProcess.spawn (internal/child_process.js:394:11)
[2020-11-25T06:57:44.501Z]     at spawn (child_process.js:549:9)
[2020-11-25T06:57:44.501Z]     at Object.execFile (child_process.js:233:17)
[2020-11-25T06:57:44.501Z]     at Object.module.<computed> [as execFile] (electron/js2c/asar.js:163:31)
[2020-11-25T06:57:44.501Z]     at exec (child_process.js:154:25)
[2020-11-25T06:57:44.501Z]     at electron/js2c/asar.js:727:23
[2020-11-25T06:57:44.501Z]     at /root/.cache/Cypress/5.1.0/Cypress/resources/app/packages/server/node_modules/systeminformation/lib/processes.js:636:17
[2020-11-25T06:57:44.501Z]     at ChildProcess.exithandler (child_process.js:295:7)
[2020-11-25T06:57:44.501Z]     at ChildProcess.emit (events.js:223:5)
[2020-11-25T06:57:44.501Z]     at maybeClose (internal/child_process.js:1021:16)
[2020-11-25T06:57:44.501Z]     at Socket.<anonymous> (internal/child_process.js:430:11)
[2020-11-25T06:57:44.501Z]     at Socket.emit (events.js:223:5)
[2020-11-25T06:57:44.501Z]     at Pipe.<anonymous> (net.js:664:12)
[2020-11-25T06:57:44.501Z] 
[2020-11-25T06:57:44.501Z] 2020-11-25T06:57:44.449Z cypress:server:browsers killing browser process
[2020-11-25T06:57:44.501Z] 2020-11-25T06:57:44.449Z cypress:server:browsers:chrome closing remote interface client
[2020-11-25T06:57:45.063Z] 2020-11-25T06:57:44.951Z cypress:network:connect got addresses { hostname: 'api.cypress.io', port: 443, addresses: [ { address: '172.67.69.12', family: 4 }, { address: '104.26.6.176', family: 4 }, { address: '104.26.7.176', family: 4 }, { address: '2606:4700:20::ac43:450c', family: 6 }, { address: '2606:4700:20::681a:6b0', family: 6 }, { address: '2606:4700:20::681a:7b0', family: 6 } ] }
[2020-11-25T06:57:45.063Z] 2020-11-25T06:57:44.954Z cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 50050 }
[2020-11-25T06:57:45.063Z] 2020-11-25T06:57:44.985Z cypress:cli child event fired { event: 'exit', code: 1, signal: null }
[2020-11-25T06:57:45.063Z] 2020-11-25T06:57:44.985Z cypress:cli Stopping Xvfb
[2020-11-25T06:57:45.063Z] 2020-11-25T06:57:44.986Z cypress:cli child event fired { event: 'close', code: 1, signal: null }
[2020-11-25T06:57:45.063Z] [?25hnpm ERR! code ELIFECYCLE
[2020-11-25T06:57:45.063Z] npm ERR! errno 1
[2020-11-25T06:57:45.063Z] npm ERR! bete-web@0.0.0 test-e2e: `npx cypress run --config integrationFolder=cypress/integration --env `

**Comment by katalie** [comment]
Hey guys,

I faced the same issue, any solutions?

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi Team, 

I have below mentioned version of cypress and experiencing issue while running the cypress from package.json: 

"cy:run": "cypress run --spec 'cypress/integration/1-getting-started/*.js' --browser chrome --headed"

error: 

Warning: We failed to trash the existing run results.

This error will not alter the exit code.

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:707:9)
    at execFile (node:child_process:334:17)
    at node:child_process:244:21
    at node:electron/js2c/asar_bundle:5:3121
    at module.exports (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\lib\windows.js:12:8)    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\index.js:53:11
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\p-try\index.js:4:10
    at new Promise (<anonymous>:null:null)
    at pTry (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\p-try\index.js:3:37)
    at trash (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\trash\index.js:11:35)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\util\trash.js:16:16
    at tryCatcher (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise_array.js:79:10)
    at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\graceful-fs\graceful-fs.js:209:16
    at FSReqCallback.oncomplete (node:fs:185:23)


================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.5.2                                                                          │
  │ Browser:        Chrome 99                                                                      │
  │ Node Version:   v14.15.0 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (1-getting-started/todo.spec.js)                                       │
  │ Searched:       cypress\integration\1-getting-started\*.js                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  1-getting-started/todo.spec.js                                                  (1 of 1)
spawn UNKNOWN
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:707:9)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:152:24     
    at FfmpegCommand.proto._getFfmpegPath (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:132:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:517:10)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:568:14  
    at nextTask (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4576:13)    
    at Object.waterfall (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4587:9)
    at Object.awaitable (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:208:32)
    at FfmpegCommand.proto._checkCapabilities (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\capabilities.js:565:11)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:298:14     
    at nextTask (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4576:13)    
    at Object.waterfall (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:4587:9)
    at Object.awaitable (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\async\dist\async.js:208:32)
    at FfmpegCommand.proto._prepare (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:295:11)
    at FfmpegCommand.proto.exec.proto.execute.proto.run (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\processor.js:431:10)
    at FfmpegCommand.proto.saveToFile.proto.save [as save] (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fluent-ffmpeg\lib\recipes.js:28:25)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:215:24
    at Promise.cancellationExecute [as _execute] (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:103:10)
    at startCapturing (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:169:16)
    at Object.start (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\video_capture.js:218:12)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\lib\modes\run.js:680:6
    at tryCatcher (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._settlePromise (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:617:21)
    at Promise._settlePromise0 (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:673:18)
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\kemtej01\AppData\Local\Cypress\Cache\9.5.2\Cypress\resources\app\node_modules\fs-extra\node_modules\universalify\index.js:22:54

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raghav-pal@1.0.0 cy:run: `cypress run --spec 'cypress/integration/1-getting-started/*.js' --browser chrome --headed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raghav-pal@1.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kemtej01\AppData\Roaming\npm-cache\_logs\2022-03-17T10_20_02_430Z-debug.log

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi Team, 

Any update on the above reported issue? 
I tried downgrading the cypress version but no still no luck.

**Comment by T-e-j-k-u-m-a-r** [comment]
Additional Info: I have same configuration in my personal laptop over there when I try to execute all spec using command: 

"test:all":"cypress run --browser chrome --headed" --> from the package.json


npm run test:all

Appreciate a response and resolution as soon as possible.
