### ISSUE TITLE
cannot uninstall or rollback from 4.4.1

### ISSUE THREAD

**Issue by jdmairs** [cypress-io/cypress#7127]
### Current behavior:

After installing 4.4.1 and having an issue with it I'm trying to rollback to 4.3.  

```
rm -fr /Users/johnmairs/Library/Caches/Cypress/

rm -fr node_modules
modify package.json (as shown)
npm install
```

<img width="963" alt="Screen Shot 2020-04-23 at 4 20 40 PM" src="https://user-images.githubusercontent.com/5624808/80146032-28331a80-857f-11ea-9b49-25c708e7794f.png">

### Desired behavior:

Installing Cypress (version 4.3)

### Test code to reproduce

Install v 4.4.1
tried to rollback to v4.4.0 as well.

### Versions

Cypress 4.4.1, OSX Catalina 10.14

**Comment by jdmairs** [comment]
I was able to workaround by explicitly installing again.

npm install cypress@4.4.0

**Comment by erwinheitzman** [comment]
same here, it's probably your package-lock.json

**Comment by mbbillz** [comment]
I'm getting an error which I'm assuming is related to this. It started happening yesterday out of the blue after deleting my package-lock.json and trying to re-install my dependencies:

```
Error: No valid exports main found for '/Documents/Code/react_components/node_modules/is-promise'
    at resolveExportsTarget (internal/modules/cjs/loader.js:632:9)
    at applyExports (internal/modules/cjs/loader.js:500:14)
    at resolveExports (internal/modules/cjs/loader.js:549:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Documents/Code/react_components/node_modules/listr/lib/task.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Documents/Code/react_components/node_modules/listr/index.js:3:14) {
  code: 'MODULE_NOT_FOUND'
}
npm WARN @egoist/vue-to-react@1.1.0 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@4.4.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! Failed at the cypress@4.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Installing v4.4.0 explicitly seems to work temporarily but if I delete package-lock.json and try and re-install everything it breaks again.

**Comment by Yethal** [comment]
Also happens on Linux, I'm unable to install either the 4.4.0 or 4.4.1 via npm, same error is printed in the console.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
