### ISSUE TITLE
typescript compilerOptions "module" param breaks cypress

### ISSUE THREAD

**Issue by yoavniran** [cypress-io/cypress#7151]
### Current behavior:
In a JS project im working on I added TS type definitions for my packages.

for this I added a `tsconfig.json` to the root of my project. The "module" field in the config was accidentally set to "System".

When i committed my branch, cypress in CI started failing with an error:

```
ReferenceError: System is not defined
```

This was completely obscure to me and I couldnt figure out why it was failing since as far as i knew, ive made no change to Cypress.

Luckily, a search for the error found a similar (non Cypress related) that pointed me to the `tsconfig`.

### Desired behavior:

Cypress shouldnt be affected by the `tsconfig` of the project using it or at the very least, the error should include useful information to help fix the problem

### Test code to reproduce

repo can be found here: 

https://github.com/rpldy/react-uploady/tree/ts-defs

setting the module field in [tsconfig](https://github.com/rpldy/react-uploady/blob/ts-defs/tsconfig.json) to "System" and running:
``` yarn e2e ``` 
will result in the aforementioned error.

### Versions

cypress: 4.4.1

**Comment by jennifer-shehane** [comment]
I can reproduce this by: 

- Pulling down the repo at https://github.com/rpldy/react-uploady
- `yarn`
- Edit the root `tsconfig.json` so that `"module": "System"`
- Run `cypress open`

This was introduced in Cypress 4.4.0 and it likely related to our out-of-the-box TypeScript support https://github.com/cypress-io/cypress/pull/5906

This project has no TypeScript files in `cypress` that it's running, so this is especially confusing as an error. cc @sainthkh 

Full error:

```
/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/exception.js:1
System.register([], function (exports_1, context_1) {
^

ReferenceError: System is not defined
    at Object.<anonymous> (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/exception.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module.m._compile (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.require.extensions.<computed> [as .js] (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at exports.Logger.logger.createException (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/logger.js:67:12)
    at exports.Logger.logger.defaultErrorHandler (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/logger.js:92:12)
    at exports.Logger.exitOnError (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/logger.js:62:21)
    at exports.Logger.Logger._uncaughtException (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/winston/lib/winston/logger.js:645:12)
    at process.emit (events.js:215:7)
    at processEmit (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/launcher/node_modules/signal-exit/index.js:161:32)
    at process.emit (/Users/jennifer/Library/Caches/Cypress/4.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:485:21)
    at process._fatalException (internal/process/execution.js:150:25)
```

DEBUG log: [system-not-defined.log](https://github.com/cypress-io/cypress/files/4544541/system-not-defined.log)

### Workaround

Downgrade to Cypress 4.3.0

**Comment by sainthkh** [comment]
I'll check this out.
