### ISSUE TITLE
Mochawesome(v6) & Mocha(v7) support (security update)

### ISSUE THREAD

**Issue by san-ouadghiri** [cypress-io/cypress#7219]
### Current behavior:
See https://github.com/cypress-io/cypress-example-reporters package.json for working versions.
On my code, I use as a reporter mocha and mochawesome, such as
```
    "cypress": "4.3.0",
    "mocha": "^5.2.0",
    "mochawesome": "^4.1.0"
```
This comes with the following options and works fine.
```
"reporterOptions": {
    "reportDir": "reports",
    "reportFilename": "mochawesome.json",
    "html": false,
    "json": true,
    "overwrite": false
  }
```
A simple `npm audit` will raise that mocha and mochawesome needs updates for security reasons. If I upgrade mocha en v6 though, the test exec. will stop at the first report generation (after test 1 out of n).

### Desired behavior:

See https://github.com/cypress-io/cypress-example-reporters/issues/1 (renovate bot)
Basically a support & the documentation (if necessary) & example repo update allowing us to use up-to-date mocha & mochawesome libs. As per today, this would mean a v7 mocha + v6 mochawesome (instead of v5 and v4).

#### Step to reproduce
On any working project using mochawesome (ex https://github.com/cypress-io/cypress-example-reporters)
- Update your package.json version on mocha to v6
- `npm install`
- `npx cypress run`

#### Error message
```
TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/myQaFolderPath/node_modules/mocha/lib/reporters/base.js:339:30)
    at Object.onceWrapper (events.js:300:26)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/reporter.js:247:55)
    at Object.onMocha (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/project.js:360:18)
    at Socket.<anonymous> (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/socket.js:305:32)
    at Socket.emit (events.js:210:5)
    at /myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (/myQaFolderPath/node_modules/mocha/lib/reporters/base.js:339:30)
    at Object.onceWrapper (events.js:300:26)
    at Runner.emit (events.js:215:7)
    at Reporter.emit (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/reporter.js:247:55)
    at Object.onMocha (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/project.js:360:18)
    at Socket.<anonymous> (/myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/socket.js:305:32)
    at Socket.emit (events.js:210:5)
    at /myHome/.cache/Cypress/4.3.0/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

The Test Runner unexpectedly exited via a exit event with signal SIGILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 4.3.0
```

### Versions
Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 4.3.0
Not especially browser related

**Comment by jennifer-shehane** [comment]
Can you update to the [current version of Cypress](https://on.cypress.io/changelog) and let us know if this is still happening for you.

In 4.5.0 specifically, we changed custom reporters to use the version of Mocha bundled with Cypress (mocha 7.0.1). You should be able to remove the `mocha` dependency altogether in order to use custom reporters after upgrading.

**Comment by san-ouadghiri** [comment]
Hi,
Oups. Sorry indeed, I didn't see that last release.
So I upgrade to cypress, tested, then removed mocha, tested, the updated mochawesome, tested.

It's all fine locallly & within our pipeline with the following dep
```
  "dependencies": {
    "cypress": "4.5.0",
    "mochawesome": "^6.1.1"
  },
```
No vuln. detected anymore. I'm very happy :smiley: . 

I would advice if ok for you to rename this ticket if necessary, & keep it for the example repo update.
San

**Comment by jennifer-shehane** [comment]
Opened an issue here in the `cypress-example-reporters` repo https://github.com/cypress-io/cypress-example-reporters/issues/16
