### ISSUE TITLE
Bundling wrong file initially when doing component tests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7244]
Cypress v4.5.0

I used https://github.com/bahmutov/cypress-react-unit-test/ and ran

```
DEBUG=cypress:webpack npm run cy:open
```

and noticed when clicking on a component spec that it is asking to bundle `GET /__cypress/iframes/component/basic/counter-set-state/counter-spec.js` but then I see the following error messages

```
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js +16s
  cypress:webpack webpackOptions: { resolve: { alias: { react: '/Users/gleb/git/cypress-react-unit-test/node_modules/react' } }, mode: 'development', stats: 'verbose', module: { rules: [ [Object], [Object], [Object] ] } } +1ms
  cypress:webpack watchOptions: {} +0ms
  cypress:webpack input: /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js +1ms
  cypress:webpack output: /Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/integration/component/basic/counter-set-state/counter-spec.js +0ms
  cypress:webpack watching +145ms
  cypress:webpack compile /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js +2ms
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/support/index.js +17ms
  cypress:webpack webpackOptions: { resolve: { alias: { react: '/Users/gleb/git/cypress-react-unit-test/node_modules/react' } }, mode: 'development', stats: 'verbose', module: { rules: [ [Object], [Object], [Object] ] }, entry: [ '/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js' ], output: { path: '/Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/integration/component/basic/counter-set-state', filename: 'counter-spec.js' }, devtool: 'inline-source-map' } +0ms
  cypress:webpack watchOptions: {} +1ms
  cypress:webpack input: /Users/gleb/git/cypress-react-unit-test/cypress/support/index.js +0ms
  cypress:webpack output: /Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/support/index.js +0ms
  cypress:webpack watching +4ms
  cypress:webpack compile /Users/gleb/git/cypress-react-unit-test/cypress/support/index.js +0ms
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +5ms
  cypress:webpack webpackOptions: { resolve: { alias: { react: '/Users/gleb/git/cypress-react-unit-test/node_modules/react' } }, mode: 'development', stats: 'verbose', module: { rules: [ [Object], [Object], [Object] ] }, entry: [ '/Users/gleb/git/cypress-react-unit-test/cypress/support/index.js' ], output: { path: '/Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/support', filename: 'index.js' }, devtool: 'inline-source-map' } +0ms
  cypress:webpack watchOptions: {} +0ms
  cypress:webpack input: /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +0ms
  cypress:webpack output: /Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/component/basic/counter-set-state/counter-spec.js +1ms
  cypress:webpack watching +2ms
  cypress:webpack compile /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +0ms
  cypress:webpack stats had error(s) +138ms
  cypress:webpack errored bundling /Users/gleb/Library/Application Support/Cypress/cy/production/projects/cypress-react-unit-test-3d4057e937d798d828e0b355d0057df4/bundles/cypress/integration/component/basic/counter-set-state/counter-spec.js Webpack Compilation Error
multi ./cypress/integration/component/basic/counter-set-state/counter-spec.js
Module not found: Error: Can't resolve '/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js' in '/Users/gleb/git/cypress-react-unit-test'
resolve '/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js' in '/Users/gleb/git/cypress-react-unit-test'
  using description file: /Users/gleb/git/cypress-react-unit-test/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/gleb/git/cypress-react-unit-test/package.json (relative path: ./cypress/integration/component/basic/counter-set-state/counter-spec.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.json doesn't exist
      as directory
        /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js doesn't exist
[/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js]
[/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.wasm]
[/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.mjs]
[/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.js]
[/Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js.json]
 @ multi ./cypress/integration/component/basic/counter-set-state/counter-spec.js main[0] +1ms
```

and then it is asking to bundle again

```
GET /__cypress/tests?p=cypress/component/basic/counter-set-state/counter-spec.js-250 - - ms - -
GET /__cypress/iframes/component/basic/counter-set-state/counter-spec.js 200 0.918 ms - 787
GET /__cypress/runner/popper.js.map 404 0.649 ms - 136
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/support/index.js +409ms
  cypress:webpack already have bundle for /Users/gleb/git/cypress-react-unit-test/cypress/support/index.js +0ms
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +1ms
  cypress:webpack already have bundle for /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +0ms
GET /__cypress/tests?p=cypress/support/index.js-864 200 302.270 ms - -
```

So something is wrong there. It is asking for file `./cypress/integration/component/basic/counter-set-state/counter-spec.js` and it should be `./cypress/component/basic/counter-set-state/counter-spec.js` (no "integration" folder)

**Comment by bahmutov** [comment]
1. Why is it asking for counter-spec.js iframe 3 times? I cannot see response from 1st and 2nd request at all

<img width="1315" alt="Screen Shot 2020-05-06 at 1 27 03 PM" src="https://user-images.githubusercontent.com/2212006/81208627-5b24d780-8f9d-11ea-962d-6bc38a03fc1f.png">

2. The third request shows correct spec path

<img width="1315" alt="Screen Shot 2020-05-06 at 1 25 55 PM" src="https://user-images.githubusercontent.com/2212006/81208657-67109980-8f9d-11ea-95b0-cda1dfa46b81.png">

**Comment by bahmutov** [comment]
I see similar triple request in normal integration specs too

<img width="1317" alt="Screen Shot 2020-05-06 at 1 29 28 PM" src="https://user-images.githubusercontent.com/2212006/81208846-a939db00-8f9d-11ea-8cf4-923746a06fcc.png">

**Comment by bahmutov** [comment]
Seeing more debug messages
```
GET /__cypress/iframes/component/basic/counter-set-state/counter-spec.js 200 8.641 ms - 992
GET /__cypress/runner/fonts/fa-solid-900.woff2 200 3.748 ms - 76120
  cypress:server:preprocessor getting file cypress/integration/component/basic/counter-set-state/counter-spec.js +0ms
  cypress:server:preprocessor getFile /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js +0ms
  cypress:webpack get /Users/gleb/git/cypress-react-unit-test/cypress/integration/component/basic/counter-set-state/counter-spec.js +32s
```

**Comment by bahmutov** [comment]
Hmm, seems the iframe has the right urls

```
  cypress:server:controllers handle iframe { test: 'component/basic/counter-set-state/counter-spec.js' } +0ms
  cypress:server:controllers get specs { spec: 'component/basic/counter-set-state/counter-spec.js' } +1ms
  cypress:server:controllers converted component/basic/counter-set-state/counter-spec.js to /Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js +1ms
  cypress:server:controllers test url for file { file: 'cypress/component/basic/counter-set-state/counter-spec.js', url: '/__cypress/tests?p=cypress/component/basic/counter-set-state/counter-spec.js' } +0ms
  cypress:server:controllers test url for file { file: 'cypress/support/index.js', url: '/__cypress/tests?p=cypress/support/index.js' } +1ms
  cypress:server:controllers iframe component/basic/counter-set-state/counter-spec.js options { title: 'component/basic/counter-set-state/counter-spec.js', domain: 'localhost', scripts: '[{"absolute":"/Users/gleb/git/cypress-react-unit-test/cypress/support/index.js","relative":"cypress/support/index.js","relativeUrl":"/__cypress/tests?p=cypress/support/index.js"},{"absolute":"/Users/gleb/git/cypress-react-unit-test/cypress/component/basic/counter-set-state/counter-spec.js","relative":"cypress/component/basic/counter-set-state/counter-spec.js","relativeUrl":"/__cypress/tests?p=cypress/component/basic/counter-set-state/counter-spec.js"}]' } +1ms
GET /__cypress/iframes/component/basic/counter-set-state/counter-spec.js 200 5.822 ms - 992
```

**Comment by bahmutov** [comment]
Hmm, have hard time figuring out where "integration" part is coming from, finally adding throwing an error

```
 cypress:server:preprocessor getting file cypress/integration/component/basic/counter-set-state/counter-spec.js +0ms
Error: stop
    at Object.getFile (/Users/gleb/git/cypress/packages/server/lib/plugins/preprocessor.coffee:74:11)
    at Socket.watchTestFileByPath (/Users/gleb/git/cypress/packages/server/lib/socket.js:103:25)
    at Socket.<anonymous> (/Users/gleb/git/cypress/packages/server/lib/socket.js:291:14)
    at Socket.emit (events.js:210:5)
    at /Users/gleb/git/cypress/packages/socket/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Yeah, this looks like the problem area

```
// TODO: clean this up by sending the spec object instead of
  // the url path
  watchTestFileByPath (config, originalFilePath, options) {
    // files are always sent as integration/foo_spec.js
    // need to take into account integrationFolder may be different so
    // integration/foo_spec.js becomes cypress/my-integration-folder/foo_spec.js
    debug('watch test file %o', originalFilePath)
    let filePath = path.join(config.integrationFolder, originalFilePath.replace(`integration${path.sep}`, ''))

    filePath = path.relative(config.projectRoot, filePath)

    // bail if this is special path like "__all"
    // maybe the client should not ask to watch non-spec files?
    if (isSpecialSpec(filePath)) {
      return
    }
```
