### ISSUE TITLE
Flaky internal test - ENOENT: no such file or directory, ensureSymlink '/root/.config/Cypress/cy'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7272]
### Current behavior:

We are having our driver tests fail occasionally with the error below. 

Failed run: https://circleci.com/gh/cypress-io/cypress/317956#tests/containers/3

This seems to be throwing from within the `server/lib/util/app_data.js` file here:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/app_data.js#L80:L80

This specific section of code has not changed in a while. I don't recall seeing this error appear before yesterday. I couldn't find any occurrences of the error before then from old CI logs.

This recent PR seems relevant to symlinks though: https://github.com/cypress-io/cypress/commit/d69c1d184f8ec7fa8969766098ee3c74dae49450

```
$ node ../../scripts/cypress run --project ./test --record --parallel --group 5x-driver-firefox --browser firefox
Unhandled rejection Error: ENOENT: no such file or directory, ensureSymlink '/root/.config/Cypress/cy'
    at Object.ret [as ensureSymlinkAsync] (<anonymous>:8:21)
    at Object.symlink (/root/cypress/packages/server/lib/util/app_data.js:80:15)
    at /root/cypress/packages/server/lib/util/app_data.js:63:34
    at CB (/root/cypress/node_modules/fs-extra/lib/remove/rimraf.js:57:5)
    at /root/cypress/node_modules/fs-extra/lib/remove/rimraf.js:81:14
    at callback (/root/cypress/node_modules/graceful-fs/polyfills.js:295:20)
    at callback (/root/cypress/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:158:21)
From previous event:
    at ensure (/root/cypress/packages/server/lib/util/app_data.js:60:8)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.ensure (/root/cypress/packages/server/lib/util/app_data.js:70:11)
    at Object.start (/root/cypress/packages/server/lib/cypress.js:146:39)
    at launchOrFork (/root/cypress/packages/server/index.js:53:45)
    at Object.<anonymous> (/root/cypress/packages/server/index.js:56:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/cypress/scripts/start.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

![Screen Shot 2020-05-08 at 11 35 42 AM](https://user-images.githubusercontent.com/1271364/81372405-4de42600-9120-11ea-8516-d23987477710.png)

### Versions

`develop` branch pre-release 4.6.0

**Comment by jennifer-shehane** [comment]
Another failure: https://circleci.com/gh/cypress-io/cypress/322571#tests/containers/3

**Comment by flotwig** [comment]
Another one: https://circleci.com/gh/cypress-io/cypress/354967#tests/containers/2

**Comment by flotwig** [comment]
This might not be limited to internal tests, this sounds like the same error message (down to the path and everything) as https://github.com/cypress-io/cypress/issues/4167

**Comment by jennifer-shehane** [comment]
Closed in https://github.com/cypress-io/cypress/pull/7625
