### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by justguy** [cypress-io/cypress#7293]
### Current behavior:

```
cypress:server:cypress exiting with err ReferenceError: define is not defined
    at Object.<anonymous> (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\routes.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module.m._compile (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\node_modules\ts-node\src\index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\node_modules\ts-node\src\index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Server.createRoutes (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:157:14)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:200:17
From previous event:
    at Server.open (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:178:28)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\project.js:133:26
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Project.open (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\project.js:132:8)
    at Object.create (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\open_project.js:320:26)
    at openProjectCreate (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:594:4)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:610:12
    at FSReqCallback.oncomplete (fs.js:146:23)
From previous event:
    at createAndOpenProject (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:607:4)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:1349:14
    at processImmediate (internal/timers.js:439:21) +10s
define is not defined
ReferenceError: define is not defined
    at Object.<anonymous> (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\routes.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module.m._compile (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\node_modules\ts-node\src\index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\node_modules\ts-node\src\index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\override_require.js:18:25)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Server.createRoutes (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:157:14)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:200:17
From previous event:
    at Server.open (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\server.js:178:28)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\project.js:133:26
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Project.open (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\project.js:132:8)
    at Object.create (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\open_project.js:320:26)
    at openProjectCreate (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:594:4)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:610:12
    at FSReqCallback.oncomplete (fs.js:146:23)
From previous event:
    at createAndOpenProject (C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:607:4)
    at C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\modes\run.js:1349:14
    at processImmediate (internal/timers.js:439:21)
**C:\Users\adile\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\exception.js:1
define(["require", "exports"], function (require, exports) {
^**
```

### Desired behavior:

cypress should run properly.

### Test code to reproduce

Unable to run any tests because cypress open / cypress run throw the same exception.

### Versions

Cypress 4.5

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. We have a *lot* of tests around Cypress, so this is likely specific to your tests, your setup, your config, or your environment you are running within. Please provide all this information.
