### ISSUE TITLE
Flaky internal test: e2e iframes passes [firefox]

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7322]
### Current behavior:

I see this test fail sometimes in the server e2e tests within firefox. 

**Failing CI**: https://circleci.com/gh/cypress-io/cypress/323407
**Test Code**: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/2_iframe_spec.coffee#L69:L69
**Spec Code**: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/support/fixtures/projects/e2e/cypress/integration/iframe_spec.coffee#L25:L25

![Screen Shot 2020-05-13 at 2 48 08 PM](https://user-images.githubusercontent.com/1271364/81788598-cc7a0280-9528-11ea-9a89-1e13961fb915.png)

```
  1) e2e iframes passes [firefox]:

      expected exit code
      + expected - actual

      -1
      +0
      
      at /root/cypress/packages/server/test/support/helpers/e2e.js:613:25
      at maybeVerifyExitCode (test/support/helpers/e2e.js:370:10)
      at exit (test/support/helpers/e2e.js:612:7)
      at copyDirItems (/root/cypress/node_modules/fs-extra/lib/copy/copy.js:151:21)
      at /root/cypress/node_modules/fs-extra/lib/copy/copy.js:145:12
      at go$readdir$cb (/root/cypress/node_modules/graceful-fs/graceful-fs.js:195:14)
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at Object.exec (test/support/helpers/e2e.js:721:6)
      at execFn (test/support/helpers/e2e.js:341:20)
      at Object.onRun (test/support/helpers/e2e.js:305:14)
      at Context.<anonymous> (test/support/helpers/e2e.js:344:22)
```

Looks like ffmpeg is exiting here with code 1 after warning that the video recording failed. 

```
Error: ffmpeg exited with code 1: pipe:0: Function not implemented
```

```
  iframes
GET /insert_iframe 200 0.713 ms - 257
GET /insert_iframe 200 0.228 ms - 257
    ✓ can snapshot iframes which arent loaded (350ms)
GET /timeout - - ms - -
GET / 200 0.312 ms - 57
GET / 200 0.288 ms - 57
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/root/cypress/node_modules/fluent-ffmpeg/lib/processor.js:25:1)
    at ChildProcess.emit (events.js:25:1)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:25:1)

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/root/cypress/node_modules/fluent-ffmpeg/lib/processor.js:25:1)
    at ChildProcess.emit (events.js:25:1)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:25:1)

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/root/cypress/node_modules/fluent-ffmpeg/lib/processor.js:25:1)
    at ChildProcess.emit (events.js:25:1)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:25:1)

    1) passes [firefox]

  e2e images
    - passes [electron]
    - passes [chrome]
----------------------------------------
     e2e images / passes [firefox]     
----------------------------------------
```

### Versions

4.5.0

**Comment by fabianaapateanu** [comment]
Hello, I have started having this issue on FF 81, cypress base 14.10. Previously I used base 14.7 and FF 75 and it did not happen at all. Cypress version used by me is 14.12.1. We run the tests on CI based on a docker image in which we set the cypress base and the desired chrome & ff versions. Now, my tests on the CI are interrupted frequently by this error, only a part of my many spec files are executed.

**Comment by jennifer-shehane** [comment]
This issue is related to our internal Cypress tests - not a user facing issue. I don't think this issue occurs anymore in our test suite either, so I'll be closing the issue.

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.
