### ISSUE TITLE
Flaky internal test: e2e plugins fails when there is an async error at the root [chrome] 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7323]
### Current behavior:

See this internal test fail sometimes. e2e plugins fails when there is an async error at the root [chrome] - fails when there is an async error at the root [chrome]

Looks like this was added a week ago in https://github.com/cypress-io/cypress/pull/7230 with a relevant [comment](https://github.com/cypress-io/cypress/pull/7230/files#r420345661) from @chrisbreiding 

>This is a related test that was skipped before because it was flaky. I think I have it more reliable now.

**CircleCI Failure**: https://circleci.com/gh/cypress-io/cypress/323426
**Test Code**: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/3_plugins_spec.js#L32:L32

![Screen Shot 2020-05-13 at 2 54 41 PM](https://user-images.githubusercontent.com/1271364/81789231-b1f45900-9529-11ea-9f75-84f841c6ba94.png)

```
Error: Different value of snapshot "e2e plugins / fails when there is an async error at the root"

----------
Difference
----------
-
-====================================================================================================
-
-  (Run Starting)
-
-  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
-  │ Cypress:    1.2.3                                                                              │
-  │ Browser:    FooBrowser 88                                                                      │
-  │ Specs:      1 found (app_spec.js)                                                              │
-  │ Searched:   cypress/integration/app_spec.js                                                    │
-  └────────────────────────────────────────────────────────────────────────────────────────────────┘
-
-
-────────────────────────────────────────────────────────────────────────────────────────────────────
-                                                                                                    
-  Running:  app_spec.js                                                                     (1 of 1)
-
 The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/foo/bar/.projects/plugins-root-async-error/cypress/plugins/index.js`)
 
  Error: Root async error from plugins file
-      [stack trace lines]
-
-  (Results)
-
-  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
-  │ Tests:        0                                                                                │
-  │ Passing:      0                                                                                │
-  │ Failing:      1                                                                                │
-  │ Pending:      0                                                                                │
-  │ Skipped:      0                                                                                │
-  │ Screenshots:  0                                                                                │
-  │ Video:        false                                                                            │
-  │ Duration:     X seconds                                                                        │
-  │ Spec Ran:     app_spec.js                                                                      │
-  └────────────────────────────────────────────────────────────────────────────────────────────────┘
-
-
-====================================================================================================
-
-  (Run Finished)
-
-
-       Spec                                              Tests  Passing  Failing  Pending  Skipped  
-  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
-  │ ✖  app_spec.js                              XX:XX        -        -        1        -        - │
-  └────────────────────────────────────────────────────────────────────────────────────────────────┘
-    ✖  1 of 1 failed (100%)                     XX:XX        -        -        1        -        -  
-
+      [stack trace lines]
-------------------
Saved snapshot text
-------------------

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    1.2.3                                                                              │
  │ Browser:    FooBrowser 88                                                                      │
  │ Specs:      1 found (app_spec.js)                                                              │
  │ Searched:   cypress/integration/app_spec.js                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  app_spec.js                                                                     (1 of 1)

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/foo/bar/.projects/plugins-root-async-error/cypress/plugins/index.js`)

 Error: Root async error from plugins file
      [stack trace lines]

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     X seconds                                                                        │
  │ Spec Ran:     app_spec.js                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  app_spec.js                              XX:XX        -        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     XX:XX        -        -        1        -        -  

------------
Current text
------------
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/foo/bar/.projects/plugins-root-async-error/cypress/plugins/index.js`)

 Error: Root async error from plugins file
      [stack trace lines]
--------
Diff end
--------

    at /root/cypress/node_modules/snap-shot-core/src/file-system.js:263:11
    at InternalConstructor.orElse (/root/cypress/node_modules/folktale/result/result.js:187:14)
    at raiseIfDifferent (/root/cypress/node_modules/snap-shot-core/src/file-system.js:254:10)
    at setOrCheckValue (/root/cypress/node_modules/snap-shot-core/src/index.js:367:7)
    at core (/root/cypress/node_modules/snap-shot-core/src/index.js:388:12)
    at snapshot (/root/cypress/node_modules/snap-shot-it/src/index.js:293:18)
    at exit (test/support/helpers/e2e.js:657:11)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.exec (test/support/helpers/e2e.js:721:6)
    at execFn (test/support/helpers/e2e.js:341:20)
    at Object.onRun (test/support/helpers/e2e.js:305:14)
    at Context.<anonymous> (test/support/helpers/e2e.js:344:22)
```

### Versions

4.5.0

**Comment by jennifer-shehane** [comment]
Released.

This comment thread has been locked as resolved.
