### ISSUE TITLE
Flaky internal test: e2e spec_isolation fails [firefox] - fails [firefox]

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7326]
### Current behavior:

There's a test that occasionally fails in our internal tests in Firefox. 

**Circle Failure**: https://circleci.com/gh/cypress-io/cypress/323487
**Test Code**: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/5_spec_isolation_spec.coffee#L216:L216

<img width="860" alt="Screen Shot 2020-05-13 at 5 38 33 PM" src="https://user-images.githubusercontent.com/1271364/81805335-aceed400-9540-11ea-8064-c68922bb38ff.png">

```
  1) e2e spec_isolation fails [firefox]:
     AssertionError: expected 700 to be within 543..693
      at expectDurationWithin (test/e2e/5_spec_isolation_spec.coffee:42:19)
      at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:88:5
      at Array.forEach (<anonymous>:null:null)
      at expectRunsToHaveCorrectStats (test/e2e/5_spec_isolation_spec.coffee:78:8)
      at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:227:11
      at /root/cypress/node_modules/jsonfile/index.js:43:5
      at /root/cypress/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  From previous event:
      at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:178:10
      at copyDirItems (/root/cypress/node_modules/fs-extra/lib/copy/copy.js:151:21)
      at /root/cypress/node_modules/fs-extra/lib/copy/copy.js:163:14
      at /root/cypress/node_modules/graceful-fs/polyfills.js:243:20
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at Object.onRun (test/e2e/5_spec_isolation_spec.coffee:174:8)
      at Context.<anonymous> (test/support/helpers/e2e.js:344:22)
```

### Versions

4.5.0

**Comment by jennifer-shehane** [comment]
Closed by https://github.com/cypress-io/cypress/pull/7355
