### ISSUE TITLE
Cannot open chrome 

### ISSUE THREAD

**Issue by praveendvd** [cypress-io/cypress#7329]
### Current behavior:

![image](https://user-images.githubusercontent.com/45095911/81817139-2b894880-9524-11ea-8c61-c3836775505c.png)

Stack Trace:

**Message:** We could not identify a known browser at the path you provided: `C:\Users\xx\AppData\Local\Google\Chrome\Application\chrome.exe`

The output from the command we ran was:

**Details:** Version=81.0.4044.138

**Stack trace:**
```
[object Object]
    at get (C:\Users\xx\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\errors.js:348:11)
    at Object.throwErr [as throw] (C:\Users\xx\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\errors.js:363:11)
    at C:\Users\xx\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\lib\browsers\index.js:119:28
From previous event:
    at fn (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88145:14)
    at ipcBus (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88164:10)
    at Object.ipc.<computed> [as openProject] (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88205:69)
    at Object.openProject (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:90620:67)
    at Project.componentDidMount (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:90201:78)
    at ik (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75003:360)
    at ../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75103:437)
    at fg (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74872:325)
    at Yj (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74996:437)
    at Lj (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74975:420)
    at file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74873:115
    at ../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75103:437)
    at fg (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74872:325)
    at ig (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74873:61)
    at jg (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74872:496)
    at bk (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74976:156)
    at reactionScheduler (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:48544:47)
    at runReactions (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:48520:5)
    at endBatch (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:48220:9)
From previous event:
    at App.componentDidMount (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:86166:77)
    at ik (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75003:360)
    at ../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75103:437)
    at fg (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74872:325)
    at Yj (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74996:437)
    at Lj (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74975:420)
    at Rg (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74966:137)
    at rk (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75031:43)
    at file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75034:301
    at ck (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:74976:210)
    at zk (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75034:287)
    at render (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:75038:416)
    at Object.start (file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/app.js:88777:61)
    at file:///C:/Users/xx/AppData/Local/Cypress/Cache/4.5.0/Cypress/resources/app/packages/desktop-gui/dist/index.html:29:11
```

### Desired behavior:

Should detect chrome in the specified path

### Test code to reproduce

cypress open --browser <path>
cypress open --browser=<path>
cypress open --browser "<path>"
cypress open --browser="<path>"

### Versions

Cypress package version: 4.5.0
Cypress binary version: 4.5.0

Windows 10 :

**Comment by jennifer-shehane** [comment]
You shouldn't need to pass a path for the `browser` command, Cypress attempts to automatically detect where it is installed after passing `--browser chrome`. 

If you need to pass a path, please follow the directions outlined here: https://on.cypress.io/troubleshooting#Launching-browsers

**Comment by praveendvd** [comment]
> You shouldn't need to pass a path for the `browser` command, Cypress attempts to automatically detect where it is installed after passing `--browser chrome`.
> 
> If you need to pass a path, please follow the directions outlined here: https://on.cypress.io/troubleshooting#Launching-browsers

Hi Jennifer , chrome is not installed inside program files where the default search looks for . So I have to provide the path but it fails

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
