### ISSUE TITLE
Flaky internal test: e2e spec_isolation fails [firefox]  "expected XXX to be within 511..711"

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7411]
### Current behavior:

I see this internal test occasionally fail in Firefox.

**CircleCI failure**: https://circleci.com/gh/cypress-io/cypress/330290
**Test code**: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/5_spec_isolation_spec.coffee#L216:L216

<img width="915" alt="Screen Shot 2020-05-19 at 2 34 37 PM" src="https://user-images.githubusercontent.com/1271364/82301415-3d646300-99de-11ea-9f50-8dde140fac84.png">

```
    at expectDurationWithin (test/e2e/5_spec_isolation_spec.coffee:42:19)
    at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:96:5
    at Array.forEach (<anonymous>:null:null)
    at expectRunsToHaveCorrectStats (test/e2e/5_spec_isolation_spec.coffee:78:8)
    at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:227:11
    at /root/cypress/node_modules/jsonfile/index.js:43:5
    at /root/cypress/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
From previous event:
    at /root/cypress/packages/server/test/e2e/5_spec_isolation_spec.coffee:178:10
    at copyDirItems (/root/cypress/node_modules/fs-extra/lib/copy/copy.js:151:21)
    at /root/cypress/node_modules/fs-extra/lib/copy/copy.js:163:14
    at /root/cypress/node_modules/graceful-fs/polyfills.js:243:20
    at FSReqCallback.oncomplete (fs.js:146:23)
From previous event:
    at Object.onRun (test/e2e/5_spec_isolation_spec.coffee:174:8)
    at Context.<anonymous> (test/support/helpers/e2e.js:344:22)
```

### Versions

4.5.0

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
