### ISSUE TITLE
cy.click() failed because Element not visible error is seen when actually it is clearly visible

### ISSUE THREAD

**Issue by iamacoderhere** [cypress-io/cypress#7462]
The button is clearly loaded and clickable. But cypress says that is not seen:

```
Timed out retrying: cy.click() failed because this element is not visible:

<span class="ladda-label">Save & ...</span>

This element <span.ladda-label> is not visible because its parent <modal.modal-open> has CSS property: overflow: hidden and an effective width and height of: 0 x 0 pixels.
```

![image](https://user-images.githubusercontent.com/24894023/82694421-d5817700-9c80-11ea-90a0-99190c626856.png)

**Comment by iamacoderhere** [comment]
Stacktrace :

  at Object.ensureVisibility (https://beta.ally.io/__cypress/runner/cypress_runner.js:148491:25)
    at runAllChecks (https://beta.ally.io/__cypress/runner/cypress_runner.js:137846:15)
    at retryActionability (https://beta.ally.io/__cypress/runner/cypress_runner.js:137889:17)
From previous event:
    at tryFn (https://beta.ally.io/__cypress/runner/cypress_runner.js:151731:25)
    at whenStable (https://beta.ally.io/__cypress/runner/cypress_runner.js:151772:13)
    at <unknown> (https://beta.ally.io/__cypress/runner/cypress_runner.js:151295:17)
From Your Spec Code:
    at Context.eval (cypress/integration/ally/login.js:21:65)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the HTML, CSS, JS code required with the test code to reproduce this situation. 

This may also be related to this issue, so check that issue: https://github.com/cypress-io/cypress/issues/695

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by anupekshajain** [comment]
I am facing the same error and issue
