### ISSUE TITLE
Error installing latest/recent cypress version on Windows 7

### ISSUE THREAD

**Issue by isystemsengineer** [cypress-io/cypress#7483]
### Current behavior:
(Tried on 1 Windows 7 machine)
`npm install --save-dev cypress@4.6.0`
Results in following error:

```
npm ERR! notarget No matching version found for cypress@4.6.0
```

I first tried with `npm install cypress --save-dev`
This resulted in downloading version 3.4.1 instead of a more later version.

I then tried with `npm install --save-dev cypress@4.6.0` to get the latest version.

This resulted in the following error:

```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/cypress failed
, reason: connect ETIMEDOUT 104.16.21.35:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cypress@4.6.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Output from log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'cypress@4.6.0' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session 2ea41fa5857ee1cc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/cypress failed, reason: connect ETIMEDOUT 104.16.21.35:443
8 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
9 http fetch GET 200 https://registry.npmjs.org/cypress 133123ms (from cache)
10 silly registry:manifest no matching version for cypress@4.6.0 in the cache. Forcing revalidation
11 http fetch GET 200 https://registry.npmjs.org/cypress 133096ms (from cache)
12 silly fetchPackageMetaData error for cypress@4.6.0 No matching version found for cypress@4.6.0
13 timing stage:rollbackFailedOptional Completed in 1ms
14 timing stage:runTopLevelLifecycles Completed in 268149ms
15 verbose type version
16 verbose stack cypress: No matching version found for cypress@4.6.0
16 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:65:11)
16 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
16 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
16 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
16 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
16 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
16 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
16 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
16 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
16 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
16 verbose stack     at runCallback (timers.js:705:18)
16 verbose stack     at tryOnImmediate (timers.js:676:5)
16 verbose stack     at processImmediate (timers.js:658:5)
17 verbose cwd C:\e2e
18 verbose Windows_NT 6.1.7601
19 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "cypress@4.6.0"
20 verbose node v10.15.3
21 verbose npm  v6.4.1
22 error code ETARGET
23 error notarget No matching version found for cypress@4.6.0
24 error notarget In most cases you or one of your dependencies are requesting
24 error notarget a package version that doesn't exist.
25 verbose exit [ 1, true ]
```

### Desired behavior:

Expected: 
i) The latest cypress version should get installed with `npm install cypress --save-dev` instead of version 3.4.1
ii) `npm install --save-dev cypress@version` should install the requested version.

### Test code to reproduce

On windows 7:
First try `npm install cypress --save-dev`
Once the installation finishes successfully, verify if the latest Cypress version is installed. If latest version is not installed, try to install with `npm install --save-dev cypress@4.6.0`

### Versions
Tried to install 4.6.0, and 4.4.0

**Comment by jennifer-shehane** [comment]
There is a published npm package at 4.6.0. This is not an issue with Cypress, I suggest googling to find solutions for resolving package versions with this error in npm. The below prints a published version at 4.6.0.

```
npm view cypress versions
```
