### ISSUE TITLE
Cypress crashes when run on AWS Workspace, run all specs, with Chrome

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#7484]
Cypress crashes when run on AWS Workspace, run all specs, with Chrome

When run headed, with Chrome, and run all specs, the test browser will pop open. No tests will appear on the left panel. it will hang for around 3 seconds, then everything will crash. Everything includes the browser window, the cypress agent window, and the terminal that opened the window will go back to showing a prompt. 

Terminal shows the following

```
GET /__cypress/tests?p=cypress/integration/admin/programs-and-teams.spec.ts 200 10.474 ms - -
(node:19358) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:19358) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:19618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:19618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
GET /__cypress/tests?p=cypress/integration/assignments/clone.spec.ts 200 142.455 ms - -
GET /__cypress/tests?p=cypress/integration/assignments/ecg-bypass-draft.spec.ts - - ms - -
GET /__cypress/tests?p=cypress/integration/assignments/create.spec.ts - - ms - -
GET /__cypress/tests?p=cypress/support/index.ts - - ms - -
GET /__cypress/tests?p=cypress/integration/assignments/comments.spec.ts - - ms - -
GET /__cypress/tests?p=cypress/integration/assignments/dashboard.spec.ts - - ms - -
GET /__cypress/tests?p=cypress/integration/assignments/ecg-broadcast-collection.spec.ts - - ms - -
GET /__cypress/iframes/__all 304 12.473 ms - -
GET /__cypress/tests?p=cypress/integration/admin/programs-and-teams.spec.ts 200 19.964 ms - -
GET /__cypress/tests?p=cypress/integration/assignments/blockers.spec.ts 200 21.894 ms - -
GET /__cypress/tests?p=cypress/integration/assignments/bug.assignees-not-required.spec.ts 200 21.926 ms - -
GET /__cypress/tests?p=cypress/integration/admin/resources.spec.ts 200 22.228 ms - -
write EPIPE
write EPIPE
GET /__cypress/tests?p=cypress/support/index.ts 200 18.805 ms - -
GET /__cypress/tests?p=cypress/integration/admin/users.spec.ts 200 22.229 ms - -
GET /__cypress/iframes/__all 304 21.126 ms - -
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:37:20
    at tryCatcher (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/express/lib/response.js:170:12)
    at /home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/lib/controllers/spec.js:37:20
    at tryCatcher (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/craig/.cache/Cypress/4.6.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
➜  frontend git:(OA-331-osoc-field-not-saving) 
```

### Versions

Cypress: 4.6.0

**Comment by craig-dae** [comment]
Issue no longer exists after upgrading to 4.7.0
