### ISSUE TITLE
Launching browser by path does not work when executing cypress run

### ISSUE THREAD

**Issue by damian131** [cypress-io/cypress#7569]
### Current behavior:

I'm trying to run Cypress with a path to browser's binary using following command:
`./node_modules/.bin/cypress run --browser "C:\Program Files (x86)\Google\chrome-win32\chrome.exe"`
and unfortunately it does not work and return following error each time:
> We could not identify a known browser at the path you provided: `C:\Program Files (x86)\Google\chrome-win32\chrome.exe`
> 
> The output from the command we ran was:
> 
>  Version=85.0.4162.0

Below are things that I've already tried without luck:
- pointing to few different browsers executables (Chrome, Chromium, Firefox, Edge)
- clearing the Cypress cache
- reinstalling Cypress after clearing the app data (File->View App Data)
- https://github.com/cypress-io/cypress/issues/4260#issuecomment-507767328
- https://github.com/cypress-io/cypress/issues/3645#issuecomment-470710360

What's really weird is that the following command works fine:
`./node_modules/.bin/cypress run --browser chromium`, but when pointing directly to the executable it fails.

cypress info:

> Displaying Cypress info...
> 
> Detected 4 browsers installed:
> 
> 1. Chrome
>   - Name: chrome
>   - Channel: stable
>   - Version: 83.0.4103.61
>   - Executable: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> 2. Chromium
>   - Name: chromium
>   - Channel: stable
>   - Version: 85.0.4162.0
>   - Executable: C:\Program Files (x86)\Google\chrome-win32\chrome.exe
>   - Profile: C:\Users\xyz\AppData\Roaming\Cypress\cy\production\browsers\chromium-stable
> 
> 3. Edge
>   - Name: edge
>   - Channel: stable
>   - Version: 83.0.478.44
>   - Executable: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
> 
> 4. Firefox
>   - Name: firefox
>   - Channel: stable
>   - Version: 76.0.1.7432
>   - Executable: C:\Program Files\Mozilla Firefox\firefox.exe
> 
> Note: to run these browsers, pass <name>:<channel> to the '--browser' field
> 
> Examples:
> - cypress run --browser chrome
> - cypress run --browser firefox
> 
> Learn More: https://on.cypress.io/launching-browsers
> 
> Proxy Settings: none detected
> Environment Variables: none detected
> 
> Application Data: C:\Users\xyz\AppData\Roaming\cypress\cy\development
> Browser Profiles: C:\Users\xyz\AppData\Roaming\cypress\cy\development\browsers
> Binary Caches: C:\Users\xyz\AppData\Local\Cypress\Cache
> 
> Cypress Version: 4.7.0
> System Platform: win32 (10.0.17134)
> System Memory: 68.4 GB free 50.9 GB

Logs (`set DEBUG:cypress:launcher`)

>   cypress:launcher detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ] }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ] }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary' }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox' }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ] }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ] }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: 'edge' }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary' }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta' }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: 'edge-dev' } ] +0ms
>   cypress:launcher checking one browser chrome +5ms
>   cypress:launcher looking up chrome on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ] }, exePaths: [ 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' ] } +0ms
>   cypress:launcher found C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ? true +1ms
>   cypress:launcher Version=83.0.4103.61 +126ms
>   cypress:launcher browser chrome at 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' version 83.0.4103.61 +0ms
>   cypress:launcher setting major version for {"name":"chrome","family":"chromium","channel":"stable","displayName":"Chrome","version":"83.0.4103.61","path":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"} +0ms
>   cypress:launcher browser chrome version 83.0.4103.61 major version 83 +0ms
>   cypress:launcher checking one browser chromium +0ms
>   cypress:launcher looking up chromium on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ] }, exePaths: [ 'C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe' ] } +0ms
>   cypress:launcher found C:\Program Files (x86)\Google\chrome-win32\chrome.exe ? true +1ms
>   cypress:launcher Version=85.0.4162.0 +107ms
>   cypress:launcher browser chromium at 'C:\Program Files (x86)\Google\chrome-win32\chrome.exe' version 85.0.4162.0 +0ms
>   cypress:launcher setting major version for {"name":"chromium","family":"chromium","channel":"stable","displayName":"Chromium","version":"85.0.4162.0","path":"C:\\Program Files (x86)\\Google\\chrome-win32\\chrome.exe"} +0ms
>   cypress:launcher browser chromium version 85.0.4162.0 major version 85 +0ms
>   cypress:launcher checking one browser chrome +0ms
>   cypress:launcher looking up chrome on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary' }, exePaths: [ 'C:\\Users\\xyz\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe' ] } +0ms
>   cypress:launcher found C:\Users\xyz\AppData\Local\Google\Chrome SxS\Application\chrome.exe ? false +1ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Users\\xyz\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe', exePaths: [], err: Error: Browser not installed: chrome at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher browser chrome not installed +2ms
>   cypress:launcher checking one browser firefox +0ms
>   cypress:launcher looking up firefox on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox' }, exePaths: [ 'C:\\Program Files\\Mozilla Firefox\\firefox.exe', 'C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe' ] } +0ms
>   cypress:launcher found C:\Program Files\Mozilla Firefox\firefox.exe ? true +0ms
>   cypress:launcher Version=76.0.1.7432 +108ms
>   cypress:launcher browser firefox at 'C:\Program Files\Mozilla Firefox\firefox.exe' version 76.0.1.7432 +0ms
>   cypress:launcher setting major version for {"name":"firefox","family":"firefox","channel":"stable","displayName":"Firefox","version":"76.0.1.7432","path":"C:\\Program Files\\Mozilla Firefox\\firefox.exe","info":"Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue)."} +0ms
>   cypress:launcher browser firefox version 76.0.1.7432 major version 76 +0ms
>   cypress:launcher checking one browser firefox +0ms
>   cypress:launcher looking up firefox on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ] }, exePaths: [ 'C:\\Program Files\\Firefox Developer Edition\\firefox.exe', 'C:\\Program Files (x86)\\Firefox Developer Edition\\firefox.exe' ] } +0ms
>   cypress:launcher found C:\Program Files\Firefox Developer Edition\firefox.exe ? false +1ms
>   cypress:launcher found C:\Program Files (x86)\Firefox Developer Edition\firefox.exe ? false +1ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files (x86)\\Firefox Developer Edition\\firefox.exe', exePaths: [], err: Error: Browser not installed: firefox at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files\\Firefox Developer Edition\\firefox.exe', exePaths: [], err: Error: Browser not installed: firefox at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:146:28 { notInstalled: true } } +0ms
>   cypress:launcher browser firefox not installed +0ms
>   cypress:launcher checking one browser firefox +1ms
>   cypress:launcher looking up firefox on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', info: 'Firefox support is currently in beta! You can help us continue to improve the Cypress + Firefox experience by [reporting any issues you find](https://on.cypress.io/new-issue).', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ] }, exePaths: [ 'C:\\Program Files\\Firefox Nightly\\firefox.exe', 'C:\\Program Files (x86)\\Firefox Nightly\\firefox.exe' ] } +0ms
>   cypress:launcher found C:\Program Files\Firefox Nightly\firefox.exe ? false +0ms
>   cypress:launcher found C:\Program Files (x86)\Firefox Nightly\firefox.exe ? false +0ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files (x86)\\Firefox Nightly\\firefox.exe', exePaths: [], err: Error: Browser not installed: firefox at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files\\Firefox Nightly\\firefox.exe', exePaths: [], err: Error: Browser not installed: firefox at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:146:28 { notInstalled: true } } +1ms
>   cypress:launcher browser firefox not installed +0ms
>   cypress:launcher checking one browser edge +1ms
>   cypress:launcher looking up edge on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: 'edge' }, exePaths: [ 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe' ] } +0ms
>   cypress:launcher found C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe ? true +0ms
>   cypress:launcher Version=83.0.478.44 +111ms
>   cypress:launcher browser edge at 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe' version 83.0.478.44 +0ms
>   cypress:launcher setting major version for {"name":"edge","family":"chromium","channel":"stable","displayName":"Edge","version":"83.0.478.44","path":"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"} +1ms
>   cypress:launcher browser edge version 83.0.478.44 major version 83 +0ms
>   cypress:launcher checking one browser edge +0ms
>   cypress:launcher looking up edge on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary' }, exePaths: [ 'C:\\Users\\xyz\\AppData\\Local\\Microsoft\\Edge SxS\\Application\\msedge.exe' ] } +0ms
>   cypress:launcher found C:\Users\xyz\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe ? false +1ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Users\\xyz\\AppData\\Local\\Microsoft\\Edge SxS\\Application\\msedge.exe', exePaths: [], err: Error: Browser not installed: edge at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher browser edge not installed +0ms
>   cypress:launcher checking one browser edge +0ms
>   cypress:launcher looking up edge on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta' }, exePaths: [ 'C:\\Program Files (x86)\\Microsoft\\Edge Beta\\Application\\msedge.exe' ] } +0ms
>   cypress:launcher found C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe ? false +1ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files (x86)\\Microsoft\\Edge Beta\\Application\\msedge.exe', exePaths: [], err: Error: Browser not installed: edge at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher browser edge not installed +0ms
>   cypress:launcher checking one browser edge +0ms
>   cypress:launcher looking up edge on win32 platform +0ms
>   cypress:launcher looking at possible paths... { browser: { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: 'edge-dev' }, exePaths: [ 'C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe' ] } +0ms
>   cypress:launcher found C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe ? false +0ms
>   cypress:launcher error while looking up exe, trying next exePath { exePath: 'C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe', exePaths: [], err: Error: Browser not installed: edge at Object.exports.notInstalledErr (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\errors.js:4:15) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:124:32 at step (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:32:23) at Object.next (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:13:53) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:7:71 at new Promise (<anonymous>:null:null) at __awaiter (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:3:12) at tryNextExePath (C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:118:47) at C:\Users\xyz\AppData\Local\Cypress\Cache\4.7.0\Cypress\resources\app\packages\launcher\lib\windows\index.js:130:32 { notInstalled: true } } +0ms
>   cypress:launcher browser edge not installed +1ms
> We could not identify a known browser at the path you provided: `C:\Program Files (x86)\Google\chrome-win32\chrome.exe`
> 
> The output from the command we ran was:
> 
>  Version=85.0.4162.0

### Desired behavior:

Cypress runs tests against the browser executable that is placed under a path that is being passed.

### Test code to reproduce

1. Install Cypress `npm install cypress --save-dev` (In my case it was a fresh installation)
2. `./node_modules/.bin/cypress run --browser "<browser-path>"`
3. Cypress fails with:
> We could not identify a known browser at the path you provided: `<browser-path>`
> 
> The output from the command we ran was:
> 
>  Version=<executable-version>

### Versions

Cypress: 4.7.0
OS: Windows 10 x64

**Comment by jennifer-shehane** [comment]
The path that Cypress is recognizing is `C: \Program Files(x86) \Google\chrome - win32\chrome.exe` with a space after the `C:`, did you try using that exact path?

Why do you need to run it with the path if it recognizes the browser with the `chromium` keyword?

**Comment by damian131** [comment]
Hello @jennifer-shehane,

I've tried running `./node_modules/.bin/cypress run --browser "C: \Program Files (x86) \Google\chrome - win
32\chrome.exe"` but it's still failing with same error - now it's not even recognizing the binary version.

Cypress recognizes `chromium` because I put the executable manually there (just for testing purposes). I'm trying to do it in this way because on my CI/CD I'm getting the path to the browser's executable - I have no guarantee that the browser will be installed under directories that Cypress expect it to. That's why it's the only possibility for me to move on.

I'm wondering why it's not working as expected? It looks like Cypress see the executable under the path that is being passed (because it recognizes the exe version), but for some reason it does not want to run tests against this executable.

Is it a defect? Or just a matter of configuration?

**Comment by damian131** [comment]
@jennifer-shehane can I get some assistance on this? Can you at least confirm that it's a bug or it's only a thing on my environment (I checked that on three different machines)?
