### ISSUE TITLE
Running `npm i` with an Angular project with Cypress 4.7.0 does not complete successfully

### ISSUE THREAD

**Issue by jethas-bennettjones** [cypress-io/cypress#7601]
We upgraded Cypress to 4.7.0 and in a new checkout of our repo, when we run `npm i`, we get the following error:
```
> cypress@4.7.0 postinstall E:\dev\code\components2\node_modules\cypress
> node index.js --exec install

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'pend'
Require stack:
- E:\dev\code\components2\node_modules\fd-slicer\index.js
- E:\dev\code\components2\node_modules\yauzl\index.js
- E:\dev\code\components2\node_modules\cypress\lib\tasks\unzip.js
- E:\dev\code\components2\node_modules\cypress\lib\tasks\install.js
- E:\dev\code\components2\node_modules\cypress\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\dev\code\components2\node_modules\fd-slicer\index.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\dev\code\components2\node_modules\yauzl\index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\dev\\code\\components2\\node_modules\\fd-slicer\\index.js',
    'E:\\dev\\code\\components2\\node_modules\\yauzl\\index.js',
    'E:\\dev\\code\\components2\\node_modules\\cypress\\lib\\tasks\\unzip.js',
    'E:\\dev\\code\\components2\\node_modules\\cypress\\lib\\tasks\\install.js',
    'E:\\dev\\code\\components2\\node_modules\\cypress\\index.js'
  ]
}
```

If we revert back to version 4.5.0, the problem goes away.

### Versions
npm: 6.13.7
node: v13.11.0
Cypress: 4.7.0

**Comment by jethas-bennettjones** [comment]
I just tried it with Cypress 4.6.0 and had the same issue.

**Comment by jennifer-shehane** [comment]
We haven't had any other reports of issues installing cypress in our last 3 weeks since this was released, so this is likely some kind of issue from npm or your node_modules. 

I can't recreate this in node 13.11.0, npm 6.13.7

**Comment by jethas-bennettjones** [comment]
If I work at producing a repro, would you be able to investigate the issue?

**Comment by jennifer-shehane** [comment]
@jethas-bennettjones Yes 😁
