### ISSUE TITLE
Setup Cypress binary build on Mac CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#767]
## Internal feature

Build Cypress Mac binary on Mac CI (on CircleCI?)

**Comment by bahmutov** [comment]
How to set identity
```
#codeSign /Users/distiller/test-mac-ci/cypress/build/darwin/Cypress.app
🔥 deploy error
{ Error: No identity found for signing.
    at /Users/distiller/test-mac-ci/cypress/node_modules/electron-osx-sign/sign.js:262:35
    at tryCatcher (/Users/distiller/test-mac-ci/cypress/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by bahmutov** [comment]
Hmm, cannot use just `.p12`, need to upload the mobile provisioning file too

<img width="624" alt="screen shot 2017-10-18 at 3 04 34 pm" src="https://user-images.githubusercontent.com/2212006/31737490-b48efe24-b415-11e7-9d1a-0af6ba128e53.png">

**Comment by bahmutov** [comment]
Setup Mac mini (installing Node, xcode command line tools, brew) and will use Buildkit agent

**Comment by bahmutov** [comment]
Almost, need to secure environment variables https://buildkite.com/docs/agent/securing#using-environment-hooks-for-secrets

**Comment by bahmutov** [comment]
Created in https://buildkite.com/cypress/cypress/builds/2#fba593f0-5960-48c1-8350-374e060703a5

Binary can be downloaded using URL
https://cdn.cypress.io/beta/binary/1.0.3/osx64/develop-8ae23df32952fadcfd9ae327c96f73275ac5c696-2/cypress.zip
