### ISSUE TITLE
Uncaught reroute error (Cannot read property 'updateRoute' of null) 

### ISSUE THREAD

**Issue by axleross09** [cypress-io/cypress#7670]
### Current behavior:

This is in relation to a ticket i Opened as well. https://github.com/cypress-io/cypress/issues/7669

When I set `experimentalSourceRewriting` to `false`, Page load finishes and proceeds to other steps however after `cy.visit()`, any cy commands after that encounter the error message.

![image](https://user-images.githubusercontent.com/65379921/84340202-be281080-abd2-11ea-8c4c-db2eaded8f68.png)

I can bypass the error with adding

```js
cy.on('uncaught:exception', (err, runnable) => {
  expect(err.message).to.include('updateRoute')
  done()
  return false
})
```

However, By doing so, Running the test again, the behaviour seems to be all wrong. Redirects are not working as expected anymore and had to use cy.visit instead.

This is the Stack trace log generated from Cypress Browser

```
cypress_runner.js:193190 TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read property 'updateRoute' of null

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at https://components.insites.io/insites_utilities.js:577:42
From previous event:
    at run (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:162880:19)
    at Object.cy.<computed> [as log] (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:163332:11)
    at Context.runnable.fn (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:163557:21)
    at callFn (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:102437:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:102424:7)
    at https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:168711:28
From previous event:
    at Object.onRunnableRun (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:168699:20)
    at $Cypress.action (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:159590:61)
    at Test.Runnable.run (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:167324:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:103096:10)
    at https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:103222:12
    at next (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:103005:14)
    at https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:103015:7
    at next (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:102917:14)
    at https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:102983:5
    at timeslice (https://axle-qa-core-v2.staging.oregon.platform-os.com/__cypress/runner/cypress_runner.js:96909:27) 

```

and this is the Application Code Block which i think the problem is encountered.

```js
setBreadCrumbsInterval(crumbs) {
  var insRendererEl;

  var _interval = setInterval(function () {

    try {
      insRendererEl = parent.document.querySelector('ins-renderer');
    } catch (e) {
      insRendererEl = document.querySelector('ins-renderer');
    }

    if (typeof insRendererEl.updateRoute === "function" && insRendererEl.updateRoute.toString() !== "()=>{}") {
      insRendererEl.updateRoute(crumbs, true);
      clearInterval(_interval);
    }
  }, 1000);
},
```

### Desired behavior:

Test can run smoothly and will perform the intended actions.

### Versions

Cypress 4.8, Mac OS Catalina, Chrome Version 83.0.4103.61

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
