### ISSUE TITLE
Flaky internal test: Timeout of 180000ms exceeded in 8_error_ui_spec

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7671]
### Current behavior:

**CircleCI Run** https://github.com/cypress-io/cypress-test-node-versions
**Failing test** https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/8_error_ui_spec.ts#L34:L34

<img width="1043" alt="Screen Shot 2020-06-11 at 11 23 53 AM" src="https://user-images.githubusercontent.com/1271364/84346490-17457380-abd6-11ea-8989-9e510e07765e.png">

```
  1) e2e error ui displays correct UI for errors [chrome]:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/cypress/packages/server/test/e2e/8_error_ui_spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
  

  2) e2e error ui displays correct UI for errors in custom commands [chrome]:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/cypress/packages/server/test/e2e/8_error_ui_spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

### Versions

4.8.0

**Comment by jennifer-shehane** [comment]
Released.
