### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when run test by cypress run

### ISSUE THREAD

**Issue by sergeyblohin** [cypress-io/cypress#7676]
### Current behavior:

I have testing site with shadow DOM.

```javascript
it('test', () => {
  cy
    .get('div[class="oneAppNavContainer"]')
    .find('one-appnav')
    .find('span[title="          Config"]', {includeShadowDom: true})
    .contains('          Config');
});
```

It's code work correctly when I use cypress open.

<img width="381" alt="Screenshot 2020-06-11 at 10 53 53" src="https://user-images.githubusercontent.com/61824066/84360504-d7c95800-abd2-11ea-9c90-41accd64c64e.png">

But not work when I use cypress run.

```
TypeError: Cannot read property 'length' of undefined
    at superMatcher (https://example.com/__cypress/runner/cypress_runner.js:86701:17)
    at Sizzle.select (https://example.com/__cypress/runner/cypress_runner.js:86897:44)
    at Function.Sizzle [as find] (https://example.com/__cypress/runner/cypress_runner.js:85065:9)
    at jQuery.fn.init.find (https://example.com/__cypress/runner/cypress_runner.js:87096:11)
    at find (https://example.com/__cypress/runner/cypress_runner.js:153939:31)
    at getEl (https://example.com/__cypress/runner/cypress_runner.js:154030:18)
    at getElements (https://example.com/__cypress/runner/cypress_runner.js:154058:17)
    at Context.<anonymous> (https://example.com/__cypress/runner/cypress_runner.js:154082:14)
    at Context.<anonymous> (https://example.com/__cypress/runner/cypress_runner.js:163288:21)
    at https://example.com/__cypress/runner/cypress_runner.js:162724:15
    at tryCatcher (https://example.com/__cypress/runner/cypress_runner.js:10161:23)
    at Promise._settlePromiseFromHandler (https://example.com/__cypress/runner/cypress_runner.js:8096:31)
    at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:8153:18)
    at Promise._settlePromiseCtx (https://example.com/__cypress/runner/cypress_runner.js:8190:10)
    at _drainQueueStep (https://example.com/__cypress/runner/cypress_runner.js:4872:12)
```

### Desired behavior:

What I do wrong?
### Versions

Cypress: 4.8.0
Chrome Canary 85

**Comment by jennifer-shehane** [comment]
Hey @sergeyblohin, thanks for opening an issue. Shadow DOM is experimental, so there could be an issue in your case. 

In order to look into this, we'll need a fully reproducible example so that we can see where the error is throwing from and recreate it ourselves. 

Please provide a repo with a failing test, or the application code required to run against this. Otherwise, we'll have to close the issue as there's no way forward to investigate.

**Comment by sergeyblohin** [comment]
@jennifer-shehane, thank you for responding.
I was able to find a site that exactly reproduces the defect I described.
I created a public repository: https://github.com/sergeyblohin/cypress-issue-7676
To play it, just do the following:

```bash
git clone git@github.com:sergeyblohin/cypress-issue-7676.git
cd cypress-issue-76
npm install

npm run cypress:open
# or
npm run cypress:run
```


`cypress:open` work correctly:
↓
<img width="1439" alt="cypress_open" src="https://user-images.githubusercontent.com/61824066/84529005-5dd7c280-ace9-11ea-9460-00993b63b6b0.png">

`cypress:run` returns error:
↓
```
TypeError: Cannot read property 'length' of undefined
```

**Comment by jennifer-shehane** [comment]
@sergeyblohin Thanks for providing a repro!

### Reproducible example

`cypress.json`

```json
{
  "experimentalShadowDomSupport": true
}
```

`spec.js`

```js
it('experimentalShadowDomSupport', () => {
    cy.visit('https://developer.salesforce.com/docs/component-library/overview/components');
    cy.get('componentreference-header[class="header dscVisible"]')
    .shadow()
    .find('componentreference-nav-bar[class="navigation"]')
    .should('exist');
})
```

#### `cypress open` with Electron 80

<img width="1238" alt="Screen Shot 2020-06-16 at 3 43 14 PM" src="https://user-images.githubusercontent.com/1271364/84755867-223e4080-afe8-11ea-9fbe-a694bf01297b.png">

#### `cypress run` with Electron 80 headless

<img width="976" alt="Screen Shot 2020-06-16 at 3 44 41 PM" src="https://user-images.githubusercontent.com/1271364/84756056-531e7580-afe8-11ea-8b77-848870ad3fb4.png">


```
  1) experimentalShadowDomSupport:
     TypeError: Cannot read property 'length' of undefined
      at superMatcher (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:86701:17)
      at Sizzle.select (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:86897:44)
      at Function.Sizzle [as find] (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:85065:9)
      at jQuery.fn.init.find (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:87096:11)
      at getEl (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:154039:35)
      at getElements (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:154058:17)
      at Context.<anonymous> (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:154082:14)
      at Context.<anonymous> (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:163288:21)
      at https://developer.salesforce.com/__cypress/runner/cypress_runner.js:162724:15
      at tryCatcher (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:10161:23)
      at Promise._settlePromiseFromHandler (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:8096:31)
      at Promise._settlePromise (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:8153:18)
      at Promise._settlePromiseCtx (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:8190:10)
      at _drainQueueStep (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:4872:12)
      at _drainQueue (https://developer.salesforce.com/__cypress/runner/cypress_runner.js:4861:9)
```
