### ISSUE TITLE
VSCode git pre-push hook triggers: bad option: --no-sandbox

### ISSUE THREAD

**Issue by superwesker1988** [cypress-io/cypress#7678]
### Current behavior:

When pre-push hook trigger via VSCode build-in git extension, we have the following error:
```bash
2020-06-11T14:33:53.786Z cypress:cli:cli cli starts with arguments ["/Users/xx/.nvm/versions/node/v10.16.0/bin/node","/Users/xx/repos/xxx/node_modules/xxxx/node_modules/.bin/cypress","run","--headless","--browser","chrome"]
2020-06-11T14:33:53.787Z cypress:cli NODE_OPTIONS is not set
2020-06-11T14:33:53.788Z cypress:cli:cli program parsing arguments
2020-06-11T14:33:53.793Z cypress:cli:cli running Cypress with args [ Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 19, exit: true, headless: true, browser: 'chrome' } ]
2020-06-11T14:33:53.961Z cypress:cli:cli variable-length opts parsed { args: [ '/Users/xx/.nvm/versions/node/v10.16.0/bin/node', '/Users/xx/repos/xxx/node_modules/xxxx/node_modules/.bin/cypress', 'run', '--headless', '--browser', 'chrome' ], opts: Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 19, exit: true, headless: true, browser: 'chrome' } }
2020-06-11T14:33:53.962Z cypress:cli parsed cli options { browser: 'chrome', headless: true }
2020-06-11T14:33:53.963Z cypress:cli verifying Cypress app
2020-06-11T14:33:53.964Z cypress:cli checking environment variables
2020-06-11T14:33:53.968Z cypress:cli checking if executable exists /Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app/Contents/MacOS/Cypress
2020-06-11T14:33:53.970Z cypress:cli Binary is executable? : true
2020-06-11T14:33:53.970Z cypress:cli binaryDir is  /Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app
2020-06-11T14:33:53.971Z cypress:cli Reading binary package.json from: /Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app/Contents/Resources/app/package.json
2020-06-11T14:33:53.974Z cypress:cli Found binary version 4.7.0 installed in: /Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app
2020-06-11T14:33:53.975Z cypress:cli { verified: true }
2020-06-11T14:33:53.975Z cypress:cli is Verified ? true
2020-06-11T14:33:53.976Z cypress:cli:run processing run options { browser: 'chrome', headless: true, key: null, spec: null, reporter: null, reporterOptions: null, project: '/Users/xx/repos/xxx' }
2020-06-11T14:33:53.976Z cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY
2020-06-11T14:33:53.976Z cypress:cli:run run to spawn.start args ["--run-project","/Users/xx/repos/xxx","--browser","chrome","--headed",false]
2020-06-11T14:33:53.976Z cypress:cli needs to start own Xvfb? false
2020-06-11T14:33:53.977Z cypress:cli spawning, should retry on display problem? false
2020-06-11T14:33:53.983Z cypress:cli spawning Cypress with executable: /Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app/Contents/MacOS/Cypress
2020-06-11T14:33:53.984Z cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '/Users/xx/repos/xxx', '--browser', 'chrome', '--headed', false, '--cwd', '/Users/xx/repos/xxx' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
2020-06-11T14:33:53.988Z cypress:cli piping child STDERR to process STDERR
/Users/xx/Library/Caches/Cypress/4.7.0/Cypress.app/Contents/MacOS/Cypress: bad option: --no-sandbox
2020-06-11T14:33:57.094Z cypress:cli child event fired { event: 'exit', code: 9, signal: null }
2020-06-11T14:33:57.094Z cypress:cli child event fired { event: 'close', code: 9, signal: null }
npm ERR! code ELIFECYCLE
```
(I marked some folder name to be 'x's intentionally)

### Desired behavior:

It should run Cypress test as it was trigger by git cli.

### Versions

Cypress: 4.7.0
MacOs: 10.14.5
Node Version: 10.16.0

**Comment by superwesker1988** [comment]
Can the issue caused by the fact VSCode and its extension is running on Electron?

**Comment by jennifer-shehane** [comment]
`--no-sandbox` is an argument that we pass to Electron when spawning Cypress if its running on non-Windows systems. https://github.com/cypress-io/cypress/pull/5458. 

What is the prepush hook doing exactly? Can you provide how that is setup?

**Comment by superwesker1988** [comment]
Hi @jennifer-shehane , thanks so much for the reply! Here is our setup:
1. In package.json, we have a `husky` prepush hook execute a bash script, like "./pre-push.sh"
2. In that script we have command like: ` cypress run --headless --browser chrome`

Is this info enough?

**Comment by xap5xap** [comment]
@superwesker1988 Was you able to fix this? I am having the same problem

**Comment by juanruben** [comment]
Same here

**Comment by silviuaavram** [comment]
I also have this issue in `downshift`. We have a cypress test run in the pre-commit hook. It happens when I commit from VSCode.

```
[test:cypress] /Users/savram/Library/Caches/Cypress/6.2.0/Cypress.app/Contents/MacOS/Cypress: bad option: --no-sandbox
[test:cypress] 
[test:cypress] INFO: Gracefully shutting down. Please wait...
[test:cypress] Error: Command failed with exit code 9: npm run cy:run
[test:cypress]     at makeError (/Users/savram/Documents/git-repos/downshift/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
[test:cypress]     at handlePromise (/Users/savram/Documents/git-repos/downshift/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
[test:cypress]     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[test:cypress]   command: 'npm run cy:run',
[test:cypress]   exitCode: 9,
[test:cypress]   signal: undefined,
[test:cypress]   signalDescription: undefined,
[test:cypress]   stdout: undefined,
[test:cypress]   stderr: undefined,
[test:cypress]   failed: true,
[test:cypress]   timedOut: false,
[test:cypress]   isCanceled: false,
[test:cypress]   killed: false
[test:cypress] }
[test:cypress] npm run test:cypress --silent exited with code 1
```

Let me know if I can provide more info.

**Comment by JoMiguelSantos** [comment]
I have the same exact issue with the same error while using precommit hook. Any potential fix or reason why this might be happening?

**Comment by jennifer-shehane** [comment]
I'm just not so sure this is an issue with Cypress itself, and rather the tools running it.

**Comment by BrunoSette** [comment]
same here

**Comment by bahmutov** [comment]
Just hit this problem on Mac with Cypress v7.5.0

- the test calls cy.task that tries to run another instance of Cypress via NPM module API
```js
// plugin file
const cypress = require('cypress')
module.exports = (on, config) => {
  on('task', {
    openCypress(config = {}) {
      console.log('running Cypress with config')
      console.log('%o', config)

      cypress.run(config)

      // we do not wait for the Cypress process to finish
      // because we want it to run concurrently with the current test
      return null
    },
  })
}
```

Debug log shows that both invocations use no sandbox flag. The first one works, the second fails

```
$ DEBUG=cypress:cli* npx cypress open
  cypress:cli:cli cli starts with arguments ["/Users/gleb/.nvm/versions/node/v14.16.0/bin/node","/Users/gleb/git/cypress-socketio-chat/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +87ms
  cypress:cli opening from options {"project":"/Users/gleb/git/cypress-socketio-chat"} +0ms
  cypress:cli command line arguments ["--project","/Users/gleb/git/cypress-socketio-chat"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/MacOS/Cypress +3ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app +0ms
  cypress:cli Reading binary package.json from: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli Found binary version 7.5.0 installed in: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app +2ms
  cypress:cli { verified: true } +4ms
  cypress:cli is Verified ? true +2ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli spawning Cypress with executable: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/MacOS/Cypress +4ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--project', '/Users/gleb/git/cypress-socketio-chat', '--cwd', '/Users/gleb/git/cypress-socketio-chat' ] { detached: false, stdio: 'inherit' } +1ms
  cypress:cli exporting Cypress module interface +0ms
...

running Cypress with config
{ configFile: 'cy-second-user.json' }
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +0ms
  cypress:cli checking if executable exists /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/MacOS/Cypress +2ms
  cypress:cli Binary is executable? : true +0ms
  cypress:cli binaryDir is  /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app +1ms
  cypress:cli Reading binary package.json from: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/package.json +0ms
  cypress:cli Found binary version 7.5.0 installed in: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app +1ms
  cypress:cli { verified: true } +2ms
  cypress:cli is Verified ? true +2ms
  cypress:cli:run processing run options { configFile: 'cy-second-user.json', outputPath: '/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/tmp-84381-JMh34wty5sjV', key: null, spec: null, reporter: null, reporterOptions: null, project: '/Users/gleb/git/cypress-socketio-chat' } +0ms
  cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY +0ms
  cypress:cli:run run to spawn.start args ["--run-project","/Users/gleb/git/cypress-socketio-chat","--config-file","cy-second-user.json","--output-path","/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/tmp-84381-JMh34wty5sjV"] +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? false +0ms
  cypress:cli spawning Cypress with executable: /Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/MacOS/Cypress +5ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '/Users/gleb/git/cypress-socketio-chat', '--config-file', 'cy-second-user.json', '--output-path', '/var/folders/bf/cgb7wvb905q3n6hgtjc1lqrm0000gn/T/tmp-84381-JMh34wty5sjV', '--cwd', '/Users/gleb/git/cypress-socketio-chat' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +1ms
  cypress:cli piping child STDERR to process STDERR +6ms
/Users/gleb/Library/Caches/Cypress/7.5.0/Cypress.app/Contents/MacOS/Cypress: bad option: --no-sandbox
  cypress:cli child event fired { event: 'exit', code: 9, signal: null } +53ms
  cypress:cli child event fired { event: 'close', code: 9, signal: null } +0ms
```

**Comment by scottapow** [comment]
Similar situation with our project, but with component tests. `cypress run-ct` within a husky precommit hook works fine when committing manually, but using VS Code's Source Control Commit causes this error. On Cypress 7.3.0.

**Comment by WesleySmits** [comment]
Same issue here running cypress from a Husky pre-commit hook. Everything works fine committing form the terminal but not through VSCode's Git GUI. I think the problem isn't with Cypress but rather with VSCode.

I found several threads with people having this issue with other tools than Cypress being called in the hooks.

**Comment by ilovejs** [comment]
Report not working
```
$ ELECTRON_RUN_AS_NODE=true npx cypress run --reporter mochawesome
/Users/xx/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/MacOS/Cypress: bad option: --no-sandbox
```

node v14.17.0
