### ISSUE TITLE
empty --project "" string crashes Cypress NPM CLI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#7743]
4.8.0 and develop

```
~/git/cypress on develop
$ yarn dev --project ''
yarn run v1.22.4
$ node ./scripts/start.js --project ''
s.indexOf is not a function
TypeError: s.indexOf is not a function
    at hasStrayEndQuote (/Users/gleb/git/cypress/packages/server/lib/util/args.js:20:21)
    at normalizeBackslash (/Users/gleb/git/cypress/packages/server/lib/util/args.js:30:7)
    at /Users/gleb/git/cypress/packages/server/lib/util/args.js:47:27
    at Array.forEach (<anonymous>)
    at normalizeBackslashes (/Users/gleb/git/cypress/packages/server/lib/util/args.js:45:18)
    at Object.toObject (/Users/gleb/git/cypress/packages/server/lib/util/args.js:277:15)
    at Object.start (/Users/gleb/git/cypress/packages/server/lib/cypress.js:117:27)
    at launchOrFork (/Users/gleb/git/cypress/packages/server/index.js:49:45)
    at Object.<anonymous> (/Users/gleb/git/cypress/packages/server/index.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/gleb/git/cypress/scripts/start.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Similarly, when using Cypress NPM module API

```
const cypress = require('cypress')
cypress.run({
  project: ''
})
// crash
```

The empty string params are common when interfacing with other systems, like github actions https://github.com/cypress-io/github-action/pull/163

**Comment by bahmutov** [comment]
```
$ DEBUG=cypress:server:args yarn dev --project ''
yarn run v1.22.4
$ node ./scripts/start.js --project ''
  cypress:server:args argv array: [ '/Users/gleb/.nvm/versions/node/v12.16.1/bin/node', '/Users/gleb/git/cypress/scripts/start.js', '--project' ] +0ms
  cypress:server:args argv parsed: { _: [ '/Users/gleb/.nvm/versions/node/v12.16.1/bin/node', '/Users/gleb/git/cypress/scripts/start.js' ], project: true, invokedFromCli: false, cwd: '/Users/gleb/git/cypress/packages/server' } +7ms
s.indexOf is not a function
TypeError: s.indexOf is not a function
```

**Comment by bahmutov** [comment]
The CLI passes an empty string
```
cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '', '--cwd', '/Users/gleb/git/cypress-test-tiny' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] }
```
