### ISSUE TITLE
Flaky internal test: 8_error_ui "number of passes should equal the number of failures: expected 61 to equal 63"

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#7750]
### Current behavior:

I have to rerun this test *constantly* to get it to pass. Only in Firefox.

**Failing CircleCI Run:** https://circleci.com/gh/cypress-io/cypress/368931
**Failing Test:** https://github.com/cypress-io/cypress/blob/issue-7280/packages/server/test/e2e/8_error_ui_spec.ts#L34:L34

<img width="1045" alt="Screen Shot 2020-06-18 at 12 23 02 PM" src="https://user-images.githubusercontent.com/1271364/84983438-cd710600-b15e-11ea-89f0-4979895d0da0.png">

```
  1) e2e error ui displays correct UI for errors [firefox]:

      number of passes should equal the number of failures
      + expected - actual

      -61
      +63
      
      at /root/cypress/packages/server/test/e2e/8_error_ui_spec.ts:31:96
      at /root/cypress/node_modules/graceful-fs/polyfills.js:243:20
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at Object.onRun (test/e2e/8_error_ui_spec.ts:45:27)
      at Context.<anonymous> (test/support/helpers/e2e.ts:330:28)
```

### Versions

`develop`

**Comment by jennifer-shehane** [comment]
I think this has been fixed as part of #7691
