### ISSUE TITLE
Fetching resource at '/__cypress/tests?p=cypress/e2e/...' failed

### ISSUE THREAD

**Issue by leogoesger** [cypress-io/cypress#7764]
### Current behavior:

When run a basic e2e happy path, it works fine locally, but it does not pass in CI. It is not always the same tests are failing either. Each time I run, a different test could fail for the same reason.

The error says 
> Fetching resource at '/__cypress/tests?p=cypress/e2e/login/login.ts' failed

Warning with 

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
 
    at ChildProcess.target.send (internal/child_process.js:678:16)
 
    at Object.send (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/plugins/util.js:28:25)
 
    at EventEmitter.<anonymous> (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:67:16)
 
    at EventEmitter.emit (events.js:215:7)
 
    at Object.removeFile (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/plugins/preprocessor.js:149:17)
 
    at Object.options.onBrowserClose (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/open_project.js:119:28)
 
    at EventEmitter.<anonymous> (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/index.js:213:19)
 
    at Object.onceWrapper (events.js:299:28)
 
    at EventEmitter.emit (events.js:215:7)
 
    at BrowserWindow.<anonymous> (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:368:25)
 
    at Object.onceWrapper (events.js:300:26)
 
    at BrowserWindow.emit (events.js:215:7)
 
    at tryToCall (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:27:27)
 
    at EventEmitter.kill (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/electron.js:377:20)
 
    at /root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/index.js:34:14
 
    at Promise.cancellationExecute [as _execute] (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:449:9)
 
    at Promise._resolveFromExecutor (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
 
    at new Promise (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
 
    at Object.kill [as close] (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/browsers/index.js:21:10)
 
    at Object.closeBrowser (/root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/open_project.js:271:23)
 
    at /root/.cache/Cypress/4.8.0/Cypress/resources/app/packages/server/lib/modes/run.js:1132:25
 ```

### Versions

cypress 4.8

**Comment by leogoesger** [comment]
This is solved by adding `npm i uws`. Not sure what it does, but seems to solve the problem.
