### ISSUE TITLE
Range Error :Maximum call stack size exceeded when calling scrollIntoView on shadow DOM el

### ISSUE THREAD

**Issue by rameshrc** [cypress-io/cypress#7986]
I have application with lit-html web component. When button is clicked on a test bed html, dialog (lit-html web component) appears with ok button. I am trying to hover over it. Since no solutions of hover work for me, i tried out "cypress-nhover": "1.0.0",

```js
cy.get('dialog').get('.ok-button', { includeShadowDom: true }).nhover()
```

It creates an error

```
get  .ok-button 
scrollIntoView {log: false}
RangeError
Maximum call stack size exceeded

View stack trace
 Print to console
    at Sizzle (http://localhost:8002/__cypress/runner/cypress_runner.js:85876:27)
    at Function.Sizzle.matches (http://localhost:8002/__cypress/runner/cypress_runner.js:86505:10)
    at Function.jQuery.filter (http://localhost:8002/__cypress/runner/cypress_runner.js:87883:22)
    at winnow (http://localhost:8002/__cypress/runner/cypress_runner.js:87866:22)
    at jQuery.fn.init.is (http://localhost:8002/__cypress/runner/cypress_runner.js:87919:13)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151206:16)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
    at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
```

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-139) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Very likely the nhover plugin is not handling shadow DOM. I would suggest following through with the issue you've already opened on their project: https://github.com/avallete/cypress-nhover/issues/14

If you have an example provided using solely Cypress without a plugin that causes an error when trying to trigger events on shadow dom, we'd be happy to look at it with a reproducible example provided.

**Comment by avallete** [comment]
Hi there,

With the help of @rameshrc I've been able to reproduce the error without `cypress-nhover` plugin in this [MWE](https://github.com/avallete/cypress-7986-mwe).

The issue seems to come from the [scrollIntoView](https://docs.cypress.io/api/commands/scrollintoview.html#Usage) command when used with shadowDom.

I will try to investigate on this issue when I have some free time, but if anyone has any suggestion or known related issue I any piece of information would be appreciated.

**Comment by jennifer-shehane** [comment]
@avallete Nice! Thanks for providing the example. I can see that a Maximum call stack size exceeded error is thrown when calling `scrollIntoView` here. 

`cypres.json`

```json
{
  "experimentalShadowDomSupport": true
}
```

`specs.js`	

```js
it('renders a message on button click', () => {
  cy.visit('index.html')
  cy.get('button', { includeShadowDom: true }).scrollIntoView()
})
```

`index.html`

```html
<html>
  <body>
    <element-one></element-one>

    <script type="module">
      import { LitElement, html } from 'https://unpkg.com/lit-element/lit-element.js?module'

      window.customElements.define('element-one', class extends LitElement {
        render() {
          return html`
            <button>Click me</button>
          `
        }
      })
    </script>
  </body>
</html>
```

<img width="493" alt="Screen Shot 2020-07-20 at 5 18 06 PM" src="https://user-images.githubusercontent.com/1271364/87929801-0299ac80-caad-11ea-8501-3d5f4e09e60e.png">
