### ISSUE TITLE
Test hangs when failed to get accounts.google.com

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress#7990]
when I  use cypress in docker, the test hangs. I got the blow log:
```
cypress:https-proxy received error on client browserSocket { 
  err: 
    Error: connect ETIMEDOUT 172.217.24.13:443 
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) { 
        errno: 'ETIMEDOUT', 
        code: 'ETIMEDOUT', 
        syscall: 'connect', 
        address: '172.217.24.13', 
        port: 443 
     }, 
  url: 'accounts.google.com:443' 
}
```

I found that I'm in china and I'm not able to access any google resource like `accounts.google.com`. So it failed and cypress always retried it.  so it hangs.   

what shoud I do for this issue?  why cypress need to request `accounts.google.com`?

**Comment by ycwdaaaa** [comment]
and the other error：


2020-07-15T12:20:39.513Z cypress:server:request received an error making http request { timeout: 30000, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://olauaeucwicuouz/', requestId: 'request168', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [], err: Error: getaddrinfo ENOTFOUND olauaeucwicuouz at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'olauaeucwicuouz' } }
2020-07-15T12:20:39.514Z cypress:server:request exhausted all attempts retrying request { timeout: 30000, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://olauaeucwicuouz/', requestId: 'request168', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [], err: Error: getaddrinfo ENOTFOUND olauaeucwicuouz at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'olauaeucwicuouz' } }
2020-07-15T12:20:39.514Z cypress:proxy:http Error in middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing', error: Error: getaddrinfo ENOTFOUND olauaeucwicuouz at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'olauaeucwicuouz' } }
2020-07-15T12:20:39.514Z cypress:proxy:http Entering stage { stage: 'Error' }
2020-07-15T12:20:39.514Z cypress:proxy:http Running middleware { stage: 'Error', middlewareName: 'LogError' }
2020-07-15T12:20:39.514Z cypress:proxy:http:error-middleware error proxying request { error: Error: getaddrinfo ENOTFOUND olauaeucwicuouz at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'olauaeucwicuouz' }, url: '/', headers: { host: 'olauaeucwicuouz', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36', 'accept-encoding': 'gzip' } }
2020-07-15T12:20:39.514Z cypress:proxy:http Running middleware { stage: 'Error', middlewareName: 'AbortRequest' }
2020-07-15T12:20:39.515Z cypress:proxy:http Running middleware { stage: 'Error', middlewareName: 'UnpipeResponse' }
2020-07-15T12:20:39.515Z cypress:proxy:http Running middleware { stage: 'Error', middlewareName: 'DestroyResponse' }
2020-07-15T12:20:39.515Z cypress:proxy:http Leaving stage { stage: 'Error' }

**Comment by ycwdaaaa** [comment]
the first error :

2020-07-15T12:20:37.546Z cypress:network:connect successfully connected { opts: { port: '443', host: 'clients1.google.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2020-07-15T12:20:37.547Z cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 'clients1.google.com', err: undefined }
2020-07-15T12:20:37.547Z cypress:server:util:socket_whitelist whitelisting socket { localPort: 60914 }
2020-07-15T12:20:37.551Z cypress:network:connect successfully connected { opts: { port: '443', host: 'clients1.google.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2020-07-15T12:20:37.551Z cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 'clients1.google.com', err: undefined }
2020-07-15T12:20:37.551Z cypress:server:util:socket_whitelist whitelisting socket { localPort: 33064 }
2020-07-15T12:20:37.922Z cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:201:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }, url: 'clients1.google.com:443' }
2020-07-15T12:20:37.922Z cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 60914 }
2020-07-15T12:20:37.923Z cypress:server:server Got CONNECT request from clients1.google.com:443
2020-07-15T12:20:37.923Z cypress:https-proxy Writing browserSocket connection headers { url: 'clients1.google.com:443', headLength: 0, headers: { host: 'clients1.google.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' } }
2020-07-15T12:20:37.924Z cypress:https-proxy Got first head bytes { url: 'clients1.google.com:443', head: '\u0016\u0003\u0001\u0002\u0000\u0001\u0000\u0001�\u0003\u00035�U[��j�������2yb�<Ɗ\nu�h��\\�\u00043 ��i\f���%G��]�T\u001a�\u0017�h�`\t' }
2020-07-15T12:20:37.924Z cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' }
2020-07-15T12:20:37.924Z cypress:server:server HTTPS request does not match URL: https://clients1.google.com:443 with props: { port: '80', tld: '172.27.65.237', domain: '' }
2020-07-15T12:20:37.924Z cypress:https-proxy Making connection to clients1.google.com:443
2020-07-15T12:20:37.924Z cypress:https-proxy getting proxy URL { port: 443, serverPort: 36456, sniPort: 46295, url: 'https://clients1.google.com:443' }
2020-07-15T12:20:37.925Z cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:201:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }, url: 'clients1.google.com:443' }
2020-07-15T12:20:37.925Z cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 33064 }
2020-07-15T12:20:37.925Z cypress:launcher chrome stderr: [813:828:0715/122037.922310:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -100
[813:828:0715/122037.925352:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -100
2020-07-15T12:20:37.926Z cypress:server:server Got CONNECT request from clients1.google.com:443
2020-07-15T12:20:37.926Z cypress:https-proxy Writing browserSocket connection headers { url: 'clients1.google.com:443', headLength: 0, headers: { host: 'clients1.google.com:443', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' } }
2020-07-15T12:20:37.927Z cypress:https-proxy Got first head bytes { url: 'clients1.google.com:443', head: '\u0016\u0003\u0001\u0002\u0000\u0001\u0000\u0001�\u0003\u0003RQ�N�\u0018��M��\u001e�\u0019Ah�\u0002�N�]l�&����- �|��Zy����Z�rmR�¥\n�d\u0000�' }
2020-07-15T12:20:37.927Z cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'google' }
2020-07-15T12:20:37.927Z cypress:server:server HTTPS request does not match URL: https://clients1.google.com:443 with props: { port: '80', tld: '172.27.65.237', domain: '' }
2020-07-15T12:20:37.927Z cypress:https-proxy Making connection to clients1.google.com:443
2020-07-15T12:20:37.927Z cypress:https-proxy getting proxy URL { port: 443, serverPort: 36456, sniPort: 46295, url: 'https://clients1.google.com:443' }
2020-07-15T12:20:38.164Z cypress:network:connect successfully connected { opts: { port: '443', host: 'clients1.google.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2020-07-15T12:20:38.164Z cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 'clients1.google.com', err: undefined }
2020-07-15T12:20:38.164Z cypress:server:util:socket_whitelist whitelisting socket { localPort: 33524 }
2020-07-15T12:20:38.185Z cypress:network:connect successfully connected { opts: { port: '443', host: 'clients1.google.com', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 }
2020-07-15T12:20:38.185Z cypress:https-proxy received upstreamSocket callback for request { port: '443', hostname: 'clients1.google.com', err: undefined }
2020-07-15T12:20:38.185Z cypress:server:util:socket_whitelist whitelisting socket { localPort: 33532 }
2020-07-15T12:20:38.246Z cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:201:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }, url: 'clients1.google.com:443' }
2020-07-15T12:20:38.246Z cypress:server:util:socket_whitelist whitelisted socket closed, removing { localPort: 33524 }
2020-07-15T12:20:38.246Z cypress:launcher chrome stderr: [813:828:0715/122038.246372:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -100
2020-07-15T12:20:38.250Z cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:201:27) { errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }, url: 'clients1.google.com:443' }

**Comment by ycwdaaaa** [comment]
![image](https://user-images.githubusercontent.com/18463029/87548421-0e692580-c6df-11ea-9572-0a39a3c1509c.png)

**Comment by jennifer-shehane** [comment]
Does this error occur when running against our [`cypress-example-kitchensink`](https://github.com/cypress-io/cypress-example-kitchensink) app? I'd like to rule out something specific to the application you are testing.

**Comment by ycwdaaaa** [comment]
this error did not  occur when running against cypress-example.  it is weird that it hangs only in docker, I run the same case in local is will

**Comment by jennifer-shehane** [comment]
Yeah, it must be something isolated to your application under test combined with the environment it's running within. This will be difficult to isolate without a reproducible example.

**Comment by mustafawm** [comment]
Hi @jennifer-shehane 
I started getting a similar error after switching from `axios` to native `fetch` (enabling `"experimentalFetchPolyfill": true`)
Any idea how to further debug?
```shell
cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     
at TCP.onStreamRead (internal/stream_base_commons.js:201:27) 
{ errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }, url: 'flbstorage01.blob.core.windows.net:443' } +2m
```

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
