### ISSUE TITLE
Cypress can not work with @emotion/babel-preset-css-prop

### ISSUE THREAD

**Issue by mervinjin** [cypress-io/cypress#8013]
### Current behavior:

```sh
cypress_runner.js:197677 ReferenceError: The following error originated from your test code, not from Cypress.

  > exports is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at Module../components/button/index.tsx (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:979:1)
    at __webpack_require__ (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:20:30)
    at Module../components/button/button.spec.tsx (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:186:38)
    at __webpack_require__ (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:20:30)
    at Object.0 (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:32458:18)
    at __webpack_require__ (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:20:30)
    at eval (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:84:18)
    at eval (http://localhost:58578/__cypress/tests?p=components/button/button.spec.tsx:87:10)
    at eval (<anonymous>)
From previous event:
    at Object.runScripts (http://localhost:58578/__cypress/runner/cypress_runner.js:173622:28)
    at $Cypress.onSpecWindow (http://localhost:58578/__cypress/runner/cypress_runner.js:163788:20)
```

### Desired behavior:

No error.

### Test code to reproduce

Go to https://github.com/mervinjin/cypress-test-tiny, clone it and run: 
```sh
yarn && yarn cypress:open
```

then, select `index.spec.tsx`.

### Versions

cypress: `^4.10.0`

**Comment by jennifer-shehane** [comment]
Can recreate running code from https://github.com/mervinjin/cypress-test-tiny

<img width="495" alt="Screen Shot 2020-07-20 at 11 57 53 AM" src="https://user-images.githubusercontent.com/1271364/87902672-44f8c480-ca80-11ea-986b-fa158e842ebf.png">


I can confirm that removing this line from `babel.config.json` makes the error disappear. 

```
["@emotion/babel-preset-css-prop", { "throwIfNamespace": false }]
```

**Comment by mervinjin** [comment]
Yes, but I want to use cypress with `@emotion/babel-preset-css-prop`.

**Comment by agg23** [comment]
@mervinjin, are you still encountering this issue? Your repro no longer exists and many improvements have been made to Cypress since this issue was opened. Feel free to reopen if there's still an ongoing issue.

**Comment by ngmiduc** [comment]
Hi I am still wondering how to use emotions `css` prop for component testing in cypress. The problem is that the styles passed via css prop are not used during testing.

**Comment by geoimpact** [comment]
We are facing the same issue. We are unable to apply emotion styling via css props.

babel.config.json

```
{
    "plugins": [
        "@babel/plugin-syntax-dynamic-import"
    ],
    "presets": [
        "@babel/preset-react"
    ]
}
```

form.cy.js

```
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import Form from './form';
// import { contactFormCSS } from '../marketsense/marketsense';

const contactFormCSS = css`
  padding: 5px;
  .ms-form {
    .row {
      display: flex;
      .col {
        display: flex;
        flex: 1;
        padding: 10px;
      }
    }
  }
`;

describe('<Form />', () => {
  it('renders', () => {
    // see: https://on.cypress.io/mounting-react
    // eslint-disable-next-line react/jsx-filename-extension
    const formComponents = [
      {
        name: 'email',
        required: true,
      },
      {
        name: 'phone',
        required: true,
      },
      {
        name: 'phone-custom',
        required: true,
        custom: true,
        size: 'big',
      },
      {
        name: 'email-custom',
        required: true,
        custom: true,
        size: 'big',
      },
    ];
    cy.mount(
      <div className="ms-form">
        <div css={contactFormCSS}>
          <Form formComponents={formComponents} />
        </div>
      </div>,
    );
  });
});

```
