### ISSUE TITLE
Angular 10, windows 10 - Could not find a Cypress configuration file, exiting.

### ISSUE THREAD

**Issue by alvipeo** [cypress-io/cypress#8025]
I have an angular 10 project and I wanted to use Cypress (4.10.0) for e2e testing. So I installed it on Windows 10 x64 as it's described in the docs. But now when I try to open it the first time I get:

> Could not find a Cypress configuration file, exiting.
>
>We looked but did not find a cypress.json file in this folder: E:\Documents\source\[project-folder]

Here's the log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cy'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.2
4 verbose run-script [ 'precy', 'cy', 'postcy' ]
5 info lifecycle this-is-my-prj@0.0.0~precy: this-is-my-prj@0.0.0
6 info lifecycle this-is-my-prj@0.0.0~cy: this-is-my-prj@0.0.0
7 verbose lifecycle this-is-my-prj@0.0.0~cy: unsafe-perm in lifecycle true
8 verbose lifecycle this-is-my-prj@0.0.0~cy: PATH: C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Documents\source\[myproject]\node_modules\.bin;....
9 verbose lifecycle this-is-my-prj@0.0.0~cy: CWD: E:\Documents\source\[myproject]
10 silly lifecycle this-is-my-prj@0.0.0~cy: Args: [ '/d /s /c', 'cypress run' ]
11 silly lifecycle this-is-my-prj@0.0.0~cy: Returned: code: 1  signal: null
12 info lifecycle this-is-my-prj@0.0.0~cy: Failed to exec cy script
13 verbose stack Error: this-is-my-prj@0.0.0 cy: `cypress run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid this-is-my-prj@0.0.0
15 verbose cwd E:\Documents\source\[myproject]
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "cy"
18 verbose node v12.18.2
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error this-is-my-prj@0.0.0 cy: `cypress run`
22 error Exit status 1
23 error Failed at the this-is-my-prj@0.0.0 cy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Well, the e2e test is over :/

**Comment by alvipeo** [comment]
I just also tried `ng add @briebug/cypress-schematic` and then `ng e2e`, no luck either:

```
An unhandled exception occurred: Cannot find module '@briebug/cypress-schematic/package.json'
Require stack:
- [path-to-prj]\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- [path-to-prj]\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- [path-to-prj]\node_modules\@angular\cli\models\architect-command.js
- [path-to-prj]\node_modules\@angular\cli\commands\e2e-impl.js
- [path-to-prj]\node_modules\@angular-devkit\schematics\tools\export-ref.js
- [path-to-prj]\node_modules\@angular-devkit\schematics\tools\index.js
- [path-to-prj]\node_modules\@angular\cli\utilities\json-schema.js
- [path-to-prj]\node_modules\@angular\cli\models\command-runner.js
- [path-to-prj]\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\myuser\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\myuser\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
```

**Comment by jennifer-shehane** [comment]
The original error you posted means that we could not find the `cypress.json` file at the located given. Make sure that you commit your `cypress.json` file in git so that it's available on the machine you're running on. 

The other error is being thrown from https://github.com/briebug/cypress-schematic - this is not a dependency of cypress - this seems to be a dependency with `@angular/cli` - I suggest opening an issue with one of those repos.

**Comment by alvipeo** [comment]
Wait! I followed [this guide](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opening-Cypress) and I simply did `cypress open`, and got this error. So how do I get this file initially?

**Comment by jennifer-shehane** [comment]
The log you've posted shows an error during running `cypress run`. `cypress open` should create the initial `cypress.json` file. Can you post the full output from the stdout when you run `cypress open`? Could you run `cypress open` in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

```
22 error this-is-my-prj@0.0.0 cy: `cypress run`
```

**Comment by alvipeo** [comment]
ok, I'm sorry. this time it opened chrome and created the file.

**Comment by ralyodio** [comment]
https://stackoverflow.com/questions/71890151/referenceerror-context-is-not-defined-when-using-cypress-with-testing-library-c
