### ISSUE TITLE
Angular 10, windows 10 - Could not find a Cypress configuration file, exiting.

### ISSUE THREAD

**Issue by alvipeo** [cypress-io/cypress#8038]
@jennifer-shehane closed the [original issue](https://github.com/cypress-io/cypress/issues/8025), so I have to create new one. Do not close please!

I followed this guide and I simply did cypress open, and got this error. So how do I get `cypress.json` initially? Shouldn't it be created with `cypress open`? The guide doesn't say anything else on this.

---

# Original issue

I have an angular 10 project and I wanted to use Cypress (4.10.0) for e2e testing. So I installed it on Windows 10 x64 as it's described in the docs. But now when I try to open it the first time I get:

> Could not find a Cypress configuration file, exiting.
>
>We looked but did not find a cypress.json file in this folder: E:\Documents\source\[project-folder]

Here's the log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cy'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.2
4 verbose run-script [ 'precy', 'cy', 'postcy' ]
5 info lifecycle this-is-my-prj@0.0.0~precy: this-is-my-prj@0.0.0
6 info lifecycle this-is-my-prj@0.0.0~cy: this-is-my-prj@0.0.0
7 verbose lifecycle this-is-my-prj@0.0.0~cy: unsafe-perm in lifecycle true
8 verbose lifecycle this-is-my-prj@0.0.0~cy: PATH: C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Documents\source\[myproject]\node_modules\.bin;....
9 verbose lifecycle this-is-my-prj@0.0.0~cy: CWD: E:\Documents\source\[myproject]
10 silly lifecycle this-is-my-prj@0.0.0~cy: Args: [ '/d /s /c', 'cypress run' ]
11 silly lifecycle this-is-my-prj@0.0.0~cy: Returned: code: 1  signal: null
12 info lifecycle this-is-my-prj@0.0.0~cy: Failed to exec cy script
13 verbose stack Error: this-is-my-prj@0.0.0 cy: `cypress run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid this-is-my-prj@0.0.0
15 verbose cwd E:\Documents\source\[myproject]
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "cy"
18 verbose node v12.18.2
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error this-is-my-prj@0.0.0 cy: `cypress run`
22 error Exit status 1
23 error Failed at the this-is-my-prj@0.0.0 cy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Well, the e2e test is over :/

**Comment by jennifer-shehane** [comment]
Please do not open a new issue for an existing issue. Comment on the original issue with any followup, so we can keep all of the relevant threads of information together. We will reopen if necessary. Thanks.
