### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dmytro-lymarenko** [cypress-io/cypress#8062]
### Current behavior:

Sometimes this happen and I don't know how to simulate:
![image](https://user-images.githubusercontent.com/14829154/88165221-0862cf80-cc1e-11ea-8b84-ec198973b20d.png)

the logs are these:
cypress_runner.js:198105 TypeError: Cannot read property 'split' of undefined

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Entity provider`
    at splitStack (http://localhost:3000/__cypress/runner/cypress_runner.js:174786:21)
    at stackWithLinesRemoved (http://localhost:3000/__cypress/runner/cypress_runner.js:174838:22)
    at Object.stackWithReplacementMarkerLineRemoved (http://localhost:3000/__cypress/runner/cypress_runner.js:174860:10)
    at preferredStackAndCodeFrameIndex (http://localhost:3000/__cypress/runner/cypress_runner.js:170413:23)
    at Object.enhanceStack (http://localhost:3000/__cypress/runner/cypress_runner.js:170425:31)
    at fail (http://localhost:3000/__cypress/runner/cypress_runner.js:167558:21)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:167434:14
From previous event:
    at run (http://localhost:3000/__cypress/runner/cypress_runner.js:167428:16)
    at $Cy.cy.<computed> [as viewport] (http://localhost:3000/__cypress/runner/cypress_runner.js:167854:11)
    at __stackReplacementMarker (http://localhost:3000/__cypress/runner/cypress_runner.js:166944:13)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:168079:21)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:103224:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:103211:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:173313:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:173301:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:164070:61)
    at Hook.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:171914:13)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:103726:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:103765:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:173237:16)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:173258:11
From previous event:
    at onNext (http://localhost:3000/__cypress/runner/cypress_runner.js:173255:57)
    at done (http://localhost:3000/__cypress/runner/cypress_runner.js:103164:5)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:103229:11
From previous event:
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:103227:14)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:103211:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:173313:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:173301:20)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:164070:61)
    at Hook.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:171914:13)
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:103726:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:103770:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:97696:27)

and if we go to the first link we will see this fuction:
![image](https://user-images.githubusercontent.com/14829154/88165331-36481400-cc1e-11ea-922c-51699da2a5f2.png)

### Desired behavior:

It should not throw this error

### Test code to reproduce

sorry, I don't know how to reproduce it

cypress v4.10 and v.11

**Comment by dmytro-lymarenko** [comment]
I found out that reading cy.windows() in my case happens too fast that my app is not yet initialized all variables on window object. That is why it fails. So, my solution is to wait until window object contains all necessary values and then continue the test. I will close this issue.

**Comment by gcbw** [comment]
I vote for this to be reopened.

Seeing what i think is the same root cause since version 4.1, when cypress runner receives ws.onmessage with `data: "0{"sid":"_6zdRCwFAA5ggbT8AAAC","upgrades":[],"pingInterval":25000,"pingTimeout":5000}"` and ultimately prints "done() invoked with non-Error: overriding event with echo for testName"

now with later versions around 4.12+ i get the error you described here originally.


with 6.5+ i get "overriding event with echo for testName"

I am not using cy methods myself. i simply point cypress to a Mocha test file that tests one library that expects a browser. nothing fancy.
