### ISSUE TITLE
Encountering tagName.toLowerCase is not a function. Please help

### ISSUE THREAD

**Issue by nimmala89** [cypress-io/cypress#8191]
Hi, I'm trying to automate a web application built on Angular on the front end.
I have a form where I need to click a button.

Html Code :
![image](https://user-images.githubusercontent.com/69274496/89464420-0f1d3680-d736-11ea-949a-8c2c05ebbc33.png)

Javascript code to click :
```js
cy.get('.modal-body.container > .mat-dialog-content > :nth-child(1) > form > :nth-child(2) > :nth-child(4) > :nth-child(1) > div > a')
  .click()
```

Error in Cypress runner : 
![image](https://user-images.githubusercontent.com/69274496/89468901-0c264400-d73e-11ea-98b6-761ed422b422.png)

I do not understand why I see the `tagName.toLowerCase()` function while executing a click on the ADD BUTTON of the form page.There is no function with that name in my code.

STEPS TO REPRODUCE 

1. Login into the application
2. Navigate to the page.
3. Click to open form.
4. Click Add Context button as shown below.

Expected : The element must be clicked.

Actual : I see the error in Cypress Runner as above.

![image](https://user-images.githubusercontent.com/69274496/89464279-cf564f00-d735-11ea-9b74-833e12f41f42.png)

NOTE : 
Seems like a bug to me as I consulted my developer and there is no such method in his code.

**Comment by jennifer-shehane** [comment]
This is being thrown from within Cypress at this line, so is a bug: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/elements.ts#L357:L357

This code hasn't really been changed since 3.5.0, so it's strange that it's just now occurring as I haven't seen anyone else with this error. 

This seems to be implying that [Element.tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) is returning something other than a String (not undefined or null though). But the very definition of this is that it returns a String. 

Is there any way you can provide an example to reproduce this? Or some hints on something outside of regular DOM elements that you're using in your web application (shadow dom, web components, etc)? I can't reproduce it with the information provided which means we can't exactly track down how to go about fixing it. You can also email any info needed to reproduce to support@cypress.io if you don't want to publicly post.

**Comment by nimmala89** [comment]
Hi @jennifer-shehane , I have sent a detailed email to the address provided. Please look into it and let me know if there is a solution.

![image](https://user-images.githubusercontent.com/69274496/89495465-f3d61980-d77d-11ea-9ea9-a23562aea895.png)

Thanks !

**Comment by jennifer-shehane** [comment]
Closing as a reproducible example was never provided. 

Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by Phillipe-Bojorquez** [comment]
@jennifer-shehane When moving from cypress 4.8 to cypress 4.9-5.3 I am seeing this error.  

Previously this block of code ran and produced a result:

```it('Allows you to reselect a customer', () => {
      let initialAddress = '';
      let initialOrderId = '';

      cy.get('[data-test="button|crm-actions"]').first().click();
      cy['ll:dropdown']({ position: 3 })
      cy.wait('@getTaxes');

      // confirm the address is populated
      cy.get(selectors.addressInput)
        .invoke('val')
        .then((val) => {
          initialAddress = val;
        })
        .should('not.have.value', '');```

After upgrading to version 4.9 or attempting an upgrade to the latest I get these errors when the test runs:

It errors out on the .should() portion of the code.  I have tried getting rid of the .then and use a .should against the invoke but the same error occures.  

```Error:       TypeError: Cannot read property 'tagName' of undefined
    at getTagName (http://localhost:8000/__cypress/runner/cypress_runner.js:178614:22)
    at Module.isValueNumberTypeElement (http://localhost:8000/__cypress/runner/cypress_runner.js:178597:35)
    at Proxy.<anonymous> (http://localhost:8000/__cypress/runner/cypress_runner.js:167884:20)
    at Proxy.methodWrapper (http://localhost:8000/__cypress/runner/cypress_runner.js:80897:25)
    at applyChainer (http://localhost:8000/__cypress/runner/cypress_runner.js:154578:32)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:154632:16
    at arrayReduce (http://localhost:8000/__cypress/runner/cypress_runner.js:25494:21)
    at Function.reduce (http://localhost:8000/__cypress/runner/cypress_runner.js:34518:14)
    at applyChainers (http://localhost:8000/__cypress/runner/cypress_runner.js:154609:24)
From previous event:
    at Context.shouldFn (http://localhost:8000/__cypress/runner/cypress_runner.js:154638:23)
    at Context.should (http://localhost:8000/__cypress/runner/cypress_runner.js:154656:23)
    at Context.<anonymous> (http://localhost:8000/__cypress/runner/cypress_runner.js:169673:21)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:169097:15
From previous event:
    at runCommand (http://localhost:8000/__cypress/runner/cypress_runner.js:169076:8)
    at next (http://localhost:8000/__cypress/runner/cypress_runner.js:169222:14)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:169250:16```

**Comment by WSINTRA** [comment]
Getting same error, unable to provide a reproducible code snippet.
<img width="409" alt="Screenshot 2024-04-04 at 9 59 22 AM" src="https://github.com/cypress-io/cypress/assets/43357403/03439905-96db-4279-9b23-9de57884eb4b">

**Comment by WSINTRA** [comment]
> Getting same error, unable to provide a reproducible code snippet. <img alt="Screenshot 2024-04-04 at 9 59 22 AM" width="409" src="https://private-user-images.githubusercontent.com/43357403/319618044-03439905-96db-4279-9b23-9de57884eb4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzk0NzksIm5iZiI6MTcxMjIzOTE3OSwicGF0aCI6Ii80MzM1NzQwMy8zMTk2MTgwNDQtMDM0Mzk5MDUtOTZkYi00Mjc5LTliMjMtOWRlNTc4ODRlYjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTA5NzY4YWQ3NTVlM2VkMTQ5NWVhZDM2NWIwMTlkNTc3Y2UxY2E3Y2ZmMjhkYmVkZGFhZjcxMjc1NTc4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dWNXUdmKLLgIHtplV3-rmlplya0VUD-1zPraMAQD_w">

One thing to note. In this code I am also using the variable called tagName as a property in my codebase. Could be a reference issue.

**Comment by cacieprins** [comment]
A minimal reproduction that likely points to a root cause:

`form.html`:
```html
<!DOCTYPE html>

<body>
  <form>
    <input id="tagName" type="text" />
  </form>
</body>
```

`spec.cy.js`:
```javascript
describe('page', () => {
  it('works', () => {
    cy.visit('cypress/fixtures/form.html')

    cy.get('#tagName').should('exist')
    cy.get('form').should('exist')
  })
})
```

This is due to how inputs with IDs interact with the form element itself: All input IDs that are children of a form become properties on that `HTMLFormElement`, keyed to that id. Such that:

```javascript
const form = document.createElement('form')
console.log(form.tagName === 'FORM') // true
const input = document.createElement('input')
input.id = 'tagName'
form.appendChild(input)
console.log(form.tagName === 'FORM') // false
console.log(form.tagName === input) // true
```

The primary workaround is to not give input elements IDs that will overwrite properties of the `HTMLFormElement`, or otherwise overwrite properties of the `HTMLFormElement`.

**Comment by utkarshxplor** [comment]
Hello @jennifer-shehane - do we have any update on this issue?
