### ISSUE TITLE
Install fails due to not finding a package dependency @cypress/listr-verbose-renderer

### ISSUE THREAD

**Issue by dheerajbhaskar** [cypress-io/cypress#8198]
### Current behavior:

```
C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>npm install cypress
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cypress%2flistr-verbose-renderer - Not found
npm ERR! 404
npm ERR! 404  '@cypress/listr-verbose-renderer@^0.4.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cypress'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dheeraj\AppData\Roaming\npm-cache\_logs\2020-08-06T09_33_10_820Z-debug.log

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>npm install cypress
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cypress%2flistr-verbose-renderer - Not found
npm ERR! 404
npm ERR! 404  '@cypress/listr-verbose-renderer@^0.4.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cypress'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dheeraj\AppData\Roaming\npm-cache\_logs\2020-08-06T09_36_34_392Z-debug.log

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>cat package.json
{
  "name": "testing-partner-plugin",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git@gitlab.com:appkrt/dylan-wordpress-plugin/testing-partner-plugin.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>which yarn
INFO: Could not find files for the given pattern(s).

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>npm install -g yarn
C:\Users\Dheeraj\AppData\Roaming\npm\yarnpkg -> C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
C:\Users\Dheeraj\AppData\Roaming\npm\yarn -> C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
+ yarn@1.22.4
added 1 package in 0.678s

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>yarn add cypress --dev
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@cypress/listr-verbose-renderer@^0.4.1" required by "cypress" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@cypress/xvfb@^1.2.4" required by "cypress" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@cypress/request@^2.88.5" required by "cypress" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@samverschueren/stream-to-observable@^0.3.0" required by "listr@^0.14.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\Dheeraj\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>
```

### Desired behavior:

- That cypress installs with npm i cypress
- OR cypress installs with yarn add cypress --dev

### Test code to reproduce
These are the commands I used
```
npm init -y
git status
git add .
git commit -m "npm init
git status
git add
git add .
git commit -m "add gitignore
git push
npm i
npm install cypress
npm install cypress
cat package.json
which yarn
npm install -g yarn
yarn add cypress --dev
```

### Versions
Info gotten from about:support in firefox

```

Name | Firefox
-- | --
79.0
20200720193547
 
release
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
Windows_NT 10.0 18363
Enabled
20/20               Enabled by default
11
Inactive
Found
Found
Found
false
```

cypress version
latest: 4.12.1

C:\my-home\Projects\client-dylan-wordpress-plugin\testing-partner-plugin>node -v
v12.18.3

**Comment by iamsaumya** [comment]
I am also facing the same issue

![Screenshot from 2020-08-06 15-20-30](https://user-images.githubusercontent.com/40148448/89520214-25d99100-d7fb-11ea-9584-708a535c866a.png)

**Comment by Jmaharman** [comment]
NPM is having issues, it's not related to cypress.

https://status.npmjs.org/

**Comment by Gabalth** [comment]
It works now, npm fixed their isssue. I think you can close this

**Comment by dheerajbhaskar** [comment]
I got it fixed the following way:

I rolled back to using node v14.7.0 using nvm-windows.

PS: Good-bye 4hrs of my life

**Comment by pedrombafonso** [comment]
Having the same issue:

```
➜  ✗ npm i cypress@4.12.1
npm ERR! code E404
npm ERR! 404 Not Found - GET https://*********.com/repository/npm/@cypress%2flistr-verbose-renderer - Not found
npm ERR! 404
npm
```

**Comment by jennifer-shehane** [comment]
This does look to have been an issue with npm. Specifically on Aug 6th for a period of 2 hours:

>Issues accessing npmjs.com and installing scoped packages

<img width="421" alt="Screen Shot 2020-08-07 at 3 16 19 PM" src="https://user-images.githubusercontent.com/1271364/89627590-1fade800-d8c1-11ea-87b1-4bbc09278f0e.png">

Closing as resolved.
