### ISSUE TITLE
Bcrypt plugin file issue, Library Validation

### ISSUE THREAD

**Issue by Adam-Burke** [cypress-io/cypress#8258]
### Current behavior:

Trying to import bcrypt into the plugin file seems to be causing an issue.

```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/adam/ligr-cypress-bug-report/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: dlopen(/Users/adam/ligr-cypress-bug-report/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/adam/ligr-cypress-bug-report/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: code signature in (/Users/adam/ligr-cypress-bug-report/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/adam/ligr-cypress-bug-report/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
```

### Desired behavior:

Should run tests without showing plugin file error.

### Test code to reproduce

https://github.com/ligrsystems/cypress-test-tiny

npm run cypress:run crashes

### Versions

OSX mojave 10.14.6 
cypress 4.12.1
bcrypt 5

**Comment by Adam-Burke** [comment]
Didn't realize i could set the node version.
