### ISSUE TITLE
Cypress crashes when running against dashboard(parallel flag) - Cannot read property 'name' of undefined at runEachSpec

### ISSUE THREAD

**Issue by BadLiveware** [cypress-io/cypress#8259]
### Current behavior:
This has started to happen in the last couple of days, our last successfull run was 
Started: Aug 10, 2020 at 05:32pm
Ended: Aug 10, 2020 at 05:42pm

When running our suit of tests with the parallel flag(even if only one machine) the first test spec fails with 
```
 2020-08-12T08:49:11.597Z cypress:server:cypress exiting with err TypeError: Cannot read property 'name' of undefined
 451       at runEachSpec (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\lib\modes\run.js:1219:32)
 452       at C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\lib\modes\run.js:415:14
 453       at tryCatcher (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
 454       at Promise._settlePromiseFromHandler (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
 455       at Promise._settlePromise (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
 456       at Promise._settlePromise0 (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
 457       at Promise._settlePromises (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
 458       at _drainQueueStep (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
 459       at _drainQueue (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
 460       at Async._drainQueues (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
 461       at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\frla01\AppData\Local\Cypress\Cache\4.12.1\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
 462       at processImmediate (internal/timers.js:439:21)
 463   Cannot read property 'name' of undefined
```
Debug logs:
[cypress.debug.log](https://github.com/cypress-io/cypress/files/5061666/cypress.debug.log)

### Desired behavior:
Cypress doesnt crash

### Versions

OS: Windows Enterprise 10 - 1809 17763.1339
File: .\package.json
```json
 {
  "name": "testautomation-ia",
  "version": "1.0.0",
  "description": "testautomation",
  "main": "index.js",
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^5.4.3",
    "@types/cypress-cucumber-preprocessor": "1.14.1",
    "@types/node": "^14.0.27",
    "cypress": "^4.12.1",
    "cypress-cucumber-preprocessor": "^2.5.4",
    "cypress-plugin-retries": "1.5.2",
    "guid-typescript": "1.0.9",
    "mocha": "^7.2.0",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.7",
    "webpack": "^4.44.1"
  },
  "author": "",
  "license": "ISC",
  "cypress-cucumber-preprocessor": {
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/results/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    },
    "nonGlobalStepDefinitions": true
  },
  "dependencies": {}
}
```

**Comment by jennifer-shehane** [comment]
@BadLiveware Thank you for reporting this issue. Our API team is investigating this issue.

**Comment by jennifer-shehane** [comment]
I believe this issue may be isolated to Windows.

**Comment by SanderMeesterIndepender** [comment]
Experiencing the exact same issue. Let me know if additional info is required.

**Comment by amrwahdan3** [comment]
oh good. im not the only one....

**Comment by jennifer-shehane** [comment]
Our engineering team has released a fix for this issue - of seeing the `Cannot read property 'name' of undefined at runEachSpec` error when running in Windows OS's. 

Please comment here or open a new issue if you continue to see this issue on new runs that are recorded to the Dashboard started after this comment.

**Comment by bvanderneut** [comment]
Can it be that this bug is active again? I have the same issue as before.

**Comment by jennifer-shehane** [comment]
@bvanderneut Please open a new issue detailing the error you are seeing or email support@cypress.io with the details. We're not aware of any current issues with this error message. It's likely a new edge case.

**Comment by jennifer-shehane** [comment]
New issue opened here https://github.com/cypress-io/cypress/issues/8367
