### ISSUE TITLE
Cypress doesn't evaluate `"esModuleInterop": true` in cypress/tsconfig.json?

### ISSUE THREAD

**Issue by tanakaworld** [cypress-io/cypress#8359]
### Current behavior:

There is a plugin .ts file.

```typescript
// cypress/plugins/index.ts
import webpackPreprocessor from "@cypress/webpack-preprocessor";
import webpackOptions from "../webpack.config";

const pluginsFunction: Cypress.PluginConfig = (on) => {
  on(
    "file:preprocessor",
    webpackPreprocessor({
      webpackOptions,
    })
  );
};

export default pluginsFunction;
```

```json
// cypress/tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "suppressImplicitAnyIndexErrors": true,
    "declarationMap": true,
    "sourceMap": true,
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
    "paths": {
      "~/*": ["./*"]
    }
  },
  "exclude": ["node_modules"],
  "include": ["**/*.ts"]
}
```

Then it failed to initialize Cypress.app with the following error.

> TypeError: fork_ts_checker_webpack_plugin_1.default is not a constructor

![image](https://user-images.githubusercontent.com/3489430/90731412-9fe23d80-e304-11ea-8a19-1b83e34a4bc4.png)

```
TypeError: fork_ts_checker_webpack_plugin_1.default is not a constructor
    at Object.<anonymous> (/Users/tanakaworld/ws/github.com/tanakaworld/sandbox-cypress/cypress/webpack.config.ts:16:5)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Module.m._compile (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/tanakaworld/ws/github.com/tanakaworld/sandbox-cypress/cypress/plugins/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Module.m._compile (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:192:15)
    at Object.<anonymous> (/Users/tanakaworld/Library/Caches/Cypress/5.0.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js:8:25)
```

### Desired behavior:

It should work with `import` syntax when `"esModuleInterop": true` is in tsconfig.json.

### Test code to reproduce

The `verify/v5.0.0` branch in [this repo](https://github.com/tanakaworld/sandbox-cypress/tree/verify/v5.0.0). It reproduces the same error.

### Versions

* `cypress: v5.0.0`
* Others: https://github.com/tanakaworld/sandbox-cypress/blob/verify/v5.0.0/package.json#L20-L37.

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-278) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
I am able to recreate this behavior in 5.0.0 (although slightly different error msg).

### Repro

`package.json`

```json
{
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@cypress/webpack-preprocessor": "^5.4.4",
    "babel-loader": "^8.1.0",
    "cypress": "5.0.0",
    "typescript": "^3.9.7",
    "webpack": "^4.44.1"
  }
}
```

`cypress/plugins/index.ts`

```ts
import webpackPreprocessor from "@cypress/webpack-preprocessor";

module.exports = (on, config) => {
  on("file:preprocessor", webpackPreprocessor({}));
}
```

`cypress/tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "suppressImplicitAnyIndexErrors": true,
    "declarationMap": true,
    "sourceMap": true,
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
    "paths": {
      "~/*": ["./*"]
    }
  },
  "exclude": ["node_modules"],
  "include": ["**/*.ts"]
}
```

### 4.12.1

<img width="709" alt="Screen Shot 2020-08-20 at 2 40 39 PM" src="https://user-images.githubusercontent.com/1271364/90734077-23932e80-e2f3-11ea-86ad-a7cfd04d0cf2.png">


### 5.0.0

<img width="708" alt="Screen Shot 2020-08-20 at 2 42 31 PM" src="https://user-images.githubusercontent.com/1271364/90735093-66550680-e2f3-11ea-8510-f665584f2823.png">

**Comment by robcresswell** [comment]
This might be a bug in the webpack preprocessor itself. Its doing a namespace export of a callable, which isn't valid in ES6 modules AFAIK.

Does `import * as webpackPreprocessor from "@cypress/webpack-preprocessor";` (a namespace import) work?

**Comment by robcresswell** [comment]
The safest fix would probably be to change the preprocessor to do `export const webpackPreprocessor`, so that consumers can use a named import, which is compatible with both CJS and ESM, and then all this synthetic defaults and transpiling issue goes away.

**Comment by tanakaworld** [comment]
Thanks for your investigation!

> Does import * as webpackPreprocessor from "@cypress/webpack-preprocessor"; (a namespace import) work?

It doesn't work too.

**Comment by tanakaworld** [comment]
> @tanakaworld In the meantime, a potential workaround is to add `"esModuleInterop": true` to the `tsconfig.json` in your project root.

Thanks! I've confirmed that `tsconfig.json` in the project root works correctly 👍 .

I think this issue should be fixed because the document says:

> Configure tsconfig.json
> We recommend the following configuration in a tsconfig.json inside your cypress folder.
> https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json
