### ISSUE TITLE
Cypress crashes when running against dashboard(parallel flag) - Cannot read property 'name' of undefined at runEachSpec

### ISSUE THREAD

**Issue by Johan-Lundin** [cypress-io/cypress#8367]
### Current behavior:
Reapperance of Issue https://github.com/cypress-io/cypress/issues/8259 submitted by another of our team members

This started to happen again just now, our last successfull run was
Started: Aug 20, 2020 at 04:41pm
Ended: Aug 20, 2020 at 05:03pm

When running our suit of tests with the parallel flag(even if only one machine) the first test spec fails with
```
2020-08-20T16:03:27.9480007Z Cannot read property 'name' of undefined
2020-08-20T16:03:27.9482826Z TypeError: Cannot read property 'name' of undefined
2020-08-20T16:03:27.9484088Z     at runEachSpec (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\modes\run.js:1232:32)
2020-08-20T16:03:27.9485293Z     at C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\lib\modes\run.js:416:14
2020-08-20T16:03:27.9486303Z     at tryCatcher (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
2020-08-20T16:03:27.9488066Z     at Promise._settlePromiseFromHandler (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
2020-08-20T16:03:27.9491091Z     at Promise._settlePromise (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
2020-08-20T16:03:27.9492058Z     at Promise._settlePromise0 (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
2020-08-20T16:03:27.9492897Z     at Promise._settlePromises (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:729:18)
2020-08-20T16:03:27.9493724Z     at _drainQueueStep (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
2020-08-20T16:03:27.9494499Z     at _drainQueue (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
2020-08-20T16:03:27.9495306Z     at Async._drainQueues (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
2020-08-20T16:03:27.9496191Z     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\SVCPrevIntern\AppData\Local\Cypress\Cache\5.0.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
2020-08-20T16:03:27.9496786Z     at processImmediate (internal/timers.js:439:21)
```

### Desired behavior:

Cypress doesnt crash
### Versions

OS: Windows 10.0.17763
File: ./package.json
```json
{
  "name": "testautomation-ia",
  "version": "1.0.0",
  "description": "testautomation",
  "main": "index.js",
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^5.4.4",
    "@types/cypress-cucumber-preprocessor": "1.14.1",
    "@types/node": "^14.6.0",
    "cypress": "^5.0.0",
    "cypress-cucumber-preprocessor": "^2.5.4",
    "guid-typescript": "1.0.9",
    "mocha": "^7.2.0",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.7",
    "webpack": "^4.44.1"
  },
  "author": "",
  "license": "ISC",
  "cypress-cucumber-preprocessor": {
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/results/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    },
    "nonGlobalStepDefinitions": true
  },
  "dependencies": {}
}
```

**Comment by amrwahdan3** [comment]
Just here to say we are experiencing this too seemed to have started this morning after 11am EST

**Comment by jennifer-shehane** [comment]
Thanks for opening this issue detailing the error. I've escalated this to our API team to investigate. Sorry for the inconvenience.
