### ISSUE TITLE
unexpected error occurred while verifying the Cypress executable

### ISSUE THREAD

**Issue by TalBuch** [cypress-io/cypress#8473]
### Current behavior:
On cypress 5.0.0/5.0.1, when installing via Jenkins, cypress validation fails

### Desired behavior:
Cypress validation should not fail

Got the following error while installing cypress via jenkins (npm install):

```
Cypress 5.1.0 is installed in /home/jenkins/.cache/Cypress/5.1.0

npm WARN e2e_testing@1.0.0 No repository field.

added 223 packages from 158 contributors and audited 223 packages in 18.1s
found 0 vulnerabilities

+ npm run test

> e2e_testing@1.0.0 test /home/jenkins/workspace/e2e-automation
> cypress run --headless

It looks like this is your first time using Cypress: 5.1.0

[?25l[08:16:50]  Verifying Cypress can run /home/jenkins/.cache/Cypress/5.1.0/Cypress [started]
[08:16:50]  Verifying Cypress can run /home/jenkins/.cache/Cypress/5.1.0/Cypress [failed]
[?25hAn unexpected error occurred while verifying the Cypress executable.

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

TypeError: spawnedPromise.finally is not a function
at setupTimeout (/home/jenkins/workspace/e2e-automation/node_modules/execa/lib/kill.js:85:51)
at Object.execa [as exec] (/home/jenkins/workspace/e2e-automation/node_modules/execa/index.js:99:23)
at spawn (/home/jenkins/workspace/e2e-automation/node_modules/cypress/lib/tasks/verify.js:171:33)
at userFriendlySpawn (/home/jenkins/workspace/e2e-automation/node_modules/cypress/lib/tasks/verify.js:198:12)
at runSmokeTest (/home/jenkins/workspace/e2e-automation/node_modules/cypress/lib/tasks/verify.js:213:10)
at /home/jenkins/workspace/e2e-automation/node_modules/cypress/lib/tasks/verify.js:237:29
at tryCatcher (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/promise.js:729:18)
at Promise._fulfill (/home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/promise.js:673:18)
at /home/jenkins/workspace/e2e-automation/node_modules/bluebird/js/release/nodeback.js:42:21
at CB (/home/jenkins/workspace/e2e-automation/node_modules/fs-extra/lib/remove/rimraf.js:57:5)
at options.lstat (/home/jenkins/workspace/e2e-automation/node_modules/fs-extra/lib/remove/rimraf.js:81:14)
at callback (/home/jenkins/workspace/e2e-automation/node_modules/graceful-fs/polyfills.js:295:20)

----------

Platform: linux (Ubuntu - 14.04)
Cypress Version: 5.1.0
[?25hnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e_testing@1.0.0 test: `cypress run --headless`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2e_testing@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by TalBuch** [comment]
Any updates regarding this one?
It's a showstopper for us as we cannot use Cypress over jenkins

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
