### ISSUE TITLE
firefoxGcInterval (Must Be Fixed Order)

### ISSUE THREAD

**Issue by CScharer** [cypress-io/cypress#8576]
### Current behavior:
**Message:** We found an invalid value in the file: `cypress.json`

Expected `firefoxGcInterval` to be a positive number or null or an object with "openMode" and "runMode" as keys and positive numbers or nulls as values. Instead the value was: `{"openMode":0,"runMode":0}`

**Stack trace:**
```
Error: We found an invalid value in the file: `cypress.json`

Expected `firefoxGcInterval` to be a positive number or null or an object with "openMode" and "runMode" as keys and positive numbers or nulls as values. Instead the value was: `{"openMode":0,"runMode":0}`
    at get (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:963:15)
    at Object.throwErr [as throw] (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:981:9)
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:292:26
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:282:18
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:2990:24)
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9368:14)
    at validate (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:270:12)
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:291:12
    at tryCatcher (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/jsonfile/index.js:43:5
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:123:16
    at /Users/srs615/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

```

### Desired behavior:
Able to include json nodes in any order.
No Error.

### Test code to reproduce
cypress.json content contains
  "firefoxGcInterval": {
    "openMode": 0,
    "runMode": 0
  },

### Versions
Cypress 5.1.0, any OS, any Browser

**Comment by flotwig** [comment]
Hi @CScharer,

If your intent is to disable `firefoxGcInterval`, pass `null`. As stated in the error message, you must supply either a positive number (>0) or `null` to disable.

```json
{
	"firefoxGcInterval": null
}
````
