### ISSUE TITLE
cy.contains will throw unrecognized expression error if it tries to match against regex containing single quotation mark

### ISSUE THREAD

**Issue by LiChoi** [cypress-io/cypress#8626]
### Current behavior:

cy.contains will throw invalid expression error if you try to match a regex containing a quotation 

### Desired behavior:

cy.contains should be able to handle any valid regular expression 

### Test code to reproduce
```js
cy.visit(any_url)
expect(/\'/.test(`'`)).to.be.true  // This test will pass, demonstrating that /\'/ is a valid regular expression 
cy.contains("div", /\'/).should('not.exist') // This will throw unrecognized expression error
```

### Versions
Cypress 5.1.0
Mac OS Catalina
chrome 85

**Comment by jennifer-shehane** [comment]
I can recreate this issue in 6.1.0

### Reproducible example

`spec.js`

```js
it('test', () => {
  cy.contains(/\'/)
})
```

```
Syntax error, unrecognized expression: :not(script,style):cy-contains('/\'/'), [type='submit'][value~='/\'/']

    at Function.Sizzle.error (http://localhost:59685/__cypress/runner/cypress_runner.js:87720:9)
    at Sizzle.tokenize (http://localhost:59685/__cypress/runner/cypress_runner.js:88372:12)
    at Function.Sizzle [as find] (http://localhost:59685/__cypress/runner/cypress_runner.js:86994:16)
    at jQuery.fn.init.find (http://localhost:59685/__cypress/runner/cypress_runner.js:89055:12)
    at new jQuery.fn.init (http://localhost:59685/__cypress/runner/cypress_runner.js:89165:33)
    at Object.query (http://localhost:59685/__cypress/runner/cypress_runner.js:179962:11)
    at $Cy.$$ (http://localhost:59685/__cypress/runner/cypress_runner.js:169245:18)
    at getElements (http://localhost:59685/__cypress/runner/cypress_runner.js:158233:21)
From previous event:
    at resolveElements (http://localhost:59685/__cypress/runner/cypress_runner.js:158283:28)
    at $Cy.get (http://localhost:59685/__cypress/runner/cypress_runner.js:158294:15)
    at $Cy.now (http://localhost:59685/__cypress/runner/cypress_runner.js:170123:48)
    at resolveElements (http://localhost:59685/__cypress/runner/cypress_runner.js:158456:20)
From previous event:
    at Context.contains (http://localhost:59685/__cypress/runner/cypress_runner.js:158488:26)
    at Context.<anonymous> (http://localhost:59685/__cypress/runner/cypress_runner.js:170049:22)
    at <unknown> (http://localhost:59685/__cypress/runner/cypress_runner.js:169473:16)
From previous event:
    at runCommand (http://localhost:59685/__cypress/runner/cypress_runner.js:169452:9)
    at next (http://localhost:59685/__cypress/runner/cypress_runner.js:169598:15)
From previous event:
    at Promise.catch.err.name (http://localhost:59685/__cypress/runner/cypress_runner.js:169639:38)
From previous event:
    at run (http://localhost:59685/__cypress/runner/cypress_runner.js:169632:22)
    at $Cy.cy.<computed> [as contains] (http://localhost:59685/__cypress/runner/cypress_runner.js:170089:12)
    at Context.runnable.fn (http://localhost:59685/__cypress/runner/cypress_runner.js:170313:22)
    at callFn (http://localhost:59685/__cypress/runner/cypress_runner.js:104396:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:59685/__cypress/runner/cypress_runner.js:104383:8)
    at <unknown> (http://localhost:59685/__cypress/runner/cypress_runner.js:175865:29)
From previous event:
    at Object.onRunnableRun (http://localhost:59685/__cypress/runner/cypress_runner.js:175853:18)
    at $Cypress.action (http://localhost:59685/__cypress/runner/cypress_runner.js:166457:29)
    at Test.Runnable.run (http://localhost:59685/__cypress/runner/cypress_runner.js:174232:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:59685/__cypress/runner/cypress_runner.js:105055:11)
    at <unknown> (http://localhost:59685/__cypress/runner/cypress_runner.js:105181:13)
    at next (http://localhost:59685/__cypress/runner/cypress_runner.js:104964:15)
    at <unknown> (http://localhost:59685/__cypress/runner/cypress_runner.js:104974:8)
    at next (http://localhost:59685/__cypress/runner/cypress_runner.js:104876:15)
    at <unknown> (http://localhost:59685/__cypress/runner/cypress_runner.js:104942:6)
    at timeslice (http://localhost:59685/__cypress/runner/cypress_runner.js:98868:28)
```

<img width="477" alt="Screen Shot 2020-12-18 at 8 34 43 AM" src="https://user-images.githubusercontent.com/1271364/102565457-e5c0de00-410b-11eb-9400-66e5fc8c1015.png">
