### ISSUE TITLE
Timed out retrying: cy.click() failed because this element is detached from the DOM.

### ISSUE THREAD

**Issue by lcastro-kareo** [cypress-io/cypress#8637]
### Current behavior:

I'm getting this error in an intermittent way on the execution of my test cases, sometimes the test cases are executed successfully and the next time I'm they fail with this error.

![Screen Shot 2020-09-21 at 13 31 54](https://user-images.githubusercontent.com/58051016/93818251-f813a480-fc0e-11ea-8cf7-56619733cbed.png)

This the button that I am trying to click. First I click over the "three dots" button to open the option "Show All Hours" and to be able to click on it
<img width="351" alt="Screen Shot 2020-09-21 at 13 34 05" src="https://user-images.githubusercontent.com/58051016/93819056-10d08a00-fc10-11ea-9783-8772fbc283f3.png">
<img width="284" alt="Screen Shot 2020-09-21 at 13 34 11" src="https://user-images.githubusercontent.com/58051016/93819063-1332e400-fc10-11ea-9e67-ec6bac302aaa.png">

{code}
View stack trace
    at Object.ensureAttached (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:148521:25)
    at runAllChecks (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:137830:13)
    at retryActionability (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:137889:17)
From previous event:
    at tryFn (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:151745:25)
    at whenStable (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:151786:13)
    at <unknown> (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:151309:17)
From previous event:
    at Object.retry (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:151289:39)
    at retryActionability (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:137892:20)
    at <unknown> (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:137894:8)
From previous event:
    at Object.verify (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:137820:25)
    at perform (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:139857:30)
From previous event:
    at mouseAction (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:139890:21)
    at Context.click (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:139910:15)
    at Context.<anonymous> (https://app-qa.kareo.com/__cypress/runner/cypress_runner.js:156259:22)
From Your Spec Code:
    at Object.clickShowAllHours (https://app-qa.kareo.com/__cypress/tests?p=cypress/integration/platform/platform/dashboard/AppointmentTest.ts:427:113)
    at Context.eval (https://app-qa.kareo.com/__cypress/tests?p=cypress/integration/platform/platform/dashboard/AppointmentTest.ts:167:34)
{code}

### Desired behavior:

I need to click over the option "Show All hours"

### Test code to reproduce

  clickShowAllHours: (): void => {
    cy.get(
      '.Menu__Wrapper-rqrtz5-0 > .IconButton__Wrapper-wotqsh-2 > .IconButton__StyledButton-wotqsh-0',
    ).click(); 
    cy.get('.dropDown > :nth-child(2) > .Button__Styled-sc-1iqorwu-0').click({
      force: true,
    }); 
  },

### Versions

Cypress:  "cypress": "^4.7.0",
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Mac : Mojave 10.14.6

**Comment by bahmutov** [comment]
This is because your application and the test runner have a race - the application is changing the DOM while the test tries to click buttons. You probably need to add assertions or a simple cy.wait to let the app update before clicking. Or you can try our new test retries, see https://on.cypress.io/test-retries

For the explanation of the detached DOM I recommend reading blogs that start with "When can the..." from our Cypress blog https://www.cypress.io/blog/

<img width="621" alt="Screen Shot 2020-09-21 at 8 12 52 PM" src="https://user-images.githubusercontent.com/2212006/93833518-d7ffd780-fc46-11ea-968e-382bd0a8b539.png">
