### ISSUE TITLE
Add support for MTLS authentication

### ISSUE THREAD

**Issue by nwwells** [cypress-io/cypress#868]
### Is this a Feature or Bug?
Feature

### Current behavior:
No apparent way to support mutual (aka client) TLS authentication

### Desired behavior:
An apparent way to support mutual (aka client) TLS authentication

### How to reproduce:
Get a hold of a server that requires mtls (happy to provide if desired) and try to make requests to it. Here's the output when I try to hit mine:

```
CypressError: cy.visit() failed trying to load:

https://admin-pe-demo-09x-o-2.dev-b.symdev.us/ui/

The response we received from your web server was:

  > 400: Bad Request

This was considered a failure because the status code was not '2xx'.


      at Object.cypressErr (http://localhost:56974/__cypress/runner/cypress_runner.js:65861:11)
      at Object.throwErr (http://localhost:56974/__cypress/runner/cypress_runner.js:65826:18)
      at Object.throwErrByPath (http://localhost:56974/__cypress/runner/cypress_runner.js:65853:17)
      at http://localhost:56974/__cypress/runner/cypress_runner.js:57502:31
      at visitFailedByErr (http://localhost:56974/__cypress/runner/cypress_runner.js:57132:12)
      at http://localhost:56974/__cypress/runner/cypress_runner.js:57483:22
      at tryCatcher (http://localhost:56974/__cypress/runner/cypress_runner.js:6268:23)
      at Promise._settlePromiseFromHandler (http://localhost:56974/__cypress/runner/cypress_runner.js:4290:31)
      at Promise._settlePromise (http://localhost:56974/__cypress/runner/cypress_runner.js:4347:18)
      at Promise._settlePromise0 (http://localhost:56974/__cypress/runner/cypress_runner.js:4392:10)
      at Promise._settlePromises (http://localhost:56974/__cypress/runner/cypress_runner.js:4467:18)
      at Async._drainQueue (http://localhost:56974/__cypress/runner/cypress_runner.js:1200:16)
      at Async._drainQueues (http://localhost:56974/__cypress/runner/cypress_runner.js:1210:10)
      at Async.drainQueues (http://localhost:56974/__cypress/runner/cypress_runner.js:1084:14)
```

#### Test code:

```js

describe("Kitchen Sink", function() {
  it(".should() - assert that <title> is correct", function() {
    // https://on.cypress.io/visit
    cy.visit("https://admin-pe-demo-09x-o-2.dev-b.symdev.us/ui/");

    // Here we've made our first assertion using a '.should()' command.
    // An assertion is comprised of a chainer, subject, and optional value.

    // https://on.cypress.io/should
    // https://on.cypress.io/and

    // https://on.cypress.io/title
    cy.title().should("include", "Private Equity");
    //   ↲               ↲            ↲
    // subject        chainer      value
  });
});
```

**Comment by TesterGreg** [comment]
Has there been any movement to look into this?

**Comment by jennifer-shehane** [comment]
No work has been done for this issue.

**Comment by drubf** [comment]
Is there any workaround available for this?

**Comment by darren271** [comment]
Looking for this also. Please update on the availability of the feature, or a workaround.

**Comment by elliotrpmorris** [comment]
Any update on this?

**Comment by jennifer-shehane** [comment]
This is supported as of Cypress 8.0.0 via the clientCertificates config option (PEM and PFX, with optional CA and passphrase):

```js
// cypress.config.js
module.exports = defineConfig({
  clientCertificates: [
    {
      url: '<https://your-mtls-server.com/**'>,
      certs: [{ cert: 'certs/cert.pem', key: 'certs/key.pem' }],
    },
  ],
})
```

Closing as resolved — please open a new issue if anything’s missing.
