### ISSUE TITLE
CypressError     cy.visit() failed trying to load:

### ISSUE THREAD

**Issue by gianmarxWebmapp** [cypress-io/cypress#8704]
i installed cypress in laravel with the following guide https://github.com/laracasts/cypress after running the command `php artisan cypress:boilerplate` cypress no longer works @jennifer-shehane

any test application always gives me the following error:
```
    TEST BODY
    1
    visit
    /
    CypressError
    cy.visit() failed trying to load:
    
    http://my-app.test/
    
    The response we received from your web server was:
    
      > 500: Server Error
    
    This was considered a failure because the status code was not 2xx.
    
    If you do not want status codes to cause failures pass the option: failOnStatusCode: false
    cypress/integration/ex_spec.js:2:5
      1 | it('works',() =>{
    > 2 | 	cy.visit('/').contains('Enviroment:Acceptance');
        | 	   ^
      3 | })


   at <unknown> (http://my-app.test/__cypress/runner/cypress_runner.js:157694:26)
    at visitFailedByErr (http://my-app.test/__cypress/runner/cypress_runner.js:157065:13)
    at <unknown> (http://my-app.test/__cypress/runner/cypress_runner.js:157674:14)
From previous event:
    at go (http://my-app.test/__cypress/runner/cypress_runner.js:157672:18)
    at <unknown> (http://my-app.test/__cypress/runner/cypress_runner.js:157738:21)
From previous event:
    at visit (http://my-app.test/__cypress/runner/cypress_runner.js:157736:39)
    at Context.visit (http://my-app.test/__cypress/runner/cypress_runner.js:157745:15)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/ex_spec.js:2:5)
```

**Comment by jennifer-shehane** [comment]
I would suggest opening an issue with the laracasts repo, as this appears to be something concerned with running the application under test - that it's returning 500 in the browser.
