### ISSUE TITLE
bluebird created-but-not-returned warnings cannot be worked around in certain cases

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#874]
- Cypress Version: 1.0.3

### Is this a Feature or Bug?

Bug

### Current behavior:

When attempting to overwrite certain commands, such as `clearCookies` -- if the origFunc is invoked within the handler, alongside other commands, and it is not returned (which it can't be), bluebird warns about a promise being created and not returned:

```txt
cypress_runner.js:2557 Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (http://example.com/__cypress/runner/cypress_runner.js:3857:10)
    at $Cypress.automation (http://example.com/__cypress/runner/cypress_runner.js:60696:12)
    at automate (http://example.com/__cypress/runner/cypress_runner.js:56019:22)
    at automateCookies (http://example.com/__cypress/runner/cypress_runner.js:56029:14)
    at getAndClear (http://example.com/__cypress/runner/cypress_runner.js:56041:12)
    at clearCookies (http://example.com/__cypress/runner/cypress_runner.js:56224:14)
    at Context.overridden.fn (http://example.com/__cypress/runner/cypress_runner.js:61343:17)
    at http://example.com/__cypress/runner/cypress_runner.js:61798:33
From previous event:
    at runCommand (http://example.com/__cypress/runner/cypress_runner.js:61788:14)
    at next (http://example.com/__cypress/runner/cypress_runner.js:61870:14)
    at http://example.com/__cypress/runner/cypress_runner.js:61882:18
From previous event:
    at next (http://example.com/__cypress/runner/cypress_runner.js:61870:34)
From previous event:
    at http://example.com/__cypress/runner/cypress_runner.js:61889:37
From previous event:
    at run (http://example.com/__cypress/runner/cypress_runner.js:61887:15)
    at Object.cy.(anonymous function) [as request] (http://example.com/__cypress/runner/cypress_runner.js:62107:11)
    at Context.runnable.fn (http://example.com/__cypress/runner/cypress_runner.js:62238:20)
    at callFn (http://example.com/__cypress/runner/cypress_runner.js:32092:21)
    at Hook.Runnable.run (http://example.com/__cypress/runner/cypress_runner.js:32085:7)
    at http://example.com/__cypress/runner/cypress_runner.js:65090:28
    at <anonymous>
From previous event:
    at Object.onRunnableRun (http://example.com/__cypress/runner/cypress_runner.js:65089:20)
    at $Cypress.action (http://example.com/__cypress/runner/cypress_runner.js:60592:51)
    at Hook.Runnable.run (http://example.com/__cypress/runner/cypress_runner.js:64240:20)
    at next (http://example.com/__cypress/runner/cypress_runner.js:32431:10)
    at http://example.com/__cypress/runner/cypress_runner.js:32453:5
    at timeslice (http://example.com/__cypress/runner/cypress_runner.js:27694:27)
```

### Desired behavior:

Not sure how to handle this. We could probably be able to return `null` as per bluebird docs to mute the warning, or something else.

Currently, it can be hacked away by muting the warnings altogether, via:

```js
Cypress.Promise.config({
    warnings: {
        wForgottenReturn: false
    }
});
```

but I'm not sure that's a good idea.

### How to reproduce:

```js
Cypress.Commands.overwrite( `clearCookies`, origFn => {

    cy.clearCookie(`sid`, { log: false });
    origFn();
});

cy.clearCookies();
```

We cannot return the `origFn`, nor we can return `null`, in the above case.

**Comment by brian-mann** [comment]
Not sure why you say "it can't be returned". 

I believe this likely *does* need to be returned else this promise will get lost and Cypress will not be able to await it.

Normally you (the user) are insulated from keeping track of Promises since Cypress handles the enqueuing and running for you - however this is a lower level API and you'll need to keep track and properly connect all promises yourself.

I'd need to try this out but I believe you want to do this...

```js
Cypress.Commands.overwrite( `clearCookies`, origFn => {

    return cy.clearCookie(`sid`, { log: false })
    .then(origFn)
});
```

**Comment by dwelle** [comment]
Hmm, right. I tried this:

```js
return origFn().then(() => {
    cy.clearCookie(`sid`, { log: false });
})
```

which didn't work -- it didn't occur to me it could work the other way round.

What's the rule behind what commands can be nested in `.then()` callbacks, when the parent command is returned?

**Comment by jennifer-shehane** [comment]
Closing as stale. No new comments in over a year.
