### ISSUE TITLE
Cypress crashing when opening project by UNC path

### ISSUE THREAD

**Issue by ezhikov** [cypress-io/cypress#8741]
### Current behavior

Trying to run Cypress.exe open project by UNC path. It creates `cypress` folder, and then just exits.

Not sure where to look for logs.

### Desired behavior
Cypress should work.

### Test code to reproduce
Download cypress binary for windows. Run Cypress.exe. Open project by UNC path.

### Versions

- Windows 10 pro 2004
- Cypress Version 5.3.0

**Comment by ezhikov** [comment]
I tried to map UNC path to as network disk, but with same result

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by ezhikov** [comment]
Not sure how to do it when I'm running downloaded `.exe`

**Comment by kosst** [comment]
I have the same problem and it looks like `chokidar` doesn't handle the path right. If I start cypress.exe through cmd and choose a path of my repo in my WSL2 network drive (`\\wsl$`), cypress crashes and I get the following error message:

```
Error: EISDIR: illegal operation on a directory, watch '/'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1343:11)
    at createFsWatchInstance (C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:116:15)
    at setFsWatchListener (C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:163:15)
    at NodeFsHandler._watchWithNodeFs (C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:325:14)
    at NodeFsHandler._handleDir (C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:551:19)
    at NodeFsHandler._addToNodeFs (C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\lib\nodefs-handler.js:600:27)
    at C:\Users\kosst\cypress\resources\app\packages\server\node_modules\chokidar\index.js:435:21
    at Function.all (<anonymous>:null:null)
```

Maybe it's related to this issue:

https://github.com/paulmillr/chokidar/issues/948

**Comment by ezhikov** [comment]
CMD can't use UNC paths, so this should be the problem.

**Comment by intelmatt** [comment]
Behavior is a bit different now when starting Cypress from a UNC path (Aug 2021):

```
npx cypress open
'\\server\path'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

So, it starts up in c:\windows and then errors out with permission issues. Can work around it by creating a drive letter mapping, but strongly prefer not to do that for obvious reasons.
