### ISSUE TITLE
cypress cache list —size throws: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#8856]
Cypress v5.4.0 on Mac with Node v12.14.1

Trying to run `npx cypress cache list --size` command

```
$ npx cypress version
Cypress package version: 5.4.0
Cypress binary version: 5.4.0
~/git/cypress-react-unit-test on main
$ npx cypress cache list --size
Unhandled rejection ReferenceError: regeneratorRuntime is not defined
    at _getSize (/Users/gleb/git/cypress-react-unit-test/node_modules/cypress/lib/tasks/get-folder-size.js:29:46)
    at getSize (/Users/gleb/git/cypress-react-unit-test/node_modules/cypress/lib/tasks/get-folder-size.js:25:19)
    at /Users/gleb/git/cypress-react-unit-test/node_modules/cypress/lib/tasks/cache.js:141:14
    at tryCatcher (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/gleb/git/cypress-react-unit-test/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

~/git/cypress-react-unit-test on main
$ node -v
v12.14.1
```

**Comment by kamiloski** [comment]
The same on windows 10
