### ISSUE TITLE
Test that is less flaky when video recording is disabled

### ISSUE THREAD

**Issue by joe-loco** [cypress-io/cypress#893]
The following test fails about 25% of the time on our CI (and when running in headless mode locally).
We’ve never seen it fail when using the Runner UI. Also, once video recording is enabled (on CI or headless mode locally), the failure rate drops to about 1 failed in 30 tests.

```js
describe('Editor Tests', function() {
  beforeEach(function() {
    cy.visit('localhost:8888/nextjournal/demo/edit')
  })

  context('Code Cells', function() {
    it('should eval locally', function() {
      let cellSelector = '[data-node-id="/collaborate"] .section-item:last-of-type .node-code'
      cy.get("#add-new-content-button").click()
      cy.get('div[rel="Code Cell: Javascript"]').click()
      cy.get(cellSelector + ' .ReactCodeMirror').click()
      cy.get(cellSelector + ' .CodeMirror-wrap textarea').focus()
      cy.get(cellSelector + ' .CodeMirror-wrap textarea').type("5", { force: true })
      cy.get(cellSelector + ' .CodeMirror-wrap textarea').blur()
      cy.get(cellSelector + ' .result-view .monospace', {
        timeout: 30 * 1000
      }).then(function($result) {
        expect($result[0].innerText.trim()).to.equal("5")
      })
    })
  })
})
```

This is the CypressError it records when the test is failing:

```
1) Editor Tests Code Cells should eval locally:
     CypressError: Timed out retrying: Expected to find element: '[data-node-id="/collaborate"] .section-item:last-of-type .node-code .result-view .monospace', but never found it.
      at Object.cypressErr (http://localhost:8888/__cypress/runner/cypress_runner.js:65836:11)
      at Object.throwErr (http://localhost:8888/__cypress/runner/cypress_runner.js:65801:18)
      at Object.throwErrByPath (http://localhost:8888/__cypress/runner/cypress_runner.js:65828:17)
      at retry (http://localhost:8888/__cypress/runner/cypress_runner.js:59954:16)
      at http://localhost:8888/__cypress/runner/cypress_runner.js:52456:18
      at tryCatcher (http://localhost:8888/__cypress/runner/cypress_runner.js:6268:23)
      at Promise._settlePromiseFromHandler (http://localhost:8888/__cypress/runner/cypress_runner.js:4290:31)
      at Promise._settlePromise (http://localhost:8888/__cypress/runner/cypress_runner.js:4347:18)
      at Promise._settlePromise0 (http://localhost:8888/__cypress/runner/cypress_runner.js:4392:10)
      at Promise._settlePromises (http://localhost:8888/__cypress/runner/cypress_runner.js:4467:18)
      at Async._drainQueue (http://localhost:8888/__cypress/runner/cypress_runner.js:1200:16)
      at Async._drainQueues (http://localhost:8888/__cypress/runner/cypress_runner.js:1210:10)
      at Async.drainQueues (http://localhost:8888/__cypress/runner/cypress_runner.js:1084:14)
```

Any idea why this test is flaky in general and why video recording could affect this?

The test’s use-case is for a live-coding environment and should do the following:

* add a new CodeMirror instance
* type something into CodeMirror
* blur CodeMirror
* wait for an (asynchronously evaluated) result to be rendered

The result is calculated in a web worker and shouldn’t take longer than a couple seconds.
Currently, we have 15 other tests for the same page and they don’t seem to have this problem.

**Comment by chit786** [comment]
we are experiencing similar problems. 

- We currently use cypress with around 400 tests in our jenkins pipelines in headless mode and it turns out with "disabled" video recordings the tests appears flaky.

We don't see any issues with the environments like memory spikes etc. Providing test guards do not provide much help either.

Does it have something to do with cypress runner being too fast when video recording is disabled ?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
