### ISSUE TITLE
Cypress - TypeError: cannot read property 'KeyboardEvent' of undefined (Cypress version - 5.5.0)

### ISSUE THREAD

**Issue by pratikpatel1221** [cypress-io/cypress#9075]
While executing the code it is throwing TypeError for - cy.get('selector').type('pqr.com').

`at Keyboard.fireSimulatedEvent ({{URL}}/__cypress/runner/cypress_runner.js:162534:29)  at Keyboard.simulatedKeydown ({{URL}}/__cypress/runner/cypress_runner.js:162679:59)  at Keyboard.typeSimulatedKey ({{URL}}/__cypress/runner/cypress_runner.js:162719:11)  at ({{URL}}/__cypress/runner/cypress_runner.js:162396:15) From previous event:  at ({{URL}}/__cypress/runner/cypress_runner.js:162405:66) From previous event:  at Keyboard.type ({{URL}}/__cypress/runner/cypress_runner.js:162404:61)  at type ({{URL}}/__cypress/runner/cypress_runner.js:153804:24)  at ({{URL}}/__cypress/runner/cypress_runner.js:153999:21) From previous event:  at onReady ({{URL}}/__cypress/runner/cypress_runner.js:153975:15)  at runAllChecks ({{URL}}/__cypress/runner/cypress_runner.js:150154:15)  at retryActionability ({{URL}}/__cypress/runner/cypress_runner.js:150163:17) From previous event:  at tryFn ({{URL}}/__cypress/runner/cypress_runner.js:165407:22)  at whenStable ({{URL}}/__cypress/runner/cypress_runner.js:165445:13)  at ({{URL}}/__cypress/runner/cypress_runner.js:164960:17) From previous event:  at $Cy.retry ({{URL}}/__cypress/runner/cypress_runner.js:164940:39)  at retryActionability ({{URL}}/__cypress/runner/cypress_runner.js:150166:20)  at ({{URL}}/__cypress/runner/cypress_runner.js:150168:8) From previous event:  at Object.verify ({{URL}}/__cypress/runner/cypress_runner.js:150095:22)  at handleFocused ({{URL}}/__cypress/runner/cypress_runner.js:153947:30)  at Context.type ({{URL}}/__cypress/runner/cypress_runner.js:154006:13)  at Context. ({{URL}}/__cypress/runner/cypress_runner.js:169891:22)  at ({{URL}}/__cypress/runner/cypress_runner.js:169315:16) From previous event:  at runCommand ({{URL}}/__cypress/runner/cypress_runner.js:169294:9)  at next ({{URL}}/__cypress/runner/cypress_runner.js:169440:15)  at ({{URL}}/__cypress/runner/cypress_runner.js:169468:17) From previous event:  at next ({{URL}}/__cypress/runner/cypress_runner.js:169440:35) From previous event:  at Promise.catch.err.name ({{URL}}/__cypress/runner/cypress_runner.js:169481:38) From previous event:  at run ({{URL}}/__cypress/runner/cypress_runner.js:169474:22)  at $Cy.cy. [as get] ({{URL}}/__cypress/runner/cypress_runner.js:169931:12)  at Context.runnable.fn ({{URL}}/__cypress/runner/cypress_runner.js:170155:22)  at callFn ({{URL}}/__cypress/runner/cypress_runner.js:104227:22)  at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run ({{URL}}/__cypress/runner/cypress_runner.js:104214:8)  at ({{URL}}/__cypress/runner/cypress_runner.js:175754:29) From previous event:  at Object.onRunnableRun ({{URL}}/__cypress/runner/cypress_runner.js:175742:18)  at $Cypress.action ({{URL}}/__cypress/runner/cypress_runner.js:166291:29)  at Test.Runnable.run ({{URL}}/__cypress/runner/cypress_runner.js:174128:14)  at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest ({{URL}}/__cypress/runner/cypress_runner.js:104886:11)  at ({{URL}}/__cypress/runner/cypress_runner.js:105012:13)  at next ({{URL}}/__cypress/runner/cypress_runner.js:104795:15)  at ({{URL}}/__cypress/runner/cypress_runner.js:104805:8)  at next ({{URL}}/__cypress/runner/cypress_runner.js:104707:15)  at ({{URL}}/__cypress/runner/cypress_runner.js:104773:6)  at timeslice ({{URL}}/__cypress/runner/cypress_runner.js:98699:28)`

A web application which I am trying to automate contains the different text boxes. I have experienced that this issue is not related to the specific filed. But it is something relevant to the previous filed. Using Cypress (cy.get('selector').type('text')) I am able to type the proper value into one field and then when I try to enter the text into another text, mentioned issue is occurred. I have checked with changing the order of the text box and found that it is not specific to the particular field.
Also to note that, it is not throwing error if I try cy.get('selector').clear().

**Comment by jennifer-shehane** [comment]
From looking at the error message, this does look like a bug within Cypress being thrown from here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/keyboard.ts#L923:L923 cc @sainthkh 

- Was this working in a previous Cypress version?
- Can you provide a reproducible example? 

We won't be able to fix it without a way to reproduce exactly why this window is undefined in your tests. Thanks!

**Comment by sainthkh** [comment]
@jennifer-shehane Usually `window` object doesn't become `undefined`. Maybe something is going on in the client's program.

**Comment by thomasdissert** [comment]
We're having the same issue here. This started to occur a couple of days ago, AFAIK.

**Comment by pratikpatel1221** [comment]
@jennifer-shehane ,
Sorry, for maintaining the code confidentiality, I am not able to provide you the exact code snippet & application details.

 I did reinstall the Cypress and it started working for me properly.

**Comment by theothersideofgod** [comment]
hi, @pratikpatel1221 sir, did you fix this issue?

**Comment by SibelUlufer** [comment]
I have the same issue. What should I do?
Same result for both use:
`cy.get('[placeholder="Search all sites"]').type(Cypress.env('topicText'))`
```
cy.get('@selectedTopicText').then ( text =>{
                cy.get('[placeholder="Search all sites"]').type(text)
            })
```

![image](https://user-images.githubusercontent.com/81959643/166672926-0b787c80-5a46-4fcc-b711-8c974669159c.png)

**Comment by Izzy1127** [comment]
Hi
I am also having the issue when automating multiple text boxes in same page.however cy.get('selector').clear().type() did not work for me.can someone help me with this. Appreciate your response.

**Comment by cheapsteak** [comment]
we've also started seeing this recently 
![image](https://user-images.githubusercontent.com/743976/182959895-9998fa94-3c08-46cc-84dc-eccd5364f2b6.png)


fwiw this github issue is currently the top google result for "cypress keyboardevent undefined"

**Comment by DarynaMinko** [comment]
I have the same issue in the Cypress "10.4.0"
<img width="796" alt="image" src="https://user-images.githubusercontent.com/106735374/185370298-f1ff2bf3-1e6c-48f4-9008-02b3f5a0cd17.png">

**Comment by LentoMan** [comment]
Our issue was that we had a change event registered on textfields for a search form which submits the form when a textfield changes. According to the documentation for ```.clear()``` it is an alias for ```.type('{selectall}{backspace}')``` and the issue was that we called .clear() on one textfield and then immediately tried to type in another textfield. The switch to the other textfield most likely triggered a form submit when the first textfield lost focus, resulting in a form refresh before cypress manage to complete typing in the second textfield. Adding ```.type("{enter}")``` after ```.clear()``` on the first textfield seems to have resolved the issue for us.

**Comment by enesberber** [comment]
In my scenario, it fails intermittently rather than constantly and I couldn't find any reason. Does anyone see a solution for this?

**Comment by nagash77** [comment]
@enesberber if you are experiencing an issue, please open a new issue with a reproducible example and our team will be happy to investigate.

**Comment by 97145963868** [comment]
I had same issue. Workaround: ato = ato.replace(/\s/g, '')

**Comment by simi1912** [comment]
I have the same issue only on `npx cypress run`, with `npx cypress open` it works fine.

Error:

>   1) Create Assignment
       "before each" hook for "should create Assignment":
     TypeError: Cannot read properties of undefined (reading 'KeyboardEvent')
Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Create Assignment`        
      at Keyboard.fireSimulatedEvent (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:152808:28)
      at Keyboard.simulatedKeydown (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:152931:58)
      at Keyboard.typeSimulatedKey (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:152969:10)
      at <unknown> (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:152665:14)
      at tryCatcher (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:18744:23)
      at Promise.attempt.Promise.try (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16018:29)
      at <unknown> (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:152674:67)
      at tryCatcher (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:18744:23)
      at Object.gotValue (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:17886:18)
      at Object.gotAccum (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:17875:25)
      at Object.tryCatcher (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16805:18)
      at Promise._resolveCallback (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16599:57)
      at Promise._settlePromiseFromHandler (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16691:17)
      at Promise._settlePromise (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://127.0.0.1:5500/__cypress/runner/cypress_runner.js:16805:18)

**Comment by afilina** [comment]
In case someone else is having this issue, hopefully this helps...

```
cy.get('input[name=username]').should('be.visible').type(USERNAME)
```

This forces Cypress to wait for the element to become visible. It also gets the input that is visible, as opposed to an old one that got detached, which happens in some JS frameworks that constantly re-render things.

In my case, after adding the `should`, this intermittent issue reliably went away.

**Comment by ivan-sam** [comment]
What's interesting is that the Cypress documentation ([Implicit Assertions section](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Implicit-Assertions)) says that
>Many commands have default, built-in assertions, or rather have requirements that may cause it to fail without needing an explicit assertion you've added.
>...
>[.type()](https://docs.cypress.io/api/commands/type) expects the element to eventually be in a typeable state.

Perhaps some implicit assertions are missing for the `type` command.

**Comment by hannamakarychak** [comment]
I also had this issue in cypress 14.4.1. I decided to skip typing altogether and manually invoke change, and it worked:

it('should type into text input ticket number', () => {

        const testValue = 'BA12345';
         
        cy.get('input[name="ticket-number"]', { timeout: 6000 })
          .should('exist')
          .should('be.visible')
          .should('not.be.disabled')
          .invoke('val', testValue)
          .trigger('input')
          .trigger('change');
           
        cy.get('input[name="ticket-number"]').should('have.value', testValue);
      });
