### ISSUE TITLE
Failed to set the 'domain' property on 'Document': '{string}' is a top-level domain.

### ISSUE THREAD

**Issue by Panteleimon** [cypress-io/cypress#9131]
# Current behaviour

<img width="658" alt="Screenshot 2020-11-09 at 2 49 05 PM" src="https://user-images.githubusercontent.com/16741917/98543623-6eda2f00-229b-11eb-91ae-f9571fb357d3.png">

This happens for all the staging and production domains we have.

 An example staging url looks like this
'https://develop-v3-staging-wm6caaxt.undisclosed.bg'
Those also end in .gr or .com.

An example production url looks like this
'https://undisclosed.gr
Those end in .com, gr, de etc... (I can provide the production URLs in direct message but i won't post them online)

# Desired behaviour
Just visit the given target url without any issue

# Test code to reproduce
The cy.visit('requiredUrl') command.

# Versions 
I have tried all the cypress versions 3 4 and 5. All produce the same thing. The website continues to load normally after the fail. I do not exactly understand what is going on because this behaviour leads to something which is fixed in version 2.xxx or 3.xxx as I saw while researching

Error log
```
cypress_runner.js:199686 SecurityError: Failed to set the 'domain' property on 'Document': 'bg' is a top-level domain.
    at Module.<anonymous> (https://develop-v3-staging-wm6caaxt.undisclosed.bg//main.508083c96c0153842fb5.js:2:2588107)
    at r (https://develop-v3-staging-wm6caaxt.undisclosed.bg//bundle.6e8dace29fd0427bfa2e.js:1:571)
at Object.<anonymous> (https://develop-v3-staging-wm6caaxt.undisclosed.bg//main.508083c96c0153842fb5.js:2:723212)
    at r (https://develop-v3-staging-wm6caaxt.undisclosed.bg//bundle.6e8dace29fd0427bfa2e.js:1:571)
at d (https://develop-v3-staging-wm6caaxt.undisclosed.bg//bundle.6e8dace29fd0427bfa2e.js:1:430)
at Array.a [as push] (https://develop-v3-staging-wm6caaxt.undisclosed.bg//bundle.6e8dace29fd0427bfa2e.js:1:293)
    at https://develop-v3-staging-wm6caaxt.undisclosed.bg//main.508083c96c0153842fb5.js:2:47
    From previous event:
    at run (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:169474:21)
at $Cy.cy.<computed> [as then] (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:169931:11)
    at Context.runnable.fn (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:170155:21)
    at callFn (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104227:21)
    at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175754:28
    From previous event:
    at Object.onRunnableRun (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175742:17)
    at $Cypress.action (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:166291:28)
    at Test.Runnable.run (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:174128:13)
    at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:105012:12
    at next (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104795:14)
    at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104805:7
    at next (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104707:14)
    at Hook.<anonymous> (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104768:7)
        at next (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175675:22)
        at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175697:11
        From previous event:
        at onNext (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175694:57)
        at done (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104167:5)
        at callFn (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104250:7)
        at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175754:28
        From previous event:
        at Object.onRunnableRun (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:175742:17)
        at $Cypress.action (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:166291:28)
        at Hook.Runnable.run (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:174128:13)
        at next (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104729:10)
        at https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:104773:5
        at timeslice (https://develop-v3-staging-wm6caaxt.undisclosed.bg/__cypress/runner/cypress_runner.js:98699:27)
```

**Comment by jennifer-shehane** [comment]
May have to do with https://www.npmjs.com/package/@cypress/parse-domain? That's where I've generally seen these issues in the past. We've been wanting to update that dep to be replaced with the latest https://github.com/peerigon/parse-domain

**Comment by camistein** [comment]
Experiencing similar issue with urls for azure container instances example: "containername.northeurope.azurecontainer.io". 
I've installed cypress: "9.1.0". 
Do you know any workaround for this issue? perhaps an override for the command for visit()

**Comment by camistein** [comment]
Update: I had to revert back to version 7.3.0, after the addition of:  "is-valid-domain": "0.0.19", in version 7.4.0 the domains for my azure container with azurecontainer.io no longer works. Master branch is using "is-valid-domain": "0.0.20", but doesnt seem to change/fix the issue. 
@jennifer-shehane does that have to do anything with the replace dep. to parse-domain?

**Comment by flotwig** [comment]
This should have been fixed in the latest release of Cypress, we update the `parse-domain` metadata with each release now. Please open a new issue if this is still occurring.
