### ISSUE TITLE
Intermittent timeouts during `cypress verify` on CI

### ISSUE THREAD

**Issue by Undistraction** [cypress-io/cypress#9138]
### Current behavior
Intermittent timeouts during `cypress verify`

### Desired behavior
No timeouts during `cypress verify`

### Test code to reproduce
We are seeing this on CI for approximately 1/10th of our builds with no discernible pattern. 

Gitlab.ci
```
prepare:
  stage: Prepare
  artifacts:
    expire_in: 2 weeks
    paths:
      - .npmrc
    script:
      …
      - $(yarn bin)/cypress cache list
      - $(yarn bin)/cypress cache path
      - DEBUG=cypress:* $(yarn bin)/cypress verify
      - $(yarn bin)/cypress -v
```

Cypress log output:
```
2020-11-09T18:54:06.770Z cypress:cli:cli cli starts with arguments ["/usr/local/bin/node","/builds/company/site/node_modules/.bin/cypress","verify"]
2020-11-09T18:54:06.771Z cypress:cli NODE_OPTIONS=--max_old_space_size=4096
2020-11-09T18:54:06.771Z cypress:cli:cli program parsing arguments
2020-11-09T18:54:06.774Z cypress:cli parsed cli options {}
2020-11-09T18:54:07.024Z cypress:cli verifying Cypress app
2020-11-09T18:54:07.025Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2020-11-09T18:54:07.025Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2020-11-09T18:54:07.025Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /builds/company/site/cache/Cypress
2020-11-09T18:54:07.026Z cypress:cli checking environment variables
2020-11-09T18:54:07.044Z cypress:cli checking if executable exists /builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress
2020-11-09T18:54:07.051Z cypress:cli Binary is executable? : true
2020-11-09T18:54:07.052Z cypress:cli binaryDir is  /builds/company/site/cache/Cypress/4.9.0/Cypress
2020-11-09T18:54:07.052Z cypress:cli Reading binary package.json from: /builds/company/site/cache/Cypress/4.9.0/Cypress/resources/app/package.json
2020-11-09T18:54:07.176Z cypress:cli Found binary version 4.9.0 installed in: /builds/company/site/cache/Cypress/4.9.0/Cypress
2020-11-09T18:54:07.179Z cypress:cli { verified: true }
2020-11-09T18:54:07.179Z cypress:cli is Verified ? true
2020-11-09T18:54:07.180Z cypress:cli force verify
2020-11-09T18:54:07.180Z cypress:cli running binary verification check 4.9.0
[18:54:07]  Verifying Cypress can run /builds/company/site/cache/Cypress/4.9.0/Cypress [started]
2020-11-09T18:54:07.186Z cypress:cli clearing out the verified version
2020-11-09T18:54:07.189Z cypress:cli undefined DISPLAY environment variable
2020-11-09T18:54:07.189Z cypress:cli Cypress will spawn its own Xvfb
2020-11-09T18:54:07.189Z cypress:cli needs Xvfb? true
2020-11-09T18:54:07.189Z cypress:cli Starting Xvfb
2020-11-09T18:54:07.209Z cypress:cli disabling Electron sandbox
2020-11-09T18:54:07.209Z cypress:cli running smoke test
2020-11-09T18:54:07.209Z cypress:cli using Cypress executable /builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress
2020-11-09T18:54:07.209Z cypress:cli smoke test command: /builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=385
2020-11-09T18:54:07.209Z cypress:cli smoke test timeout 30000 ms
2020-11-09T18:54:37.344Z cypress:cli Smoke test failed: Error: Command failed: /builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=385
    at makeError (/builds/company/site/node_modules/execa/index.js:174:9)
    at /builds/company/site/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: null,
  stdout: '',
  stderr: '',
  failed: true,
  signal: 'SIGTERM',
  cmd: '/builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=385',
  timedOut: true,
  killed: true
}
2020-11-09T18:54:37.346Z cypress:cli error message: Command failed: /builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=385
2020-11-09T18:54:37.346Z cypress:cli error timedOut is true
2020-11-09T18:54:37.356Z cypress:cli Stopping Xvfb
[18:54:37]  Verifying Cypress can run /builds/company/site/cache/Cypress/4.9.0/Cypress [failed]
Cypress verification timed out.
This command failed with the following output:
/builds/company/site/cache/Cypress/4.9.0/Cypress/Cypress --no-sandbox --smoke-test --ping=385
```

### Versions

Cypress 4.9.0
GitLab Community Edition 13.5.3

### Workaround

The only workaround that I can find is to monkey-patch Cypress's internals with is gross:
```
# In Gitlab.yml
sed -i 's/VERIFY_TEST_RUNNER_TIMEOUT_MS = 30000/VERIFY_TEST_RUNNER_TIMEOUT_MS = 60000/g' node_modules\/cypress\/lib\/tasks\/verify.js
```

### Comments

Please provide a means of changing this timeout via config or a flag. 

### Related
- https://github.com/cypress-io/cypress/issues/6082

**Comment by kaiyoma** [comment]
Others have been seeing the same problem. See issue #6082. No word from Cypress folks about what's wrong or how to fix this.

**Comment by donegjookim** [comment]
[Solution](https://stackoverflow.com/a/70867864)
