### ISSUE TITLE
Can't open cypress

### ISSUE THREAD

**Issue by Pitasi** [cypress-io/cypress#9192]
### Current behavior

I installed Cypress 5.6 tryind different ways: `yarn global add cypress`, `yarn add cypress`, `npm install cypress`, `npm install -g cypress` always with same results. Cypress won't open/start.

### Debug logs

```
$ env DEBUG="*" node_modules/.bin/cypress open

  cypress:cli:cli cli starts with arguments ["/usr/bin/node","/home/antonio/git/myrepo/node_modules/.bin/cypress","open"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +85ms
  cypress:cli opening from options {"project":"/home/antonio/git/myrepo"} +0ms
  cypress:cli command line arguments ["--project","/home/antonio/git/myrepo"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress +4ms
  cypress:cli Binary is executable? : true +2ms
  cypress:cli binaryDir is  /home/antonio/.cache/Cypress/5.6.0/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/antonio/.cache/Cypress/5.6.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 5.6.0 installed in: /home/antonio/.cache/Cypress/5.6.0/Cypress +6ms
  cypress:cli could not read binary_state.json file at "/home/antonio/.cache/Cypress/5.6.0/binary_state.json" +7ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +1ms
  cypress:cli running binary verification check 5.6.0 +0ms
It looks like this is your first time using Cypress: 5.6.0

  cypress:cli clearing out the verified version +3ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +3ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=233 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  ⠸  Verifying Cypress can run /home/antonio/.cache/Cypress/5.6.0/Cypress
  cypress:cli Smoke test failed: Error: Command was killed with SIGTRAP (Debugger breakpoint): /home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=233
[57219:1113/120139.007227:ERROR:icu_util.cc(247)] Couldn't mmap icu data file
    at makeError (/home/antonio/git/myrepo/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/antonio/git/myrepo/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  shortMessage: 'Command was killed with SIGTRAP (Debugger breakpoint): /home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=233',
  command: '/home/antonio/.cache/Cypress/5.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=233',
  exitCode: undefined,
  signal: 'SIGTRAP',
  signalDescription: 'Debugger breakpoint',
  stdout: '',
  stderr: "[57219:1113/120139.007227:ERROR:icu_util.cc(247)] Couldn't mmap icu data file",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +375ms
  ✖  Verifying Cypress can run /home/antonio/.cache/Cypress/5.6.0/Cypress
    → Cypress Version: 5.6.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

[57219:1113/120139.007227:ERROR:icu_util.cc(247)] Couldn't mmap icu data file

----------

Platform: linux (Arch Linux - )
Cypress Version: 5.6.0
```

I also tried launching with --dev since I got suspicious by the SIGTRAP:

```
env DEBUG="*" node_modules/.bin/cypress open --dev 

  cypress:cli:cli cli starts with arguments ["/usr/bin/node","/home/antonio/git/myrepo/node_modules/.bin/cypress","open","--dev"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli opening Cypress +0ms
  cypress:cli parsed cli options { dev: true } +77ms
  cypress:cli opening from options {"dev":true,"project":"/home/antonio/git/myrepo"} +0ms
  cypress:cli command line arguments ["--project","/home/antonio/git/myrepo"] +1ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +1ms
  cypress:cli in dev mode the args became [ '/home/antonio/git/myrepo/node_modules/scripts/start.js', '--', '--project', '/home/antonio/git/myrepo', '--cwd', '/home/antonio/git/myrepo' ] +0ms
  cypress:cli passing DISPLAY :0 +3ms
  cypress:cli spawning Cypress with executable: node +0ms
  cypress:cli spawn args [ '/home/antonio/git/myrepo/node_modules/scripts/start.js', '--', '--project', '/home/antonio/git/myrepo', '--cwd', '/home/antonio/git/myrepo' ] { detached: false, stdio: 'inherit' } +0ms
node:internal/modules/cjs/loader:922
  throw err;
  ^

Error: Cannot find module '/home/antonio/git/myrepo/node_modules/scripts/start.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +38ms
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +1ms
```

Why is it looking for a `node_modules/scripts/start.js`?

### Download method
 

- [x] npm
- [x] yarn
- [ ] Direct download
- [ ] other 

### Operating System
 

- [x] Linux
- [ ] Mac
- [ ] Windows

### Other

- [x] I'm installing latest Cypress version 
- [ ] I'm behind a proxy 
- [ ] This only occurs in CI

**Comment by Pitasi** [comment]
Solved this after finding #4624 (didn't find it the first time from github search, only from google).

The steps the solved the problem for me were:
```
$ cypress cache clear
$ cypress install
$ cypress verify  # not open/run!
```
