### ISSUE TITLE
cy.visit error with multiple calls to 301 redirect

### ISSUE THREAD

**Issue by katerynae** [cypress-io/cypress#926]
- Operating System: OSX 10.12.6
- Cypress Version: 1.03
- Browser Version: chrome 62

### Is this a Feature or Bug?
Bug

### Current behavior:
I have two tests in one file. They both call `cy.visit('/')`. The base_url has a 301 redirect (from http to a different website with https). The `visit` call in the first test follows the redirect correctly. The visit in the second test does not (sometimes). 

When I am running the server locally, the second visit call sometimes passes, and sometimes results in:
```
Error:         Uncaught TypeError: Cannot read property 'isEmpty' of null
    at t.value (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:5:17343)
    at t.value (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:5:17248)
    at e.bt.AnonymousObserver.e.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10526)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at e.<anonymous> (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:16180)
    at e.n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:28868)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:28579)
    at n.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at n.<anonymous> (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:16180)
    at e.n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:28868)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at r.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:11950)
    at r.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at r.<anonymous> (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:16180)
    at e.n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:28868)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:30375)
    at e.<anonymous> (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:16180)
    at e.n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:28868)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at e.<anonymous> (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:16180)
    at e.n.next (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:4:28868)
    at e.bt.internals.AbstractObserver.e.onNext (https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:3:10031)
    at https://www.storygize.net/public/dist/d30f61ee-e3f7-4038-9201-3dee138af8b6_bundle.js:2:1117
    at d (https://cdn.ravenjs.com/3.19.1/raven.min.js:2:4294)
From previous event:
    at run (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:61887:15)
    at Object.cy.(anonymous function) [as visit] (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:62107:11)
    at Context.runnable.fn (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:62238:20)
    at callFn (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32092:21)
    at Test.Runnable.run (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32085:7)
    at http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:65090:28
From previous event:
    at Object.onRunnableRun (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:65089:20)
    at $Cypress.action (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:60592:51)
    at Test.Runnable.run (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:64240:20)
    at Runner.runTest (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32555:10)
    at http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32661:12
    at next (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32475:14)
    at http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32485:7
    at next (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32417:14)
    at http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:32453:5
    at timeslice (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:27694:27)
```

When I run against a QA server (on Amazon) it passes.
 
### Desired behavior:
cy.visit("/") should resolve the URL correctly both times.

### How to reproduce:
Create a slow? server with a url that redirects. Try to call that url in two tests.

#### Test code:

```js
describe('A cypress test', function() {
  it('first visit', function () {
    cy.visit("/")
  })

  it('second visit', function() {
    cy.visit("/")
  })
})
```

### Additional Info (images, stack traces, etc)

<img width="1680" alt="screen shot 2017-11-16 at 11 55 54 pm" src="https://user-images.githubusercontent.com/17116790/32930014-e9d771e4-cb29-11e7-8535-c1e80d101d0c.png">
<img width="1680" alt="screen shot 2017-11-16 at 11 56 57 pm" src="https://user-images.githubusercontent.com/17116790/32930015-e9e35464-cb29-11e7-8bff-ff7210ecf7a0.png">
<img width="1680" alt="screen shot 2017-11-17 at 12 05 44 am" src="https://user-images.githubusercontent.com/17116790/32930201-249b381e-cb2b-11e7-8d1a-97af34fc3a9b.png">

**Comment by brian-mann** [comment]
I don't believe there is anything wrong with `cy.visit.` This error is an **uncaught error** originating from your application code (look at the stack trace). The problem is that you have a bug in your javascript somewhere. 

Just click on the stack trace to goto where that's happening. Also you could use Dev Tools to break on uncaught exceptions.

You can also turn this off in Cypress if you want to.

https://docs.cypress.io/api/events/catalog-of-events.html#Uncaught-Exceptions

**Comment by katerynae** [comment]
@brian-mann 

The full error I see in cypress driver log looks like this
```
cypress:driver emitted: 'uncaught:exception' to '0' listeners - with args: TypeError: Cannot read property 'isEmpty' of null
    at t.value (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:5)
    at t.value (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:5)
    at e.bt.AnonymousObserver.e.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at e.<anonymous> (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2)
    at e.n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at n.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at n.<anonymous> (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2)
    at e.n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at r.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at r.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at r.<anonymous> (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2)
    at e.n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.<anonymous> (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2)
    at e.n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at e.<anonymous> (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2)
    at e.n.next (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:4)
    at e.bt.internals.AbstractObserver.e.onNext (VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:3)
    at VM792 98f69970-83a5-42fe-bd80-65b0ae78a913_bundle.js:2
    at d (VM669 raven.min.js:2) +37ms 
```

And also stack for this error looks like this:
```
Error: done() called multiple times at Test.Runnable (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:31821:17) at new Test (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:33449:12) at context.it.context.specify (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:28364:18) at context.describe.context.context (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:28326:10)
message
:
"done() called multiple times"
stack
:
"Error: done() called multiple times↵    at Test.Runnable (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:31821:17)↵    at new Test (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:33449:12)↵    at context.it.context.specify (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:28364:18)↵    at context.describe.context.context (http://local-members.onepeloton.com:3000/__cypress/runner/cypress_runner.js:28326:10)"
```

So i don't understand how it might come from our code.

It happens to the second visit when I was already redirected once. So maybe you can suggest any scenarios why cypress might get confused with it...

**Comment by brian-mann** [comment]
Do this:

```js
Cypress.on('uncaught:exception', (err) => {
  debugger
})
```

Inspect the error instance. Walk up the stack trace. That should point you to the exact spot it fails. It could be failing due to something about the way that Cypress works - but I'm 100% sure that error is coming from your application, not Cypress.

If you were to `return false` there, it would no longer fail the test.
