### ISSUE TITLE
I am starting with Cypress but Not sure it supports Win64 or not?  I am using Win 10, 64bit with node v6.11.0 and npm 3.10.10

### ISSUE THREAD

**Issue by Shiv751** [cypress-io/cypress#929]
`C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:57
          throw new Error("Platform: '" + p + "' is not supported.");
          ^

Error: Platform: 'win32' is not supported.
    at Object.getDefaultAppFolder (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:37:15)
    at Object.getPathToExecutable (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:18:16)
    at Object._fileExistsAtPath (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:51:23)
    at Object.verifyCypress (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:78:6)
    at C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:167:8
    at Object.spawn (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\utils.coffee:191:7)
    at Open.open (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\commands\open.coffee:25:11)
    at new Open (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\commands\open.coffee:10:6)
    at Open (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\commands\open.coffee:8:14)
    at Command.<anonymous> (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\cli.coffee:98:7)
    at Command.listener (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\node_modules\commander\index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\node_modules\commander\index.js:635:12)
    at Command.parse (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\node_modules\commander\index.js:457:21)
    at module.exports (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\lib\cli.coffee:135:11)
    at Object.<anonymous> (C:\Users\tvishnoi\AppData\Roaming\npm\node_modules\cypress-cli\bin\cypress:4:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3`

**Comment by jennifer-shehane** [comment]
From the docs, it looks like only 32bit is provided: https://on.cypress.io/installing-cypress

> Windows 7+, only 32bit binaries are provided for Windows.

So, converting this issue over to a request for Windows 64bit support.

**Comment by brian-mann** [comment]
I can tell from your paths that you are trying to use the old/deprecated `cypress-cli`. 

This is no longer supported. Please uninstall it with `npm uninstall -g cypress-cli`.

Windows works - you just need to follow our Getting Started Installing guides.

https://docs.cypress.io/guides/getting-started/installing-cypress.html

**Comment by Shiv751** [comment]
I have uninstalled and reinstalled it but the same problem again with CLI
tool.
I am  attaching the CLI screencast here
<https://www.screencast.com/t/2tzBBlZZwbUM>


Regards,
Shivam Bharadwaj

**Comment by brian-mann** [comment]
That image only shows the desktop app running, nothing with the CLI.

**Comment by jennifer-shehane** [comment]
From the screenshot, it looks like you've installed Cypress thought direct download, you'll want to install using `npm` within your project and run it in CLI. 

```
npm uninstall -g cypress-cli
cd Users\tvishnoi\frontline
npm install cypress --save-dev
./node_modules/.bin/cypress run
```
