### ISSUE TITLE
Click a button multiple times until it dissapears

### ISSUE THREAD

**Issue by Romiko** [cypress-io/cypress#9295]
Hi,

I have a button that is client side rendered. Sometimes the click will not work as the event from javascript is not bind to the element.

I would like to do this.

    const watcher = Cypress.$('#SubmitCreate')
    var count = 0
    while (!watcher.length) {
        if (count > 50) { break }
        cy.get('#SubmitCreate').click()
        count += 1
        cy.wait(50)
    }

however this code does not work. Cypress does not like   cy.get('#SubmitCreate').click() being called multiple times.

Error I get is

Error: You can only create one Muuri Item per element!
      at new de (https://cdn.jsdelivr.net/npm/muuri@0.9.3/dist/muuri.min.js:21:59332)
      at Ee.add (https://cdn.jsdelivr.net/npm/muuri@0.9.3/dist/muuri.min.js:21:77478)
      at new Ee (https://cdn.jsdelivr.net/npm/muuri@0.9.3/dist/muuri.min.js:21:72422)
      at CheckGalleriesEnded (eval at <anonymous... 

Any ideas on how I can achieve this elegantly?

**Comment by mdunicorn** [comment]
>  Cypress does not like cy.get('#SubmitCreate').click() being called multiple times.

The error comes from "Muuri" library, not from Cypress. How do you know that Cypress does not like calling `click()` multiple times?

Also, you said:

>  Sometimes the click will not work as the event from javascript is not bind to the element.

But you have an error. How do you know that the event from JavaScript is not bound to the element?

**Comment by Romiko** [comment]
Hi, you are correct this is due to Muuri. 

How do you know that the event from JavaScript is not bound to the element?

If I had a cy.wait(500) before clicking the button, it works. So I assume due to this wait that the slow PHP library takes time after the DOM to attach events to the button.

**Comment by Romiko** [comment]
This is how I currently fix the issue.

`    cy.get('#Add_album', { timeout: 30000 }).should('exist').within(() => {
        cy.wait(500)
        cy.get('#SubmitCreateAlbum', { timeout: 30000 }).click()
    })`

**Comment by sainthkh** [comment]
Sorry for the late reply. 

It seems that there's nothing wrong with the given code. It doesn't matter to call `cy.click()` multiple times. I guess it's more related with the time it takes to finish creating Muuri elements. 

Unfortunately, I cannot do more than this because the example is not reproducible. Could you give me a reproducible example to research further?

**Comment by sainthkh** [comment]
Closing because of inactivity. If the problem is still happening, please open a new issue with a reproducible example.
