### ISSUE TITLE
reject is not defined

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#934]
@HugoGiraudel commented on [Mon Nov 20 2017](https://github.com/cypress-io/cypress-webpack-preprocessor/issues/7)

- Operating System: macOS 10.12.6
- Cypress Version: 1.1.0
- Browser Version: n/a

### Is this a Feature or Bug?

A bug.

### Current behavior:

Opening Cypress results in:

```
ReferenceError: reject is not defined
    at EventEmitter.<anonymous> (/Users/hugo/Sites/goldfish/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:81:18)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/Users/hugo/Sites/goldfish/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:23:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Desired behavior:

Not a crash. :)

### How to reproduce:

Set up the following plugin file:

```
const webpack = require('@cypress/webpack-preprocessor')

module.exports = on => {
  on('file:preprocessor', webpack())
}
```

### Additional Info (images, stack traces, etc)

Using `import` instead of `require` fails the same way.

**Comment by brian-mann** [comment]
Released in [`1.1.1`](https://docs.cypress.io/guides/references/changelog.html#1-1-1).
