### ISSUE TITLE
Type error in before() hook

### ISSUE THREAD

**Issue by ksezen59** [cypress-io/cypress#9368]
Hello,

I have written exactly the same code what instructor shows on course video, however, Cypress throws TypeError saying "Cannot set property 'data' of undefined".

Plus, even though my Cypress application version was 3.8.3 for these examples, when I initiated to "npx cypress open" today, it automatically downloaded version 6.0.0 and automatically opens this version(I tried to delete and execute but installed it again.

`TestHook.js`

Note: I did not understand why my quotation marks for code do not cover whole.

```js
/// <reference types="Cypress" />
describe('Test Hooks', () => {

    before(() => {
        cy.fixture('example').then((data) => {
            this.data = data
        })
    })

    it('Test Hook Case', () => {
        cy.visit('https://www.rahulshettyacademy.com/angularpractice/')
        cy.get('input[name="name"]:nth-child(2)').type(this.data.name)
        cy.get('select').select(this.data.gender)
    })
})
```

package.json
```json
{
  "name": "cypress-training",
  "version": "1.0.0",
  "description": "Cypress Training",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cy:run": "cypress run"
  },
  "author": "Kerem Sezen",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^4.3.0",
    "cypress-iframe": "^1.0.1"
  },
  "dependencies": {
    "@types/core-js": "^2.5.4",
    "@types/jasmine": "^3.6.2"
  }
}
```

fixtures.example.json

```json
{
  "name": "Kerem",
  "gender": "Male"
}
```

**Stack trace:**
```
at Context.eval (webpack:///cypress/integration/examples/TestHooks.js:9:13)
From previous event:
    at Context.thenFn (http://localhost:60338/__cypress/runner/cypress_runner.js:155133:24)
    at Context.then (http://localhost:60338/__cypress/runner/cypress_runner.js:155572:22)
    at Context.<anonymous> (http://localhost:60338/__cypress/runner/cypress_runner.js:169999:22)
    at <unknown> (http://localhost:60338/__cypress/runner/cypress_runner.js:169423:16)
From previous event:
    at runCommand (http://localhost:60338/__cypress/runner/cypress_runner.js:169402:9)
    at next (http://localhost:60338/__cypress/runner/cypress_runner.js:169548:15)
    at <unknown> (http://localhost:60338/__cypress/runner/cypress_runner.js:169576:17)
From previous event:
    at next (http://localhost:60338/__cypress/runner/cypress_runner.js:169548:35)
From previous event:
    at Promise.catch.err.name (http://localhost:60338/__cypress/runner/cypress_runner.js:169589:38)
From previous event:
    at run (http://localhost:60338/__cypress/runner/cypress_runner.js:169582:22)
    at $Cy.cy.<computed> [as fixture] (http://localhost:60338/__cypress/runner/cypress_runner.js:170039:12)
    at Context.runnable.fn (http://localhost:60338/__cypress/runner/cypress_runner.js:170263:22)
    at callFn (http://localhost:60338/__cypress/runner/cypress_runner.js:104396:22)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:60338/__cypress/runner/cypress_runner.js:104383:8)
    at <unknown> (http://localhost:60338/__cypress/runner/cypress_runner.js:175798:29)
From previous event:
    at Object.onRunnableRun (http://localhost:60338/__cypress/runner/cypress_runner.js:175786:18)
    at $Cypress.action (http://localhost:60338/__cypress/runner/cypress_runner.js:166429:29)
    at Hook.Runnable.run (http://localhost:60338/__cypress/runner/cypress_runner.js:174172:14)
    at next (http://localhost:60338/__cypress/runner/cypress_runner.js:104898:11)
    at <unknown> (http://localhost:60338/__cypress/runner/cypress_runner.js:104942:6)
    at timeslice (http://localhost:60338/__cypress/runner/cypress_runner.js:98868:28)
```

![image](https://user-images.githubusercontent.com/32410200/100541885-efb39780-3257-11eb-8bd6-f2805c7ba956.png)

**Comment by ksezen59** [comment]
What is the reason of using "function(){}"  instead of "() => {}" when we use "this" in our context?
When I changed the code as seen below, it works.
I had to change both functions in "before" and  in my "it".

```
/// <reference types="Cypress" />

describe('Test Hooks', () => {

    before(function () {

        cy.fixture('example').then((data) => {

            this.data = data

        })

    })

    it('Test Hook Case', function () {

        cy.visit('https://www.rahulshettyacademy.com/angularpractice/')
        cy.get('input[name="name"]:nth-child(2)').type(this.data.name)
        cy.get('select').select(this.data.gender)
    })


})

```

**Comment by jennifer-shehane** [comment]
You'll need to use `function` over arrow functions in this case to get the correct `this` context. I would suggest researching the differences between ES6 arrow function and function to find out the reason this works this way in JavaScript.
