### ISSUE TITLE
Cypress fails to open in Ubuntu (Smoke test failed)

### ISSUE THREAD

**Issue by sporto** [cypress-io/cypress#9431]
Continues from https://github.com/cypress-io/cypress/issues/4624

Using Cypress 6.0.1 I run:

```
npx cypress cache clear
npx cypress install
DEBUG=cypress:cli npx cypress verify
```

Getting

```
  cypress:cli using Cypress executable /home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command failed with exit code 9: /home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126
/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --no-sandbox
/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --smoke-test
/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --ping=126
    at makeError (/home/sebastian/Source/staxio/stax/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/sebastian/Source/staxio/stax/cypress/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 9: /home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126',
  command: '/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=126',
  exitCode: 9,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --no-sandbox\n' +
    '/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --smoke-test\n' +
    '/home/sebastian/.cache/Cypress/6.0.1/Cypress/Cypress: bad option: --ping=126',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +23ms
  ✖  Verifying Cypress can run /home/sebastian/.cache/Cypress/6.0.1/Cypress
    → Cypress Version: 6.0.1
Cypress failed to start.
```

Restarting my computer seems to be the only way to get pass this

**Comment by dzschille** [comment]
I use Ubuntu 20.04 and the verification is successful:

```
$ DEBUG=cypress:cli yarn cypress verify
yarn run v1.22.4
warning package.json: No license field
warning ../../package.json: No license field
$ /home/david/repos/tests/cypress/node_modules/.bin/cypress verify
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli parsed cli options {} +2ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/david/.cache/Cypress/6.0.1/Cypress/Cypress +3ms
  cypress:cli Binary is executable? : true +1ms
  cypress:cli binaryDir is  /home/david/.cache/Cypress/6.0.1/Cypress +1ms
  cypress:cli Reading binary package.json from: /home/david/.cache/Cypress/6.0.1/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 6.0.1 installed in: /home/david/.cache/Cypress/6.0.1/Cypress +9ms
  cypress:cli { verified: true } +13ms
  cypress:cli is Verified ? true +6ms
  cypress:cli force verify +0ms
  cypress:cli running binary verification check 6.0.1 +0ms

  cypress:cli clearing out the verified version +4ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs Xvfb? false +3ms
  cypress:cli spawning, should retry on display problem? true +1ms
  cypress:cli disabling Electron sandbox +0ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/david/.cache/Cypress/6.0.1/Cypress/Cypress +0ms
  cypress:cli smoke test command: /home/david/.cache/Cypress/6.0.1/Cypress/Cypress --no-sandbox --smoke-test --ping=556 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  ⠼  Verifying Cypress can run /home/david/.cache/Cypress/6.0.1/Cypress
  cypress:cli smoke test stdout "It looks like you are running the Cypress binary directly.

This is not the recommended approach, and Cypress may not work correctly.

Please install the 'cypress' NPM package and follow the instructions here:

https://on.cypress.io/installing-cypress
  ⠴  Verifying Cypress can run /home/david/.cache/Cypress/6.0.1/Cypress
  cypress:cli write verified: true +74ms
  cypress:cli could not read binary_state.json file at "/home/david/.cache/Cypress/6.0.1/binary_state.  ✔  Verified Cypress! /home/david/.cache/Cypress/6.0.1/Cypress
Done in 2.26s.
```  
I installed Cypress via Yarn locally in a test directory.

**Comment by sporto** [comment]
To clarify, this error doesn't happen all the time. Usually Cypress opens fine. But then for some reason that I haven't been able to figure out it will stop opening, showing that error above.

At that point clearing the cache, or removing node modules or reinstalling Cypress again or loging out doesn't do anything. Restarting the computer seems the only way to get Cypress to open again.

**Comment by donegjookim** [comment]
[Solution](https://stackoverflow.com/a/70867864)

**Comment by jerrychong25** [comment]
Issue still happening until today

Any solution?
