### ISSUE TITLE
Cypress failing on linux (Debian - 9.6) with error "Syntax error: Unterminated quoted string"

### ISSUE THREAD

**Issue by ilaizra** [cypress-io/cypress#9565]

**Comment by bahmutov** [comment]
Can you please try installing the latest Cypress version which is 6.1.0

**Comment by ilaizra** [comment]
> Can you please try installing the latest Cypress version which is 6.1.0
> […](#)
> Sent from my iPhone
> On Dec 8, 2020, at 08:52, ilaizra ***@***.***> wrote: ﻿ I am running by buildspec.yml on aws pipeline and getting the following error: It looks like this is your first time using Cypress: 4.12.1 1001 | 1002 | [19:40:13] Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [started] 1003 | [19:40:13] Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [failed] 1004 | [19:40:13] → Cypress failed to start. 1005 | 1006 | This is usually caused by a missing library or dependency. 1007 | 1008 | The error below should indicate which dependency is missing. 1009 | 1010 | https://on.cypress.io/required-dependencies 1011 | 1012 | If you are using Docker, we provide containers with all required dependencies installed. 1013 | 1014 | ---------- 1015 | 1016 | /root/.cache/Cypress/4.12.1/Cypress/Cypress: 3: /root/.cache/Cypress/4.12.1/Cypress/Cypress: Syntax error: Unterminated quoted string 1017 | 1018 | ---------- 1019 | 1020 | Platform: linux (Debian - 9.6) 1021 | Cypress Version: 4.12.1 1022 | Cypress failed to start. My buildspec.yml: version: 0.2 phases: pre_build: commands: - echo logging in to Amazon ECR... - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) - echo $IMAGE_TAG build: commands: - echo Build started on date - echo Building the Docker image... - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg AWS_REGION=$AWS_DEFAULT_REGION --no-cache . - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG post_build: commands: - echo Build completed on date - echo Pushing the Docker image... - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG - echo pulling image - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG - docker run $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG My dockerfile which executes a python file in which I run the npx cypress run command: FROM node:10.13 this base image supports installing cypress deps for docker pipeline/build WORKDIR /app COPY . /app ARG AWS_REGION="" ENV AWS_REGION=${AWS_REGION} RUN npm install RUN npm install cypress --save-dev install cypress deps for running in Linux RUN apt-get update && apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb RUN apt-get -y install python3-pip RUN pip3 install setuptools RUN pip3 install boto3 #RUN pip3 show boto3 it doesnt allow to run npm install -g cypress due to permissions error #RUN npm install -g cypress --unsafe-perm --silent ENTRYPOINT ["python3", "./start.py"] My start.py file: #!/usr/bin/env python3 import os import boto3 os.system('npx cypress run --headless --config-file="./cypress/configs/dev.json" -e environment="dev"') There is more functionality in the file, however I am concentrating on getting this cypress run command to run successfully I am thankful for your help. I have tried to change the base image in dockerfile, tried to install cypress globally, but still getting the same error. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ilaizra** [comment]
Hi @bahmutov , thanks for the tip, however still producing same error:

[Container] 2020/12/08 14:38:13 Running command docker run $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
956 | 2020-12-08T14:38:15.551Z cypress:cli NODE_OPTIONS is not set
957 | 2020-12-08T14:38:15.735Z cypress:cli parsed cli options { configFile: './cypress/configs/dev.json', env: 'environment=dev', headless: true }
958 | 2020-12-08T14:38:15.736Z cypress:cli verifying Cypress app
959 | 2020-12-08T14:38:15.737Z cypress:cli checking environment variables
960 | 2020-12-08T14:38:15.742Z cypress:cli checking if executable exists /root/.cache/Cypress/6.1.0/Cypress/Cypress
961 | 2020-12-08T14:38:15.744Z cypress:cli Binary is executable? : true
962 | 2020-12-08T14:38:15.744Z cypress:cli binaryDir is  /root/.cache/Cypress/6.1.0/Cypress
963 | 2020-12-08T14:38:15.745Z cypress:cli Reading binary package.json from: /root/.cache/Cypress/6.1.0/Cypress/resources/app/package.json
964 | 2020-12-08T14:38:15.749Z cypress:cli Found binary version 6.1.0 installed in: /root/.cache/Cypress/6.1.0/Cypress
965 | 2020-12-08T14:38:15.751Z cypress:cli could not read binary_state.json file at "/root/.cache/Cypress/6.1.0/binary_state.json"
966 | 2020-12-08T14:38:15.751Z cypress:cli {}
967 | 2020-12-08T14:38:15.751Z cypress:cli is Verified ? undefined
968 | 2020-12-08T14:38:15.752Z cypress:cli running binary verification check 6.1.0
969 | It looks like this is your first time using Cypress: 6.1.0
970 |  
971 | [14:38:15]  Verifying Cypress can run /root/.cache/Cypress/6.1.0/Cypress [started]
972 | 2020-12-08T14:38:15.760Z cypress:cli clearing out the verified version
973 | 2020-12-08T14:38:15.764Z cypress:cli undefined DISPLAY environment variable
974 | 2020-12-08T14:38:15.764Z cypress:cli Cypress will spawn its own Xvfb
975 | 2020-12-08T14:38:15.764Z cypress:cli needs Xvfb? true
976 | 2020-12-08T14:38:15.764Z cypress:cli Starting Xvfb
977 | 2020-12-08T14:38:15.789Z cypress:cli disabling Electron sandbox
978 | 2020-12-08T14:38:15.789Z cypress:cli running smoke test
979 | 2020-12-08T14:38:15.789Z cypress:cli using Cypress executable /root/.cache/Cypress/6.1.0/Cypress/Cypress
980 | 2020-12-08T14:38:15.789Z cypress:cli smoke test command: /root/.cache/Cypress/6.1.0/Cypress/Cypress --no-sandbox --smoke-test --ping=203
981 | 2020-12-08T14:38:15.790Z cypress:cli smoke test timeout 30000 ms
982 | 2020-12-08T14:38:15.813Z cypress:cli Smoke test failed: { Error: Command failed with exit code 2: /root/.cache/Cypress/6.1.0/Cypress/Cypress --no-sandbox --smoke-test --ping=203
983 | /root/.cache/Cypress/6.1.0/Cypress/Cypress: 1: /root/.cache/Cypress/6.1.0/Cypress/Cypress: Syntax error: ")" unexpected
984 | at makeError (/app/node_modules/execa/lib/error.js:59:11)
985 | at handlePromise (/app/node_modules/execa/index.js:114:26)
986 | at process._tickCallback (internal/process/next_tick.js:68:7)
987 | shortMessage:
988 | 'Command failed with exit code 2: /root/.cache/Cypress/6.1.0/Cypress/Cypress --no-sandbox --smoke-test --ping=203',
989 | command:
990 | '/root/.cache/Cypress/6.1.0/Cypress/Cypress --no-sandbox --smoke-test --ping=203',
991 | exitCode: 2,
992 | signal: undefined,
993 | signalDescription: undefined,
994 | stdout: '',
995 | stderr:
996 | '/root/.cache/Cypress/6.1.0/Cypress/Cypress: 1: /root/.cache/Cypress/6.1.0/Cypress/Cypress: Syntax error: ")" unexpected',
997 | failed: true,
998 | timedOut: false,
999 | isCanceled: false,
1000 | killed: false }
1001 | 2020-12-08T14:38:15.814Z cypress:cli error message: /root/.cache/Cypress/6.1.0/Cypress/Cypress: 1: /root/.cache/Cypress/6.1.0/Cypress/Cypress: Syntax error: ")" unexpected
1002 | 2020-12-08T14:38:15.828Z cypress:cli Stopping Xvfb
1003 | [14:38:15]  Verifying Cypress can run /root/.cache/Cypress/6.1.0/Cypress [failed]
1004 | [14:38:15] → Cypress failed to start.
1005 |  
1006 | This is usually caused by a missing library or dependency.
1007 |  
1008 | The error below should indicate which dependency is missing.
1009 |  
1010 | https://on.cypress.io/required-dependencies
1011 |  
1012 | If you are using Docker, we provide containers with all required dependencies installed.
1013 |  
1014 | ----------
1015 |  
1016 | /root/.cache/Cypress/6.1.0/Cypress/Cypress: 1: /root/.cache/Cypress/6.1.0/Cypress/Cypress: Syntax error: ")" unexpected
1017 |  
1018 | ----------
1019 |  
1020 | Platform: linux (Debian - 9.6)
1021 | Cypress Version: 6.1.0
1022 | Cypress failed to start.
1023 |  
1024 | This is usually caused by a missing library or dependency.
1025 |  
1026 | The error below should indicate which dependency is missing.
1027 |  
1028 | https://on.cypress.io/required-dependencies
1029 |  
1030 | If you are using Docker, we provide containers with all required dependencies installed.
1031 |  
1032 | ----------
1033 |  
1034 | /root/.cache/Cypress/6.1.0/Cypress/Cypress: 1: /root/.cache/Cypress/6.1.0/Cypress/Cypress: Syntax error: ")" unexpected
1035 |  
1036 | ----------
1037 |  
1038 | Platform: linux (Debian - 9.6)
1039 | Cypress Version: 6.1.0
1040 |  
1041 | [Container] 2020/12/08 14:38:16 Phase complete: POST_BUILD State: SUCCEEDED
1042 | [Container] 2020/12/08 14:38:16 Phase context status code:  Message:
1043

**Comment by ilaizra** [comment]
Sorry, close issue by mistake

**Comment by ilaizra** [comment]
.

**Comment by ilaizra** [comment]
> Can you please try installing the latest Cypress version which is 6.1.0
> […](#)
> Sent from my iPhone
> On Dec 8, 2020, at 08:52, ilaizra ***@***.***> wrote: ﻿ I am running by buildspec.yml on aws pipeline and getting the following error: It looks like this is your first time using Cypress: 4.12.1 1001 | 1002 | [19:40:13] Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [started] 1003 | [19:40:13] Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [failed] 1004 | [19:40:13] → Cypress failed to start. 1005 | 1006 | This is usually caused by a missing library or dependency. 1007 | 1008 | The error below should indicate which dependency is missing. 1009 | 1010 | https://on.cypress.io/required-dependencies 1011 | 1012 | If you are using Docker, we provide containers with all required dependencies installed. 1013 | 1014 | ---------- 1015 | 1016 | /root/.cache/Cypress/4.12.1/Cypress/Cypress: 3: /root/.cache/Cypress/4.12.1/Cypress/Cypress: Syntax error: Unterminated quoted string 1017 | 1018 | ---------- 1019 | 1020 | Platform: linux (Debian - 9.6) 1021 | Cypress Version: 4.12.1 1022 | Cypress failed to start. My buildspec.yml: version: 0.2 phases: pre_build: commands: - echo logging in to Amazon ECR... - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) - echo $IMAGE_TAG build: commands: - echo Build started on date - echo Building the Docker image... - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg AWS_REGION=$AWS_DEFAULT_REGION --no-cache . - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG post_build: commands: - echo Build completed on date - echo Pushing the Docker image... - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG - echo pulling image - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG - docker run $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG My dockerfile which executes a python file in which I run the npx cypress run command: FROM node:10.13 this base image supports installing cypress deps for docker pipeline/build WORKDIR /app COPY . /app ARG AWS_REGION="" ENV AWS_REGION=${AWS_REGION} RUN npm install RUN npm install cypress --save-dev install cypress deps for running in Linux RUN apt-get update && apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb RUN apt-get -y install python3-pip RUN pip3 install setuptools RUN pip3 install boto3 #RUN pip3 show boto3 it doesnt allow to run npm install -g cypress due to permissions error #RUN npm install -g cypress --unsafe-perm --silent ENTRYPOINT ["python3", "./start.py"] My start.py file: #!/usr/bin/env python3 import os import boto3 os.system('npx cypress run --headless --config-file="./cypress/configs/dev.json" -e environment="dev"') There is more functionality in the file, however I am concentrating on getting this cypress run command to run successfully I am thankful for your help. I have tried to change the base image in dockerfile, tried to install cypress globally, but still getting the same error. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@bahmutov Can you please delete this comment and the issue as soon as possible, I have made a tremendous mistake by posting this content here. Please do this as soon as possible, I apologize for this
