### ISSUE TITLE
"Error: Callback was already called." when parsing custom webpack.config.js

### ISSUE THREAD

**Issue by benblazke** [cypress-io/cypress#9676]
### Current behavior:

The `cypress-react-unit-test` plugin crashes while running a component test with custom webpack config:

```
**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/websites/coursehero/src/js/cypress/plugins/index.js`)

**Details:** Error: Callback was already called.
    at throwError (/websites/coursehero/src/js/node_modules/neo-async/async.js:16:11)
    at /websites/coursehero/src/js/node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Stack trace:**

Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/websites/coursehero/src/js/cypress/plugins/index.js`)
    at Object.get (/Users/bblazke/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:968:15)
    at EventEmitter.handleError (/Users/bblazke/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:150:20)
    at EventEmitter.emit (events.js:223:5)
    at ChildProcess.<anonymous> (/Users/bblazke/Library/Caches/Cypress/5.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

### Desired behavior:

The component test loads and runs.
-- or --
If there is an error in configuration provide a debuggable message. 

### Test code to reproduce

https://github.com/benblazke/crut-webpack/blob/master/src/cypress/common/school-dropdown.tsx

Note: **This is a private repo. I will gladly provide access to specific users.** 

Output from `DEBUG="*" node_modules/cypress/bin/cypress open" > error-output.log 2>&1`:
https://github.com/benblazke/crut-webpack/blob/master/error-output.log

Also, I noticed that the debug output above contains the following line:
```
No module factory available for dependency type: CssDependency
```
If the component under test does not load any .scss then the plugin loads fine and runs without crashing. The component itself works fine in the app outside of Cypress.

The custom webpack configuration is under /build: https://github.com/benblazke/crut-webpack/tree/master/build 

### Versions

    "cypress": "^5.2.0",
    "cypress-react-unit-test": "^4.11.2",

**Comment by jennifer-shehane** [comment]
Closing as stale. Please update to the latest versions of Cypress and @cypress/react. If this issue is still occuring, please open a new issue with a reproducible example with the latest versions.
