### ISSUE TITLE
Not compatible with react-scripts@next

### ISSUE THREAD

**Issue by larrifax** [cypress-io/cypress#9679]
I'm trying to run component tests using `"react-scripts": "4.0.0-next.98"`, in which the tests fails with the following error:
```
  1) An uncaught error was detected outside of a test:
     ReferenceError: The following error originated from your test code, not from Cypress.

  > $RefreshReg$ is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object../src/Child.js (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:29879:1)
      at __webpack_require__ (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:20:30)
      at Object../src/App.js (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:29545:37)
      at __webpack_require__ (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:20:30)
      at Object../src/resources.cy-spec.js (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:30040:35)
      at __webpack_require__ (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:20:30)
      at Object.0 (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:30483:18)
      at __webpack_require__ (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:20:30)
      at eval (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:84:18)
      at eval (http://localhost:41669/__cypress/tests?p=src/resources.cy-spec.js:87:10)
```

Adding an issue for it as an heads-up that the library might break when react-scripts v4 is released.

**Comment by dmtrKovalenko** [comment]
This was already fixed and released also as a part of `@cypress/react`
